/**
 * Anachronism Quality Rule
 *
 * A question that asks what year a past event happened must not offer a year that
 * has not arrived. Such an option tests whether the player parses the question,
 * not whether they know the answer.
 *
 * This is BLOCKING: an impossible option is a correctness defect, not a style issue.
 *
 * Tense is what separates a bug from a legitimate question. "What year WILL the
 * councilors face re-election?" may offer 2028; "In what year WAS he charged?" may not.
 *
 * Written for wnews-0134, generated by the nightly pipeline on 2026-09-23, which asked
 * what year a man was charged and offered 2027.
 */

import { RuleResult, QuestionInput, Violation } from '../types.js';

/** Does the question ask for a year or a date at all? */
const YEAR_QUESTION =
  /\b(what|which|in what|by what)\s+year\b|\bwhen\s+(did|was|were|will|does|is)\b|\byear\s+(did|was|were|will)\b|\bon what date\b/i;

/**
 * Forward-looking constructions. Checked first — these make future options correct.
 * `projects?/projected` covers reports published in the past that look forward.
 */
const FUTURE_MARKER =
  /\b(will|shall|by\s+what\s+year|plans?\s+to|planned\s+to|is\s+permitted|are\s+permitted|committed\s+to|commits?\s+to|targets?|targeting|projects?|projected|projecting|expects?|expected|scheduled|due\s+to|set\s+to|aims?\s+to|intends?\s+to|deadline)\b/i;

/**
 * A period boundary that lies ahead, e.g. "for a term ending in which year".
 *
 * This is a STRONG exemption: it wins even when a past-tense marker is present,
 * because the past-tense verb describes a different event (being elected) from the
 * one the question actually asks about (when the term ends). Deliberately narrow —
 * it requires "term(s)" immediately followed by an end/expiry word, so
 * "In what year was the council term limit first adopted?" is untouched.
 *
 * Found by running the rule against the live bank: smo-407 was a false positive,
 * while bxl-414 ("When does the current term ... expire?") already passed for having
 * no past-tense verb at all.
 */
const FUTURE_BOUNDARY = /\bterms?\s+(that\s+)?(ending|ends|end|expiring|expires|expire)\b/i;

/** Past-tense constructions. */
const PAST_MARKER =
  /\b(was|were|did|has\s+been|have\s+been|had|became|opened|established|founded|incorporated|chartered|adopted|signed|charged|elected|created|passed|enacted|built|completed|launched|began|started|ended|occurred|happened|died|born)\b/i;

/** A plausible calendar year: 1000-2999, matched anywhere in the option. */
const YEAR_TOKEN = /\b([12]\d{3})\b/g;

/** "2026-27" and "2026/27": expand the abbreviated second half into a full year. */
const YEAR_SPAN = /\b([12]\d{3})\s*[-/–]\s*(\d{2})\b/;

/**
 * Years offered by a single option.
 *
 * A four-digit number is only read as a year because the question asked for one —
 * that gate is applied before this function is reached, and it is what keeps
 * "1200 killed" and "2400 seats" from being misread.
 */
function yearsIn(option: string): number[] {
  const found: number[] = [];

  for (const match of option.matchAll(YEAR_TOKEN)) {
    found.push(Number(match[1]));
  }

  const span = option.match(YEAR_SPAN);
  if (span) {
    const century = Math.floor(Number(span[1]) / 100) * 100;
    found.push(century + Number(span[2]));
  }

  return found;
}

/**
 * BLOCKING RULE: no future year may be offered for an event already past.
 *
 * @param question - Question to evaluate
 * @returns Rule result with any violations found
 */
export function checkAnachronisticYear(question: QuestionInput): RuleResult {
  const violations: Violation[] = [];
  const text = question.text;

  // Gate 1: is this even a year question?
  if (!YEAR_QUESTION.test(text)) {
    return { passed: true, violations: [] };
  }

  // Gate 1a: a question asking when a term ends is forward-looking whatever tense
  // the surrounding verbs use. This is the one exemption that outranks a past marker.
  if (FUTURE_BOUNDARY.test(text)) {
    return { passed: true, violations: [] };
  }

  const hasFuture = FUTURE_MARKER.test(text);
  const hasPast = PAST_MARKER.test(text);

  // Gate 2: forward-looking questions may offer future years.
  //
  // A future marker only exempts the question when no past-tense marker sits
  // alongside it. "What year was the deadline set, before it will take effect?"
  // is a past-tense question that happens to contain "will"; exempting it would
  // let the bug through in the one phrasing most likely to carry both.
  if (hasFuture && !hasPast) {
    return { passed: true, violations: [] };
  }

  // Gate 3: only past-tense questions are constrained.
  if (!hasPast) {
    return { passed: true, violations: [] };
  }

  const currentYear = new Date().getFullYear();
  const offending: number[] = [];

  for (const option of question.options) {
    for (const year of yearsIn(option)) {
      if (year > currentYear) {
        offending.push(year);
      }
    }
  }

  if (offending.length > 0) {
    const unique = [...new Set(offending)].sort((a, b) => a - b);
    violations.push({
      rule: 'anachronistic-year-option',
      severity: 'blocking',
      message:
        'Question asks when a past event happened but offers a year that has not arrived. ' +
        'The option tests comprehension, not knowledge.',
      evidence: `current year ${currentYear}; offered ${unique.join(', ')}`,
    });
  }

  return { passed: violations.length === 0, violations };
}
