-- Migration 1122: Washington County Commission stances - Kathryn Harrington (County Chair) (AUDIT-ONLY)
--
-- Phase 175 (WASH-01). AUDIT-ONLY: NOT registered in the migration ledger;
-- the structural ledger stays at 1120. Evidence-only compass stances (CHAIRS
-- model - value is the discrete position the evidence matches, not a polarity).
-- 100% cited; every stance carries reasoning + source URL(s). Topics with no
-- county-level record are honest blanks (absent). No defaulted values. Judicial
-- topics skipped (non-judicial county official). topic_id resolved LIVE by
-- topic_key (is_live=true) - no hardcoded topic UUIDs.
-- politician_id = 76b00811-8bf8-46c0-bb0c-9867c90fe9d4 (external_id -410100, minted by mig 1120).
-- Cross-verified by two independent research passes; 18 cited stances, 18 honest blanks.

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing'::text, 3, 'Backed the regional affordable-housing bond (800+ units), grew the county Housing Authority to ~1,800 units, funded 500+ new affordable units, and distributes ~3,200 rental-assistance vouchers; supports more housing types for affordability - targeted public subsidy and supply tools rather than rent caps or direct public housing.', ARRAY['https://www.washingtoncountyor.gov/housing/regional-affordable-housing-bond','https://washcodems.org/2022/04/30/kathryn-harrington-washington-county-chair-candidate-interview/']::text[]),
    ('homelessness'::text, 3, 'Ordinance 896 (July 2023, adopted under her chairmanship) permits camping enforcement only after shelter capacity (426 beds) was built and routes people to existing services; she framed it as connecting unsheltered residents with services rather than criminal penalties.', ARRAY['https://www.washingtoncountyor.gov/housing/news/2023/07/18/regulations-public-camping-adopted-board-county-commissioners','https://www.washingtoncountyor.gov/housing/tpm-ordinance-provisions']::text[]),
    ('homelessness-response'::text, 2, 'Explicitly champions a housing-first approach (the county chose it because it is proven and it works) and deployed all Metro Supportive Housing Services resources - transitional housing, access centers, long-term rent assistance, outreach and mental-health wraparound - housing 3,800+ households and cutting unsheltered homelessness ~35%, with enforcement secondary to services.', ARRAY['https://www.washingtoncountyor.gov/housing/news/2024/09/11/supportive-housing-services-shs-fully-committed-and-changing-lives','https://www.washingtoncountyor.gov/housing/news/2024/12/09/washington-county-funds-transitional-housing-sites-and-access-center-shs-resources']::text[]),
    ('residential-zoning'::text, 3, 'Supports allowing more housing types (duplexes/triplexes) and the county implements Oregon HB 2001 middle-housing rules, but she has not advocated eliminating single-family zoning outright - added density near corridors while retaining most residential zones.', ARRAY['https://washcodems.org/2022/04/30/kathryn-harrington-washington-county-chair-candidate-interview/','https://www.washingtoncountyor.gov/lut/planning/middle-housing-hb-2001']::text[]),
    ('transportation-priorities'::text, 2, 'A 12-year Metro Councilor and JPACT member with a multimodal record; MSTIP under her board funded ~150 miles of bike lanes and sidewalks, a 2024 active-transportation grant (protected bike lanes, safe routes to transit), and $150M in bonds preserving multimodal MSTIP projects - investing in roads and multimodal together.', ARRAY['https://www.washingtoncountyor.gov/lut/mstip','https://www.washingtoncountyor.gov/lut/news/2024/10/31/planning-grant-fund-washington-county-active-transportation-efforts']::text[]),
    ('public-safety-approach'::text, 3, 'Referred and celebrated the 2025 public-safety levy funding jail operations and prosecution alongside Mental Health Response Teams pairing deputies with clinicians, and opened the Hillsboro Recovery Center - maintaining public-safety funding while adding crisis/behavioral-health response.', ARRAY['https://www.washingtoncountyor.gov/cao/news/chair-harrington-issues-levy-results-statement','https://www.washingtoncountyor.gov/cao/2025-public-safety-levy-information']::text[]),
    ('jail-capacity'::text, 3, 'The 2025 levy she backed funds operations within the existing ~572-bed jail (no design-capacity expansion) and adds Mental Health Response Teams as alternatives for crisis calls; she pressed for shelter/youth-shelter funding alongside jail operations - maintaining capacity with treatment alternatives, not expansion.', ARRAY['https://www.washingtoncountyor.gov/cao/2025-public-safety-levy-information','https://www.washingtoncountyor.gov/sheriff/news/2025/11/05/washington-county-voters-show-strong-support-public-safety-levy']::text[]),
    ('local-immigration'::text, 2, 'Washington County does not honor ICE detainers absent a judicial warrant (Oregon Sanctuary Promise Act), set aside $200,000 for ICE-impacted residents, and the Board unanimously declared an emergency over ICE activity she called horrific - court-ordered compliance only, not proactive enforcement.', ARRAY['https://www.opb.org/article/2025/11/05/washington-county-declares-emergency-over-increased-ice-activity/','https://www.washingtoncountyor.gov/cao/sanctuary-promise-and-immigration-support']::text[]),
    ('immigration'::text, 2, 'The county keeps program access unconditioned on immigration status and she publicly condemned the federal removal of Temporary Protected Status as horrific - a posture keeping public services open to residents regardless of status.', ARRAY['https://www.opb.org/article/2025/11/05/washington-county-declares-emergency-over-increased-ice-activity/']::text[]),
    ('civil-rights'::text, 2, 'Adopted equity as a county core value, issued statements framing anti-Asian violence and systemic racism as priorities, and chartered the Advisory Council on Racial Equity (2022) - actively strengthening civil-rights work and addressing systemic discrimination.', ARRAY['https://www.washingtoncountyor.gov/bcc/news/2022/09/23/board-adopts-charter-advisory-council-racial-equity','https://washcodems.org/2022/04/30/kathryn-harrington-washington-county-chair-candidate-interview/']::text[]),
    ('economic-development'::text, 3, 'Launched a county Economic Development Program (2021) investing $2.5M+ ARPA funds in workforce and small-business support with equity conditions, partnering with nine community organizations targeting BIPOC, women, veterans and low-income residents - targeted incentives with community-benefit requirements.', ARRAY['https://www.washingtoncountyor.gov/cao/news/washington-county-recognized-nationwide-cohort-boost-high-quality-jobs','https://washingtoncountyor.gov/cao/news/washington-county-collaborate-community-organizations-robust-workforce-development']::text[]),
    ('climate-change'::text, 3, 'The county matches 100% of its electricity via PGE Green Future solar, installed facility solar arrays, and after the 2021 heat dome she opened cooling centers, made 211 a 24/7 service, and backed right-to-cool rules - clean-energy investment and resilience, not a climate emergency or fossil-fuel ban.', ARRAY['https://washcodems.org/2022/04/30/kathryn-harrington-washington-county-chair-candidate-interview/','https://www.washingtoncountyor.gov/sustainability/energy-conservation']::text[]),
    ('taxes'::text, 2, 'Placed and publicly supported 2025 public-safety and library levies and governed through five years of property-tax-compression gaps, saying the constrained system disadvantages the county - protecting services through targeted revenue increases rather than cutting taxes.', ARRAY['https://www.washingtoncountyor.gov/cao/news/chair-harrington-issues-levy-results-statement','https://www.washingtoncountyor.gov/bcc/news/2024/06/24/washington-county-board-adopts-budget-preserving-basic-county-services-despite-reductions-funds']::text[]),
    ('healthcare'::text, 3, 'The county runs six school-based health centers and its Health and Human Services department contracts with safety-net partners (Virginia Garcia, Neighborhood Health Center) focused on low-income and uninsured residents - expanding low-income/behavioral-health care while broader coverage stays with existing systems.', ARRAY['https://www.washingtoncountyor.gov/hhs','https://www.washingtoncountyor.gov/public-health']::text[]),
    ('childcare'::text, 3, 'Funded a 2023 ECONorthwest childcare study (ARPA) finding capacity must nearly double by 2030 and pursued targeted solutions - workforce training, provider support, navigation - aimed at lower-income families, not universal public childcare.', ARRAY['https://www.washingtoncountyor.gov/hhs/news/2023/12/13/washington-county-study-reveals-extent-child-care-difficulties-and-possible-solutions','https://www.washingtoncountyor.gov/hhs/child-care-study']::text[]),
    ('data-centers'::text, 3, 'Did not seek a moratorium but documented that county taxpayers bear ~$400K/year administering enterprise-zone breaks worth ~$85M to data centers and pressed for cost accountability and state support - allowing data centers with cost/impact conditions.', ARRAY['https://www.govtech.com/policy/oregon-counties-want-help-with-data-center-tax-breaks']::text[]),
    ('local-environment'::text, 2, 'Endorsed by the Oregon League of Conservation Voters (2018) and Sierra Club (2022); the county enforces Exclusive Farm Use zoning and farmland preservation and partners on Tualatin River watershed conservation - a record of prioritizing environmental protection.', ARRAY['https://www.olcv.org/2018-endorsements/','https://www.sierraclub.org/oregon/2022-political-endorsements']::text[]),
    ('growth-and-development'::text, 3, 'As a Metro Councilor she supported the 2018 urban growth boundary expansion (~9,200 homes) tied to urban/rural reserves planning, and the county MSTIP invests in infrastructure ahead of growth - proactive infrastructure-led planning.', ARRAY['https://washcodems.org/2022/04/30/kathryn-harrington-washington-county-chair-candidate-interview/','https://www.washingtoncountyor.gov/lut/mstip']::text[])
),
t AS (
  SELECT s.*, ct.id AS topic_id
  FROM s JOIN inform.compass_topics ct
    ON ct.topic_key = s.topic_key AND ct.is_live = true
),
ins_ans AS (
  INSERT INTO inform.politician_answers (politician_id, topic_id, value)
  SELECT '76b00811-8bf8-46c0-bb0c-9867c90fe9d4'::uuid, topic_id, val FROM t
  ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value
  RETURNING 1
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
  SELECT '76b00811-8bf8-46c0-bb0c-9867c90fe9d4'::uuid, topic_id, reasoning, sources FROM t
  ON CONFLICT (politician_id, topic_id) DO UPDATE
    SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
