-- Migration 1125: Washington County Commission stances - Jason Snider (District 3) (AUDIT-ONLY)
--
-- Phase 175 (WASH-01). AUDIT-ONLY: NOT registered in the migration ledger.
-- Evidence-only compass stances (CHAIRS model). 100% cited; reasoning + sources
-- per stance. Honest blanks where no record. No defaulted values. Judicial topics
-- skipped. topic_id resolved LIVE by topic_key (is_live=true). Includes his
-- documented Tigard mayoral/council record as evidence.
-- politician_id = a98aeea6-c7cf-475c-96f2-100119c9037a (external_id -410112, minted by mig 1120).
-- 13 cited stances.

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing'::text, 3, 'As Tigard mayor Snider facilitated affordable-housing projects and led preservation of the Woodspring Apartments (later bought by the county for $48.5M to hold rents below market); his platform calls for form-based codes in town centers, aggressively implementing middle-housing reforms, and public resources for regulated affordable housing - targeted subsidy and permit-streamlining, not public construction or pure deregulation.', ARRAY['https://beavertonvalleytimes.com/2024/04/30/candidate-qa-washington-county-commission-candidates-talk-key-policy-issues/','https://tigardlife.com/featured/former-mayor-snider-reflects-on-decade-in-public-office-as-he-passes-the-mantle/']::text[]),
    ('residential-zoning'::text, 4, 'Snider calls for aggressively implementing middle-housing reforms, focusing density in town centers, and using form-based codes to streamline approvals; under his mayorship Tigard adopted Ordinance 22-06 cutting residential zones from 8 to 5 and implementing statewide middle-housing mandates - allowing multifamily broadly by right rather than community-by-community rezoning.', ARRAY['https://beavertonvalleytimes.com/2024/04/30/candidate-qa-washington-county-commission-candidates-talk-key-policy-issues/','https://tigardlife.com/local-news/former-tigard-mayor-jason-snider-announces-candidacy-for-county-commissioner/']::text[]),
    ('homelessness'::text, 3, 'As Tigard mayor Snider said area communities are not doing enough and partnered with Just Compassion to fund transitional shelter; as commissioner he declined Portland''s $6M request citing unmet needs in his own district - supporting enforcement coupled with local shelter/services capacity, not open-camping rights nor a pure ban.', ARRAY['https://tigardlife.com/featured/an-interview-with-tigard-mayor-jason-snider/','https://beavertonvalleytimes.com/2026/04/08/washington-county-declines-portland-mayors-6m-request-for-homeless-funding/']::text[]),
    ('homelessness-response'::text, 3, 'Snider funded transitional shelter via Just Compassion, expanded outreach, backed the Metro SHS levy, and as commissioner invests in county homeless services - combining outreach and shelter investment with enforcement of reasonable public-space rules rather than pure housing-first or enforcement-led response.', ARRAY['https://tigardlife.com/featured/an-interview-with-tigard-mayor-jason-snider/','https://beavertonvalleytimes.com/2026/04/08/washington-county-declines-portland-mayors-6m-request-for-homeless-funding/']::text[]),
    ('transportation-priorities'::text, 3, 'Snider supports continued MSTIP multimodal investment and backed SW Corridor light rail in principle while prioritizing road capacity (opposing Barbur Boulevard lane reductions); his platform has the county committee pick multimodal priorities where density supports it - maintaining roads while selectively adding transit/pedestrian improvements.', ARRAY['https://beavertonvalleytimes.com/2024/04/30/candidate-qa-washington-county-commission-candidates-talk-key-policy-issues/','https://www.washingtoncountyor.gov/bcc/news/2025/01/09/county-officials-sworn-2025']::text[]),
    ('public-safety-approach'::text, 3, 'As Tigard mayor Snider passed the city''s first public-safety levy adding eight officers while funding mental-health and crisis-intervention training for all officers and forming a 15-member Public Safety Advisory Board after George Floyd - keeping public-safety funding while adding crisis-response capacity, not defunding nor police-budget-above-all.', ARRAY['https://tigardchamber.org/tigard-chamber-endorsement-of-jason-snider-for-washington-county-commissioner-district-3/','https://tigardlife.com/featured/former-mayor-snider-reflects-on-decade-in-public-office-as-he-passes-the-mantle/']::text[]),
    ('growth-and-development'::text, 3, 'Snider advocates proactive infrastructure investment - supporting MSTIP bond issuance to fund transportation ahead of growth and pairing middle-housing reforms with form-based codes in town centers - planning infrastructure before building rather than growth limits or removing all barriers.', ARRAY['https://beavertonvalleytimes.com/2024/04/30/candidate-qa-washington-county-commission-candidates-talk-key-policy-issues/','https://citizenportal.ai/articles/6646388/Washington-County/Oregon/Washington-County-reviews-MSTIP-investments-and-launches-funding-strategy-work-amid-budget-pressure']::text[]),
    ('local-immigration'::text, 2, 'In November 2025 Snider co-brought the county emergency declaration after increased ICE arrests, calling the activity designed to instill fear and supporting $250,000 in contingency funds for impacted immigrant/refugee communities, while acknowledging the county must follow federal law and favoring support of community organizations - complying only with court-ordered detainers and protecting residents.', ARRAY['https://www.opb.org/article/2025/11/05/washington-county-emergency-increased-ice-activity/','https://www.kgw.com/article/news/politics/immigration-news/county-leaders-repond-ice-detainments/283-704ce267-4354-4bc6-be1f-125a120eaeb3']::text[]),
    ('climate-change'::text, 3, 'As Tigard mayor Snider set a city carbon-neutrality goal by 2035, formed an implementation workgroup, pushed fleet electrification, and credited the youth Climate Champions - a gradual, implementation-focused clean-energy transition rather than an emergency ban or market-only approach.', ARRAY['https://tigardlife.com/featured/an-interview-with-tigard-mayor-jason-snider/','https://tigardlife.com/featured/former-mayor-snider-reflects-on-decade-in-public-office-as-he-passes-the-mantle/']::text[]),
    ('economic-development'::text, 3, 'Snider''s platform stresses leveraging the county''s existing high-tech manufacturing ecosystem with targeted infrastructure and workforce investments to attract traded-sector jobs - targeted, industry-specific investment with workforce development rather than maximum incentives for any large employer.', ARRAY['https://beavertonvalleytimes.com/2024/04/30/candidate-qa-washington-county-commission-candidates-talk-key-policy-issues/']::text[]),
    ('local-environment'::text, 3, 'Snider serves on the Clean Water Services Board and publicly pushed for improved financial governance there (declining CWS travel/gifts); his housing approach pairs density with form-based codes that carry design/environmental standards - consistent standards with reasonable flexibility, neither full-offset mandates nor stripping local rules.', ARRAY['https://washingtoncounty.civicweb.net/portal/members.aspx?id=10','https://www.kgw.com/article/news/local/the-story/washington-county-audit-sewer-agency-investigation-lavish-spending-clean-water-services/283-8cad6b52-2658-4080-b5cf-f9fb526444dc']::text[]),
    ('civil-rights'::text, 2, 'Snider''s campaign statement says differences in race, gender identity, culture and background affect people''s ability to prosper and calls for fair and just policies to increase equity, and he expanded diverse community engagement via the Public Safety Advisory Board after George Floyd - actively strengthening civil-rights work and acknowledging systemic discrimination.', ARRAY['https://washingtoncountyor.gov/elections/documents/county-commissioner-district-3-jason-snider/download?inline=','https://tigardlife.com/featured/former-mayor-snider-reflects-on-decade-in-public-office-as-he-passes-the-mantle/']::text[]),
    ('childcare'::text, 3, 'Snider identified youth mental health among the county''s most impactful challenges and proposed coordinating regional behavioral-health investments across cities and school districts - targeted subsidies/coordination for high-need youth services rather than universal public childcare or a pure market approach.', ARRAY['https://beavertonvalleytimes.com/2024/04/30/candidate-qa-washington-county-commission-candidates-talk-key-policy-issues/']::text[])
),
t AS (
  SELECT s.*, ct.id AS topic_id
  FROM s JOIN inform.compass_topics ct
    ON ct.topic_key = s.topic_key AND ct.is_live = true
),
ins_ans AS (
  INSERT INTO inform.politician_answers (politician_id, topic_id, value)
  SELECT 'a98aeea6-c7cf-475c-96f2-100119c9037a'::uuid, topic_id, val FROM t
  ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value
  RETURNING 1
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
  SELECT 'a98aeea6-c7cf-475c-96f2-100119c9037a'::uuid, topic_id, reasoning, sources FROM t
  ON CONFLICT (politician_id, topic_id) DO UPDATE
    SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
