-- Migration 1133: Lacey Beaty (Mayor) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 12 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 2, 'Beaty called housing a ''fundamental human right'' in her 2023 State of the City address. She secured $9 million from the Metro Affordable Housing Bond for the Amity Orchards complex (164 affordable units), championed $850,000 in ARPA funds for affordable housing, and led Beaverton to be named a global finalist in the 2025 Bloomberg Mayors Challenge for an innovative cooperative housing model. As a councilor she worked on the regional housing coalition to build more affordable housing. This consistent record of publicly funding new affordable housing and requiring affordability in developments maps to Chair 2.', ARRAY['https://beavertonvalleytimes.com/2026/05/30/beaverton-metro-cuts-the-ribbon-on-multigenerational-affordable-housing-complex-amity-orchards/', 'https://beavertonvalleytimes.com/2025/07/20/beaverton-named-global-finalist-in-bloomberg-mayors-challenge-for-innovative-housing-plan/', 'https://www.governing.com/urban/oregon-city-explores-new-ways-to-develop-senior-housing']::text[]),
    ('homelessness', 3, 'Beaverton enacted a camping ordinance (effective July 2023) that allows camping in public right-of-way 9pm–7am with a balanced enforcement approach: 169 warnings, minimal arrests (1 booked, 15 cited), with officers providing trash bags and time rather than leading with citations. The city enforced only after the shelter (60-bed year-round facility) opened. Mayor Beaty described the city''s strategy as ''a balanced strategy that supports those in need while ensuring the safety and integrity of our community.'' This matches Chair 3 (enforcement only when adequate shelter is available, citations divert to services).', ARRAY['https://youroregonnews.com/2024/02/21/beaverton-city-council-looks-back-at-six-months-of-new-camping-ordinances/', 'https://www.kgw.com/article/news/local/homeless/beaverton-mayor-response-man-accidentally-sets-himself-on-fire/283-129d5289-0dbd-4dd5-81d8-c186df28ff44', 'https://beavertonoregon.gov/1499/Beaverton-Homelessness-Response']::text[]),
    ('homelessness-response', 2, 'Beaty built Beaverton''s first year-round, 24/7 shelter (60 beds, 3 meals/day, showers, laundry, clinic, pet-friendly, trauma-informed design) at no direct cost to the city by assembling grants and partnerships. The shelter provides housing navigation case managers to help guests transition to stable housing. Beaty framed homelessness as requiring proactive shelter and service investment, calling housing a ''fundamental human right.'' Enforcement (the camping ordinance) followed shelter capacity. This matches Chair 2 (expand shelter capacity and services as primary strategy; use enforcement only after services are offered).', ARRAY['https://www.governing.com/urban/oregon-mayor-builds-homeless-shelter-at-no-cost-to-the-city', 'https://www.oregonmetro.gov/stories/beaverton-opens-its-first-year-round-homeless-shelter', 'https://beavertonvalleytimes.com/2024/11/21/a-beacon-of-hope-beavertons-first-permanent-homeless-shelter-is-complete/']::text[]),
    ('transportation-priorities', 1, 'Beaty championed the Beaverton Downtown Loop — a 1.3-mile downtown circuit with protected bike lanes, wider sidewalks, pedestrian crossing treatments, and enhanced bus stops — securing a $2 million federal DOT grant. She approved Resolution No. 4838 supporting climate-friendly transportation, developed a full Active Transportation Plan, and endorsed bus rapid transit as the locally preferred alternative for the TV Highway corridor. She testified against state transportation-bill cuts that would reduce city funding for these projects. Transportation investment is explicitly framed around safety, equity, and climate. This maps to Chair 1 (prioritize pedestrian infrastructure, cycling networks, and public transit).', ARRAY['https://bonamici.house.gov/media/press-releases/bonamici-wyden-merkley-announce-funding-beaverton-road-safety-improvements', 'https://www.youtube.com/watch?v=WXlzylLa-nM', 'https://beavertonoregon.gov/410/Active-Transportation-Plan', 'https://medium.com/usmayors/meet-the-mayor-lacey-beaty-5ad15bc11951']::text[]),
    ('climate-change', 3, 'Beaty established the Beaverton Climate Action Task Force (Resolution No. 2712), presided over adoption of a Climate Action Plan targeting net-zero community emissions by 2050 and city-government carbon neutrality by 2030, created a city sustainability department, and invested in renewables (hydropower on the water system). In her 2020 candidate interview she called for state-level cap-and-invest policy. She called the climate crisis one of her top three priorities. This is an active, multi-pronged clean-energy investment posture that maps to Chair 3 (invest in clean energy while gradually reducing reliance on fossil fuels).', ARRAY['https://www.buildreuse.org/community-highlights/beaverton-or-climate-action-plan', 'https://blog.energytrust.org/city-of-beaverton-and-energy-trust-celebrate-hydropower-success/', 'https://washcodems.org/2020/04/26/lacey-beaty-candidate-interview/', 'https://www.climatesolutions.org/beaverton-or']::text[]),
    ('local-environment', 3, 'Beaty stated in August 2023 that ''while growth is important, this should be balanced with sustainability,'' specifically citing the city''s Purple Pipe reclaimed-water system as a sustainability infrastructure investment enabling growth. The city applies environmental standards to development (composting, EV infrastructure, tree canopy lists) while still actively pursuing growth and development. This balanced stance — consistent environmental standards with reasonable implementation flexibility — maps to Chair 3.', ARRAY['https://blog.energytrust.org/with-small-steps-beaverton-is-leading-the-way-in-climate-action/', 'https://medium.com/usmayors/meet-the-mayor-lacey-beaty-5ad15bc11951']::text[]),
    ('public-safety-approach', 3, 'Beaty explicitly called the #8CantWait use-of-force reforms the ''bare minimum'' and advocated police reform as a councilor. The city maintained a Mental Health Resource Team (police-clinician co-responder model). However, she did not support defunding: Beaverton increased its police budget under her watch and budget cuts in 2025 were fiscal-driven (structural deficit), not ideological. She supported keeping current public safety funding while adding mental health crisis response capacity. This maps to Chair 3 (keep current public safety funding while adding crisis response teams).', ARRAY['https://www.beavertonvalleytimes.com/news/beavertons-beaty-isnt-backing-away-from-police-reform/article_5c1d7373-ec1e-5e71-802b-6cac124c7585.html', 'https://beavertonpolice.org/198/Mental-Health-Response-Team', 'https://katu.com/news/local/beaverton-faces-107-million-budget-shortfall-plans-cuts-to-police-and-public-works-library-street-repair-resident-portland-oregon-washington-county-finances-economy-consumer']::text[]),
    ('civil-rights', 2, 'Beaty signed the U.S. Conference of Mayors'' Compact on Racial Equity (January 2022), which explicitly affirms that systemic discrimination exists and commits signatories to work to eliminate inequities in housing, wages, education, and criminal justice. Her administration developed a Downtown Equity Strategy targeting a Central Beaverton neighborhood historically harmed by redlining, and maintained an Office of Equity & Inclusion. This record of affirming systemic discrimination and taking governmental action to address it maps to Chair 2 (strengthen civil rights enforcement and address systemic discrimination).', ARRAY['https://www.usmayors.org/wp-content/uploads/2022/01/COMPACT-ON-RACIAL-EQUITY-011922.docx.pdf', 'https://beavertonoregon.gov/385/Cultural-Inclusion', 'https://medium.com/usmayors/meet-the-mayor-lacey-beaty-5ad15bc11951']::text[]),
    ('local-immigration', 1, 'Beaverton''s city council approved a strengthened sanctuary city ordinance on January 20, 2026, adding language that prohibits city employees from providing immigration-status information to federal agencies for immigration enforcement purposes (except where legally required) and banning use of city personnel to arrest or detain anyone for immigration enforcement. Beaty supported the ordinance and stated that residents would live in fear if local law enforcement targeted them for deportation. The council also considered amending city code to allow officers to investigate and cite ICE agents for local law violations. This matches Chair 1 (refuse ICE detainers; prohibit city employees from sharing immigration status information with federal agencies).', ARRAY['https://beavertonvalleytimes.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/', 'https://katu.com/news/local/beaverton-mayor-lacey-beaty-councilors-nadia-hasan-kevin-teater-considers-having-officers-investigate-federal-immigration-ice-agents', 'https://www.koin.com/news/portland-beaverton-to-remain-sanctuary-cities/']::text[]),
    ('economic-development', 3, 'Beaverton under Beaty maintains formal tax-incentive programs for development in specific areas of the city (property tax incentives for targeted zones). Beaty cited a ''laser focus'' on restaurant and business attraction strategies and pointed to near-zero vacancy rates as evidence of success. The city supports small businesses while also using targeted tax abatements in designated areas. This targeted-incentive model — neither refusing all corporate incentives nor offering blanket maximum subsidies — maps to Chair 3 (targeted incentives for specific industries with community benefit agreements).', ARRAY['https://www.beavertonoregon.gov/256/City-Incentives', 'https://www.koin.com/local/washington-county/laser-focus-helps-beaverton-boom-outpace-portland/']::text[]),
    ('growth-and-development', 3, 'Beaty described Beaverton as being ''in a time of immense growth'' and said ''while growth is important, this should be balanced with sustainability.'' She invested proactively in the Purple Pipe reclaimed-water infrastructure to support future growth, championed sidewalk and transportation infrastructure investments ahead of demand, and supported annexations. This is neither a growth-limits stance nor pure deregulation, but proactive infrastructure investment to support responsible expansion — Chair 3.', ARRAY['https://medium.com/usmayors/meet-the-mayor-lacey-beaty-5ad15bc11951', 'https://en.wikipedia.org/wiki/Lacey_Beaty']::text[]),
    ('taxes', 2, 'Beaty raised Beaverton''s property tax rate from $4.23 to $4.62 per $1,000 assessed value in 2023 to address structural budget pressures. She explicitly stated that if expenses continue to outpace revenues, property tax levies will be necessary in the future — signaling willingness to raise taxes to fund public services rather than cut services. She oversaw budget cuts in 2025 as a fiscal necessity, not an ideological preference for smaller government. This willingness to raise taxes on property owners to fund existing and expanded services maps to Chair 2 (moderately raise taxes to fund existing services).', ARRAY['https://beavertonvalleytimes.com/2023/06/16/beaverton-raises-property-taxes-using-decades-old-oregon-laws/', 'https://katu.com/news/local/beaverton-faces-107-million-budget-shortfall-plans-cuts-to-police-and-public-works-library-street-repair-resident-portland-oregon-washington-county-finances-economy-consumer']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '6f4e9c86-1c23-4569-ad1a-7614463420f1'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 2, 'Beaty called housing a ''fundamental human right'' in her 2023 State of the City address. She secured $9 million from the Metro Affordable Housing Bond for the Amity Orchards complex (164 affordable units), championed $850,000 in ARPA funds for affordable housing, and led Beaverton to be named a global finalist in the 2025 Bloomberg Mayors Challenge for an innovative cooperative housing model. As a councilor she worked on the regional housing coalition to build more affordable housing. This consistent record of publicly funding new affordable housing and requiring affordability in developments maps to Chair 2.', ARRAY['https://beavertonvalleytimes.com/2026/05/30/beaverton-metro-cuts-the-ribbon-on-multigenerational-affordable-housing-complex-amity-orchards/', 'https://beavertonvalleytimes.com/2025/07/20/beaverton-named-global-finalist-in-bloomberg-mayors-challenge-for-innovative-housing-plan/', 'https://www.governing.com/urban/oregon-city-explores-new-ways-to-develop-senior-housing']::text[]),
    ('homelessness', 3, 'Beaverton enacted a camping ordinance (effective July 2023) that allows camping in public right-of-way 9pm–7am with a balanced enforcement approach: 169 warnings, minimal arrests (1 booked, 15 cited), with officers providing trash bags and time rather than leading with citations. The city enforced only after the shelter (60-bed year-round facility) opened. Mayor Beaty described the city''s strategy as ''a balanced strategy that supports those in need while ensuring the safety and integrity of our community.'' This matches Chair 3 (enforcement only when adequate shelter is available, citations divert to services).', ARRAY['https://youroregonnews.com/2024/02/21/beaverton-city-council-looks-back-at-six-months-of-new-camping-ordinances/', 'https://www.kgw.com/article/news/local/homeless/beaverton-mayor-response-man-accidentally-sets-himself-on-fire/283-129d5289-0dbd-4dd5-81d8-c186df28ff44', 'https://beavertonoregon.gov/1499/Beaverton-Homelessness-Response']::text[]),
    ('homelessness-response', 2, 'Beaty built Beaverton''s first year-round, 24/7 shelter (60 beds, 3 meals/day, showers, laundry, clinic, pet-friendly, trauma-informed design) at no direct cost to the city by assembling grants and partnerships. The shelter provides housing navigation case managers to help guests transition to stable housing. Beaty framed homelessness as requiring proactive shelter and service investment, calling housing a ''fundamental human right.'' Enforcement (the camping ordinance) followed shelter capacity. This matches Chair 2 (expand shelter capacity and services as primary strategy; use enforcement only after services are offered).', ARRAY['https://www.governing.com/urban/oregon-mayor-builds-homeless-shelter-at-no-cost-to-the-city', 'https://www.oregonmetro.gov/stories/beaverton-opens-its-first-year-round-homeless-shelter', 'https://beavertonvalleytimes.com/2024/11/21/a-beacon-of-hope-beavertons-first-permanent-homeless-shelter-is-complete/']::text[]),
    ('transportation-priorities', 1, 'Beaty championed the Beaverton Downtown Loop — a 1.3-mile downtown circuit with protected bike lanes, wider sidewalks, pedestrian crossing treatments, and enhanced bus stops — securing a $2 million federal DOT grant. She approved Resolution No. 4838 supporting climate-friendly transportation, developed a full Active Transportation Plan, and endorsed bus rapid transit as the locally preferred alternative for the TV Highway corridor. She testified against state transportation-bill cuts that would reduce city funding for these projects. Transportation investment is explicitly framed around safety, equity, and climate. This maps to Chair 1 (prioritize pedestrian infrastructure, cycling networks, and public transit).', ARRAY['https://bonamici.house.gov/media/press-releases/bonamici-wyden-merkley-announce-funding-beaverton-road-safety-improvements', 'https://www.youtube.com/watch?v=WXlzylLa-nM', 'https://beavertonoregon.gov/410/Active-Transportation-Plan', 'https://medium.com/usmayors/meet-the-mayor-lacey-beaty-5ad15bc11951']::text[]),
    ('climate-change', 3, 'Beaty established the Beaverton Climate Action Task Force (Resolution No. 2712), presided over adoption of a Climate Action Plan targeting net-zero community emissions by 2050 and city-government carbon neutrality by 2030, created a city sustainability department, and invested in renewables (hydropower on the water system). In her 2020 candidate interview she called for state-level cap-and-invest policy. She called the climate crisis one of her top three priorities. This is an active, multi-pronged clean-energy investment posture that maps to Chair 3 (invest in clean energy while gradually reducing reliance on fossil fuels).', ARRAY['https://www.buildreuse.org/community-highlights/beaverton-or-climate-action-plan', 'https://blog.energytrust.org/city-of-beaverton-and-energy-trust-celebrate-hydropower-success/', 'https://washcodems.org/2020/04/26/lacey-beaty-candidate-interview/', 'https://www.climatesolutions.org/beaverton-or']::text[]),
    ('local-environment', 3, 'Beaty stated in August 2023 that ''while growth is important, this should be balanced with sustainability,'' specifically citing the city''s Purple Pipe reclaimed-water system as a sustainability infrastructure investment enabling growth. The city applies environmental standards to development (composting, EV infrastructure, tree canopy lists) while still actively pursuing growth and development. This balanced stance — consistent environmental standards with reasonable implementation flexibility — maps to Chair 3.', ARRAY['https://blog.energytrust.org/with-small-steps-beaverton-is-leading-the-way-in-climate-action/', 'https://medium.com/usmayors/meet-the-mayor-lacey-beaty-5ad15bc11951']::text[]),
    ('public-safety-approach', 3, 'Beaty explicitly called the #8CantWait use-of-force reforms the ''bare minimum'' and advocated police reform as a councilor. The city maintained a Mental Health Resource Team (police-clinician co-responder model). However, she did not support defunding: Beaverton increased its police budget under her watch and budget cuts in 2025 were fiscal-driven (structural deficit), not ideological. She supported keeping current public safety funding while adding mental health crisis response capacity. This maps to Chair 3 (keep current public safety funding while adding crisis response teams).', ARRAY['https://www.beavertonvalleytimes.com/news/beavertons-beaty-isnt-backing-away-from-police-reform/article_5c1d7373-ec1e-5e71-802b-6cac124c7585.html', 'https://beavertonpolice.org/198/Mental-Health-Response-Team', 'https://katu.com/news/local/beaverton-faces-107-million-budget-shortfall-plans-cuts-to-police-and-public-works-library-street-repair-resident-portland-oregon-washington-county-finances-economy-consumer']::text[]),
    ('civil-rights', 2, 'Beaty signed the U.S. Conference of Mayors'' Compact on Racial Equity (January 2022), which explicitly affirms that systemic discrimination exists and commits signatories to work to eliminate inequities in housing, wages, education, and criminal justice. Her administration developed a Downtown Equity Strategy targeting a Central Beaverton neighborhood historically harmed by redlining, and maintained an Office of Equity & Inclusion. This record of affirming systemic discrimination and taking governmental action to address it maps to Chair 2 (strengthen civil rights enforcement and address systemic discrimination).', ARRAY['https://www.usmayors.org/wp-content/uploads/2022/01/COMPACT-ON-RACIAL-EQUITY-011922.docx.pdf', 'https://beavertonoregon.gov/385/Cultural-Inclusion', 'https://medium.com/usmayors/meet-the-mayor-lacey-beaty-5ad15bc11951']::text[]),
    ('local-immigration', 1, 'Beaverton''s city council approved a strengthened sanctuary city ordinance on January 20, 2026, adding language that prohibits city employees from providing immigration-status information to federal agencies for immigration enforcement purposes (except where legally required) and banning use of city personnel to arrest or detain anyone for immigration enforcement. Beaty supported the ordinance and stated that residents would live in fear if local law enforcement targeted them for deportation. The council also considered amending city code to allow officers to investigate and cite ICE agents for local law violations. This matches Chair 1 (refuse ICE detainers; prohibit city employees from sharing immigration status information with federal agencies).', ARRAY['https://beavertonvalleytimes.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/', 'https://katu.com/news/local/beaverton-mayor-lacey-beaty-councilors-nadia-hasan-kevin-teater-considers-having-officers-investigate-federal-immigration-ice-agents', 'https://www.koin.com/news/portland-beaverton-to-remain-sanctuary-cities/']::text[]),
    ('economic-development', 3, 'Beaverton under Beaty maintains formal tax-incentive programs for development in specific areas of the city (property tax incentives for targeted zones). Beaty cited a ''laser focus'' on restaurant and business attraction strategies and pointed to near-zero vacancy rates as evidence of success. The city supports small businesses while also using targeted tax abatements in designated areas. This targeted-incentive model — neither refusing all corporate incentives nor offering blanket maximum subsidies — maps to Chair 3 (targeted incentives for specific industries with community benefit agreements).', ARRAY['https://www.beavertonoregon.gov/256/City-Incentives', 'https://www.koin.com/local/washington-county/laser-focus-helps-beaverton-boom-outpace-portland/']::text[]),
    ('growth-and-development', 3, 'Beaty described Beaverton as being ''in a time of immense growth'' and said ''while growth is important, this should be balanced with sustainability.'' She invested proactively in the Purple Pipe reclaimed-water infrastructure to support future growth, championed sidewalk and transportation infrastructure investments ahead of demand, and supported annexations. This is neither a growth-limits stance nor pure deregulation, but proactive infrastructure investment to support responsible expansion — Chair 3.', ARRAY['https://medium.com/usmayors/meet-the-mayor-lacey-beaty-5ad15bc11951', 'https://en.wikipedia.org/wiki/Lacey_Beaty']::text[]),
    ('taxes', 2, 'Beaty raised Beaverton''s property tax rate from $4.23 to $4.62 per $1,000 assessed value in 2023 to address structural budget pressures. She explicitly stated that if expenses continue to outpace revenues, property tax levies will be necessary in the future — signaling willingness to raise taxes to fund public services rather than cut services. She oversaw budget cuts in 2025 as a fiscal necessity, not an ideological preference for smaller government. This willingness to raise taxes on property owners to fund existing and expanded services maps to Chair 2 (moderately raise taxes to fund existing services).', ARRAY['https://beavertonvalleytimes.com/2023/06/16/beaverton-raises-property-taxes-using-decades-old-oregon-laws/', 'https://katu.com/news/local/beaverton-faces-107-million-budget-shortfall-plans-cuts-to-police-and-public-works-library-street-repair-resident-portland-oregon-washington-county-finances-economy-consumer']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '6f4e9c86-1c23-4569-ad1a-7614463420f1'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
