-- Migration 1134: Ashley Hartmeier-Prigg (Position 1) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 17 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Hartmeier-Prigg''s record shows targeted subsidies, streamlined permitting, and affordable-unit requirements as her primary tools: she ''delivered 696 affordable units, 2,656 new homes'' and wants to ''streamline the inspections and permitting process'' and assure ''building codes and land use policies are aimed at making safe, affordable housing for all income levels.'' She also secured Metro housing spending and IGA funding for year-round shelter construction. This is targeted government help plus easier building—chair 3—rather than rent caps or public construction of housing directly.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/', 'https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/']::text[]),
    ('homelessness', 2, 'Hartmeier-Prigg motioned in February 2023 to adopt a Shelter Code ordinance updating emergency shelter definitions and processes, and in October 2023 motioned to approve IGA funding for year-round shelter construction (7-0). She frames homelessness response as investing in shelter capacity and supportive services (''outreach, services, and shelter''), describing the completed year-round shelter connecting 50 people to permanent housing as a model she wants to expand. No evidence of support for criminal penalties or camping bans; emphasis is on service access and decriminalization via shelter availability.', ARRAY['https://beaverton.granicus.com/DocumentViewer.php?file=beaverton_85207b6f45cd31338cdf273f9da2e613.pdf&view=1', 'https://beaverton.granicus.com/DocumentViewer.php?file=beaverton_a420dfe761c70c0e7b5f6e28bf107a50.pdf&view=1', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/']::text[]),
    ('homelessness-response', 2, 'Her primary homelessness strategy has been expanding shelter capacity (launched Beaverton''s first year-round, 60-guest shelter with meals, showers, laundry, clinic, and coordinated care) while connecting residents to services. The Washington County Democrats interview shows she wants to ''maximize Metro housing spending with measurable outcomes'' and improve shelter-to-housing pathways. Shelter investment plus services as primary strategy, with enforcement only after services are offered, matches chair 2.', ARRAY['https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/', 'https://www.washingtoncountyor.gov/housing/news/2023/11/06/year-round-shelter-construction-begins-beaverton', 'https://www.koin.com/news/homeless/beaverton-breaks-ground-on-first-year-round-homeless-shelter-in-washington-county/']::text[]),
    ('residential-zoning', 4, 'At the Cooper Mountain planning session, Hartmeier-Prigg advocated for Scenario C featuring smaller roads to encourage biking/pedestrian travel and diverse housing types including ''duplexes, cottage clusters, row housing, and apartments.'' In the 2022 candidate Q&A she listed ''duplexes, cottage clusters, row housing, and apartments'' as the housing variety needed ''for all income levels.'' Streamlining permitting and upzoning to allow multifamily broadly aligns with chair 4, rather than the modest/incremental approach of chair 3.', ARRAY['https://beavertonvalleytimes.com/news/beaverton-explores-neighborhood-scenarios-for-cooper-mountain/article_1d26e072-529f-550b-a530-69d816d8a053.html', 'https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/']::text[]),
    ('growth-and-development', 3, 'Hartmeier-Prigg supported Beaverton''s proactive Cooper Mountain development planning and housing expansion while also advocating ecosystem and natural resource preservation as part of that planning. She supports streamlining permitting to enable growth but within a framework of building codes and land-use standards. This is planning ahead with infrastructure investment to enable responsible growth, matching chair 3.', ARRAY['https://beavertonvalleytimes.com/news/beaverton-explores-neighborhood-scenarios-for-cooper-mountain/article_1d26e072-529f-550b-a530-69d816d8a053.html', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/']::text[]),
    ('transportation-priorities', 1, 'Hartmeier-Prigg served on the TV Highway Transit & Safety Project Steering Committee and in February 2025 helped recommend a locally preferred alternative for bus rapid transit (TriMet FX) on the corridor. At Cooper Mountain planning she argued that ''building roads doesn''t ease congestion'' and favored smaller roads to ''encourage more biking and pedestrian rolling and other ways of getting around.'' In the 2022 candidate Q&A she explicitly called for ''planning and building a city that is pedestrian-friendly.'' These on-record positions consistently prioritize transit, pedestrians, and cycling over road capacity, aligning with chair 1.', ARRAY['https://www.oregonmetro.gov/projects/tualatin-valley-highway-transit-and-safety-project', 'https://www.trimet.org/tvhighway/', 'https://beavertonvalleytimes.com/news/beaverton-explores-neighborhood-scenarios-for-cooper-mountain/article_1d26e072-529f-550b-a530-69d816d8a053.html', 'https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/']::text[]),
    ('local-environment', 2, 'At Cooper Mountain, Hartmeier-Prigg specifically supported the scenario that balanced ''ample housing and natural resource preservation'' and advocated protecting ecosystems. Her 2022 Q&A described supporting development plans that protect ecosystems while providing housing variety. Strict tree/park protection plus full developer offset for environmental impact reflects chair 2.', ARRAY['https://beavertonvalleytimes.com/news/beaverton-explores-neighborhood-scenarios-for-cooper-mountain/article_1d26e072-529f-550b-a530-69d816d8a053.html', 'https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/']::text[]),
    ('climate-change', 3, 'Her Oregon SoS voters'' guide and campaign materials list ''climate action'' as a priority. In the Washington County Democrats interview she listed ''fighting climate change'' among legislative goals alongside livable wages and ERA. The 2022 candidate Q&A records her saying she ''feel[s] the effects of climate change in Beaverton'' and supports climate-conscious development. However, she does not call for banning fossil fuels by 2030 or a climate emergency declaration; her framing is investment in clean alternatives and climate action within a practical framework, matching chair 3.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/', 'https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/']::text[]),
    ('childcare', 3, 'Hartmeier-Prigg''s Oregon SoS voters'' guide statement highlights ''Delivered $150,000 in grants for childcare centers'' as a signature accomplishment in Beaverton. Her HD-27 platform includes childcare affordability as part of reducing the cost of living. Grant programs and targeted subsidies for providers below an income threshold (rather than universal public childcare or pure market solutions) align with chair 3.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html', 'https://www.ashleyhartmeierprigg.com/']::text[]),
    ('healthcare', 2, 'Hartmeier-Prigg''s Oregon SoS voters'' guide lists ''healthcare for all'' as a cost-of-living priority and her HD-27 platform says ''People should not have to choose between housing and health care.'' In the Washington County Democrats interview she stated she wants to ''do more to help people get health care'' and that the state needs ''to find the resources to take care of the health care system'' amid federal cuts. This language (''for all,'' affordable coverage through public programs) fits chair 2—ensuring affordable coverage through public programs and regulated private insurance—without a specific single-payer or free-for-all endorsement on record.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/']::text[]),
    ('abortion', 1, 'Her Oregon SoS voters'' guide explicitly states protecting ''reproductive healthcare and abortion'' as a core priority, and she frames it as ''defending'' access. The Washington County Democrats interview notes her goal of ''protecting reproductive healthcare access and abortion rights.'' The hoodline.com article and her campaign materials frame this as defending against federal attacks on an existing right (Oregon''s full legal access). ''Protecting reproductive healthcare and abortion'' without any qualification language (no trimester limits mentioned) best matches chair 1—keeping abortion legal, accessible, and protected.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/', 'https://hoodline.com/2026/04/beaverton-left-showdown-dueling-progressives-battle-for-house-district-27/']::text[]),
    ('local-immigration', 1, 'In her Washington County Democrats interview (2026) and Oregon SoS voters'' guide, Hartmeier-Prigg states she supports Oregon''s sanctuary state status by ensuring ''no state, county or municipal resources are used in immigration enforcement.'' She wants to ''hold ICE accountable'' and stated that ''when immigration officers violate the rights of people in Oregon, we must sue the federal government and prosecute those federal agents.'' Refusing ICE detainers and prohibiting city employees from sharing immigration status information aligns with chair 1.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/']::text[]),
    ('civil-rights', 2, 'Her voters'' guide and campaign materials list DEI/equity, ERA passage, and LGBTQ+ equality among legislative priorities. In the Washington County Democrats interview she expresses support for racial equity (Beaverton diversity preservation) and systemic approaches. Strengthening civil rights enforcement and addressing systemic discrimination—chair 2—fits her stated priorities without the reparations mandate of chair 1.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/']::text[]),
    ('economic-development', 2, 'Hartmeier-Prigg secured ''$1 million in funding for loans and grants supporting minority and women-owned small businesses'' as a Beaverton council accomplishment, and her HD-27 platform emphasizes ''small business development through mentorship and resources'' and incubator programs over large corporate subsidies. She supports ''business-friendly regulations'' while targeting minority entrepreneurs. Small business and local entrepreneur programs, avoiding large corporate subsidies, aligns with chair 2.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/']::text[]),
    ('taxes', 1, 'In the Washington County Democrats interview, Hartmeier-Prigg stated ''if we need more revenue, we need to find more creative ways to create revenue streams, so we can look out for all'' and called for a ''budget that reflects our values.'' She also stated ''It''s a failure of our system that billionaires exist,'' reflecting support for significant wealth redistribution. Raising taxes on wealthy people and large companies to fund more public services aligns with chair 1.', ARRAY['https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/']::text[]),
    ('public-safety-approach', 3, 'The Pamplin Media article notes that ''reforming public safety, much less defund the police, was not a primary issue on which Hartmeier-Prigg ran'' and she publicly supported creation of a Beaverton Police advisory committee—suggesting she supports existing police staffing while adding accountability. She describes herself as supporting ''fostering safe and welcoming communities'' without defunding or significant reallocation language. Keeping current funding while adding crisis/oversight mechanisms aligns with chair 3.', ARRAY['https://pamplinmedia.com/bvt/15-news/528701-422624-public-safety-rhetoric-haunts-progressive-candidates-in-washington-county', 'https://www.instagram.com/p/DRvHlJegd37/']::text[]),
    ('school-vouchers', 1, 'Her Oregon SoS voters'' guide explicitly states ''Fully funding public education so all children get a quality public education'' as a legislative priority. Full public school funding without any mention of vouchers or school choice programs, in the context of running for state legislature where this would be a direct vote, strongly implies opposition to voucher programs—chair 1.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT 'd7756d33-4c53-4c68-9c36-cf2f9817a17b'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Hartmeier-Prigg''s record shows targeted subsidies, streamlined permitting, and affordable-unit requirements as her primary tools: she ''delivered 696 affordable units, 2,656 new homes'' and wants to ''streamline the inspections and permitting process'' and assure ''building codes and land use policies are aimed at making safe, affordable housing for all income levels.'' She also secured Metro housing spending and IGA funding for year-round shelter construction. This is targeted government help plus easier building—chair 3—rather than rent caps or public construction of housing directly.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/', 'https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/']::text[]),
    ('homelessness', 2, 'Hartmeier-Prigg motioned in February 2023 to adopt a Shelter Code ordinance updating emergency shelter definitions and processes, and in October 2023 motioned to approve IGA funding for year-round shelter construction (7-0). She frames homelessness response as investing in shelter capacity and supportive services (''outreach, services, and shelter''), describing the completed year-round shelter connecting 50 people to permanent housing as a model she wants to expand. No evidence of support for criminal penalties or camping bans; emphasis is on service access and decriminalization via shelter availability.', ARRAY['https://beaverton.granicus.com/DocumentViewer.php?file=beaverton_85207b6f45cd31338cdf273f9da2e613.pdf&view=1', 'https://beaverton.granicus.com/DocumentViewer.php?file=beaverton_a420dfe761c70c0e7b5f6e28bf107a50.pdf&view=1', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/']::text[]),
    ('homelessness-response', 2, 'Her primary homelessness strategy has been expanding shelter capacity (launched Beaverton''s first year-round, 60-guest shelter with meals, showers, laundry, clinic, and coordinated care) while connecting residents to services. The Washington County Democrats interview shows she wants to ''maximize Metro housing spending with measurable outcomes'' and improve shelter-to-housing pathways. Shelter investment plus services as primary strategy, with enforcement only after services are offered, matches chair 2.', ARRAY['https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/', 'https://www.washingtoncountyor.gov/housing/news/2023/11/06/year-round-shelter-construction-begins-beaverton', 'https://www.koin.com/news/homeless/beaverton-breaks-ground-on-first-year-round-homeless-shelter-in-washington-county/']::text[]),
    ('residential-zoning', 4, 'At the Cooper Mountain planning session, Hartmeier-Prigg advocated for Scenario C featuring smaller roads to encourage biking/pedestrian travel and diverse housing types including ''duplexes, cottage clusters, row housing, and apartments.'' In the 2022 candidate Q&A she listed ''duplexes, cottage clusters, row housing, and apartments'' as the housing variety needed ''for all income levels.'' Streamlining permitting and upzoning to allow multifamily broadly aligns with chair 4, rather than the modest/incremental approach of chair 3.', ARRAY['https://beavertonvalleytimes.com/news/beaverton-explores-neighborhood-scenarios-for-cooper-mountain/article_1d26e072-529f-550b-a530-69d816d8a053.html', 'https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/']::text[]),
    ('growth-and-development', 3, 'Hartmeier-Prigg supported Beaverton''s proactive Cooper Mountain development planning and housing expansion while also advocating ecosystem and natural resource preservation as part of that planning. She supports streamlining permitting to enable growth but within a framework of building codes and land-use standards. This is planning ahead with infrastructure investment to enable responsible growth, matching chair 3.', ARRAY['https://beavertonvalleytimes.com/news/beaverton-explores-neighborhood-scenarios-for-cooper-mountain/article_1d26e072-529f-550b-a530-69d816d8a053.html', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/']::text[]),
    ('transportation-priorities', 1, 'Hartmeier-Prigg served on the TV Highway Transit & Safety Project Steering Committee and in February 2025 helped recommend a locally preferred alternative for bus rapid transit (TriMet FX) on the corridor. At Cooper Mountain planning she argued that ''building roads doesn''t ease congestion'' and favored smaller roads to ''encourage more biking and pedestrian rolling and other ways of getting around.'' In the 2022 candidate Q&A she explicitly called for ''planning and building a city that is pedestrian-friendly.'' These on-record positions consistently prioritize transit, pedestrians, and cycling over road capacity, aligning with chair 1.', ARRAY['https://www.oregonmetro.gov/projects/tualatin-valley-highway-transit-and-safety-project', 'https://www.trimet.org/tvhighway/', 'https://beavertonvalleytimes.com/news/beaverton-explores-neighborhood-scenarios-for-cooper-mountain/article_1d26e072-529f-550b-a530-69d816d8a053.html', 'https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/']::text[]),
    ('local-environment', 2, 'At Cooper Mountain, Hartmeier-Prigg specifically supported the scenario that balanced ''ample housing and natural resource preservation'' and advocated protecting ecosystems. Her 2022 Q&A described supporting development plans that protect ecosystems while providing housing variety. Strict tree/park protection plus full developer offset for environmental impact reflects chair 2.', ARRAY['https://beavertonvalleytimes.com/news/beaverton-explores-neighborhood-scenarios-for-cooper-mountain/article_1d26e072-529f-550b-a530-69d816d8a053.html', 'https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/']::text[]),
    ('climate-change', 3, 'Her Oregon SoS voters'' guide and campaign materials list ''climate action'' as a priority. In the Washington County Democrats interview she listed ''fighting climate change'' among legislative goals alongside livable wages and ERA. The 2022 candidate Q&A records her saying she ''feel[s] the effects of climate change in Beaverton'' and supports climate-conscious development. However, she does not call for banning fossil fuels by 2030 or a climate emergency declaration; her framing is investment in clean alternatives and climate action within a practical framework, matching chair 3.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/', 'https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/']::text[]),
    ('childcare', 3, 'Hartmeier-Prigg''s Oregon SoS voters'' guide statement highlights ''Delivered $150,000 in grants for childcare centers'' as a signature accomplishment in Beaverton. Her HD-27 platform includes childcare affordability as part of reducing the cost of living. Grant programs and targeted subsidies for providers below an income threshold (rather than universal public childcare or pure market solutions) align with chair 3.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html', 'https://www.ashleyhartmeierprigg.com/']::text[]),
    ('healthcare', 2, 'Hartmeier-Prigg''s Oregon SoS voters'' guide lists ''healthcare for all'' as a cost-of-living priority and her HD-27 platform says ''People should not have to choose between housing and health care.'' In the Washington County Democrats interview she stated she wants to ''do more to help people get health care'' and that the state needs ''to find the resources to take care of the health care system'' amid federal cuts. This language (''for all,'' affordable coverage through public programs) fits chair 2—ensuring affordable coverage through public programs and regulated private insurance—without a specific single-payer or free-for-all endorsement on record.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/']::text[]),
    ('abortion', 1, 'Her Oregon SoS voters'' guide explicitly states protecting ''reproductive healthcare and abortion'' as a core priority, and she frames it as ''defending'' access. The Washington County Democrats interview notes her goal of ''protecting reproductive healthcare access and abortion rights.'' The hoodline.com article and her campaign materials frame this as defending against federal attacks on an existing right (Oregon''s full legal access). ''Protecting reproductive healthcare and abortion'' without any qualification language (no trimester limits mentioned) best matches chair 1—keeping abortion legal, accessible, and protected.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/', 'https://hoodline.com/2026/04/beaverton-left-showdown-dueling-progressives-battle-for-house-district-27/']::text[]),
    ('local-immigration', 1, 'In her Washington County Democrats interview (2026) and Oregon SoS voters'' guide, Hartmeier-Prigg states she supports Oregon''s sanctuary state status by ensuring ''no state, county or municipal resources are used in immigration enforcement.'' She wants to ''hold ICE accountable'' and stated that ''when immigration officers violate the rights of people in Oregon, we must sue the federal government and prosecute those federal agents.'' Refusing ICE detainers and prohibiting city employees from sharing immigration status information aligns with chair 1.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/']::text[]),
    ('civil-rights', 2, 'Her voters'' guide and campaign materials list DEI/equity, ERA passage, and LGBTQ+ equality among legislative priorities. In the Washington County Democrats interview she expresses support for racial equity (Beaverton diversity preservation) and systemic approaches. Strengthening civil rights enforcement and addressing systemic discrimination—chair 2—fits her stated priorities without the reparations mandate of chair 1.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/']::text[]),
    ('economic-development', 2, 'Hartmeier-Prigg secured ''$1 million in funding for loans and grants supporting minority and women-owned small businesses'' as a Beaverton council accomplishment, and her HD-27 platform emphasizes ''small business development through mentorship and resources'' and incubator programs over large corporate subsidies. She supports ''business-friendly regulations'' while targeting minority entrepreneurs. Small business and local entrepreneur programs, avoiding large corporate subsidies, aligns with chair 2.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html', 'https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/']::text[]),
    ('taxes', 1, 'In the Washington County Democrats interview, Hartmeier-Prigg stated ''if we need more revenue, we need to find more creative ways to create revenue streams, so we can look out for all'' and called for a ''budget that reflects our values.'' She also stated ''It''s a failure of our system that billionaires exist,'' reflecting support for significant wealth redistribution. Raising taxes on wealthy people and large companies to fund more public services aligns with chair 1.', ARRAY['https://washcodems.org/2026/04/26/ashley-hartmeier-prigg-race-for-hd-27-seat-candidate-interview/']::text[]),
    ('public-safety-approach', 3, 'The Pamplin Media article notes that ''reforming public safety, much less defund the police, was not a primary issue on which Hartmeier-Prigg ran'' and she publicly supported creation of a Beaverton Police advisory committee—suggesting she supports existing police staffing while adding accountability. She describes herself as supporting ''fostering safe and welcoming communities'' without defunding or significant reallocation language. Keeping current funding while adding crisis/oversight mechanisms aligns with chair 3.', ARRAY['https://pamplinmedia.com/bvt/15-news/528701-422624-public-safety-rhetoric-haunts-progressive-candidates-in-washington-county', 'https://www.instagram.com/p/DRvHlJegd37/']::text[]),
    ('school-vouchers', 1, 'Her Oregon SoS voters'' guide explicitly states ''Fully funding public education so all children get a quality public education'' as a legislative priority. Full public school funding without any mention of vouchers or school choice programs, in the context of running for state legislature where this would be a direct vote, strongly implies opposition to voucher programs—chair 1.', ARRAY['https://oregonvotes.gov/voters-guide/english/ashleyhartmeierprigg.html']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT 'd7756d33-4c53-4c68-9c36-cf2f9817a17b'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
