-- Migration 1135: Kevin Teater (Position 2) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 12 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('transportation-priorities', 1, 'Teater was a central champion of Beaverton''s July 2023 unanimous vote to eliminate all minimum parking requirements citywide, calling the policy ''absolutely transformative.'' He rides his bike daily and told BikePortland he ''fears for my life multiple times a day'' on the Downtown Loop. In a June 2024 policy ride with BikePortland, he explicitly stated he wants to shift local transportation dialogues away from car parking and toward accessibility—asking ''How is our community connecting with itself?'' He also supports the Denney Road bike/pedestrian path, Complete Streets policy, and Millikan Way improvements.', ARRAY['https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://parkingreform.org/2023/09/29/meet-beaverton-oregons-city-councilor-kevin-teater/', 'https://bikeportland.org/2024/06/14/tigard-beaverton-councilors-face-cycling-conditions-on-policy-ride-387570', 'https://bikeportland.org/2022/08/11/beaverton-gets-2-million-grant-for-downtown-loop-project-361391']::text[]),
    ('residential-zoning', 4, 'Teater supports Beaverton''s Housing Production Strategy which he touts as making ''it easier to build housing of all kinds at various price levels throughout the city.'' He credits the council with producing 6,500+ new housing units, and backs large-scale development (5,000+ homes in Cooper Mountain). His 2022 campaign called for ''increased housing development flexibility and variety'' and updating Beaverton''s development code. The parking-minimum elimination (2023) further reduces regulatory barriers to housing. His overall record is consistent with broadly upzoning and streamlining approvals.', ARRAY['https://kevinteater.com/policies', 'https://beavertonvalleytimes.com/2026/04/21/kevin-teater-seeks-reelection-to-beaverton-city-council/', 'https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/']::text[]),
    ('housing', 3, 'Teater lists housing as one of his top three priorities and touts 350+ regulated affordable units and the Housing Production Strategy. He supported city-funded construction of Beaverton''s first permanent homeless shelter at no taxpayer cost to city (funded via Metro''s SHS fund). He advocates for subsidized affordable projects and making it easier to permit housing of all types—consistent with targeted help (subsidies + easier permits) rather than direct public housing ownership or city-wide rent caps.', ARRAY['https://kevinteater.com/', 'https://beavertonvalleytimes.com/2026/04/21/kevin-teater-seeks-reelection-to-beaverton-city-council/', 'https://www.oregonmetro.gov/stories/beaverton-opens-its-first-year-round-homeless-shelter']::text[]),
    ('homelessness-response', 2, 'Teater voted 7-0 in February 2023 for the preconstruction phase of the city''s first year-round permanent shelter. His campaign website highlights this shelter as a signature accomplishment and states ''We must also continue building more housing and expanding services that address housing insecurity.'' The shelter model (shelter capacity + outreach + service connection) is his stated primary strategy, with enforcement secondary. He also backed an Access Center and police bike team for outreach alongside enforcement.', ARRAY['https://beaverton.granicus.com/DocumentViewer.php?file=beaverton_85207b6f45cd31338cdf273f9da2e613.pdf&view=1', 'https://kevinteater.com/', 'https://www.beavertonoregon.gov/the-beaverton-shelter']::text[]),
    ('homelessness', 2, 'The council''s shelter model—where Teater voted 7-0 for the permanent shelter—offers services on a voluntary 24/7 basis. Beaverton''s policy approach pairs enforcement with available shelter beds and services, consistent with decriminalizing public sleeping while investing in shelter and outreach. Teater has not publicly advocated for strict camping bans without service alternatives.', ARRAY['https://beaverton.granicus.com/DocumentViewer.php?file=beaverton_85207b6f45cd31338cdf273f9da2e613.pdf&view=1', 'https://www.beavertonoregon.gov/1499/Beaverton-Homelessness-Response', 'https://kevinteater.com/']::text[]),
    ('local-immigration', 1, 'Teater''s reelection campaign explicitly listed ''codifying Sanctuary City status'' and ''joining four lawsuits against the federal government to keep Beaverton families safe'' as council accomplishments. He voted for the January 2026 sanctuary ordinance update prohibiting city employees from sharing immigration data with federal agencies except where legally required. His only stated concern was procedural (amendment language should have been reviewed by city attorney first), not substantive opposition to the policy''s protections.', ARRAY['https://beavertonvalleytimes.com/2026/04/21/kevin-teater-seeks-reelection-to-beaverton-city-council/', 'https://beavertonvalleytimes.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/', 'https://katu.com/news/local/beaverton-mayor-lacey-beaty-councilors-nadia-hasan-kevin-teater-considers-having-officers-investigate-federal-immigration-ice-agents']::text[]),
    ('civil-rights', 2, 'In his 2022 candidate Q&A, Teater identified racial equity as one of his top three issues and stated he had been ''pushing council to challenge our thinking when it comes to housing policy to dismantle past racist systems.'' He also noted that urban renewal history ''is very racist, classist, and destructive'' and that BURA must keep ''equity and racial reconciliation as top priorities.'' He supports small-business programs specifically targeting ''immigrants, refugees, and people of color'' to reduce barriers to entrepreneurship.', ARRAY['https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/', 'https://pamplinmedia.com/bvt/15-news/543526-435063-q-and-a-get-to-know-beaverton-city-council-candidates']::text[]),
    ('public-safety-approach', 2, 'In July 2023, Teater voted NO (5-2) on the city''s contract to keep armed officers (Youth Services Officers) in Beaverton schools, stating: ''We heard very clearly from our community and from the results of the SeeChange report that the presence of law enforcement makes it difficult for some of our most marginalized students to feel safe in our schools.'' This is a documented dissent from expanding police presence in a non-violent school environment, consistent with favoring mental health and community-based alternatives for non-violent situations.', ARRAY['https://www.kgw.com/article/sports/high-school/beaverton-council-school-youth-services-officers-armed-police-schools/283-83cdb8f4-3a61-4dff-a056-bf60dcad33ec', 'https://www.opb.org/article/2023/07/14/police-officers-schools-beaverton-oregon/']::text[]),
    ('climate-change', 3, 'Teater stated in his 2022 campaign that ''Climate change is real, and my generation is going to bear the brunt of it'' and committed to ''prioritizing climate action in all that we do.'' He received the Oregon League of Conservation Voters endorsement in both 2022 and 2026, which endorses candidates who ''fight to protect Oregon''s air and water'' and advance climate solutions. His transportation and housing record (parking elimination, dense infill, Complete Streets) reflects climate-conscious infrastructure choices, though no specific carbon or fossil fuel city policy votes are on record—consistent with chair 3 (invest in clean priorities, gradual transition).', ARRAY['https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/', 'https://www.olcv.org/2026-primary/', 'https://thewashingtoncountyvoterguide.com/']::text[]),
    ('local-environment', 2, 'Teater published a blog post on restoring neighborhood tree canopies and included tree preservation as a priority in his 2022 development code update platform. He received endorsements from the Oregon League of Conservation Voters in 2026 specifically for environmental stewardship, and his campaign website emphasizes ''environmental stewardship'' as a core value. His 2022 Q&A cited updating the development code with a focus on ''transportation and tree preservation.'' His approach is consistent with requiring developers to offset environmental impact.', ARRAY['https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/', 'https://kevinteater.com/blog/f/restoring-neighborhood-tree-canopies', 'https://www.olcv.org/2026-primary/']::text[]),
    ('growth-and-development', 3, 'Teater credits the council with 6,500+ new housing units and backs major growth projects like Cooper Mountain (5,000+ homes) and the Housing Production Strategy. His platform calls for proactive infrastructure investment (''Willamette Water Supply Pipeline,'' Downtown Loop, street improvements) to support growth. He does not impose growth limits but also does not advocate removing all regulatory barriers—consistent with investing in infrastructure ahead of growth to support responsible expansion.', ARRAY['https://kevinteater.com/', 'https://beavertonvalleytimes.com/2026/04/21/kevin-teater-seeks-reelection-to-beaverton-city-council/']::text[]),
    ('economic-development', 2, 'Teater''s 2022 campaign pledged support for ''continued aid to Beaverton businesses in entrepreneur incubators such as Impact Beaverton and OTBC'' and making entrepreneurship ''more accessible for the people who have typically faced the greatest barriers.'' His background as executive director of the Beaverton Downtown Association (securing $400K+ in grants for small businesses) and his focus on local/small business programs is consistent with prioritizing small business support over large corporate tax subsidies.', ARRAY['https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/', 'https://kevinteater.com/about']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '6d019025-985f-4410-aa82-75de91eb4203'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('transportation-priorities', 1, 'Teater was a central champion of Beaverton''s July 2023 unanimous vote to eliminate all minimum parking requirements citywide, calling the policy ''absolutely transformative.'' He rides his bike daily and told BikePortland he ''fears for my life multiple times a day'' on the Downtown Loop. In a June 2024 policy ride with BikePortland, he explicitly stated he wants to shift local transportation dialogues away from car parking and toward accessibility—asking ''How is our community connecting with itself?'' He also supports the Denney Road bike/pedestrian path, Complete Streets policy, and Millikan Way improvements.', ARRAY['https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://parkingreform.org/2023/09/29/meet-beaverton-oregons-city-councilor-kevin-teater/', 'https://bikeportland.org/2024/06/14/tigard-beaverton-councilors-face-cycling-conditions-on-policy-ride-387570', 'https://bikeportland.org/2022/08/11/beaverton-gets-2-million-grant-for-downtown-loop-project-361391']::text[]),
    ('residential-zoning', 4, 'Teater supports Beaverton''s Housing Production Strategy which he touts as making ''it easier to build housing of all kinds at various price levels throughout the city.'' He credits the council with producing 6,500+ new housing units, and backs large-scale development (5,000+ homes in Cooper Mountain). His 2022 campaign called for ''increased housing development flexibility and variety'' and updating Beaverton''s development code. The parking-minimum elimination (2023) further reduces regulatory barriers to housing. His overall record is consistent with broadly upzoning and streamlining approvals.', ARRAY['https://kevinteater.com/policies', 'https://beavertonvalleytimes.com/2026/04/21/kevin-teater-seeks-reelection-to-beaverton-city-council/', 'https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/']::text[]),
    ('housing', 3, 'Teater lists housing as one of his top three priorities and touts 350+ regulated affordable units and the Housing Production Strategy. He supported city-funded construction of Beaverton''s first permanent homeless shelter at no taxpayer cost to city (funded via Metro''s SHS fund). He advocates for subsidized affordable projects and making it easier to permit housing of all types—consistent with targeted help (subsidies + easier permits) rather than direct public housing ownership or city-wide rent caps.', ARRAY['https://kevinteater.com/', 'https://beavertonvalleytimes.com/2026/04/21/kevin-teater-seeks-reelection-to-beaverton-city-council/', 'https://www.oregonmetro.gov/stories/beaverton-opens-its-first-year-round-homeless-shelter']::text[]),
    ('homelessness-response', 2, 'Teater voted 7-0 in February 2023 for the preconstruction phase of the city''s first year-round permanent shelter. His campaign website highlights this shelter as a signature accomplishment and states ''We must also continue building more housing and expanding services that address housing insecurity.'' The shelter model (shelter capacity + outreach + service connection) is his stated primary strategy, with enforcement secondary. He also backed an Access Center and police bike team for outreach alongside enforcement.', ARRAY['https://beaverton.granicus.com/DocumentViewer.php?file=beaverton_85207b6f45cd31338cdf273f9da2e613.pdf&view=1', 'https://kevinteater.com/', 'https://www.beavertonoregon.gov/the-beaverton-shelter']::text[]),
    ('homelessness', 2, 'The council''s shelter model—where Teater voted 7-0 for the permanent shelter—offers services on a voluntary 24/7 basis. Beaverton''s policy approach pairs enforcement with available shelter beds and services, consistent with decriminalizing public sleeping while investing in shelter and outreach. Teater has not publicly advocated for strict camping bans without service alternatives.', ARRAY['https://beaverton.granicus.com/DocumentViewer.php?file=beaverton_85207b6f45cd31338cdf273f9da2e613.pdf&view=1', 'https://www.beavertonoregon.gov/1499/Beaverton-Homelessness-Response', 'https://kevinteater.com/']::text[]),
    ('local-immigration', 1, 'Teater''s reelection campaign explicitly listed ''codifying Sanctuary City status'' and ''joining four lawsuits against the federal government to keep Beaverton families safe'' as council accomplishments. He voted for the January 2026 sanctuary ordinance update prohibiting city employees from sharing immigration data with federal agencies except where legally required. His only stated concern was procedural (amendment language should have been reviewed by city attorney first), not substantive opposition to the policy''s protections.', ARRAY['https://beavertonvalleytimes.com/2026/04/21/kevin-teater-seeks-reelection-to-beaverton-city-council/', 'https://beavertonvalleytimes.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/', 'https://katu.com/news/local/beaverton-mayor-lacey-beaty-councilors-nadia-hasan-kevin-teater-considers-having-officers-investigate-federal-immigration-ice-agents']::text[]),
    ('civil-rights', 2, 'In his 2022 candidate Q&A, Teater identified racial equity as one of his top three issues and stated he had been ''pushing council to challenge our thinking when it comes to housing policy to dismantle past racist systems.'' He also noted that urban renewal history ''is very racist, classist, and destructive'' and that BURA must keep ''equity and racial reconciliation as top priorities.'' He supports small-business programs specifically targeting ''immigrants, refugees, and people of color'' to reduce barriers to entrepreneurship.', ARRAY['https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/', 'https://pamplinmedia.com/bvt/15-news/543526-435063-q-and-a-get-to-know-beaverton-city-council-candidates']::text[]),
    ('public-safety-approach', 2, 'In July 2023, Teater voted NO (5-2) on the city''s contract to keep armed officers (Youth Services Officers) in Beaverton schools, stating: ''We heard very clearly from our community and from the results of the SeeChange report that the presence of law enforcement makes it difficult for some of our most marginalized students to feel safe in our schools.'' This is a documented dissent from expanding police presence in a non-violent school environment, consistent with favoring mental health and community-based alternatives for non-violent situations.', ARRAY['https://www.kgw.com/article/sports/high-school/beaverton-council-school-youth-services-officers-armed-police-schools/283-83cdb8f4-3a61-4dff-a056-bf60dcad33ec', 'https://www.opb.org/article/2023/07/14/police-officers-schools-beaverton-oregon/']::text[]),
    ('climate-change', 3, 'Teater stated in his 2022 campaign that ''Climate change is real, and my generation is going to bear the brunt of it'' and committed to ''prioritizing climate action in all that we do.'' He received the Oregon League of Conservation Voters endorsement in both 2022 and 2026, which endorses candidates who ''fight to protect Oregon''s air and water'' and advance climate solutions. His transportation and housing record (parking elimination, dense infill, Complete Streets) reflects climate-conscious infrastructure choices, though no specific carbon or fossil fuel city policy votes are on record—consistent with chair 3 (invest in clean priorities, gradual transition).', ARRAY['https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/', 'https://www.olcv.org/2026-primary/', 'https://thewashingtoncountyvoterguide.com/']::text[]),
    ('local-environment', 2, 'Teater published a blog post on restoring neighborhood tree canopies and included tree preservation as a priority in his 2022 development code update platform. He received endorsements from the Oregon League of Conservation Voters in 2026 specifically for environmental stewardship, and his campaign website emphasizes ''environmental stewardship'' as a core value. His 2022 Q&A cited updating the development code with a focus on ''transportation and tree preservation.'' His approach is consistent with requiring developers to offset environmental impact.', ARRAY['https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/', 'https://kevinteater.com/blog/f/restoring-neighborhood-tree-canopies', 'https://www.olcv.org/2026-primary/']::text[]),
    ('growth-and-development', 3, 'Teater credits the council with 6,500+ new housing units and backs major growth projects like Cooper Mountain (5,000+ homes) and the Housing Production Strategy. His platform calls for proactive infrastructure investment (''Willamette Water Supply Pipeline,'' Downtown Loop, street improvements) to support growth. He does not impose growth limits but also does not advocate removing all regulatory barriers—consistent with investing in infrastructure ahead of growth to support responsible expansion.', ARRAY['https://kevinteater.com/', 'https://beavertonvalleytimes.com/2026/04/21/kevin-teater-seeks-reelection-to-beaverton-city-council/']::text[]),
    ('economic-development', 2, 'Teater''s 2022 campaign pledged support for ''continued aid to Beaverton businesses in entrepreneur incubators such as Impact Beaverton and OTBC'' and making entrepreneurship ''more accessible for the people who have typically faced the greatest barriers.'' His background as executive director of the Beaverton Downtown Association (securing $400K+ in grants for small businesses) and his focus on local/small business programs is consistent with prioritizing small business support over large corporate tax subsidies.', ARRAY['https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/', 'https://kevinteater.com/about']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '6d019025-985f-4410-aa82-75de91eb4203'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
