-- Migration 1136: Edward Kimmi (Position 3) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 12 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Kimmi has consistently supported affordable housing options for all income levels including seniors and ''emerging households,'' endorsed the middle housing plan allowing duplexes/triplexes/cottage clusters, and supported the 2023 CPAH senior affordable housing project at the Beaverton Community Center (104 units, $10.5M Metro bond). His stated goal is that ''people who work here can afford to live here'' via targeted projects and easier permitting — not public ownership or broad rent caps. This aligns with chair 3: targeted subsidies for affordable projects, first-time buyer assistance, and easier permits.', ARRAY['https://www.edwardkimmi.com/priorities', 'https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/', 'https://beavertonvalleytimes.com/2023/05/03/new-affordable-housing-project-approved-at-beaverton-community-center/']::text[]),
    ('residential-zoning', 4, 'Kimmi explicitly endorsed the Beaverton Housing Options Project and ''the middle housing plan where we can build all different types of housing where it meets all the levels of the income,'' supporting duplexes, triplexes, quadplexes, and cottage clusters city-wide as required under state law. He also voted unanimously with the council to eliminate minimum parking requirements citywide in July 2023, reducing barriers to higher-density development. This pattern matches chair 4: broadly upzone to allow multifamily by right and reduce parking requirements.', ARRAY['https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/', 'https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://beavertonoregon.gov/399/Housing-Options-Project']::text[]),
    ('transportation-priorities', 1, 'Kimmi''s campaign explicitly prioritizes investment in ''innovative and smart transportation systems'' and backing the Downtown Loop project — a multimodal pedestrian/cycling/transit corridor on SW Hall Blvd and SW Watson Ave. He was part of the unanimous council vote in July 2023 eliminating citywide minimum parking requirements for new development. Taken together, these represent a clear pattern of prioritizing pedestrian infrastructure, cycling networks, public transit, and reducing parking requirements citywide — matching chair 1.', ARRAY['https://www.edwardkimmi.com/priorities', 'https://www.ballotready.org/people/edward-kimmi', 'https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://beavertonoregon.gov/420/Beaverton-Downtown-Loop-Project']::text[]),
    ('homelessness', 4, 'Kimmi voted YES on Ordinance 4841 (June 6, 2023), which bans homeless camping on Beaverton streets and sidewalks. The ordinance passed 4-1 (only then-Councilor Lacey Beaty dissented). The ordinance allows camping only between 9 p.m. and 7:30 a.m. for those without alternative shelter, using enforcement with warnings. Beaverton simultaneously maintained shelter options, which aligns with chair 4: prohibiting encampments on public property with graduated warnings and penalties while requiring jurisdictions to maintain basic shelter options.', ARRAY['https://katu.com/news/local/beaverton-city-council-passes-ordinance-to-ban-camping-on-streets-sidewalks', 'https://beaverton.municipal.codes/enactments/Ord4743', 'https://beaverton.municipal.codes/BC/5.18.040']::text[]),
    ('homelessness-response', 3, 'Kimmi''s campaign platform calls for ''enhance public safety with resources to address mental health crises and homelessness,'' and the council he is part of voted to fund and build Beaverton''s first year-round 24/7 shelter (opened November 2024, 60 guests, operated by Open Door with housing navigation and supportive services). He also supported the camping ordinance as an enforcement tool alongside those services. This balanced approach — invest in outreach, shelter, and mental health services while enforcing reasonable public space rules — matches chair 3.', ARRAY['https://www.edwardkimmi.com/priorities', 'https://www.ballotready.org/people/edward-kimmi', 'https://www.kptv.com/2024/11/19/city-beaverton-opens-first-247-homeless-shelter/', 'https://beavertonvalleytimes.com/2023/10/05/construction-for-beavertons-year-round-homeless-shelter-set-to-start-next-month/']::text[]),
    ('public-safety-approach', 3, 'Kimmi''s campaign platform calls for augmenting public safety ''with resources to address mental health crises and homelessness'' — indicating support for adding crisis response capacity alongside police. He voted YES in the 5-2 council vote (July 25, 2023) to keep armed Youth Services Officers in Beaverton schools under a two-year intergovernmental agreement, signaling he does not support defunding or significantly redirecting police. The combination of maintaining current police capacity while adding mental health/crisis resources matches chair 3.', ARRAY['https://www.edwardkimmi.com/priorities', 'https://www.kgw.com/article/sports/high-school/beaverton-council-school-youth-services-officers-armed-police-schools/283-83cdb8f4-3a61-4dff-a056-bf60dcad83ec', 'https://www.koin.com/news/education/beaverton-youth-service-officers-schools-07252023/']::text[]),
    ('local-immigration', 1, 'Kimmi co-authored amendments to Beaverton''s sanctuary city ordinance (Ord. 4877, passed Jan. 20, 2026) alongside Councilor Hasan. The ordinance prohibits city employees from providing immigration status information to federal agencies for enforcement purposes and bars city personnel from arresting or detaining anyone for immigration enforcement. Kimmi''s amendments added mandatory staff training on immigration law. He described the package as a ''compromise'' of what the council wanted to see, indicating he was pushing for strong protective measures. This matches chair 1: refuse ICE detainers; prohibit city employees from sharing immigration status with federal agencies.', ARRAY['https://beavertonvalleytimes.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/', 'https://youroregonnews.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/', 'https://katu.com/news/local/beaverton-city-council-discusses-oregons-sanctuary-promise-act']::text[]),
    ('climate-change', 3, 'Kimmi''s stated priority is to ''make tangible, measurable progress on our climate action goals.'' He noted his motivation for running included the disproportionate impact of climate change on low-income communities and communities of color. The council (including Kimmi) adopted an updated Climate Action Plan in February 2025 targeting net-zero by 2050. The language of ''measurable progress'' with a long-term plan — rather than emergency declarations or fossil fuel bans — aligns with chair 3: invest in clean energy while gradually reducing reliance on fossil fuels.', ARRAY['https://www.edwardkimmi.com/priorities', 'https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/', 'https://beavertonoregon.gov/1696/BCAP-Update']::text[]),
    ('economic-development', 2, 'Kimmi''s campaign priorities include ''invest in our entrepreneurs through business accelerators and grant programs'' and encourage ''a varied industry mix to expand job opportunities'' — focused on small businesses and local entrepreneurs rather than competing for large corporate employers with major tax abatements. He also noted the need to ''provide access and opportunity for all residents.'' This small-business-first approach with local grant programs and entrepreneur support matches chair 2.', ARRAY['https://www.edwardkimmi.com/priorities']::text[]),
    ('growth-and-development', 3, 'Kimmi acknowledged that growth brings ''more diversity in business opportunities'' and innovation but also ''more traffic, increasing housing costs and decrease in quality of life.'' He wants to ''connect the last mile where everyone has access to more transportation options,'' suggesting he views proactive infrastructure investment as the key to managing growth responsibly — rather than either blocking it or removing all regulatory barriers. This matches chair 3: plan proactively, invest in infrastructure ahead of growth to support responsible expansion.', ARRAY['https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/']::text[]),
    ('local-environment', 3, 'Kimmi supports the city''s Climate Action Plan and has described making ''tangible, measurable progress on climate action goals'' as a priority, which encompasses local environmental protections. His campaign materials emphasize ''resilient city'' language. However, no evidence shows him pushing for stricter-than-standard environmental review on development projects or opposing any development on environmental grounds. This suggests a consistent-standards approach matching chair 3: apply consistent environmental standards while giving developers reasonable flexibility on implementation.', ARRAY['https://www.edwardkimmi.com/priorities', 'https://beavertonoregon.gov/1696/BCAP-Update']::text[]),
    ('childcare', 3, 'Kimmi''s campaign states he will ''support conversations between local government and community partners about childcare and dependent care affordability'' — framing childcare as a community partnership issue rather than a direct government subsidy or universal program. This convening-and-partnership approach with targeted support for working families, without advocating for universal public childcare, matches chair 3: targeted tax credits/subsidies below an income threshold plus provider support through training and grants.', ARRAY['https://www.edwardkimmi.com/priorities']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT 'b3cadd4c-3e7b-46b5-b5a5-3b062493184b'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Kimmi has consistently supported affordable housing options for all income levels including seniors and ''emerging households,'' endorsed the middle housing plan allowing duplexes/triplexes/cottage clusters, and supported the 2023 CPAH senior affordable housing project at the Beaverton Community Center (104 units, $10.5M Metro bond). His stated goal is that ''people who work here can afford to live here'' via targeted projects and easier permitting — not public ownership or broad rent caps. This aligns with chair 3: targeted subsidies for affordable projects, first-time buyer assistance, and easier permits.', ARRAY['https://www.edwardkimmi.com/priorities', 'https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/', 'https://beavertonvalleytimes.com/2023/05/03/new-affordable-housing-project-approved-at-beaverton-community-center/']::text[]),
    ('residential-zoning', 4, 'Kimmi explicitly endorsed the Beaverton Housing Options Project and ''the middle housing plan where we can build all different types of housing where it meets all the levels of the income,'' supporting duplexes, triplexes, quadplexes, and cottage clusters city-wide as required under state law. He also voted unanimously with the council to eliminate minimum parking requirements citywide in July 2023, reducing barriers to higher-density development. This pattern matches chair 4: broadly upzone to allow multifamily by right and reduce parking requirements.', ARRAY['https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/', 'https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://beavertonoregon.gov/399/Housing-Options-Project']::text[]),
    ('transportation-priorities', 1, 'Kimmi''s campaign explicitly prioritizes investment in ''innovative and smart transportation systems'' and backing the Downtown Loop project — a multimodal pedestrian/cycling/transit corridor on SW Hall Blvd and SW Watson Ave. He was part of the unanimous council vote in July 2023 eliminating citywide minimum parking requirements for new development. Taken together, these represent a clear pattern of prioritizing pedestrian infrastructure, cycling networks, public transit, and reducing parking requirements citywide — matching chair 1.', ARRAY['https://www.edwardkimmi.com/priorities', 'https://www.ballotready.org/people/edward-kimmi', 'https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://beavertonoregon.gov/420/Beaverton-Downtown-Loop-Project']::text[]),
    ('homelessness', 4, 'Kimmi voted YES on Ordinance 4841 (June 6, 2023), which bans homeless camping on Beaverton streets and sidewalks. The ordinance passed 4-1 (only then-Councilor Lacey Beaty dissented). The ordinance allows camping only between 9 p.m. and 7:30 a.m. for those without alternative shelter, using enforcement with warnings. Beaverton simultaneously maintained shelter options, which aligns with chair 4: prohibiting encampments on public property with graduated warnings and penalties while requiring jurisdictions to maintain basic shelter options.', ARRAY['https://katu.com/news/local/beaverton-city-council-passes-ordinance-to-ban-camping-on-streets-sidewalks', 'https://beaverton.municipal.codes/enactments/Ord4743', 'https://beaverton.municipal.codes/BC/5.18.040']::text[]),
    ('homelessness-response', 3, 'Kimmi''s campaign platform calls for ''enhance public safety with resources to address mental health crises and homelessness,'' and the council he is part of voted to fund and build Beaverton''s first year-round 24/7 shelter (opened November 2024, 60 guests, operated by Open Door with housing navigation and supportive services). He also supported the camping ordinance as an enforcement tool alongside those services. This balanced approach — invest in outreach, shelter, and mental health services while enforcing reasonable public space rules — matches chair 3.', ARRAY['https://www.edwardkimmi.com/priorities', 'https://www.ballotready.org/people/edward-kimmi', 'https://www.kptv.com/2024/11/19/city-beaverton-opens-first-247-homeless-shelter/', 'https://beavertonvalleytimes.com/2023/10/05/construction-for-beavertons-year-round-homeless-shelter-set-to-start-next-month/']::text[]),
    ('public-safety-approach', 3, 'Kimmi''s campaign platform calls for augmenting public safety ''with resources to address mental health crises and homelessness'' — indicating support for adding crisis response capacity alongside police. He voted YES in the 5-2 council vote (July 25, 2023) to keep armed Youth Services Officers in Beaverton schools under a two-year intergovernmental agreement, signaling he does not support defunding or significantly redirecting police. The combination of maintaining current police capacity while adding mental health/crisis resources matches chair 3.', ARRAY['https://www.edwardkimmi.com/priorities', 'https://www.kgw.com/article/sports/high-school/beaverton-council-school-youth-services-officers-armed-police-schools/283-83cdb8f4-3a61-4dff-a056-bf60dcad83ec', 'https://www.koin.com/news/education/beaverton-youth-service-officers-schools-07252023/']::text[]),
    ('local-immigration', 1, 'Kimmi co-authored amendments to Beaverton''s sanctuary city ordinance (Ord. 4877, passed Jan. 20, 2026) alongside Councilor Hasan. The ordinance prohibits city employees from providing immigration status information to federal agencies for enforcement purposes and bars city personnel from arresting or detaining anyone for immigration enforcement. Kimmi''s amendments added mandatory staff training on immigration law. He described the package as a ''compromise'' of what the council wanted to see, indicating he was pushing for strong protective measures. This matches chair 1: refuse ICE detainers; prohibit city employees from sharing immigration status with federal agencies.', ARRAY['https://beavertonvalleytimes.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/', 'https://youroregonnews.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/', 'https://katu.com/news/local/beaverton-city-council-discusses-oregons-sanctuary-promise-act']::text[]),
    ('climate-change', 3, 'Kimmi''s stated priority is to ''make tangible, measurable progress on our climate action goals.'' He noted his motivation for running included the disproportionate impact of climate change on low-income communities and communities of color. The council (including Kimmi) adopted an updated Climate Action Plan in February 2025 targeting net-zero by 2050. The language of ''measurable progress'' with a long-term plan — rather than emergency declarations or fossil fuel bans — aligns with chair 3: invest in clean energy while gradually reducing reliance on fossil fuels.', ARRAY['https://www.edwardkimmi.com/priorities', 'https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/', 'https://beavertonoregon.gov/1696/BCAP-Update']::text[]),
    ('economic-development', 2, 'Kimmi''s campaign priorities include ''invest in our entrepreneurs through business accelerators and grant programs'' and encourage ''a varied industry mix to expand job opportunities'' — focused on small businesses and local entrepreneurs rather than competing for large corporate employers with major tax abatements. He also noted the need to ''provide access and opportunity for all residents.'' This small-business-first approach with local grant programs and entrepreneur support matches chair 2.', ARRAY['https://www.edwardkimmi.com/priorities']::text[]),
    ('growth-and-development', 3, 'Kimmi acknowledged that growth brings ''more diversity in business opportunities'' and innovation but also ''more traffic, increasing housing costs and decrease in quality of life.'' He wants to ''connect the last mile where everyone has access to more transportation options,'' suggesting he views proactive infrastructure investment as the key to managing growth responsibly — rather than either blocking it or removing all regulatory barriers. This matches chair 3: plan proactively, invest in infrastructure ahead of growth to support responsible expansion.', ARRAY['https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/']::text[]),
    ('local-environment', 3, 'Kimmi supports the city''s Climate Action Plan and has described making ''tangible, measurable progress on climate action goals'' as a priority, which encompasses local environmental protections. His campaign materials emphasize ''resilient city'' language. However, no evidence shows him pushing for stricter-than-standard environmental review on development projects or opposing any development on environmental grounds. This suggests a consistent-standards approach matching chair 3: apply consistent environmental standards while giving developers reasonable flexibility on implementation.', ARRAY['https://www.edwardkimmi.com/priorities', 'https://beavertonoregon.gov/1696/BCAP-Update']::text[]),
    ('childcare', 3, 'Kimmi''s campaign states he will ''support conversations between local government and community partners about childcare and dependent care affordability'' — framing childcare as a community partnership issue rather than a direct government subsidy or universal program. This convening-and-partnership approach with targeted support for working families, without advocating for universal public childcare, matches chair 3: targeted tax credits/subsidies below an income threshold plus provider support through training and grants.', ARRAY['https://www.edwardkimmi.com/priorities']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT 'b3cadd4c-3e7b-46b5-b5a5-3b062493184b'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
