-- Migration 1137: Allison Tivnon (Position 4) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 11 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('homelessness', 4, 'Tivnon co-crafted Beaverton''s Time, Place, and Manner camping ordinance (Ord. 4841, Jun 2023), which prohibits camping on public right-of-way with graduated warnings and penalties; she voted yes in the 7-0 passage of the Shelter Code ordinance (Feb 2023), expressing concern about neighbor impacts while supporting the motion. These actions place her squarely in the ''prohibit encampments with graduated warnings while requiring basic shelter'' posture.', ARRAY['https://www.beavertonoregon.gov/848/Councilor-Position-4', 'https://beaverton.granicus.com/DocumentViewer.php?file=beaverton_85207b6f45cd31338cdf273f9da2e613.pdf&view=1', 'https://katu.com/news/local/beaverton-city-council-passes-ordinance-to-ban-camping-on-streets-sidewalks', 'https://beaverton.municipal.codes/BC/5.18.040']::text[]),
    ('homelessness-response', 3, 'Tivnon helped secure the site for Beaverton''s first permanent year-round shelter (opened Nov 2024) and voted 7-0 for the Shelter Code ordinance updating standards and services access. She simultaneously co-authored the camping ordinance that enforces public-space rules. She expressed concern about adequate community outreach before locking in shelter sites — a service-investment posture, not strict enforcement-first. This combination — outreach + shelter capacity + reasonable enforcement — maps to chair 3.', ARRAY['https://www.beavertonoregon.gov/848/Councilor-Position-4', 'https://www.washingtoncountyor.gov/housing/news/2024/11/18/beaverton-shelter-joins-washington-county-shelter-program', 'https://youroregonnews.com/2024/02/21/beaverton-city-council-looks-back-at-six-months-of-new-camping-ordinances/']::text[]),
    ('housing', 3, 'Tivnon''s campaign explicitly lists affordable housing as a priority; she voted unanimously with the council to approve 104-unit affordable housing at the Beaverton Community Center ($10.5M Metro bond) and voted for code revisions to induce housing development. Her professional firm (ECONorthwest) focuses on housing finance and zoning. Her record favors targeted subsidies and permitting reform, not rent control or public construction, consistent with chair 3.', ARRAY['https://www.beavertonoregon.gov/848/Councilor-Position-4', 'https://businesstribune.online/2023/05/03/new-affordable-housing-project-approved-at-beaverton-community-center/', 'https://beavertonvalleytimes.com/2024/03/13/take-a-look-at-the-candidates-running-for-beaverton-city-council/']::text[]),
    ('residential-zoning', 4, 'Tivnon voted unanimously (7-0, Jul 2023) to eliminate citywide minimum parking requirements for new developments, a reform that facilitates denser housing by right. She also voted for the Housing Options Project code updates implementing HB 2001 middle-housing requirements (duplexes/triplexes citywide). Her ECONorthwest background in upzoning and her stated support for ''revising code and permitting requirements to induce additional housing development'' aligns with chair 4.', ARRAY['https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://beavertonoregon.gov/399/Housing-Options-Project', 'https://www.beavertonoregon.gov/848/Councilor-Position-4']::text[]),
    ('transportation-priorities', 1, 'Tivnon voted with the unanimous council to eliminate all minimum parking requirements citywide (Jul 2023) — explicitly to support housing and transit-oriented development — and her campaign lists ''vital transportation safety improvements'' and advocacy for active transportation as a top priority. Her firm works on transportation planning for cities and DOTs. The parking elimination vote + stated multimodal priority maps to chair 1.', ARRAY['https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://www.beavertonoregon.gov/848/Councilor-Position-4', 'https://beavertonvalleytimes.com/2024/03/13/take-a-look-at-the-candidates-running-for-beaverton-city-council/']::text[]),
    ('local-immigration', 1, 'Tivnon voted for Beaverton''s Sanctuary Promise Ordinance (Jan 20, 2026), which added a new chapter prohibiting city employees from sharing immigration-status information with federal agencies for enforcement purposes and barring city personnel from arresting or detaining anyone for immigration enforcement — the most protective chair. News coverage confirmed Tivnon''s endorsement of protecting immigrant communities.', ARRAY['https://beavertonvalleytimes.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/', 'https://youroregonnews.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/', 'https://katu.com/news/local/beaverton-city-council-discusses-oregons-sanctuary-promise-act']::text[]),
    ('public-safety-approach', 3, 'Tivnon voted yes in the 5-2 council vote to keep armed Youth Services Officers in Beaverton schools (Jul 2023), while also supporting the B-SOBR specialty DUII court as a treatment diversion alternative to incarceration. She advocated for the city''s public safety levy (Feb 2026), wanting to maintain and fund current levels of police service. This combination — no defunding, support for crisis-response alternatives alongside police funding — is chair 3.', ARRAY['https://www.kgw.com/article/sports/high-school/beaverton-council-school-youth-services-officers-armed-police-schools/283-83cdb8f4-3a61-4dff-a056-bf60dcad33ec', 'https://beavertonvalleytimes.com/2026/02/05/beaverton-to-wait-a-year-before-sending-public-safety-levy-ask-to-voters/', 'https://www.beavertonoregon.gov/848/Councilor-Position-4']::text[]),
    ('climate-change', 3, 'Tivnon''s campaign lists Beaverton''s climate action plan as a key priority she supports. The city''s Climate Action Plan (adopted 2019, updated 2025) targets carbon neutrality for city operations by 2030 and net-zero community emissions by 2050 — an invest-and-transition framework without an emergency declaration. Her stated commitment to diversity and the climate action plan is consistent with chair 3.', ARRAY['https://beavertonvalleytimes.com/2024/03/13/take-a-look-at-the-candidates-running-for-beaverton-city-council/', 'https://beavertonoregon.gov/1696/BCAP-Update', 'https://blog.energytrust.org/with-small-steps-beaverton-is-leading-the-way-in-climate-action/']::text[]),
    ('economic-development', 3, 'Tivnon serves on the BURA Board and has voted consistently for targeted downtown redevelopment, arts leases, parking management, and affordable-housing-inclusive development. She expressed hesitancy at a Metro advisory meeting (Dec 2024) about plans that would eliminate industrial land, preferring to protect industrial jobs while still attracting development — consistent with targeted incentives tied to community benefit, not blanket corporate subsidies.', ARRAY['https://beaverton.granicus.com/MetaViewer.php?view_id=11&clip_id=2934&meta_id=178658', 'https://www.beavertonoregon.gov/961/About-The-Beaverton-Urban-Redevelopment-', 'https://oregonmetro.legistar.com/View.ashx?GUID=EA478001-C6FD-40FA-A419-7E79BCEE63E5&ID=13646715&M=F']::text[]),
    ('taxes', 1, 'Facing a $10.7 million budget shortfall and cuts to police and library services, Tivnon stated publicly: ''This is an excellent time to start educating people about we don''t have a choice until our state legislature starts addressing very outdated (funding) measures that are hamstringing cities.'' She backed a new monthly utility fee to restore services, and supported the public safety levy. Her position is that cities need more revenue to fund public services — consistent with chair 1 (raise revenue to fund services) at the local level.', ARRAY['https://beavertonvalleytimes.com/2026/03/11/beaverton-looks-at-possible-monthly-fee-on-utility-bills-to-help-with-declining-revenues/', 'https://beavertonvalleytimes.com/2026/02/05/beaverton-to-wait-a-year-before-sending-public-safety-levy-ask-to-voters/']::text[]),
    ('growth-and-development', 3, 'Tivnon has consistently voted for development code reforms to accommodate housing growth (HOP, parking elimination) while also expressing concern about infrastructure timing and loss of industrial capacity. Her MPAC comments about industrial land being irreplaceable suggest she wants growth planned deliberately with infrastructure investment, not unchecked developer-led expansion — chair 3 (plan proactively, invest in infrastructure to support expansion).', ARRAY['https://beavertonvalleytimes.com/2024/03/13/take-a-look-at-the-candidates-running-for-beaverton-city-council/', 'https://beavertonoregon.gov/399/Housing-Options-Project', 'https://oregonmetro.legistar.com/View.ashx?GUID=EA478001-C6FD-40FA-A419-7E79BCEE63E5&ID=13646715&M=F']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT 'f9a8fdd0-c685-4692-a161-a7d8f8e01cc7'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('homelessness', 4, 'Tivnon co-crafted Beaverton''s Time, Place, and Manner camping ordinance (Ord. 4841, Jun 2023), which prohibits camping on public right-of-way with graduated warnings and penalties; she voted yes in the 7-0 passage of the Shelter Code ordinance (Feb 2023), expressing concern about neighbor impacts while supporting the motion. These actions place her squarely in the ''prohibit encampments with graduated warnings while requiring basic shelter'' posture.', ARRAY['https://www.beavertonoregon.gov/848/Councilor-Position-4', 'https://beaverton.granicus.com/DocumentViewer.php?file=beaverton_85207b6f45cd31338cdf273f9da2e613.pdf&view=1', 'https://katu.com/news/local/beaverton-city-council-passes-ordinance-to-ban-camping-on-streets-sidewalks', 'https://beaverton.municipal.codes/BC/5.18.040']::text[]),
    ('homelessness-response', 3, 'Tivnon helped secure the site for Beaverton''s first permanent year-round shelter (opened Nov 2024) and voted 7-0 for the Shelter Code ordinance updating standards and services access. She simultaneously co-authored the camping ordinance that enforces public-space rules. She expressed concern about adequate community outreach before locking in shelter sites — a service-investment posture, not strict enforcement-first. This combination — outreach + shelter capacity + reasonable enforcement — maps to chair 3.', ARRAY['https://www.beavertonoregon.gov/848/Councilor-Position-4', 'https://www.washingtoncountyor.gov/housing/news/2024/11/18/beaverton-shelter-joins-washington-county-shelter-program', 'https://youroregonnews.com/2024/02/21/beaverton-city-council-looks-back-at-six-months-of-new-camping-ordinances/']::text[]),
    ('housing', 3, 'Tivnon''s campaign explicitly lists affordable housing as a priority; she voted unanimously with the council to approve 104-unit affordable housing at the Beaverton Community Center ($10.5M Metro bond) and voted for code revisions to induce housing development. Her professional firm (ECONorthwest) focuses on housing finance and zoning. Her record favors targeted subsidies and permitting reform, not rent control or public construction, consistent with chair 3.', ARRAY['https://www.beavertonoregon.gov/848/Councilor-Position-4', 'https://businesstribune.online/2023/05/03/new-affordable-housing-project-approved-at-beaverton-community-center/', 'https://beavertonvalleytimes.com/2024/03/13/take-a-look-at-the-candidates-running-for-beaverton-city-council/']::text[]),
    ('residential-zoning', 4, 'Tivnon voted unanimously (7-0, Jul 2023) to eliminate citywide minimum parking requirements for new developments, a reform that facilitates denser housing by right. She also voted for the Housing Options Project code updates implementing HB 2001 middle-housing requirements (duplexes/triplexes citywide). Her ECONorthwest background in upzoning and her stated support for ''revising code and permitting requirements to induce additional housing development'' aligns with chair 4.', ARRAY['https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://beavertonoregon.gov/399/Housing-Options-Project', 'https://www.beavertonoregon.gov/848/Councilor-Position-4']::text[]),
    ('transportation-priorities', 1, 'Tivnon voted with the unanimous council to eliminate all minimum parking requirements citywide (Jul 2023) — explicitly to support housing and transit-oriented development — and her campaign lists ''vital transportation safety improvements'' and advocacy for active transportation as a top priority. Her firm works on transportation planning for cities and DOTs. The parking elimination vote + stated multimodal priority maps to chair 1.', ARRAY['https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://www.beavertonoregon.gov/848/Councilor-Position-4', 'https://beavertonvalleytimes.com/2024/03/13/take-a-look-at-the-candidates-running-for-beaverton-city-council/']::text[]),
    ('local-immigration', 1, 'Tivnon voted for Beaverton''s Sanctuary Promise Ordinance (Jan 20, 2026), which added a new chapter prohibiting city employees from sharing immigration-status information with federal agencies for enforcement purposes and barring city personnel from arresting or detaining anyone for immigration enforcement — the most protective chair. News coverage confirmed Tivnon''s endorsement of protecting immigrant communities.', ARRAY['https://beavertonvalleytimes.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/', 'https://youroregonnews.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/', 'https://katu.com/news/local/beaverton-city-council-discusses-oregons-sanctuary-promise-act']::text[]),
    ('public-safety-approach', 3, 'Tivnon voted yes in the 5-2 council vote to keep armed Youth Services Officers in Beaverton schools (Jul 2023), while also supporting the B-SOBR specialty DUII court as a treatment diversion alternative to incarceration. She advocated for the city''s public safety levy (Feb 2026), wanting to maintain and fund current levels of police service. This combination — no defunding, support for crisis-response alternatives alongside police funding — is chair 3.', ARRAY['https://www.kgw.com/article/sports/high-school/beaverton-council-school-youth-services-officers-armed-police-schools/283-83cdb8f4-3a61-4dff-a056-bf60dcad33ec', 'https://beavertonvalleytimes.com/2026/02/05/beaverton-to-wait-a-year-before-sending-public-safety-levy-ask-to-voters/', 'https://www.beavertonoregon.gov/848/Councilor-Position-4']::text[]),
    ('climate-change', 3, 'Tivnon''s campaign lists Beaverton''s climate action plan as a key priority she supports. The city''s Climate Action Plan (adopted 2019, updated 2025) targets carbon neutrality for city operations by 2030 and net-zero community emissions by 2050 — an invest-and-transition framework without an emergency declaration. Her stated commitment to diversity and the climate action plan is consistent with chair 3.', ARRAY['https://beavertonvalleytimes.com/2024/03/13/take-a-look-at-the-candidates-running-for-beaverton-city-council/', 'https://beavertonoregon.gov/1696/BCAP-Update', 'https://blog.energytrust.org/with-small-steps-beaverton-is-leading-the-way-in-climate-action/']::text[]),
    ('economic-development', 3, 'Tivnon serves on the BURA Board and has voted consistently for targeted downtown redevelopment, arts leases, parking management, and affordable-housing-inclusive development. She expressed hesitancy at a Metro advisory meeting (Dec 2024) about plans that would eliminate industrial land, preferring to protect industrial jobs while still attracting development — consistent with targeted incentives tied to community benefit, not blanket corporate subsidies.', ARRAY['https://beaverton.granicus.com/MetaViewer.php?view_id=11&clip_id=2934&meta_id=178658', 'https://www.beavertonoregon.gov/961/About-The-Beaverton-Urban-Redevelopment-', 'https://oregonmetro.legistar.com/View.ashx?GUID=EA478001-C6FD-40FA-A419-7E79BCEE63E5&ID=13646715&M=F']::text[]),
    ('taxes', 1, 'Facing a $10.7 million budget shortfall and cuts to police and library services, Tivnon stated publicly: ''This is an excellent time to start educating people about we don''t have a choice until our state legislature starts addressing very outdated (funding) measures that are hamstringing cities.'' She backed a new monthly utility fee to restore services, and supported the public safety levy. Her position is that cities need more revenue to fund public services — consistent with chair 1 (raise revenue to fund services) at the local level.', ARRAY['https://beavertonvalleytimes.com/2026/03/11/beaverton-looks-at-possible-monthly-fee-on-utility-bills-to-help-with-declining-revenues/', 'https://beavertonvalleytimes.com/2026/02/05/beaverton-to-wait-a-year-before-sending-public-safety-levy-ask-to-voters/']::text[]),
    ('growth-and-development', 3, 'Tivnon has consistently voted for development code reforms to accommodate housing growth (HOP, parking elimination) while also expressing concern about infrastructure timing and loss of industrial capacity. Her MPAC comments about industrial land being irreplaceable suggest she wants growth planned deliberately with infrastructure investment, not unchecked developer-led expansion — chair 3 (plan proactively, invest in infrastructure to support expansion).', ARRAY['https://beavertonvalleytimes.com/2024/03/13/take-a-look-at-the-candidates-running-for-beaverton-city-council/', 'https://beavertonoregon.gov/399/Housing-Options-Project', 'https://oregonmetro.legistar.com/View.ashx?GUID=EA478001-C6FD-40FA-A419-7E79BCEE63E5&ID=13646715&M=F']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT 'f9a8fdd0-c685-4692-a161-a7d8f8e01cc7'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
