-- Migration 1138: John Dugger (Position 5) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 15 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Dugger advocates building more housing supply — ''We have to get stuff built. Full stop.'' — including the Cooper Mountain annexation (5,500 mixed-type homes), zoning changes to allow duplexes/triplexes/ADUs, and increased system development charge waivers for affordable projects. His focus is on targeted supply-side help and permitting ease rather than public ownership or rent caps, placing him in the targeted-subsidy/easier-permits lane.', ARRAY['https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/', 'https://washcodems.org/2020/04/05/up-close-and-personal-candidate-john-dugger/']::text[]),
    ('residential-zoning', 4, 'Dugger explicitly supported Beaverton''s elimination of single-family-only zoning, advocating for ''middle housing'' — duplexes, triplexes, ADUs — and upzoning to allow multifamily on residential lots. He backed the 2023 parking-minimum elimination (passed unanimously) which removes a core barrier to denser development, and co-authored zoning changes to allow home-based childcare in residential areas. His stated goal is broad permission for middle housing without lot-size or type restrictions.', ARRAY['https://washcodems.org/2020/04/05/up-close-and-personal-candidate-john-dugger/', 'https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/']::text[]),
    ('homelessness', 4, 'Dugger voted yes on Ordinance 4841 (June 2023, 4-1 vote — Lacey Beaty was the lone no), which bans camping in public rights-of-way with a graduated warning and citation process. He publicly stated drafting the rules was ''a very difficult but ultimately necessary task.'' The ordinance allows 9 pm–7 am camping and prohibits it otherwise, aligning with chair 4 (prohibiting encampments with graduated penalties while maintaining basic shelter). Dugger also supported opening the city''s first permanent, year-round shelter alongside the ban.', ARRAY['https://katu.com/news/local/beaverton-city-council-passes-ordinance-to-ban-camping-on-streets-sidewalks', 'https://youroregonnews.com/2024/02/21/beaverton-city-council-looks-back-at-six-months-of-new-camping-ordinances/']::text[]),
    ('homelessness-response', 3, 'Dugger''s stated priority is addressing homelessness root causes (mental health, addiction, economic loss, domestic violence) while also supporting enforcement of reasonable public space rules. He championed Beaverton''s first trauma-informed permanent shelter and the bicycle patrol unit connecting people to services, and supported the camping ordinance that relies on outreach before citations. His public statements consistently frame both shelter/services investment and measured enforcement as co-equal tools.', ARRAY['https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/', 'https://beavertonvalleytimes.com/2026/04/28/john-dugger-seeks-another-term-on-beaverton-city-council/', 'https://youroregonnews.com/2024/02/21/beaverton-city-council-looks-back-at-six-months-of-new-camping-ordinances/']::text[]),
    ('transportation-priorities', 2, 'Dugger''s 2020 and 2022 platform explicitly prioritized pedestrian safety, bicycle lanes (including off-street routes), public transit, EV charging infrastructure, and traffic calming; he voted unanimously with the full council in July 2023 to eliminate parking minimums citywide. His 2026 campaign lists road safety as a specific legislative accomplishment. He does not propose defunding roads, but consistently ranks multimodal options as co-equal investments.', ARRAY['https://washcodems.org/2020/04/05/up-close-and-personal-candidate-john-dugger/', 'https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://beavertonvalleytimes.com/2026/04/28/john-dugger-seeks-another-term-on-beaverton-city-council/']::text[]),
    ('growth-and-development', 3, 'Dugger backs proactive infrastructure investment ahead of growth (water/WIFIA $140M investment, Cooper Mountain community plan), and consistently supports responsible expansion rather than growth limits or purely market-driven growth. He has expressed caution about fiscal sustainability, serving on a fiscal-sustainability subcommittee with the mayor, suggesting he wants infrastructure and finances to keep pace with development.', ARRAY['https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/', 'https://youroregonnews.com/2026/04/28/john-dugger-seeks-another-term-on-beaverton-city-council/']::text[]),
    ('public-safety-approach', 3, 'Dugger voted yes in July 2023 (5-2 vote, Hasan and Teater dissented) to keep armed Youth Services Officers in Beaverton schools with a two-year contract — indicating support for maintaining police in schools. He simultaneously pushed for neurodivergent de-escalation training extended department-wide, and backed the bicycle patrol co-responder model for homeless outreach. His approach keeps current police staffing but adds specialized crisis response capacity alongside it.', ARRAY['https://www.kgw.com/article/sports/high-school/beaverton-council-school-youth-services-officers-armed-police-schools/283-83cdb8f4-3a61-4dff-a056-bf60dcad33ec', 'https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/', 'https://youroregonnews.com/2024/02/21/beaverton-city-council-looks-back-at-six-months-of-new-camping-ordinances/']::text[]),
    ('local-immigration', 1, 'Dugger publicly championed codifying Beaverton''s sanctuary city resolution into Ordinance 4877 (adopted January 20, 2026), which prohibits city employees from sharing immigration status information with federal agencies and bars using city personnel for immigration enforcement. He also amended city policy so staff could join lawsuits against federal immigration overreach. His stated position aligns squarely with refusing ICE detainers and prohibiting city employees from sharing information with federal agencies.', ARRAY['https://beavertonvalleytimes.com/2026/04/28/john-dugger-seeks-another-term-on-beaverton-city-council/', 'https://youroregonnews.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/', 'https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/']::text[]),
    ('civil-rights', 2, 'Dugger maintained Beaverton''s DEI programs (funded via local property taxes) against federal executive order pressure and amended city policy to allow staff to join civil rights-related lawsuits against federal overreach. He is the first openly LGBTQIA+ person elected to the Beaverton City Council and co-founded Pride Beaverton. His actions go beyond merely maintaining existing civil rights laws to actively strengthening enforcement against discrimination and systemic interference.', ARRAY['https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/', 'https://youroregonnews.com/2026/04/28/john-dugger-seeks-another-term-on-beaverton-city-council/']::text[]),
    ('climate-change', 3, 'Dugger has a degree in environmental studies and supports Beaverton''s climate action plan (net-zero by 2050, 50% city ops fossil fuel reduction by 2030), calling for it to go further with urban forestry, EV infrastructure, and public transit investment. During his 2022 campaign he stated he would have voted for the existing climate plan, unlike his opponent. His proposals — investing in clean energy and reducing reliance on fossil fuels over time — align with chair 3.', ARRAY['https://washcodems.org/2020/04/06/john-dugger-candidate-interview/', 'https://washcodems.org/2020/04/05/up-close-and-personal-candidate-john-dugger/']::text[]),
    ('local-environment', 2, 'Dugger advocates for formal urban forestry and street-tree investment programs, protection of green space, and carbon-negative city goals. His platform includes aggressive urban forestry and neighborhood eco-districts, indicating he would require developers to offset environmental impacts rather than allow fee-in-lieu substitution.', ARRAY['https://washcodems.org/2020/04/05/up-close-and-personal-candidate-john-dugger/', 'https://washcodems.org/2020/04/06/john-dugger-candidate-interview/']::text[]),
    ('childcare', 3, 'Dugger led rezoning to allow home-based daycares in residential zones (previously restricted to commercial only), provided grants to help empty nesters become state-certified providers, and funded code-improvement loans — creating ''a couple hundred childcare units.'' He also incorporated a Head Start childcare program on the ground floor of a 104-unit mixed-use senior housing development. His approach is targeted subsidies and regulatory reforms for affordability, not universal public funding.', ARRAY['https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/']::text[]),
    ('economic-development', 3, 'Dugger is updating Beaverton''s economic development strategy to target industries suited to local land and talent (not blanket incentives), supports the IMPACT program for small businesses, and advocates for entrepreneur resources and storefront improvements. His stated approach is ''targeted incentives for specific industries'' with community-fit requirements — neither refusing all incentives nor offering maximum abatements to any large employer.', ARRAY['https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/', 'https://washcodems.org/2020/04/05/up-close-and-personal-candidate-john-dugger/']::text[]),
    ('campaign-finance', 2, 'Dugger''s 2020 platform explicitly called for ''reviewing and implementing local campaign finance limits to keep our elections people-driven,'' and his campaign declined donations from large businesses, accepting only small business and individual donors. This positions him in favor of strict limits on corporate donations to keep campaigns small-donor-driven.', ARRAY['https://washcodems.org/2020/04/05/up-close-and-personal-candidate-john-dugger/']::text[]),
    ('city-sanitation', 3, 'Dugger negotiated waste hauler contract expansions to add mid-tier bulk pickup options (reducing costs from ~$1,200 to ~$400-500 per pickup), prioritizing affordability and service access over major staffing expansion or enforcement-only approaches. This aligns with maintaining current services with improved access, consistent with chair 3.', ARRAY['https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '11427932-a17e-4898-8258-ec8c8bf7709f'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Dugger advocates building more housing supply — ''We have to get stuff built. Full stop.'' — including the Cooper Mountain annexation (5,500 mixed-type homes), zoning changes to allow duplexes/triplexes/ADUs, and increased system development charge waivers for affordable projects. His focus is on targeted supply-side help and permitting ease rather than public ownership or rent caps, placing him in the targeted-subsidy/easier-permits lane.', ARRAY['https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/', 'https://washcodems.org/2020/04/05/up-close-and-personal-candidate-john-dugger/']::text[]),
    ('residential-zoning', 4, 'Dugger explicitly supported Beaverton''s elimination of single-family-only zoning, advocating for ''middle housing'' — duplexes, triplexes, ADUs — and upzoning to allow multifamily on residential lots. He backed the 2023 parking-minimum elimination (passed unanimously) which removes a core barrier to denser development, and co-authored zoning changes to allow home-based childcare in residential areas. His stated goal is broad permission for middle housing without lot-size or type restrictions.', ARRAY['https://washcodems.org/2020/04/05/up-close-and-personal-candidate-john-dugger/', 'https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/']::text[]),
    ('homelessness', 4, 'Dugger voted yes on Ordinance 4841 (June 2023, 4-1 vote — Lacey Beaty was the lone no), which bans camping in public rights-of-way with a graduated warning and citation process. He publicly stated drafting the rules was ''a very difficult but ultimately necessary task.'' The ordinance allows 9 pm–7 am camping and prohibits it otherwise, aligning with chair 4 (prohibiting encampments with graduated penalties while maintaining basic shelter). Dugger also supported opening the city''s first permanent, year-round shelter alongside the ban.', ARRAY['https://katu.com/news/local/beaverton-city-council-passes-ordinance-to-ban-camping-on-streets-sidewalks', 'https://youroregonnews.com/2024/02/21/beaverton-city-council-looks-back-at-six-months-of-new-camping-ordinances/']::text[]),
    ('homelessness-response', 3, 'Dugger''s stated priority is addressing homelessness root causes (mental health, addiction, economic loss, domestic violence) while also supporting enforcement of reasonable public space rules. He championed Beaverton''s first trauma-informed permanent shelter and the bicycle patrol unit connecting people to services, and supported the camping ordinance that relies on outreach before citations. His public statements consistently frame both shelter/services investment and measured enforcement as co-equal tools.', ARRAY['https://beavertonvalleytimes.com/2022/04/28/qa-get-to-know-beaverton-city-council-candidates/', 'https://beavertonvalleytimes.com/2026/04/28/john-dugger-seeks-another-term-on-beaverton-city-council/', 'https://youroregonnews.com/2024/02/21/beaverton-city-council-looks-back-at-six-months-of-new-camping-ordinances/']::text[]),
    ('transportation-priorities', 2, 'Dugger''s 2020 and 2022 platform explicitly prioritized pedestrian safety, bicycle lanes (including off-street routes), public transit, EV charging infrastructure, and traffic calming; he voted unanimously with the full council in July 2023 to eliminate parking minimums citywide. His 2026 campaign lists road safety as a specific legislative accomplishment. He does not propose defunding roads, but consistently ranks multimodal options as co-equal investments.', ARRAY['https://washcodems.org/2020/04/05/up-close-and-personal-candidate-john-dugger/', 'https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://beavertonvalleytimes.com/2026/04/28/john-dugger-seeks-another-term-on-beaverton-city-council/']::text[]),
    ('growth-and-development', 3, 'Dugger backs proactive infrastructure investment ahead of growth (water/WIFIA $140M investment, Cooper Mountain community plan), and consistently supports responsible expansion rather than growth limits or purely market-driven growth. He has expressed caution about fiscal sustainability, serving on a fiscal-sustainability subcommittee with the mayor, suggesting he wants infrastructure and finances to keep pace with development.', ARRAY['https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/', 'https://youroregonnews.com/2026/04/28/john-dugger-seeks-another-term-on-beaverton-city-council/']::text[]),
    ('public-safety-approach', 3, 'Dugger voted yes in July 2023 (5-2 vote, Hasan and Teater dissented) to keep armed Youth Services Officers in Beaverton schools with a two-year contract — indicating support for maintaining police in schools. He simultaneously pushed for neurodivergent de-escalation training extended department-wide, and backed the bicycle patrol co-responder model for homeless outreach. His approach keeps current police staffing but adds specialized crisis response capacity alongside it.', ARRAY['https://www.kgw.com/article/sports/high-school/beaverton-council-school-youth-services-officers-armed-police-schools/283-83cdb8f4-3a61-4dff-a056-bf60dcad33ec', 'https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/', 'https://youroregonnews.com/2024/02/21/beaverton-city-council-looks-back-at-six-months-of-new-camping-ordinances/']::text[]),
    ('local-immigration', 1, 'Dugger publicly championed codifying Beaverton''s sanctuary city resolution into Ordinance 4877 (adopted January 20, 2026), which prohibits city employees from sharing immigration status information with federal agencies and bars using city personnel for immigration enforcement. He also amended city policy so staff could join lawsuits against federal immigration overreach. His stated position aligns squarely with refusing ICE detainers and prohibiting city employees from sharing information with federal agencies.', ARRAY['https://beavertonvalleytimes.com/2026/04/28/john-dugger-seeks-another-term-on-beaverton-city-council/', 'https://youroregonnews.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/', 'https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/']::text[]),
    ('civil-rights', 2, 'Dugger maintained Beaverton''s DEI programs (funded via local property taxes) against federal executive order pressure and amended city policy to allow staff to join civil rights-related lawsuits against federal overreach. He is the first openly LGBTQIA+ person elected to the Beaverton City Council and co-founded Pride Beaverton. His actions go beyond merely maintaining existing civil rights laws to actively strengthening enforcement against discrimination and systemic interference.', ARRAY['https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/', 'https://youroregonnews.com/2026/04/28/john-dugger-seeks-another-term-on-beaverton-city-council/']::text[]),
    ('climate-change', 3, 'Dugger has a degree in environmental studies and supports Beaverton''s climate action plan (net-zero by 2050, 50% city ops fossil fuel reduction by 2030), calling for it to go further with urban forestry, EV infrastructure, and public transit investment. During his 2022 campaign he stated he would have voted for the existing climate plan, unlike his opponent. His proposals — investing in clean energy and reducing reliance on fossil fuels over time — align with chair 3.', ARRAY['https://washcodems.org/2020/04/06/john-dugger-candidate-interview/', 'https://washcodems.org/2020/04/05/up-close-and-personal-candidate-john-dugger/']::text[]),
    ('local-environment', 2, 'Dugger advocates for formal urban forestry and street-tree investment programs, protection of green space, and carbon-negative city goals. His platform includes aggressive urban forestry and neighborhood eco-districts, indicating he would require developers to offset environmental impacts rather than allow fee-in-lieu substitution.', ARRAY['https://washcodems.org/2020/04/05/up-close-and-personal-candidate-john-dugger/', 'https://washcodems.org/2020/04/06/john-dugger-candidate-interview/']::text[]),
    ('childcare', 3, 'Dugger led rezoning to allow home-based daycares in residential zones (previously restricted to commercial only), provided grants to help empty nesters become state-certified providers, and funded code-improvement loans — creating ''a couple hundred childcare units.'' He also incorporated a Head Start childcare program on the ground floor of a 104-unit mixed-use senior housing development. His approach is targeted subsidies and regulatory reforms for affordability, not universal public funding.', ARRAY['https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/']::text[]),
    ('economic-development', 3, 'Dugger is updating Beaverton''s economic development strategy to target industries suited to local land and talent (not blanket incentives), supports the IMPACT program for small businesses, and advocates for entrepreneur resources and storefront improvements. His stated approach is ''targeted incentives for specific industries'' with community-fit requirements — neither refusing all incentives nor offering maximum abatements to any large employer.', ARRAY['https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/', 'https://washcodems.org/2020/04/05/up-close-and-personal-candidate-john-dugger/']::text[]),
    ('campaign-finance', 2, 'Dugger''s 2020 platform explicitly called for ''reviewing and implementing local campaign finance limits to keep our elections people-driven,'' and his campaign declined donations from large businesses, accepting only small business and individual donors. This positions him in favor of strict limits on corporate donations to keep campaigns small-donor-driven.', ARRAY['https://washcodems.org/2020/04/05/up-close-and-personal-candidate-john-dugger/']::text[]),
    ('city-sanitation', 3, 'Dugger negotiated waste hauler contract expansions to add mid-tier bulk pickup options (reducing costs from ~$1,200 to ~$400-500 per pickup), prioritizing affordability and service access over major staffing expansion or enforcement-only approaches. This aligns with maintaining current services with improved access, consistent with chair 3.', ARRAY['https://washcodems.org/2026/04/28/john-dugger-beaverton-city-council-position-5-candidate-interview/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '11427932-a17e-4898-8258-ec8c8bf7709f'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
