-- Migration 1139: Nadia Hasan (Position 6) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 12 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 2, 'Hasan states housing is a "fundamental human right" and has directed $2.3M in affordable housing investments on council. Her priorities page lists rent protections, middle housing initiatives, ADUs, and publicly funded affordable units (Metro bond). She supports mandatory affordable unit inclusion in new developments and renter protections — exceeding targeted-subsidy approaches but stopping short of publicly built and operated housing.', ARRAY['https://nadiaforbeaverton.com/priorities', 'https://washcodems.org/2024/04/21/nadia-hasan-beaverton-city-council-candidate-interview/', 'https://beavertonvalleytimes.com/2023/05/03/new-affordable-housing-project-approved-at-beaverton-community-center/']::text[]),
    ('homelessness', 3, 'Hasan voted YES on Ordinance 4841 (June 2023, 4-1, only Mayor Beaty dissented), which bans public camping on streets/sidewalks while allowing nighttime camping 9pm–7am as Oregon HB 3115 requires. She simultaneously worked to create Beaverton''s first year-round shelter (opened Nov 2024) and voted 7-0 for Ord. 4838 updating shelter code (Feb 2023). This pattern — regulated camping restrictions only when shelter is available, citations diverting to services — matches chair 3.', ARRAY['https://beaverton.municipal.codes/BC/5.18.040', 'https://katu.com/news/local/beaverton-city-council-passes-ordinance-to-ban-camping-on-streets-sidewalks', 'https://beaverton.granicus.com/DocumentViewer.php?file=beaverton_85207b6f45cd31338cdf273f9da2e613.pdf&view=1']::text[]),
    ('homelessness-response', 2, 'Hasan championed creation of Beaverton''s first year-round 60-bed shelter (opened Nov 2024) with 24/7 meals, showers, and service connections as the primary homelessness strategy. She directed $2.3M toward affordable housing investments and voted for updated shelter code Ord. 4838 (7-0). Her stated priority is connecting people to housing programs and outreach workers, with camping enforcement as a secondary tool after services are offered.', ARRAY['https://nadiaforbeaverton.com/priorities', 'https://www.washingtoncountyor.gov/housing/news/2024/11/18/beaverton-shelter-joins-washington-county-shelter-program', 'https://beaverton.granicus.com/DocumentViewer.php?file=beaverton_85207b6f45cd31338cdf273f9da2e613.pdf&view=1']::text[]),
    ('residential-zoning', 4, 'Hasan supports middle housing initiatives, ADUs, and increased density. She voted unanimously (7-0) with the council to eliminate all minimum parking requirements citywide (July 2023), explicitly as a Climate Equitable and Friendly Communities measure to reduce development costs and increase housing supply. Her priorities page cites middle housing and ADUs as key tools. Eliminating parking minimums citywide while supporting middle housing by right reflects broad upzoning/streamlined-approval posture.', ARRAY['https://nadiaforbeaverton.com/priorities', 'https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://washcodems.org/2024/04/21/nadia-hasan-beaverton-city-council-candidate-interview/']::text[]),
    ('transportation-priorities', 1, 'Hasan sponsored and passed the Beaverton Complete Streets Policy (emphasizing biking, walking, and transit) and championed parking minimum elimination citywide. She lists transportation access without a car as a right and has driven investment in EV charging and public transit as a Metro Policy Advisory Commission member. Her priorities explicitly frame transportation as a climate and equity issue with pedestrian/cycling/transit infrastructure as the top investment.', ARRAY['https://nadiaforbeaverton.com/priorities', 'https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://www.beavertonoregon.gov/1585/Beaverton-Complete-Streets-Policy']::text[]),
    ('climate-change', 3, 'Hasan fought to make tree canopy a council priority and led elimination of parking minimums as part of the city''s Climate Equitable and Friendly Communities initiative. She supports investing in EV charging, public transit, and sustainable infrastructure, and states clean water and clean air as priorities. Her actions are substantial — removing parking minimums, expanding tree canopy, transit investment — but stop short of declaring a climate emergency or a 2030 fossil-fuel-free pledge.', ARRAY['https://nadiaforbeaverton.com/priorities', 'https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://washcodems.org/2024/04/21/nadia-hasan-beaverton-city-council-candidate-interview/']::text[]),
    ('local-environment', 2, 'Hasan made increasing tree canopy in vulnerable neighborhoods a council priority, and drove the parking minimum elimination in part as an environmental measure. Her priorities page explicitly names tree canopy conservation and offset requirements for development as goals. Her overall framing is "conserving natural resources" and requiring developers to fully offset environmental impact.', ARRAY['https://nadiaforbeaverton.com/priorities', 'https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/']::text[]),
    ('local-immigration', 1, 'Hasan co-authored amendments to Ordinance 4877 (Jan 20, 2026) that prohibit city employees from sharing immigration status with federal agencies and bar city personnel from arresting or detaining for immigration enforcement. She then proposed going further: directing Beaverton police to stop unmarked federal vehicles driving recklessly, document excessive force by ICE agents, and refer criminal violations to the DA. She stated "I want our officers to do more" — this is the most protective posture available to a local government.', ARRAY['https://beavertonvalleytimes.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/', 'https://katu.com/news/local/beaverton-mayor-lacey-beaty-councilors-nadia-hasan-kevin-teater-considers-having-officers-investigate-federal-immigration-ice-agents', 'https://youroregonnews.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/']::text[]),
    ('civil-rights', 2, 'Hasan established Beaverton''s equity office — a formal institutional mechanism to address systemic discrimination. She describes herself as "passionate about dismantling racism and building equitable systems" and has prioritized uplifting underrepresented voices throughout her tenure. Her background includes racial and immigrant justice advocacy. Establishing a city equity office exceeds maintaining current civil rights laws but falls short of mandating racial equity requirements in all institutions.', ARRAY['https://nadiaforbeaverton.com/about-me', 'https://washcodems.org/2024/04/21/nadia-hasan-beaverton-city-council-candidate-interview/', 'https://nadiaforbeaverton.com/priorities']::text[]),
    ('public-safety-approach', 2, 'Hasan voted NO (5-2, July 2023) on the Youth Services Officers IGA to keep armed officers in Beaverton schools, citing lack of specificity in safeguards for marginalized students. She stated: "I was elected to use my voice to ask the hard questions, and I did that by voting no." Her stated public safety priority is ensuring "all diverse groups feel safe" and partnering with police on community-specific strategy — not defunding, but shifting non-violent response to targeted crisis co-responders.', ARRAY['https://www.kgw.com/article/sports/high-school/beaverton-council-school-youth-services-officers-armed-police-schools/283-83cdb8f4-3a61-4dff-a056-bf60dcad33ec', 'https://www.kptv.com/2023/07/25/beaverton-city-council-vote-school-resource-officer-agreement/', 'https://washcodems.org/2024/04/21/nadia-hasan-beaverton-city-council-candidate-interview/']::text[]),
    ('economic-development', 2, 'Hasan invested $2M into small business recovery grants, adopted the Downtown Equity Strategy for redevelopment, and championed Business Improvement Grants for local businesses. She supports arts/culture/entertainment investment and expanded services for job seekers and emerging entrepreneurs. Her explicit focus is local/small business support and an equity-based downtown strategy — not major corporate tax abatements or competing for large employers with tax incentives.', ARRAY['https://nadiaforbeaverton.com/priorities', 'https://washcodems.org/2024/04/21/nadia-hasan-beaverton-city-council-candidate-interview/']::text[]),
    ('growth-and-development', 3, 'Hasan''s priorities emphasize proactive infrastructure investment to support growth — transit, Complete Streets, affordable housing pre-investment with Metro bond. She voted 7-0 for routine annexations with proper land use review. Her framing is planned, equity-focused growth rather than growth limits OR deregulated developer-led growth. Her Complete Streets and parking elimination policies show investment ahead of growth to support responsible expansion.', ARRAY['https://nadiaforbeaverton.com/priorities', 'https://citizenportal.ai/articles/6668358/oregon/washington-county/beaverton/Beaverton/Washington-County/Oregon/Votes-at-a-glance-Beaverton-council-approves-annexation-map-amendments-and-zoning-change-consent-agenda-passes-unanimously']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT 'f5867b19-d040-4a95-b558-475e5469a945'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 2, 'Hasan states housing is a "fundamental human right" and has directed $2.3M in affordable housing investments on council. Her priorities page lists rent protections, middle housing initiatives, ADUs, and publicly funded affordable units (Metro bond). She supports mandatory affordable unit inclusion in new developments and renter protections — exceeding targeted-subsidy approaches but stopping short of publicly built and operated housing.', ARRAY['https://nadiaforbeaverton.com/priorities', 'https://washcodems.org/2024/04/21/nadia-hasan-beaverton-city-council-candidate-interview/', 'https://beavertonvalleytimes.com/2023/05/03/new-affordable-housing-project-approved-at-beaverton-community-center/']::text[]),
    ('homelessness', 3, 'Hasan voted YES on Ordinance 4841 (June 2023, 4-1, only Mayor Beaty dissented), which bans public camping on streets/sidewalks while allowing nighttime camping 9pm–7am as Oregon HB 3115 requires. She simultaneously worked to create Beaverton''s first year-round shelter (opened Nov 2024) and voted 7-0 for Ord. 4838 updating shelter code (Feb 2023). This pattern — regulated camping restrictions only when shelter is available, citations diverting to services — matches chair 3.', ARRAY['https://beaverton.municipal.codes/BC/5.18.040', 'https://katu.com/news/local/beaverton-city-council-passes-ordinance-to-ban-camping-on-streets-sidewalks', 'https://beaverton.granicus.com/DocumentViewer.php?file=beaverton_85207b6f45cd31338cdf273f9da2e613.pdf&view=1']::text[]),
    ('homelessness-response', 2, 'Hasan championed creation of Beaverton''s first year-round 60-bed shelter (opened Nov 2024) with 24/7 meals, showers, and service connections as the primary homelessness strategy. She directed $2.3M toward affordable housing investments and voted for updated shelter code Ord. 4838 (7-0). Her stated priority is connecting people to housing programs and outreach workers, with camping enforcement as a secondary tool after services are offered.', ARRAY['https://nadiaforbeaverton.com/priorities', 'https://www.washingtoncountyor.gov/housing/news/2024/11/18/beaverton-shelter-joins-washington-county-shelter-program', 'https://beaverton.granicus.com/DocumentViewer.php?file=beaverton_85207b6f45cd31338cdf273f9da2e613.pdf&view=1']::text[]),
    ('residential-zoning', 4, 'Hasan supports middle housing initiatives, ADUs, and increased density. She voted unanimously (7-0) with the council to eliminate all minimum parking requirements citywide (July 2023), explicitly as a Climate Equitable and Friendly Communities measure to reduce development costs and increase housing supply. Her priorities page cites middle housing and ADUs as key tools. Eliminating parking minimums citywide while supporting middle housing by right reflects broad upzoning/streamlined-approval posture.', ARRAY['https://nadiaforbeaverton.com/priorities', 'https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://washcodems.org/2024/04/21/nadia-hasan-beaverton-city-council-candidate-interview/']::text[]),
    ('transportation-priorities', 1, 'Hasan sponsored and passed the Beaverton Complete Streets Policy (emphasizing biking, walking, and transit) and championed parking minimum elimination citywide. She lists transportation access without a car as a right and has driven investment in EV charging and public transit as a Metro Policy Advisory Commission member. Her priorities explicitly frame transportation as a climate and equity issue with pedestrian/cycling/transit infrastructure as the top investment.', ARRAY['https://nadiaforbeaverton.com/priorities', 'https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://www.beavertonoregon.gov/1585/Beaverton-Complete-Streets-Policy']::text[]),
    ('climate-change', 3, 'Hasan fought to make tree canopy a council priority and led elimination of parking minimums as part of the city''s Climate Equitable and Friendly Communities initiative. She supports investing in EV charging, public transit, and sustainable infrastructure, and states clean water and clean air as priorities. Her actions are substantial — removing parking minimums, expanding tree canopy, transit investment — but stop short of declaring a climate emergency or a 2030 fossil-fuel-free pledge.', ARRAY['https://nadiaforbeaverton.com/priorities', 'https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/', 'https://washcodems.org/2024/04/21/nadia-hasan-beaverton-city-council-candidate-interview/']::text[]),
    ('local-environment', 2, 'Hasan made increasing tree canopy in vulnerable neighborhoods a council priority, and drove the parking minimum elimination in part as an environmental measure. Her priorities page explicitly names tree canopy conservation and offset requirements for development as goals. Her overall framing is "conserving natural resources" and requiring developers to fully offset environmental impact.', ARRAY['https://nadiaforbeaverton.com/priorities', 'https://www.opb.org/article/2023/07/24/beaverton-council-votes-to-eliminate-minimum-parking-requirements-for-new-projects/']::text[]),
    ('local-immigration', 1, 'Hasan co-authored amendments to Ordinance 4877 (Jan 20, 2026) that prohibit city employees from sharing immigration status with federal agencies and bar city personnel from arresting or detaining for immigration enforcement. She then proposed going further: directing Beaverton police to stop unmarked federal vehicles driving recklessly, document excessive force by ICE agents, and refer criminal violations to the DA. She stated "I want our officers to do more" — this is the most protective posture available to a local government.', ARRAY['https://beavertonvalleytimes.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/', 'https://katu.com/news/local/beaverton-mayor-lacey-beaty-councilors-nadia-hasan-kevin-teater-considers-having-officers-investigate-federal-immigration-ice-agents', 'https://youroregonnews.com/2026/01/27/beaverton-hones-sanctuary-city-code-preventing-city-employees-from-helping-ice-officials/']::text[]),
    ('civil-rights', 2, 'Hasan established Beaverton''s equity office — a formal institutional mechanism to address systemic discrimination. She describes herself as "passionate about dismantling racism and building equitable systems" and has prioritized uplifting underrepresented voices throughout her tenure. Her background includes racial and immigrant justice advocacy. Establishing a city equity office exceeds maintaining current civil rights laws but falls short of mandating racial equity requirements in all institutions.', ARRAY['https://nadiaforbeaverton.com/about-me', 'https://washcodems.org/2024/04/21/nadia-hasan-beaverton-city-council-candidate-interview/', 'https://nadiaforbeaverton.com/priorities']::text[]),
    ('public-safety-approach', 2, 'Hasan voted NO (5-2, July 2023) on the Youth Services Officers IGA to keep armed officers in Beaverton schools, citing lack of specificity in safeguards for marginalized students. She stated: "I was elected to use my voice to ask the hard questions, and I did that by voting no." Her stated public safety priority is ensuring "all diverse groups feel safe" and partnering with police on community-specific strategy — not defunding, but shifting non-violent response to targeted crisis co-responders.', ARRAY['https://www.kgw.com/article/sports/high-school/beaverton-council-school-youth-services-officers-armed-police-schools/283-83cdb8f4-3a61-4dff-a056-bf60dcad33ec', 'https://www.kptv.com/2023/07/25/beaverton-city-council-vote-school-resource-officer-agreement/', 'https://washcodems.org/2024/04/21/nadia-hasan-beaverton-city-council-candidate-interview/']::text[]),
    ('economic-development', 2, 'Hasan invested $2M into small business recovery grants, adopted the Downtown Equity Strategy for redevelopment, and championed Business Improvement Grants for local businesses. She supports arts/culture/entertainment investment and expanded services for job seekers and emerging entrepreneurs. Her explicit focus is local/small business support and an equity-based downtown strategy — not major corporate tax abatements or competing for large employers with tax incentives.', ARRAY['https://nadiaforbeaverton.com/priorities', 'https://washcodems.org/2024/04/21/nadia-hasan-beaverton-city-council-candidate-interview/']::text[]),
    ('growth-and-development', 3, 'Hasan''s priorities emphasize proactive infrastructure investment to support growth — transit, Complete Streets, affordable housing pre-investment with Metro bond. She voted 7-0 for routine annexations with proper land use review. Her framing is planned, equity-focused growth rather than growth limits OR deregulated developer-led growth. Her Complete Streets and parking elimination policies show investment ahead of growth to support responsible expansion.', ARRAY['https://nadiaforbeaverton.com/priorities', 'https://citizenportal.ai/articles/6668358/oregon/washington-county/beaverton/Beaverton/Washington-County/Oregon/Votes-at-a-glance-Beaverton-council-approves-annexation-map-amendments-and-zoning-change-consent-agenda-passes-unanimously']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT 'f5867b19-d040-4a95-b558-475e5469a945'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
