-- Migration 1152: Beach Pace (Mayor, Hillsboro OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 9 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('local-immigration', 1, 'As Mayor, Pace issued a joint October 2025 statement with Police Chief Jim Coleman reaffirming Hillsboro is a sanctuary city whose police "does not coordinate with federal immigration authorities." She then presided over the unanimous Nov 18, 2025 state-of-emergency resolution condemning ICE conduct (detentions without due process), and the unanimous Nov 24, 2025 five-point response plan that paused the city''s automated license plate readers (cutting a data channel to federal agencies), added ICE-warrant-required signage on city facilities, funded $400K in grants to impacted families/businesses, and directed evaluation of strengthening sanctuary status. Matches Chair 1 (refuse all ICE detainers; prohibit city employees from sharing immigration status).', ARRAY['https://hillsboronewstimes.com/2025/11/05/hillsboro-residents-call-for-city-action-as-ice-raids-immigration-enforcement-fears-grow/', 'https://hillsboroherald.com/hillsboro-city-council-reaches-unanimous-agreement-on-plan-to-respond-to-ice/', 'https://www.kptv.com/2025/11/19/hillsboro-declares-state-emergency-amid-increased-ice-activity/']::text[]),
    ('homelessness-response', 2, 'Pace championed the Safe Rest Pods (served 196 people, connected 178 to housing assessments) as a councilor, calling affordable housing and safe rest pods her proudest accomplishment (Aug 2024), and as Mayor delivered Hillsboro''s first year-round 75-bed shelter ($17M; opened Nov 14, 2025). At the March 3, 2025 groundbreaking she said the city is "committed to supporting efforts that provide compassionate care and pathways to housing while also addressing the impacts of homelessness on businesses and our community"; in Sept 2025 she framed the goal as getting "folks off the street and into support... services that they can use and get themselves back on their feet and into more regular housing." Matches Chair 2 (expand shelter capacity and services as the primary strategy; use enforcement only after).', ARRAY['https://www.washingtoncountyor.gov/housing/news/2025/03/03/hillsboro-year-round-shelter-celebrates-groundbreaking', 'https://katu.com/news/local/hillsboro-to-open-year-round-homeless-shelter-with-75-capacity-pets-welcome-homelessness-oregon-portland-suburbs-baseline-bonamici-project-funding', 'https://outnw.com/queer-politicians-q-a-beach-pace-for-mayor-of-hillsboro-or/']::text[]),
    ('housing', 2, 'In her 2018 council campaign she explicitly backed inclusionary zoning requiring "a percentage of affordable units," supported Measure 102 and the Metro affordable housing bond (public funding of new affordable housing), plus city land acquisition and public-private partnerships. As Mayor (Aug 2025) she greenlit an affordable housing development on TriMet property, calling it "the best of what transit-oriented development can be - and helps to address our community''s need for affordable housing." No rent-cap statement found; match rests on the require-affordable-units + publicly-fund elements of Chair 2.', ARRAY['https://hillsborosignal.com/2018/10/27/conversation-with-city-council-candidate-beach-pace/', 'https://hillsboronewstimes.com/2025/08/21/hillsboro-greenlights-proposal-for-affordable-housing-development-on-trimet-property/']::text[]),
    ('data-centers', 3, 'Pace defends continued data center development and its economic benefits (May 2026 city video: "economic development has been able to provide the city some pretty amazing things like the Hidden Creek Community Center, fire stations, emergency vehicles and playgrounds"), while noting state law forces approval of qualifying enterprise-zone applications. Under her, the city halted new data center tax-break applications after May 7, 2026 ahead of the statewide moratorium, and the Council directed staff (June 2026) to create a data-center use category, add development standards, require detailed utility/environmental impact review in permitting, and narrow where data centers are allowed. Matches Chair 3 (allowing data center development with impact assessments, energy cost-sharing agreements) — allow-with-conditions, not moratorium and not minimal-barriers welcome.', ARRAY['https://katu.com/news/local/high-stakes-hillsboro-city-council-meeting-to-tackle-data-center-boom-mayor-beach-pace-washington-county-nike-intel', 'https://katu.com/news/local/after-surge-in-requests-hillsboro-halts-new-data-center-tax-break-applications', 'https://hillsboroherald.com/the-hidden-creek-smokescreen-fact-checking-hillsboro-mayor-paces-data-center-defense/']::text[]),
    ('economic-development', 4, 'Pace publicly defends Hillsboro''s enterprise-zone tax abatements and Strategic Investment Program model, crediting "economic development" for community amenities "without raising taxes" (city video, May 2026). She testified to the Legislature (Feb 2026) leading the push (SB 1586) to open ~1,700 acres for semiconductor investment: "few sites in Oregon have been studied more thoroughly and none are more ready and better positioned to immediately help the state''s economic recovery." Campaign priority: growing living-wage job opportunities. Matches Chair 4 (compete actively for major employers with significant tax abatements and infrastructure).', ARRAY['https://www.opb.org/article/2026/02/17/oregon-senators-tech-development-hillsboro-farm-group/', 'https://hillsboroherald.com/the-hidden-creek-smokescreen-fact-checking-hillsboro-mayor-paces-data-center-defense/']::text[]),
    ('growth-and-development', 4, 'As Mayor, Pace is a lead advocate for SB 1586 (Feb 2026) to expand Hillsboro''s urban growth boundary onto ~1,700 acres of reserved farmland for semiconductor development — overriding the 2014 "Grand Bargain" farmland reservation over farm-group objections — testifying the lands are "ready" to "immediately help the state''s economic recovery." As councilor she was part of the council majority approving successive large industrial/residential annexations and rezonings (e.g., 400+ acres, July 2024). Matches Chair 4 (streamline permitting, reduce fees, and actively recruit development to grow); caveat: she grounds it in "nearly 20 years of review [and] regional planning."', ARRAY['https://www.opb.org/article/2026/02/17/oregon-senators-tech-development-hillsboro-farm-group/', 'https://hillsboroherald.com/hillsboro-city-council-to-vote-in-another-400-acres-of-growth-land/']::text[]),
    ('residential-zoning', 3, 'As Mayor she approved/praised an affordable multifamily development on TriMet transit-center property - "the best of what transit-oriented development can be" (Aug 2025) - i.e., density sited at transit/commercial nodes. In 2018 she endorsed inclusionary zoning and more housing "at all levels," and in 2022 emphasized inclusive, community-driven processes for the Jackson East rezoning rather than blanket upzoning. No evidence she supports citywide by-right upzoning or eliminating single-family zoning. Matches Chair 3 (allow multifamily and mixed-use near commercial corridors while protecting most residential areas).', ARRAY['https://hillsboronewstimes.com/2025/08/21/hillsboro-greenlights-proposal-for-affordable-housing-development-on-trimet-property/', 'https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/']::text[]),
    ('transportation-priorities', 3, 'Former Transportation Committee chair; 2024 campaign priority "advocating for safe transportation." In the 2022 candidate Q&A she envisioned the 10th Avenue corridor with "improved lighting, walkability, and biking infrastructure," and as Mayor (Aug 2025) championed transit-oriented development at a TriMet site. Pattern is targeted multimodal/pedestrian investment where density supports it; no documented push to deprioritize roads citywide or to mandate bike lanes on all projects. Matches Chair 3 (maintain roads while selectively adding transit connections and pedestrian improvements).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/', 'https://hillsboronewstimes.com/2025/08/21/hillsboro-greenlights-proposal-for-affordable-housing-development-on-trimet-property/']::text[]),
    ('public-safety-approach', 3, 'In the Oct 2022 candidate Q&A she cited police crisis intervention teams (alongside safe rest pods and nonprofit counseling partnerships) as part of the city homelessness/public-safety approach she supports; her 2024 mayoral platform was "preserving public safety through comprehensive police training" - maintain-and-improve rather than expand or divert police funding. No statement supporting budget reallocation away from police or major staffing expansion. Matches Chair 3 (keep current public safety funding while adding crisis response teams for mental health).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/', 'https://hillsboronewstimes.com/2024/08/23/hillsboro-city-councilor-beach-pace-places-bid-for-mayor/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '95a6d0c4-2b0e-4c4f-9f53-02eb55543fb7'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('local-immigration', 1, 'As Mayor, Pace issued a joint October 2025 statement with Police Chief Jim Coleman reaffirming Hillsboro is a sanctuary city whose police "does not coordinate with federal immigration authorities." She then presided over the unanimous Nov 18, 2025 state-of-emergency resolution condemning ICE conduct (detentions without due process), and the unanimous Nov 24, 2025 five-point response plan that paused the city''s automated license plate readers (cutting a data channel to federal agencies), added ICE-warrant-required signage on city facilities, funded $400K in grants to impacted families/businesses, and directed evaluation of strengthening sanctuary status. Matches Chair 1 (refuse all ICE detainers; prohibit city employees from sharing immigration status).', ARRAY['https://hillsboronewstimes.com/2025/11/05/hillsboro-residents-call-for-city-action-as-ice-raids-immigration-enforcement-fears-grow/', 'https://hillsboroherald.com/hillsboro-city-council-reaches-unanimous-agreement-on-plan-to-respond-to-ice/', 'https://www.kptv.com/2025/11/19/hillsboro-declares-state-emergency-amid-increased-ice-activity/']::text[]),
    ('homelessness-response', 2, 'Pace championed the Safe Rest Pods (served 196 people, connected 178 to housing assessments) as a councilor, calling affordable housing and safe rest pods her proudest accomplishment (Aug 2024), and as Mayor delivered Hillsboro''s first year-round 75-bed shelter ($17M; opened Nov 14, 2025). At the March 3, 2025 groundbreaking she said the city is "committed to supporting efforts that provide compassionate care and pathways to housing while also addressing the impacts of homelessness on businesses and our community"; in Sept 2025 she framed the goal as getting "folks off the street and into support... services that they can use and get themselves back on their feet and into more regular housing." Matches Chair 2 (expand shelter capacity and services as the primary strategy; use enforcement only after).', ARRAY['https://www.washingtoncountyor.gov/housing/news/2025/03/03/hillsboro-year-round-shelter-celebrates-groundbreaking', 'https://katu.com/news/local/hillsboro-to-open-year-round-homeless-shelter-with-75-capacity-pets-welcome-homelessness-oregon-portland-suburbs-baseline-bonamici-project-funding', 'https://outnw.com/queer-politicians-q-a-beach-pace-for-mayor-of-hillsboro-or/']::text[]),
    ('housing', 2, 'In her 2018 council campaign she explicitly backed inclusionary zoning requiring "a percentage of affordable units," supported Measure 102 and the Metro affordable housing bond (public funding of new affordable housing), plus city land acquisition and public-private partnerships. As Mayor (Aug 2025) she greenlit an affordable housing development on TriMet property, calling it "the best of what transit-oriented development can be - and helps to address our community''s need for affordable housing." No rent-cap statement found; match rests on the require-affordable-units + publicly-fund elements of Chair 2.', ARRAY['https://hillsborosignal.com/2018/10/27/conversation-with-city-council-candidate-beach-pace/', 'https://hillsboronewstimes.com/2025/08/21/hillsboro-greenlights-proposal-for-affordable-housing-development-on-trimet-property/']::text[]),
    ('data-centers', 3, 'Pace defends continued data center development and its economic benefits (May 2026 city video: "economic development has been able to provide the city some pretty amazing things like the Hidden Creek Community Center, fire stations, emergency vehicles and playgrounds"), while noting state law forces approval of qualifying enterprise-zone applications. Under her, the city halted new data center tax-break applications after May 7, 2026 ahead of the statewide moratorium, and the Council directed staff (June 2026) to create a data-center use category, add development standards, require detailed utility/environmental impact review in permitting, and narrow where data centers are allowed. Matches Chair 3 (allowing data center development with impact assessments, energy cost-sharing agreements) — allow-with-conditions, not moratorium and not minimal-barriers welcome.', ARRAY['https://katu.com/news/local/high-stakes-hillsboro-city-council-meeting-to-tackle-data-center-boom-mayor-beach-pace-washington-county-nike-intel', 'https://katu.com/news/local/after-surge-in-requests-hillsboro-halts-new-data-center-tax-break-applications', 'https://hillsboroherald.com/the-hidden-creek-smokescreen-fact-checking-hillsboro-mayor-paces-data-center-defense/']::text[]),
    ('economic-development', 4, 'Pace publicly defends Hillsboro''s enterprise-zone tax abatements and Strategic Investment Program model, crediting "economic development" for community amenities "without raising taxes" (city video, May 2026). She testified to the Legislature (Feb 2026) leading the push (SB 1586) to open ~1,700 acres for semiconductor investment: "few sites in Oregon have been studied more thoroughly and none are more ready and better positioned to immediately help the state''s economic recovery." Campaign priority: growing living-wage job opportunities. Matches Chair 4 (compete actively for major employers with significant tax abatements and infrastructure).', ARRAY['https://www.opb.org/article/2026/02/17/oregon-senators-tech-development-hillsboro-farm-group/', 'https://hillsboroherald.com/the-hidden-creek-smokescreen-fact-checking-hillsboro-mayor-paces-data-center-defense/']::text[]),
    ('growth-and-development', 4, 'As Mayor, Pace is a lead advocate for SB 1586 (Feb 2026) to expand Hillsboro''s urban growth boundary onto ~1,700 acres of reserved farmland for semiconductor development — overriding the 2014 "Grand Bargain" farmland reservation over farm-group objections — testifying the lands are "ready" to "immediately help the state''s economic recovery." As councilor she was part of the council majority approving successive large industrial/residential annexations and rezonings (e.g., 400+ acres, July 2024). Matches Chair 4 (streamline permitting, reduce fees, and actively recruit development to grow); caveat: she grounds it in "nearly 20 years of review [and] regional planning."', ARRAY['https://www.opb.org/article/2026/02/17/oregon-senators-tech-development-hillsboro-farm-group/', 'https://hillsboroherald.com/hillsboro-city-council-to-vote-in-another-400-acres-of-growth-land/']::text[]),
    ('residential-zoning', 3, 'As Mayor she approved/praised an affordable multifamily development on TriMet transit-center property - "the best of what transit-oriented development can be" (Aug 2025) - i.e., density sited at transit/commercial nodes. In 2018 she endorsed inclusionary zoning and more housing "at all levels," and in 2022 emphasized inclusive, community-driven processes for the Jackson East rezoning rather than blanket upzoning. No evidence she supports citywide by-right upzoning or eliminating single-family zoning. Matches Chair 3 (allow multifamily and mixed-use near commercial corridors while protecting most residential areas).', ARRAY['https://hillsboronewstimes.com/2025/08/21/hillsboro-greenlights-proposal-for-affordable-housing-development-on-trimet-property/', 'https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/']::text[]),
    ('transportation-priorities', 3, 'Former Transportation Committee chair; 2024 campaign priority "advocating for safe transportation." In the 2022 candidate Q&A she envisioned the 10th Avenue corridor with "improved lighting, walkability, and biking infrastructure," and as Mayor (Aug 2025) championed transit-oriented development at a TriMet site. Pattern is targeted multimodal/pedestrian investment where density supports it; no documented push to deprioritize roads citywide or to mandate bike lanes on all projects. Matches Chair 3 (maintain roads while selectively adding transit connections and pedestrian improvements).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/', 'https://hillsboronewstimes.com/2025/08/21/hillsboro-greenlights-proposal-for-affordable-housing-development-on-trimet-property/']::text[]),
    ('public-safety-approach', 3, 'In the Oct 2022 candidate Q&A she cited police crisis intervention teams (alongside safe rest pods and nonprofit counseling partnerships) as part of the city homelessness/public-safety approach she supports; her 2024 mayoral platform was "preserving public safety through comprehensive police training" - maintain-and-improve rather than expand or divert police funding. No statement supporting budget reallocation away from police or major staffing expansion. Matches Chair 3 (keep current public safety funding while adding crisis response teams for mental health).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/', 'https://hillsboronewstimes.com/2024/08/23/hillsboro-city-councilor-beach-pace-places-bid-for-mayor/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '95a6d0c4-2b0e-4c4f-9f53-02eb55543fb7'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
