-- Migration 1153: Cristian Salgado (Councilor, Ward 1 Position A, Hillsboro OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 8 cited stances; blank spokes omitted.
-- Salgado appointed Jan 21, 2025; pre-tenure attribution rule applied (only post-seating actions attributed).
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('local-immigration', 1, 'Voted YES (5-0, present; Harris excused) on Resolution No. 2906, Nov 18, 2025, declaring a State of Emergency over federal immigration enforcement impacts — the resolution reaffirms Hillsboro''s sanctuary status, condemns ICE detentions without due process, and directs ICE-warrant-required signage on nonpublic areas of city facilities (verified in official Nov 18, 2025 council minutes). Participated in the unanimous Nov 24, 2025 response plan (ALPR pause, signage, $400K community/business grants, sanctuary codification study). Went further than colleagues with his own first-party Nov 17, 2025 memorandum proposing a "Two-Track Strategy: Immediate Launch of Civil/Human Rights Response Program and Refer Permanent Commission Charter Amendments," including a coordinator working with legal observers who respond to and document ICE enforcement actions; per reporting he demands "historical accounting of who made the arrests, who was arrested, where they were taken, and if any constitutional rights were violated." Matches Chair 1 (refuse all ICE detainers; prohibit city employees from sharing immigration status).', ARRAY['https://hillsboro-oregon.civicweb.net/document/253982/', 'https://hillsboro-oregon.civicweb.net/document/254838/', 'https://hillsboroherald.com/hillsboro-city-council-reaches-unanimous-agreement-on-plan-to-respond-to-ice/', 'https://hillsboroherald.com/theyre-hunting-our-neighbors-hillsboros-ice-crisis-and-the-people-fighting-back/']::text[]),
    ('civil-rights', 2, 'Authored and sponsored (Nov 17, 2025 memorandum, first-party) the proposal to create a permanent, charter-based Civil/Human Rights Commission and an immediate Civil/Human Rights Response Program for Hillsboro — institutionalizing civil-rights monitoring, documentation of violations, and enforcement capacity rather than ad-hoc responses. The city''s ICE-response plan subsequently included a "Plan for an Office of Human Rights and Community Advisory Committee" (Dec 16, 2025 City Manager memo). Matches Chair 2 (strengthen civil rights enforcement and address systemic discrimination).', ARRAY['https://hillsboro-oregon.civicweb.net/document/253982/', 'https://hillsboro-oregon.civicweb.net/document/254838/']::text[]),
    ('housing', 3, 'At the Dec 2, 2025 public hearing he seconded and voted YES (4-0) on Resolution No. 2907 readopting the Hillsboro Housing Production Strategy Cycle 1 (2025-2030) — a package of targeted "plans, tools, actions, and policies to address identified housing needs." Per official minutes: "Councilor Salgado echoed Councilor Harris'' comments on SDCs [reviewing System Development Charges], especially for Accessory Dwelling Units. Additionally, Salgado expressed support for quicker implementation to support multigenerational housing." Targeted-tools-plus-easier/cheaper-building posture; no evidence of rent caps or leave-it-to-the-market. Matches Chair 3 (offer targeted help like subsidies for affordable projects, first-time buyer assistance, and easier permitting).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254837/City%20Council%20-%2002%20Dec%202025.pdf']::text[]),
    ('growth-and-development', 3, 'Voted YES on first readings of Ordinance 6509 (Public Facilities Plan comprehensive-plan amendment incorporating facility master plans to serve growth) and Ordinance 6510 (Metro 2040 regional/town center boundaries), Dec 2, 2025 (4-0). Voted YES Nov 18, 2025 (5-0) on Resolution 2905, a $710,000 interfund loan to "meet infrastructure needs in South Hillsboro" ahead of SDC revenue collection, and seconded/voted YES on Order No. 29 approving the 82-lot Riverside at Butternut Woods planned unit development. Pattern: approve growth with infrastructure planned and financed in front of it. Matches Chair 3 (plan proactively — invest in infrastructure ahead of growth to support responsible expansion).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254837/City%20Council%20-%2002%20Dec%202025.pdf']::text[]),
    ('residential-zoning', 2, 'On the record at the Dec 2, 2025 Housing Production Strategy hearing advocating lower System Development Charges specifically for Accessory Dwelling Units and quicker implementation "to support multigenerational housing" — enabling modest, gentle-density infill (ADUs/multigenerational arrangements) within existing neighborhoods. No evidence he supports broad by-right upzoning or eliminating single-family zoning. Matches Chair 2 (allow modest density increases — duplexes, accessory units — with strong design review).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254837/City%20Council%20-%2002%20Dec%202025.pdf']::text[]),
    ('climate-change', 3, 'Voted YES on Resolution No. 2911 adopting Hillsboro''s Climate Action Plan, Feb 3, 2026 (carried 4-1; official minutes: "Saba Anvery, Elizabeth Case, Rob Harris, and Cristian Salgado voted yes. Kipperlyn Sinclair voted no"). The CAP is the city''s roadmap to "reduce pollution, save energy and money, and prepare for climate impacts like extreme heat and wildfire smoke" — an invest-and-gradually-reduce framework, not an emergency ban or a 2030 fossil phase-out. Matches Chair 3 (invest in clean energy while gradually reducing reliance on fossil fuels).', ARRAY['https://hillsboro-oregon.civicweb.net/document/256729/City%20Council%20-%2003%20Feb%202026.pdf', 'https://engage.hillsboro-oregon.gov/climateplan']::text[]),
    ('data-centers', 3, 'At the June 9, 2026 council work session on the data-center surge (17 enterprise-zone tax-break applications ahead of the state HB 4084 moratorium), Salgado opposed Councilor Sinclair''s emergency 45-day pause ordinance and argued for allow-with-conditions policy work: "I invite you all to remove the politics out of this. This is a math problem, right? That''s all it is. It''s a math problem." He pushed staff to evaluate structural utility credits for low-income ratepayers and to differentiate standards for small co-location vs. hyperscale facilities; he was part of the council direction to develop environmental/design standards and study community service fees rather than adopt an immediate ban. Matches Chair 3 (allowing data center development with impact assessments, energy cost-sharing agreements).', ARRAY['https://hillsboroherald.com/hillsboro-council-divided-at-data-center-work-session-dr-alcaire-pierces-the-bureaucratic-veil/', 'https://hillsboronewstimes.com/2026/05/08/hillsboro-data-center-tax-incentives-spark-scrutiny-before-statewide-moratorium/']::text[]),
    ('transportation-priorities', 3, 'Voted YES (5-0) on Resolution No. 2910, Feb 3, 2026, authorizing federal/state/regional grant applications for two transit projects with $175,000 in transit transportation-impact-fee funds as local match; voted YES Nov 18, 2025 on the IGA with Washington County ($12,500 match) for a Commuter Transportation Needs Assessment and on the $710K South Hillsboro road-infrastructure interfund loan. Pattern: sustain road/infrastructure investment while selectively adding transit; no evidence of a transit-first or roads-only agenda. Matches Chair 3 (maintain roads while selectively adding transit connections and pedestrian improvements).', ARRAY['https://hillsboro-oregon.civicweb.net/document/256729/City%20Council%20-%2003%20Feb%202026.pdf']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '44d84b41-36f0-4b46-8235-df1ca4ed7da7'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('local-immigration', 1, 'Voted YES (5-0, present; Harris excused) on Resolution No. 2906, Nov 18, 2025, declaring a State of Emergency over federal immigration enforcement impacts — the resolution reaffirms Hillsboro''s sanctuary status, condemns ICE detentions without due process, and directs ICE-warrant-required signage on nonpublic areas of city facilities (verified in official Nov 18, 2025 council minutes). Participated in the unanimous Nov 24, 2025 response plan (ALPR pause, signage, $400K community/business grants, sanctuary codification study). Went further than colleagues with his own first-party Nov 17, 2025 memorandum proposing a "Two-Track Strategy: Immediate Launch of Civil/Human Rights Response Program and Refer Permanent Commission Charter Amendments," including a coordinator working with legal observers who respond to and document ICE enforcement actions; per reporting he demands "historical accounting of who made the arrests, who was arrested, where they were taken, and if any constitutional rights were violated." Matches Chair 1 (refuse all ICE detainers; prohibit city employees from sharing immigration status).', ARRAY['https://hillsboro-oregon.civicweb.net/document/253982/', 'https://hillsboro-oregon.civicweb.net/document/254838/', 'https://hillsboroherald.com/hillsboro-city-council-reaches-unanimous-agreement-on-plan-to-respond-to-ice/', 'https://hillsboroherald.com/theyre-hunting-our-neighbors-hillsboros-ice-crisis-and-the-people-fighting-back/']::text[]),
    ('civil-rights', 2, 'Authored and sponsored (Nov 17, 2025 memorandum, first-party) the proposal to create a permanent, charter-based Civil/Human Rights Commission and an immediate Civil/Human Rights Response Program for Hillsboro — institutionalizing civil-rights monitoring, documentation of violations, and enforcement capacity rather than ad-hoc responses. The city''s ICE-response plan subsequently included a "Plan for an Office of Human Rights and Community Advisory Committee" (Dec 16, 2025 City Manager memo). Matches Chair 2 (strengthen civil rights enforcement and address systemic discrimination).', ARRAY['https://hillsboro-oregon.civicweb.net/document/253982/', 'https://hillsboro-oregon.civicweb.net/document/254838/']::text[]),
    ('housing', 3, 'At the Dec 2, 2025 public hearing he seconded and voted YES (4-0) on Resolution No. 2907 readopting the Hillsboro Housing Production Strategy Cycle 1 (2025-2030) — a package of targeted "plans, tools, actions, and policies to address identified housing needs." Per official minutes: "Councilor Salgado echoed Councilor Harris'' comments on SDCs [reviewing System Development Charges], especially for Accessory Dwelling Units. Additionally, Salgado expressed support for quicker implementation to support multigenerational housing." Targeted-tools-plus-easier/cheaper-building posture; no evidence of rent caps or leave-it-to-the-market. Matches Chair 3 (offer targeted help like subsidies for affordable projects, first-time buyer assistance, and easier permitting).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254837/City%20Council%20-%2002%20Dec%202025.pdf']::text[]),
    ('growth-and-development', 3, 'Voted YES on first readings of Ordinance 6509 (Public Facilities Plan comprehensive-plan amendment incorporating facility master plans to serve growth) and Ordinance 6510 (Metro 2040 regional/town center boundaries), Dec 2, 2025 (4-0). Voted YES Nov 18, 2025 (5-0) on Resolution 2905, a $710,000 interfund loan to "meet infrastructure needs in South Hillsboro" ahead of SDC revenue collection, and seconded/voted YES on Order No. 29 approving the 82-lot Riverside at Butternut Woods planned unit development. Pattern: approve growth with infrastructure planned and financed in front of it. Matches Chair 3 (plan proactively — invest in infrastructure ahead of growth to support responsible expansion).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254837/City%20Council%20-%2002%20Dec%202025.pdf']::text[]),
    ('residential-zoning', 2, 'On the record at the Dec 2, 2025 Housing Production Strategy hearing advocating lower System Development Charges specifically for Accessory Dwelling Units and quicker implementation "to support multigenerational housing" — enabling modest, gentle-density infill (ADUs/multigenerational arrangements) within existing neighborhoods. No evidence he supports broad by-right upzoning or eliminating single-family zoning. Matches Chair 2 (allow modest density increases — duplexes, accessory units — with strong design review).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254837/City%20Council%20-%2002%20Dec%202025.pdf']::text[]),
    ('climate-change', 3, 'Voted YES on Resolution No. 2911 adopting Hillsboro''s Climate Action Plan, Feb 3, 2026 (carried 4-1; official minutes: "Saba Anvery, Elizabeth Case, Rob Harris, and Cristian Salgado voted yes. Kipperlyn Sinclair voted no"). The CAP is the city''s roadmap to "reduce pollution, save energy and money, and prepare for climate impacts like extreme heat and wildfire smoke" — an invest-and-gradually-reduce framework, not an emergency ban or a 2030 fossil phase-out. Matches Chair 3 (invest in clean energy while gradually reducing reliance on fossil fuels).', ARRAY['https://hillsboro-oregon.civicweb.net/document/256729/City%20Council%20-%2003%20Feb%202026.pdf', 'https://engage.hillsboro-oregon.gov/climateplan']::text[]),
    ('data-centers', 3, 'At the June 9, 2026 council work session on the data-center surge (17 enterprise-zone tax-break applications ahead of the state HB 4084 moratorium), Salgado opposed Councilor Sinclair''s emergency 45-day pause ordinance and argued for allow-with-conditions policy work: "I invite you all to remove the politics out of this. This is a math problem, right? That''s all it is. It''s a math problem." He pushed staff to evaluate structural utility credits for low-income ratepayers and to differentiate standards for small co-location vs. hyperscale facilities; he was part of the council direction to develop environmental/design standards and study community service fees rather than adopt an immediate ban. Matches Chair 3 (allowing data center development with impact assessments, energy cost-sharing agreements).', ARRAY['https://hillsboroherald.com/hillsboro-council-divided-at-data-center-work-session-dr-alcaire-pierces-the-bureaucratic-veil/', 'https://hillsboronewstimes.com/2026/05/08/hillsboro-data-center-tax-incentives-spark-scrutiny-before-statewide-moratorium/']::text[]),
    ('transportation-priorities', 3, 'Voted YES (5-0) on Resolution No. 2910, Feb 3, 2026, authorizing federal/state/regional grant applications for two transit projects with $175,000 in transit transportation-impact-fee funds as local match; voted YES Nov 18, 2025 on the IGA with Washington County ($12,500 match) for a Commuter Transportation Needs Assessment and on the $710K South Hillsboro road-infrastructure interfund loan. Pattern: sustain road/infrastructure investment while selectively adding transit; no evidence of a transit-first or roads-only agenda. Matches Chair 3 (maintain roads while selectively adding transit connections and pedestrian improvements).', ARRAY['https://hillsboro-oregon.civicweb.net/document/256729/City%20Council%20-%2003%20Feb%202026.pdf']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '44d84b41-36f0-4b46-8235-df1ca4ed7da7'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
