-- Migration 1154: Saba Anvery (Councilor, Ward 1 Position B, Hillsboro OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 7 cited stances; blank spokes omitted.
-- Anvery elected Nov 2024 (unopposed), seated Jan 7, 2025; pre-tenure attribution rule applied.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('local-immigration', 1, 'Voted YES on Resolution No. 2906 (Nov 18, 2025, CARRIED 5-0; official minutes name her: "Olivia Alcaire, Kipperlyn Sinclair, Saba Anvery, Elizabeth Case, and Cristian Salgado voted yes"; Harris excused) declaring a State of Emergency over federal immigration enforcement impacts. The resolution "directs that City resources will not be used to enforce federal immigration laws," strengthens sanctuary measures, condemns ICE detentions without due process, calls for an immediate end to ICE enforcement actions targeting students and families, and directs restricted-area signage in city facilities. She was also present and participating at the Nov 24, 2025 special work session where the council unanimously advanced the response plan (ALPR pause, signage, expanded utility/rental assistance, $400K community/business grants, sanctuary-codification study). Matches Chair 1 (refuse all ICE detainers; prohibit city employees from sharing immigration status).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254042/Adopted_Resolution_No._2906.pdf', 'https://hillsboronewstimes.com/2025/11/19/hillsboro-declares-state-of-emergency-over-local-ice-activity/']::text[]),
    ('climate-change', 3, 'Voted YES on Resolution No. 2911 adopting Hillsboro''s Climate Action Plan, Feb 3, 2026 (CARRIED 4-1: "Saba Anvery, Elizabeth Case, Rob Harris, and Cristian Salgado voted yes. Kipperlyn Sinclair voted no" — official minutes). The CAP targets net-zero emissions by 2050 (per the Dec 2, 2025 work session minutes) — an invest-and-gradually-reduce framework, not an emergency ban or 2030 phase-out. Reinforced by her first-party 2024 campaign priority: "Implement creative and sustainable climate change solutions." Matches Chair 3 (invest in clean energy while gradually reducing reliance on fossil fuels).', ARRAY['https://hillsboro-oregon.civicweb.net/document/256729/City%20Council%20-%2003%20Feb%202026.pdf', 'https://www.sabaanvery.com']::text[]),
    ('housing', 3, 'Voted YES (4-0, present and named) on Resolution No. 2907 (Dec 2, 2025) readopting the Hillsboro Housing Production Strategy Cycle 1 (2025-2030), a package of targeted "plans, tools, actions, and policies to address identified housing needs." First-party campaign priority: "Create affordable housing options" / making housing in Hillsboro more affordable. No evidence of rent caps/inclusionary mandates or market-only posture. Matches Chair 3 (offer targeted help like subsidies for affordable projects, first-time buyer assistance, and easier permitting).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254837/City%20Council%20-%2002%20Dec%202025.pdf', 'https://www.sabaanvery.com', 'https://hillsboronewstimes.com/2024/08/23/ward-1-profile-saba-anvery-runs-unopposed-for-hillsboro-city-council/']::text[]),
    ('growth-and-development', 3, 'Seconded and voted YES on Resolution 2905 (Nov 18, 2025, 5-0), a $710,000 interfund loan to "meet infrastructure needs in South Hillsboro" ahead of SDC revenue; voted YES on Ordinances 6509 (Public Facilities Plan comp-plan amendment) and 6510 (Metro 2040 regional/town center boundaries) at first reading Dec 2, 2025 (4-0); voted YES on Order No. 29 (82-lot Riverside at Butternut Woods PUD, Nov 18, 2025) and Annexation Ordinance 6512 (45.88 acres, Apr 21, 2026, 6-0). First-party (Nov 4, 2024 interview): called the urban growth boundary her "biggest challenge," said both sides of the UGB debate have merit, and favored attracting semiconductor companies "while imposing growth restrictions and conditions." Matches Chair 3 (plan proactively — invest in infrastructure ahead of growth to support responsible expansion).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254837/City%20Council%20-%2002%20Dec%202025.pdf', 'https://washcodems.org/2024/11/04/saban-anvery-hillsboro-city-council-candidate-interview/']::text[]),
    ('transportation-priorities', 3, 'Voted YES (5-0) on Resolution No. 2910 (Feb 3, 2026) authorizing grant applications for two transit projects with $175,000 in transit transportation-impact-fee funds as local match; personally MOVED adoption of Ordinance No. 6515 (Transportation System Plan update, May 5, 2026, 5-0); voted YES Nov 18, 2025 on the consent IGA with Washington County ($12,500 match) for a Commuter Transportation Needs Assessment; May 5, 2026 consent yes on $2.7M Pavement Management Program (road maintenance). Campaign priority: "Improve the transportation systems so that they can work for everyone." Matches Chair 3 (maintain roads while selectively adding transit connections and pedestrian improvements).', ARRAY['https://hillsboro-oregon.civicweb.net/document/256729/City%20Council%20-%2003%20Feb%202026.pdf', 'https://www.sabaanvery.com']::text[]),
    ('data-centers', 3, 'At the June 9, 2026 council work session on the data-center/enterprise-zone surge (17 tax-break applications ahead of the HB 4084 state moratorium), Anvery was one of four councilors (with Case, Harris, Salgado) who declined Sinclair''s 45-day emergency pause ordinance in favor of directing staff to study a statutory land-use moratorium, development-code text amendments, environmental design standards, and community service fees. She defended staff — "The staff is doing exactly what the council told them to do" — and pushed for strategic investment of the ~$55M Enterprise Zone fund balance. Her documented emphasis is ratepayer/impact transparency: Apr 21, 2026 council comment suggesting the City send a formal letter to PGE requesting itemized residential bills; May 5, 2026 council comment requesting the City''s data-center FAQ be verified/updated. Matches Chair 3 (allowing data center development with impact assessments, energy cost-sharing agreements).', ARRAY['https://hillsboroherald.com/hillsboro-council-divided-at-data-center-work-session-dr-alcaire-pierces-the-bureaucratic-veil/', 'https://katu.com/news/local/after-surge-in-requests-hillsboro-halts-new-data-center-tax-break-applications']::text[]),
    ('homelessness-response', 2, 'First-party candidate interview (Nov 4, 2024): emphasized prevention — "helping people who had fallen on hard times with bills" — advocated increased mental health and addiction support services, and expressed enthusiasm for Hillsboro''s year-round shelter initiative, saying it "would make it easier to help people, as well as provide support." As councilor, voted YES (Nov 18, 2025 consent, 5-0) to name the new year-round houseless shelter facility "Hillsboro Shelter." Services-and-shelter-first posture; no enforcement-first statement found. Matches Chair 2 (expand shelter capacity and services as the primary strategy; use enforcement only after).', ARRAY['https://washcodems.org/2024/11/04/saban-anvery-hillsboro-city-council-candidate-interview/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '2615c597-7974-441e-a9f1-93616b2da33c'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('local-immigration', 1, 'Voted YES on Resolution No. 2906 (Nov 18, 2025, CARRIED 5-0; official minutes name her: "Olivia Alcaire, Kipperlyn Sinclair, Saba Anvery, Elizabeth Case, and Cristian Salgado voted yes"; Harris excused) declaring a State of Emergency over federal immigration enforcement impacts. The resolution "directs that City resources will not be used to enforce federal immigration laws," strengthens sanctuary measures, condemns ICE detentions without due process, calls for an immediate end to ICE enforcement actions targeting students and families, and directs restricted-area signage in city facilities. She was also present and participating at the Nov 24, 2025 special work session where the council unanimously advanced the response plan (ALPR pause, signage, expanded utility/rental assistance, $400K community/business grants, sanctuary-codification study). Matches Chair 1 (refuse all ICE detainers; prohibit city employees from sharing immigration status).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254042/Adopted_Resolution_No._2906.pdf', 'https://hillsboronewstimes.com/2025/11/19/hillsboro-declares-state-of-emergency-over-local-ice-activity/']::text[]),
    ('climate-change', 3, 'Voted YES on Resolution No. 2911 adopting Hillsboro''s Climate Action Plan, Feb 3, 2026 (CARRIED 4-1: "Saba Anvery, Elizabeth Case, Rob Harris, and Cristian Salgado voted yes. Kipperlyn Sinclair voted no" — official minutes). The CAP targets net-zero emissions by 2050 (per the Dec 2, 2025 work session minutes) — an invest-and-gradually-reduce framework, not an emergency ban or 2030 phase-out. Reinforced by her first-party 2024 campaign priority: "Implement creative and sustainable climate change solutions." Matches Chair 3 (invest in clean energy while gradually reducing reliance on fossil fuels).', ARRAY['https://hillsboro-oregon.civicweb.net/document/256729/City%20Council%20-%2003%20Feb%202026.pdf', 'https://www.sabaanvery.com']::text[]),
    ('housing', 3, 'Voted YES (4-0, present and named) on Resolution No. 2907 (Dec 2, 2025) readopting the Hillsboro Housing Production Strategy Cycle 1 (2025-2030), a package of targeted "plans, tools, actions, and policies to address identified housing needs." First-party campaign priority: "Create affordable housing options" / making housing in Hillsboro more affordable. No evidence of rent caps/inclusionary mandates or market-only posture. Matches Chair 3 (offer targeted help like subsidies for affordable projects, first-time buyer assistance, and easier permitting).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254837/City%20Council%20-%2002%20Dec%202025.pdf', 'https://www.sabaanvery.com', 'https://hillsboronewstimes.com/2024/08/23/ward-1-profile-saba-anvery-runs-unopposed-for-hillsboro-city-council/']::text[]),
    ('growth-and-development', 3, 'Seconded and voted YES on Resolution 2905 (Nov 18, 2025, 5-0), a $710,000 interfund loan to "meet infrastructure needs in South Hillsboro" ahead of SDC revenue; voted YES on Ordinances 6509 (Public Facilities Plan comp-plan amendment) and 6510 (Metro 2040 regional/town center boundaries) at first reading Dec 2, 2025 (4-0); voted YES on Order No. 29 (82-lot Riverside at Butternut Woods PUD, Nov 18, 2025) and Annexation Ordinance 6512 (45.88 acres, Apr 21, 2026, 6-0). First-party (Nov 4, 2024 interview): called the urban growth boundary her "biggest challenge," said both sides of the UGB debate have merit, and favored attracting semiconductor companies "while imposing growth restrictions and conditions." Matches Chair 3 (plan proactively — invest in infrastructure ahead of growth to support responsible expansion).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254837/City%20Council%20-%2002%20Dec%202025.pdf', 'https://washcodems.org/2024/11/04/saban-anvery-hillsboro-city-council-candidate-interview/']::text[]),
    ('transportation-priorities', 3, 'Voted YES (5-0) on Resolution No. 2910 (Feb 3, 2026) authorizing grant applications for two transit projects with $175,000 in transit transportation-impact-fee funds as local match; personally MOVED adoption of Ordinance No. 6515 (Transportation System Plan update, May 5, 2026, 5-0); voted YES Nov 18, 2025 on the consent IGA with Washington County ($12,500 match) for a Commuter Transportation Needs Assessment; May 5, 2026 consent yes on $2.7M Pavement Management Program (road maintenance). Campaign priority: "Improve the transportation systems so that they can work for everyone." Matches Chair 3 (maintain roads while selectively adding transit connections and pedestrian improvements).', ARRAY['https://hillsboro-oregon.civicweb.net/document/256729/City%20Council%20-%2003%20Feb%202026.pdf', 'https://www.sabaanvery.com']::text[]),
    ('data-centers', 3, 'At the June 9, 2026 council work session on the data-center/enterprise-zone surge (17 tax-break applications ahead of the HB 4084 state moratorium), Anvery was one of four councilors (with Case, Harris, Salgado) who declined Sinclair''s 45-day emergency pause ordinance in favor of directing staff to study a statutory land-use moratorium, development-code text amendments, environmental design standards, and community service fees. She defended staff — "The staff is doing exactly what the council told them to do" — and pushed for strategic investment of the ~$55M Enterprise Zone fund balance. Her documented emphasis is ratepayer/impact transparency: Apr 21, 2026 council comment suggesting the City send a formal letter to PGE requesting itemized residential bills; May 5, 2026 council comment requesting the City''s data-center FAQ be verified/updated. Matches Chair 3 (allowing data center development with impact assessments, energy cost-sharing agreements).', ARRAY['https://hillsboroherald.com/hillsboro-council-divided-at-data-center-work-session-dr-alcaire-pierces-the-bureaucratic-veil/', 'https://katu.com/news/local/after-surge-in-requests-hillsboro-halts-new-data-center-tax-break-applications']::text[]),
    ('homelessness-response', 2, 'First-party candidate interview (Nov 4, 2024): emphasized prevention — "helping people who had fallen on hard times with bills" — advocated increased mental health and addiction support services, and expressed enthusiasm for Hillsboro''s year-round shelter initiative, saying it "would make it easier to help people, as well as provide support." As councilor, voted YES (Nov 18, 2025 consent, 5-0) to name the new year-round houseless shelter facility "Hillsboro Shelter." Services-and-shelter-first posture; no enforcement-first statement found. Matches Chair 2 (expand shelter capacity and services as the primary strategy; use enforcement only after).', ARRAY['https://washcodems.org/2024/11/04/saban-anvery-hillsboro-city-council-candidate-interview/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '2615c597-7974-441e-a9f1-93616b2da33c'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
