-- Migration 1155: Kipperlyn Sinclair (Councilor, Ward 2 Position A, Hillsboro OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 12 cited stances; blank spokes omitted.
-- Sinclair elected Nov 2022, seated Jan 3, 2023 (term to Jan 2027); 2026 candidate for Washington County Commissioner District 4.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('data-centers', 1, 'On May 3, 2026 Sinclair (sitting councilor) publicly launched a petition calling for "a moratorium on all data centers from this point forward," expressly citing residential electricity rates up ~50% while data centers pay less than half the per-kWh household rate, families subsidizing a $200M substation, $128M in school-district revenue lost to data-center tax abatements, 4.5M gal/day water use, and heat islands. At the June 9, 2026 council work session she proposed an ordinance removing data centers as a primary permitted use in industrial zones, requiring 15 permanent FTE jobs/acre, and subjecting larger facilities to additional public review plus electric and water capacity assessments; the rest of council did not advance a pause. Her 2026 county campaign platform: "End tax breaks for data centers and stop their spread onto prime farmland." Matches Chair 1 (imposing a moratorium on new data center construction until energy infrastructure catches up).', ARRAY['https://hillsboroherald.com/signatures-sought-on-hillsboro-data-center-moratorium-petition-brought-by-kipperlyn-sinclair/', 'https://hillsboronewstimes.com/2026/06/10/data-center-lag-hillsboro-makes-little-headway-in-possible-regulations-moratorium/', 'https://www.kipperlynsinclair.com/']::text[]),
    ('local-immigration', 2, 'Sinclair PROPOSED Ordinance 6513 (adopted unanimously March 3, 2026), codifying Hillsboro sanctuary status into municipal code: city may not use facilities, personnel, or resources to investigate, detain, or assist federal immigration enforcement except where required by law, such as a judicial warrant; restricts federal agent access to non-public city facilities; mandates documentation/public reporting of ICE contacts. Her Feb 15, 2026 statement backing Oregon HB 4138 (Enforcement Accountability and Visibility Act): "HB 4138 does not block lawful enforcement. It ensures clear identification, defined authority, and accountability" — confirms court-order/lawful-process compliance rather than absolute refusal. Matches Chair 2 (comply only with court-ordered detainers; protect undocumented crime witnesses/victims).', ARRAY['https://hillsboronewstimes.com/2026/03/11/hillsboro-codifies-sanctuary-status-amid-local-ice-activity/', 'https://hillsboroherald.com/from-promise-to-policy-how-hillsboro-finally-gave-its-sanctuary-status-legal-teeth-thanks-to-councilor-kipperlyn-sinclairs-leadership/', 'https://hillsboroherald.com/hillsboro-city-councilor-kipperlyn-sinclair-backs-passage-of-oregon-house-bill-4138/']::text[]),
    ('immigration', 2, 'Sinclair led the codification of sanctuary protections guaranteeing residents access to city services/facilities regardless of immigration status (Ord 6513, Mar 3, 2026, her proposal, unanimous). She developed one of the individual councilor proposals in the city''s Nov 2025 ICE response, and publicly advocated for ICE transparency legislation citing community harm: "This lack of transparency erodes trust and destabilizes families. Parents fear taking children to school" (Feb 15, 2026). Welcoming, services-access posture; no evidence she favors expanding legal immigration levels or restriction. MEDIUM confidence — mapped from city-scope actions + first-party statements; no federal-policy statement. Matches Chair 2 (keep legal immigration open and let most residents use public services regardless of status).', ARRAY['https://hillsboroherald.com/from-promise-to-policy-how-hillsboro-finally-gave-its-sanctuary-status-legal-teeth-thanks-to-councilor-kipperlyn-sinclairs-leadership/', 'https://hillsboroherald.com/hillsboro-city-councilor-kipperlyn-sinclair-backs-passage-of-oregon-house-bill-4138/']::text[]),
    ('economic-development', 2, '2026 campaign platform (first-party): end data-center tax breaks ("Corporations must pay their fair share"); activate Economic Improvement Districts along Main Streets; "provide tax credits to independent businesses"; invest in farm-to-market distribution hubs for local farmers/local supply chain. 2022 (first-party): supports flexible zoning/mixed-use to help small businesses, wants "unique kinds of businesses here that make healthier communities." Consistent pattern: local-entrepreneur support, explicit opposition to large corporate subsidies. Matches Chair 2 (small business support and local entrepreneur programs only; avoid large corporate subsidies).', ARRAY['https://www.kipperlynsinclair.com/', 'https://hillsboronewstimes.com/2022/11/10/hillsboro-city-council-newcomer-wants-to-break-barriers/']::text[]),
    ('taxes', 2, 'First-party 2026 campaign platform: "End tax breaks for data centers... Corporations must pay their fair share to fully fund our schools and community services," and on the county $20.5M deficit, "working families shouldn''t bear the burden." Concrete policy = ending corporate abatements (raising large companies'' effective taxes) to fund services while shielding working families. Matches Chair 2 (moderately raise taxes on wealthy people and large companies to fund public services).', ARRAY['https://www.kipperlynsinclair.com/']::text[]),
    ('housing', 3, '2026 campaign platform: "Advocate for transit-oriented, affordable workforce housing" near transit and job centers. 2022 candidate Q&A: cited Hillsboro Comprehensive Plan responsibility for fair and affordable housing; supported "rezoning in support of expanding work-live opportunity" and dense mixed-use development. Supports targeted affordable-housing production; no evidence of rent caps/public housing operation or deregulation-only posture. Matches Chair 3 (offer targeted help like subsidies for affordable projects, first-time buyer assistance, and easier permitting).', ARRAY['https://www.kipperlynsinclair.com/', 'https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/']::text[]),
    ('residential-zoning', 3, '2022 candidate Q&A (first-party): for the 10th Avenue corridor she backed "dense mixed-use development, rezoning in support of expanding work-live opportunity, enhanced sidewalks for safe walkability"; smart-growth plank includes "mixing land use (homes, offices, shops)." 2026 platform: "encourage transit-oriented affordable housing and mixed-use spaces." Density targeted at corridors/centers, not citywide upzoning. Matches Chair 3 (allow multifamily and mixed-use near commercial corridors while protecting most residential areas).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/', 'https://www.kipperlynsinclair.com/']::text[]),
    ('growth-and-development', 2, 'As Planning Commissioner she voted AGAINST the Jackson East industrial rezoning and said "the city moved too quickly," urging a Housing Needs Analysis and Environmental Action Plan first (2022 Q&A, first-party). As councilor (June 9, 2026) she pushed to pause/restrict data-center approvals pending electric and water capacity assessments and public review; her moratorium petition conditions growth on energy infrastructure capacity and ratepayer protection. Consistent infrastructure-first, slow-the-approvals posture. Matches Chair 2 (allow growth only where existing infrastructure can support it).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/', 'https://hillsboronewstimes.com/2026/06/10/data-center-lag-hillsboro-makes-little-headway-in-possible-regulations-moratorium/']::text[]),
    ('transportation-priorities', 2, 'She is President of the city Transportation Committee. On Feb 3, 2026 she personally MOVED adoption of Resolution 2910 authorizing transit grant applications and $175,000 in transit transportation impact fee funds for the local match (carried 5-0, Sinclair yes). First-party 2022 smart-growth plank: "promoting public transit, improving pedestrian and bicycle amenities"; 10th Ave vision includes "enhanced sidewalks for safe walkability." 2026 platform: housing near transit and job centers. Multimodal-forward, no anti-road or parking-reduction statements. Matches Chair 2 (invest equally in roads and multimodal options; require bike/pedestrian infrastructure in new development).', ARRAY['https://hillsboro-oregon.civicweb.net/document/256729/City%20Council%20-%2003%20Feb%202026.pdf', 'https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/']::text[]),
    ('local-environment', 1, 'First-party 2022 Q&A: voted against Jackson East rezoning on the Planning Commission pending an Environmental Action Plan; supports smart growth that "reduce[s] impervious surfaces, safeguard[s] environmentally sensitive areas." 2026: demanded additional public review plus electric/water capacity assessments before data-center approvals and to "stop their spread onto prime farmland"; petition cites heat islands and 4.5M gal/day water use. Recurring demand for environmental review as a precondition of development approval. Matches Chair 1 (require significant green space, tree preservation, and environmental review before approving development).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/', 'https://hillsboroherald.com/signatures-sought-on-hillsboro-data-center-moratorium-petition-brought-by-kipperlyn-sinclair/', 'https://www.kipperlynsinclair.com/']::text[]),
    ('homelessness-response', 2, '2022 candidate Q&A (first-party): praised the Safe Rest Pods partnership with Open Door HousingWorks and plans for "a permanent village with amenities such as heating and cooling for year-round use"; framed solutions as services, nonprofit collaboration, and affordable housing ("Public engagement, diverse planning, and collaborative partnerships become long term solutions to lessen the hardship"). During her tenure (seated Jan 2023) the city ran the Safe Rest Pods (Dec 2023-Oct 2024) and opened the 75-bed year-round Hillsboro Shelter (Dec 2025). No enforcement-first statements anywhere in her record. Confidence note: chair placement rests on her first-party pro-shelter/services statements; specific council roll-calls on shelter funding not individually located. Matches Chair 2 (expand shelter capacity and services as the primary strategy; use enforcement only after).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/', 'https://www.hillsboro-oregon.gov/Home/Components/News/News/16159/4300']::text[]),
    ('civil-rights', 2, 'First-party, post-election profile (Nov 10, 2022): "On all aspects, my first priority will always be diversity, equity and inclusion" and "I will vote in a way that breaks barriers." Reinforced in practice by proposing binding civil-rights-protective code (Ord 6513, 2026) with mandatory documentation/public reporting of federal enforcement contacts. Confidence note: values-statement + local action; no federal civil-rights policy statement. Matches Chair 2 (strengthen civil rights enforcement and address systemic discrimination).', ARRAY['https://hillsboronewstimes.com/2022/11/10/hillsboro-city-council-newcomer-wants-to-break-barriers/', 'https://hillsboronewstimes.com/2026/03/11/hillsboro-codifies-sanctuary-status-amid-local-ice-activity/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '92ad1ef9-117d-4042-a19e-438c0ec7dea6'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('data-centers', 1, 'On May 3, 2026 Sinclair (sitting councilor) publicly launched a petition calling for "a moratorium on all data centers from this point forward," expressly citing residential electricity rates up ~50% while data centers pay less than half the per-kWh household rate, families subsidizing a $200M substation, $128M in school-district revenue lost to data-center tax abatements, 4.5M gal/day water use, and heat islands. At the June 9, 2026 council work session she proposed an ordinance removing data centers as a primary permitted use in industrial zones, requiring 15 permanent FTE jobs/acre, and subjecting larger facilities to additional public review plus electric and water capacity assessments; the rest of council did not advance a pause. Her 2026 county campaign platform: "End tax breaks for data centers and stop their spread onto prime farmland." Matches Chair 1 (imposing a moratorium on new data center construction until energy infrastructure catches up).', ARRAY['https://hillsboroherald.com/signatures-sought-on-hillsboro-data-center-moratorium-petition-brought-by-kipperlyn-sinclair/', 'https://hillsboronewstimes.com/2026/06/10/data-center-lag-hillsboro-makes-little-headway-in-possible-regulations-moratorium/', 'https://www.kipperlynsinclair.com/']::text[]),
    ('local-immigration', 2, 'Sinclair PROPOSED Ordinance 6513 (adopted unanimously March 3, 2026), codifying Hillsboro sanctuary status into municipal code: city may not use facilities, personnel, or resources to investigate, detain, or assist federal immigration enforcement except where required by law, such as a judicial warrant; restricts federal agent access to non-public city facilities; mandates documentation/public reporting of ICE contacts. Her Feb 15, 2026 statement backing Oregon HB 4138 (Enforcement Accountability and Visibility Act): "HB 4138 does not block lawful enforcement. It ensures clear identification, defined authority, and accountability" — confirms court-order/lawful-process compliance rather than absolute refusal. Matches Chair 2 (comply only with court-ordered detainers; protect undocumented crime witnesses/victims).', ARRAY['https://hillsboronewstimes.com/2026/03/11/hillsboro-codifies-sanctuary-status-amid-local-ice-activity/', 'https://hillsboroherald.com/from-promise-to-policy-how-hillsboro-finally-gave-its-sanctuary-status-legal-teeth-thanks-to-councilor-kipperlyn-sinclairs-leadership/', 'https://hillsboroherald.com/hillsboro-city-councilor-kipperlyn-sinclair-backs-passage-of-oregon-house-bill-4138/']::text[]),
    ('immigration', 2, 'Sinclair led the codification of sanctuary protections guaranteeing residents access to city services/facilities regardless of immigration status (Ord 6513, Mar 3, 2026, her proposal, unanimous). She developed one of the individual councilor proposals in the city''s Nov 2025 ICE response, and publicly advocated for ICE transparency legislation citing community harm: "This lack of transparency erodes trust and destabilizes families. Parents fear taking children to school" (Feb 15, 2026). Welcoming, services-access posture; no evidence she favors expanding legal immigration levels or restriction. MEDIUM confidence — mapped from city-scope actions + first-party statements; no federal-policy statement. Matches Chair 2 (keep legal immigration open and let most residents use public services regardless of status).', ARRAY['https://hillsboroherald.com/from-promise-to-policy-how-hillsboro-finally-gave-its-sanctuary-status-legal-teeth-thanks-to-councilor-kipperlyn-sinclairs-leadership/', 'https://hillsboroherald.com/hillsboro-city-councilor-kipperlyn-sinclair-backs-passage-of-oregon-house-bill-4138/']::text[]),
    ('economic-development', 2, '2026 campaign platform (first-party): end data-center tax breaks ("Corporations must pay their fair share"); activate Economic Improvement Districts along Main Streets; "provide tax credits to independent businesses"; invest in farm-to-market distribution hubs for local farmers/local supply chain. 2022 (first-party): supports flexible zoning/mixed-use to help small businesses, wants "unique kinds of businesses here that make healthier communities." Consistent pattern: local-entrepreneur support, explicit opposition to large corporate subsidies. Matches Chair 2 (small business support and local entrepreneur programs only; avoid large corporate subsidies).', ARRAY['https://www.kipperlynsinclair.com/', 'https://hillsboronewstimes.com/2022/11/10/hillsboro-city-council-newcomer-wants-to-break-barriers/']::text[]),
    ('taxes', 2, 'First-party 2026 campaign platform: "End tax breaks for data centers... Corporations must pay their fair share to fully fund our schools and community services," and on the county $20.5M deficit, "working families shouldn''t bear the burden." Concrete policy = ending corporate abatements (raising large companies'' effective taxes) to fund services while shielding working families. Matches Chair 2 (moderately raise taxes on wealthy people and large companies to fund public services).', ARRAY['https://www.kipperlynsinclair.com/']::text[]),
    ('housing', 3, '2026 campaign platform: "Advocate for transit-oriented, affordable workforce housing" near transit and job centers. 2022 candidate Q&A: cited Hillsboro Comprehensive Plan responsibility for fair and affordable housing; supported "rezoning in support of expanding work-live opportunity" and dense mixed-use development. Supports targeted affordable-housing production; no evidence of rent caps/public housing operation or deregulation-only posture. Matches Chair 3 (offer targeted help like subsidies for affordable projects, first-time buyer assistance, and easier permitting).', ARRAY['https://www.kipperlynsinclair.com/', 'https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/']::text[]),
    ('residential-zoning', 3, '2022 candidate Q&A (first-party): for the 10th Avenue corridor she backed "dense mixed-use development, rezoning in support of expanding work-live opportunity, enhanced sidewalks for safe walkability"; smart-growth plank includes "mixing land use (homes, offices, shops)." 2026 platform: "encourage transit-oriented affordable housing and mixed-use spaces." Density targeted at corridors/centers, not citywide upzoning. Matches Chair 3 (allow multifamily and mixed-use near commercial corridors while protecting most residential areas).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/', 'https://www.kipperlynsinclair.com/']::text[]),
    ('growth-and-development', 2, 'As Planning Commissioner she voted AGAINST the Jackson East industrial rezoning and said "the city moved too quickly," urging a Housing Needs Analysis and Environmental Action Plan first (2022 Q&A, first-party). As councilor (June 9, 2026) she pushed to pause/restrict data-center approvals pending electric and water capacity assessments and public review; her moratorium petition conditions growth on energy infrastructure capacity and ratepayer protection. Consistent infrastructure-first, slow-the-approvals posture. Matches Chair 2 (allow growth only where existing infrastructure can support it).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/', 'https://hillsboronewstimes.com/2026/06/10/data-center-lag-hillsboro-makes-little-headway-in-possible-regulations-moratorium/']::text[]),
    ('transportation-priorities', 2, 'She is President of the city Transportation Committee. On Feb 3, 2026 she personally MOVED adoption of Resolution 2910 authorizing transit grant applications and $175,000 in transit transportation impact fee funds for the local match (carried 5-0, Sinclair yes). First-party 2022 smart-growth plank: "promoting public transit, improving pedestrian and bicycle amenities"; 10th Ave vision includes "enhanced sidewalks for safe walkability." 2026 platform: housing near transit and job centers. Multimodal-forward, no anti-road or parking-reduction statements. Matches Chair 2 (invest equally in roads and multimodal options; require bike/pedestrian infrastructure in new development).', ARRAY['https://hillsboro-oregon.civicweb.net/document/256729/City%20Council%20-%2003%20Feb%202026.pdf', 'https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/']::text[]),
    ('local-environment', 1, 'First-party 2022 Q&A: voted against Jackson East rezoning on the Planning Commission pending an Environmental Action Plan; supports smart growth that "reduce[s] impervious surfaces, safeguard[s] environmentally sensitive areas." 2026: demanded additional public review plus electric/water capacity assessments before data-center approvals and to "stop their spread onto prime farmland"; petition cites heat islands and 4.5M gal/day water use. Recurring demand for environmental review as a precondition of development approval. Matches Chair 1 (require significant green space, tree preservation, and environmental review before approving development).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/', 'https://hillsboroherald.com/signatures-sought-on-hillsboro-data-center-moratorium-petition-brought-by-kipperlyn-sinclair/', 'https://www.kipperlynsinclair.com/']::text[]),
    ('homelessness-response', 2, '2022 candidate Q&A (first-party): praised the Safe Rest Pods partnership with Open Door HousingWorks and plans for "a permanent village with amenities such as heating and cooling for year-round use"; framed solutions as services, nonprofit collaboration, and affordable housing ("Public engagement, diverse planning, and collaborative partnerships become long term solutions to lessen the hardship"). During her tenure (seated Jan 2023) the city ran the Safe Rest Pods (Dec 2023-Oct 2024) and opened the 75-bed year-round Hillsboro Shelter (Dec 2025). No enforcement-first statements anywhere in her record. Confidence note: chair placement rests on her first-party pro-shelter/services statements; specific council roll-calls on shelter funding not individually located. Matches Chair 2 (expand shelter capacity and services as the primary strategy; use enforcement only after).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/', 'https://www.hillsboro-oregon.gov/Home/Components/News/News/16159/4300']::text[]),
    ('civil-rights', 2, 'First-party, post-election profile (Nov 10, 2022): "On all aspects, my first priority will always be diversity, equity and inclusion" and "I will vote in a way that breaks barriers." Reinforced in practice by proposing binding civil-rights-protective code (Ord 6513, 2026) with mandatory documentation/public reporting of federal enforcement contacts. Confidence note: values-statement + local action; no federal civil-rights policy statement. Matches Chair 2 (strengthen civil rights enforcement and address systemic discrimination).', ARRAY['https://hillsboronewstimes.com/2022/11/10/hillsboro-city-council-newcomer-wants-to-break-barriers/', 'https://hillsboronewstimes.com/2026/03/11/hillsboro-codifies-sanctuary-status-amid-local-ice-activity/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '92ad1ef9-117d-4042-a19e-438c0ec7dea6'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
