-- Migration 1156: Elizabeth Case (Councilor, Ward 2 Position B, Hillsboro OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 9 cited stances; blank spokes omitted.
-- Case elected Nov 2024, seated Jan 7, 2025 (term to Jan 2029); pre-tenure attribution rule applied.
-- economic-development and civil-rights carry MEDIUM confidence / values-statement inference flags — see reasoning.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, '2024 campaign platform (first-party): "It needs to be easier and more straightforward for everyone to build and get into housing" — advocates streamlining land-use/permitting processes while maintaining safety standards, plus "increased access to affordable housing" as a named priority and housing "for neighbors of all income levels." Matches targeted-help + easier-permits chair, not deregulation-only (she explicitly keeps safety standards) and not rent caps/public housing. Matches Chair 3 (offer targeted help like subsidies for affordable projects, first-time buyer assistance, and easier permitting).', ARRAY['https://elizabethcase.com/the-issues/', 'https://hillsboronewstimes.com/2024/08/23/ward-2-profile-elizabeth-case-joins-the-race-for-hillsboro-city-council/']::text[]),
    ('growth-and-development', 4, 'Campaign platform urges "clarity and ease at all levels of the housing crisis from land use to construction"; on South Hillsboro: "the decades of planning it took to begin developing South Hillsboro is a testament to patience and perseverance but we don''t have time for that anymore" — explicit impatience with slow planning/approvals and a push to accelerate development; as councilor she sided with continued industrial development (data centers) over pause proposals (June 2026). Matches Chair 4 (streamline permitting, reduce fees, and actively recruit development to grow the city).', ARRAY['https://elizabethcase.com/the-issues/', 'https://hillsboroherald.com/hillsboro-council-divided-at-data-center-work-session-dr-alcaire-pierces-the-bureaucratic-veil/']::text[]),
    ('climate-change', 3, 'First-party campaign platform: supports the City of Hillsboro Climate Action Plan; member of the city Environmental Stewardship Committee since late 2023; encourages companies to adopt solar energy and battery storage ("I will encourage more companies...to move in this direction"). Incremental clean-energy investment framing, no phase-out/emergency language. (Res 2911 CAP adoption Feb 3, 2026 passed 4-1 with Sinclair the only no — consistent with a Case yes, but her presence was not individually confirmed, so the campaign platform is the citable evidence.) Matches Chair 3 (invest in clean energy while gradually reducing reliance on fossil fuels).', ARRAY['https://elizabethcase.com/the-issues/']::text[]),
    ('local-immigration', 1, 'Voted yes on Resolution 2906 (Nov 18, 2025), adopted unanimously 5-0 with all five councilors present recorded yes (roll call verified in cross-official research for Pace/Salgado/Anvery; city announcement confirms unanimous adoption). The resolution declares a state of emergency over ICE conduct, "directs that City resources will not be used to enforce federal immigration laws," strengthens sanctuary measures, and reaffirms Oregon Sanctuary Promise laws. Council also unanimously adopted the ICE response plan Nov 24, 2025, and codified sanctuary provisions via Ord. 6513 (Mar 3, 2026, unanimous per prior verified research). Matches Chair 1 (refuse all ICE detainers; prohibit city employees from sharing immigration status).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254042/Adopted_Resolution_No._2906.pdf', 'https://www.hillsboro-oregon.gov/Home/Components/News/News/17035/']::text[]),
    ('immigration', 2, 'Same Res 2906 yes vote (Nov 18, 2025): resolution declares Hillsboro "a welcoming and inclusive city," calls immigration "a legacy to be honored and a strength to be protected," demands the Oregon congressional delegation prioritize comprehensive immigration reform with "a realistic pathway to citizenship for all aspiring Americans," and treats fear-driven loss of access to city services, schools, and healthcare (regardless of status) as the emergency harm to remedy. Matches the open-legal-immigration + services-regardless-of-status chair; goes beyond status quo but doesn''t demand full public funding of all services for undocumented residents. Matches Chair 2 (keep legal immigration open and let most residents use public services regardless of status).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254042/Adopted_Resolution_No._2906.pdf']::text[]),
    ('data-centers', 3, 'At the June 9, 2026 council work session on 17 pending data center applications, Case was one of four councilors (with Harris, Salgado, Anvery) who declined Councilor Sinclair''s push for an emergency ordinance/moratorium restricting data centers, favoring slower long-term administrative/regulatory pathways while council directed staff to explore regulation options. Her documented quote: "We are the economic engine of the state of Oregon here in Hillsboro. And so what we do matters for our jobs, our friends and neighbors'' livelihoods, as well as our own." Position = keep allowing development while studying regulation. Matches Chair 3 (allowing data center development with impact assessments, energy cost-sharing agreements).', ARRAY['https://hillsboroherald.com/hillsboro-council-divided-at-data-center-work-session-dr-alcaire-pierces-the-bureaucratic-veil/', 'https://hillsboronewstimes.com/2026/06/10/data-center-lag-hillsboro-makes-little-headway-in-possible-regulations-moratorium/']::text[]),
    ('economic-development', 4, 'MEDIUM CONFIDENCE (values-statement inference): Former Washington County Chamber of Commerce board chair (2024); frames Hillsboro''s identity around major-employer industrial growth ("We are the economic engine of the state of Oregon here in Hillsboro," June 9, 2026); declined to support Sinclair''s proposal to condition data centers on job-quality requirements (15 FTE/acre) — rejecting the community-benefit-requirement approach while defending continued recruitment/retention of the tax-abated data center industry. She has not explicitly endorsed tax abatements by name; chair chosen because she rejected conditions-based development and champions major-employer growth. Matches Chair 4 (compete actively for major employers with significant tax abatements and infrastructure).', ARRAY['https://hillsboroherald.com/hillsboro-council-divided-at-data-center-work-session-dr-alcaire-pierces-the-bureaucratic-veil/', 'https://elizabethcase.com/the-issues/']::text[]),
    ('jail-capacity', 4, 'First-party campaign platform on the Washington County jail: "I support getting the jail back to full operating levels" to address overcrowding and forced releases. Advocates expanding operational jail capacity (reopening/restoring beds) as the response to overcrowding. Confidence note: "back to full operating levels" is restoring built capacity, not new construction; not proposing diversion/decarceration and explicitly wants more operating capacity than today. Matches Chair 4 (building additional jail capacity to address overcrowding and facility conditions).', ARRAY['https://elizabethcase.com/the-issues/']::text[]),
    ('civil-rights', 2, 'MEDIUM CONFIDENCE (values-statement inference): DEI is a named 2024 campaign priority; as Chamber board chair she championed expanding diversity business advisory councils (Latino, Black, LGBTQ+, Veterans, Asian/Pacific Islander); voted yes on Res 2906 (Nov 18, 2025), which condemns federal actions that "institutionalize racial profiling and encourage discrimination" and demands rights protections for all regardless of status. Evidence is affirmative DEI programming + anti-profiling vote, mapped to the systemic-discrimination chair. Matches Chair 2 (strengthen civil rights enforcement and address systemic discrimination).', ARRAY['https://elizabethcase.com/the-issues/', 'https://hillsboro-oregon.civicweb.net/document/254042/Adopted_Resolution_No._2906.pdf']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT 'c95bfe4d-65c0-41a2-9c54-21a958f54f58'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, '2024 campaign platform (first-party): "It needs to be easier and more straightforward for everyone to build and get into housing" — advocates streamlining land-use/permitting processes while maintaining safety standards, plus "increased access to affordable housing" as a named priority and housing "for neighbors of all income levels." Matches targeted-help + easier-permits chair, not deregulation-only (she explicitly keeps safety standards) and not rent caps/public housing. Matches Chair 3 (offer targeted help like subsidies for affordable projects, first-time buyer assistance, and easier permitting).', ARRAY['https://elizabethcase.com/the-issues/', 'https://hillsboronewstimes.com/2024/08/23/ward-2-profile-elizabeth-case-joins-the-race-for-hillsboro-city-council/']::text[]),
    ('growth-and-development', 4, 'Campaign platform urges "clarity and ease at all levels of the housing crisis from land use to construction"; on South Hillsboro: "the decades of planning it took to begin developing South Hillsboro is a testament to patience and perseverance but we don''t have time for that anymore" — explicit impatience with slow planning/approvals and a push to accelerate development; as councilor she sided with continued industrial development (data centers) over pause proposals (June 2026). Matches Chair 4 (streamline permitting, reduce fees, and actively recruit development to grow the city).', ARRAY['https://elizabethcase.com/the-issues/', 'https://hillsboroherald.com/hillsboro-council-divided-at-data-center-work-session-dr-alcaire-pierces-the-bureaucratic-veil/']::text[]),
    ('climate-change', 3, 'First-party campaign platform: supports the City of Hillsboro Climate Action Plan; member of the city Environmental Stewardship Committee since late 2023; encourages companies to adopt solar energy and battery storage ("I will encourage more companies...to move in this direction"). Incremental clean-energy investment framing, no phase-out/emergency language. (Res 2911 CAP adoption Feb 3, 2026 passed 4-1 with Sinclair the only no — consistent with a Case yes, but her presence was not individually confirmed, so the campaign platform is the citable evidence.) Matches Chair 3 (invest in clean energy while gradually reducing reliance on fossil fuels).', ARRAY['https://elizabethcase.com/the-issues/']::text[]),
    ('local-immigration', 1, 'Voted yes on Resolution 2906 (Nov 18, 2025), adopted unanimously 5-0 with all five councilors present recorded yes (roll call verified in cross-official research for Pace/Salgado/Anvery; city announcement confirms unanimous adoption). The resolution declares a state of emergency over ICE conduct, "directs that City resources will not be used to enforce federal immigration laws," strengthens sanctuary measures, and reaffirms Oregon Sanctuary Promise laws. Council also unanimously adopted the ICE response plan Nov 24, 2025, and codified sanctuary provisions via Ord. 6513 (Mar 3, 2026, unanimous per prior verified research). Matches Chair 1 (refuse all ICE detainers; prohibit city employees from sharing immigration status).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254042/Adopted_Resolution_No._2906.pdf', 'https://www.hillsboro-oregon.gov/Home/Components/News/News/17035/']::text[]),
    ('immigration', 2, 'Same Res 2906 yes vote (Nov 18, 2025): resolution declares Hillsboro "a welcoming and inclusive city," calls immigration "a legacy to be honored and a strength to be protected," demands the Oregon congressional delegation prioritize comprehensive immigration reform with "a realistic pathway to citizenship for all aspiring Americans," and treats fear-driven loss of access to city services, schools, and healthcare (regardless of status) as the emergency harm to remedy. Matches the open-legal-immigration + services-regardless-of-status chair; goes beyond status quo but doesn''t demand full public funding of all services for undocumented residents. Matches Chair 2 (keep legal immigration open and let most residents use public services regardless of status).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254042/Adopted_Resolution_No._2906.pdf']::text[]),
    ('data-centers', 3, 'At the June 9, 2026 council work session on 17 pending data center applications, Case was one of four councilors (with Harris, Salgado, Anvery) who declined Councilor Sinclair''s push for an emergency ordinance/moratorium restricting data centers, favoring slower long-term administrative/regulatory pathways while council directed staff to explore regulation options. Her documented quote: "We are the economic engine of the state of Oregon here in Hillsboro. And so what we do matters for our jobs, our friends and neighbors'' livelihoods, as well as our own." Position = keep allowing development while studying regulation. Matches Chair 3 (allowing data center development with impact assessments, energy cost-sharing agreements).', ARRAY['https://hillsboroherald.com/hillsboro-council-divided-at-data-center-work-session-dr-alcaire-pierces-the-bureaucratic-veil/', 'https://hillsboronewstimes.com/2026/06/10/data-center-lag-hillsboro-makes-little-headway-in-possible-regulations-moratorium/']::text[]),
    ('economic-development', 4, 'MEDIUM CONFIDENCE (values-statement inference): Former Washington County Chamber of Commerce board chair (2024); frames Hillsboro''s identity around major-employer industrial growth ("We are the economic engine of the state of Oregon here in Hillsboro," June 9, 2026); declined to support Sinclair''s proposal to condition data centers on job-quality requirements (15 FTE/acre) — rejecting the community-benefit-requirement approach while defending continued recruitment/retention of the tax-abated data center industry. She has not explicitly endorsed tax abatements by name; chair chosen because she rejected conditions-based development and champions major-employer growth. Matches Chair 4 (compete actively for major employers with significant tax abatements and infrastructure).', ARRAY['https://hillsboroherald.com/hillsboro-council-divided-at-data-center-work-session-dr-alcaire-pierces-the-bureaucratic-veil/', 'https://elizabethcase.com/the-issues/']::text[]),
    ('jail-capacity', 4, 'First-party campaign platform on the Washington County jail: "I support getting the jail back to full operating levels" to address overcrowding and forced releases. Advocates expanding operational jail capacity (reopening/restoring beds) as the response to overcrowding. Confidence note: "back to full operating levels" is restoring built capacity, not new construction; not proposing diversion/decarceration and explicitly wants more operating capacity than today. Matches Chair 4 (building additional jail capacity to address overcrowding and facility conditions).', ARRAY['https://elizabethcase.com/the-issues/']::text[]),
    ('civil-rights', 2, 'MEDIUM CONFIDENCE (values-statement inference): DEI is a named 2024 campaign priority; as Chamber board chair she championed expanding diversity business advisory councils (Latino, Black, LGBTQ+, Veterans, Asian/Pacific Islander); voted yes on Res 2906 (Nov 18, 2025), which condemns federal actions that "institutionalize racial profiling and encourage discrimination" and demands rights protections for all regardless of status. Evidence is affirmative DEI programming + anti-profiling vote, mapped to the systemic-discrimination chair. Matches Chair 2 (strengthen civil rights enforcement and address systemic discrimination).', ARRAY['https://elizabethcase.com/the-issues/', 'https://hillsboro-oregon.civicweb.net/document/254042/Adopted_Resolution_No._2906.pdf']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT 'c95bfe4d-65c0-41a2-9c54-21a958f54f58'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
