-- Migration 1157: Olivia Alcaire (Councilor, Ward 3 Position A, Hillsboro OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 8 cited stances; blank spokes omitted.
-- Alcaire appointed Feb 2017, elected Nov 2018 (unopposed), re-elected Nov 2022 (term to Jan 2027, term-limited).
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('local-immigration', 1, 'Voted yes on Res 2906 (Nov 18, 2025) declaring a state of emergency over ICE activity — condemns "the misuse of immigration enforcement to detain and deport individuals who are lawfully present," commits city to Oregon Sanctuary Promise Laws, and directs that city resources will not be used to enforce federal immigration law. She was present and spoke at the meeting ("It''s because people showed up at the last meeting that we are having this consideration tonight... I know that there are people who can''t be here tonight because they''re afraid to be here"); named roll call 5-0 all-yes verified in cross-official research. Matches Chair 1 (refuse all ICE detainers; prohibit city employees from sharing immigration status).', ARRAY['https://hillsboronewstimes.com/2025/11/19/hillsboro-declares-state-of-emergency-over-local-ice-activity/', 'https://hillsboro-oregon.civicweb.net/document/254042/Adopted_Resolution_No._2906.pdf']::text[]),
    ('immigration', 2, 'Same Res 2906 yes vote (present, quoted): emergency declaration committing city support for immigrant and mixed-status families regardless of status, condemning enforcement misuse; plus sanctuary codification support (Ord 6513). Her public statements urge immigrant residents to participate ("show up and speak up... represent your community") and acknowledge fear in the community. No evidence on expanding legal immigration pathways. Matches Chair 2 (keep legal immigration open and let most residents use public services regardless of status).', ARRAY['https://hillsboronewstimes.com/2025/11/19/hillsboro-declares-state-of-emergency-over-local-ice-activity/']::text[]),
    ('data-centers', 1, 'At the June 2, 2026 council work session on the surge of 17 standalone data-center applications, Alcaire backed Councilor Sinclair''s emergency ordinance to immediately strip data centers of primary-permitted-use status citywide (with 15 permanent jobs/acre and water/electric capacity review requirements): "I would support this what Kipperlyn is suggesting right now and to take action." She criticized the majority''s slower administrative path: "We''re just making money. We''re generating money, and we''re sacrificing people''s well-being." She was skeptical a formal land-use moratorium could work legally and instead demanded equivalent immediate zoning restriction. Matches Chair 1 (imposing a moratorium on new data center construction until energy infrastructure catches up).', ARRAY['https://hillsboroherald.com/hillsboro-council-divided-at-data-center-work-session-dr-alcaire-pierces-the-bureaucratic-veil/', 'https://hillsboronewstimes.com/2026/06/10/data-center-lag-hillsboro-makes-little-headway-in-possible-regulations-moratorium/']::text[]),
    ('economic-development', 3, '2022 (first-party): supported industrializing Jackson East to strengthen Hillsboro''s technology/business sector, bringing "jobs, diverse housing needs, and great schools." 2026: endorsed data-center regulation package requiring at least 15 permanent full-time jobs per acre and additional public review — industry-targeted growth with job-quality strings attached — while rejecting revenue-first growth ("We''re just making money... sacrificing people''s well-being"). Combined record = targeted, conditioned industrial development, not maximal incentives and not anti-corporate. Matches Chair 3 (targeted incentives for specific industries with community benefit agreements and job quality standards).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/', 'https://hillsboroherald.com/hillsboro-council-divided-at-data-center-work-session-dr-alcaire-pierces-the-bureaucratic-veil/']::text[]),
    ('growth-and-development', 3, '2022 Q&A (first-party): backed the Jackson East expansion/rezoning for jobs, housing and schools, noting council "listened to the residents, did everything they requested"; separately endorsed water-rate increases as "necessary to support our city''s infrastructure" in light of growth and climate impacts, with equity mechanisms (HiLight discounts) for low-income residents. Pattern = pro-growth with proactive infrastructure funding and resident engagement. Matches Chair 3 (plan proactively — invest in infrastructure ahead of growth to support responsible expansion).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/']::text[]),
    ('homelessness-response', 2, '2022 Q&A (first-party): supports the city''s transitional-housing projects — the Turnkey initiative and Safe Rest Pods — and advocated city-funded supportive services as the response, hoping solutions produce "more stable housing and meeting basic needs." She acknowledged business owners'' harms yet her prescribed remedy was services/shelter, not enforcement. (Hillsboro subsequently built the $17M 75-bed year-round shelter, opened 2025, but no Alcaire-named funding vote was located, so her first-party statement is the anchor.) Matches Chair 2 (expand shelter capacity and services as the primary strategy; use enforcement only after).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/']::text[]),
    ('housing', 3, '2022 platform statement: goal to "expand affordable housing options"; supports transitional-housing projects (Turnkey, Safe Rest Pods) and preventing gentrification along the 10th Ave/Calle Diez corridor (grant accessibility for small-business facade improvements); long-time board member of Bienestar (affordable-housing nonprofit), the role from which she joined council in 2017. No evidence of rent-cap/public-housing-scale positions — evidence sits at targeted-support tier. Matches Chair 3 (offer targeted help like subsidies for affordable projects, first-time buyer assistance, and easier permitting).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/', 'https://bienestar-or.org/board-member-olivia-alcaire-joins-hillsboro-city-council/']::text[]),
    ('transportation-priorities', 3, '2022 Q&A (first-party) on the 10th Avenue/Calle Diez corridor: wants "slower traffic," safer pedestrian spaces, and outdoor dining in a targeted cultural corridor — selective pedestrian-oriented investment where density/activity supports it, not a citywide car-reduction or transit-first agenda. (Res 2910 transit grant match 5-0 could not be attributed — her presence at that vote was not confirmed.) Matches Chair 3 (maintain roads while selectively adding transit connections and pedestrian improvements).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '6f901dde-b4d9-49d9-90ef-f318166664d9'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('local-immigration', 1, 'Voted yes on Res 2906 (Nov 18, 2025) declaring a state of emergency over ICE activity — condemns "the misuse of immigration enforcement to detain and deport individuals who are lawfully present," commits city to Oregon Sanctuary Promise Laws, and directs that city resources will not be used to enforce federal immigration law. She was present and spoke at the meeting ("It''s because people showed up at the last meeting that we are having this consideration tonight... I know that there are people who can''t be here tonight because they''re afraid to be here"); named roll call 5-0 all-yes verified in cross-official research. Matches Chair 1 (refuse all ICE detainers; prohibit city employees from sharing immigration status).', ARRAY['https://hillsboronewstimes.com/2025/11/19/hillsboro-declares-state-of-emergency-over-local-ice-activity/', 'https://hillsboro-oregon.civicweb.net/document/254042/Adopted_Resolution_No._2906.pdf']::text[]),
    ('immigration', 2, 'Same Res 2906 yes vote (present, quoted): emergency declaration committing city support for immigrant and mixed-status families regardless of status, condemning enforcement misuse; plus sanctuary codification support (Ord 6513). Her public statements urge immigrant residents to participate ("show up and speak up... represent your community") and acknowledge fear in the community. No evidence on expanding legal immigration pathways. Matches Chair 2 (keep legal immigration open and let most residents use public services regardless of status).', ARRAY['https://hillsboronewstimes.com/2025/11/19/hillsboro-declares-state-of-emergency-over-local-ice-activity/']::text[]),
    ('data-centers', 1, 'At the June 2, 2026 council work session on the surge of 17 standalone data-center applications, Alcaire backed Councilor Sinclair''s emergency ordinance to immediately strip data centers of primary-permitted-use status citywide (with 15 permanent jobs/acre and water/electric capacity review requirements): "I would support this what Kipperlyn is suggesting right now and to take action." She criticized the majority''s slower administrative path: "We''re just making money. We''re generating money, and we''re sacrificing people''s well-being." She was skeptical a formal land-use moratorium could work legally and instead demanded equivalent immediate zoning restriction. Matches Chair 1 (imposing a moratorium on new data center construction until energy infrastructure catches up).', ARRAY['https://hillsboroherald.com/hillsboro-council-divided-at-data-center-work-session-dr-alcaire-pierces-the-bureaucratic-veil/', 'https://hillsboronewstimes.com/2026/06/10/data-center-lag-hillsboro-makes-little-headway-in-possible-regulations-moratorium/']::text[]),
    ('economic-development', 3, '2022 (first-party): supported industrializing Jackson East to strengthen Hillsboro''s technology/business sector, bringing "jobs, diverse housing needs, and great schools." 2026: endorsed data-center regulation package requiring at least 15 permanent full-time jobs per acre and additional public review — industry-targeted growth with job-quality strings attached — while rejecting revenue-first growth ("We''re just making money... sacrificing people''s well-being"). Combined record = targeted, conditioned industrial development, not maximal incentives and not anti-corporate. Matches Chair 3 (targeted incentives for specific industries with community benefit agreements and job quality standards).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/', 'https://hillsboroherald.com/hillsboro-council-divided-at-data-center-work-session-dr-alcaire-pierces-the-bureaucratic-veil/']::text[]),
    ('growth-and-development', 3, '2022 Q&A (first-party): backed the Jackson East expansion/rezoning for jobs, housing and schools, noting council "listened to the residents, did everything they requested"; separately endorsed water-rate increases as "necessary to support our city''s infrastructure" in light of growth and climate impacts, with equity mechanisms (HiLight discounts) for low-income residents. Pattern = pro-growth with proactive infrastructure funding and resident engagement. Matches Chair 3 (plan proactively — invest in infrastructure ahead of growth to support responsible expansion).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/']::text[]),
    ('homelessness-response', 2, '2022 Q&A (first-party): supports the city''s transitional-housing projects — the Turnkey initiative and Safe Rest Pods — and advocated city-funded supportive services as the response, hoping solutions produce "more stable housing and meeting basic needs." She acknowledged business owners'' harms yet her prescribed remedy was services/shelter, not enforcement. (Hillsboro subsequently built the $17M 75-bed year-round shelter, opened 2025, but no Alcaire-named funding vote was located, so her first-party statement is the anchor.) Matches Chair 2 (expand shelter capacity and services as the primary strategy; use enforcement only after).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/']::text[]),
    ('housing', 3, '2022 platform statement: goal to "expand affordable housing options"; supports transitional-housing projects (Turnkey, Safe Rest Pods) and preventing gentrification along the 10th Ave/Calle Diez corridor (grant accessibility for small-business facade improvements); long-time board member of Bienestar (affordable-housing nonprofit), the role from which she joined council in 2017. No evidence of rent-cap/public-housing-scale positions — evidence sits at targeted-support tier. Matches Chair 3 (offer targeted help like subsidies for affordable projects, first-time buyer assistance, and easier permitting).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/', 'https://bienestar-or.org/board-member-olivia-alcaire-joins-hillsboro-city-council/']::text[]),
    ('transportation-priorities', 3, '2022 Q&A (first-party) on the 10th Avenue/Calle Diez corridor: wants "slower traffic," safer pedestrian spaces, and outdoor dining in a targeted cultural corridor — selective pedestrian-oriented investment where density/activity supports it, not a citywide car-reduction or transit-first agenda. (Res 2910 transit grant match 5-0 could not be attributed — her presence at that vote was not confirmed.) Matches Chair 3 (maintain roads while selectively adding transit connections and pedestrian improvements).', ARRAY['https://hillsboronewstimes.com/2022/10/31/qa-hillsboro-city-council-candidates-on-the-issues/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '6f901dde-b4d9-49d9-90ef-f318166664d9'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
