-- Migration 1158: Rob Harris (Councilor, Ward 3 Position B, Council President, Hillsboro OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 7 cited stances; blank spokes omitted.
-- Harris elected Nov 2024, seated Jan 7, 2025 (term to Jan 2029); pre-tenure attribution rule applied.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('data-centers', 1, 'In April 2026, Harris himself introduced a request for a time-limited suspension (proposed one-year pause) on permits for new standalone data centers in Hillsboro, to give the city time to evaluate land use within current boundaries and develop new regulations; quoted: "I appreciate Senator Sollman''s partnership on this critical issue... She has led work to increase accountability for data centers at the state level." At the June 9, 2026 work session he declined Councilor Sinclair''s 45-day emergency-ordinance route, instead steering the majority (Anvery/Case/Salgado/Harris) to authorize staff to investigate a statutory land-use moratorium plus development-code text amendments ("It''s just authorizing the staff again to explore it") — a pause via the deliberate statutory path, not the emergency one. His concrete proposal is still a temporary moratorium on new approvals; he is softer/more procedural than Sinclair. Matches Chair 1 (imposing a moratorium on new data center construction until energy infrastructure catches up).', ARRAY['https://www.grantspasstribune.com/hillsboro-weighs-temporary-halt-on-data-centers-as-oregon-reexamines-energy-costs-and-growth/', 'https://hillsboronewstimes.com/2026/06/10/data-center-lag-hillsboro-makes-little-headway-in-possible-regulations-moratorium/', 'https://hillsboroherald.com/hillsboro-council-divided-at-data-center-work-session-dr-alcaire-pierces-the-bureaucratic-veil/']::text[]),
    ('local-immigration', 1, 'Voted yes on Res 2906 (Nov 18, 2025) declaring a city state of emergency over federal immigration enforcement activity — passed 5-0 with all five councilors named yes in the minutes (cross-official-verified roll call; those minutes were approved on the Dec 2, 2025 consent agenda Harris also voted for). The resolution reaffirms commitment to Oregon''s Sanctuary Promise Laws, directs that city resources will not be used to enforce federal immigration law, condemns enforcement tactics as harmful, and directs signage on nonpublic building areas, expanded know-your-rights materials, and staff sanctuary-law training. Matches Chair 1 (refuse all ICE detainers; prohibit city employees from sharing immigration status).', ARRAY['https://hillsboronewstimes.com/2025/11/19/hillsboro-declares-state-of-emergency-over-local-ice-activity/', 'https://www.hillsboro-oregon.gov/Home/Components/News/News/17035/', 'https://hillsboronewstimes.com/2026/03/11/hillsboro-codifies-sanctuary-status-amid-local-ice-activity/']::text[]),
    ('housing', 3, 'Dec 2, 2025 — voted yes (named, 4-0) on Res 2907 readopting the Hillsboro Housing Production Strategy Cycle 1 (2025-2030), a state-required package of "specific and meaningful plans, tools, actions, and policies to address identified housing needs." Minutes: "Councilor Harris supported the plan with the understanding that it does not bind the City to regional tax decisions. Harris also emphasized urgency in reviewing System Development Charges (SDC) and building codes" — targeted production tools plus reducing permitting/fee barriers, not rent caps or public housing operation. Consistent with 2024 campaign priority of "housing accessibility." Matches Chair 3 (offer targeted help like subsidies for affordable projects, first-time buyer assistance, and easier permitting).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254837/City%20Council%20-%2002%20Dec%202025.pdf', 'https://hillsboronewstimes.com/2024/08/23/ward-3-profile-rob-harris-seeks-a-spot-on-hillsboro-city-council/']::text[]),
    ('climate-change', 3, 'Feb 3, 2026 — Harris SECONDED the motion and voted yes (named) to adopt Res 2911, the City''s first Climate Action Plan (carried 4-1, Sinclair the lone no on process grounds). Minutes: "Councilor Harris noted Council can have ongoing engagement with staff as the plan is a living document." He also attended the Dec 2, 2025 CAP work session. Campaign listed "sustainability" among livability priorities. Supports institutionalized, incremental municipal climate action; no evidence of emergency-declaration or rapid fossil-fuel-phase-out advocacy (contrast: he declined the data-center emergency route). Matches Chair 3 (invest in clean energy while gradually reducing reliance on fossil fuels).', ARRAY['https://hillsboro-oregon.civicweb.net/document/256729/City%20Council%20-%2003%20Feb%202026.pdf']::text[]),
    ('transportation-priorities', 3, 'Feb 3, 2026 — voted yes (named, 5-0) on Res 2910 authorizing grant applications for two transit projects and committing $175,000 in transit transportation impact fee funds as the required local match. 2024 campaign priority: "improved transportation infrastructure and walkability." Supports selective transit/pedestrian investment; no evidence of a road-capacity-first or transit-first-citywide position. Matches Chair 3 (maintain roads while selectively adding transit connections and pedestrian improvements).', ARRAY['https://hillsboro-oregon.civicweb.net/document/256729/City%20Council%20-%2003%20Feb%202026.pdf', 'https://hillsboronewstimes.com/2024/08/23/ward-3-profile-rob-harris-seeks-a-spot-on-hillsboro-city-council/']::text[]),
    ('homelessness-response', 3, '2024 Vote411/LWV questionnaire answer (first-party campaign statement): "City employees who have regular contact with homeless campers should be trained to assist with referring to resources such as housing, food and healthcare and to be educated on some forms of constructive behavior modification prompts." Campaign priorities included "homeless intervention programs." Service-referral/outreach orientation combined with pragmatic behavior management of campers in public space; no evidence for housing-first-no-enforcement or enforcement-first. Matches Chair 3 (invest in outreach, shelter, and mental health services while enforcing basic public-space rules).', ARRAY['https://onyourballot.vote411.org/race-detail.do?id=68912016']::text[]),
    ('growth-and-development', 3, 'Dec 2, 2025 — Harris personally MOVED first readings of Ord 6509 (Comprehensive Plan Amendment incorporating the Public Facilities Plan/system master plans — infrastructure planning ahead of growth) and Ord 6510 (adopting Metro 2040 Growth Concept regional & town center boundaries), both carrying 4-0 with Harris named yes. Consistent with his data-center pause rationale — "evaluate land use within current boundaries" before approving further expansion — and his urban-planning background. Managed, plan-first growth posture rather than growth caps or deregulation. Matches Chair 3 (plan proactively — invest in infrastructure ahead of growth to support responsible expansion).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254837/City%20Council%20-%2002%20Dec%202025.pdf', 'https://www.grantspasstribune.com/hillsboro-weighs-temporary-halt-on-data-centers-as-oregon-reexamines-energy-costs-and-growth/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '38aa9579-5fdf-40a5-8f7a-738f16b3d655'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('data-centers', 1, 'In April 2026, Harris himself introduced a request for a time-limited suspension (proposed one-year pause) on permits for new standalone data centers in Hillsboro, to give the city time to evaluate land use within current boundaries and develop new regulations; quoted: "I appreciate Senator Sollman''s partnership on this critical issue... She has led work to increase accountability for data centers at the state level." At the June 9, 2026 work session he declined Councilor Sinclair''s 45-day emergency-ordinance route, instead steering the majority (Anvery/Case/Salgado/Harris) to authorize staff to investigate a statutory land-use moratorium plus development-code text amendments ("It''s just authorizing the staff again to explore it") — a pause via the deliberate statutory path, not the emergency one. His concrete proposal is still a temporary moratorium on new approvals; he is softer/more procedural than Sinclair. Matches Chair 1 (imposing a moratorium on new data center construction until energy infrastructure catches up).', ARRAY['https://www.grantspasstribune.com/hillsboro-weighs-temporary-halt-on-data-centers-as-oregon-reexamines-energy-costs-and-growth/', 'https://hillsboronewstimes.com/2026/06/10/data-center-lag-hillsboro-makes-little-headway-in-possible-regulations-moratorium/', 'https://hillsboroherald.com/hillsboro-council-divided-at-data-center-work-session-dr-alcaire-pierces-the-bureaucratic-veil/']::text[]),
    ('local-immigration', 1, 'Voted yes on Res 2906 (Nov 18, 2025) declaring a city state of emergency over federal immigration enforcement activity — passed 5-0 with all five councilors named yes in the minutes (cross-official-verified roll call; those minutes were approved on the Dec 2, 2025 consent agenda Harris also voted for). The resolution reaffirms commitment to Oregon''s Sanctuary Promise Laws, directs that city resources will not be used to enforce federal immigration law, condemns enforcement tactics as harmful, and directs signage on nonpublic building areas, expanded know-your-rights materials, and staff sanctuary-law training. Matches Chair 1 (refuse all ICE detainers; prohibit city employees from sharing immigration status).', ARRAY['https://hillsboronewstimes.com/2025/11/19/hillsboro-declares-state-of-emergency-over-local-ice-activity/', 'https://www.hillsboro-oregon.gov/Home/Components/News/News/17035/', 'https://hillsboronewstimes.com/2026/03/11/hillsboro-codifies-sanctuary-status-amid-local-ice-activity/']::text[]),
    ('housing', 3, 'Dec 2, 2025 — voted yes (named, 4-0) on Res 2907 readopting the Hillsboro Housing Production Strategy Cycle 1 (2025-2030), a state-required package of "specific and meaningful plans, tools, actions, and policies to address identified housing needs." Minutes: "Councilor Harris supported the plan with the understanding that it does not bind the City to regional tax decisions. Harris also emphasized urgency in reviewing System Development Charges (SDC) and building codes" — targeted production tools plus reducing permitting/fee barriers, not rent caps or public housing operation. Consistent with 2024 campaign priority of "housing accessibility." Matches Chair 3 (offer targeted help like subsidies for affordable projects, first-time buyer assistance, and easier permitting).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254837/City%20Council%20-%2002%20Dec%202025.pdf', 'https://hillsboronewstimes.com/2024/08/23/ward-3-profile-rob-harris-seeks-a-spot-on-hillsboro-city-council/']::text[]),
    ('climate-change', 3, 'Feb 3, 2026 — Harris SECONDED the motion and voted yes (named) to adopt Res 2911, the City''s first Climate Action Plan (carried 4-1, Sinclair the lone no on process grounds). Minutes: "Councilor Harris noted Council can have ongoing engagement with staff as the plan is a living document." He also attended the Dec 2, 2025 CAP work session. Campaign listed "sustainability" among livability priorities. Supports institutionalized, incremental municipal climate action; no evidence of emergency-declaration or rapid fossil-fuel-phase-out advocacy (contrast: he declined the data-center emergency route). Matches Chair 3 (invest in clean energy while gradually reducing reliance on fossil fuels).', ARRAY['https://hillsboro-oregon.civicweb.net/document/256729/City%20Council%20-%2003%20Feb%202026.pdf']::text[]),
    ('transportation-priorities', 3, 'Feb 3, 2026 — voted yes (named, 5-0) on Res 2910 authorizing grant applications for two transit projects and committing $175,000 in transit transportation impact fee funds as the required local match. 2024 campaign priority: "improved transportation infrastructure and walkability." Supports selective transit/pedestrian investment; no evidence of a road-capacity-first or transit-first-citywide position. Matches Chair 3 (maintain roads while selectively adding transit connections and pedestrian improvements).', ARRAY['https://hillsboro-oregon.civicweb.net/document/256729/City%20Council%20-%2003%20Feb%202026.pdf', 'https://hillsboronewstimes.com/2024/08/23/ward-3-profile-rob-harris-seeks-a-spot-on-hillsboro-city-council/']::text[]),
    ('homelessness-response', 3, '2024 Vote411/LWV questionnaire answer (first-party campaign statement): "City employees who have regular contact with homeless campers should be trained to assist with referring to resources such as housing, food and healthcare and to be educated on some forms of constructive behavior modification prompts." Campaign priorities included "homeless intervention programs." Service-referral/outreach orientation combined with pragmatic behavior management of campers in public space; no evidence for housing-first-no-enforcement or enforcement-first. Matches Chair 3 (invest in outreach, shelter, and mental health services while enforcing basic public-space rules).', ARRAY['https://onyourballot.vote411.org/race-detail.do?id=68912016']::text[]),
    ('growth-and-development', 3, 'Dec 2, 2025 — Harris personally MOVED first readings of Ord 6509 (Comprehensive Plan Amendment incorporating the Public Facilities Plan/system master plans — infrastructure planning ahead of growth) and Ord 6510 (adopting Metro 2040 Growth Concept regional & town center boundaries), both carrying 4-0 with Harris named yes. Consistent with his data-center pause rationale — "evaluate land use within current boundaries" before approving further expansion — and his urban-planning background. Managed, plan-first growth posture rather than growth caps or deregulation. Matches Chair 3 (plan proactively — invest in infrastructure ahead of growth to support responsible expansion).', ARRAY['https://hillsboro-oregon.civicweb.net/document/254837/City%20Council%20-%2002%20Dec%202025.pdf', 'https://www.grantspasstribune.com/hillsboro-weighs-temporary-halt-on-data-centers-as-oregon-reexamines-energy-costs-and-growth/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '38aa9579-5fdf-40a5-8f7a-738f16b3d655'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
