-- Migration 1161: Yi-Kang Hu (Mayor, Tigard OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 7 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Affordable housing was a core plank of Hu''s 2022 council platform, and at the Nov 9, 2023 grand opening of Alongside Senior Apartments (Tigard''s first low-income senior complex) then-Council President Hu praised the project as showing the city''s "dedication to creating an inclusive, compassionate and vibrant community," citing that 28% of Tigard households are severely rent-burdened. The project he championed was enabled by targeted city subsidies — property tax exemptions, waived system development charges, and a $1/year 99-year lease of city land — and as mayor he has touted electronic permitting modernization and lists housing among the council''s three key goals (May 2026 Mayor''s Corner). This matches the targeted-subsidies-plus-easier-permits chair, not rent caps/public housing or deregulation-only approaches.', ARRAY['https://valleytimes.news/2023/11/09/tigard-opens-first-low-income-housing-complex-for-seniors/', 'https://tigardlife.com/local-news/yi-kang-hu-2/', 'https://tigardlife.com/local-news/mayors-corner-may-2026/']::text[]),
    ('homelessness-response', 3, 'Hu''s documented approach pairs services investment with enforcement of public-space rules: at the Aug 26, 2025 council meeting he cited Tigard''s "significant resources" — affordable housing, policing, a safe parking lot, a shelter, and sanctioned camping space — while pushing Tualatin and Sherwood to "step up" via a county-facilitated regional dialogue. As mayor he backed the April 21, 2026 emergency ordinance tightening rules on camping materials on public property ("This is not about punishment. This is about having clear rules that can be applied consistently"), and in his May 2026 Mayor''s Corner described the strategy as "manage impacts through reasonable rules and a centralized location, while continuing to work with community partners to connect people with available services." That is precisely the outreach/shelter/services-plus-reasonable-rules chair.', ARRAY['https://tigardlife.com/featured/as-homelessness-surges-tigard-revisits-regulations-questions-equity-of-shared-response/', 'https://valleytimes.news/2026/04/24/tigard-tightens-ban-on-keeping-camping-materials-on-city-property/', 'https://tigardlife.com/local-news/mayors-corner-may-2026/']::text[]),
    ('homelessness', 3, 'On public camping specifically, Hu supports enforcement conditioned on the city maintaining alternatives: Tigard keeps a sanctioned public campsite at Public Works, a shelter, and a safe lot (which Hu enumerated Aug 26, 2025), while restricting camping elsewhere and — under the April 21, 2026 ordinance he supported — barring daytime storage of camping materials on sidewalks, framed as keeping sidewalks "passable for everyone including people with disabilities" and explicitly "not about punishment." Outreach staff helped campers rather than routing them to criminal justice, and Hu emphasizes connecting people to services through community partners (May 2026). This best fits enforcement-paired-with-available-shelter-and-service-diversion rather than blanket criminal bans or a right-to-camp position.', ARRAY['https://valleytimes.news/2026/04/24/tigard-tightens-ban-on-keeping-camping-materials-on-city-property/', 'https://tigardlife.com/featured/as-homelessness-surges-tigard-revisits-regulations-questions-equity-of-shared-response/', 'https://tigardlife.com/local-news/mayors-corner-may-2026/']::text[]),
    ('public-safety-approach', 4, 'Hu has made expanding police capacity a signature mayoral initiative: he championed the public safety facility bond (Measure 34-349) that council referred to voters on Feb 17, 2026, writing in Mayor''s Corner columns that the 1980s police building designed for 25 officers now serves 70+ officers plus 16 staff, that the city wastes nearly $1 million/year maintaining aging facilities, and asking voters to accept roughly $13.60/month in added property tax over ~30 years for a modern integrated police/public works/emergency operations facility. "Public safety and stability" is one of his stated top priorities, and community safety was a plank of his 2022 platform. His documented record is about growing police facilities, capacity, and resilience — not reallocating police funding — though there is no evidence he wants police spending to trump all other services.', ARRAY['https://tigardlife.com/local-news/mayors-corner-investing-in-tigards-future-safety-and-resilience/', 'https://tigardlife.com/local-news/mayors-corner-may-2026/', 'https://www.kgw.com/article/news/politics/tigard-city-council-appoints-mayor-yi-kang-hu/283-3c320b4a-25ce-4438-94f6-5e13634440ab']::text[]),
    ('transportation-priorities', 2, 'Hu says he joined the Tigard Planning Commission and Transportation Advisory Committee ~2015 specifically "to advocate for safer streets and more sidewalks in our community," and his 2022 council platform was "centered on improved street and pedestrian accessibility." As mayor (Jan 2026 Mayor''s Corner) he highlighted safety upgrades near major roads and schools and expanded Fanno Creek Trail connections for walkers and cyclists, and in April 2026 stressed keeping sidewalks passable for people with disabilities, families, and seniors as "a basic function of the city government." His record balances road safety investment with strong pedestrian/multimodal advocacy rather than a transit-first, parking-reduction agenda or a roads-only stance.', ARRAY['https://tigardlife.com/local-news/yi-kang-hu-2/', 'https://tigardlife.com/local-news/mayors-corner-january-2026/', 'https://valleytimes.news/2026/04/24/tigard-tightens-ban-on-keeping-camping-materials-on-city-property/']::text[]),
    ('growth-and-development', 3, 'Hu''s documented posture is proactive infrastructure planning ahead of growth: in his May 2026 Mayor''s Corner he cautioned that "delaying critical infrastructure comes with real costs" and that construction costs rise over time, and his January 2026 column touted completing the Reservoir 18 water-system project, shaping the River Terrace 2.0 expansion (~4,500 homes on 500 annexed acres) through community input, and modernizing electronic permitting. He spent ~7 years on the Planning Commission (as president) guiding Tigard''s growth planning before joining council in Jan 2023. This matches planning proactively and investing in infrastructure to support responsible expansion, not growth caps or wholesale deregulation.', ARRAY['https://tigardlife.com/local-news/mayors-corner-may-2026/', 'https://tigardlife.com/local-news/mayors-corner-january-2026/', 'https://businesstribune.online/2024/07/15/tigard-moves-forward-with-river-terrace-2-0-planning-creating-possibility-of-4500-new-homes/']::text[]),
    ('economic-development', 3, '"Supporting local businesses" is one of Hu''s stated top mayoral priorities, and his January 2026 Mayor''s Corner credits the city with strengthening "small and family-run shops through business-support programs." At the same time he serves on the Town Center Advisory Commission and the Urban Renewal Funding Selection Subcommittee, the bodies that direct Tigard''s tax-increment-financing incentives to targeted downtown/Triangle redevelopment, and economic development was a plank of his 2022 platform. His record combines small-business programs with targeted, place-based incentives rather than either rejecting incentives outright or courting large employers with maximum abatements.', ARRAY['https://tigardlife.com/local-news/mayors-corner-january-2026/', 'https://www.kgw.com/article/news/politics/tigard-city-council-appoints-mayor-yi-kang-hu/283-3c320b4a-25ce-4438-94f6-5e13634440ab', 'https://tigardlife.com/local-news/yi-kang-hu-2/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '6701cd53-e7fb-491c-9b45-d0474705349e'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Affordable housing was a core plank of Hu''s 2022 council platform, and at the Nov 9, 2023 grand opening of Alongside Senior Apartments (Tigard''s first low-income senior complex) then-Council President Hu praised the project as showing the city''s "dedication to creating an inclusive, compassionate and vibrant community," citing that 28% of Tigard households are severely rent-burdened. The project he championed was enabled by targeted city subsidies — property tax exemptions, waived system development charges, and a $1/year 99-year lease of city land — and as mayor he has touted electronic permitting modernization and lists housing among the council''s three key goals (May 2026 Mayor''s Corner). This matches the targeted-subsidies-plus-easier-permits chair, not rent caps/public housing or deregulation-only approaches.', ARRAY['https://valleytimes.news/2023/11/09/tigard-opens-first-low-income-housing-complex-for-seniors/', 'https://tigardlife.com/local-news/yi-kang-hu-2/', 'https://tigardlife.com/local-news/mayors-corner-may-2026/']::text[]),
    ('homelessness-response', 3, 'Hu''s documented approach pairs services investment with enforcement of public-space rules: at the Aug 26, 2025 council meeting he cited Tigard''s "significant resources" — affordable housing, policing, a safe parking lot, a shelter, and sanctioned camping space — while pushing Tualatin and Sherwood to "step up" via a county-facilitated regional dialogue. As mayor he backed the April 21, 2026 emergency ordinance tightening rules on camping materials on public property ("This is not about punishment. This is about having clear rules that can be applied consistently"), and in his May 2026 Mayor''s Corner described the strategy as "manage impacts through reasonable rules and a centralized location, while continuing to work with community partners to connect people with available services." That is precisely the outreach/shelter/services-plus-reasonable-rules chair.', ARRAY['https://tigardlife.com/featured/as-homelessness-surges-tigard-revisits-regulations-questions-equity-of-shared-response/', 'https://valleytimes.news/2026/04/24/tigard-tightens-ban-on-keeping-camping-materials-on-city-property/', 'https://tigardlife.com/local-news/mayors-corner-may-2026/']::text[]),
    ('homelessness', 3, 'On public camping specifically, Hu supports enforcement conditioned on the city maintaining alternatives: Tigard keeps a sanctioned public campsite at Public Works, a shelter, and a safe lot (which Hu enumerated Aug 26, 2025), while restricting camping elsewhere and — under the April 21, 2026 ordinance he supported — barring daytime storage of camping materials on sidewalks, framed as keeping sidewalks "passable for everyone including people with disabilities" and explicitly "not about punishment." Outreach staff helped campers rather than routing them to criminal justice, and Hu emphasizes connecting people to services through community partners (May 2026). This best fits enforcement-paired-with-available-shelter-and-service-diversion rather than blanket criminal bans or a right-to-camp position.', ARRAY['https://valleytimes.news/2026/04/24/tigard-tightens-ban-on-keeping-camping-materials-on-city-property/', 'https://tigardlife.com/featured/as-homelessness-surges-tigard-revisits-regulations-questions-equity-of-shared-response/', 'https://tigardlife.com/local-news/mayors-corner-may-2026/']::text[]),
    ('public-safety-approach', 4, 'Hu has made expanding police capacity a signature mayoral initiative: he championed the public safety facility bond (Measure 34-349) that council referred to voters on Feb 17, 2026, writing in Mayor''s Corner columns that the 1980s police building designed for 25 officers now serves 70+ officers plus 16 staff, that the city wastes nearly $1 million/year maintaining aging facilities, and asking voters to accept roughly $13.60/month in added property tax over ~30 years for a modern integrated police/public works/emergency operations facility. "Public safety and stability" is one of his stated top priorities, and community safety was a plank of his 2022 platform. His documented record is about growing police facilities, capacity, and resilience — not reallocating police funding — though there is no evidence he wants police spending to trump all other services.', ARRAY['https://tigardlife.com/local-news/mayors-corner-investing-in-tigards-future-safety-and-resilience/', 'https://tigardlife.com/local-news/mayors-corner-may-2026/', 'https://www.kgw.com/article/news/politics/tigard-city-council-appoints-mayor-yi-kang-hu/283-3c320b4a-25ce-4438-94f6-5e13634440ab']::text[]),
    ('transportation-priorities', 2, 'Hu says he joined the Tigard Planning Commission and Transportation Advisory Committee ~2015 specifically "to advocate for safer streets and more sidewalks in our community," and his 2022 council platform was "centered on improved street and pedestrian accessibility." As mayor (Jan 2026 Mayor''s Corner) he highlighted safety upgrades near major roads and schools and expanded Fanno Creek Trail connections for walkers and cyclists, and in April 2026 stressed keeping sidewalks passable for people with disabilities, families, and seniors as "a basic function of the city government." His record balances road safety investment with strong pedestrian/multimodal advocacy rather than a transit-first, parking-reduction agenda or a roads-only stance.', ARRAY['https://tigardlife.com/local-news/yi-kang-hu-2/', 'https://tigardlife.com/local-news/mayors-corner-january-2026/', 'https://valleytimes.news/2026/04/24/tigard-tightens-ban-on-keeping-camping-materials-on-city-property/']::text[]),
    ('growth-and-development', 3, 'Hu''s documented posture is proactive infrastructure planning ahead of growth: in his May 2026 Mayor''s Corner he cautioned that "delaying critical infrastructure comes with real costs" and that construction costs rise over time, and his January 2026 column touted completing the Reservoir 18 water-system project, shaping the River Terrace 2.0 expansion (~4,500 homes on 500 annexed acres) through community input, and modernizing electronic permitting. He spent ~7 years on the Planning Commission (as president) guiding Tigard''s growth planning before joining council in Jan 2023. This matches planning proactively and investing in infrastructure to support responsible expansion, not growth caps or wholesale deregulation.', ARRAY['https://tigardlife.com/local-news/mayors-corner-may-2026/', 'https://tigardlife.com/local-news/mayors-corner-january-2026/', 'https://businesstribune.online/2024/07/15/tigard-moves-forward-with-river-terrace-2-0-planning-creating-possibility-of-4500-new-homes/']::text[]),
    ('economic-development', 3, '"Supporting local businesses" is one of Hu''s stated top mayoral priorities, and his January 2026 Mayor''s Corner credits the city with strengthening "small and family-run shops through business-support programs." At the same time he serves on the Town Center Advisory Commission and the Urban Renewal Funding Selection Subcommittee, the bodies that direct Tigard''s tax-increment-financing incentives to targeted downtown/Triangle redevelopment, and economic development was a plank of his 2022 platform. His record combines small-business programs with targeted, place-based incentives rather than either rejecting incentives outright or courting large employers with maximum abatements.', ARRAY['https://tigardlife.com/local-news/mayors-corner-january-2026/', 'https://www.kgw.com/article/news/politics/tigard-city-council-appoints-mayor-yi-kang-hu/283-3c320b4a-25ce-4438-94f6-5e13634440ab', 'https://tigardlife.com/local-news/yi-kang-hu-2/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '6701cd53-e7fb-491c-9b45-d0474705349e'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = '6701cd53-e7fb-491c-9b45-d0474705349e';
  IF v_ext IS DISTINCT FROM -4173651 THEN
    RAISE EXCEPTION 'UUID 6701cd53-e7fb-491c-9b45-d0474705349e does not belong to external_id -4173651 (Yi-Kang Hu) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = '6701cd53-e7fb-491c-9b45-d0474705349e';
  IF n <> 7 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 7, n;
  END IF;
  -- Context-parity gate (WR-03): the context VALUES list is a verbatim
  -- duplicate of the answers list; count it too so a single-sided edit
  -- cannot silently drop or skew reasoning/sources rows.
  SELECT COUNT(*) INTO n FROM inform.politician_context WHERE politician_id = '6701cd53-e7fb-491c-9b45-d0474705349e';
  IF n <> 7 THEN
    RAISE EXCEPTION 'Expected % context rows, found % — answers/context VALUES lists diverged', 7, n;
  END IF;
END $$;

COMMIT;
