-- Migration 1162: Tom Anderson (Councilor, Tigard OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 4 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).
-- Anderson was APPOINTED interim Dec 2025 and will NOT run in Nov 2026 — very thin record; honest blanks expected.

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('public-safety-approach', 4, 'At his Dec 2025 appointment Anderson made passage of the May 2026 $150M police/public works facility bond his "No. 1 funding priority," and in Feb 2026 he said of the new police facility: "It''s long overdue. You know, we have to address the current inadequacy. We can''t sustain what we''re doing here. It''s not a luxury; it''s a necessity." This continues a documented first-party position from his Sept 2022 candidacy, when he called the current police headquarters "extremely outdated and just plain inadequate for our officers and staff." His record supports significantly increased capital investment in police facilities/equipment (chair 4); there is no evidence he supports crisis-response reallocation (chair 3) or budget reduction. Note the bond is facility investment, not staffing/pay per se, and voters rejected it May 19, 2026.', ARRAY['https://tigardlife.com/featured/tigard-city-council-taps-former-member-to-fill-vacancy-for-2026/', 'https://tigardlife.com/featured/modern-campus-modest-cost-tigard-refines-pitch-for-may-150-million-bond-measure/', 'https://tigardlife.com/local-news/tom-anderson-2/']::text[]),
    ('homelessness-response', 4, 'At his Dec 2025 appointment Anderson named "worsening homelessness, particularly visible in downtown Tigard" as a top 2026 issue. On April 21, 2026 he was part of the council''s unanimous emergency vote tightening Tigard''s camping rules to prohibit keeping camping materials on any city public property or right-of-way (including at the sole sanctioned campsite), with no new services or shelter components in the ordinance; the city maintains basic outreach (a city/county homeless liaison and street outreach). His documented record — enforcement-tightening votes plus problem-framing of visible downtown homelessness, with no documented advocacy for expanded services — best matches enforcing anti-camping ordinances as the primary tool while maintaining basic outreach. Caveat: the vote was unanimous across the council, so it distinguishes him from chairs 1-2 more strongly than from chair 3.', ARRAY['https://youroregonnews.com/2026/04/24/tigard-tightens-ban-on-keeping-camping-materials-on-city-property/', 'https://tigardlife.com/featured/tigard-city-council-taps-former-member-to-fill-vacancy-for-2026/']::text[]),
    ('homelessness', 4, 'Anderson''s only documented 2026 action on public camping is his April 21, 2026 vote (unanimous council, emergency ordinance) prohibiting keeping camping materials on all Tigard public property, layered on Tigard''s time/place/manner regime that bans encampments outside narrow hours/locations while the city maintains a sanctioned camping green space and outreach liaison. That is a direct match for prohibiting encampments on public property with escalating restrictions while the jurisdiction maintains basic sheltering options (chair 4). He framed homelessness at his Dec 2025 appointment as a worsening, visible downtown problem to be addressed.', ARRAY['https://youroregonnews.com/2026/04/24/tigard-tightens-ban-on-keeping-camping-materials-on-city-property/', 'https://tigardlife.com/featured/tigard-city-council-taps-former-member-to-fill-vacancy-for-2026/']::text[]),
    ('housing', 3, 'In his Sept 21, 2022 council candidacy announcement (his most recent first-party platform, cited conservatively per attribution rules), Anderson listed affordable housing among his priorities and specifically supported extending price protections on affordable housing units whose affordability certifications were nearing expiration, to prevent conversion to market-rate rents. That is targeted government intervention to preserve subsidized affordable units — not citywide rent caps/public construction (chairs 1-2) and not deregulation-only (chairs 4-5). A real-estate broker described by colleagues as bringing a pro-business development perspective, his documented position best matches targeted help for affordable projects (chair 3).', ARRAY['https://tigardlife.com/local-news/tom-anderson-2/', 'https://tigardlife.com/featured/tigard-city-council-taps-former-member-to-fill-vacancy-for-2026/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT 'af1382e1-7b67-4729-8d6c-ec1bab0625bd'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('public-safety-approach', 4, 'At his Dec 2025 appointment Anderson made passage of the May 2026 $150M police/public works facility bond his "No. 1 funding priority," and in Feb 2026 he said of the new police facility: "It''s long overdue. You know, we have to address the current inadequacy. We can''t sustain what we''re doing here. It''s not a luxury; it''s a necessity." This continues a documented first-party position from his Sept 2022 candidacy, when he called the current police headquarters "extremely outdated and just plain inadequate for our officers and staff." His record supports significantly increased capital investment in police facilities/equipment (chair 4); there is no evidence he supports crisis-response reallocation (chair 3) or budget reduction. Note the bond is facility investment, not staffing/pay per se, and voters rejected it May 19, 2026.', ARRAY['https://tigardlife.com/featured/tigard-city-council-taps-former-member-to-fill-vacancy-for-2026/', 'https://tigardlife.com/featured/modern-campus-modest-cost-tigard-refines-pitch-for-may-150-million-bond-measure/', 'https://tigardlife.com/local-news/tom-anderson-2/']::text[]),
    ('homelessness-response', 4, 'At his Dec 2025 appointment Anderson named "worsening homelessness, particularly visible in downtown Tigard" as a top 2026 issue. On April 21, 2026 he was part of the council''s unanimous emergency vote tightening Tigard''s camping rules to prohibit keeping camping materials on any city public property or right-of-way (including at the sole sanctioned campsite), with no new services or shelter components in the ordinance; the city maintains basic outreach (a city/county homeless liaison and street outreach). His documented record — enforcement-tightening votes plus problem-framing of visible downtown homelessness, with no documented advocacy for expanded services — best matches enforcing anti-camping ordinances as the primary tool while maintaining basic outreach. Caveat: the vote was unanimous across the council, so it distinguishes him from chairs 1-2 more strongly than from chair 3.', ARRAY['https://youroregonnews.com/2026/04/24/tigard-tightens-ban-on-keeping-camping-materials-on-city-property/', 'https://tigardlife.com/featured/tigard-city-council-taps-former-member-to-fill-vacancy-for-2026/']::text[]),
    ('homelessness', 4, 'Anderson''s only documented 2026 action on public camping is his April 21, 2026 vote (unanimous council, emergency ordinance) prohibiting keeping camping materials on all Tigard public property, layered on Tigard''s time/place/manner regime that bans encampments outside narrow hours/locations while the city maintains a sanctioned camping green space and outreach liaison. That is a direct match for prohibiting encampments on public property with escalating restrictions while the jurisdiction maintains basic sheltering options (chair 4). He framed homelessness at his Dec 2025 appointment as a worsening, visible downtown problem to be addressed.', ARRAY['https://youroregonnews.com/2026/04/24/tigard-tightens-ban-on-keeping-camping-materials-on-city-property/', 'https://tigardlife.com/featured/tigard-city-council-taps-former-member-to-fill-vacancy-for-2026/']::text[]),
    ('housing', 3, 'In his Sept 21, 2022 council candidacy announcement (his most recent first-party platform, cited conservatively per attribution rules), Anderson listed affordable housing among his priorities and specifically supported extending price protections on affordable housing units whose affordability certifications were nearing expiration, to prevent conversion to market-rate rents. That is targeted government intervention to preserve subsidized affordable units — not citywide rent caps/public construction (chairs 1-2) and not deregulation-only (chairs 4-5). A real-estate broker described by colleagues as bringing a pro-business development perspective, his documented position best matches targeted help for affordable projects (chair 3).', ARRAY['https://tigardlife.com/local-news/tom-anderson-2/', 'https://tigardlife.com/featured/tigard-city-council-taps-former-member-to-fill-vacancy-for-2026/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT 'af1382e1-7b67-4729-8d6c-ec1bab0625bd'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
BEGIN
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = 'af1382e1-7b67-4729-8d6c-ec1bab0625bd';
  IF n <> 4 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 4, n;
  END IF;
END $$;

COMMIT;
