-- Migration 1163: Faraz Ghoddusi (Councilor, Tigard OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 7 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('public-safety-approach', 3, 'His #1 2024 campaign priority was public safety via community policing: "Safety is the foundation of everything we want to achieve," with officers "equipped with training in de-escalation and mental health crisis intervention" and a pledge to "expand mental health co-response units to address non-violent situations" (tigardlife candidate profile, Oct 2024). In the Oct 2024 candidate Q&A he called safety "paramount but requires a holistic approach that includes supporting local law enforcement and creating an infrastructure to bolster county mental health services," and he was "absolutely supportive" of the new Tigard Police Department building on Hunziker Street. This matches keeping current public safety funding/support for police while adding mental-health crisis response capacity — not shifting funds away from police (chair 1-2) and not making police expansion the top budget priority (chair 4-5).', ARRAY['https://tigardlife.com/local-news/faraz-ghoddusi-2/', 'https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more']::text[]),
    ('homelessness-response', 3, 'In his 2024 campaign he pledged "taking meaningful steps to help our houseless population, moving beyond short-term fixes to create long-term solutions" addressing root causes, paired with expanded mental health co-response and support services (tigardlife profile). In the Oct 2024 Q&A he proposed "expanding housing options and collaborating with programs to extend support services" focused on "both immediate assistance and long-term solutions," noting "the houseless population is typically migratory, so housing issues cannot be confined to the city boundary" — while simultaneously "supporting local law enforcement." This services-plus-outreach approach alongside support for police best matches investing in outreach, shelter, and mental health services while maintaining reasonable public-space rules; he has not advocated enforcement-first (4-5) or no-preconditions housing-first/anti-enforcement (1).', ARRAY['https://tigardlife.com/local-news/faraz-ghoddusi-2/', 'https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more']::text[]),
    ('housing', 3, 'In the Oct 2024 candidate Q&A he said "while the city has taken steps to address houselessness and affordable housing, I think there''s still more that can be done," proposing "policies that increase the availability of affordable housing using sustainable methods" and helping residents "find routes to home ownership." His campaign priorities page states "the expansion of affordable housing must be meticulously planned and integrated into a walkable community." Targeted government facilitation of affordable projects plus first-time ownership pathways matches chair 3; he has not called for rent caps/public funding mandates (2) or broad deregulation (4).', ARRAY['https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more', 'https://www.ghoddusi.org/services-2']::text[]),
    ('growth-and-development', 3, 'His platform is explicitly "sustainable growth": affordable-housing expansion "must be meticulously planned and integrated into a walkable community" (ghoddusi.org priorities), and his 10-year vision is Tigard "modeling a blend of sustainable growth and community well-being" (Oct 2024 Q&A). He strongly supported the new Public Works facility ("a modernized Public Works facility will provide our public servants with up-to-date resources"), i.e., city infrastructure investment to serve growth, and favors "encouraging sustainable development." Planned, proactive growth with infrastructure investment matches chair 3 — neither growth caps (1-2) nor deregulated recruitment of development (4-5).', ARRAY['https://www.ghoddusi.org/services-2', 'https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more']::text[]),
    ('economic-development', 2, 'In the Oct 2024 Q&A his economic platform centered on small business: "expanding support for small businesses and entrepreneurs. By reducing barriers for first-time business owners and encouraging sustainable development, we can create jobs," and "the city''s continued support for local businesses is pivotal, and I will advocate for continuing to reduce barriers to business growth." His priorities page commits to "expanding these programs and attracting more businesses to our city" but never proposes tax abatements or corporate incentive packages. Small-business and entrepreneur support as the primary tool matches chair 2; caveat that he does want to attract more businesses generally, just without any documented incentive/subsidy component.', ARRAY['https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more', 'https://www.ghoddusi.org/services-2']::text[]),
    ('local-environment', 3, 'His campaign environment priority: "Continue to maintain our green space, while promoting sustainable growth in Tigard," including "incentives to reduce waste" (ghoddusi.org priorities, 2024). He also frames affordable-housing expansion as needing "convenient access to green spaces." This is an explicit balance — maintain green space while still enabling development — matching consistent environmental standards with reasonable flexibility (chair 3), not strict preservation mandates before any development (1-2) or removal of local environmental rules (4-5).', ARRAY['https://www.ghoddusi.org/services-2', 'https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more']::text[]),
    ('transportation-priorities', 2, 'His 2024 platform pairs "investment in public transportation" with sustainable growth (ghoddusi.org priorities) and insists housing expansion be "integrated into a walkable community that provides secure streets" — affirmative multimodal/walkability investment with no anti-road framing. That best matches investing in multimodal options alongside roads (chair 2) rather than transit-first with reduced parking (1) or roads-first (4-5). Caveat: evidence is a platform statement, not a specific project vote; the "require bike lanes on all new road projects" clause of the chair is not documented.', ARRAY['https://www.ghoddusi.org/services-2']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '53570d0d-30c7-4bd3-8a0e-ac0865d2b15a'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('public-safety-approach', 3, 'His #1 2024 campaign priority was public safety via community policing: "Safety is the foundation of everything we want to achieve," with officers "equipped with training in de-escalation and mental health crisis intervention" and a pledge to "expand mental health co-response units to address non-violent situations" (tigardlife candidate profile, Oct 2024). In the Oct 2024 candidate Q&A he called safety "paramount but requires a holistic approach that includes supporting local law enforcement and creating an infrastructure to bolster county mental health services," and he was "absolutely supportive" of the new Tigard Police Department building on Hunziker Street. This matches keeping current public safety funding/support for police while adding mental-health crisis response capacity — not shifting funds away from police (chair 1-2) and not making police expansion the top budget priority (chair 4-5).', ARRAY['https://tigardlife.com/local-news/faraz-ghoddusi-2/', 'https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more']::text[]),
    ('homelessness-response', 3, 'In his 2024 campaign he pledged "taking meaningful steps to help our houseless population, moving beyond short-term fixes to create long-term solutions" addressing root causes, paired with expanded mental health co-response and support services (tigardlife profile). In the Oct 2024 Q&A he proposed "expanding housing options and collaborating with programs to extend support services" focused on "both immediate assistance and long-term solutions," noting "the houseless population is typically migratory, so housing issues cannot be confined to the city boundary" — while simultaneously "supporting local law enforcement." This services-plus-outreach approach alongside support for police best matches investing in outreach, shelter, and mental health services while maintaining reasonable public-space rules; he has not advocated enforcement-first (4-5) or no-preconditions housing-first/anti-enforcement (1).', ARRAY['https://tigardlife.com/local-news/faraz-ghoddusi-2/', 'https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more']::text[]),
    ('housing', 3, 'In the Oct 2024 candidate Q&A he said "while the city has taken steps to address houselessness and affordable housing, I think there''s still more that can be done," proposing "policies that increase the availability of affordable housing using sustainable methods" and helping residents "find routes to home ownership." His campaign priorities page states "the expansion of affordable housing must be meticulously planned and integrated into a walkable community." Targeted government facilitation of affordable projects plus first-time ownership pathways matches chair 3; he has not called for rent caps/public funding mandates (2) or broad deregulation (4).', ARRAY['https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more', 'https://www.ghoddusi.org/services-2']::text[]),
    ('growth-and-development', 3, 'His platform is explicitly "sustainable growth": affordable-housing expansion "must be meticulously planned and integrated into a walkable community" (ghoddusi.org priorities), and his 10-year vision is Tigard "modeling a blend of sustainable growth and community well-being" (Oct 2024 Q&A). He strongly supported the new Public Works facility ("a modernized Public Works facility will provide our public servants with up-to-date resources"), i.e., city infrastructure investment to serve growth, and favors "encouraging sustainable development." Planned, proactive growth with infrastructure investment matches chair 3 — neither growth caps (1-2) nor deregulated recruitment of development (4-5).', ARRAY['https://www.ghoddusi.org/services-2', 'https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more']::text[]),
    ('economic-development', 2, 'In the Oct 2024 Q&A his economic platform centered on small business: "expanding support for small businesses and entrepreneurs. By reducing barriers for first-time business owners and encouraging sustainable development, we can create jobs," and "the city''s continued support for local businesses is pivotal, and I will advocate for continuing to reduce barriers to business growth." His priorities page commits to "expanding these programs and attracting more businesses to our city" but never proposes tax abatements or corporate incentive packages. Small-business and entrepreneur support as the primary tool matches chair 2; caveat that he does want to attract more businesses generally, just without any documented incentive/subsidy component.', ARRAY['https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more', 'https://www.ghoddusi.org/services-2']::text[]),
    ('local-environment', 3, 'His campaign environment priority: "Continue to maintain our green space, while promoting sustainable growth in Tigard," including "incentives to reduce waste" (ghoddusi.org priorities, 2024). He also frames affordable-housing expansion as needing "convenient access to green spaces." This is an explicit balance — maintain green space while still enabling development — matching consistent environmental standards with reasonable flexibility (chair 3), not strict preservation mandates before any development (1-2) or removal of local environmental rules (4-5).', ARRAY['https://www.ghoddusi.org/services-2', 'https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more']::text[]),
    ('transportation-priorities', 2, 'His 2024 platform pairs "investment in public transportation" with sustainable growth (ghoddusi.org priorities) and insists housing expansion be "integrated into a walkable community that provides secure streets" — affirmative multimodal/walkability investment with no anti-road framing. That best matches investing in multimodal options alongside roads (chair 2) rather than transit-first with reduced parking (1) or roads-first (4-5). Caveat: evidence is a platform statement, not a specific project vote; the "require bike lanes on all new road projects" clause of the chair is not documented.', ARRAY['https://www.ghoddusi.org/services-2']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '53570d0d-30c7-4bd3-8a0e-ac0865d2b15a'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = '53570d0d-30c7-4bd3-8a0e-ac0865d2b15a';
  IF v_ext IS DISTINCT FROM -4173653 THEN
    RAISE EXCEPTION 'UUID 53570d0d-30c7-4bd3-8a0e-ac0865d2b15a does not belong to external_id -4173653 (Faraz Ghoddusi) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = '53570d0d-30c7-4bd3-8a0e-ac0865d2b15a';
  IF n <> 7 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 7, n;
  END IF;
END $$;

COMMIT;
