-- Migration 1164: Heather Robbins (Councilor, Tigard OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 6 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('public-safety-approach', 3, 'Robbins''s stated #1 priority in her 2024 campaign was public safety via a health-oriented response to the opioid/fentanyl crisis: making naloxone (Narcan) "readily available in our public schools and public buildings," partnering with local businesses to stock naloxone and train employees, and community education with take-home naloxone kits — an addiction/health-response layer added to existing public safety services rather than a call to expand or cut police budgets. She was endorsed by the Tigard Police Officers'' Association and supported the new Public Works and Police facility as "a critical need for a very long time," indicating she wants to keep police funding and facilities solid while adding addiction-crisis responses. This best matches keeping current public safety funding while adding response capacity for addiction/health calls.', ARRAY['https://tigardlife.com/local-news/heather-robbins-2/', 'https://heatherrobbins.org/priorities/', 'https://heatherrobbins.org/endorsements/']::text[]),
    ('homelessness-response', 3, 'Her campaign priority page commits to continuing "Council''s work to reduce houselessness, protect property values, and implement effective, cost-conscious solutions." In an October 2024 Q&A she praised Tigard''s balance — leaders "listened, reevaluated, and adjusted the rules to protect our library patrons while still offering a safe camping space at our public works building" — and said Tigard is "ahead of most cities with our wide variety of support services." In office (Oct 28, 2025 council discussion), she supported tightening camping hours and clearing belongings ("People don''t feel safe walking by a huge mountain of belongings that''s on the sidewalk") while explicitly opposing a full ban on camping at the public works site, seeking "balance." That is investing in outreach/shelter/services while enforcing reasonable public-space rules.', ARRAY['https://heatherrobbins.org/priorities/', 'https://youroregonnews.com/2025/11/03/tigard-council-considers-tightening-hours-allowed-for-camping-on-city-property/', 'https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more']::text[]),
    ('homelessness', 3, 'On the specific question of camping in public spaces, Robbins supports Tigard''s time-place-manner model: camping is restricted on public property but the city maintains a sanctioned safe camping space at the Public Works building with trash service and street outreach. In the Oct 28, 2025 council discussion she said she "didn''t want to ban camping at the public works building" but also didn''t want Tigard to become "a more comfortable place to camp" via expansive hours; the council subsequently adopted the tightened ordinance (camping 7 p.m.-8 a.m., expanded clearance) on Dec 16, 2025. Enforcement paired with a maintained sanctioned option and service connections, rather than criminalization or a right to camp anywhere, matches this chair.', ARRAY['https://youroregonnews.com/2025/11/03/tigard-council-considers-tightening-hours-allowed-for-camping-on-city-property/', 'https://valleytimes.news/2025/12/18/tigard-overnight-camping-reduced-by-one-hour-each-day-camper-clearance-expanded/']::text[]),
    ('housing', 3, 'In an October 2024 candidate Q&A, Robbins said "Tigard is doing a good job in addressing homeless and affordable housing issues," citing roughly 600 affordable units built over six years and the council "streamlining zoning rules to allow ADUs to be built fairly easily" — i.e., targeted affordable-housing production plus permitting/zoning ease rather than rent caps or a purely market approach. Her campaign profile says residents "deserve access to affordable housing in a clean environment." She endorses targeted government help (affordable projects, easier building rules) within a mostly private market.', ARRAY['https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more', 'https://goodlicious.co/heather-robbins-for-tigard-city-council/']::text[]),
    ('residential-zoning', 2, 'Robbins specifically praised Tigard''s "streamlining zoning rules to allow ADUs to be built fairly easily" as an affordability tool in her October 2024 candidate Q&A — endorsing modest, incremental density like accessory dwelling units. At the same time her platform commits to "protect property values" and she has not advocated broad upzoning or eliminating single-family zoning. Modest density increases with attention to existing neighborhoods is the best fit.', ARRAY['https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more', 'https://heatherrobbins.org/priorities/']::text[]),
    ('transportation-priorities', 3, 'Her campaign priorities call for "comprehensive traffic solutions, including infrastructure upgrades and multimodal facility improvements on Hall Blvd and our city streets," and in the October 2024 Q&A she emphasized maintaining streets and sidewalks while staying "open to new and creative ideas on infrastructure and transportation." Her profile also cites "safe roads, walkable neighborhoods" as things residents deserve. The pattern is road maintenance and traffic flow first, with targeted multimodal/pedestrian improvements on key corridors like Hall Blvd — matching selective multimodal additions on a maintained road network.', ARRAY['https://heatherrobbins.org/priorities/', 'https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more', 'https://goodlicious.co/heather-robbins-for-tigard-city-council/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '18896554-4b57-42ee-82b8-9549878959b5'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('public-safety-approach', 3, 'Robbins''s stated #1 priority in her 2024 campaign was public safety via a health-oriented response to the opioid/fentanyl crisis: making naloxone (Narcan) "readily available in our public schools and public buildings," partnering with local businesses to stock naloxone and train employees, and community education with take-home naloxone kits — an addiction/health-response layer added to existing public safety services rather than a call to expand or cut police budgets. She was endorsed by the Tigard Police Officers'' Association and supported the new Public Works and Police facility as "a critical need for a very long time," indicating she wants to keep police funding and facilities solid while adding addiction-crisis responses. This best matches keeping current public safety funding while adding response capacity for addiction/health calls.', ARRAY['https://tigardlife.com/local-news/heather-robbins-2/', 'https://heatherrobbins.org/priorities/', 'https://heatherrobbins.org/endorsements/']::text[]),
    ('homelessness-response', 3, 'Her campaign priority page commits to continuing "Council''s work to reduce houselessness, protect property values, and implement effective, cost-conscious solutions." In an October 2024 Q&A she praised Tigard''s balance — leaders "listened, reevaluated, and adjusted the rules to protect our library patrons while still offering a safe camping space at our public works building" — and said Tigard is "ahead of most cities with our wide variety of support services." In office (Oct 28, 2025 council discussion), she supported tightening camping hours and clearing belongings ("People don''t feel safe walking by a huge mountain of belongings that''s on the sidewalk") while explicitly opposing a full ban on camping at the public works site, seeking "balance." That is investing in outreach/shelter/services while enforcing reasonable public-space rules.', ARRAY['https://heatherrobbins.org/priorities/', 'https://youroregonnews.com/2025/11/03/tigard-council-considers-tightening-hours-allowed-for-camping-on-city-property/', 'https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more']::text[]),
    ('homelessness', 3, 'On the specific question of camping in public spaces, Robbins supports Tigard''s time-place-manner model: camping is restricted on public property but the city maintains a sanctioned safe camping space at the Public Works building with trash service and street outreach. In the Oct 28, 2025 council discussion she said she "didn''t want to ban camping at the public works building" but also didn''t want Tigard to become "a more comfortable place to camp" via expansive hours; the council subsequently adopted the tightened ordinance (camping 7 p.m.-8 a.m., expanded clearance) on Dec 16, 2025. Enforcement paired with a maintained sanctioned option and service connections, rather than criminalization or a right to camp anywhere, matches this chair.', ARRAY['https://youroregonnews.com/2025/11/03/tigard-council-considers-tightening-hours-allowed-for-camping-on-city-property/', 'https://valleytimes.news/2025/12/18/tigard-overnight-camping-reduced-by-one-hour-each-day-camper-clearance-expanded/']::text[]),
    ('housing', 3, 'In an October 2024 candidate Q&A, Robbins said "Tigard is doing a good job in addressing homeless and affordable housing issues," citing roughly 600 affordable units built over six years and the council "streamlining zoning rules to allow ADUs to be built fairly easily" — i.e., targeted affordable-housing production plus permitting/zoning ease rather than rent caps or a purely market approach. Her campaign profile says residents "deserve access to affordable housing in a clean environment." She endorses targeted government help (affordable projects, easier building rules) within a mostly private market.', ARRAY['https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more', 'https://goodlicious.co/heather-robbins-for-tigard-city-council/']::text[]),
    ('residential-zoning', 2, 'Robbins specifically praised Tigard''s "streamlining zoning rules to allow ADUs to be built fairly easily" as an affordability tool in her October 2024 candidate Q&A — endorsing modest, incremental density like accessory dwelling units. At the same time her platform commits to "protect property values" and she has not advocated broad upzoning or eliminating single-family zoning. Modest density increases with attention to existing neighborhoods is the best fit.', ARRAY['https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more', 'https://heatherrobbins.org/priorities/']::text[]),
    ('transportation-priorities', 3, 'Her campaign priorities call for "comprehensive traffic solutions, including infrastructure upgrades and multimodal facility improvements on Hall Blvd and our city streets," and in the October 2024 Q&A she emphasized maintaining streets and sidewalks while staying "open to new and creative ideas on infrastructure and transportation." Her profile also cites "safe roads, walkable neighborhoods" as things residents deserve. The pattern is road maintenance and traffic flow first, with targeted multimodal/pedestrian improvements on key corridors like Hall Blvd — matching selective multimodal additions on a maintained road network.', ARRAY['https://heatherrobbins.org/priorities/', 'https://www.newsbreak.com/news/3632693847088-candidate-q-a-tigard-council-2-year-candidates-talk-housing-economics-and-more', 'https://goodlicious.co/heather-robbins-for-tigard-city-council/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '18896554-4b57-42ee-82b8-9549878959b5'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = '18896554-4b57-42ee-82b8-9549878959b5';
  IF v_ext IS DISTINCT FROM -4173654 THEN
    RAISE EXCEPTION 'UUID 18896554-4b57-42ee-82b8-9549878959b5 does not belong to external_id -4173654 (Heather Robbins) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = '18896554-4b57-42ee-82b8-9549878959b5';
  IF n <> 6 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 6, n;
  END IF;
END $$;

COMMIT;
