-- Migration 1165: Jake Schlack (Councilor, Tigard OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 6 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'In his 2024 Tigard Life candidate profile, Schlack named addressing housing needs his #1 priority, citing Tigard''s 2023 Community Survey (only 26% rated affordable housing availability good/excellent) and that 28% of renter households are severely rent burdened. His stated approach is to "advocate for diverse housing options across all income levels," partner with businesses, governments, and nonprofits to develop affordable housing, build supporting infrastructure, and prevent displacement — a targeted partnership/subsidy approach rather than rent caps or direct public housing construction.', ARRAY['https://tigardlife.com/local-news/jake-schlack-2/']::text[]),
    ('growth-and-development', 3, 'Schlack''s 2024 candidate platform paired his housing-growth priority with commitments to "build supporting infrastructure," prevent displacement, and "implement proactive planning for parking capacity and multimodal transportation." As a Town Center Development Agency director he voted (unanimous, May 27, 2025) for the $12M Regal Cinema land purchase to guide Triangle redevelopment ahead of ~1,000 pipeline housing units, calling it "a landmark project for the Tigard Triangle." This matches proactive planning and infrastructure investment ahead of growth.', ARRAY['https://tigardlife.com/local-news/jake-schlack-2/', 'https://tigardlife.com/featured/citys-12m-regal-cinema-land-purchase-aims-at-revitalizing-10-acres-in-the-triangle/']::text[]),
    ('homelessness-response', 3, 'Schlack supports Tigard''s services-plus-rules model: his candidate profile touts that he "voted to strengthen time, place, and manner restrictions" on camping after his July 2024 appointment, while at the October 28, 2025 council discussion he emphasized Tigard''s leadership in per-capita shelter beds and criticized regional partners for lagging on services and lacking long-term plans. His record combines maintaining/defending shelter and services investment with enforcing tightened public-space rules, matching the outreach-plus-reasonable-enforcement chair.', ARRAY['https://tigardlife.com/local-news/jake-schlack-2/', 'https://youroregonnews.com/2025/11/03/tigard-council-considers-tightening-hours-allowed-for-camping-on-city-property/']::text[]),
    ('homelessness', 4, 'Schlack has repeatedly backed tightening restrictions on public camping: he voted to strengthen time/place/manner camping restrictions (2024), and on the April 2026 emergency ordinance barring "camp materials" from city rights-of-way — enforceable by Class 3 civil infraction, citation, or trespass arrest — he said "Sometimes the compassionate thing to do is to take tough decisions proactively." At the same time Tigard maintains a designated overnight camping site and shelter capacity he touts as region-leading, matching the prohibit-encampments-with-graduated-penalties-while-maintaining-shelter chair.', ARRAY['https://tigardlife.com/local-news/city-cracks-down-on-camp-materials-in-city-rights-of-way/', 'https://tigardlife.com/local-news/jake-schlack-2/', 'https://youroregonnews.com/2025/11/03/tigard-council-considers-tightening-hours-allowed-for-camping-on-city-property/']::text[]),
    ('public-safety-approach', 4, 'Schlack is a leading public advocate for expanding Tigard''s public safety investment: he authored an April 24, 2026 op-ed urging a yes vote on Measure 34-349 (police/public works levy), calling it "the responsible thing to do," and championed the $150M public safety bond to build a combined police/public works facility, arguing "Now''s the time to fix us... for our needs as a community 40 to 50 years from now" and citing over $1M/year wasted on off-site storage and repairs. His platform lists "improving public safety" and "safe streets, secure neighborhoods" among top priorities.', ARRAY['https://youroregonnews.com/2026/04/24/opinion-supporting-tigard-police-public-works-levy-the-responsible-thing-to-do/', 'https://katu.com/news/local/tigard-voters-weigh-public-safety-bond-tigard-police-department-public-works-debate-over-cost-growth-efficiency-city-councilor-jake-schlack-former-city-manager-bill-monahan', 'https://tigardlife.com/local-news/jake-schlack-2/']::text[]),
    ('economic-development', 3, 'Schlack advances economic development through targeted, project-specific public investment with community benefits rather than broad corporate incentives: as TCDA director he voted for and championed the $12M Regal Cinema purchase (May 27, 2025) to catalyze Triangle redevelopment via public-private partnerships including a park, housing, and creek restoration, and his council record includes advancing Downtown Tigard redevelopment. He also reformed the city grant program "so your taxpayer dollars go toward efforts that best serve the community," reflecting a value-for-money, targeted-investment approach.', ARRAY['https://tigardlife.com/featured/citys-12m-regal-cinema-land-purchase-aims-at-revitalizing-10-acres-in-the-triangle/', 'https://tigardlife.com/local-news/jake-schlack-2/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT 'ffd6a403-6e6b-428d-8c8d-4a3557be339b'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'In his 2024 Tigard Life candidate profile, Schlack named addressing housing needs his #1 priority, citing Tigard''s 2023 Community Survey (only 26% rated affordable housing availability good/excellent) and that 28% of renter households are severely rent burdened. His stated approach is to "advocate for diverse housing options across all income levels," partner with businesses, governments, and nonprofits to develop affordable housing, build supporting infrastructure, and prevent displacement — a targeted partnership/subsidy approach rather than rent caps or direct public housing construction.', ARRAY['https://tigardlife.com/local-news/jake-schlack-2/']::text[]),
    ('growth-and-development', 3, 'Schlack''s 2024 candidate platform paired his housing-growth priority with commitments to "build supporting infrastructure," prevent displacement, and "implement proactive planning for parking capacity and multimodal transportation." As a Town Center Development Agency director he voted (unanimous, May 27, 2025) for the $12M Regal Cinema land purchase to guide Triangle redevelopment ahead of ~1,000 pipeline housing units, calling it "a landmark project for the Tigard Triangle." This matches proactive planning and infrastructure investment ahead of growth.', ARRAY['https://tigardlife.com/local-news/jake-schlack-2/', 'https://tigardlife.com/featured/citys-12m-regal-cinema-land-purchase-aims-at-revitalizing-10-acres-in-the-triangle/']::text[]),
    ('homelessness-response', 3, 'Schlack supports Tigard''s services-plus-rules model: his candidate profile touts that he "voted to strengthen time, place, and manner restrictions" on camping after his July 2024 appointment, while at the October 28, 2025 council discussion he emphasized Tigard''s leadership in per-capita shelter beds and criticized regional partners for lagging on services and lacking long-term plans. His record combines maintaining/defending shelter and services investment with enforcing tightened public-space rules, matching the outreach-plus-reasonable-enforcement chair.', ARRAY['https://tigardlife.com/local-news/jake-schlack-2/', 'https://youroregonnews.com/2025/11/03/tigard-council-considers-tightening-hours-allowed-for-camping-on-city-property/']::text[]),
    ('homelessness', 4, 'Schlack has repeatedly backed tightening restrictions on public camping: he voted to strengthen time/place/manner camping restrictions (2024), and on the April 2026 emergency ordinance barring "camp materials" from city rights-of-way — enforceable by Class 3 civil infraction, citation, or trespass arrest — he said "Sometimes the compassionate thing to do is to take tough decisions proactively." At the same time Tigard maintains a designated overnight camping site and shelter capacity he touts as region-leading, matching the prohibit-encampments-with-graduated-penalties-while-maintaining-shelter chair.', ARRAY['https://tigardlife.com/local-news/city-cracks-down-on-camp-materials-in-city-rights-of-way/', 'https://tigardlife.com/local-news/jake-schlack-2/', 'https://youroregonnews.com/2025/11/03/tigard-council-considers-tightening-hours-allowed-for-camping-on-city-property/']::text[]),
    ('public-safety-approach', 4, 'Schlack is a leading public advocate for expanding Tigard''s public safety investment: he authored an April 24, 2026 op-ed urging a yes vote on Measure 34-349 (police/public works levy), calling it "the responsible thing to do," and championed the $150M public safety bond to build a combined police/public works facility, arguing "Now''s the time to fix us... for our needs as a community 40 to 50 years from now" and citing over $1M/year wasted on off-site storage and repairs. His platform lists "improving public safety" and "safe streets, secure neighborhoods" among top priorities.', ARRAY['https://youroregonnews.com/2026/04/24/opinion-supporting-tigard-police-public-works-levy-the-responsible-thing-to-do/', 'https://katu.com/news/local/tigard-voters-weigh-public-safety-bond-tigard-police-department-public-works-debate-over-cost-growth-efficiency-city-councilor-jake-schlack-former-city-manager-bill-monahan', 'https://tigardlife.com/local-news/jake-schlack-2/']::text[]),
    ('economic-development', 3, 'Schlack advances economic development through targeted, project-specific public investment with community benefits rather than broad corporate incentives: as TCDA director he voted for and championed the $12M Regal Cinema purchase (May 27, 2025) to catalyze Triangle redevelopment via public-private partnerships including a park, housing, and creek restoration, and his council record includes advancing Downtown Tigard redevelopment. He also reformed the city grant program "so your taxpayer dollars go toward efforts that best serve the community," reflecting a value-for-money, targeted-investment approach.', ARRAY['https://tigardlife.com/featured/citys-12m-regal-cinema-land-purchase-aims-at-revitalizing-10-acres-in-the-triangle/', 'https://tigardlife.com/local-news/jake-schlack-2/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT 'ffd6a403-6e6b-428d-8c8d-4a3557be339b'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
BEGIN
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = 'ffd6a403-6e6b-428d-8c8d-4a3557be339b';
  IF n <> 6 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 6, n;
  END IF;
END $$;

COMMIT;
