-- Migration 1166: Jeanette Shaw (Councilor, Tigard OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 8 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Shaw''s 2024 platform pledges to "collaborate with housing developers, governments, and non-profits to continue developing diverse housing for all income levels," and her campaign achievements page credits the council with adding nearly 600 affordable homes over five years, a $1M city investment in the Family Promise hotel purchase (Bridge to Home transitional housing for 75 families), and tenant assistance preventing ~4,500 county-wide evictions. This is targeted subsidy/partnership work rather than rent caps or full public housing, matching the targeted-help chair. She was endorsed in 2024 by the Home Building Association of Greater Portland while also championing city-funded affordable projects.', ARRAY['https://www.shawfortigard.com/meet-jeanette', 'https://www.shawfortigard.com/achievements', 'https://tigardlife.com/local-news/jeanette-shaw-2-2/']::text[]),
    ('homelessness-response', 3, 'At the August 10, 2021 council meeting Shaw called on the city to reconvene its homelessness task force, and she served on the resulting CHART team alongside business, city, and currently-homeless members; the associated Washington County encampment program pairs street outreach and services with a scoring system that can lead to camp removal. Her 2024 platform commits to "continue to partner with Washington County to reduce homelessness," and her achievements tout the $1M Family Promise transitional-housing investment plus a library social service coordinator. This services-plus-reasonable-rules posture matches chair 3.', ARRAY['https://tigardlife.com/featured/encampments-program-will-either-help-or-remove-homeless-camps/', 'https://tigardlife.com/local-news/jeanette-shaw-2-2/', 'https://www.shawfortigard.com/achievements']::text[]),
    ('public-safety-approach', 3, 'Shaw championed the Public Safety Levy Renewal (passed with 78% approval in 2024) — a renewal preserving existing police funding — while her achievements list adds a downtown patrol officer, a Community Services Officer, specialized crisis intervention and de-escalation training for police, and a social service coordinator at the library for de-escalation. In her 2020 WashCo Dems interview she called police "vital" and praised Tigard''s chief for being "willing to reframe the approach to policing" with emphasis on training. Her 2024 platform''s lead priority is to "prioritize and modernize our Police and Public Works facilities and resources so they can perform their duties efficiently," and she was endorsed by the Tigard Police Officers'' Association — sustained funding plus crisis-response additions rather than either defunding or expansion-first.', ARRAY['https://www.shawfortigard.com/achievements', 'https://washcodems.org/2020/10/12/jeanette-shaw-tigard-city-council-candidate-interview/', 'https://tigardlife.com/local-news/jeanette-shaw-2-2/']::text[]),
    ('growth-and-development', 3, 'In her 2020 Tigard Life profile Shaw framed growth in the Tigard Triangle, Washington Square, and Downtown Tigard as an opportunity to "be at the forefront of community innovation" and called for "developing Tigard''s future growth through a comprehensive strategic plan." Her campaign bio describes engaging the community on River Terrace 2.0 planning (community plan phase through 2026), and her 2024 achievements emphasize infrastructure investment ahead of need — citywide software modernization, water billing systems, and purchasing property for new police and public works facilities. This proactive plan-and-invest posture matches chair 3.', ARRAY['https://tigardlife.com/local-news/jeanette-shaw/', 'https://www.shawfortigard.com/meet-jeanette', 'https://www.shawfortigard.com/achievements']::text[]),
    ('residential-zoning', 3, 'Shaw''s campaign bio says she is engaging the community on River Terrace 2.0 planning for "a multi-modal, multi-use community that increases housing density" with walkable access to shopping, and her platform calls for "diverse housing for all income levels" and housing choices "for all stages of life" (2020 profile). She supports added density and mixed uses in planned growth areas rather than either strict neighborhood-character protection or citywide elimination of single-family zoning, matching the corridor/planned-density chair.', ARRAY['https://www.shawfortigard.com/meet-jeanette', 'https://tigardlife.com/local-news/jeanette-shaw/']::text[]),
    ('transportation-priorities', 2, 'Shaw''s 2024 candidate profile commits to filling "sidewalk gaps, create additional Safe Routes to School programs" and expanding "bike lanes" and mobility options, and her achievements cite the Locust Street Safe Routes to School project plus a $2M state grant for two more school routes. At the same time she prioritizes road maintenance — securing the Hall Boulevard jurisdictional transfer "in good repair" and "reducing road congestion" — a both/and roads-plus-multimodal investment posture matching chair 2.', ARRAY['https://tigardlife.com/local-news/jeanette-shaw-2-2/', 'https://www.shawfortigard.com/achievements']::text[]),
    ('climate-change', 3, 'In her October 2020 WashCo Dems interview Shaw noted transportation is "40% of fossil fuel carbon emissions" and backed electrification, EV charging in the Tigard Triangle, and California-style EV adoption incentives; her professional work includes legislation for transportation electrification (electric school buses, medium/heavy-duty vehicles). Her 2024 platform supports budgets that invest in Tigard''s Climate Action Resiliency Plan, and her achievements include a heat pump cash incentive program, replacing gas-powered city vehicles, tree canopy expansion, and public EV charging at three sites. This is clean-energy investment with gradual transition, not a rapid fossil-fuel phase-out mandate — chair 3. She was endorsed by the Oregon League of Conservation Voters in 2024.', ARRAY['https://washcodems.org/2020/10/12/jeanette-shaw-tigard-city-council-candidate-interview/', 'https://www.shawfortigard.com/achievements', 'https://tigardlife.com/local-news/jeanette-shaw-2-2/']::text[]),
    ('economic-development', 2, 'Shaw''s documented economic development record centers on small business: she cites establishing the $250K Tigard Small Business Sustainability Fund with the Chamber of Commerce, pandemic relief for residents and businesses, and a 2024 platform for budgets that "strengthen and support our businesses, grows our workforce." No documented support for large corporate tax abatements or recruitment subsidies appears in her record; her stated approach matches the small-business/local-support chair. She was endorsed by the Tigard Chamber of Commerce in 2024.', ARRAY['https://www.shawfortigard.com/achievements', 'https://tigardlife.com/local-news/jeanette-shaw-2-2/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '9e4d8f47-e4d5-4652-8fda-8e19b33bedea'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Shaw''s 2024 platform pledges to "collaborate with housing developers, governments, and non-profits to continue developing diverse housing for all income levels," and her campaign achievements page credits the council with adding nearly 600 affordable homes over five years, a $1M city investment in the Family Promise hotel purchase (Bridge to Home transitional housing for 75 families), and tenant assistance preventing ~4,500 county-wide evictions. This is targeted subsidy/partnership work rather than rent caps or full public housing, matching the targeted-help chair. She was endorsed in 2024 by the Home Building Association of Greater Portland while also championing city-funded affordable projects.', ARRAY['https://www.shawfortigard.com/meet-jeanette', 'https://www.shawfortigard.com/achievements', 'https://tigardlife.com/local-news/jeanette-shaw-2-2/']::text[]),
    ('homelessness-response', 3, 'At the August 10, 2021 council meeting Shaw called on the city to reconvene its homelessness task force, and she served on the resulting CHART team alongside business, city, and currently-homeless members; the associated Washington County encampment program pairs street outreach and services with a scoring system that can lead to camp removal. Her 2024 platform commits to "continue to partner with Washington County to reduce homelessness," and her achievements tout the $1M Family Promise transitional-housing investment plus a library social service coordinator. This services-plus-reasonable-rules posture matches chair 3.', ARRAY['https://tigardlife.com/featured/encampments-program-will-either-help-or-remove-homeless-camps/', 'https://tigardlife.com/local-news/jeanette-shaw-2-2/', 'https://www.shawfortigard.com/achievements']::text[]),
    ('public-safety-approach', 3, 'Shaw championed the Public Safety Levy Renewal (passed with 78% approval in 2024) — a renewal preserving existing police funding — while her achievements list adds a downtown patrol officer, a Community Services Officer, specialized crisis intervention and de-escalation training for police, and a social service coordinator at the library for de-escalation. In her 2020 WashCo Dems interview she called police "vital" and praised Tigard''s chief for being "willing to reframe the approach to policing" with emphasis on training. Her 2024 platform''s lead priority is to "prioritize and modernize our Police and Public Works facilities and resources so they can perform their duties efficiently," and she was endorsed by the Tigard Police Officers'' Association — sustained funding plus crisis-response additions rather than either defunding or expansion-first.', ARRAY['https://www.shawfortigard.com/achievements', 'https://washcodems.org/2020/10/12/jeanette-shaw-tigard-city-council-candidate-interview/', 'https://tigardlife.com/local-news/jeanette-shaw-2-2/']::text[]),
    ('growth-and-development', 3, 'In her 2020 Tigard Life profile Shaw framed growth in the Tigard Triangle, Washington Square, and Downtown Tigard as an opportunity to "be at the forefront of community innovation" and called for "developing Tigard''s future growth through a comprehensive strategic plan." Her campaign bio describes engaging the community on River Terrace 2.0 planning (community plan phase through 2026), and her 2024 achievements emphasize infrastructure investment ahead of need — citywide software modernization, water billing systems, and purchasing property for new police and public works facilities. This proactive plan-and-invest posture matches chair 3.', ARRAY['https://tigardlife.com/local-news/jeanette-shaw/', 'https://www.shawfortigard.com/meet-jeanette', 'https://www.shawfortigard.com/achievements']::text[]),
    ('residential-zoning', 3, 'Shaw''s campaign bio says she is engaging the community on River Terrace 2.0 planning for "a multi-modal, multi-use community that increases housing density" with walkable access to shopping, and her platform calls for "diverse housing for all income levels" and housing choices "for all stages of life" (2020 profile). She supports added density and mixed uses in planned growth areas rather than either strict neighborhood-character protection or citywide elimination of single-family zoning, matching the corridor/planned-density chair.', ARRAY['https://www.shawfortigard.com/meet-jeanette', 'https://tigardlife.com/local-news/jeanette-shaw/']::text[]),
    ('transportation-priorities', 2, 'Shaw''s 2024 candidate profile commits to filling "sidewalk gaps, create additional Safe Routes to School programs" and expanding "bike lanes" and mobility options, and her achievements cite the Locust Street Safe Routes to School project plus a $2M state grant for two more school routes. At the same time she prioritizes road maintenance — securing the Hall Boulevard jurisdictional transfer "in good repair" and "reducing road congestion" — a both/and roads-plus-multimodal investment posture matching chair 2.', ARRAY['https://tigardlife.com/local-news/jeanette-shaw-2-2/', 'https://www.shawfortigard.com/achievements']::text[]),
    ('climate-change', 3, 'In her October 2020 WashCo Dems interview Shaw noted transportation is "40% of fossil fuel carbon emissions" and backed electrification, EV charging in the Tigard Triangle, and California-style EV adoption incentives; her professional work includes legislation for transportation electrification (electric school buses, medium/heavy-duty vehicles). Her 2024 platform supports budgets that invest in Tigard''s Climate Action Resiliency Plan, and her achievements include a heat pump cash incentive program, replacing gas-powered city vehicles, tree canopy expansion, and public EV charging at three sites. This is clean-energy investment with gradual transition, not a rapid fossil-fuel phase-out mandate — chair 3. She was endorsed by the Oregon League of Conservation Voters in 2024.', ARRAY['https://washcodems.org/2020/10/12/jeanette-shaw-tigard-city-council-candidate-interview/', 'https://www.shawfortigard.com/achievements', 'https://tigardlife.com/local-news/jeanette-shaw-2-2/']::text[]),
    ('economic-development', 2, 'Shaw''s documented economic development record centers on small business: she cites establishing the $250K Tigard Small Business Sustainability Fund with the Chamber of Commerce, pandemic relief for residents and businesses, and a 2024 platform for budgets that "strengthen and support our businesses, grows our workforce." No documented support for large corporate tax abatements or recruitment subsidies appears in her record; her stated approach matches the small-business/local-support chair. She was endorsed by the Tigard Chamber of Commerce in 2024.', ARRAY['https://www.shawfortigard.com/achievements', 'https://tigardlife.com/local-news/jeanette-shaw-2-2/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '9e4d8f47-e4d5-4652-8fda-8e19b33bedea'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = '9e4d8f47-e4d5-4652-8fda-8e19b33bedea';
  IF v_ext IS DISTINCT FROM -4173656 THEN
    RAISE EXCEPTION 'UUID 9e4d8f47-e4d5-4652-8fda-8e19b33bedea does not belong to external_id -4173656 (Jeanette Shaw) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = '9e4d8f47-e4d5-4652-8fda-8e19b33bedea';
  IF n <> 8 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 8, n;
  END IF;
  -- Context-parity gate (WR-03): the context VALUES list is a verbatim
  -- duplicate of the answers list; count it too so a single-sided edit
  -- cannot silently drop or skew reasoning/sources rows.
  SELECT COUNT(*) INTO n FROM inform.politician_context WHERE politician_id = '9e4d8f47-e4d5-4652-8fda-8e19b33bedea';
  IF n <> 8 THEN
    RAISE EXCEPTION 'Expected % context rows, found % — answers/context VALUES lists diverged', 8, n;
  END IF;
END $$;

COMMIT;
