-- Migration 1167: Maureen Wolf (Councilor, Council President title-on-seat, Tigard OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 10 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Wolf''s #1 stated 2024 campaign priority was "Sustainable Housing Solutions." She explicitly supports Tigard''s toolkit of system development charge and construction excise tax exemptions, the Middle Housing Revolving Loan Fund (short-term public lending seeded with pandemic relief funds), fee reductions, land donations, and accessible loans that produced nearly 600 affordable homes in five years, plus tenant rent assistance partnership with Washington County. Her documented approach is targeted subsidies, exemptions, and easier financing for affordable projects — not rent caps or inclusionary mandates (chair 2) and not deregulation-only (chair 4).', ARRAY['https://tigardlife.com/local-news/maureen-wolf-5/', 'https://maureenwolf.com/goals/']::text[]),
    ('homelessness-response', 3, 'Wolf''s platform lists "reducing houselessness" as a top priority; her achievements page touts expanding Just Compassion shelter beds (20 to 60), the $1M Family Promise hotel purchase creating Bridge to Home transitional housing, Safe Parking Lots launching at City Hall (fall 2024), and support for Washington County''s Center for Addictions Triage & Treatment. At the same time she works within Tigard''s time/place/manner camping ordinance: at the Oct 28, 2025 council discussion on tightening camping hours she took a cautious middle path, requesting input from the city''s Community Homelessness Assessment & Response Team before finalizing changes (adopted Dec 16, 2025). Services-heavy investment paired with reasonable public-space rules matches chair 3.', ARRAY['https://maureenwolf.com/goals/', 'https://youroregonnews.com/2025/11/03/tigard-council-considers-tightening-hours-allowed-for-camping-on-city-property/', 'https://valleytimes.news/2025/12/18/tigard-overnight-camping-reduced-by-one-hour-each-day-camper-clearance-expanded/']::text[]),
    ('public-safety-approach', 3, 'Wolf led the "Keep Tigard Safe" campaign that renewed Tigard''s Public Safety Levy in May 2024 with 78% approval — the renewal continued the existing $0.29/$1,000 rate (no tax increase) to keep funding 8 patrol officers, 1 School Resource Officer, and de-escalation/crisis intervention training for all officers; the Tigard Police Officers'' Association endorsed her for it. She simultaneously supports Washington County''s Center for Addictions Triage & Treatment coming to serve Tigard. Maintaining current public-safety funding while backing crisis-intervention and addiction-response capacity matches chair 3.', ARRAY['https://maureenwolf.com/goals/', 'https://tigardlife.com/local-news/maureen-wolf-5/', 'https://www.tigard-or.gov/your-government/departments/police/about-tigard-police/public-safety-levy']::text[]),
    ('transportation-priorities', 2, 'Wolf''s campaign platform emphasizes "walkable and safe neighborhoods," and her achievements page highlights Safe Routes to School sidewalk/biking projects on Locust Street plus a $2M ODOT grant for Twality Middle School and Templeton Elementary improvements completed in 2025. For River Terrace 2.0 (4,500+ new homes) she insists residents have "biking, walking, driving, and transit options," and she champions Tigard''s needs in Washington County transportation planning. Investing in roads and multimodal infrastructure together matches chair 2.', ARRAY['https://maureenwolf.com/goals/', 'https://tigardlife.com/local-news/maureen-wolf-5/']::text[]),
    ('growth-and-development', 3, 'In her October 2024 Tigard Life candidate profile Wolf embraced River Terrace 2.0 — a 500+ acre expansion with an estimated 4,500 new homes — while emphasizing "balancing growth with livability" and ensuring multimodal infrastructure is in place for new residents. Her platform pairs growth with "modernizing facilities" and infrastructure investment rather than growth limits or blanket deregulation. Proactive planning and infrastructure ahead of growth matches chair 3.', ARRAY['https://tigardlife.com/local-news/maureen-wolf-5/', 'https://maureenwolf.com/']::text[]),
    ('residential-zoning', 3, 'Wolf explicitly supports Tigard''s Middle Housing Revolving Loan Fund financing duplex/middle-housing construction, and celebrates the nearly 600 affordable (largely multifamily) homes facilitated through fee exemptions and loans — Tigard "led the state in adopting affordable housing strategies before state law changed," per her 2024 candidate profile. Her record supports multifamily and middle housing where it fits (corridors, planned expansion areas like River Terrace) while framing it around neighborhood livability, matching chair 3.', ARRAY['https://tigardlife.com/local-news/maureen-wolf-5/', 'https://maureenwolf.com/goals/']::text[]),
    ('economic-development', 2, 'Wolf''s documented economic-development record is small-business centered: she partnered with the Tigard Chamber of Commerce to create the $250,000 Tigard Small Business Sustainability Fund for local business safety and security improvements, and earned the Chamber''s 2023 "From the Heart" award; her professional background is as a CPA specializing in small business practice. Her platform pairs "economic development and livability," with no record of pursuing large corporate tax abatements or incentive competitions. Chair 2 (small business and local entrepreneur support) best matches the documented record.', ARRAY['https://maureenwolf.com/goals/', 'https://maureenwolf.com/meet-maureen/']::text[]),
    ('climate-change', 3, '"Climate action initiatives" is a stated priority on Wolf''s own campaign site, and her 2022 candidate profile listed climate change mitigation among her city priorities. Her achievements page details incremental clean-energy investment: a city fleet electrification plan replacing eight gas vehicles, public EV charging stations, $11,000-per-home heat pump incentives, and forming a community-driven Climate Action Committee. This invest-in-clean-energy, gradual-transition posture matches chair 3; she has not advocated emergency bans or 2030 fossil-fuel phaseouts.', ARRAY['https://maureenwolf.com/', 'https://maureenwolf.com/goals/', 'https://tigardlife.com/local-news/maureen-wolf-2/']::text[]),
    ('civil-rights', 2, 'As Tigard-Tualatin School Board chair, Wolf voted yes on the district''s anti-racist/equity resolution adopted June 8, 2020 (passed 4-1), which made TTSD a statewide leader in anti-racist policy development. Her 2022 council campaign emphasized policies ensuring students feel "safe, included, and valued, with equitable opportunities," and she backed Tigard''s "Tigard Forward" budget plan that explicitly prioritized equity and inclusion. Actively addressing systemic inequity through institutional policy matches chair 2.', ARRAY['https://tuhswolf.com/1400/news/howantiracistresolution/', 'https://tigardlife.com/local-news/maureen-wolf-2/']::text[]),
    ('taxes', 3, 'Wolf led the 2024 "Keep Tigard Safe" campaign to renew Tigard''s Public Safety Levy at the existing $0.29/$1,000 rate — explicitly continuing, not raising, current taxes to preserve existing services (passed with 78% in May 2024). Endorsers and her own materials stress her CPA background and "efficient, responsible budgeting," and her 2022 profile noted "what is funded in a budget says a lot about the priorities." Maintaining the current tax structure to sustain current services matches chair 3.', ARRAY['https://maureenwolf.com/meet-maureen/', 'https://maureenwolf.com/goals/', 'https://tigardlife.com/local-news/maureen-wolf-2/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '4994a44e-ea96-4248-a39f-9ebadc5f97ef'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Wolf''s #1 stated 2024 campaign priority was "Sustainable Housing Solutions." She explicitly supports Tigard''s toolkit of system development charge and construction excise tax exemptions, the Middle Housing Revolving Loan Fund (short-term public lending seeded with pandemic relief funds), fee reductions, land donations, and accessible loans that produced nearly 600 affordable homes in five years, plus tenant rent assistance partnership with Washington County. Her documented approach is targeted subsidies, exemptions, and easier financing for affordable projects — not rent caps or inclusionary mandates (chair 2) and not deregulation-only (chair 4).', ARRAY['https://tigardlife.com/local-news/maureen-wolf-5/', 'https://maureenwolf.com/goals/']::text[]),
    ('homelessness-response', 3, 'Wolf''s platform lists "reducing houselessness" as a top priority; her achievements page touts expanding Just Compassion shelter beds (20 to 60), the $1M Family Promise hotel purchase creating Bridge to Home transitional housing, Safe Parking Lots launching at City Hall (fall 2024), and support for Washington County''s Center for Addictions Triage & Treatment. At the same time she works within Tigard''s time/place/manner camping ordinance: at the Oct 28, 2025 council discussion on tightening camping hours she took a cautious middle path, requesting input from the city''s Community Homelessness Assessment & Response Team before finalizing changes (adopted Dec 16, 2025). Services-heavy investment paired with reasonable public-space rules matches chair 3.', ARRAY['https://maureenwolf.com/goals/', 'https://youroregonnews.com/2025/11/03/tigard-council-considers-tightening-hours-allowed-for-camping-on-city-property/', 'https://valleytimes.news/2025/12/18/tigard-overnight-camping-reduced-by-one-hour-each-day-camper-clearance-expanded/']::text[]),
    ('public-safety-approach', 3, 'Wolf led the "Keep Tigard Safe" campaign that renewed Tigard''s Public Safety Levy in May 2024 with 78% approval — the renewal continued the existing $0.29/$1,000 rate (no tax increase) to keep funding 8 patrol officers, 1 School Resource Officer, and de-escalation/crisis intervention training for all officers; the Tigard Police Officers'' Association endorsed her for it. She simultaneously supports Washington County''s Center for Addictions Triage & Treatment coming to serve Tigard. Maintaining current public-safety funding while backing crisis-intervention and addiction-response capacity matches chair 3.', ARRAY['https://maureenwolf.com/goals/', 'https://tigardlife.com/local-news/maureen-wolf-5/', 'https://www.tigard-or.gov/your-government/departments/police/about-tigard-police/public-safety-levy']::text[]),
    ('transportation-priorities', 2, 'Wolf''s campaign platform emphasizes "walkable and safe neighborhoods," and her achievements page highlights Safe Routes to School sidewalk/biking projects on Locust Street plus a $2M ODOT grant for Twality Middle School and Templeton Elementary improvements completed in 2025. For River Terrace 2.0 (4,500+ new homes) she insists residents have "biking, walking, driving, and transit options," and she champions Tigard''s needs in Washington County transportation planning. Investing in roads and multimodal infrastructure together matches chair 2.', ARRAY['https://maureenwolf.com/goals/', 'https://tigardlife.com/local-news/maureen-wolf-5/']::text[]),
    ('growth-and-development', 3, 'In her October 2024 Tigard Life candidate profile Wolf embraced River Terrace 2.0 — a 500+ acre expansion with an estimated 4,500 new homes — while emphasizing "balancing growth with livability" and ensuring multimodal infrastructure is in place for new residents. Her platform pairs growth with "modernizing facilities" and infrastructure investment rather than growth limits or blanket deregulation. Proactive planning and infrastructure ahead of growth matches chair 3.', ARRAY['https://tigardlife.com/local-news/maureen-wolf-5/', 'https://maureenwolf.com/']::text[]),
    ('residential-zoning', 3, 'Wolf explicitly supports Tigard''s Middle Housing Revolving Loan Fund financing duplex/middle-housing construction, and celebrates the nearly 600 affordable (largely multifamily) homes facilitated through fee exemptions and loans — Tigard "led the state in adopting affordable housing strategies before state law changed," per her 2024 candidate profile. Her record supports multifamily and middle housing where it fits (corridors, planned expansion areas like River Terrace) while framing it around neighborhood livability, matching chair 3.', ARRAY['https://tigardlife.com/local-news/maureen-wolf-5/', 'https://maureenwolf.com/goals/']::text[]),
    ('economic-development', 2, 'Wolf''s documented economic-development record is small-business centered: she partnered with the Tigard Chamber of Commerce to create the $250,000 Tigard Small Business Sustainability Fund for local business safety and security improvements, and earned the Chamber''s 2023 "From the Heart" award; her professional background is as a CPA specializing in small business practice. Her platform pairs "economic development and livability," with no record of pursuing large corporate tax abatements or incentive competitions. Chair 2 (small business and local entrepreneur support) best matches the documented record.', ARRAY['https://maureenwolf.com/goals/', 'https://maureenwolf.com/meet-maureen/']::text[]),
    ('climate-change', 3, '"Climate action initiatives" is a stated priority on Wolf''s own campaign site, and her 2022 candidate profile listed climate change mitigation among her city priorities. Her achievements page details incremental clean-energy investment: a city fleet electrification plan replacing eight gas vehicles, public EV charging stations, $11,000-per-home heat pump incentives, and forming a community-driven Climate Action Committee. This invest-in-clean-energy, gradual-transition posture matches chair 3; she has not advocated emergency bans or 2030 fossil-fuel phaseouts.', ARRAY['https://maureenwolf.com/', 'https://maureenwolf.com/goals/', 'https://tigardlife.com/local-news/maureen-wolf-2/']::text[]),
    ('civil-rights', 2, 'As Tigard-Tualatin School Board chair, Wolf voted yes on the district''s anti-racist/equity resolution adopted June 8, 2020 (passed 4-1), which made TTSD a statewide leader in anti-racist policy development. Her 2022 council campaign emphasized policies ensuring students feel "safe, included, and valued, with equitable opportunities," and she backed Tigard''s "Tigard Forward" budget plan that explicitly prioritized equity and inclusion. Actively addressing systemic inequity through institutional policy matches chair 2.', ARRAY['https://tuhswolf.com/1400/news/howantiracistresolution/', 'https://tigardlife.com/local-news/maureen-wolf-2/']::text[]),
    ('taxes', 3, 'Wolf led the 2024 "Keep Tigard Safe" campaign to renew Tigard''s Public Safety Levy at the existing $0.29/$1,000 rate — explicitly continuing, not raising, current taxes to preserve existing services (passed with 78% in May 2024). Endorsers and her own materials stress her CPA background and "efficient, responsible budgeting," and her 2022 profile noted "what is funded in a budget says a lot about the priorities." Maintaining the current tax structure to sustain current services matches chair 3.', ARRAY['https://maureenwolf.com/meet-maureen/', 'https://maureenwolf.com/goals/', 'https://tigardlife.com/local-news/maureen-wolf-2/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '4994a44e-ea96-4248-a39f-9ebadc5f97ef'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
BEGIN
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = '4994a44e-ea96-4248-a39f-9ebadc5f97ef';
  IF n <> 10 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 10, n;
  END IF;
END $$;

COMMIT;
