-- Migration 1171: Frank Bubenik (Mayor, Tualatin OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 10 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Bubenik''s documented housing record centers on targeted subsidies for affordable projects plus working within permitting processes: he celebrated Plambeck Gardens, Tualatin''s first affordable housing community (116 units for households at 30-50% of median income, opened 2024) as a milestone in his 2025 State of the City, and the city paired it with a $2,500 grant to Community Partners for Affordable Housing for wrap-around resident services and $5,200 to Family Promise of Tualatin Valley. He convened the state-required Sept 30, 2024 "Barriers and Solutions to Housing" community meeting, noting Tualatin''s severe rent-burdened population exceeds 25% and stating the goal was "to see more people get permanently housed," while pressing Metro''s housing director for consulting county chairs but not mayors on a proposed supportive housing bond. He also voted Feb 28, 2022 to approve the Tualatin Heights rezoning enabling ~116 additional units. This matches the targeted-help chair (subsidies for affordable projects, working through permits) rather than rent caps/public housing or pure deregulation.', ARRAY['https://tualatinlife.com/local-news/officials-discuss-solutions-for-tualatins-affordable-housing-crisis/', 'https://tigardlife.com/featured/as-homelessness-surges-tigard-revisits-regulations-questions-equity-of-shared-response/', 'https://tualatinlife.com/featured/state-of-the-city-tualatin-is-going-full-steam-ahead/']::text[]),
    ('homelessness', 3, 'On public camping, Bubenik presided over and joined the unanimous June 26, 2023 council vote adopting Tualatin''s "time, place, and manner" ordinance, which prohibits camping in parks, parking lots, within 20 feet of buildings and 500 feet of freeways and schools, while designating one city-owned parcel next to the police station (capacity ~50 tents) where camping is permitted 7 p.m.-7 a.m. The ordinance was expressly written to comply with the state-law standard that people cannot be punished for camping when no alternative shelter is available, and Washington County was building a shelter-bed availability system with local law enforcement to guide its application. Bubenik framed the issue as "complex" and said Tualatin "has been engaged and involved and is working to do our part," pairing regulation with grants to service providers. That fits the chair allowing enforcement conditioned on available alternatives with diversion toward services, not blanket criminal bans or a protected right to camp anywhere.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://www.tualatinoregon.gov/administration/camping-regulations', 'https://tigardlife.com/featured/as-homelessness-surges-tigard-revisits-regulations-questions-equity-of-shared-response/']::text[]),
    ('homelessness-response', 3, 'Bubenik''s citywide strategy combines outreach and services investment with reasonable public-space rules: under his mayorship Tualatin adopted the 2023 camping regulations limiting camping to a designated overnight location, hired a homelessness-focused employee shared with Sherwood and Washington County (touted in his 2025 State of the City), and funds services through the Outside Agency Grant Program, which he called "a vital bridge connecting the city of Tualatin with community-based organizations that address residents'' most pressing needs" when it awarded $50K to 19 nonprofits in Sept 2025 — adding "By channeling financial resources into these areas, I believe we can make a lasting and positive impact on the lives of all Tualatin residents." He also points to the 116-unit Plambeck Gardens affordable community and wrap-around service grants as part of the response. This is the invest-in-outreach-shelter-and-services-while-enforcing-reasonable-rules chair, not enforcement-first or housing-first-no-enforcement.', ARRAY['https://valleytimes.news/2025/09/26/tualatin-awards-50k-to-19-area-nonprofits/', 'https://tigardlife.com/featured/as-homelessness-surges-tigard-revisits-regulations-questions-equity-of-shared-response/', 'https://tualatinlife.com/featured/state-of-the-city-tualatin-is-going-full-steam-ahead/']::text[]),
    ('growth-and-development', 3, 'Bubenik''s posture is proactive planning and infrastructure investment ahead of growth: the city committed $53 million to open the 717-acre Basalt Creek/Southwest development area — Tualatin''s first new investment area in over two decades — with new infrastructure and upsized utilities, and his 2025 State of the City promised "In 10 to 15 years, you''ll see things going full-steam ahead" while highlighting the Transportation System Plan update nearing completion and two new urban renewal areas to shape industrial and downtown growth. As early as his May 2021 State of the City he was planning for buildout, noting "Tualatin will be built out except for infill unless we extend our boundaries." Nothing in his record supports growth moratoria or voter-approval requirements, nor wholesale removal of regulatory barriers; he manages growth through planning, annexation strategy, and front-loaded infrastructure.', ARRAY['https://tualatinlife.com/featured/state-of-the-city-tualatin-is-going-full-steam-ahead/', 'https://www.tualatinoregon.gov/economicdevelopment/southwest-and-basalt-creek-development-area', 'https://tualatinlife.com/featured/state-of-the-city-busy/']::text[]),
    ('economic-development', 4, 'Bubenik has led an actively recruitment-oriented economic development program: under his mayorship Tualatin established two urban renewal (tax-increment) districts — the Southwest Basalt Creek Development Area for industrial/commercial employers and the Downtown Core Opportunity and Redevelopment Area — hired a dedicated urban renewal/economic development manager (Sid Sin), and committed $53 million to open 717 acres for employment development with new infrastructure, upsized utilities, and "additional incentive programs," with the Basalt Creek Manufacturing Park zone alone projected to accommodate ~1,897 new jobs. In March 2022 he identified the lack of developable land as among the city''s biggest obstacles to economic growth, framing land supply for employers as a problem for the city to solve. This matches competing actively for major employers with significant incentives and infrastructure investment, though he balances it with small-business and Latino Business Networking support rather than treating growth as the city''s sole priority.', ARRAY['https://www.tualatinoregon.gov/economicdevelopment/southwest-and-basalt-creek-development-area', 'https://tualatinlife.com/business/two-year-report-shows-mostly-sunny-snapshot-of-tualatins-economy/', 'https://tualatinlife.com/featured/state-of-the-city-tualatin-is-going-full-steam-ahead/']::text[]),
    ('transportation-priorities', 2, 'Bubenik''s signature transportation program, the voter-approved $20 million Tualatin Moving Forward bond he has shepherded as mayor (36 projects, nearly all complete by 2024), was explicitly split among congestion relief, neighborhood traffic safety, and safe walking access to schools and parks — investing in roads and pedestrian infrastructure together. He has simultaneously championed transit: on the Southwest Corridor light rail he said in Nov 2019 "The goal is to reduce congestion in the region... [light rail will] take more cars off I-5 and with improved bus transit, ideally we''ll get more cars off Tualatin-Sherwood Road and 99W," pushed for a full-size regional transit center (rather than a park-and-ride) with robust parking, and welcomed TriMet''s planned 72nd Avenue pedestrian safety improvements. This balanced roads-plus-multimodal investment record matches the invest-equally chair rather than a transit-first/parking-reduction agenda or a roads-only stance.', ARRAY['https://www.tualatinmovingforward.com/', 'https://tigardlife.com/featured/how-tigard-and-tualatin-will-be-impacted-by-the-southwest-corridor-light-rail-project/', 'https://www.tualatinoregon.gov/communitydevelopment/city-council-takes-final-tour-bond-funded-transportation-improvements']::text[]),
    ('climate-change', 3, 'Under Bubenik the Tualatin City Council adopted the Community Climate Action Plan in May 2024, a roadmap to citywide net-zero emissions by 2050 built on increasing energy efficiency and renewable energy use, more sustainable transportation, and infrastructure/natural-resource resilience; Bubenik said "This plan provides a road map for how the community can address the current and future impacts of climate change in Tualatin. The actions included in the plan will help ensure that our community is a healthy, resilient, and thriving place to live now and for generations to come." The city followed with the opt-out "Pennies for Climate Action" 99-cent monthly utility charge implemented in January 2026 to fund climate mitigation, and he has promoted the city''s sustainability initiatives in regional media. A 2050 net-zero target funded by modest voluntary charges is the invest-in-clean-energy-while-gradually-reducing-fossil-fuel-reliance chair, not a 2030 phase-out, emergency declaration, or market-only approach.', ARRAY['https://valleytimes.news/2026/01/07/pennies-for-climate-action-tualatin-implements-optional-charge-to-mitigate-climate-change/', 'https://tualatinoregon.gov/administration/climate-action/', 'https://tualatinlife.com/featured/state-of-the-city-tualatin-is-going-full-steam-ahead/']::text[]),
    ('civil-rights', 2, 'Bubenik has taken repeated documented actions to institutionalize inclusion and equity work in city government: in April 2023 the council under his leadership created the Inclusion, Diversity, Equity, and Access (IDEA) Advisory Committee, charged with recommending goals and measuring the city''s progress toward greater inclusion, diversity, equity, access, and belonging (he highlighted its creation and first annual report in his State of the City remarks, calling Tualatin "an active, interested, kind and inclusive community"). In February 2025 he voted with the 6-1 majority — over a councilor''s dissent — to proclaim March 31 Transgender Day of Visibility, and he has promoted the city''s inclusion, diversity, and access initiatives in regional media appearances. As a councilor he also joined the unanimous 2017 "Inclusive City" resolution embracing immigrant and refugee residents. Creating standing equity institutions and measuring progress goes beyond merely maintaining existing law, placing him at the actively-address-systemic-inequity chair, though he has proposed no mandates or reparations.', ARRAY['https://www.tualatinoregon.gov/idea', 'https://tualatinlife.com/featured/tualatin-to-recognize-transgender-day-of-visibility/', 'https://tualatinlife.com/featured/state-of-the-city-tualatin-is-going-full-steam-ahead/']::text[]),
    ('local-immigration', 3, 'On May 22, 2017, then-Councilor Bubenik voted with the unanimous council to declare Tualatin an "Inclusive City" — a resolution that welcomes immigrant and refugee residents and affirms that city resources cannot be used to enforce federal immigration law, consistent with Oregon''s statewide sanctuary statute; the "inclusive" framing was adopted as an alternative to a proposed "sanctuary city" resolution. Speaking as a former military police officer, Bubenik explained the division of labor directly: just as he enforced Army military law rather than other countries'' laws, ICE is empowered to enforce federal immigration law while the Tualatin Police Department enforces Oregon and Tualatin law, not federal policy. That is precisely the follow-federal-law-but-commit-no-city-resources-to-proactive-immigration-enforcement chair — he has not advocated actively assisting ICE, nor gone further toward refusing court-ordered cooperation.', ARRAY['https://www.valleytimes.news/news/tualatin-an-inclusive-city-city-council-declares-in-unanimous-vote/article_56c42f54-ee21-5a28-aad7-fef95025a927.html', 'https://www.koin.com/am-extra/tualatin-oregon-inclusion-diversity-access/']::text[]),
    ('residential-zoning', 2, 'Bubenik accepts added residential density but insists on strong local review and neighborhood mitigation: on the Tualatin Heights rezoning (raising an existing complex from 220 to 336 units, a ~50% density increase), he said at the Jan 24, 2022 hearing that "HB 2001 kind of handcuffed us," explaining the state law''s purpose was to "increase density and remove arbitrary standards so that cities couldn''t just block things they didn''t like" — lamenting lost local discretion — before voting with the 5-1 majority on Feb 28, 2022 to approve it while emphasizing the developer must still "go through a whole permit application process" and "be screened against city criteria," with "a lot of hurdles and steps... before they can begin construction." He proposed a residential parking permit area to protect neighbors across the street from overflow parking, and in his 2021 State of the City welcomed future multifamily with "more multi-bedroom units instead of just having one or two bedrooms." That matches allowing density increases with strong review and neighborhood input, rather than broad by-right upzoning or strict neighborhood-character protection requiring community votes.', ARRAY['https://tualatinlife.com/local-news/tualatin-city-council-grapples-with-new-zoning-requirements/', 'https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/', 'https://oregonhousingproject.org/cities/tualatin/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '8fbc9fc7-6840-450f-b490-24c41b2a153f'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Bubenik''s documented housing record centers on targeted subsidies for affordable projects plus working within permitting processes: he celebrated Plambeck Gardens, Tualatin''s first affordable housing community (116 units for households at 30-50% of median income, opened 2024) as a milestone in his 2025 State of the City, and the city paired it with a $2,500 grant to Community Partners for Affordable Housing for wrap-around resident services and $5,200 to Family Promise of Tualatin Valley. He convened the state-required Sept 30, 2024 "Barriers and Solutions to Housing" community meeting, noting Tualatin''s severe rent-burdened population exceeds 25% and stating the goal was "to see more people get permanently housed," while pressing Metro''s housing director for consulting county chairs but not mayors on a proposed supportive housing bond. He also voted Feb 28, 2022 to approve the Tualatin Heights rezoning enabling ~116 additional units. This matches the targeted-help chair (subsidies for affordable projects, working through permits) rather than rent caps/public housing or pure deregulation.', ARRAY['https://tualatinlife.com/local-news/officials-discuss-solutions-for-tualatins-affordable-housing-crisis/', 'https://tigardlife.com/featured/as-homelessness-surges-tigard-revisits-regulations-questions-equity-of-shared-response/', 'https://tualatinlife.com/featured/state-of-the-city-tualatin-is-going-full-steam-ahead/']::text[]),
    ('homelessness', 3, 'On public camping, Bubenik presided over and joined the unanimous June 26, 2023 council vote adopting Tualatin''s "time, place, and manner" ordinance, which prohibits camping in parks, parking lots, within 20 feet of buildings and 500 feet of freeways and schools, while designating one city-owned parcel next to the police station (capacity ~50 tents) where camping is permitted 7 p.m.-7 a.m. The ordinance was expressly written to comply with the state-law standard that people cannot be punished for camping when no alternative shelter is available, and Washington County was building a shelter-bed availability system with local law enforcement to guide its application. Bubenik framed the issue as "complex" and said Tualatin "has been engaged and involved and is working to do our part," pairing regulation with grants to service providers. That fits the chair allowing enforcement conditioned on available alternatives with diversion toward services, not blanket criminal bans or a protected right to camp anywhere.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://www.tualatinoregon.gov/administration/camping-regulations', 'https://tigardlife.com/featured/as-homelessness-surges-tigard-revisits-regulations-questions-equity-of-shared-response/']::text[]),
    ('homelessness-response', 3, 'Bubenik''s citywide strategy combines outreach and services investment with reasonable public-space rules: under his mayorship Tualatin adopted the 2023 camping regulations limiting camping to a designated overnight location, hired a homelessness-focused employee shared with Sherwood and Washington County (touted in his 2025 State of the City), and funds services through the Outside Agency Grant Program, which he called "a vital bridge connecting the city of Tualatin with community-based organizations that address residents'' most pressing needs" when it awarded $50K to 19 nonprofits in Sept 2025 — adding "By channeling financial resources into these areas, I believe we can make a lasting and positive impact on the lives of all Tualatin residents." He also points to the 116-unit Plambeck Gardens affordable community and wrap-around service grants as part of the response. This is the invest-in-outreach-shelter-and-services-while-enforcing-reasonable-rules chair, not enforcement-first or housing-first-no-enforcement.', ARRAY['https://valleytimes.news/2025/09/26/tualatin-awards-50k-to-19-area-nonprofits/', 'https://tigardlife.com/featured/as-homelessness-surges-tigard-revisits-regulations-questions-equity-of-shared-response/', 'https://tualatinlife.com/featured/state-of-the-city-tualatin-is-going-full-steam-ahead/']::text[]),
    ('growth-and-development', 3, 'Bubenik''s posture is proactive planning and infrastructure investment ahead of growth: the city committed $53 million to open the 717-acre Basalt Creek/Southwest development area — Tualatin''s first new investment area in over two decades — with new infrastructure and upsized utilities, and his 2025 State of the City promised "In 10 to 15 years, you''ll see things going full-steam ahead" while highlighting the Transportation System Plan update nearing completion and two new urban renewal areas to shape industrial and downtown growth. As early as his May 2021 State of the City he was planning for buildout, noting "Tualatin will be built out except for infill unless we extend our boundaries." Nothing in his record supports growth moratoria or voter-approval requirements, nor wholesale removal of regulatory barriers; he manages growth through planning, annexation strategy, and front-loaded infrastructure.', ARRAY['https://tualatinlife.com/featured/state-of-the-city-tualatin-is-going-full-steam-ahead/', 'https://www.tualatinoregon.gov/economicdevelopment/southwest-and-basalt-creek-development-area', 'https://tualatinlife.com/featured/state-of-the-city-busy/']::text[]),
    ('economic-development', 4, 'Bubenik has led an actively recruitment-oriented economic development program: under his mayorship Tualatin established two urban renewal (tax-increment) districts — the Southwest Basalt Creek Development Area for industrial/commercial employers and the Downtown Core Opportunity and Redevelopment Area — hired a dedicated urban renewal/economic development manager (Sid Sin), and committed $53 million to open 717 acres for employment development with new infrastructure, upsized utilities, and "additional incentive programs," with the Basalt Creek Manufacturing Park zone alone projected to accommodate ~1,897 new jobs. In March 2022 he identified the lack of developable land as among the city''s biggest obstacles to economic growth, framing land supply for employers as a problem for the city to solve. This matches competing actively for major employers with significant incentives and infrastructure investment, though he balances it with small-business and Latino Business Networking support rather than treating growth as the city''s sole priority.', ARRAY['https://www.tualatinoregon.gov/economicdevelopment/southwest-and-basalt-creek-development-area', 'https://tualatinlife.com/business/two-year-report-shows-mostly-sunny-snapshot-of-tualatins-economy/', 'https://tualatinlife.com/featured/state-of-the-city-tualatin-is-going-full-steam-ahead/']::text[]),
    ('transportation-priorities', 2, 'Bubenik''s signature transportation program, the voter-approved $20 million Tualatin Moving Forward bond he has shepherded as mayor (36 projects, nearly all complete by 2024), was explicitly split among congestion relief, neighborhood traffic safety, and safe walking access to schools and parks — investing in roads and pedestrian infrastructure together. He has simultaneously championed transit: on the Southwest Corridor light rail he said in Nov 2019 "The goal is to reduce congestion in the region... [light rail will] take more cars off I-5 and with improved bus transit, ideally we''ll get more cars off Tualatin-Sherwood Road and 99W," pushed for a full-size regional transit center (rather than a park-and-ride) with robust parking, and welcomed TriMet''s planned 72nd Avenue pedestrian safety improvements. This balanced roads-plus-multimodal investment record matches the invest-equally chair rather than a transit-first/parking-reduction agenda or a roads-only stance.', ARRAY['https://www.tualatinmovingforward.com/', 'https://tigardlife.com/featured/how-tigard-and-tualatin-will-be-impacted-by-the-southwest-corridor-light-rail-project/', 'https://www.tualatinoregon.gov/communitydevelopment/city-council-takes-final-tour-bond-funded-transportation-improvements']::text[]),
    ('climate-change', 3, 'Under Bubenik the Tualatin City Council adopted the Community Climate Action Plan in May 2024, a roadmap to citywide net-zero emissions by 2050 built on increasing energy efficiency and renewable energy use, more sustainable transportation, and infrastructure/natural-resource resilience; Bubenik said "This plan provides a road map for how the community can address the current and future impacts of climate change in Tualatin. The actions included in the plan will help ensure that our community is a healthy, resilient, and thriving place to live now and for generations to come." The city followed with the opt-out "Pennies for Climate Action" 99-cent monthly utility charge implemented in January 2026 to fund climate mitigation, and he has promoted the city''s sustainability initiatives in regional media. A 2050 net-zero target funded by modest voluntary charges is the invest-in-clean-energy-while-gradually-reducing-fossil-fuel-reliance chair, not a 2030 phase-out, emergency declaration, or market-only approach.', ARRAY['https://valleytimes.news/2026/01/07/pennies-for-climate-action-tualatin-implements-optional-charge-to-mitigate-climate-change/', 'https://tualatinoregon.gov/administration/climate-action/', 'https://tualatinlife.com/featured/state-of-the-city-tualatin-is-going-full-steam-ahead/']::text[]),
    ('civil-rights', 2, 'Bubenik has taken repeated documented actions to institutionalize inclusion and equity work in city government: in April 2023 the council under his leadership created the Inclusion, Diversity, Equity, and Access (IDEA) Advisory Committee, charged with recommending goals and measuring the city''s progress toward greater inclusion, diversity, equity, access, and belonging (he highlighted its creation and first annual report in his State of the City remarks, calling Tualatin "an active, interested, kind and inclusive community"). In February 2025 he voted with the 6-1 majority — over a councilor''s dissent — to proclaim March 31 Transgender Day of Visibility, and he has promoted the city''s inclusion, diversity, and access initiatives in regional media appearances. As a councilor he also joined the unanimous 2017 "Inclusive City" resolution embracing immigrant and refugee residents. Creating standing equity institutions and measuring progress goes beyond merely maintaining existing law, placing him at the actively-address-systemic-inequity chair, though he has proposed no mandates or reparations.', ARRAY['https://www.tualatinoregon.gov/idea', 'https://tualatinlife.com/featured/tualatin-to-recognize-transgender-day-of-visibility/', 'https://tualatinlife.com/featured/state-of-the-city-tualatin-is-going-full-steam-ahead/']::text[]),
    ('local-immigration', 3, 'On May 22, 2017, then-Councilor Bubenik voted with the unanimous council to declare Tualatin an "Inclusive City" — a resolution that welcomes immigrant and refugee residents and affirms that city resources cannot be used to enforce federal immigration law, consistent with Oregon''s statewide sanctuary statute; the "inclusive" framing was adopted as an alternative to a proposed "sanctuary city" resolution. Speaking as a former military police officer, Bubenik explained the division of labor directly: just as he enforced Army military law rather than other countries'' laws, ICE is empowered to enforce federal immigration law while the Tualatin Police Department enforces Oregon and Tualatin law, not federal policy. That is precisely the follow-federal-law-but-commit-no-city-resources-to-proactive-immigration-enforcement chair — he has not advocated actively assisting ICE, nor gone further toward refusing court-ordered cooperation.', ARRAY['https://www.valleytimes.news/news/tualatin-an-inclusive-city-city-council-declares-in-unanimous-vote/article_56c42f54-ee21-5a28-aad7-fef95025a927.html', 'https://www.koin.com/am-extra/tualatin-oregon-inclusion-diversity-access/']::text[]),
    ('residential-zoning', 2, 'Bubenik accepts added residential density but insists on strong local review and neighborhood mitigation: on the Tualatin Heights rezoning (raising an existing complex from 220 to 336 units, a ~50% density increase), he said at the Jan 24, 2022 hearing that "HB 2001 kind of handcuffed us," explaining the state law''s purpose was to "increase density and remove arbitrary standards so that cities couldn''t just block things they didn''t like" — lamenting lost local discretion — before voting with the 5-1 majority on Feb 28, 2022 to approve it while emphasizing the developer must still "go through a whole permit application process" and "be screened against city criteria," with "a lot of hurdles and steps... before they can begin construction." He proposed a residential parking permit area to protect neighbors across the street from overflow parking, and in his 2021 State of the City welcomed future multifamily with "more multi-bedroom units instead of just having one or two bedrooms." That matches allowing density increases with strong review and neighborhood input, rather than broad by-right upzoning or strict neighborhood-character protection requiring community votes.', ARRAY['https://tualatinlife.com/local-news/tualatin-city-council-grapples-with-new-zoning-requirements/', 'https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/', 'https://oregonhousingproject.org/cities/tualatin/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '8fbc9fc7-6840-450f-b490-24c41b2a153f'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = '8fbc9fc7-6840-450f-b490-24c41b2a153f';
  IF v_ext IS DISTINCT FROM -4174951 THEN
    RAISE EXCEPTION 'UUID 8fbc9fc7-6840-450f-b490-24c41b2a153f does not belong to external_id -4174951 (Frank Bubenik) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = '8fbc9fc7-6840-450f-b490-24c41b2a153f';
  IF n <> 10 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 10, n;
  END IF;
  -- Context-parity gate (WR-03): the context VALUES list is a verbatim
  -- duplicate of the answers list; count it too so a single-sided edit
  -- cannot silently drop or skew reasoning/sources rows.
  SELECT COUNT(*) INTO n FROM inform.politician_context WHERE politician_id = '8fbc9fc7-6840-450f-b490-24c41b2a153f';
  IF n <> 10 THEN
    RAISE EXCEPTION 'Expected % context rows, found % — answers/context VALUES lists diverged', 10, n;
  END IF;
END $$;

COMMIT;
