-- Migration 1172: María Reyes (Council Member Position 1, Tualatin OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 6 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Reyes''s clearest housing statement came at the Jan 24, 2022 Tualatin Heights rezoning hearing, where she urged approval of a density increase adding roughly 116 apartments over neighbors'' parking and green-space objections: "To me, what matters is that someone is inside a home warm with food, and then the rest will be fine," adding "I guarantee you that''s how my community thinks. That''s how my mom and I and new immigrants think." The rezoning passed 5-1 on Feb 28, 2022 (she was absent for the final vote but on record in favor from the earlier hearing). At the city''s state-required Sept 30, 2024 "Barriers and Solutions to Housing" community meeting — held because 26.8% of Tualatin''s population is severely rent-burdened — she pressed regional housing experts on how residents could get into affordable apartments faster given long waiting lists, calling it "a tough situation." Her record is about getting affordable units approved and residents into them through existing subsidy and permitting channels, matching the targeted-help chair rather than rent caps/public development or market-only deregulation.', ARRAY['https://tualatinlife.com/local-news/tualatin-city-council-grapples-with-new-zoning-requirements/', 'https://tualatinlife.com/local-news/officials-discuss-solutions-for-tualatins-affordable-housing-crisis/', 'https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/']::text[]),
    ('residential-zoning', 3, 'At the Jan 24, 2022 hearing on the Tualatin Heights rezoning — which raised an existing apartment property from 220 to 336 units, a roughly 50% density increase opposed by neighbors citing parking, loss of green space, and storage — Reyes spoke in favor, arguing the housing shortage outweighed those quality-of-life concerns: "To me, what matters is that someone is inside a home warm with food, and then the rest will be fine." She framed acceptance of added density as how "my community... my mom and I and new immigrants think." The ordinance passed 5-1 on Feb 28, 2022 with Reyes absent for the final vote but publicly on record supporting the change. Backing a major multifamily density increase at an existing apartment site over neighborhood objection — without advocating citywide by-right upzoning or the elimination of single-family zoning — best matches allowing multifamily growth in appropriate locations while leaving most residential zones intact.', ARRAY['https://tualatinlife.com/local-news/tualatin-city-council-grapples-with-new-zoning-requirements/', 'https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/']::text[]),
    ('homelessness', 3, 'Reyes joined the unanimous June 26, 2023 vote adopting Tualatin''s "time, place, and manner" camping ordinance, which prohibits camping in parks, parking lots, within 20 feet of buildings and 500 feet of freeways and schools, while designating a single city-owned parcel next to the police station (capacity about 50 tents) where camping is allowed 7 p.m. to 7 a.m. She explained her vote as deliberate incrementalism tied to the designated alternative site: "I''m in favor of starting slowly, then moving and progressing. I''m in favor of the police station lot." The ordinance was expressly written to comply with the Oregon-law standard that people cannot be punished for sleeping outside when no alternative shelter is available, with Washington County building a shelter-bed availability system to guide enforcement. Supporting regulated enforcement conditioned on an available alternative location matches the enforcement-only-when-shelter-is-available chair, not a blanket criminal ban or an unrestricted right to camp in public spaces.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://www.tualatinoregon.gov/administration/camping-regulations']::text[]),
    ('homelessness-response', 3, 'Reyes''s documented approach pairs reasonable public-space rules with services and housing access: she voted for the unanimous June 26, 2023 camping ordinance that restricts camping citywide while providing a designated overnight site next to the police station, saying "I''m in favor of starting slowly, then moving and progressing. I''m in favor of the police station lot." At the Sept 30, 2024 "Barriers and Solutions to Housing" community discussion she focused on the services side, asking regional housing experts how people stuck on long waiting lists could reach affordable apartments faster and calling it "a tough situation." The ordinance she supported operates within a county shelter-bed availability framework rather than as punitive-first enforcement. That combination — pushing housing and service connections for unhoused residents alongside enforceable time-place-manner rules — matches the outreach-shelter-and-services-with-reasonable-rules chair rather than the enforcement-primary or no-enforcement housing-first chairs.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://tualatinlife.com/local-news/officials-discuss-solutions-for-tualatins-affordable-housing-crisis/', 'https://www.tualatinoregon.gov/administration/camping-regulations']::text[]),
    ('civil-rights', 2, 'Reyes has a sustained record of institutionalizing inclusion work in Tualatin government: she came to the council from the city''s volunteer Diversity Task Force (which she joined in 2016), became the first Latina ever elected to the Tualatin City Council in Nov 2018, and in February 2025 voted with the 6-1 majority — over Councilor Octavio Gonzalez''s dissent — to proclaim March 31 Transgender Day of Visibility, recognizing transgender and nonbinary residents'' contributions to the community. During her tenure the council also created the Inclusion, Diversity, Equity, and Access (IDEA) Advisory Committee (2023) to set and measure equity goals for city government. Her official city biography highlights her ongoing engagement with TuaLatinos and the Café con Pan Dulce Latino business network as core councilor activity. Taking affirmative public actions to advance inclusion for immigrant, Latino, and LGBTQ residents — over dissent when necessary — goes beyond merely maintaining existing law, matching the strengthen-protections chair, while nothing in her record supports institution-wide mandates or reparations.', ARRAY['https://tualatinlife.com/featured/tualatin-to-recognize-transgender-day-of-visibility/', 'https://tualatinoregon.gov/city-council/', 'https://tualatinlife.com/featured/meet-your-councilor-maria-a-reyes/']::text[]),
    ('transportation-priorities', 2, 'Reyes''s official councilor biography states that her experience living in Los Angeles and Washington, D.C. "has increased her focus on investing in better transportation in growing communities" and that she "is committed to providing faster transportation and better access for commuters between Tualatin and other metro cities" — an explicit commuter-transit investment commitment published as her position. She serves as an alternate on the C4 Metro Sub-Committee (the regional transportation/land-use coordinating body) and on the Core Area Parking District Board, and her entire tenure (Jan 2019 to present) spans the council''s implementation of the voter-approved $20 million Tualatin Moving Forward program, whose 36 projects deliberately mix congestion relief, neighborhood traffic safety, and safe walking access to schools and parks. Championing better transit access for commuters while the council she serves on delivers road and pedestrian projects together matches the invest-in-roads-and-multimodal-together chair rather than a transit-first/parking-reduction agenda or a roads-primary stance.', ARRAY['https://tualatinoregon.gov/city-council/', 'https://www.tualatinmovingforward.com/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT 'f7c39cdd-959c-4ae9-8894-d7dda67fc9e8'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Reyes''s clearest housing statement came at the Jan 24, 2022 Tualatin Heights rezoning hearing, where she urged approval of a density increase adding roughly 116 apartments over neighbors'' parking and green-space objections: "To me, what matters is that someone is inside a home warm with food, and then the rest will be fine," adding "I guarantee you that''s how my community thinks. That''s how my mom and I and new immigrants think." The rezoning passed 5-1 on Feb 28, 2022 (she was absent for the final vote but on record in favor from the earlier hearing). At the city''s state-required Sept 30, 2024 "Barriers and Solutions to Housing" community meeting — held because 26.8% of Tualatin''s population is severely rent-burdened — she pressed regional housing experts on how residents could get into affordable apartments faster given long waiting lists, calling it "a tough situation." Her record is about getting affordable units approved and residents into them through existing subsidy and permitting channels, matching the targeted-help chair rather than rent caps/public development or market-only deregulation.', ARRAY['https://tualatinlife.com/local-news/tualatin-city-council-grapples-with-new-zoning-requirements/', 'https://tualatinlife.com/local-news/officials-discuss-solutions-for-tualatins-affordable-housing-crisis/', 'https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/']::text[]),
    ('residential-zoning', 3, 'At the Jan 24, 2022 hearing on the Tualatin Heights rezoning — which raised an existing apartment property from 220 to 336 units, a roughly 50% density increase opposed by neighbors citing parking, loss of green space, and storage — Reyes spoke in favor, arguing the housing shortage outweighed those quality-of-life concerns: "To me, what matters is that someone is inside a home warm with food, and then the rest will be fine." She framed acceptance of added density as how "my community... my mom and I and new immigrants think." The ordinance passed 5-1 on Feb 28, 2022 with Reyes absent for the final vote but publicly on record supporting the change. Backing a major multifamily density increase at an existing apartment site over neighborhood objection — without advocating citywide by-right upzoning or the elimination of single-family zoning — best matches allowing multifamily growth in appropriate locations while leaving most residential zones intact.', ARRAY['https://tualatinlife.com/local-news/tualatin-city-council-grapples-with-new-zoning-requirements/', 'https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/']::text[]),
    ('homelessness', 3, 'Reyes joined the unanimous June 26, 2023 vote adopting Tualatin''s "time, place, and manner" camping ordinance, which prohibits camping in parks, parking lots, within 20 feet of buildings and 500 feet of freeways and schools, while designating a single city-owned parcel next to the police station (capacity about 50 tents) where camping is allowed 7 p.m. to 7 a.m. She explained her vote as deliberate incrementalism tied to the designated alternative site: "I''m in favor of starting slowly, then moving and progressing. I''m in favor of the police station lot." The ordinance was expressly written to comply with the Oregon-law standard that people cannot be punished for sleeping outside when no alternative shelter is available, with Washington County building a shelter-bed availability system to guide enforcement. Supporting regulated enforcement conditioned on an available alternative location matches the enforcement-only-when-shelter-is-available chair, not a blanket criminal ban or an unrestricted right to camp in public spaces.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://www.tualatinoregon.gov/administration/camping-regulations']::text[]),
    ('homelessness-response', 3, 'Reyes''s documented approach pairs reasonable public-space rules with services and housing access: she voted for the unanimous June 26, 2023 camping ordinance that restricts camping citywide while providing a designated overnight site next to the police station, saying "I''m in favor of starting slowly, then moving and progressing. I''m in favor of the police station lot." At the Sept 30, 2024 "Barriers and Solutions to Housing" community discussion she focused on the services side, asking regional housing experts how people stuck on long waiting lists could reach affordable apartments faster and calling it "a tough situation." The ordinance she supported operates within a county shelter-bed availability framework rather than as punitive-first enforcement. That combination — pushing housing and service connections for unhoused residents alongside enforceable time-place-manner rules — matches the outreach-shelter-and-services-with-reasonable-rules chair rather than the enforcement-primary or no-enforcement housing-first chairs.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://tualatinlife.com/local-news/officials-discuss-solutions-for-tualatins-affordable-housing-crisis/', 'https://www.tualatinoregon.gov/administration/camping-regulations']::text[]),
    ('civil-rights', 2, 'Reyes has a sustained record of institutionalizing inclusion work in Tualatin government: she came to the council from the city''s volunteer Diversity Task Force (which she joined in 2016), became the first Latina ever elected to the Tualatin City Council in Nov 2018, and in February 2025 voted with the 6-1 majority — over Councilor Octavio Gonzalez''s dissent — to proclaim March 31 Transgender Day of Visibility, recognizing transgender and nonbinary residents'' contributions to the community. During her tenure the council also created the Inclusion, Diversity, Equity, and Access (IDEA) Advisory Committee (2023) to set and measure equity goals for city government. Her official city biography highlights her ongoing engagement with TuaLatinos and the Café con Pan Dulce Latino business network as core councilor activity. Taking affirmative public actions to advance inclusion for immigrant, Latino, and LGBTQ residents — over dissent when necessary — goes beyond merely maintaining existing law, matching the strengthen-protections chair, while nothing in her record supports institution-wide mandates or reparations.', ARRAY['https://tualatinlife.com/featured/tualatin-to-recognize-transgender-day-of-visibility/', 'https://tualatinoregon.gov/city-council/', 'https://tualatinlife.com/featured/meet-your-councilor-maria-a-reyes/']::text[]),
    ('transportation-priorities', 2, 'Reyes''s official councilor biography states that her experience living in Los Angeles and Washington, D.C. "has increased her focus on investing in better transportation in growing communities" and that she "is committed to providing faster transportation and better access for commuters between Tualatin and other metro cities" — an explicit commuter-transit investment commitment published as her position. She serves as an alternate on the C4 Metro Sub-Committee (the regional transportation/land-use coordinating body) and on the Core Area Parking District Board, and her entire tenure (Jan 2019 to present) spans the council''s implementation of the voter-approved $20 million Tualatin Moving Forward program, whose 36 projects deliberately mix congestion relief, neighborhood traffic safety, and safe walking access to schools and parks. Championing better transit access for commuters while the council she serves on delivers road and pedestrian projects together matches the invest-in-roads-and-multimodal-together chair rather than a transit-first/parking-reduction agenda or a roads-primary stance.', ARRAY['https://tualatinoregon.gov/city-council/', 'https://www.tualatinmovingforward.com/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT 'f7c39cdd-959c-4ae9-8894-d7dda67fc9e8'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = 'f7c39cdd-959c-4ae9-8894-d7dda67fc9e8';
  IF v_ext IS DISTINCT FROM -4174952 THEN
    RAISE EXCEPTION 'UUID f7c39cdd-959c-4ae9-8894-d7dda67fc9e8 does not belong to external_id -4174952 (María Reyes) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = 'f7c39cdd-959c-4ae9-8894-d7dda67fc9e8';
  IF n <> 6 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 6, n;
  END IF;
  -- Context-parity gate (WR-03): the context VALUES list is a verbatim
  -- duplicate of the answers list; count it too so a single-sided edit
  -- cannot silently drop or skew reasoning/sources rows.
  SELECT COUNT(*) INTO n FROM inform.politician_context WHERE politician_id = 'f7c39cdd-959c-4ae9-8894-d7dda67fc9e8';
  IF n <> 6 THEN
    RAISE EXCEPTION 'Expected % context rows, found % — answers/context VALUES lists diverged', 6, n;
  END IF;
END $$;

COMMIT;
