-- Migration 1173: Christen Sacco (Council Member Position 2, Tualatin OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 8 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Sacco''s documented housing record centers on targeted, equity-framed solutions worked through the city''s existing review processes. At the Jan 24, 2022 Tualatin Heights hearing she said "We have a huge housing crisis in our area. At the same time, there are concerns about losing storage, green spaces and parking. We want to maintain a decent quality of life for everybody and not leave people behind," and on Feb 28, 2022 she voted with the 5-1 majority to approve the rezoning enabling roughly 116 additional multifamily units at an existing complex. In her Sept 2024 reelection platform she named housing an ongoing council priority, pledging to "continue to advocate for creative solutions and funding that are equitable" because housing costs "disproportionately impact our most vulnerable community members." That is the targeted-help chair — subsidized/creative affordable-housing solutions and permitting-process approvals — rather than rent caps and public construction or market-only deregulation, neither of which she has advocated.', ARRAY['https://tualatinlife.com/local-news/tualatin-city-council-grapples-with-new-zoning-requirements/','https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/','https://hillsboronewstimes.com/2024/09/13/sacco-seeks-second-term-on-tualatin-city-council/']::text[]),
    ('residential-zoning', 2, 'On the highest-profile density decision of her tenure — the Tualatin Heights rezoning raising an existing apartment property from 220 to 336 units — Sacco voted yes with the 5-1 majority on Feb 28, 2022, but only after publicly weighing neighborhood impacts through two hearings. Her Jan 24, 2022 statement framed the tradeoff directly: "We have a huge housing crisis in our area. At the same time, there are concerns about losing storage, green spaces and parking. We want to maintain a decent quality of life for everybody and not leave people behind." She accepted the added density while insisting the neighborhood not be "left behind" on green space, parking, and livability, and the approval still ran through the city''s full permit and design-review pipeline. That matches the chair allowing density increases with strong design review and neighborhood input; she has never advocated broad by-right upzoning, nor demanded community votes to freeze neighborhood character.', ARRAY['https://tualatinlife.com/local-news/tualatin-city-council-grapples-with-new-zoning-requirements/','https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/']::text[]),
    ('homelessness', 3, 'Sacco was a sitting councilor when the Tualatin City Council voted unanimously on June 26, 2023 to adopt the city''s "time, place, and manner" camping ordinance, which prohibits camping in parks, parking lots, within 20 feet of buildings and 500 feet of freeways and schools, while designating a single city-owned lot next to the police station where overnight camping (7 p.m.-7 a.m., roughly 50-tent capacity) is permitted. The ordinance was expressly written to comply with the Oregon state-law standard that people cannot be punished for sleeping outside when no alternative shelter is available, and Washington County was building a shelter-bed availability system with local law enforcement to guide its application. Her unanimous vote for regulated time-place-manner limits paired with a lawful designated alternative fits the chair allowing enforcement only when alternatives exist, with diversion toward services — not a blanket criminal ban and not a protected right to camp anywhere.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/','https://www.tualatinoregon.gov/administration/camping-regulations']::text[]),
    ('homelessness-response', 3, 'Sacco''s documented strategy pairs reasonable public-space rules with equity-focused service investment. She joined the unanimous June 26, 2023 vote adopting Tualatin''s camping regulations, which channel camping to one designated overnight location while the city and Washington County stand up shelter-bed tracking and outreach; the council she serves on funds community-based service organizations alongside that enforcement framework. Her own framing is services-forward: her 2024 platform commits to "creative solutions and funding that are equitable" for problems that "disproportionately impact our most vulnerable community members," and the I.D.E.A. Advisory Committee she championed is chartered to advocate for underserved populations and measure the city''s progress. That combination — enforce reasonable rules while investing in outreach and support for vulnerable residents — is the middle chair, not enforcement-first minimalism and not housing-first with no enforcement.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/','https://hillsboronewstimes.com/2024/09/13/sacco-seeks-second-term-on-tualatin-city-council/','https://tualatinlife.com/local-news/council-corner-december-2024/']::text[]),
    ('climate-change', 3, 'Sacco has a recorded pro-climate-compliance vote: in September 2022, when the council voted 4-3 to join a 13-city lawsuit seeking to halt Oregon''s Climate Friendly and Equitable Communities rules (parking reform, EV-charging mandates, tree-canopy requirements), Sacco was one of the three dissenters voting against suing the state — the dissenting bloc argued the money was better spent working toward the climate goals than on litigation. She also participated in the council''s unanimous early-2022 vote awarding the $280,000 Climate Action Plan contract that produced Tualatin''s Community Climate Action Plan, adopted by the council in May 2024 with a roadmap to citywide net-zero emissions by 2050 through energy efficiency, renewable energy, and more sustainable transportation. Supporting compliance with state climate rules and a 2050 net-zero municipal roadmap matches the invest-in-clean-energy-while-gradually-reducing-fossil-fuel-reliance chair; she has not advocated a 2030 phase-out or emergency declaration, nor a market-only approach.', ARRAY['https://tualatinlife.com/local-news/tualatin-among-13-cities-suing-oregon-to-halt-new-climate-regulations/','https://tualatinlife.com/local-news/city-of-tualatin-awards-climate-action-plan-contract/','https://tualatinoregon.gov/administration/climate-action/']::text[]),
    ('civil-rights', 2, 'Equity and inclusion are Sacco''s signature issue, backed by institutional action rather than statements alone. She cites creating the Inclusion, Diversity, Equity, and Access (I.D.E.A.) Advisory Committee — chartered in 2023 to advocate for underserved populations, identify opportunities, and recommend measurable goals — as a first-term accomplishment, and her Council Corner columns (Aug 2023, Dec 2024) center the Tualatin 2030 Vision to "cultivate a caring and inclusive community that promotes equity, diversity, belonging and access," celebrating Pride and ¡Viva Tualatin! events. In February 2025 she voted with the 6-1 majority — over a colleague''s dissent — to proclaim March 31 Transgender Day of Visibility and spoke in support of the motion. Her 2020 platform pressed language access (translation of city materials, interpretation at meetings), arguing "City leaders cannot serve the people of Tualatin until they have the ability to serve all the people of Tualatin." Building standing equity institutions and measuring progress goes beyond maintaining current law, placing her at the actively-address-systemic-inequity chair, though she has proposed no mandates or reparations.', ARRAY['https://hillsboronewstimes.com/2024/09/13/sacco-seeks-second-term-on-tualatin-city-council/','https://tualatinlife.com/local-news/council-corner-august-2023/','https://tualatinlife.com/featured/tualatin-to-recognize-transgender-day-of-visibility/']::text[]),
    ('local-environment', 3, 'Sacco''s record balances a strong personal preservation background with acceptance of code-compliant development. Before and during her council service she sat on the Tualatin Tree City USA board, the Bee City USA committee, and the Parks Advisory Committee (as vice-chair), and she advocated for the $25 million parks-and-trails bond voters passed in November 2022. Yet in her Aug 7, 2025 first-party op-ed on the Norwood Road church expansion she defended the city''s final land-use approvals while acknowledging that "the City''s goals, such as tree preservation and enhanced pedestrian safety, may appear to be at odds," committing to preserve trees "whenever possible" and expressing confidence that "with collaboration and thoughtful planning, a solution can be reached that protects the trees while ensuring a safe and accessible environment." Applying the city''s environmental standards while working flexibly with the developer through conditions of approval — rather than blocking development or demanding full offsets — matches the consistent-standards-with-reasonable-flexibility chair.', ARRAY['https://tualatinlife.com/local-news/opinion-city-prioritizes-tree-preservation-and-pedestrian-safety-along-norwood-road/','https://tualatinlife.com/politics/christen-sacco/','https://hillsboronewstimes.com/2024/09/13/sacco-seeks-second-term-on-tualatin-city-council/']::text[]),
    ('transportation-priorities', 2, 'Sacco''s documented transportation posture is roads-plus-multimodal together. Her Aug 2025 Norwood Road op-ed describes the city''s street-design goal as corridors with "travel lanes, bicycle lanes, planter strips, and sidewalks" to create "a safer and more comfortable transportation environment" — bike and pedestrian facilities built into road projects as a matter of course. In September 2022 she voted against Tualatin joining the 13-city lawsuit to block Oregon''s Climate Friendly and Equitable Communities rules, declining to fight state mandates that eliminate parking minimums, cap parking near transit, and require EV charging in new development. Her 2024 platform names transportation a top council priority with a pledge to "advocate for creative solutions and funding that are equitable" for vulnerable residents. Requiring multimodal elements on road projects while accepting (not initiating) parking reform matches the invest-equally chair rather than a transit-first parking-reduction agenda or a roads-and-parking-first stance.', ARRAY['https://tualatinlife.com/local-news/opinion-city-prioritizes-tree-preservation-and-pedestrian-safety-along-norwood-road/','https://tualatinlife.com/local-news/tualatin-among-13-cities-suing-oregon-to-halt-new-climate-regulations/','https://hillsboronewstimes.com/2024/09/13/sacco-seeks-second-term-on-tualatin-city-council/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '95368151-cddd-4ac4-924d-4a2a1989daf9'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Sacco''s documented housing record centers on targeted, equity-framed solutions worked through the city''s existing review processes. At the Jan 24, 2022 Tualatin Heights hearing she said "We have a huge housing crisis in our area. At the same time, there are concerns about losing storage, green spaces and parking. We want to maintain a decent quality of life for everybody and not leave people behind," and on Feb 28, 2022 she voted with the 5-1 majority to approve the rezoning enabling roughly 116 additional multifamily units at an existing complex. In her Sept 2024 reelection platform she named housing an ongoing council priority, pledging to "continue to advocate for creative solutions and funding that are equitable" because housing costs "disproportionately impact our most vulnerable community members." That is the targeted-help chair — subsidized/creative affordable-housing solutions and permitting-process approvals — rather than rent caps and public construction or market-only deregulation, neither of which she has advocated.', ARRAY['https://tualatinlife.com/local-news/tualatin-city-council-grapples-with-new-zoning-requirements/','https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/','https://hillsboronewstimes.com/2024/09/13/sacco-seeks-second-term-on-tualatin-city-council/']::text[]),
    ('residential-zoning', 2, 'On the highest-profile density decision of her tenure — the Tualatin Heights rezoning raising an existing apartment property from 220 to 336 units — Sacco voted yes with the 5-1 majority on Feb 28, 2022, but only after publicly weighing neighborhood impacts through two hearings. Her Jan 24, 2022 statement framed the tradeoff directly: "We have a huge housing crisis in our area. At the same time, there are concerns about losing storage, green spaces and parking. We want to maintain a decent quality of life for everybody and not leave people behind." She accepted the added density while insisting the neighborhood not be "left behind" on green space, parking, and livability, and the approval still ran through the city''s full permit and design-review pipeline. That matches the chair allowing density increases with strong design review and neighborhood input; she has never advocated broad by-right upzoning, nor demanded community votes to freeze neighborhood character.', ARRAY['https://tualatinlife.com/local-news/tualatin-city-council-grapples-with-new-zoning-requirements/','https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/']::text[]),
    ('homelessness', 3, 'Sacco was a sitting councilor when the Tualatin City Council voted unanimously on June 26, 2023 to adopt the city''s "time, place, and manner" camping ordinance, which prohibits camping in parks, parking lots, within 20 feet of buildings and 500 feet of freeways and schools, while designating a single city-owned lot next to the police station where overnight camping (7 p.m.-7 a.m., roughly 50-tent capacity) is permitted. The ordinance was expressly written to comply with the Oregon state-law standard that people cannot be punished for sleeping outside when no alternative shelter is available, and Washington County was building a shelter-bed availability system with local law enforcement to guide its application. Her unanimous vote for regulated time-place-manner limits paired with a lawful designated alternative fits the chair allowing enforcement only when alternatives exist, with diversion toward services — not a blanket criminal ban and not a protected right to camp anywhere.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/','https://www.tualatinoregon.gov/administration/camping-regulations']::text[]),
    ('homelessness-response', 3, 'Sacco''s documented strategy pairs reasonable public-space rules with equity-focused service investment. She joined the unanimous June 26, 2023 vote adopting Tualatin''s camping regulations, which channel camping to one designated overnight location while the city and Washington County stand up shelter-bed tracking and outreach; the council she serves on funds community-based service organizations alongside that enforcement framework. Her own framing is services-forward: her 2024 platform commits to "creative solutions and funding that are equitable" for problems that "disproportionately impact our most vulnerable community members," and the I.D.E.A. Advisory Committee she championed is chartered to advocate for underserved populations and measure the city''s progress. That combination — enforce reasonable rules while investing in outreach and support for vulnerable residents — is the middle chair, not enforcement-first minimalism and not housing-first with no enforcement.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/','https://hillsboronewstimes.com/2024/09/13/sacco-seeks-second-term-on-tualatin-city-council/','https://tualatinlife.com/local-news/council-corner-december-2024/']::text[]),
    ('climate-change', 3, 'Sacco has a recorded pro-climate-compliance vote: in September 2022, when the council voted 4-3 to join a 13-city lawsuit seeking to halt Oregon''s Climate Friendly and Equitable Communities rules (parking reform, EV-charging mandates, tree-canopy requirements), Sacco was one of the three dissenters voting against suing the state — the dissenting bloc argued the money was better spent working toward the climate goals than on litigation. She also participated in the council''s unanimous early-2022 vote awarding the $280,000 Climate Action Plan contract that produced Tualatin''s Community Climate Action Plan, adopted by the council in May 2024 with a roadmap to citywide net-zero emissions by 2050 through energy efficiency, renewable energy, and more sustainable transportation. Supporting compliance with state climate rules and a 2050 net-zero municipal roadmap matches the invest-in-clean-energy-while-gradually-reducing-fossil-fuel-reliance chair; she has not advocated a 2030 phase-out or emergency declaration, nor a market-only approach.', ARRAY['https://tualatinlife.com/local-news/tualatin-among-13-cities-suing-oregon-to-halt-new-climate-regulations/','https://tualatinlife.com/local-news/city-of-tualatin-awards-climate-action-plan-contract/','https://tualatinoregon.gov/administration/climate-action/']::text[]),
    ('civil-rights', 2, 'Equity and inclusion are Sacco''s signature issue, backed by institutional action rather than statements alone. She cites creating the Inclusion, Diversity, Equity, and Access (I.D.E.A.) Advisory Committee — chartered in 2023 to advocate for underserved populations, identify opportunities, and recommend measurable goals — as a first-term accomplishment, and her Council Corner columns (Aug 2023, Dec 2024) center the Tualatin 2030 Vision to "cultivate a caring and inclusive community that promotes equity, diversity, belonging and access," celebrating Pride and ¡Viva Tualatin! events. In February 2025 she voted with the 6-1 majority — over a colleague''s dissent — to proclaim March 31 Transgender Day of Visibility and spoke in support of the motion. Her 2020 platform pressed language access (translation of city materials, interpretation at meetings), arguing "City leaders cannot serve the people of Tualatin until they have the ability to serve all the people of Tualatin." Building standing equity institutions and measuring progress goes beyond maintaining current law, placing her at the actively-address-systemic-inequity chair, though she has proposed no mandates or reparations.', ARRAY['https://hillsboronewstimes.com/2024/09/13/sacco-seeks-second-term-on-tualatin-city-council/','https://tualatinlife.com/local-news/council-corner-august-2023/','https://tualatinlife.com/featured/tualatin-to-recognize-transgender-day-of-visibility/']::text[]),
    ('local-environment', 3, 'Sacco''s record balances a strong personal preservation background with acceptance of code-compliant development. Before and during her council service she sat on the Tualatin Tree City USA board, the Bee City USA committee, and the Parks Advisory Committee (as vice-chair), and she advocated for the $25 million parks-and-trails bond voters passed in November 2022. Yet in her Aug 7, 2025 first-party op-ed on the Norwood Road church expansion she defended the city''s final land-use approvals while acknowledging that "the City''s goals, such as tree preservation and enhanced pedestrian safety, may appear to be at odds," committing to preserve trees "whenever possible" and expressing confidence that "with collaboration and thoughtful planning, a solution can be reached that protects the trees while ensuring a safe and accessible environment." Applying the city''s environmental standards while working flexibly with the developer through conditions of approval — rather than blocking development or demanding full offsets — matches the consistent-standards-with-reasonable-flexibility chair.', ARRAY['https://tualatinlife.com/local-news/opinion-city-prioritizes-tree-preservation-and-pedestrian-safety-along-norwood-road/','https://tualatinlife.com/politics/christen-sacco/','https://hillsboronewstimes.com/2024/09/13/sacco-seeks-second-term-on-tualatin-city-council/']::text[]),
    ('transportation-priorities', 2, 'Sacco''s documented transportation posture is roads-plus-multimodal together. Her Aug 2025 Norwood Road op-ed describes the city''s street-design goal as corridors with "travel lanes, bicycle lanes, planter strips, and sidewalks" to create "a safer and more comfortable transportation environment" — bike and pedestrian facilities built into road projects as a matter of course. In September 2022 she voted against Tualatin joining the 13-city lawsuit to block Oregon''s Climate Friendly and Equitable Communities rules, declining to fight state mandates that eliminate parking minimums, cap parking near transit, and require EV charging in new development. Her 2024 platform names transportation a top council priority with a pledge to "advocate for creative solutions and funding that are equitable" for vulnerable residents. Requiring multimodal elements on road projects while accepting (not initiating) parking reform matches the invest-equally chair rather than a transit-first parking-reduction agenda or a roads-and-parking-first stance.', ARRAY['https://tualatinlife.com/local-news/opinion-city-prioritizes-tree-preservation-and-pedestrian-safety-along-norwood-road/','https://tualatinlife.com/local-news/tualatin-among-13-cities-suing-oregon-to-halt-new-climate-regulations/','https://hillsboronewstimes.com/2024/09/13/sacco-seeks-second-term-on-tualatin-city-council/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '95368151-cddd-4ac4-924d-4a2a1989daf9'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = '95368151-cddd-4ac4-924d-4a2a1989daf9';
  IF v_ext IS DISTINCT FROM -4174953 THEN
    RAISE EXCEPTION 'UUID 95368151-cddd-4ac4-924d-4a2a1989daf9 does not belong to external_id -4174953 (Christen Sacco) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = '95368151-cddd-4ac4-924d-4a2a1989daf9';
  IF n <> 8 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 8, n;
  END IF;
  -- Context-parity gate (WR-03): the context VALUES list is a verbatim
  -- duplicate of the answers list; count it too so a single-sided edit
  -- cannot silently drop or skew reasoning/sources rows.
  SELECT COUNT(*) INTO n FROM inform.politician_context WHERE politician_id = '95368151-cddd-4ac4-924d-4a2a1989daf9';
  IF n <> 8 THEN
    RAISE EXCEPTION 'Expected % context rows, found % — answers/context VALUES lists diverged', 8, n;
  END IF;
END $$;

COMMIT;
