-- Migration 1174: Bridget Brooks (Council Member Position 3, Tualatin OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 9 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Brooks''s documented housing record centers on enabling more housing — especially affordable and family-sized units — through the city''s planning and permitting machinery. At the February 28, 2022 second vote on the Tualatin Heights rezoning (raising an existing apartment complex from 220 to 336 units), she voted with the 5-1 majority and framed her vote in explicitly pro-housing terms: "This is a code change that is very specific, and I do want to say that for me ''public good'' is having housing opportunities for people in our community." At the May 12, 2021 State of the City she presented Tualatin 2040, the comprehensive plan and development code update "focusing on providing a diversity of housing" alongside the climate action plan. In December 2024, as the 116-unit Plambeck Gardens affordable community came online in a city where 26.8% of residents are severely rent-burdened, she pressed staff on whether Tualatin residents could be prioritized for local affordable housing and services (staff explained legal prioritization is not allowed but outreach was underway). This matches the targeted-help chair — approving affordable projects and easing them through rezonings and planning updates — rather than rent caps/public housing operation or market-only deregulation.', ARRAY['https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/', 'https://tualatinlife.com/featured/state-of-the-city-busy/', 'https://mccmeetings.blob.core.usgovcloudapi.net/tualtnor-pubu/MEET-Packet-15ec587d6bfe4dc8ae561fc58af200fb.pdf']::text[]),
    ('residential-zoning', 3, 'Brooks has repeatedly supported adding multifamily density where it is proposed while working within the city''s established review process. On the contested Tualatin Heights rezoning — a roughly 50% density increase on an existing multifamily site that drew neighborhood opposition over parking and traffic — she voted yes with the 5-1 majority on February 28, 2022, over Council President Nancy Grimes''s dissent, telling the public that "for me ''public good'' is having housing opportunities for people in our community"; her affirmative framing contrasted with colleagues who lamented that state law HB 2001 had constrained local discretion. She also championed the Tualatin 2040 comprehensive plan and development code update aimed at "providing a diversity of housing" (May 12, 2021 State of the City). She has not advocated eliminating single-family zoning citywide or broad by-right upzoning, nor demanded community votes to protect neighborhood character — placing her at the chair that welcomes multifamily and mixed-use in appropriate locations while most residential zones remain protected by the normal code process.', ARRAY['https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/', 'https://tualatinlife.com/local-news/tualatin-city-council-grapples-with-new-zoning-requirements/', 'https://tualatinlife.com/featured/state-of-the-city-busy/']::text[]),
    ('homelessness', 3, 'Brooks joined the unanimous June 26, 2023 Tualatin City Council vote adopting the city''s "time, place, and manner" camping ordinance, which prohibits camping in parks and parking lots and near buildings, schools, and freeways, while designating one city-owned grassy parcel on SW Tualatin Road next to the police station where camping is permitted from 7 p.m. to 7 a.m. in tents up to 12x12 feet. The ordinance was expressly written to comply with the state-law standard that people cannot be punished for sleeping outside when no alternative shelter is available, and Washington County was standing up a shelter-bed availability system with local law enforcement to govern when the rules could be applied. That regulatory design — enforcement conditioned on available alternatives, with a lawful designated option preserved — is precisely the middle chair, not a blanket criminal camping ban and not a protected right to camp anywhere.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://www.tualatinoregon.gov/administration/camping-regulations']::text[]),
    ('homelessness-response', 3, 'Brooks''s documented approach pairs reasonable public-space rules with connecting people to housing and services — consistent with her professional background as a Licensed Clinical Social Worker with a master''s degree in social work. She voted with the unanimous council on June 26, 2023 for the time/place/manner camping ordinance that banned camping in most public places while designating a legal overnight location next to the police station and tying enforcement to Washington County''s shelter-bed availability tracking. At the December 9, 2024 council meeting, as the Plambeck Gardens affordable units opened, she inquired about prioritizing Tualatin residents for housing and services, pushing staff on how locally unhoused and rent-burdened residents would actually be connected to the new resources. That is the invest-in-outreach-shelter-and-services-while-enforcing-reasonable-public-space-rules chair, not enforcement-first minimalism and not housing-first with no enforcement.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://mccmeetings.blob.core.usgovcloudapi.net/tualtnor-pubu/MEET-Packet-15ec587d6bfe4dc8ae561fc58af200fb.pdf', 'https://www.tualatinoregon.gov/administration/camping-regulations']::text[]),
    ('climate-change', 2, 'Brooks is the council''s most consistently documented climate advocate and treats decarbonization as urgent rather than gradual. In September 2022 she was one of three dissenters when the council voted 4-3 to join 13 cities suing Oregon to halt the Climate-Friendly and Equitable Communities rules, saying "I''m not interested in joining a lawsuit. I think the (costs) are going to get multiplied. I think the relationships are going to get strained," and instead declaring "I''m very interested in creative solutions" and that she wanted to "be a change maker on this as an elected official, to represent my constituents that care deeply about this climate crisis." In her August and September 2022 Council Corner columns championing the Climate Action Plan, she warned Tualatin''s days over 90 degrees could rise from 6 to nearly 60 per summer and argued that "by switching to carbon-free electricity and fuels and employing strategies such as carbon sequestration to draw down the greenhouse gasses in the atmosphere, we can avoid the worst effects of climate change." At the April 23, 2025 State of the City she presented the CAP''s net-zero-by-2050 goal and concrete measures (energy capture from water pipes, tree inventory, habitat improvement). Her "climate crisis" framing, advocacy for switching to carbon-free electricity and fuels, and defense of binding state climate mandates against her own city''s litigation best match the rapid-transition chair rather than the gradualist or market-driven chairs.', ARRAY['https://tualatinlife.com/local-news/tualatin-among-13-cities-suing-oregon-to-halt-new-climate-regulations/', 'https://tualatinlife.com/local-news/council-corner-september-2022/', 'https://tualatinlife.com/featured/state-of-the-city-tualatin-is-going-full-steam-ahead/']::text[]),
    ('local-environment', 2, 'Brooks holds development and infrastructure to a strict environmental accounting while still supporting projects that pass it. At the February 22, 2021 council meeting she opposed committing up to $1.45 million of MSTIP funds to right-of-way for the Basalt Creek Parkway extension, saying "It''s very controversial here, it''s very unwelcome by some people and there have been some issues with managing the road buildout," and pointing to flooding, stormwater runoff, dead trees, and fish-passage impacts, including a wetland crossing requiring Army Corps and Oregon DEQ permits. She led Tualatin''s unanimous 2019 certification as a Bee City USA affiliate and wrote in her November 1, 2019 Council Corner that "Becoming a Certified Bee City is a key step in our path to becoming a more sustainable city," tying pollinator habitat to Tualatin''s vision of an "environmentally active and responsible community." At the April 2025 State of the City she highlighted the citywide tree inventory and backyard habitat improvements as climate-plan actions. Because she pairs this strict-protection posture with votes for infill housing (Tualatin Heights), the evidence best fits protecting natural assets and requiring impacts to be fully addressed, rather than blanket pre-approval environmental review of all development or pay-a-fee laxity.', ARRAY['https://tualatinlife.com/featured/basalt-creek-parkway-plan-raises-questions/', 'https://tualatinlife.com/featured/council-corner-whats-the-buzz-bee-city-certification-blooms-in-tualatin/', 'https://tualatinlife.com/featured/state-of-the-city-tualatin-is-going-full-steam-ahead/']::text[]),
    ('civil-rights', 2, 'Brooks has taken affirmative, documented steps on inclusion beyond simply maintaining existing law. In February 2025 she spoke in support of the motion and then voted with the 6-1 majority — over Councilor Octavio Gonzalez''s public dissent, which he defended in a signed opinion column — to proclaim March 31 Transgender Day of Visibility in Tualatin, after roughly a half-dozen community members testified in favor. She serves on the council that established the Inclusion, Diversity, Equity, and Access (IDEA) Advisory Committee in April 2023, a standing body charged with recommending goals and measuring the city''s progress toward greater inclusion, diversity, equity, access, and belonging. Publicly aligning with a contested LGBTQ visibility proclamation and institutionalizing equity measurement in city government matches the actively-address-discrimination chair; she has not proposed mandates or reparations that would indicate the strongest chair.', ARRAY['https://tualatinlife.com/featured/tualatin-to-recognize-transgender-day-of-visibility/', 'https://www.tualatinoregon.gov/idea', 'https://tualatinlife.com/featured/opinion-why-i-voted-against-the-transgender-day-of-visibility-recognition-and-my-broader-approach-to-governance/']::text[]),
    ('transportation-priorities', 2, 'Brooks''s documented transportation record shows resistance to auto-capacity expansion combined with acceptance of state multimodal mandates. At the February 22, 2021 council meeting she strongly opposed allocating up to $1.45 million in MSTIP funds toward right-of-way for the Basalt Creek Parkway extension — a new arterial roadway — calling it "very controversial here... very unwelcome by some people" and citing unresolved flooding, stormwater, and fish-passage problems with the road buildout. In September 2022 she voted against Tualatin joining the 13-city lawsuit to halt the Climate-Friendly and Equitable Communities rules, which eliminate minimum parking requirements for new businesses, limit parking in designated areas, require EV charging in new developments, and mandate walkable design — meaning she was willing to implement parking reform and walkability standards that a majority of her colleagues sued to stop, citing constituents "that care deeply about this climate crisis." She has not called for shifting investment away from roads wholesale, so the evidence best fits balanced investment in roads and multimodal options with new projects held to walkability and environmental standards, rather than a roads-and-parking-first stance.', ARRAY['https://tualatinlife.com/featured/basalt-creek-parkway-plan-raises-questions/', 'https://tualatinlife.com/local-news/tualatin-among-13-cities-suing-oregon-to-halt-new-climate-regulations/']::text[]),
    ('growth-and-development', 3, 'Brooks manages growth through forward planning rather than either growth caps or wholesale deregulation. At the May 12, 2021 State of the City she personally presented Tualatin 2040, the city''s long-range vision including "updates to the comprehensive plan and development code focusing on providing a diversity of housing and a climate action plan" — planning frameworks that shape where and how the nearly built-out city grows. She voted February 28, 2022 to approve the Tualatin Heights infill density increase, showing she supports accommodating growth within existing city fabric. At the same time, on the Basalt Creek growth area she insisted the supporting infrastructure be done right, opposing right-of-way funding for the parkway extension in February 2021 until flooding, stormwater, and environmental problems with "managing the road buildout" were addressed. That combination — proactive comprehensive planning plus insisting infrastructure issues be resolved as expansion proceeds — matches the plan-proactively chair, with no documented support for growth moratoria, voter-approval requirements, or removing regulatory oversight.', ARRAY['https://tualatinlife.com/featured/state-of-the-city-busy/', 'https://tualatinlife.com/featured/basalt-creek-parkway-plan-raises-questions/', 'https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT 'f0f26baf-1de7-408d-8073-219ad6236dc7'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Brooks''s documented housing record centers on enabling more housing — especially affordable and family-sized units — through the city''s planning and permitting machinery. At the February 28, 2022 second vote on the Tualatin Heights rezoning (raising an existing apartment complex from 220 to 336 units), she voted with the 5-1 majority and framed her vote in explicitly pro-housing terms: "This is a code change that is very specific, and I do want to say that for me ''public good'' is having housing opportunities for people in our community." At the May 12, 2021 State of the City she presented Tualatin 2040, the comprehensive plan and development code update "focusing on providing a diversity of housing" alongside the climate action plan. In December 2024, as the 116-unit Plambeck Gardens affordable community came online in a city where 26.8% of residents are severely rent-burdened, she pressed staff on whether Tualatin residents could be prioritized for local affordable housing and services (staff explained legal prioritization is not allowed but outreach was underway). This matches the targeted-help chair — approving affordable projects and easing them through rezonings and planning updates — rather than rent caps/public housing operation or market-only deregulation.', ARRAY['https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/', 'https://tualatinlife.com/featured/state-of-the-city-busy/', 'https://mccmeetings.blob.core.usgovcloudapi.net/tualtnor-pubu/MEET-Packet-15ec587d6bfe4dc8ae561fc58af200fb.pdf']::text[]),
    ('residential-zoning', 3, 'Brooks has repeatedly supported adding multifamily density where it is proposed while working within the city''s established review process. On the contested Tualatin Heights rezoning — a roughly 50% density increase on an existing multifamily site that drew neighborhood opposition over parking and traffic — she voted yes with the 5-1 majority on February 28, 2022, over Council President Nancy Grimes''s dissent, telling the public that "for me ''public good'' is having housing opportunities for people in our community"; her affirmative framing contrasted with colleagues who lamented that state law HB 2001 had constrained local discretion. She also championed the Tualatin 2040 comprehensive plan and development code update aimed at "providing a diversity of housing" (May 12, 2021 State of the City). She has not advocated eliminating single-family zoning citywide or broad by-right upzoning, nor demanded community votes to protect neighborhood character — placing her at the chair that welcomes multifamily and mixed-use in appropriate locations while most residential zones remain protected by the normal code process.', ARRAY['https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/', 'https://tualatinlife.com/local-news/tualatin-city-council-grapples-with-new-zoning-requirements/', 'https://tualatinlife.com/featured/state-of-the-city-busy/']::text[]),
    ('homelessness', 3, 'Brooks joined the unanimous June 26, 2023 Tualatin City Council vote adopting the city''s "time, place, and manner" camping ordinance, which prohibits camping in parks and parking lots and near buildings, schools, and freeways, while designating one city-owned grassy parcel on SW Tualatin Road next to the police station where camping is permitted from 7 p.m. to 7 a.m. in tents up to 12x12 feet. The ordinance was expressly written to comply with the state-law standard that people cannot be punished for sleeping outside when no alternative shelter is available, and Washington County was standing up a shelter-bed availability system with local law enforcement to govern when the rules could be applied. That regulatory design — enforcement conditioned on available alternatives, with a lawful designated option preserved — is precisely the middle chair, not a blanket criminal camping ban and not a protected right to camp anywhere.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://www.tualatinoregon.gov/administration/camping-regulations']::text[]),
    ('homelessness-response', 3, 'Brooks''s documented approach pairs reasonable public-space rules with connecting people to housing and services — consistent with her professional background as a Licensed Clinical Social Worker with a master''s degree in social work. She voted with the unanimous council on June 26, 2023 for the time/place/manner camping ordinance that banned camping in most public places while designating a legal overnight location next to the police station and tying enforcement to Washington County''s shelter-bed availability tracking. At the December 9, 2024 council meeting, as the Plambeck Gardens affordable units opened, she inquired about prioritizing Tualatin residents for housing and services, pushing staff on how locally unhoused and rent-burdened residents would actually be connected to the new resources. That is the invest-in-outreach-shelter-and-services-while-enforcing-reasonable-public-space-rules chair, not enforcement-first minimalism and not housing-first with no enforcement.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://mccmeetings.blob.core.usgovcloudapi.net/tualtnor-pubu/MEET-Packet-15ec587d6bfe4dc8ae561fc58af200fb.pdf', 'https://www.tualatinoregon.gov/administration/camping-regulations']::text[]),
    ('climate-change', 2, 'Brooks is the council''s most consistently documented climate advocate and treats decarbonization as urgent rather than gradual. In September 2022 she was one of three dissenters when the council voted 4-3 to join 13 cities suing Oregon to halt the Climate-Friendly and Equitable Communities rules, saying "I''m not interested in joining a lawsuit. I think the (costs) are going to get multiplied. I think the relationships are going to get strained," and instead declaring "I''m very interested in creative solutions" and that she wanted to "be a change maker on this as an elected official, to represent my constituents that care deeply about this climate crisis." In her August and September 2022 Council Corner columns championing the Climate Action Plan, she warned Tualatin''s days over 90 degrees could rise from 6 to nearly 60 per summer and argued that "by switching to carbon-free electricity and fuels and employing strategies such as carbon sequestration to draw down the greenhouse gasses in the atmosphere, we can avoid the worst effects of climate change." At the April 23, 2025 State of the City she presented the CAP''s net-zero-by-2050 goal and concrete measures (energy capture from water pipes, tree inventory, habitat improvement). Her "climate crisis" framing, advocacy for switching to carbon-free electricity and fuels, and defense of binding state climate mandates against her own city''s litigation best match the rapid-transition chair rather than the gradualist or market-driven chairs.', ARRAY['https://tualatinlife.com/local-news/tualatin-among-13-cities-suing-oregon-to-halt-new-climate-regulations/', 'https://tualatinlife.com/local-news/council-corner-september-2022/', 'https://tualatinlife.com/featured/state-of-the-city-tualatin-is-going-full-steam-ahead/']::text[]),
    ('local-environment', 2, 'Brooks holds development and infrastructure to a strict environmental accounting while still supporting projects that pass it. At the February 22, 2021 council meeting she opposed committing up to $1.45 million of MSTIP funds to right-of-way for the Basalt Creek Parkway extension, saying "It''s very controversial here, it''s very unwelcome by some people and there have been some issues with managing the road buildout," and pointing to flooding, stormwater runoff, dead trees, and fish-passage impacts, including a wetland crossing requiring Army Corps and Oregon DEQ permits. She led Tualatin''s unanimous 2019 certification as a Bee City USA affiliate and wrote in her November 1, 2019 Council Corner that "Becoming a Certified Bee City is a key step in our path to becoming a more sustainable city," tying pollinator habitat to Tualatin''s vision of an "environmentally active and responsible community." At the April 2025 State of the City she highlighted the citywide tree inventory and backyard habitat improvements as climate-plan actions. Because she pairs this strict-protection posture with votes for infill housing (Tualatin Heights), the evidence best fits protecting natural assets and requiring impacts to be fully addressed, rather than blanket pre-approval environmental review of all development or pay-a-fee laxity.', ARRAY['https://tualatinlife.com/featured/basalt-creek-parkway-plan-raises-questions/', 'https://tualatinlife.com/featured/council-corner-whats-the-buzz-bee-city-certification-blooms-in-tualatin/', 'https://tualatinlife.com/featured/state-of-the-city-tualatin-is-going-full-steam-ahead/']::text[]),
    ('civil-rights', 2, 'Brooks has taken affirmative, documented steps on inclusion beyond simply maintaining existing law. In February 2025 she spoke in support of the motion and then voted with the 6-1 majority — over Councilor Octavio Gonzalez''s public dissent, which he defended in a signed opinion column — to proclaim March 31 Transgender Day of Visibility in Tualatin, after roughly a half-dozen community members testified in favor. She serves on the council that established the Inclusion, Diversity, Equity, and Access (IDEA) Advisory Committee in April 2023, a standing body charged with recommending goals and measuring the city''s progress toward greater inclusion, diversity, equity, access, and belonging. Publicly aligning with a contested LGBTQ visibility proclamation and institutionalizing equity measurement in city government matches the actively-address-discrimination chair; she has not proposed mandates or reparations that would indicate the strongest chair.', ARRAY['https://tualatinlife.com/featured/tualatin-to-recognize-transgender-day-of-visibility/', 'https://www.tualatinoregon.gov/idea', 'https://tualatinlife.com/featured/opinion-why-i-voted-against-the-transgender-day-of-visibility-recognition-and-my-broader-approach-to-governance/']::text[]),
    ('transportation-priorities', 2, 'Brooks''s documented transportation record shows resistance to auto-capacity expansion combined with acceptance of state multimodal mandates. At the February 22, 2021 council meeting she strongly opposed allocating up to $1.45 million in MSTIP funds toward right-of-way for the Basalt Creek Parkway extension — a new arterial roadway — calling it "very controversial here... very unwelcome by some people" and citing unresolved flooding, stormwater, and fish-passage problems with the road buildout. In September 2022 she voted against Tualatin joining the 13-city lawsuit to halt the Climate-Friendly and Equitable Communities rules, which eliminate minimum parking requirements for new businesses, limit parking in designated areas, require EV charging in new developments, and mandate walkable design — meaning she was willing to implement parking reform and walkability standards that a majority of her colleagues sued to stop, citing constituents "that care deeply about this climate crisis." She has not called for shifting investment away from roads wholesale, so the evidence best fits balanced investment in roads and multimodal options with new projects held to walkability and environmental standards, rather than a roads-and-parking-first stance.', ARRAY['https://tualatinlife.com/featured/basalt-creek-parkway-plan-raises-questions/', 'https://tualatinlife.com/local-news/tualatin-among-13-cities-suing-oregon-to-halt-new-climate-regulations/']::text[]),
    ('growth-and-development', 3, 'Brooks manages growth through forward planning rather than either growth caps or wholesale deregulation. At the May 12, 2021 State of the City she personally presented Tualatin 2040, the city''s long-range vision including "updates to the comprehensive plan and development code focusing on providing a diversity of housing and a climate action plan" — planning frameworks that shape where and how the nearly built-out city grows. She voted February 28, 2022 to approve the Tualatin Heights infill density increase, showing she supports accommodating growth within existing city fabric. At the same time, on the Basalt Creek growth area she insisted the supporting infrastructure be done right, opposing right-of-way funding for the parkway extension in February 2021 until flooding, stormwater, and environmental problems with "managing the road buildout" were addressed. That combination — proactive comprehensive planning plus insisting infrastructure issues be resolved as expansion proceeds — matches the plan-proactively chair, with no documented support for growth moratoria, voter-approval requirements, or removing regulatory oversight.', ARRAY['https://tualatinlife.com/featured/state-of-the-city-busy/', 'https://tualatinlife.com/featured/basalt-creek-parkway-plan-raises-questions/', 'https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT 'f0f26baf-1de7-408d-8073-219ad6236dc7'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = 'f0f26baf-1de7-408d-8073-219ad6236dc7';
  IF v_ext IS DISTINCT FROM -4174954 THEN
    RAISE EXCEPTION 'UUID f0f26baf-1de7-408d-8073-219ad6236dc7 does not belong to external_id -4174954 (Bridget Brooks) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = 'f0f26baf-1de7-408d-8073-219ad6236dc7';
  IF n <> 9 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 9, n;
  END IF;
  -- Context-parity gate (WR-03): the context VALUES list is a verbatim
  -- duplicate of the answers list; count it too so a single-sided edit
  -- cannot silently drop or skew reasoning/sources rows.
  SELECT COUNT(*) INTO n FROM inform.politician_context WHERE politician_id = 'f0f26baf-1de7-408d-8073-219ad6236dc7';
  IF n <> 9 THEN
    RAISE EXCEPTION 'Expected % context rows, found % — answers/context VALUES lists diverged', 9, n;
  END IF;
END $$;

COMMIT;
