-- Migration 1175: Cyndy Hillier (Council Member Position 4, Tualatin OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 10 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Hillier''s documented housing posture is targeted help — subsidies for affordable projects plus removing permitting barriers. In her October 2024 candidate Q&A she cited that "30% of our Tualatin residents fall into the rent- or mortgage-burdened category. This is around 8,100 people," pointed to the 116-unit Plambeck Gardens affordable development as proof the council is "removing barriers that have added the type of affordable housing needed," and called for "collaborative solutions" involving Metro and Washington County. At the state-required Sept 30, 2024 "Barriers and Solutions to Housing" community meeting she engaged directly on the affordability crisis, noting one-third of Tualatin''s population lives in Clackamas County — a complication for regional housing funding. She also voted with the 5-1 majority on Feb 28, 2022 to approve the Tualatin Heights rezoning enabling roughly 116 additional apartments. Targeted subsidized-project support and barrier removal — not rent caps, city-built public housing, or pure market deregulation — matches the targeted-help chair.', ARRAY['https://www.newsbreak.com/news/3638717425073-candidate-q-a-tualatin-city-council-candidates-talk-economics-housing-and-more', 'https://tualatinlife.com/local-news/officials-discuss-solutions-for-tualatins-affordable-housing-crisis/', 'https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/']::text[]),
    ('homelessness', 3, 'Hillier joined the unanimous June 26, 2023 council vote adopting Tualatin''s "time, place, and manner" camping ordinance, which prohibits camping in parks, parking lots, within 20 feet of buildings and 500 feet of schools and freeways, while designating one city-owned lot next to the police station where overnight camping (7 p.m.-7 a.m.) is permitted. The ordinance was written to comply with the Oregon-law standard that people cannot be punished for sleeping outside when no alternative shelter is available, and city staff framed its goal as transitioning people experiencing unsheltered homelessness into shelter and permanent housing. In her 2024 candidate Q&A Hillier treated homelessness as a systemic regional failure requiring collaborative solutions with Metro and Washington County rather than a pure enforcement problem. Enforcement conditioned on available alternatives, with a designated lawful location and a services-oriented goal, matches the shelter-conditioned enforcement chair rather than blanket criminal bans or a protected right to camp anywhere.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://www.tualatinoregon.gov/administration/camping-regulations', 'https://www.newsbreak.com/news/3638717425073-candidate-q-a-tualatin-city-council-candidates-talk-economics-housing-and-more']::text[]),
    ('homelessness-response', 3, 'Hillier''s citywide strategy pairs services investment with reasonable public-space rules. She voted for the unanimous June 26, 2023 camping ordinance that restricts camping citywide while designating a permitted overnight location by the police station, and her 2024 reelection platform centered on closing service gaps — she named the "crisis of loneliness and lack of mental health services" and proposed a multiuse center housing resource providers and community services as part of her 10-year vision for the city. In her Q&A she framed homelessness and rent burden (about 8,100 Tualatin residents) as problems requiring collaborative solutions with Metro and Washington County, and she cited the 116-unit Plambeck Gardens affordable project among the council''s responses. That is the invest-in-outreach-shelter-and-services-while-enforcing-reasonable-public-space-rules chair, not enforcement-first minimization of services and not housing-first with no enforcement.', ARRAY['https://www.newsbreak.com/news/3638717425073-candidate-q-a-tualatin-city-council-candidates-talk-economics-housing-and-more', 'https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://tualatinlife.com/featured/tualatin-votes-2024-2/']::text[]),
    ('growth-and-development', 3, 'Hillier''s stated top priority for her second term is holistic long-range planning for Basalt Creek growth and downtown core development, with review of codes, ordinances, and zoning to eliminate unintentional barriers — planning proactively so the city shapes growth rather than reacting to it. In her October 2024 Q&A she embraced growth explicitly — "a city that sleeps eventually dies. We must always have an open eye for opportunity" — pointing to the Basalt Creek and downtown urban renewal areas where the city is front-loading infrastructure investment to support expansion. Her 10-year vision describes a thriving core with balanced live-work ratios. Nothing in her record supports growth moratoria or voter-approval gates, nor removing regulatory oversight entirely; she manages growth through long-range planning and infrastructure invested ahead of demand, the plan-proactively chair.', ARRAY['https://tualatinlife.com/featured/tualatin-votes-2024-2/', 'https://www.newsbreak.com/news/3638717425073-candidate-q-a-tualatin-city-council-candidates-talk-economics-housing-and-more', 'https://www.tualatinoregon.gov/economicdevelopment/southwest-and-basalt-creek-development-area']::text[]),
    ('economic-development', 3, 'Hillier supports active but targeted economic development with job-quality strings attached. In her October 2024 candidate Q&A she advocated continued growth — "a city that sleeps eventually dies. We must always have an open eye for opportunity" — and highlighted the two urban renewal (tax-increment) zones the council created during her tenure, Basalt Creek (industrial/employment) and the downtown core, as examples of infrastructure development paired with "clean living wage jobs." Her emphasis is on specific districts and specific industry types with wage quality as the payoff, not maximal incentives for any employer; she has simultaneously prioritized reviewing codes and ordinances to remove unintentional barriers for development in those areas. That matches the targeted-incentives-for-specific-industries-with-job-quality-requirements chair rather than either refusing corporate incentives outright or treating recruitment of any large employer as the city''s top priority.', ARRAY['https://www.newsbreak.com/news/3638717425073-candidate-q-a-tualatin-city-council-candidates-talk-economics-housing-and-more', 'https://www.tualatinoregon.gov/economicdevelopment/southwest-and-basalt-creek-development-area', 'https://tualatinlife.com/featured/tualatin-votes-2024-2/']::text[]),
    ('residential-zoning', 3, 'Hillier''s key documented zoning action is her Feb 28, 2022 vote with the 5-1 majority (Council President Nancy Grimes the lone no) approving the Tualatin Heights rezoning from medium-low to medium-high density, letting an existing apartment property infill from 220 to 336 units — a roughly 50% density increase — after more than four hours of testimony across three meetings; the measure had failed to clear a first-reading unanimity requirement earlier that month, and she voted yes both times. In her 2024 Q&A she credited the council with "removing barriers that have added the type of affordable housing needed" and made zoning-code review to eliminate unintentional barriers part of her second-term platform. Her record is expanding multifamily capacity where multifamily already exists through the normal hearing process — not blanket by-right citywide upzoning, and not strict neighborhood-character protection with community votes — which fits the allow-multifamily-in-appropriate-areas-while-protecting-most-residential-zones chair.', ARRAY['https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/', 'https://tualatinlife.com/local-news/tualatin-city-council-grapples-with-new-zoning-requirements/', 'https://www.newsbreak.com/news/3638717425073-candidate-q-a-tualatin-city-council-candidates-talk-economics-housing-and-more']::text[]),
    ('climate-change', 3, 'Hillier supports gradual, locally-driven clean-energy investment while resisting rapid state mandates. She names the Community Climate Action Plan — adopted by the council in May 2024, a roadmap to citywide net-zero emissions by 2050 through energy efficiency, renewable energy use, more sustainable transportation, and climate resilience — as one of the two first-term accomplishments she is most proud of. Yet in September 2022 she voted with the 4-3 majority to join roughly a dozen Oregon cities suing to halt the state''s Climate-Friendly and Equitable Communities rules, a challenge framed around implementation capacity and compressed deadlines for parking and EV-charging mandates rather than climate denial ("A city the size of ours doesn''t have the staff" to implement so quickly, as the mayor put it); dissenting colleagues preferred spending the money on meeting the climate goals. Championing a 2050 net-zero local plan while litigating against fast state-imposed mandates is the invest-in-clean-energy-while-gradually-transitioning chair, not a 2030 phase-out posture and not rejection of climate policy.', ARRAY['https://tualatinlife.com/featured/tualatin-votes-2024-2/', 'https://tualatinlife.com/local-news/tualatin-among-13-cities-suing-oregon-to-halt-new-climate-regulations/', 'https://tualatinoregon.gov/administration/climate-action/']::text[]),
    ('civil-rights', 2, 'Hillier has taken affirmative documented steps on inclusion beyond simply maintaining existing law. In February 2025 she voted with the 6-1 majority — over Councilor Octavio Gonzalez''s dissent — to proclaim March 31 Transgender Day of Visibility in Tualatin, saying "It''s an onus on all of us to find ways to better educate ourselves, to better support the people that we know and love, and certainly from this position, we should be doing everything we can to make this community better for everyone." She serves as council alternate to the city''s Inclusion, Diversity, Equity, and Access (IDEA) Advisory Committee, the standing body created to recommend and measure the city''s equity progress, and her stated governing philosophy is ensuring all community members feel "seen, heard and represented." Actively institutionalizing and voting for equity and visibility measures over dissent places her at the actively-address-systemic-inequity chair, though she has proposed no mandates or reparations.', ARRAY['https://tualatinlife.com/featured/tualatin-to-recognize-transgender-day-of-visibility/', 'https://www.tualatinoregon.gov/idea', 'https://goodparty.org/candidate/cyndy-hillier/tualatin-city-council-position-4']::text[]),
    ('public-safety-approach', 3, 'Hillier''s public-safety identity is prevention and mental-health capacity layered on top of, not in place of, existing public safety services. A professional prevention specialist (executive director of Tualatin Together since 2014), she campaigned in 2020 on bringing "a prevention lens to the City Council," with a youth center giving young people "a place to gain coping skills and have trusted adults to help guide them" as her top priority, and in 2024 she targeted the "crisis of loneliness and lack of mental health services," envisioning a multiuse center housing resource providers; on election night she described building a community "where we talk about mental health and substance misuse challenges." She sits on the board of the Washington County Consolidated Communications Agency (the county 911 dispatch system) and campaigns on "preserving safety, livability, and community," with no documented proposal to cut or dramatically expand the police budget. Adding prevention, crisis, and mental-health capacity while sustaining current public-safety services matches the keep-funding-while-adding-mental-health-response chair.', ARRAY['https://tualatinlife.com/politics/cyndy-hillier/', 'https://www.youroregonnews.com/news/hillier-leads-in-early-results-in-tualatin-s-only-challenged-council-race/article_f18569c1-614a-5d1a-bad4-26fe6e8a58f9.html', 'https://tualatinlife.com/featured/tualatin-votes-2024-2/']::text[]),
    ('transportation-priorities', 3, 'Hillier treats transportation as a major issue to be solved through regional coordination alongside road maintenance rather than through a mode-ideological program. In her 2024 reelection coverage she identified transportation and the lack of affordable housing as the major issues facing Tualatin, calling them "connected and complicated" problems requiring a coordinated regional solution, and pointed to the council''s work with TriMet and other regional agencies to address transportation. In her 2020 candidate profile she acknowledged traffic congestion and I-205 tolling as "important matters" requiring ongoing council attention regardless of who serves. Her record — congestion and safety concern, selective transit coordination through TriMet, no documented push to reduce parking citywide or to prioritize highways over other modes — best matches the maintain-roads-while-selectively-adding-transit-and-pedestrian-improvements chair.', ARRAY['https://www.forestgrovenewstimes.com/news/hillier-seeks-reelection-in-tualatins-only-challenged-council-race/article_65a905ff-01ed-50e7-87f0-3542da2a0fca.html', 'https://tualatinlife.com/politics/cyndy-hillier/', 'https://www.newsbreak.com/news/3638717425073-candidate-q-a-tualatin-city-council-candidates-talk-economics-housing-and-more']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '2c2c74d5-017d-4889-9fad-907f0f556271'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Hillier''s documented housing posture is targeted help — subsidies for affordable projects plus removing permitting barriers. In her October 2024 candidate Q&A she cited that "30% of our Tualatin residents fall into the rent- or mortgage-burdened category. This is around 8,100 people," pointed to the 116-unit Plambeck Gardens affordable development as proof the council is "removing barriers that have added the type of affordable housing needed," and called for "collaborative solutions" involving Metro and Washington County. At the state-required Sept 30, 2024 "Barriers and Solutions to Housing" community meeting she engaged directly on the affordability crisis, noting one-third of Tualatin''s population lives in Clackamas County — a complication for regional housing funding. She also voted with the 5-1 majority on Feb 28, 2022 to approve the Tualatin Heights rezoning enabling roughly 116 additional apartments. Targeted subsidized-project support and barrier removal — not rent caps, city-built public housing, or pure market deregulation — matches the targeted-help chair.', ARRAY['https://www.newsbreak.com/news/3638717425073-candidate-q-a-tualatin-city-council-candidates-talk-economics-housing-and-more', 'https://tualatinlife.com/local-news/officials-discuss-solutions-for-tualatins-affordable-housing-crisis/', 'https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/']::text[]),
    ('homelessness', 3, 'Hillier joined the unanimous June 26, 2023 council vote adopting Tualatin''s "time, place, and manner" camping ordinance, which prohibits camping in parks, parking lots, within 20 feet of buildings and 500 feet of schools and freeways, while designating one city-owned lot next to the police station where overnight camping (7 p.m.-7 a.m.) is permitted. The ordinance was written to comply with the Oregon-law standard that people cannot be punished for sleeping outside when no alternative shelter is available, and city staff framed its goal as transitioning people experiencing unsheltered homelessness into shelter and permanent housing. In her 2024 candidate Q&A Hillier treated homelessness as a systemic regional failure requiring collaborative solutions with Metro and Washington County rather than a pure enforcement problem. Enforcement conditioned on available alternatives, with a designated lawful location and a services-oriented goal, matches the shelter-conditioned enforcement chair rather than blanket criminal bans or a protected right to camp anywhere.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://www.tualatinoregon.gov/administration/camping-regulations', 'https://www.newsbreak.com/news/3638717425073-candidate-q-a-tualatin-city-council-candidates-talk-economics-housing-and-more']::text[]),
    ('homelessness-response', 3, 'Hillier''s citywide strategy pairs services investment with reasonable public-space rules. She voted for the unanimous June 26, 2023 camping ordinance that restricts camping citywide while designating a permitted overnight location by the police station, and her 2024 reelection platform centered on closing service gaps — she named the "crisis of loneliness and lack of mental health services" and proposed a multiuse center housing resource providers and community services as part of her 10-year vision for the city. In her Q&A she framed homelessness and rent burden (about 8,100 Tualatin residents) as problems requiring collaborative solutions with Metro and Washington County, and she cited the 116-unit Plambeck Gardens affordable project among the council''s responses. That is the invest-in-outreach-shelter-and-services-while-enforcing-reasonable-public-space-rules chair, not enforcement-first minimization of services and not housing-first with no enforcement.', ARRAY['https://www.newsbreak.com/news/3638717425073-candidate-q-a-tualatin-city-council-candidates-talk-economics-housing-and-more', 'https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://tualatinlife.com/featured/tualatin-votes-2024-2/']::text[]),
    ('growth-and-development', 3, 'Hillier''s stated top priority for her second term is holistic long-range planning for Basalt Creek growth and downtown core development, with review of codes, ordinances, and zoning to eliminate unintentional barriers — planning proactively so the city shapes growth rather than reacting to it. In her October 2024 Q&A she embraced growth explicitly — "a city that sleeps eventually dies. We must always have an open eye for opportunity" — pointing to the Basalt Creek and downtown urban renewal areas where the city is front-loading infrastructure investment to support expansion. Her 10-year vision describes a thriving core with balanced live-work ratios. Nothing in her record supports growth moratoria or voter-approval gates, nor removing regulatory oversight entirely; she manages growth through long-range planning and infrastructure invested ahead of demand, the plan-proactively chair.', ARRAY['https://tualatinlife.com/featured/tualatin-votes-2024-2/', 'https://www.newsbreak.com/news/3638717425073-candidate-q-a-tualatin-city-council-candidates-talk-economics-housing-and-more', 'https://www.tualatinoregon.gov/economicdevelopment/southwest-and-basalt-creek-development-area']::text[]),
    ('economic-development', 3, 'Hillier supports active but targeted economic development with job-quality strings attached. In her October 2024 candidate Q&A she advocated continued growth — "a city that sleeps eventually dies. We must always have an open eye for opportunity" — and highlighted the two urban renewal (tax-increment) zones the council created during her tenure, Basalt Creek (industrial/employment) and the downtown core, as examples of infrastructure development paired with "clean living wage jobs." Her emphasis is on specific districts and specific industry types with wage quality as the payoff, not maximal incentives for any employer; she has simultaneously prioritized reviewing codes and ordinances to remove unintentional barriers for development in those areas. That matches the targeted-incentives-for-specific-industries-with-job-quality-requirements chair rather than either refusing corporate incentives outright or treating recruitment of any large employer as the city''s top priority.', ARRAY['https://www.newsbreak.com/news/3638717425073-candidate-q-a-tualatin-city-council-candidates-talk-economics-housing-and-more', 'https://www.tualatinoregon.gov/economicdevelopment/southwest-and-basalt-creek-development-area', 'https://tualatinlife.com/featured/tualatin-votes-2024-2/']::text[]),
    ('residential-zoning', 3, 'Hillier''s key documented zoning action is her Feb 28, 2022 vote with the 5-1 majority (Council President Nancy Grimes the lone no) approving the Tualatin Heights rezoning from medium-low to medium-high density, letting an existing apartment property infill from 220 to 336 units — a roughly 50% density increase — after more than four hours of testimony across three meetings; the measure had failed to clear a first-reading unanimity requirement earlier that month, and she voted yes both times. In her 2024 Q&A she credited the council with "removing barriers that have added the type of affordable housing needed" and made zoning-code review to eliminate unintentional barriers part of her second-term platform. Her record is expanding multifamily capacity where multifamily already exists through the normal hearing process — not blanket by-right citywide upzoning, and not strict neighborhood-character protection with community votes — which fits the allow-multifamily-in-appropriate-areas-while-protecting-most-residential-zones chair.', ARRAY['https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/', 'https://tualatinlife.com/local-news/tualatin-city-council-grapples-with-new-zoning-requirements/', 'https://www.newsbreak.com/news/3638717425073-candidate-q-a-tualatin-city-council-candidates-talk-economics-housing-and-more']::text[]),
    ('climate-change', 3, 'Hillier supports gradual, locally-driven clean-energy investment while resisting rapid state mandates. She names the Community Climate Action Plan — adopted by the council in May 2024, a roadmap to citywide net-zero emissions by 2050 through energy efficiency, renewable energy use, more sustainable transportation, and climate resilience — as one of the two first-term accomplishments she is most proud of. Yet in September 2022 she voted with the 4-3 majority to join roughly a dozen Oregon cities suing to halt the state''s Climate-Friendly and Equitable Communities rules, a challenge framed around implementation capacity and compressed deadlines for parking and EV-charging mandates rather than climate denial ("A city the size of ours doesn''t have the staff" to implement so quickly, as the mayor put it); dissenting colleagues preferred spending the money on meeting the climate goals. Championing a 2050 net-zero local plan while litigating against fast state-imposed mandates is the invest-in-clean-energy-while-gradually-transitioning chair, not a 2030 phase-out posture and not rejection of climate policy.', ARRAY['https://tualatinlife.com/featured/tualatin-votes-2024-2/', 'https://tualatinlife.com/local-news/tualatin-among-13-cities-suing-oregon-to-halt-new-climate-regulations/', 'https://tualatinoregon.gov/administration/climate-action/']::text[]),
    ('civil-rights', 2, 'Hillier has taken affirmative documented steps on inclusion beyond simply maintaining existing law. In February 2025 she voted with the 6-1 majority — over Councilor Octavio Gonzalez''s dissent — to proclaim March 31 Transgender Day of Visibility in Tualatin, saying "It''s an onus on all of us to find ways to better educate ourselves, to better support the people that we know and love, and certainly from this position, we should be doing everything we can to make this community better for everyone." She serves as council alternate to the city''s Inclusion, Diversity, Equity, and Access (IDEA) Advisory Committee, the standing body created to recommend and measure the city''s equity progress, and her stated governing philosophy is ensuring all community members feel "seen, heard and represented." Actively institutionalizing and voting for equity and visibility measures over dissent places her at the actively-address-systemic-inequity chair, though she has proposed no mandates or reparations.', ARRAY['https://tualatinlife.com/featured/tualatin-to-recognize-transgender-day-of-visibility/', 'https://www.tualatinoregon.gov/idea', 'https://goodparty.org/candidate/cyndy-hillier/tualatin-city-council-position-4']::text[]),
    ('public-safety-approach', 3, 'Hillier''s public-safety identity is prevention and mental-health capacity layered on top of, not in place of, existing public safety services. A professional prevention specialist (executive director of Tualatin Together since 2014), she campaigned in 2020 on bringing "a prevention lens to the City Council," with a youth center giving young people "a place to gain coping skills and have trusted adults to help guide them" as her top priority, and in 2024 she targeted the "crisis of loneliness and lack of mental health services," envisioning a multiuse center housing resource providers; on election night she described building a community "where we talk about mental health and substance misuse challenges." She sits on the board of the Washington County Consolidated Communications Agency (the county 911 dispatch system) and campaigns on "preserving safety, livability, and community," with no documented proposal to cut or dramatically expand the police budget. Adding prevention, crisis, and mental-health capacity while sustaining current public-safety services matches the keep-funding-while-adding-mental-health-response chair.', ARRAY['https://tualatinlife.com/politics/cyndy-hillier/', 'https://www.youroregonnews.com/news/hillier-leads-in-early-results-in-tualatin-s-only-challenged-council-race/article_f18569c1-614a-5d1a-bad4-26fe6e8a58f9.html', 'https://tualatinlife.com/featured/tualatin-votes-2024-2/']::text[]),
    ('transportation-priorities', 3, 'Hillier treats transportation as a major issue to be solved through regional coordination alongside road maintenance rather than through a mode-ideological program. In her 2024 reelection coverage she identified transportation and the lack of affordable housing as the major issues facing Tualatin, calling them "connected and complicated" problems requiring a coordinated regional solution, and pointed to the council''s work with TriMet and other regional agencies to address transportation. In her 2020 candidate profile she acknowledged traffic congestion and I-205 tolling as "important matters" requiring ongoing council attention regardless of who serves. Her record — congestion and safety concern, selective transit coordination through TriMet, no documented push to reduce parking citywide or to prioritize highways over other modes — best matches the maintain-roads-while-selectively-adding-transit-and-pedestrian-improvements chair.', ARRAY['https://www.forestgrovenewstimes.com/news/hillier-seeks-reelection-in-tualatins-only-challenged-council-race/article_65a905ff-01ed-50e7-87f0-3542da2a0fca.html', 'https://tualatinlife.com/politics/cyndy-hillier/', 'https://www.newsbreak.com/news/3638717425073-candidate-q-a-tualatin-city-council-candidates-talk-economics-housing-and-more']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '2c2c74d5-017d-4889-9fad-907f0f556271'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = '2c2c74d5-017d-4889-9fad-907f0f556271';
  IF v_ext IS DISTINCT FROM -4174955 THEN
    RAISE EXCEPTION 'UUID 2c2c74d5-017d-4889-9fad-907f0f556271 does not belong to external_id -4174955 (Cyndy Hillier) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = '2c2c74d5-017d-4889-9fad-907f0f556271';
  IF n <> 10 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 10, n;
  END IF;
  -- Context-parity gate (WR-03): the context VALUES list is a verbatim
  -- duplicate of the answers list; count it too so a single-sided edit
  -- cannot silently drop or skew reasoning/sources rows.
  SELECT COUNT(*) INTO n FROM inform.politician_context WHERE politician_id = '2c2c74d5-017d-4889-9fad-907f0f556271';
  IF n <> 10 THEN
    RAISE EXCEPTION 'Expected % context rows, found % — answers/context VALUES lists diverged', 10, n;
  END IF;
END $$;

COMMIT;
