-- Migration 1176: Octavio Gonzalez (Council Member Position 5, Tualatin OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 7 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('civil-rights', 4, 'Gonzalez cast the lone dissenting vote when the Tualatin City Council proclaimed March 31 Transgender Day of Visibility in February 2025 (6-1), and in a March 22, 2025 op-ed explained: "I voted against recognizing Transgender Day of Visibility because I believe in the biological distinction between males and females," adding that "local governments should not promote social ideologies" and framing the vote as against government overreach rather than against individuals. In the same piece he opposed DEI initiatives, writing "I believe in earning my place based on merit, not racial quotas. True inclusion comes from equal opportunity," and argued government "should stay focused on essential services" — public safety, infrastructure, and economic growth. This record of voting against inclusion proclamations and opposing government equity/DEI programming, while still endorsing equal opportunity, best matches the chair confining government civil-rights activity to clear cases of discrimination — not the proactive-equity chairs he dissents from, and not a documented call to eliminate every race-conscious program at all levels.', ARRAY['https://tualatinlife.com/featured/opinion-why-i-voted-against-the-transgender-day-of-visibility-recognition-and-my-broader-approach-to-governance/', 'https://tualatinlife.com/featured/tualatin-to-recognize-transgender-day-of-visibility/']::text[]),
    ('climate-change', 4, 'In his March 2025 op-ed Gonzalez disclosed his dissent from the city''s May 2024 Community Climate Action Plan — the roadmap to citywide net-zero emissions by 2050 — writing "I voted against Tualatin''s Climate Action Plan because I believe climate efforts should be addressed locally, rather than dictated by a federal bureaucracy." He pairs that with blanket opposition to new public costs: "I consistently vote against tax and utility increases to ease financial burdens on residents," positioning him against ratepayer-funded climate programs such as the city''s subsequent Pennies for Climate Action utility-bill charge (implemented January 2026). He does not reject climate action outright — his stated preference is locally tailored, low-cost measures rather than plan-driven mandates and charges. Voting against the city''s clean-energy investment roadmap while favoring local, unmandated approaches matches the let-market-forces-drive-the-transition chair rather than the invest-in-clean-energy chair or outright rejection of climate policy.', ARRAY['https://tualatinlife.com/featured/opinion-why-i-voted-against-the-transgender-day-of-visibility-recognition-and-my-broader-approach-to-governance/', 'https://tualatinoregon.gov/administration/climate-action/', 'https://valleytimes.news/2026/01/07/pennies-for-climate-action-tualatin-implements-optional-charge-to-mitigate-climate-change/']::text[]),
    ('taxes', 4, 'Gonzalez''s stated fiscal doctrine is that "government should stay focused on essential services, not impose ideological or financial burdens," and that "I consistently vote against tax and utility increases to ease financial burdens on residents" (March 2025 op-ed). As a 2022 candidate he pledged to "oppose any action that increases living costs" and blamed "burdensome taxes, regulations, and shutdowns" for harming small businesses. In April 2025 he publicly campaigned against the Tigard-Tualatin School District''s Measure 34-342 bond, writing "Now is not the time to approve a new bond. It''s time to ask tough questions," arguing the district''s general fund had grown to record levels while resources were misallocated toward "ideological programming." Consistent, across-the-board opposition to revenue increases paired with an essential-services-only view of government matches the lower-the-burden-and-scale-services-back chair rather than status-quo maintenance with small adjustments.', ARRAY['https://tualatinlife.com/featured/opinion-why-i-voted-against-the-transgender-day-of-visibility-recognition-and-my-broader-approach-to-governance/', 'https://tualatinlife.com/local-news/opinion-why-im-voting-no-on-measure-34-342-and-why-you-should-too/', 'https://tualatinlife.com/politics/octavio-gonzales-is-running-for-tualatin-city-council/']::text[]),
    ('homelessness', 3, 'Gonzalez joined the unanimous June 26, 2023 council vote adopting Tualatin''s "time, place, and manner" camping ordinance (Ordinance 1475-23), which prohibits camping in city parks, parking lots, within 20 feet of buildings and 500 feet of freeways and schools, while designating a single city-owned parcel next to the police station where overnight camping is permitted 7 p.m.-7 a.m. The ordinance was expressly structured to comply with the Oregon-law standard that people cannot be punished for sleeping outside when no alternative shelter is available, with Washington County building a shelter-bed availability system for law enforcement to guide its application. Reducing "home insecurity and homelessness" was also among his stated reasons for seeking office in 2022. Voting for regulated enforcement conditioned on lawful alternatives and a designated camping location matches the enforcement-only-when-shelter-is-available chair rather than a blanket criminal ban or a protected right to camp anywhere.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://www.tualatinoregon.gov/administration/camping-regulations', 'https://tualatinlife.com/politics/octavio-gonzalez-is-only-new-member-on-city-council/']::text[]),
    ('public-safety-approach', 4, 'Crime was the first item on Gonzalez''s stated list of reasons for running in 2022: he said "safety and security in our neighborhood are a priority" and that he "supports law enforcement and will work to make sure it has what it needs to keep the streets safe." In his March 2025 op-ed he identified public safety — alongside infrastructure and economic growth — as what municipalities should prioritize instead of "ideological or financial burdens," and his regional assignments include serving as alternate on the Washington County Consolidated Communications Agency (911) board. He has never proposed shifting police funding toward co-responder or social-service models; his documented posture is to resource law enforcement fully as a core city function. That safety-first, give-police-what-they-need position matches the increase-police-resourcing chair better than the budget-neutral crisis-team chair or any reallocation chair.', ARRAY['https://tualatinlife.com/politics/octavio-gonzales-is-running-for-tualatin-city-council/', 'https://tualatinlife.com/featured/opinion-why-i-voted-against-the-transgender-day-of-visibility-recognition-and-my-broader-approach-to-governance/', 'https://tualatinoregon.gov/city-council/']::text[]),
    ('residential-zoning', 2, 'Shortly after being sworn in (January 2023), Gonzalez expressed interest in implementing Oregon''s "middle housing" policies — the state framework legalizing duplexes and other modest density increases in single-family neighborhoods — and as a candidate he argued "housing regulations need to be updated to reflect changing needs of the community and multi-generational families." His platform paired "safe neighborhoods and housing opportunities" with reducing home insecurity, grounding the density interest in family and neighborhood needs rather than developer throughput. He has not advocated broad by-right upzoning, eliminating single-family-only zoning citywide, or growth-freeze protections requiring community votes. Supporting modest, family-oriented density increases delivered through updated local regulations best matches the modest-density-with-neighborhood-input chair.', ARRAY['https://tualatinlife.com/politics/octavio-gonzalez-is-only-new-member-on-city-council/', 'https://tualatinlife.com/politics/octavio-gonzales-is-running-for-tualatin-city-council/']::text[]),
    ('transportation-priorities', 2, 'At the June 2024 State of the City, Councilor Gonzalez presented the city''s Tualatin Moving Forward program — the voter-approved $20 million transportation bond — describing its projects as providing "congestion relief, neighborhood safety, and safe access to schools and parks" and noting residents can request small neighborhood projects; he also presented the city''s five-year Capital Improvement Plan for infrastructure and facilities. The program he promoted deliberately splits its investment between road congestion relief and pedestrian/safe-routes-to-school infrastructure, and his 2022 campaign emphasis on safe neighborhoods aligns with its neighborhood traffic-safety strand. Publicly championing this balanced roads-plus-walking investment portfolio matches the invest-equally-in-roads-and-multimodal-options chair rather than a transit-first/parking-reduction agenda or a roads-and-parking-only stance.', ARRAY['https://tualatinlife.com/local-news/state-of-the-city-tualatin-was-busy-in-2023/', 'https://www.tualatinmovingforward.com/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '9ac04511-d092-4c6c-becb-4bd333b0999d'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('civil-rights', 4, 'Gonzalez cast the lone dissenting vote when the Tualatin City Council proclaimed March 31 Transgender Day of Visibility in February 2025 (6-1), and in a March 22, 2025 op-ed explained: "I voted against recognizing Transgender Day of Visibility because I believe in the biological distinction between males and females," adding that "local governments should not promote social ideologies" and framing the vote as against government overreach rather than against individuals. In the same piece he opposed DEI initiatives, writing "I believe in earning my place based on merit, not racial quotas. True inclusion comes from equal opportunity," and argued government "should stay focused on essential services" — public safety, infrastructure, and economic growth. This record of voting against inclusion proclamations and opposing government equity/DEI programming, while still endorsing equal opportunity, best matches the chair confining government civil-rights activity to clear cases of discrimination — not the proactive-equity chairs he dissents from, and not a documented call to eliminate every race-conscious program at all levels.', ARRAY['https://tualatinlife.com/featured/opinion-why-i-voted-against-the-transgender-day-of-visibility-recognition-and-my-broader-approach-to-governance/', 'https://tualatinlife.com/featured/tualatin-to-recognize-transgender-day-of-visibility/']::text[]),
    ('climate-change', 4, 'In his March 2025 op-ed Gonzalez disclosed his dissent from the city''s May 2024 Community Climate Action Plan — the roadmap to citywide net-zero emissions by 2050 — writing "I voted against Tualatin''s Climate Action Plan because I believe climate efforts should be addressed locally, rather than dictated by a federal bureaucracy." He pairs that with blanket opposition to new public costs: "I consistently vote against tax and utility increases to ease financial burdens on residents," positioning him against ratepayer-funded climate programs such as the city''s subsequent Pennies for Climate Action utility-bill charge (implemented January 2026). He does not reject climate action outright — his stated preference is locally tailored, low-cost measures rather than plan-driven mandates and charges. Voting against the city''s clean-energy investment roadmap while favoring local, unmandated approaches matches the let-market-forces-drive-the-transition chair rather than the invest-in-clean-energy chair or outright rejection of climate policy.', ARRAY['https://tualatinlife.com/featured/opinion-why-i-voted-against-the-transgender-day-of-visibility-recognition-and-my-broader-approach-to-governance/', 'https://tualatinoregon.gov/administration/climate-action/', 'https://valleytimes.news/2026/01/07/pennies-for-climate-action-tualatin-implements-optional-charge-to-mitigate-climate-change/']::text[]),
    ('taxes', 4, 'Gonzalez''s stated fiscal doctrine is that "government should stay focused on essential services, not impose ideological or financial burdens," and that "I consistently vote against tax and utility increases to ease financial burdens on residents" (March 2025 op-ed). As a 2022 candidate he pledged to "oppose any action that increases living costs" and blamed "burdensome taxes, regulations, and shutdowns" for harming small businesses. In April 2025 he publicly campaigned against the Tigard-Tualatin School District''s Measure 34-342 bond, writing "Now is not the time to approve a new bond. It''s time to ask tough questions," arguing the district''s general fund had grown to record levels while resources were misallocated toward "ideological programming." Consistent, across-the-board opposition to revenue increases paired with an essential-services-only view of government matches the lower-the-burden-and-scale-services-back chair rather than status-quo maintenance with small adjustments.', ARRAY['https://tualatinlife.com/featured/opinion-why-i-voted-against-the-transgender-day-of-visibility-recognition-and-my-broader-approach-to-governance/', 'https://tualatinlife.com/local-news/opinion-why-im-voting-no-on-measure-34-342-and-why-you-should-too/', 'https://tualatinlife.com/politics/octavio-gonzales-is-running-for-tualatin-city-council/']::text[]),
    ('homelessness', 3, 'Gonzalez joined the unanimous June 26, 2023 council vote adopting Tualatin''s "time, place, and manner" camping ordinance (Ordinance 1475-23), which prohibits camping in city parks, parking lots, within 20 feet of buildings and 500 feet of freeways and schools, while designating a single city-owned parcel next to the police station where overnight camping is permitted 7 p.m.-7 a.m. The ordinance was expressly structured to comply with the Oregon-law standard that people cannot be punished for sleeping outside when no alternative shelter is available, with Washington County building a shelter-bed availability system for law enforcement to guide its application. Reducing "home insecurity and homelessness" was also among his stated reasons for seeking office in 2022. Voting for regulated enforcement conditioned on lawful alternatives and a designated camping location matches the enforcement-only-when-shelter-is-available chair rather than a blanket criminal ban or a protected right to camp anywhere.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://www.tualatinoregon.gov/administration/camping-regulations', 'https://tualatinlife.com/politics/octavio-gonzalez-is-only-new-member-on-city-council/']::text[]),
    ('public-safety-approach', 4, 'Crime was the first item on Gonzalez''s stated list of reasons for running in 2022: he said "safety and security in our neighborhood are a priority" and that he "supports law enforcement and will work to make sure it has what it needs to keep the streets safe." In his March 2025 op-ed he identified public safety — alongside infrastructure and economic growth — as what municipalities should prioritize instead of "ideological or financial burdens," and his regional assignments include serving as alternate on the Washington County Consolidated Communications Agency (911) board. He has never proposed shifting police funding toward co-responder or social-service models; his documented posture is to resource law enforcement fully as a core city function. That safety-first, give-police-what-they-need position matches the increase-police-resourcing chair better than the budget-neutral crisis-team chair or any reallocation chair.', ARRAY['https://tualatinlife.com/politics/octavio-gonzales-is-running-for-tualatin-city-council/', 'https://tualatinlife.com/featured/opinion-why-i-voted-against-the-transgender-day-of-visibility-recognition-and-my-broader-approach-to-governance/', 'https://tualatinoregon.gov/city-council/']::text[]),
    ('residential-zoning', 2, 'Shortly after being sworn in (January 2023), Gonzalez expressed interest in implementing Oregon''s "middle housing" policies — the state framework legalizing duplexes and other modest density increases in single-family neighborhoods — and as a candidate he argued "housing regulations need to be updated to reflect changing needs of the community and multi-generational families." His platform paired "safe neighborhoods and housing opportunities" with reducing home insecurity, grounding the density interest in family and neighborhood needs rather than developer throughput. He has not advocated broad by-right upzoning, eliminating single-family-only zoning citywide, or growth-freeze protections requiring community votes. Supporting modest, family-oriented density increases delivered through updated local regulations best matches the modest-density-with-neighborhood-input chair.', ARRAY['https://tualatinlife.com/politics/octavio-gonzalez-is-only-new-member-on-city-council/', 'https://tualatinlife.com/politics/octavio-gonzales-is-running-for-tualatin-city-council/']::text[]),
    ('transportation-priorities', 2, 'At the June 2024 State of the City, Councilor Gonzalez presented the city''s Tualatin Moving Forward program — the voter-approved $20 million transportation bond — describing its projects as providing "congestion relief, neighborhood safety, and safe access to schools and parks" and noting residents can request small neighborhood projects; he also presented the city''s five-year Capital Improvement Plan for infrastructure and facilities. The program he promoted deliberately splits its investment between road congestion relief and pedestrian/safe-routes-to-school infrastructure, and his 2022 campaign emphasis on safe neighborhoods aligns with its neighborhood traffic-safety strand. Publicly championing this balanced roads-plus-walking investment portfolio matches the invest-equally-in-roads-and-multimodal-options chair rather than a transit-first/parking-reduction agenda or a roads-and-parking-only stance.', ARRAY['https://tualatinlife.com/local-news/state-of-the-city-tualatin-was-busy-in-2023/', 'https://www.tualatinmovingforward.com/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '9ac04511-d092-4c6c-becb-4bd333b0999d'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = '9ac04511-d092-4c6c-becb-4bd333b0999d';
  IF v_ext IS DISTINCT FROM -4174956 THEN
    RAISE EXCEPTION 'UUID 9ac04511-d092-4c6c-becb-4bd333b0999d does not belong to external_id -4174956 (Octavio Gonzalez) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = '9ac04511-d092-4c6c-becb-4bd333b0999d';
  IF n <> 7 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 7, n;
  END IF;
  -- Context-parity gate (WR-03): the context VALUES list is a verbatim
  -- duplicate of the answers list; count it too so a single-sided edit
  -- cannot silently drop or skew reasoning/sources rows.
  SELECT COUNT(*) INTO n FROM inform.politician_context WHERE politician_id = '9ac04511-d092-4c6c-becb-4bd333b0999d';
  IF n <> 7 THEN
    RAISE EXCEPTION 'Expected % context rows, found % — answers/context VALUES lists diverged', 7, n;
  END IF;
END $$;

COMMIT;
