-- Migration 1177: Valerie Pratt (Council Member Position 6 / Council President, Tualatin OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 9 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Pratt''s consistent through-line is increasing housing supply with targeted city tools: at the Feb 28, 2022 Tualatin Heights hearing she voted with the 5-1 majority to rezone an existing apartment complex from 220 to 336 units, explaining "All of these issues are in the public interest but to me, housing is the bottom line, most important issue." In April 18, 2025 written testimony to the Oregon House Rules Committee opposing HB 3499 (which would have required general-election votes for urban renewal plans), she wrote as Council President that "Oregon is in the midst of a severe housing crisis and it is vital that everything possible is done to avoid impeding the ability to increase the state''s housing inventory," citing Tualatin''s shortage of 4,300 housing units and the "over 400 housing units" added through the Basalt Creek Urban Renewal District, with more housing planned in the Core Area district. In her 2020 candidate statement she named "providing housing, so those who work here can also afford to live here" as a strategy. Public tax-increment funding to enable housing projects plus rezoning approvals matches the targeted-help chair (subsidies for projects, easier building) rather than rent caps/public housing or leaving housing to the market.', ARRAY['https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/', 'https://olis.oregonlegislature.gov/liz/2025R1/Downloads/PublicTestimonyDocument/196481', 'https://tualatinlife.com/politics/valerie-pratt/']::text[]),
    ('residential-zoning', 3, 'Pratt''s documented zoning record supports substantial multifamily density where it already fits: she voted with the 5-1 majority on Feb 28, 2022 to approve the Tualatin Heights rezoning, a roughly 50% density increase (220 to 336 units) at an existing apartment site, telling neighbors who raised traffic, parking, and livability objections that "All of these issues are in the public interest but to me, housing is the bottom line, most important issue." In her 2020 candidate Q&A she acknowledged that Oregon HB 2001''s housing infill requirements would increase traffic congestion but answered with housing supply — "providing housing, so those who work here can also afford to live here" — rather than resistance to density. Her 2025 legislative testimony backs adding more housing through the downtown Core Area Urban Renewal District, i.e., density concentrated in the commercial core. That fits allowing multifamily and mixed-use near corridors while keeping most residential zones intact, rather than restricting change to modest duplex-scale infill or demanding community votes before rezoning.', ARRAY['https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/', 'https://tualatinlife.com/politics/valerie-pratt/', 'https://olis.oregonlegislature.gov/liz/2025R1/Downloads/PublicTestimonyDocument/196481']::text[]),
    ('homelessness', 3, 'Pratt joined the unanimous June 26, 2023 council vote adopting Tualatin''s "time, place, and manner" camping ordinance, which prohibits camping in parks, city parking lots, within 20 feet of buildings and 500 feet of schools and freeway ramps, while designating one city-owned lot next to the police station where overnight camping (7 p.m.-7 a.m.) is permitted. The city''s own regulations page states the rules were "adopted in 2023 to comply with state and federal laws" and that they "allow for outdoor camping on public property when an individual is without available shelter and when specific time, place, and manner regulations are followed" — i.e., enforcement is expressly conditioned on the availability of alternatives, consistent with Oregon''s statutory standard. This regulated-but-not-criminalized framework, pairing location/hour limits with a lawful place to sleep when no shelter exists, matches the chair allowing enforcement only when adequate alternatives are available with diversion toward services rather than blanket criminal bans or an unrestricted right to camp.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://tualatinoregon.gov/administration/homelessness/camping-regulations/']::text[]),
    ('homelessness-response', 3, 'Pratt''s citywide strategy pairs reasonable public-space rules with services and behavioral-health capacity: she voted for the unanimous June 26, 2023 camping ordinance that limits camping to a designated lot near the police station between 7 p.m. and 7 a.m. while leaving camping lawful when a person is without available shelter, and the city administers the regulations within its broader homelessness program. In her September 2024 reelection interview she named mental health services — alongside transportation and housing — as one of the three key challenges facing Tualatin, and her housing record (the Tualatin Heights rezoning vote and urban renewal districts she credits with adding over 400 housing units) treats supply as part of the response. Nothing in her record supports enforcement-first crackdowns or minimizing city spending on services, nor a no-enforcement housing-first-only posture; the documented mix is outreach-and-services investment alongside enforceable public-space rules.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://beavertonvalleytimes.com/2024/09/13/pratt-seeks-second-term-on-tualatin-city-council/', 'https://tualatinoregon.gov/administration/homelessness/camping-regulations/']::text[]),
    ('climate-change', 3, 'Pratt cast one of the three dissenting votes (with Councilors Brooks and Sacco) when the council voted 4-3 in September 2022 to join thirteen local governments suing to pause Oregon''s Climate Friendly and Equitable Communities rules, stating "My decision is based on what I think is best for the climate" and arguing the city''s resources were better spent meeting climate goals than litigating against them. In her September 2024 reelection interview she listed "implementing Tualatin''s Climate Action Plan" — the council-adopted May 2024 roadmap toward citywide net-zero emissions by 2050 through energy efficiency, renewable energy, and more sustainable transportation — as a top priority for her next term. Her documented posture is affirmative local climate action on a gradual net-zero-2050 trajectory: she has not advocated a 2030 fossil-fuel phase-out or emergency declaration, but she has actively refused to obstruct state climate mandates. That matches the invest-in-clean-energy-while-gradually-reducing-fossil-fuel-reliance chair.', ARRAY['https://tualatinlife.com/local-news/tualatin-among-13-cities-suing-oregon-to-halt-new-climate-regulations/', 'https://beavertonvalleytimes.com/2024/09/13/pratt-seeks-second-term-on-tualatin-city-council/']::text[]),
    ('transportation-priorities', 2, 'Pratt calls traffic congestion Tualatin''s "#1 issue" and works both sides of the ledger: her 2020 candidate Q&A urged "effective use of Tualatin Moving Forward bond funds" (the $20 million package spanning congestion relief and safety projects), improvements to eastbound Nyberg Street at I-5, and advocacy with Washington County, Clackamas County, Metro, and ODOT — while explicitly endorsing "safe and continuous bike and pedestrian paths" as congestion solutions. As Council President she presented the city''s Transportation System Plan update at the April 2025 State of the City. Tellingly, in September 2022 she voted against joining the lawsuit fighting the state''s Climate Friendly and Equitable Communities rules, declining to resist mandates that eliminate parking minimums and require EV charging in new development. Road congestion investment paired with bike/pedestrian infrastructure and acceptance of parking reform matches the invest-equally-in-roads-and-multimodal chair rather than a transit-first agenda or a roads-and-parking-only stance.', ARRAY['https://tualatinlife.com/politics/valerie-pratt/', 'https://tualatinlife.com/local-news/state-of-the-city-tualatin-is-going-full-steam-ahead/', 'https://tualatinlife.com/local-news/tualatin-among-13-cities-suing-oregon-to-halt-new-climate-regulations/']::text[]),
    ('economic-development', 3, 'Pratt champions urban renewal as a targeted tool with strings she is willing to pull: her April 2025 testimony against HB 3499 called urban renewal plans "vital to providing future livability to communities throughout Oregon," providing "funding to provide housing and economic development" in blighted and developing areas, and her 2024 reelection priorities include the "reimagining and development of the urban renewal districts in both Basalt Creek and the core downtown area." But her support is conditional on the city''s terms, not incentives at any cost: in August 2021 she voted against the Basalt Creek urban renewal ordinance in back-to-back 5-2 votes because Washington County had tied it to the Basalt Creek Parkway extension, saying "I feel like we''ve been bullied. And in my experience, you have to face up and be strong and direct with a bully," and separately questioning the road design ("I''m not understanding why we have a road that will dump onto Boones Ferry"). Targeted tax-increment districts for specific industrial/downtown aims, scrutinized for community benefit, is the chair 3 posture rather than maximal recruitment incentives.', ARRAY['https://olis.oregonlegislature.gov/liz/2025R1/Downloads/PublicTestimonyDocument/196481', 'https://tualatinlife.com/featured/county-ties-basalt-creek-urban-renewal-to-parkway-extension-project/', 'https://beavertonvalleytimes.com/2024/09/13/pratt-seeks-second-term-on-tualatin-city-council/']::text[]),
    ('growth-and-development', 3, 'Pratt manages growth through proactive planning and front-loaded public investment: her 2020 candidate Q&A pointed to the Tualatin 2040 Plan to identify future transportation needs, accepting that "Expected growth will inevitably result in increased traffic" and answering with bond-funded infrastructure and regional advocacy rather than growth limits; as Council President she presented the Transportation System Plan update at the April 2025 State of the City, and her 2024 priorities center on developing the Basalt Creek and downtown urban renewal districts. Her April 2025 HB 3499 testimony explicitly rejected adding a voter-approval requirement for urban renewal plans — "Requiring a general election vote would only complicate matters and increase costs... it makes no sense to add another costly and cumbersome step" — the direct opposite of the growth-limits-by-referendum chair. Nothing in her record supports removing regulatory barriers wholesale either; the documented pattern is plan first, build infrastructure, then grow.', ARRAY['https://olis.oregonlegislature.gov/liz/2025R1/Downloads/PublicTestimonyDocument/196481', 'https://tualatinlife.com/politics/valerie-pratt/', 'https://beavertonvalleytimes.com/2024/09/13/pratt-seeks-second-term-on-tualatin-city-council/']::text[]),
    ('civil-rights', 2, 'In February 2025 Pratt voted with the 6-1 majority — over Councilor Gonzalez''s dissent — to proclaim March 31 Transgender Day of Visibility in Tualatin, and the coverage records that she was among the councilors (with Brooks, Sacco, and Hillier) who affirmatively spoke in support of the motion before the vote. Choosing to publicly advocate for a contested inclusion proclamation, rather than quietly maintain the status quo, is an affirmative pro-inclusion act; she has also served throughout the period in which the council built out its standing inclusion, diversity, equity, and access work. At the same time she has proposed no equity mandates or reparations-style programs. Speaking up for recognition of a marginalized group over a colleague''s objection places her at the strengthen-protections-and-address-discrimination chair rather than mere maintenance of current law.', ARRAY['https://tualatinlife.com/featured/tualatin-to-recognize-transgender-day-of-visibility/', 'https://beavertonvalleytimes.com/2024/09/13/pratt-seeks-second-term-on-tualatin-city-council/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT 'c4fd4fc9-8c63-4711-955f-cbec5e6cc985'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'Pratt''s consistent through-line is increasing housing supply with targeted city tools: at the Feb 28, 2022 Tualatin Heights hearing she voted with the 5-1 majority to rezone an existing apartment complex from 220 to 336 units, explaining "All of these issues are in the public interest but to me, housing is the bottom line, most important issue." In April 18, 2025 written testimony to the Oregon House Rules Committee opposing HB 3499 (which would have required general-election votes for urban renewal plans), she wrote as Council President that "Oregon is in the midst of a severe housing crisis and it is vital that everything possible is done to avoid impeding the ability to increase the state''s housing inventory," citing Tualatin''s shortage of 4,300 housing units and the "over 400 housing units" added through the Basalt Creek Urban Renewal District, with more housing planned in the Core Area district. In her 2020 candidate statement she named "providing housing, so those who work here can also afford to live here" as a strategy. Public tax-increment funding to enable housing projects plus rezoning approvals matches the targeted-help chair (subsidies for projects, easier building) rather than rent caps/public housing or leaving housing to the market.', ARRAY['https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/', 'https://olis.oregonlegislature.gov/liz/2025R1/Downloads/PublicTestimonyDocument/196481', 'https://tualatinlife.com/politics/valerie-pratt/']::text[]),
    ('residential-zoning', 3, 'Pratt''s documented zoning record supports substantial multifamily density where it already fits: she voted with the 5-1 majority on Feb 28, 2022 to approve the Tualatin Heights rezoning, a roughly 50% density increase (220 to 336 units) at an existing apartment site, telling neighbors who raised traffic, parking, and livability objections that "All of these issues are in the public interest but to me, housing is the bottom line, most important issue." In her 2020 candidate Q&A she acknowledged that Oregon HB 2001''s housing infill requirements would increase traffic congestion but answered with housing supply — "providing housing, so those who work here can also afford to live here" — rather than resistance to density. Her 2025 legislative testimony backs adding more housing through the downtown Core Area Urban Renewal District, i.e., density concentrated in the commercial core. That fits allowing multifamily and mixed-use near corridors while keeping most residential zones intact, rather than restricting change to modest duplex-scale infill or demanding community votes before rezoning.', ARRAY['https://tualatinlife.com/local-news/tualatin-heights-re-zoning-passes-city-council-in-second-vote/', 'https://tualatinlife.com/politics/valerie-pratt/', 'https://olis.oregonlegislature.gov/liz/2025R1/Downloads/PublicTestimonyDocument/196481']::text[]),
    ('homelessness', 3, 'Pratt joined the unanimous June 26, 2023 council vote adopting Tualatin''s "time, place, and manner" camping ordinance, which prohibits camping in parks, city parking lots, within 20 feet of buildings and 500 feet of schools and freeway ramps, while designating one city-owned lot next to the police station where overnight camping (7 p.m.-7 a.m.) is permitted. The city''s own regulations page states the rules were "adopted in 2023 to comply with state and federal laws" and that they "allow for outdoor camping on public property when an individual is without available shelter and when specific time, place, and manner regulations are followed" — i.e., enforcement is expressly conditioned on the availability of alternatives, consistent with Oregon''s statutory standard. This regulated-but-not-criminalized framework, pairing location/hour limits with a lawful place to sleep when no shelter exists, matches the chair allowing enforcement only when adequate alternatives are available with diversion toward services rather than blanket criminal bans or an unrestricted right to camp.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://tualatinoregon.gov/administration/homelessness/camping-regulations/']::text[]),
    ('homelessness-response', 3, 'Pratt''s citywide strategy pairs reasonable public-space rules with services and behavioral-health capacity: she voted for the unanimous June 26, 2023 camping ordinance that limits camping to a designated lot near the police station between 7 p.m. and 7 a.m. while leaving camping lawful when a person is without available shelter, and the city administers the regulations within its broader homelessness program. In her September 2024 reelection interview she named mental health services — alongside transportation and housing — as one of the three key challenges facing Tualatin, and her housing record (the Tualatin Heights rezoning vote and urban renewal districts she credits with adding over 400 housing units) treats supply as part of the response. Nothing in her record supports enforcement-first crackdowns or minimizing city spending on services, nor a no-enforcement housing-first-only posture; the documented mix is outreach-and-services investment alongside enforceable public-space rules.', ARRAY['https://tualatinlife.com/local-news/new-ordinance-limits-hours-and-locations-for-houseless-camping/', 'https://beavertonvalleytimes.com/2024/09/13/pratt-seeks-second-term-on-tualatin-city-council/', 'https://tualatinoregon.gov/administration/homelessness/camping-regulations/']::text[]),
    ('climate-change', 3, 'Pratt cast one of the three dissenting votes (with Councilors Brooks and Sacco) when the council voted 4-3 in September 2022 to join thirteen local governments suing to pause Oregon''s Climate Friendly and Equitable Communities rules, stating "My decision is based on what I think is best for the climate" and arguing the city''s resources were better spent meeting climate goals than litigating against them. In her September 2024 reelection interview she listed "implementing Tualatin''s Climate Action Plan" — the council-adopted May 2024 roadmap toward citywide net-zero emissions by 2050 through energy efficiency, renewable energy, and more sustainable transportation — as a top priority for her next term. Her documented posture is affirmative local climate action on a gradual net-zero-2050 trajectory: she has not advocated a 2030 fossil-fuel phase-out or emergency declaration, but she has actively refused to obstruct state climate mandates. That matches the invest-in-clean-energy-while-gradually-reducing-fossil-fuel-reliance chair.', ARRAY['https://tualatinlife.com/local-news/tualatin-among-13-cities-suing-oregon-to-halt-new-climate-regulations/', 'https://beavertonvalleytimes.com/2024/09/13/pratt-seeks-second-term-on-tualatin-city-council/']::text[]),
    ('transportation-priorities', 2, 'Pratt calls traffic congestion Tualatin''s "#1 issue" and works both sides of the ledger: her 2020 candidate Q&A urged "effective use of Tualatin Moving Forward bond funds" (the $20 million package spanning congestion relief and safety projects), improvements to eastbound Nyberg Street at I-5, and advocacy with Washington County, Clackamas County, Metro, and ODOT — while explicitly endorsing "safe and continuous bike and pedestrian paths" as congestion solutions. As Council President she presented the city''s Transportation System Plan update at the April 2025 State of the City. Tellingly, in September 2022 she voted against joining the lawsuit fighting the state''s Climate Friendly and Equitable Communities rules, declining to resist mandates that eliminate parking minimums and require EV charging in new development. Road congestion investment paired with bike/pedestrian infrastructure and acceptance of parking reform matches the invest-equally-in-roads-and-multimodal chair rather than a transit-first agenda or a roads-and-parking-only stance.', ARRAY['https://tualatinlife.com/politics/valerie-pratt/', 'https://tualatinlife.com/local-news/state-of-the-city-tualatin-is-going-full-steam-ahead/', 'https://tualatinlife.com/local-news/tualatin-among-13-cities-suing-oregon-to-halt-new-climate-regulations/']::text[]),
    ('economic-development', 3, 'Pratt champions urban renewal as a targeted tool with strings she is willing to pull: her April 2025 testimony against HB 3499 called urban renewal plans "vital to providing future livability to communities throughout Oregon," providing "funding to provide housing and economic development" in blighted and developing areas, and her 2024 reelection priorities include the "reimagining and development of the urban renewal districts in both Basalt Creek and the core downtown area." But her support is conditional on the city''s terms, not incentives at any cost: in August 2021 she voted against the Basalt Creek urban renewal ordinance in back-to-back 5-2 votes because Washington County had tied it to the Basalt Creek Parkway extension, saying "I feel like we''ve been bullied. And in my experience, you have to face up and be strong and direct with a bully," and separately questioning the road design ("I''m not understanding why we have a road that will dump onto Boones Ferry"). Targeted tax-increment districts for specific industrial/downtown aims, scrutinized for community benefit, is the chair 3 posture rather than maximal recruitment incentives.', ARRAY['https://olis.oregonlegislature.gov/liz/2025R1/Downloads/PublicTestimonyDocument/196481', 'https://tualatinlife.com/featured/county-ties-basalt-creek-urban-renewal-to-parkway-extension-project/', 'https://beavertonvalleytimes.com/2024/09/13/pratt-seeks-second-term-on-tualatin-city-council/']::text[]),
    ('growth-and-development', 3, 'Pratt manages growth through proactive planning and front-loaded public investment: her 2020 candidate Q&A pointed to the Tualatin 2040 Plan to identify future transportation needs, accepting that "Expected growth will inevitably result in increased traffic" and answering with bond-funded infrastructure and regional advocacy rather than growth limits; as Council President she presented the Transportation System Plan update at the April 2025 State of the City, and her 2024 priorities center on developing the Basalt Creek and downtown urban renewal districts. Her April 2025 HB 3499 testimony explicitly rejected adding a voter-approval requirement for urban renewal plans — "Requiring a general election vote would only complicate matters and increase costs... it makes no sense to add another costly and cumbersome step" — the direct opposite of the growth-limits-by-referendum chair. Nothing in her record supports removing regulatory barriers wholesale either; the documented pattern is plan first, build infrastructure, then grow.', ARRAY['https://olis.oregonlegislature.gov/liz/2025R1/Downloads/PublicTestimonyDocument/196481', 'https://tualatinlife.com/politics/valerie-pratt/', 'https://beavertonvalleytimes.com/2024/09/13/pratt-seeks-second-term-on-tualatin-city-council/']::text[]),
    ('civil-rights', 2, 'In February 2025 Pratt voted with the 6-1 majority — over Councilor Gonzalez''s dissent — to proclaim March 31 Transgender Day of Visibility in Tualatin, and the coverage records that she was among the councilors (with Brooks, Sacco, and Hillier) who affirmatively spoke in support of the motion before the vote. Choosing to publicly advocate for a contested inclusion proclamation, rather than quietly maintain the status quo, is an affirmative pro-inclusion act; she has also served throughout the period in which the council built out its standing inclusion, diversity, equity, and access work. At the same time she has proposed no equity mandates or reparations-style programs. Speaking up for recognition of a marginalized group over a colleague''s objection places her at the strengthen-protections-and-address-discrimination chair rather than mere maintenance of current law.', ARRAY['https://tualatinlife.com/featured/tualatin-to-recognize-transgender-day-of-visibility/', 'https://beavertonvalleytimes.com/2024/09/13/pratt-seeks-second-term-on-tualatin-city-council/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT 'c4fd4fc9-8c63-4711-955f-cbec5e6cc985'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = 'c4fd4fc9-8c63-4711-955f-cbec5e6cc985';
  IF v_ext IS DISTINCT FROM -4174957 THEN
    RAISE EXCEPTION 'UUID c4fd4fc9-8c63-4711-955f-cbec5e6cc985 does not belong to external_id -4174957 (Valerie Pratt) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = 'c4fd4fc9-8c63-4711-955f-cbec5e6cc985';
  IF n <> 9 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 9, n;
  END IF;
  -- Context-parity gate (WR-03): the context VALUES list is a verbatim
  -- duplicate of the answers list; count it too so a single-sided edit
  -- cannot silently drop or skew reasoning/sources rows.
  SELECT COUNT(*) INTO n FROM inform.politician_context WHERE politician_id = 'c4fd4fc9-8c63-4711-955f-cbec5e6cc985';
  IF n <> 9 THEN
    RAISE EXCEPTION 'Expected % context rows, found % — answers/context VALUES lists diverged', 9, n;
  END IF;
END $$;

COMMIT;
