-- Migration 1180: Malynda Wenzl (Mayor, Forest Grove OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 7 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'In her 2022 mayoral candidate Q&A, Wenzl argued that the main cause of homelessness is a lack of housing supply and that, from a city policy standpoint, Forest Grove needs to encourage more housing — specifically affordable housing. Her March 17, 2025 State of the City address highlighted the city approving nine residential projects exceeding $100 million and delivering 780 additional housing units, including the 78-unit Jesse Quinn mixed-use project downtown, while the city works to expand opportunities for affordable housing development to meet current and future needs. Encouraging supply through city approvals with an explicit affordable-housing emphasis matches the targeted-help chair (subsidies for affordable projects, easier permitting), not rent caps/public housing on one side or pure market deregulation on the other.', ARRAY['https://www.newsbreak.com/news/2783850894715-q-a-what-do-candidates-for-forest-grove-mayor-have-to-say', 'https://www.newsinthegrove.com/forest-grove-state-of-the-city-address-draws-standing-room-only-crowd/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('homelessness', 3, 'Wenzl presided over and joined the unanimous 7-0 first-reading vote (June 12, 2023) adopting Forest Grove''s "time, place and manner" camping ordinance (Ordinance 2023-04, second reading June 26, 2023), which prohibits camping in parks and restricts overnight camping to the designated City Hall South Lot between 7 p.m. and 7 a.m. The ordinance was written to comply with Oregon''s HB 3115 mandate that cities set "objectively reasonable" rules for where camping is allowed when shelter beds are unavailable — the statewide codification of the rule that people cannot be punished for sleeping outside with no alternative. Facing heated public opposition, Wenzl defended it as a "step in creating structures and boundaries to address some of the issues we have heard from the community," while conceding "Do I know for sure it''s going to be a perfect answer? No, I don''t know if any of us in this room do." Enforcement conditioned on the shelter-availability standard with a designated permitted location fits the allow-enforcement-only-with-adequate-alternatives chair, not a blanket criminal ban or a protected right to camp anywhere.', ARRAY['https://hillsboronewstimes.com/2023/06/21/forest-grove-residents-blast-city-council-for-overnight-camping-regulations/', 'https://www.forestgrove-or.gov/ArchiveCenter/ViewFile/Item/336']::text[]),
    ('homelessness-response', 3, 'Wenzl''s documented strategy pairs shelter-and-services investment with reasonable public-space rules: on January 22, 2024 she joined the unanimous council vote denying the appeal against the Forest Grove Foundation''s transitional homeless pod village (12-16 heated sleeping pods plus a common building with kitchen, showers, and laundry at 2500 22nd Ave — the third pod village in Washington County), saying "I think this is a good project. I think it meets our needs." In her 2022 mayoral Q&A she said "Every possible solution must be given consideration; there is no single answer to this complex issue," expressed pride in the city''s partnerships with service providers and Washington County, and advocated a tiered approach modeled on Hillsboro''s Family Justice Center — "something that addresses all of the issues in one spot." Combined with the 2023 camping regulations she shepherded, this is the invest-in-outreach-shelter-and-services-while-enforcing-reasonable-rules chair, not enforcement-first and not housing-first-with-no-enforcement.', ARRAY['https://forestgrovenewstimes.com/2024/01/26/plans-for-new-forest-grove-homeless-pod-village-moves-forward-council-denies-appeal/', 'https://www.newsbreak.com/news/2783850894715-q-a-what-do-candidates-for-forest-grove-mayor-have-to-say']::text[]),
    ('growth-and-development', 3, 'Wenzl''s official city bio states she is "focused on balanced growth while retaining the small-town essence of our city," wants long-term development to be "mindful and intentional," works to "build and maintain existing city infrastructure; creating systems that remain resilient in challenging times," and emphasizes "strategic growth, moving the vision of the city forward at a pace the community supports." In practice she has not slowed growth: her March 2025 State of the City celebrated $23.6 million in new commercial development, $100.7 million in industrial construction, and nine approved residential projects (780 units), and under her mayorship the city launched the Forest Grove Forward 2040 community visioning process to plan a vibrant downtown, walkability, and a thriving local economy. Managing expansion through deliberate long-range planning, community visioning, and resilient infrastructure matches the plan-proactively chair, not growth moratoria/voter-approval requirements and not streamlined-recruitment deregulation.', ARRAY['https://www.forestgrove-or.gov/611/Meet-the-Council', 'https://www.newsinthegrove.com/forest-grove-state-of-the-city-address-draws-standing-room-only-crowd/']::text[]),
    ('public-safety-approach', 4, 'Wenzl has repeatedly championed major new capital investment in the police department: after Forest Grove voters rejected a police facility bond 52.3%-47.7% in November 2025, she led the push to return a trimmed $29.5 million bond (for a new station at 19th Avenue and Birch Street, replacing a 1977 building the force has tripled beyond) to the November 3, 2026 ballot, saying the city "worked with consultants to trim costs" (from 77 to 69 cents per $1,000 assessed value), that "Going for it now allows us to keep that same price — if we push it out further, then we have some other compression," and "We felt the no-vote margins were within a space that we could do more education." As a 2022 mayoral candidate she named "officer retention and encouraging officers to live locally" as her public-safety priority and praised the chief''s community-policing focus. Sustained advocacy for expanding police facilities and retaining/supporting officers matches the increase-police-investment chair; she has proposed no budget reallocation away from police and no crisis-team substitution.', ARRAY['https://forestgrovenewstimes.com/2026/06/25/forest-grove-police-facility-bond-likely-to-return-to-ballot-after-2025-defeat/', 'https://www.newsbreak.com/news/2783850894715-q-a-what-do-candidates-for-forest-grove-mayor-have-to-say']::text[]),
    ('civil-rights', 2, 'On November 10, 2025, Wenzl and the council unanimously approved a state-of-emergency declaration over federal immigration raids, allocating up to $50,000 to community organizations assisting impacted residents so people would not fear leaving home for work, school, or medical care; Wenzl said "It''s our kids that are hurting the most. I don''t know how you come back from this trauma" and "We''re open to more suggestions. We are a team. We all love Forest Grove." Under her leadership the council also agreed to codify additional protections for immigrant residents by ordinance and began drafting a letter asking Washington County to suspend its Flock Safety license-plate-reader contract, citing links to racial profiling and increased detainments. As a councilor in 2017 she supported the unanimous resolution declaring Forest Grove an "inclusive community for all persons" and voiced disappointment that the stronger sanctuary-city resolution had failed. Taking affirmative city action against profiling and codifying protections for vulnerable residents goes beyond maintaining current law, matching the actively-address-systemic-discrimination chair; she has proposed no mandates or reparations.', ARRAY['https://forestgrovenewstimes.com/2025/11/11/forest-grove-declares-state-of-emergency-over-ice-raids/', 'https://www.forestgrove-or.gov/707/Inclusive-Community-and-Immigration-Reso']::text[]),
    ('local-immigration', 2, 'Forest Grove''s standing "inclusive community" resolution — which Wenzl supported as a councilor in 2017 after voicing disappointment that a formal sanctuary-city resolution had failed — keeps city resources out of federal immigration enforcement consistent with Oregon''s statewide sanctuary law. As mayor she has moved beyond passive non-participation: on November 10, 2025 she joined the unanimous emergency declaration committing up to $50,000 to organizations assisting residents impacted by ICE raids, the council under her leadership agreed to replace the inclusive-city resolution with an ordinance formally establishing Forest Grove as a sanctuary city with additional codified protections for immigrant residents (resolution discussion set for November 24, 2025), and the council began requesting that Washington County cancel the Flock license-plate-reader contract that it linked to increased detainments. Actively protecting immigrant residents while complying only with what state and federal law actually require matches the protect-residents chair (comply only with court-ordered cooperation), stronger than mere non-use of city resources but short of a documented refusal of all detainers.', ARRAY['https://forestgrovenewstimes.com/2025/11/11/forest-grove-declares-state-of-emergency-over-ice-raids/', 'https://www.forestgrove-or.gov/707/Inclusive-Community-and-Immigration-Reso']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '749da610-7755-4c36-8f2d-efdacc522b2c'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'In her 2022 mayoral candidate Q&A, Wenzl argued that the main cause of homelessness is a lack of housing supply and that, from a city policy standpoint, Forest Grove needs to encourage more housing — specifically affordable housing. Her March 17, 2025 State of the City address highlighted the city approving nine residential projects exceeding $100 million and delivering 780 additional housing units, including the 78-unit Jesse Quinn mixed-use project downtown, while the city works to expand opportunities for affordable housing development to meet current and future needs. Encouraging supply through city approvals with an explicit affordable-housing emphasis matches the targeted-help chair (subsidies for affordable projects, easier permitting), not rent caps/public housing on one side or pure market deregulation on the other.', ARRAY['https://www.newsbreak.com/news/2783850894715-q-a-what-do-candidates-for-forest-grove-mayor-have-to-say', 'https://www.newsinthegrove.com/forest-grove-state-of-the-city-address-draws-standing-room-only-crowd/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('homelessness', 3, 'Wenzl presided over and joined the unanimous 7-0 first-reading vote (June 12, 2023) adopting Forest Grove''s "time, place and manner" camping ordinance (Ordinance 2023-04, second reading June 26, 2023), which prohibits camping in parks and restricts overnight camping to the designated City Hall South Lot between 7 p.m. and 7 a.m. The ordinance was written to comply with Oregon''s HB 3115 mandate that cities set "objectively reasonable" rules for where camping is allowed when shelter beds are unavailable — the statewide codification of the rule that people cannot be punished for sleeping outside with no alternative. Facing heated public opposition, Wenzl defended it as a "step in creating structures and boundaries to address some of the issues we have heard from the community," while conceding "Do I know for sure it''s going to be a perfect answer? No, I don''t know if any of us in this room do." Enforcement conditioned on the shelter-availability standard with a designated permitted location fits the allow-enforcement-only-with-adequate-alternatives chair, not a blanket criminal ban or a protected right to camp anywhere.', ARRAY['https://hillsboronewstimes.com/2023/06/21/forest-grove-residents-blast-city-council-for-overnight-camping-regulations/', 'https://www.forestgrove-or.gov/ArchiveCenter/ViewFile/Item/336']::text[]),
    ('homelessness-response', 3, 'Wenzl''s documented strategy pairs shelter-and-services investment with reasonable public-space rules: on January 22, 2024 she joined the unanimous council vote denying the appeal against the Forest Grove Foundation''s transitional homeless pod village (12-16 heated sleeping pods plus a common building with kitchen, showers, and laundry at 2500 22nd Ave — the third pod village in Washington County), saying "I think this is a good project. I think it meets our needs." In her 2022 mayoral Q&A she said "Every possible solution must be given consideration; there is no single answer to this complex issue," expressed pride in the city''s partnerships with service providers and Washington County, and advocated a tiered approach modeled on Hillsboro''s Family Justice Center — "something that addresses all of the issues in one spot." Combined with the 2023 camping regulations she shepherded, this is the invest-in-outreach-shelter-and-services-while-enforcing-reasonable-rules chair, not enforcement-first and not housing-first-with-no-enforcement.', ARRAY['https://forestgrovenewstimes.com/2024/01/26/plans-for-new-forest-grove-homeless-pod-village-moves-forward-council-denies-appeal/', 'https://www.newsbreak.com/news/2783850894715-q-a-what-do-candidates-for-forest-grove-mayor-have-to-say']::text[]),
    ('growth-and-development', 3, 'Wenzl''s official city bio states she is "focused on balanced growth while retaining the small-town essence of our city," wants long-term development to be "mindful and intentional," works to "build and maintain existing city infrastructure; creating systems that remain resilient in challenging times," and emphasizes "strategic growth, moving the vision of the city forward at a pace the community supports." In practice she has not slowed growth: her March 2025 State of the City celebrated $23.6 million in new commercial development, $100.7 million in industrial construction, and nine approved residential projects (780 units), and under her mayorship the city launched the Forest Grove Forward 2040 community visioning process to plan a vibrant downtown, walkability, and a thriving local economy. Managing expansion through deliberate long-range planning, community visioning, and resilient infrastructure matches the plan-proactively chair, not growth moratoria/voter-approval requirements and not streamlined-recruitment deregulation.', ARRAY['https://www.forestgrove-or.gov/611/Meet-the-Council', 'https://www.newsinthegrove.com/forest-grove-state-of-the-city-address-draws-standing-room-only-crowd/']::text[]),
    ('public-safety-approach', 4, 'Wenzl has repeatedly championed major new capital investment in the police department: after Forest Grove voters rejected a police facility bond 52.3%-47.7% in November 2025, she led the push to return a trimmed $29.5 million bond (for a new station at 19th Avenue and Birch Street, replacing a 1977 building the force has tripled beyond) to the November 3, 2026 ballot, saying the city "worked with consultants to trim costs" (from 77 to 69 cents per $1,000 assessed value), that "Going for it now allows us to keep that same price — if we push it out further, then we have some other compression," and "We felt the no-vote margins were within a space that we could do more education." As a 2022 mayoral candidate she named "officer retention and encouraging officers to live locally" as her public-safety priority and praised the chief''s community-policing focus. Sustained advocacy for expanding police facilities and retaining/supporting officers matches the increase-police-investment chair; she has proposed no budget reallocation away from police and no crisis-team substitution.', ARRAY['https://forestgrovenewstimes.com/2026/06/25/forest-grove-police-facility-bond-likely-to-return-to-ballot-after-2025-defeat/', 'https://www.newsbreak.com/news/2783850894715-q-a-what-do-candidates-for-forest-grove-mayor-have-to-say']::text[]),
    ('civil-rights', 2, 'On November 10, 2025, Wenzl and the council unanimously approved a state-of-emergency declaration over federal immigration raids, allocating up to $50,000 to community organizations assisting impacted residents so people would not fear leaving home for work, school, or medical care; Wenzl said "It''s our kids that are hurting the most. I don''t know how you come back from this trauma" and "We''re open to more suggestions. We are a team. We all love Forest Grove." Under her leadership the council also agreed to codify additional protections for immigrant residents by ordinance and began drafting a letter asking Washington County to suspend its Flock Safety license-plate-reader contract, citing links to racial profiling and increased detainments. As a councilor in 2017 she supported the unanimous resolution declaring Forest Grove an "inclusive community for all persons" and voiced disappointment that the stronger sanctuary-city resolution had failed. Taking affirmative city action against profiling and codifying protections for vulnerable residents goes beyond maintaining current law, matching the actively-address-systemic-discrimination chair; she has proposed no mandates or reparations.', ARRAY['https://forestgrovenewstimes.com/2025/11/11/forest-grove-declares-state-of-emergency-over-ice-raids/', 'https://www.forestgrove-or.gov/707/Inclusive-Community-and-Immigration-Reso']::text[]),
    ('local-immigration', 2, 'Forest Grove''s standing "inclusive community" resolution — which Wenzl supported as a councilor in 2017 after voicing disappointment that a formal sanctuary-city resolution had failed — keeps city resources out of federal immigration enforcement consistent with Oregon''s statewide sanctuary law. As mayor she has moved beyond passive non-participation: on November 10, 2025 she joined the unanimous emergency declaration committing up to $50,000 to organizations assisting residents impacted by ICE raids, the council under her leadership agreed to replace the inclusive-city resolution with an ordinance formally establishing Forest Grove as a sanctuary city with additional codified protections for immigrant residents (resolution discussion set for November 24, 2025), and the council began requesting that Washington County cancel the Flock license-plate-reader contract that it linked to increased detainments. Actively protecting immigrant residents while complying only with what state and federal law actually require matches the protect-residents chair (comply only with court-ordered cooperation), stronger than mere non-use of city resources but short of a documented refusal of all detainers.', ARRAY['https://forestgrovenewstimes.com/2025/11/11/forest-grove-declares-state-of-emergency-over-ice-raids/', 'https://www.forestgrove-or.gov/707/Inclusive-Community-and-Immigration-Reso']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '749da610-7755-4c36-8f2d-efdacc522b2c'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = '749da610-7755-4c36-8f2d-efdacc522b2c';
  IF v_ext IS DISTINCT FROM -4126201 THEN
    RAISE EXCEPTION 'UUID 749da610-7755-4c36-8f2d-efdacc522b2c does not belong to external_id -4126201 (Malynda Wenzl) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = '749da610-7755-4c36-8f2d-efdacc522b2c';
  IF n <> 7 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 7, n;
  END IF;
  -- Context-parity gate (WR-03): the context VALUES list is a verbatim
  -- duplicate of the answers list; count it too so a single-sided edit
  -- cannot silently drop or skew reasoning/sources rows.
  SELECT COUNT(*) INTO n FROM inform.politician_context WHERE politician_id = '749da610-7755-4c36-8f2d-efdacc522b2c';
  IF n <> 7 THEN
    RAISE EXCEPTION 'Expected % context rows, found % — answers/context VALUES lists diverged', 7, n;
  END IF;
END $$;

COMMIT;
