-- Migration 1182: Karen Martinez (City Councilor, Forest Grove OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 4 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('homelessness', 3, 'Martinez, seated on the seven-member council since January 2023, joined the unanimous 7-0 first-reading vote (June 12, 2023) adopting Forest Grove''s "time, place and manner" camping ordinance (Ordinance 2023-04), which prohibits camping in parks and restricts overnight camping to the designated City Hall South Lot between 7 p.m. and 7 a.m., written to satisfy Oregon''s HB 3115 requirement that cities set "objectively reasonable" rules for where camping is allowed when shelter is unavailable — the statewide codification that people cannot be punished for sleeping outside with no alternative. Her official city bio frames her goal as finding "solutions to help the homeless off the streets and on the road to becoming self-supporting," i.e., moving people out of public spaces and into services rather than either criminalizing them outright or leaving encampments in place. Enforcement conditioned on the shelter-availability standard with a designated permitted location matches the allow-enforcement-only-with-adequate-alternatives chair, not a blanket criminal ban and not a protected right to camp anywhere.', ARRAY['https://hillsboronewstimes.com/2023/06/21/forest-grove-residents-blast-city-council-for-overnight-camping-regulations/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('homelessness-response', 3, 'Martinez''s documented strategy pairs services investment with accountability rules: on January 22, 2024 she joined the unanimous council vote denying the appeal against the Forest Grove Foundation''s transitional homeless pod village (12-16 heated sleeping pods plus a common building with kitchen, showers, and laundry at 2500 22nd Ave) — while pressing at the hearing for consequences for residents who break the village''s rules and advocating 24-hour onsite staffing rather than remote monitoring. In her 2022 candidate Q&A she said the underlying issues of homelessness — mental health and addiction — must be addressed and urged the city to reach out to nonprofits with experience serving the homeless. Her city bio states she is "focused on the resolution of homelessness in our city, with a goal to find solutions to help the homeless off the streets and on the road to becoming self-supporting," and she is separately concerned about drug use and theft. Supporting shelter capacity and service partnerships while insisting on rule enforcement and oversight — alongside the 2023 camping regulations she voted for — matches the invest-in-outreach-shelter-and-mental-health-services-while-enforcing-reasonable-public-space-rules chair, not housing-first-without-enforcement and not enforcement-as-the-primary-tool.', ARRAY['https://forestgrovenewstimes.com/2024/01/26/plans-for-new-forest-grove-homeless-pod-village-moves-forward-council-denies-appeal/', 'https://pamplinmedia.com/fgnt/36-news/560432-448404-q-and-a-would-be-forest-grove-city-councilors-answer-questions', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('public-safety-approach', 4, 'Martinez''s official city bio identifies her as "a proponent of protecting police funding and public safety" who is "concerned about drug use and theft." In her 2022 candidate Q&A she defended the police department against criticism, saying the trust issue "doesn''t revolve around trust in the police department as much as Oregon restrictions" on policing, and praising the department''s efforts to keep officers'' skills current. In June 2026 she was part of the Forest Grove City Council consensus (June 22, 2026 work session) to return the trimmed $29.5 million police facility bond — funding a new station at 19th Avenue and Birch Street to replace a 1977 building the force has tripled beyond — to the November 3, 2026 ballot after its 2025 defeat. A record of shielding the police budget from cuts, defending officers against state-imposed restrictions, and supporting major new capital investment in police facilities matches the increase-police-investment chair; she has proposed no reallocation away from police and no crisis-team substitution for sworn response.', ARRAY['https://www.forestgrove-or.gov/611/Meet-the-Council', 'https://pamplinmedia.com/fgnt/36-news/560432-448404-q-and-a-would-be-forest-grove-city-councilors-answer-questions', 'https://forestgrovenewstimes.com/2026/06/25/forest-grove-police-facility-bond-likely-to-return-to-ballot-after-2025-defeat/']::text[]),
    ('local-immigration', 3, 'Martinez joined the unanimous November 10, 2025 council vote declaring a state of emergency over federal immigration raids, authorizing up to $50,000 for community organizations assisting impacted residents — but on January 12, 2026 she cast the lone dissenting vote (6-1, having also opposed the December first reading) against the ordinance codifying Oregon''s Sanctuary Promise Act into Forest Grove''s municipal code with new staff policies, training, and restricted "nonpublic" areas. She argued the ordinance gives residents false confidence: "My biggest concerns are these (ordinances) make people feel like they can stand up to ICE agents, and they can''t... These are federal agents who trump our local enforcement," and she voiced support for establishing a detention center in Oregon so locally detained people face fewer legal barriers than when transported out of state. Her documented position — comply with the state sanctuary law that already binds the city, support emergency aid to affected residents, but oppose codifying additional local resistance while deferring to federal authority — matches the follow-federal-law-as-required-but-commit-no-city-resources-to-proactive-enforcement chair; she has not advocated honoring detainers or actively assisting ICE, nor does she support the council majority''s stronger protections.', ARRAY['https://hillsboronewstimes.com/2026/01/14/forest-grove-affirms-its-a-sanctuary-city-in-6-1-vote-will-develop-new-internal-ice-policies/', 'https://forestgrovenewstimes.com/2025/11/11/forest-grove-declares-state-of-emergency-over-ice-raids/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT 'cdc010a8-66d5-4cd6-ab5f-ca10f5101e88'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('homelessness', 3, 'Martinez, seated on the seven-member council since January 2023, joined the unanimous 7-0 first-reading vote (June 12, 2023) adopting Forest Grove''s "time, place and manner" camping ordinance (Ordinance 2023-04), which prohibits camping in parks and restricts overnight camping to the designated City Hall South Lot between 7 p.m. and 7 a.m., written to satisfy Oregon''s HB 3115 requirement that cities set "objectively reasonable" rules for where camping is allowed when shelter is unavailable — the statewide codification that people cannot be punished for sleeping outside with no alternative. Her official city bio frames her goal as finding "solutions to help the homeless off the streets and on the road to becoming self-supporting," i.e., moving people out of public spaces and into services rather than either criminalizing them outright or leaving encampments in place. Enforcement conditioned on the shelter-availability standard with a designated permitted location matches the allow-enforcement-only-with-adequate-alternatives chair, not a blanket criminal ban and not a protected right to camp anywhere.', ARRAY['https://hillsboronewstimes.com/2023/06/21/forest-grove-residents-blast-city-council-for-overnight-camping-regulations/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('homelessness-response', 3, 'Martinez''s documented strategy pairs services investment with accountability rules: on January 22, 2024 she joined the unanimous council vote denying the appeal against the Forest Grove Foundation''s transitional homeless pod village (12-16 heated sleeping pods plus a common building with kitchen, showers, and laundry at 2500 22nd Ave) — while pressing at the hearing for consequences for residents who break the village''s rules and advocating 24-hour onsite staffing rather than remote monitoring. In her 2022 candidate Q&A she said the underlying issues of homelessness — mental health and addiction — must be addressed and urged the city to reach out to nonprofits with experience serving the homeless. Her city bio states she is "focused on the resolution of homelessness in our city, with a goal to find solutions to help the homeless off the streets and on the road to becoming self-supporting," and she is separately concerned about drug use and theft. Supporting shelter capacity and service partnerships while insisting on rule enforcement and oversight — alongside the 2023 camping regulations she voted for — matches the invest-in-outreach-shelter-and-mental-health-services-while-enforcing-reasonable-public-space-rules chair, not housing-first-without-enforcement and not enforcement-as-the-primary-tool.', ARRAY['https://forestgrovenewstimes.com/2024/01/26/plans-for-new-forest-grove-homeless-pod-village-moves-forward-council-denies-appeal/', 'https://pamplinmedia.com/fgnt/36-news/560432-448404-q-and-a-would-be-forest-grove-city-councilors-answer-questions', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('public-safety-approach', 4, 'Martinez''s official city bio identifies her as "a proponent of protecting police funding and public safety" who is "concerned about drug use and theft." In her 2022 candidate Q&A she defended the police department against criticism, saying the trust issue "doesn''t revolve around trust in the police department as much as Oregon restrictions" on policing, and praising the department''s efforts to keep officers'' skills current. In June 2026 she was part of the Forest Grove City Council consensus (June 22, 2026 work session) to return the trimmed $29.5 million police facility bond — funding a new station at 19th Avenue and Birch Street to replace a 1977 building the force has tripled beyond — to the November 3, 2026 ballot after its 2025 defeat. A record of shielding the police budget from cuts, defending officers against state-imposed restrictions, and supporting major new capital investment in police facilities matches the increase-police-investment chair; she has proposed no reallocation away from police and no crisis-team substitution for sworn response.', ARRAY['https://www.forestgrove-or.gov/611/Meet-the-Council', 'https://pamplinmedia.com/fgnt/36-news/560432-448404-q-and-a-would-be-forest-grove-city-councilors-answer-questions', 'https://forestgrovenewstimes.com/2026/06/25/forest-grove-police-facility-bond-likely-to-return-to-ballot-after-2025-defeat/']::text[]),
    ('local-immigration', 3, 'Martinez joined the unanimous November 10, 2025 council vote declaring a state of emergency over federal immigration raids, authorizing up to $50,000 for community organizations assisting impacted residents — but on January 12, 2026 she cast the lone dissenting vote (6-1, having also opposed the December first reading) against the ordinance codifying Oregon''s Sanctuary Promise Act into Forest Grove''s municipal code with new staff policies, training, and restricted "nonpublic" areas. She argued the ordinance gives residents false confidence: "My biggest concerns are these (ordinances) make people feel like they can stand up to ICE agents, and they can''t... These are federal agents who trump our local enforcement," and she voiced support for establishing a detention center in Oregon so locally detained people face fewer legal barriers than when transported out of state. Her documented position — comply with the state sanctuary law that already binds the city, support emergency aid to affected residents, but oppose codifying additional local resistance while deferring to federal authority — matches the follow-federal-law-as-required-but-commit-no-city-resources-to-proactive-enforcement chair; she has not advocated honoring detainers or actively assisting ICE, nor does she support the council majority''s stronger protections.', ARRAY['https://hillsboronewstimes.com/2026/01/14/forest-grove-affirms-its-a-sanctuary-city-in-6-1-vote-will-develop-new-internal-ice-policies/', 'https://forestgrovenewstimes.com/2025/11/11/forest-grove-declares-state-of-emergency-over-ice-raids/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT 'cdc010a8-66d5-4cd6-ab5f-ca10f5101e88'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = 'cdc010a8-66d5-4cd6-ab5f-ca10f5101e88';
  IF v_ext IS DISTINCT FROM -4126203 THEN
    RAISE EXCEPTION 'UUID cdc010a8-66d5-4cd6-ab5f-ca10f5101e88 does not belong to external_id -4126203 (Karen Martinez) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = 'cdc010a8-66d5-4cd6-ab5f-ca10f5101e88';
  IF n <> 4 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 4, n;
  END IF;
  -- Context-parity gate (WR-03): the context VALUES list is a verbatim
  -- duplicate of the answers list; count it too so a single-sided edit
  -- cannot silently drop or skew reasoning/sources rows.
  SELECT COUNT(*) INTO n FROM inform.politician_context WHERE politician_id = 'cdc010a8-66d5-4cd6-ab5f-ca10f5101e88';
  IF n <> 4 THEN
    RAISE EXCEPTION 'Expected % context rows, found % — answers/context VALUES lists diverged', 4, n;
  END IF;
END $$;

COMMIT;
