-- Migration 1184: Donna Gustafson (Councilor, Forest Grove OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 8 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('homelessness', 3, 'Gustafson, on the council since her November 2020 election (seated January 2021), joined the unanimous 7-0 first-reading vote (June 12, 2023) adopting Forest Grove''s "time, place and manner" camping ordinance (Ordinance 2023-04, second reading June 26, 2023), which prohibits camping in parks and restricts overnight camping to the designated City Hall South Lot between 7 p.m. and 7 a.m. — written to satisfy Oregon''s HB 3115 requirement that cities set "objectively reasonable" rules for where camping is allowed when shelter is unavailable, the statewide codification that people cannot be punished for sleeping outside with no alternative. Her official city bio names homelessness first among the issues she is deeply concerned about, and she has paired the camping rules with support for transitional shelter (the January 22, 2024 pod-village appeal denial). Enforcement conditioned on the shelter-availability standard with a designated permitted overnight location matches the allow-enforcement-only-with-adequate-alternatives chair, not a blanket criminal ban and not a protected right to camp anywhere.', ARRAY['https://hillsboronewstimes.com/2023/06/21/forest-grove-residents-blast-city-council-for-overnight-camping-regulations/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('homelessness-response', 3, 'On January 22, 2024 Gustafson joined the unanimous council vote denying the appeal against the Forest Grove Foundation''s transitional homeless pod village (12-16 heated sleeping pods plus a common building with kitchen, showers, and laundry at 2500 22nd Ave) — a services-centered transitional-shelter investment. Her official city bio ties homelessness directly to the opioid epidemic and what she describes as a lack of rehabilitation facilities and access to mental-health services, framing service capacity as the gap to close, and in her 2020 candidate Q&A she urged transferring responsibilities requiring social-work expertise away from police to "the appropriate expert field." Pairing that services orientation with the 2023 time-place-manner camping regulations she voted for (7-0, June 12, 2023) matches the invest-in-outreach-shelter-and-mental-health-services-while-enforcing-reasonable-public-space-rules chair, not housing-first-without-enforcement and not enforcement-as-the-primary-tool.', ARRAY['https://forestgrovenewstimes.com/2024/01/26/plans-for-new-forest-grove-homeless-pod-village-moves-forward-council-denies-appeal/', 'https://www.forestgrove-or.gov/611/Meet-the-Council', 'https://forestgrovenewstimes.com/2020/10/26/forest-grove-city-council-candidates-field-questions/']::text[]),
    ('local-immigration', 2, 'Gustafson joined the unanimous November 10, 2025 council vote declaring a state of emergency over federal immigration raids, authorizing up to $50,000 for community-based organizations assisting impacted residents, and on January 12, 2026 she voted with the 6-1 majority (Councilor Martinez the lone no on the seven-member council) to codify Oregon''s sanctuary protections into Forest Grove''s municipal code — directing the city manager to create staff policies and training on interactions with federal immigration enforcement, establishing reporting requirements, and defining "nonpublic" areas of city facilities that federal agents cannot enter without a warrant. Voting to codify rules that limit cooperation to what a warrant or court order compels, while funding aid to affected residents, matches the comply-only-with-court-ordered-cooperation-and-protect-residents chair — stronger than passive non-use of city resources, but short of a documented refusal of all detainers.', ARRAY['https://hillsboronewstimes.com/2026/01/14/forest-grove-affirms-its-a-sanctuary-city-in-6-1-vote-will-develop-new-internal-ice-policies/', 'https://forestgrovenewstimes.com/2025/11/11/forest-grove-declares-state-of-emergency-over-ice-raids/']::text[]),
    ('public-safety-approach', 2, 'In her October 2020 candidate Q&A Gustafson laid out a detailed policing program: transfer duties "which require a different expertise such as social work, student management etc.. to the appropriate expert field. Let peace officers be peace officers," alongside paid short-term sabbaticals for officers, more frequent psychiatric assessments, diversity and de-escalation education, a diverse Law Enforcement Review Board to review complaints and screen recruits, a no-tolerance policy on racism and police abuse, and a salary review "to encourage a higher recruit pool." In her first term she established a sabbatical program at the Forest Grove Police Department (cited in her September 2024 reelection announcement), and her 2024 platform lists "Law Enforcement Culture Transformation and Sustainability" as a priority. Sustaining the police force (including better pay and wellness) while shifting non-law-enforcement calls to unarmed experts matches the maintain-staffing-but-shift-nonviolent-calls-to-co-responders chair, not a budget-redirection agenda and not an expand-police-first stance.', ARRAY['https://forestgrovenewstimes.com/2020/10/26/forest-grove-city-council-candidates-field-questions/', 'https://forestgrovenewstimes.com/2024/09/20/donna-gustafson-seeks-reelection-to-forest-grove-city-council/', 'https://donnagustafsonforcitycouncil.com/']::text[]),
    ('growth-and-development', 2, 'In her October 2024 candidate Q&A Gustafson identified growth as the city''s biggest issue: "Forest Grove''s rapid growth has strained our infrastructure and challenged our livability," pointing to increased apartment and housing development creating traffic impacts and straining community resources, and calling for "strategic development" with investment in the necessary infrastructure, transportation options, green-space preservation, and local business support. Her 2024 campaign platform lists "Controlled Growth" as a standing priority. Treating existing infrastructure strain as the constraint on further development — growth conditioned on capacity rather than actively recruited or left to the market — matches the allow-growth-only-where-infrastructure-can-support-it chair; she has not proposed voter-approval growth caps or moratoria.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://donnagustafsonforcitycouncil.com/']::text[]),
    ('transportation-priorities', 2, 'Gustafson''s documented transportation agenda invests in roads and multimodal options together: in her October 2024 candidate Q&A she named sidewalks and bike lanes as her infrastructure priority — "They ensure safety, promote health, boost economies and foster equity" — while also emphasizing "effective traffic and transportation control" and lobbying for federal funding. In her 2020 candidate Q&A she proposed executing plans for sidewalks and bike lanes with ADA compliance, increasing GroveLink bus frequency, and building downtown parking structures. Championing bike lanes, sidewalks, and more frequent bus service alongside traffic management and added parking matches the invest-equally-in-roads-and-multimodal chair, not a transit-first/parking-reduction agenda and not a roads-only stance.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://forestgrovenewstimes.com/2020/10/26/forest-grove-city-council-candidates-field-questions/']::text[]),
    ('economic-development', 2, 'Gustafson''s documented economic-development record is entirely small-business and downtown centered: a former downtown small-business owner herself (Bella Donna''s Bistro & Patisserie on 21st Street), her October 2020 candidate Q&A proposed increased city financial support for downtown businesses, emergency business plans, subsidies for businesses offering Pacific University student discounts, and closer city-university collaboration, while her 2024 reelection platform lists "Downtown revitalization" and "Small Business Stability" as priorities and her October 2024 Q&A named downtown revitalization through supporting small businesses a top funding priority. As City Club of Forest Grove president she works on community revitalization outreach, per her official city bio. Nothing in her record involves recruiting major employers with tax abatements; this matches the small-business-support-and-local-entrepreneur-programs chair.', ARRAY['https://forestgrovenewstimes.com/2020/10/26/forest-grove-city-council-candidates-field-questions/', 'https://forestgrovenewstimes.com/2024/09/20/donna-gustafson-seeks-reelection-to-forest-grove-city-council/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('civil-rights', 2, 'In her October 2020 candidate Q&A on racial justice and policing, Gustafson proposed active institutional measures against discrimination: a "no-tolerance policy on racism, discrimination and police abuse with a swift and strict correction and termination philosophy," mandatory education and assessment of law enforcement personnel''s views on race, diversity, and de-escalation, and creation of a diverse Law Enforcement Review Board to review all complaints and screen new recruits for warning signs. Her 2024 campaign platform commits her to decision-making that weighs the needs of vulnerable and underserved populations. Proposing standing accountability institutions and mandatory anti-discrimination policies goes beyond maintaining existing law, matching the strengthen-enforcement-and-address-systemic-discrimination chair, though she has proposed no mandates across all institutions or reparations.', ARRAY['https://forestgrovenewstimes.com/2020/10/26/forest-grove-city-council-candidates-field-questions/', 'https://donnagustafsonforcitycouncil.com/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '47f5c014-2100-45cf-a4c7-da6b6782b6e5'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('homelessness', 3, 'Gustafson, on the council since her November 2020 election (seated January 2021), joined the unanimous 7-0 first-reading vote (June 12, 2023) adopting Forest Grove''s "time, place and manner" camping ordinance (Ordinance 2023-04, second reading June 26, 2023), which prohibits camping in parks and restricts overnight camping to the designated City Hall South Lot between 7 p.m. and 7 a.m. — written to satisfy Oregon''s HB 3115 requirement that cities set "objectively reasonable" rules for where camping is allowed when shelter is unavailable, the statewide codification that people cannot be punished for sleeping outside with no alternative. Her official city bio names homelessness first among the issues she is deeply concerned about, and she has paired the camping rules with support for transitional shelter (the January 22, 2024 pod-village appeal denial). Enforcement conditioned on the shelter-availability standard with a designated permitted overnight location matches the allow-enforcement-only-with-adequate-alternatives chair, not a blanket criminal ban and not a protected right to camp anywhere.', ARRAY['https://hillsboronewstimes.com/2023/06/21/forest-grove-residents-blast-city-council-for-overnight-camping-regulations/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('homelessness-response', 3, 'On January 22, 2024 Gustafson joined the unanimous council vote denying the appeal against the Forest Grove Foundation''s transitional homeless pod village (12-16 heated sleeping pods plus a common building with kitchen, showers, and laundry at 2500 22nd Ave) — a services-centered transitional-shelter investment. Her official city bio ties homelessness directly to the opioid epidemic and what she describes as a lack of rehabilitation facilities and access to mental-health services, framing service capacity as the gap to close, and in her 2020 candidate Q&A she urged transferring responsibilities requiring social-work expertise away from police to "the appropriate expert field." Pairing that services orientation with the 2023 time-place-manner camping regulations she voted for (7-0, June 12, 2023) matches the invest-in-outreach-shelter-and-mental-health-services-while-enforcing-reasonable-public-space-rules chair, not housing-first-without-enforcement and not enforcement-as-the-primary-tool.', ARRAY['https://forestgrovenewstimes.com/2024/01/26/plans-for-new-forest-grove-homeless-pod-village-moves-forward-council-denies-appeal/', 'https://www.forestgrove-or.gov/611/Meet-the-Council', 'https://forestgrovenewstimes.com/2020/10/26/forest-grove-city-council-candidates-field-questions/']::text[]),
    ('local-immigration', 2, 'Gustafson joined the unanimous November 10, 2025 council vote declaring a state of emergency over federal immigration raids, authorizing up to $50,000 for community-based organizations assisting impacted residents, and on January 12, 2026 she voted with the 6-1 majority (Councilor Martinez the lone no on the seven-member council) to codify Oregon''s sanctuary protections into Forest Grove''s municipal code — directing the city manager to create staff policies and training on interactions with federal immigration enforcement, establishing reporting requirements, and defining "nonpublic" areas of city facilities that federal agents cannot enter without a warrant. Voting to codify rules that limit cooperation to what a warrant or court order compels, while funding aid to affected residents, matches the comply-only-with-court-ordered-cooperation-and-protect-residents chair — stronger than passive non-use of city resources, but short of a documented refusal of all detainers.', ARRAY['https://hillsboronewstimes.com/2026/01/14/forest-grove-affirms-its-a-sanctuary-city-in-6-1-vote-will-develop-new-internal-ice-policies/', 'https://forestgrovenewstimes.com/2025/11/11/forest-grove-declares-state-of-emergency-over-ice-raids/']::text[]),
    ('public-safety-approach', 2, 'In her October 2020 candidate Q&A Gustafson laid out a detailed policing program: transfer duties "which require a different expertise such as social work, student management etc.. to the appropriate expert field. Let peace officers be peace officers," alongside paid short-term sabbaticals for officers, more frequent psychiatric assessments, diversity and de-escalation education, a diverse Law Enforcement Review Board to review complaints and screen recruits, a no-tolerance policy on racism and police abuse, and a salary review "to encourage a higher recruit pool." In her first term she established a sabbatical program at the Forest Grove Police Department (cited in her September 2024 reelection announcement), and her 2024 platform lists "Law Enforcement Culture Transformation and Sustainability" as a priority. Sustaining the police force (including better pay and wellness) while shifting non-law-enforcement calls to unarmed experts matches the maintain-staffing-but-shift-nonviolent-calls-to-co-responders chair, not a budget-redirection agenda and not an expand-police-first stance.', ARRAY['https://forestgrovenewstimes.com/2020/10/26/forest-grove-city-council-candidates-field-questions/', 'https://forestgrovenewstimes.com/2024/09/20/donna-gustafson-seeks-reelection-to-forest-grove-city-council/', 'https://donnagustafsonforcitycouncil.com/']::text[]),
    ('growth-and-development', 2, 'In her October 2024 candidate Q&A Gustafson identified growth as the city''s biggest issue: "Forest Grove''s rapid growth has strained our infrastructure and challenged our livability," pointing to increased apartment and housing development creating traffic impacts and straining community resources, and calling for "strategic development" with investment in the necessary infrastructure, transportation options, green-space preservation, and local business support. Her 2024 campaign platform lists "Controlled Growth" as a standing priority. Treating existing infrastructure strain as the constraint on further development — growth conditioned on capacity rather than actively recruited or left to the market — matches the allow-growth-only-where-infrastructure-can-support-it chair; she has not proposed voter-approval growth caps or moratoria.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://donnagustafsonforcitycouncil.com/']::text[]),
    ('transportation-priorities', 2, 'Gustafson''s documented transportation agenda invests in roads and multimodal options together: in her October 2024 candidate Q&A she named sidewalks and bike lanes as her infrastructure priority — "They ensure safety, promote health, boost economies and foster equity" — while also emphasizing "effective traffic and transportation control" and lobbying for federal funding. In her 2020 candidate Q&A she proposed executing plans for sidewalks and bike lanes with ADA compliance, increasing GroveLink bus frequency, and building downtown parking structures. Championing bike lanes, sidewalks, and more frequent bus service alongside traffic management and added parking matches the invest-equally-in-roads-and-multimodal chair, not a transit-first/parking-reduction agenda and not a roads-only stance.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://forestgrovenewstimes.com/2020/10/26/forest-grove-city-council-candidates-field-questions/']::text[]),
    ('economic-development', 2, 'Gustafson''s documented economic-development record is entirely small-business and downtown centered: a former downtown small-business owner herself (Bella Donna''s Bistro & Patisserie on 21st Street), her October 2020 candidate Q&A proposed increased city financial support for downtown businesses, emergency business plans, subsidies for businesses offering Pacific University student discounts, and closer city-university collaboration, while her 2024 reelection platform lists "Downtown revitalization" and "Small Business Stability" as priorities and her October 2024 Q&A named downtown revitalization through supporting small businesses a top funding priority. As City Club of Forest Grove president she works on community revitalization outreach, per her official city bio. Nothing in her record involves recruiting major employers with tax abatements; this matches the small-business-support-and-local-entrepreneur-programs chair.', ARRAY['https://forestgrovenewstimes.com/2020/10/26/forest-grove-city-council-candidates-field-questions/', 'https://forestgrovenewstimes.com/2024/09/20/donna-gustafson-seeks-reelection-to-forest-grove-city-council/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('civil-rights', 2, 'In her October 2020 candidate Q&A on racial justice and policing, Gustafson proposed active institutional measures against discrimination: a "no-tolerance policy on racism, discrimination and police abuse with a swift and strict correction and termination philosophy," mandatory education and assessment of law enforcement personnel''s views on race, diversity, and de-escalation, and creation of a diverse Law Enforcement Review Board to review all complaints and screen new recruits for warning signs. Her 2024 campaign platform commits her to decision-making that weighs the needs of vulnerable and underserved populations. Proposing standing accountability institutions and mandatory anti-discrimination policies goes beyond maintaining existing law, matching the strengthen-enforcement-and-address-systemic-discrimination chair, though she has proposed no mandates across all institutions or reparations.', ARRAY['https://forestgrovenewstimes.com/2020/10/26/forest-grove-city-council-candidates-field-questions/', 'https://donnagustafsonforcitycouncil.com/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '47f5c014-2100-45cf-a4c7-da6b6782b6e5'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = '47f5c014-2100-45cf-a4c7-da6b6782b6e5';
  IF v_ext IS DISTINCT FROM -4126205 THEN
    RAISE EXCEPTION 'UUID 47f5c014-2100-45cf-a4c7-da6b6782b6e5 does not belong to external_id -4126205 (Donna Gustafson) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = '47f5c014-2100-45cf-a4c7-da6b6782b6e5';
  IF n <> 8 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 8, n;
  END IF;
  -- Context-parity gate (WR-03): the context VALUES list is a verbatim
  -- duplicate of the answers list; count it too so a single-sided edit
  -- cannot silently drop or skew reasoning/sources rows.
  SELECT COUNT(*) INTO n FROM inform.politician_context WHERE politician_id = '47f5c014-2100-45cf-a4c7-da6b6782b6e5';
  IF n <> 8 THEN
    RAISE EXCEPTION 'Expected % context rows, found % — answers/context VALUES lists diverged', 8, n;
  END IF;
END $$;

COMMIT;
