-- Migration 1185: Angel Falconer (City Councilor, Forest Grove OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 8 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).
-- Tenure guard: Falconer's Forest Grove seat begins with her November 2024 election (seated January 2025).
-- Her 2016/council-president/2020 history is Milwaukie, OR — no Milwaukie council vote is cited as Forest
-- Grove evidence; where her own 2024 campaign statements describe Milwaukie-era work, that framing is explicit.

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'In her October 2024 candidate Q&A, Falconer — elected to the Forest Grove council in November 2024 and seated January 2025 — named "housing affordability and choice" her top funding priority, describing "many years of experience working alongside advocates, providers and policymakers to create policies and programs that address housing choice and affordability for all" and arguing the housing stock "must include a mix of options to fit all residents'' needs at every stage of life." In her October 2024 Washington County Democrats interview she pushed for a conversation beyond "No new development. Keep people out," said Forest Grove''s sprawling, car-dependent development pattern keeps prices high, and proposed addressing farmworker housing through partnerships with local farmers; her campaign platform pairs "planned development that welcomes residents without displacement" with collaboration across local, regional, and state partners. A programs-and-partnerships agenda — creating affordability policies and programs with providers, diversifying housing types, and reviewing the development code — matches the targeted-help chair (subsidies for affordable projects and easier building approvals), not documented advocacy for rent caps or inclusionary mandates, and not a deregulate-and-step-back stance.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://washcodems.org/2024/10/06/angel-falconer-forest-grove-city-council-candidate-interview/', 'https://www.angelfalconer.com/']::text[]),
    ('residential-zoning', 3, 'Falconer''s October 2024 candidate Q&A argues Forest Grove''s housing stock "must include a mix of options to fit all residents'' needs at every stage of life," and her October 2024 Washington County Democrats interview names a comprehensive-plan and development-code review as the first of her four primary goals — diagnosing the city''s sprawling, car-dependent development pattern as what keeps prices high and endorsing the integration of local shops into walkable neighborhoods. Welcoming a broader mix of housing types and mixed-use, walkable development through a code update matches the allow-multifamily-and-mixed-use-near-commercial-corridors chair: she has not advocated eliminating single-family-only zoning citywide or blanket by-right upzoning, nor community-vote gatekeeping to protect existing neighborhood character.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://washcodems.org/2024/10/06/angel-falconer-forest-grove-city-council-candidate-interview/']::text[]),
    ('growth-and-development', 3, 'In her October 2024 candidate Q&A Falconer framed Forest Grove''s growth as an opportunity rather than a crisis and called for "working collaboratively with state agencies, the county, Metro, local community organizations" instead of isolation, while her campaign platform commits to planned development that welcomes new residents without displacing longtime ones. Her official city bio records her enthusiasm for the city''s 2040 Visioning project — "to develop a strategy for the next 20 years to build a self-reliant and resilient community" — and her Washington County Democrats interview makes a comprehensive-plan and development-code review her first primary goal. Planning deliberately for expected growth through long-range visioning, code modernization, and regional coordination matches the plan-proactively-and-invest-ahead-of-growth chair, not a slow-approvals infrastructure-gating posture and not an active-recruitment deregulation agenda.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://www.angelfalconer.com/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('transportation-priorities', 2, 'Falconer''s October 2024 candidate Q&A names her infrastructure priority as "safe and accessible transportation options for all" — safe routes to school and ADA-compliant connections to transit and services — alongside maintaining local street infrastructure and pursuing regional partnerships, and her campaign platform makes the same pairing of active-transportation investment with street maintenance. Her statement that she "led the creation of a program to create safe routes to school" describes her earlier service in Milwaukie, OR (her own 2024 campaign account of her pre-Forest-Grove record, cited here as her stated position, not as a Forest Grove action). Her October 2024 Washington County Democrats interview lists transportation and active networks among her four primary goals, with investment in transit accessibility. Championing sidewalks, safe routes, ADA transit access, and active networks while committing to keep maintaining streets matches the invest-equally-in-roads-and-multimodal chair; she has not documented a parking-reduction, transit-first agenda or a roads-first stance.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://www.angelfalconer.com/', 'https://washcodems.org/2024/10/06/angel-falconer-forest-grove-city-council-candidate-interview/']::text[]),
    ('climate-change', 3, 'Climate action is one of the four pillars of Falconer''s 2024 Forest Grove campaign platform, which advocates local adaptation and resilience strategies, and her official city bio ties her long-term climate and sustainability goals to her transportation focus. In her October 2024 Washington County Democrats interview she said "Taking stock is the first step," proposing a city emissions audit, reinstating the sustainability commission Forest Grove had disbanded, and promoting sustainable building practices, urban forestry, and transit accessibility. Her campaign statement that she "helped create the city''s first Climate Action Plan" refers to Milwaukie, OR — her own 2024 first-party account of pre-Forest-Grove work, cited as her position, not a Forest Grove action. A concrete local clean-investment and emissions-planning agenda, without a documented commitment to a fossil-fuel phase-out deadline or emergency-ban framework, matches the invest-in-clean-energy-while-gradually-reducing-fossil-fuel-reliance chair.', ARRAY['https://washcodems.org/2024/10/06/angel-falconer-forest-grove-city-council-candidate-interview/', 'https://www.angelfalconer.com/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('local-immigration', 2, 'Falconer, seated on the seven-member Forest Grove council in January 2025, joined the unanimous November 10, 2025 vote declaring a state of emergency over federal immigration raids, authorizing up to $50,000 for community-based organizations assisting impacted residents, and on January 12, 2026 she voted with the 6-1 majority (Councilor Martinez the lone no) to codify Oregon''s sanctuary protections into Forest Grove''s municipal code — prohibiting city resources from assisting federal immigration enforcement, directing the city manager to create staff policies and training on interactions with federal agents, establishing reporting requirements, and defining "nonpublic" areas of city facilities that federal agents cannot enter without a warrant. Voting to codify rules that limit cooperation to what a warrant or court order compels, while funding aid to affected residents, matches the comply-only-with-court-ordered-cooperation-and-protect-residents chair — stronger than passive non-use of city resources, but short of a documented refusal of all detainers.', ARRAY['https://hillsboronewstimes.com/2026/01/14/forest-grove-affirms-its-a-sanctuary-city-in-6-1-vote-will-develop-new-internal-ice-policies/', 'https://forestgrovenewstimes.com/2025/11/11/forest-grove-declares-state-of-emergency-over-ice-raids/']::text[]),
    ('immigration', 2, 'In her October 2024 Washington County Democrats interview Falconer confronted anti-immigrant rhetoric directly: "This idea that immigrants are the reason for our housing shortage is a new concept for me," calling the scapegoating of immigrants "disgusting," invoking Springfield, Ohio''s positive experience with immigration, and pledging to "speak strongly against that kind of hateful scapegoating." As a Forest Grove councilor she then voted for the November 10, 2025 emergency declaration funding community organizations that serve residents affected by federal immigration enforcement regardless of status, and for the January 12, 2026 sanctuary codification (6-1). A welcoming posture that extends city protections and emergency services to residents regardless of legal status matches the keep-legal-immigration-open-and-let-most-residents-use-public-services chair; she has no documented platform for expanding legal-immigration pathways beyond current law, and nothing in her record is restrictionist.', ARRAY['https://washcodems.org/2024/10/06/angel-falconer-forest-grove-city-council-candidate-interview/', 'https://forestgrovenewstimes.com/2025/11/11/forest-grove-declares-state-of-emergency-over-ice-raids/', 'https://hillsboronewstimes.com/2026/01/14/forest-grove-affirms-its-a-sanctuary-city-in-6-1-vote-will-develop-new-internal-ice-policies/']::text[]),
    ('economic-development', 2, 'Supporting small businesses through neighborhood integration is one of the four primary goals Falconer laid out in her October 2024 Washington County Democrats interview: she tied the lack of foot traffic for local shops to Forest Grove''s car-dependent design and endorsed creating business hubs with multilingual resources and integrating local businesses into walkable neighborhoods. Her campaign platform likewise centers local livability and collaboration rather than employer recruitment. Nothing in her documented record involves competing for major employers with tax abatements or incentive packages; a locally focused small-business and entrepreneur-support agenda matches the small-business-support-and-local-entrepreneur-programs chair.', ARRAY['https://washcodems.org/2024/10/06/angel-falconer-forest-grove-city-council-candidate-interview/', 'https://www.angelfalconer.com/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '8a09c44f-b45f-4ece-9636-4d49b4a09679'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'In her October 2024 candidate Q&A, Falconer — elected to the Forest Grove council in November 2024 and seated January 2025 — named "housing affordability and choice" her top funding priority, describing "many years of experience working alongside advocates, providers and policymakers to create policies and programs that address housing choice and affordability for all" and arguing the housing stock "must include a mix of options to fit all residents'' needs at every stage of life." In her October 2024 Washington County Democrats interview she pushed for a conversation beyond "No new development. Keep people out," said Forest Grove''s sprawling, car-dependent development pattern keeps prices high, and proposed addressing farmworker housing through partnerships with local farmers; her campaign platform pairs "planned development that welcomes residents without displacement" with collaboration across local, regional, and state partners. A programs-and-partnerships agenda — creating affordability policies and programs with providers, diversifying housing types, and reviewing the development code — matches the targeted-help chair (subsidies for affordable projects and easier building approvals), not documented advocacy for rent caps or inclusionary mandates, and not a deregulate-and-step-back stance.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://washcodems.org/2024/10/06/angel-falconer-forest-grove-city-council-candidate-interview/', 'https://www.angelfalconer.com/']::text[]),
    ('residential-zoning', 3, 'Falconer''s October 2024 candidate Q&A argues Forest Grove''s housing stock "must include a mix of options to fit all residents'' needs at every stage of life," and her October 2024 Washington County Democrats interview names a comprehensive-plan and development-code review as the first of her four primary goals — diagnosing the city''s sprawling, car-dependent development pattern as what keeps prices high and endorsing the integration of local shops into walkable neighborhoods. Welcoming a broader mix of housing types and mixed-use, walkable development through a code update matches the allow-multifamily-and-mixed-use-near-commercial-corridors chair: she has not advocated eliminating single-family-only zoning citywide or blanket by-right upzoning, nor community-vote gatekeeping to protect existing neighborhood character.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://washcodems.org/2024/10/06/angel-falconer-forest-grove-city-council-candidate-interview/']::text[]),
    ('growth-and-development', 3, 'In her October 2024 candidate Q&A Falconer framed Forest Grove''s growth as an opportunity rather than a crisis and called for "working collaboratively with state agencies, the county, Metro, local community organizations" instead of isolation, while her campaign platform commits to planned development that welcomes new residents without displacing longtime ones. Her official city bio records her enthusiasm for the city''s 2040 Visioning project — "to develop a strategy for the next 20 years to build a self-reliant and resilient community" — and her Washington County Democrats interview makes a comprehensive-plan and development-code review her first primary goal. Planning deliberately for expected growth through long-range visioning, code modernization, and regional coordination matches the plan-proactively-and-invest-ahead-of-growth chair, not a slow-approvals infrastructure-gating posture and not an active-recruitment deregulation agenda.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://www.angelfalconer.com/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('transportation-priorities', 2, 'Falconer''s October 2024 candidate Q&A names her infrastructure priority as "safe and accessible transportation options for all" — safe routes to school and ADA-compliant connections to transit and services — alongside maintaining local street infrastructure and pursuing regional partnerships, and her campaign platform makes the same pairing of active-transportation investment with street maintenance. Her statement that she "led the creation of a program to create safe routes to school" describes her earlier service in Milwaukie, OR (her own 2024 campaign account of her pre-Forest-Grove record, cited here as her stated position, not as a Forest Grove action). Her October 2024 Washington County Democrats interview lists transportation and active networks among her four primary goals, with investment in transit accessibility. Championing sidewalks, safe routes, ADA transit access, and active networks while committing to keep maintaining streets matches the invest-equally-in-roads-and-multimodal chair; she has not documented a parking-reduction, transit-first agenda or a roads-first stance.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://www.angelfalconer.com/', 'https://washcodems.org/2024/10/06/angel-falconer-forest-grove-city-council-candidate-interview/']::text[]),
    ('climate-change', 3, 'Climate action is one of the four pillars of Falconer''s 2024 Forest Grove campaign platform, which advocates local adaptation and resilience strategies, and her official city bio ties her long-term climate and sustainability goals to her transportation focus. In her October 2024 Washington County Democrats interview she said "Taking stock is the first step," proposing a city emissions audit, reinstating the sustainability commission Forest Grove had disbanded, and promoting sustainable building practices, urban forestry, and transit accessibility. Her campaign statement that she "helped create the city''s first Climate Action Plan" refers to Milwaukie, OR — her own 2024 first-party account of pre-Forest-Grove work, cited as her position, not a Forest Grove action. A concrete local clean-investment and emissions-planning agenda, without a documented commitment to a fossil-fuel phase-out deadline or emergency-ban framework, matches the invest-in-clean-energy-while-gradually-reducing-fossil-fuel-reliance chair.', ARRAY['https://washcodems.org/2024/10/06/angel-falconer-forest-grove-city-council-candidate-interview/', 'https://www.angelfalconer.com/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('local-immigration', 2, 'Falconer, seated on the seven-member Forest Grove council in January 2025, joined the unanimous November 10, 2025 vote declaring a state of emergency over federal immigration raids, authorizing up to $50,000 for community-based organizations assisting impacted residents, and on January 12, 2026 she voted with the 6-1 majority (Councilor Martinez the lone no) to codify Oregon''s sanctuary protections into Forest Grove''s municipal code — prohibiting city resources from assisting federal immigration enforcement, directing the city manager to create staff policies and training on interactions with federal agents, establishing reporting requirements, and defining "nonpublic" areas of city facilities that federal agents cannot enter without a warrant. Voting to codify rules that limit cooperation to what a warrant or court order compels, while funding aid to affected residents, matches the comply-only-with-court-ordered-cooperation-and-protect-residents chair — stronger than passive non-use of city resources, but short of a documented refusal of all detainers.', ARRAY['https://hillsboronewstimes.com/2026/01/14/forest-grove-affirms-its-a-sanctuary-city-in-6-1-vote-will-develop-new-internal-ice-policies/', 'https://forestgrovenewstimes.com/2025/11/11/forest-grove-declares-state-of-emergency-over-ice-raids/']::text[]),
    ('immigration', 2, 'In her October 2024 Washington County Democrats interview Falconer confronted anti-immigrant rhetoric directly: "This idea that immigrants are the reason for our housing shortage is a new concept for me," calling the scapegoating of immigrants "disgusting," invoking Springfield, Ohio''s positive experience with immigration, and pledging to "speak strongly against that kind of hateful scapegoating." As a Forest Grove councilor she then voted for the November 10, 2025 emergency declaration funding community organizations that serve residents affected by federal immigration enforcement regardless of status, and for the January 12, 2026 sanctuary codification (6-1). A welcoming posture that extends city protections and emergency services to residents regardless of legal status matches the keep-legal-immigration-open-and-let-most-residents-use-public-services chair; she has no documented platform for expanding legal-immigration pathways beyond current law, and nothing in her record is restrictionist.', ARRAY['https://washcodems.org/2024/10/06/angel-falconer-forest-grove-city-council-candidate-interview/', 'https://forestgrovenewstimes.com/2025/11/11/forest-grove-declares-state-of-emergency-over-ice-raids/', 'https://hillsboronewstimes.com/2026/01/14/forest-grove-affirms-its-a-sanctuary-city-in-6-1-vote-will-develop-new-internal-ice-policies/']::text[]),
    ('economic-development', 2, 'Supporting small businesses through neighborhood integration is one of the four primary goals Falconer laid out in her October 2024 Washington County Democrats interview: she tied the lack of foot traffic for local shops to Forest Grove''s car-dependent design and endorsed creating business hubs with multilingual resources and integrating local businesses into walkable neighborhoods. Her campaign platform likewise centers local livability and collaboration rather than employer recruitment. Nothing in her documented record involves competing for major employers with tax abatements or incentive packages; a locally focused small-business and entrepreneur-support agenda matches the small-business-support-and-local-entrepreneur-programs chair.', ARRAY['https://washcodems.org/2024/10/06/angel-falconer-forest-grove-city-council-candidate-interview/', 'https://www.angelfalconer.com/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '8a09c44f-b45f-4ece-9636-4d49b4a09679'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = '8a09c44f-b45f-4ece-9636-4d49b4a09679';
  IF v_ext IS DISTINCT FROM -4126206 THEN
    RAISE EXCEPTION 'UUID 8a09c44f-b45f-4ece-9636-4d49b4a09679 does not belong to external_id -4126206 (Angel Falconer) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = '8a09c44f-b45f-4ece-9636-4d49b4a09679';
  IF n <> 8 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 8, n;
  END IF;
  -- Context-parity gate (WR-03): the context VALUES list is a verbatim
  -- duplicate of the answers list; count it too so a single-sided edit
  -- cannot silently drop or skew reasoning/sources rows.
  SELECT COUNT(*) INTO n FROM inform.politician_context WHERE politician_id = '8a09c44f-b45f-4ece-9636-4d49b4a09679';
  IF n <> 8 THEN
    RAISE EXCEPTION 'Expected % context rows, found % — answers/context VALUES lists diverged', 8, n;
  END IF;
END $$;

COMMIT;
