-- Migration 1186: Brian Schimmel (City Councilor, Forest Grove OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 6 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).
-- Tenure guard: Schimmel was elected November 2024 and seated January 2025. Forest Grove council actions
-- that pre-date his seating (the June 2023 camping ordinance, the January 2024 pod-village appeal) are NOT
-- cited as his votes; only January 2025+ council actions and his own 2024 campaign statements are used.
-- No content about or from his 2024 opponent is cited anywhere in this file.

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'In his October 2024 candidate Q&A, Schimmel — elected to the Forest Grove council in November 2024 and seated January 2025 — named housing his top funding priority: "I will pursue housing policies that steer public and private investments into affordable housing," aimed at creating and preserving homes for low- and middle-income families, and he added that his own household is "building a custom accessory dwelling unit (ADU) in our backyard to contribute to deeply affordable housing in Forest Grove." His September 2024 candidacy announcement framed the goal as "implementing effective housing policies reflective of Forest Grove''s small size," and his official city bio lists diverse housing options among his priorities. Steering targeted public and private investment into affordable projects while personally adding ADU capacity matches the targeted-help chair (subsidies for affordable projects and easier building approvals) — he has no documented advocacy for rent caps, inclusionary mandates, or city-built public housing, and his posture is not deregulate-and-step-back.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://forestgrovenewstimes.com/2024/09/20/brian-schimmel-runs-for-forest-grove-city-council/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('transportation-priorities', 2, 'Schimmel''s October 2024 candidate Q&A names transportation modernization as his infrastructure priority: "We need to invest in modernizing transportation networks, including safer roads, improving public transit options and enhancing pedestrian walkways" to support a more accessible, connected city, and his second-ranked funding priority is infrastructure improvements including sustainable transportation. His official city bio likewise pairs transportation and infrastructure improvements with housing options among his core priorities. Committing investment across roads, transit, and pedestrian infrastructure together matches the invest-equally-in-roads-and-multimodal chair — he has not documented a transit-first parking-reduction agenda, nor a roads-and-traffic-flow-first stance.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('climate-change', 3, 'In his October 2024 candidate Q&A Schimmel made "infrastructure improvements including sustainable transportation and green energy" his second-ranked funding priority, and cited his service on the Forest Grove Sustainability Commission among the experiences preparing him for the council seat he won in November 2024 (seated January 2025). His official city bio emphasizes balancing immediate concerns with sustainable, forward-thinking policies and long-term resilience. A concrete local green-energy and sustainable-transportation investment agenda, without any documented commitment to a fossil-fuel phase-out deadline or emergency-ban framework, matches the invest-in-clean-energy-while-gradually-reducing-fossil-fuel-reliance chair.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('public-safety-approach', 4, 'In his October 2024 candidate Q&A Schimmel advocated for "the construction of a new police station to better serve the growing population and improve public safety," and ranked community services "like public safety and youth recreation" third among his funding priorities. Championing new capital investment in police facilities to improve service to a growing city matches the increase-police-capacity chair (more staffing, equipment, and facilities to improve response and deter crime) more closely than a flat-funding-plus-crisis-teams posture — he has no documented co-responder or budget-reallocation agenda — while his ranking of public safety behind housing and infrastructure, alongside youth recreation, shows it is not his top spending priority over other municipal services.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/']::text[]),
    ('economic-development', 3, 'Schimmel''s September 2024 candidacy announcement committed him to promoting local businesses, attracting new investment into the city, and lowering barriers to community engagement, and in his October 2024 candidate Q&A he diagnosed that "economic growth hasn''t kept pace to provide living wages and job opportunities" — pairing investment attraction with an explicit job-quality lens. Welcoming new investment while centering local businesses and living-wage outcomes matches the targeted-incentives-with-community-benefit-and-job-quality chair: his documented posture is neither small-business-only with subsidies foreclosed, nor active recruitment of major employers through significant tax abatements.', ARRAY['https://forestgrovenewstimes.com/2024/09/20/brian-schimmel-runs-for-forest-grove-city-council/', 'https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/']::text[]),
    ('local-immigration', 2, 'Schimmel, seated on the seven-member Forest Grove council in January 2025, joined the unanimous November 10, 2025 vote declaring a state of emergency over federal immigration raids, authorizing up to $50,000 for community-based organizations assisting impacted residents, and on January 12, 2026 he voted with the 6-1 majority (Councilor Martinez the lone no on the seven-member council) to codify Oregon''s sanctuary protections into Forest Grove''s municipal code — prohibiting city resources from assisting federal immigration enforcement, directing the city manager to create staff policies and training on interactions with federal agents, establishing reporting requirements, and defining "nonpublic" areas of city facilities that federal agents cannot enter without a warrant. Voting to codify rules that limit cooperation to what a warrant or court order compels, while funding aid to affected residents, matches the comply-only-with-court-ordered-cooperation-and-protect-residents chair — stronger than passive non-use of city resources, but short of a documented refusal of all detainers.', ARRAY['https://hillsboronewstimes.com/2026/01/14/forest-grove-affirms-its-a-sanctuary-city-in-6-1-vote-will-develop-new-internal-ice-policies/', 'https://forestgrovenewstimes.com/2025/11/11/forest-grove-declares-state-of-emergency-over-ice-raids/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT '01e1da66-778b-4bac-9a41-9c7fa9f3bbc3'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('housing', 3, 'In his October 2024 candidate Q&A, Schimmel — elected to the Forest Grove council in November 2024 and seated January 2025 — named housing his top funding priority: "I will pursue housing policies that steer public and private investments into affordable housing," aimed at creating and preserving homes for low- and middle-income families, and he added that his own household is "building a custom accessory dwelling unit (ADU) in our backyard to contribute to deeply affordable housing in Forest Grove." His September 2024 candidacy announcement framed the goal as "implementing effective housing policies reflective of Forest Grove''s small size," and his official city bio lists diverse housing options among his priorities. Steering targeted public and private investment into affordable projects while personally adding ADU capacity matches the targeted-help chair (subsidies for affordable projects and easier building approvals) — he has no documented advocacy for rent caps, inclusionary mandates, or city-built public housing, and his posture is not deregulate-and-step-back.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://forestgrovenewstimes.com/2024/09/20/brian-schimmel-runs-for-forest-grove-city-council/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('transportation-priorities', 2, 'Schimmel''s October 2024 candidate Q&A names transportation modernization as his infrastructure priority: "We need to invest in modernizing transportation networks, including safer roads, improving public transit options and enhancing pedestrian walkways" to support a more accessible, connected city, and his second-ranked funding priority is infrastructure improvements including sustainable transportation. His official city bio likewise pairs transportation and infrastructure improvements with housing options among his core priorities. Committing investment across roads, transit, and pedestrian infrastructure together matches the invest-equally-in-roads-and-multimodal chair — he has not documented a transit-first parking-reduction agenda, nor a roads-and-traffic-flow-first stance.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('climate-change', 3, 'In his October 2024 candidate Q&A Schimmel made "infrastructure improvements including sustainable transportation and green energy" his second-ranked funding priority, and cited his service on the Forest Grove Sustainability Commission among the experiences preparing him for the council seat he won in November 2024 (seated January 2025). His official city bio emphasizes balancing immediate concerns with sustainable, forward-thinking policies and long-term resilience. A concrete local green-energy and sustainable-transportation investment agenda, without any documented commitment to a fossil-fuel phase-out deadline or emergency-ban framework, matches the invest-in-clean-energy-while-gradually-reducing-fossil-fuel-reliance chair.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/', 'https://www.forestgrove-or.gov/611/Meet-the-Council']::text[]),
    ('public-safety-approach', 4, 'In his October 2024 candidate Q&A Schimmel advocated for "the construction of a new police station to better serve the growing population and improve public safety," and ranked community services "like public safety and youth recreation" third among his funding priorities. Championing new capital investment in police facilities to improve service to a growing city matches the increase-police-capacity chair (more staffing, equipment, and facilities to improve response and deter crime) more closely than a flat-funding-plus-crisis-teams posture — he has no documented co-responder or budget-reallocation agenda — while his ranking of public safety behind housing and infrastructure, alongside youth recreation, shows it is not his top spending priority over other municipal services.', ARRAY['https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/']::text[]),
    ('economic-development', 3, 'Schimmel''s September 2024 candidacy announcement committed him to promoting local businesses, attracting new investment into the city, and lowering barriers to community engagement, and in his October 2024 candidate Q&A he diagnosed that "economic growth hasn''t kept pace to provide living wages and job opportunities" — pairing investment attraction with an explicit job-quality lens. Welcoming new investment while centering local businesses and living-wage outcomes matches the targeted-incentives-with-community-benefit-and-job-quality chair: his documented posture is neither small-business-only with subsidies foreclosed, nor active recruitment of major employers through significant tax abatements.', ARRAY['https://forestgrovenewstimes.com/2024/09/20/brian-schimmel-runs-for-forest-grove-city-council/', 'https://hillsboronewstimes.com/2024/10/01/candidate-qa-forest-grove-city-council-candidates-talk-housing-charter-changes-and-more/']::text[]),
    ('local-immigration', 2, 'Schimmel, seated on the seven-member Forest Grove council in January 2025, joined the unanimous November 10, 2025 vote declaring a state of emergency over federal immigration raids, authorizing up to $50,000 for community-based organizations assisting impacted residents, and on January 12, 2026 he voted with the 6-1 majority (Councilor Martinez the lone no on the seven-member council) to codify Oregon''s sanctuary protections into Forest Grove''s municipal code — prohibiting city resources from assisting federal immigration enforcement, directing the city manager to create staff policies and training on interactions with federal agents, establishing reporting requirements, and defining "nonpublic" areas of city facilities that federal agents cannot enter without a warrant. Voting to codify rules that limit cooperation to what a warrant or court order compels, while funding aid to affected residents, matches the comply-only-with-court-ordered-cooperation-and-protect-residents chair — stronger than passive non-use of city resources, but short of a documented refusal of all detainers.', ARRAY['https://hillsboronewstimes.com/2026/01/14/forest-grove-affirms-its-a-sanctuary-city-in-6-1-vote-will-develop-new-internal-ice-policies/', 'https://forestgrovenewstimes.com/2025/11/11/forest-grove-declares-state-of-emergency-over-ice-raids/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT '01e1da66-778b-4bac-9a41-9c7fa9f3bbc3'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = '01e1da66-778b-4bac-9a41-9c7fa9f3bbc3';
  IF v_ext IS DISTINCT FROM -4126207 THEN
    RAISE EXCEPTION 'UUID 01e1da66-778b-4bac-9a41-9c7fa9f3bbc3 does not belong to external_id -4126207 (Brian Schimmel) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = '01e1da66-778b-4bac-9a41-9c7fa9f3bbc3';
  IF n <> 6 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 6, n;
  END IF;
  -- Context-parity gate (WR-03): the context VALUES list is a verbatim
  -- duplicate of the answers list; count it too so a single-sided edit
  -- cannot silently drop or skew reasoning/sources rows.
  SELECT COUNT(*) INTO n FROM inform.politician_context WHERE politician_id = '01e1da66-778b-4bac-9a41-9c7fa9f3bbc3';
  IF n <> 6 THEN
    RAISE EXCEPTION 'Expected % context rows, found % — answers/context VALUES lists diverged', 6, n;
  END IF;
END $$;

COMMIT;
