-- Migration 1189: Tim Rosener (Mayor, Sherwood OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 7 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('growth-and-development', 1, 'Rosener presided over the October 28, 2025 special session at which the council adopted, 7:0 with his vote, Resolutions 2025-073/074/075 referring two City Charter amendments; the minutes record him saying "local control was important and should be enshrined in the Charter" and urging the emergency election so voters could act "before the next legislative session in Salem." Measure 34-348 wrote into the Charter that "annexation may only take effect with the approval of city voters" (except declared public-health emergencies) and that these procedures "shall not be preempted by state laws," while Measure 34-347 bars any Type III or higher development from being decided without at least one neighborhood meeting and one public hearing; voters ratified them January 13, 2026 (82.71% and 94.23% yes per his blog). He frames this as pro-growth-on-community-terms ("These Charter amendments are not about opposing growth; they are about ensuring Sherwood grows on our terms"), but the operative policy he championed — voter approval as a precondition for annexations and charter-locked procedural gates before large-scale developments — is the voter-approval-gate chair, deliberately entrenched against state housing-production mandates like SB 974.', ARRAY['https://www.sherwoodoregon.gov/wp-content/uploads/2025/12/10.28.2025-City-Council-Meeting-Minutes.pdf', 'https://rosener.com/therosenercorner/2025/1/9/zuhok11ucuf3ja521az38lu4sspokc-rwfft-dd9sm-tprwf', 'https://rosener.com/therosenercorner/2025/1/9/zuhok11ucuf3ja521az38lu4sspokc-rwfft-dd9sm-tprwf-m4z8z-a77yz', 'https://www.opb.org/article/2026/01/18/sherwood-votes-overwhelmingly-to-challenge-new-state-housing-laws/']::text[]),
    ('residential-zoning', 2, 'In his December 31, 2025 blog post Rosener argued that state laws "such as HB 2001 (2019), SB 1537 (2024), and SB 974 (2025) have steadily eroded cities'' ability to manage growth" and that housing types should be decided by "the community," not "out-of-town developers." His alternative is the community-developed Sherwood West Plan, which designates "specific areas for duplexes and townhomes" and guarantees "cottage clusters and middle housing" for affordability while preserving "traditional single-family detached neighborhoods"; his January 2026 post reiterates the plan targets "cottage clusters, townhomes, and plexes" for affordability. He simultaneously championed Charter Measure 34-347 requiring a neighborhood meeting, a public hearing, and 1,000-foot mailed notice before significant land-use decisions. Accepting modest middle-housing density in designated areas under strong neighborhood-input requirements — while opposing state-mandated broad upzoning — matches the modest-density-with-neighborhood-input chair.', ARRAY['https://rosener.com/therosenercorner/2025/1/9/zuhok11ucuf3ja521az38lu4sspokc-rwfft-dd9sm-tprwf-m4z8z', 'https://rosener.com/therosenercorner/2025/1/9/zuhok11ucuf3ja521az38lu4sspokc-rwfft-dd9sm-tprwf-m4z8z-a77yz', 'https://www.sherwoodoregon.gov/wp-content/uploads/2025/12/10.28.2025-City-Council-Meeting-Minutes.pdf']::text[]),
    ('housing', 3, 'Rosener acknowledges "a regional housing crisis" and wrote after the January 2026 charter vote that "We are ready and willing to do our part to solve the regional housing crisis," pointing to the nearly 1,300-acre Sherwood West plan in which the city itself designates and guarantees middle-housing types — "cottage clusters, townhomes, and plexes" — specifically for affordability. In his September 2023 "Balancing Act" post he called for Sherwood to "diversify our housing options," and he told Tigard Life in September 2025 that Sherwood has "invested local funds and staff capacity into homelessness response and housing affordability efforts." He rejects the pure-deregulation path — publicly opposing SB 974 and similar bills that bypass local planning — and has proposed no rent caps or city-built public housing; city-led planning that carves out and enables affordable and middle housing, backed by local funds for affordability efforts, matches the targeted-help chair.', ARRAY['https://rosener.com/therosenercorner/2025/1/9/zuhok11ucuf3ja521az38lu4sspokc-rwfft-dd9sm-tprwf-m4z8z-a77yz', 'https://rosener.com/therosenercorner/2024/2/9/mayors-corner-keeping-the-water-turned-on-ejdng', 'https://tigardlife.com/featured/as-homelessness-surges-tigard-revisits-regulations-questions-equity-of-shared-response/']::text[]),
    ('transportation-priorities', 2, 'Rosener championed and publicly defended Sherwood''s $30 million pedestrian and bicycle bridge over Highway 99W (roughly $4 million in state lottery funds plus about $24-26 million in urban-renewal tax-increment financing), writing in May 2025 that it "represents more than just improved transportation; it''s a commitment to public safety, accessibility, and responsible growth," providing "a safe, ADA-compliant route for pedestrians and cyclists" and connecting schools and trail systems. His published mayoral priorities pair that multimodal investment with road work: championing "traffic calming and congestion solutions," ensuring student safety on roads and trails to schools, and securing state/federal funding for a grade-separated crossing at Cedar Creek. Committing major capital to walking/biking infrastructure alongside continued road and congestion investment matches the invest-in-both-roads-and-multimodal chair, not a transit-first posture with reduced parking.', ARRAY['https://rosener.com/therosenercorner/2025/1/9/zuhok11ucuf3ja521az38lu4sspokc-rwfft', 'https://rosener.com/priorities']::text[]),
    ('public-safety-approach', 4, 'In a March 18, 2026 Sherwood Sun interview Rosener made clear he wants more police resources: "Our police department does an amazing job. We''re not staffed at the same level as on a per capita basis as some of the agencies around us, but it''s expensive," adding "We''re talking right now about other revenue sources for the police department... There have been talks of a levy, maybe a fee," and warning "If you get behind on public safety, it''s really hard to catch up." Police are already the top general-fund cost, yet he is pursuing new dedicated revenue to raise staffing toward peer-agency levels rather than reallocating away from police; Sherwood''s mental-health crisis response is handled through a county partnership he cites (co-funding Washington County''s Mental Health Response Team with Tigard and Tualatin, $24,539 last fiscal year). Seeking additional revenue to expand police staffing matches the increase-police-investment chair.', ARRAY['https://www.sherwoodsun.org/sherwood-mayor-tim-rosener-highlights-progress-eyes-future-challenges/', 'https://tigardlife.com/featured/as-homelessness-surges-tigard-revisits-regulations-questions-equity-of-shared-response/']::text[]),
    ('homelessness-response', 3, 'Rosener''s documented strategy is services investment through regional partnership: he told Tigard Life (September 10, 2025) that Sherwood has "invested local funds and staff capacity into homelessness response," co-funds Washington County''s Mental Health Response Team with Tigard and Tualatin ($24,539 in the last fiscal year), donates $10,000 annually to the Family Justice Center, and serves on Metro''s President''s Work Group advocating that Supportive Housing Services funds be reshaped to include direct city allocations. He framed the posture as "Above all, Sherwood is committed to a compassionate response for our friends experiencing homelessness in our region" and "These are shared challenges, and inter-jurisdictional cooperation, not competition, is the best way to solve them," while noting Sherwood''s caseload was low enough that it ceded most of its shared homelessness liaison time to Tigard. Outreach and mental-health services investment within the region''s existing public-space framework — with no documented push for either enforcement-first crackdowns or unconditional housing-first — matches the invest-in-outreach-and-mental-health-services chair.', ARRAY['https://tigardlife.com/featured/as-homelessness-surges-tigard-revisits-regulations-questions-equity-of-shared-response/']::text[]),
    ('economic-development', 3, 'Rosener''s September 2023 "Balancing Act" post argues Sherwood must "encourage growth in high-quality jobs" (only about 900 of 9,000 commuting residents work locally) and makes a fiscal case for employment land — residential service costs run about $1.25 per tax dollar received versus $0.50-0.75 for jobs land. His tool of choice is targeted public infrastructure for a specific sector: he touts the $3 million federally funded road through the Tonquin Employment Area and the recruitment of high-tech employers Lam Research, DW Fritz, and NSI. His published priorities are to "attract family-wage jobs" while focusing growth "on projects that are compatible with our community values, goals, and expectations" and promoting "stable funding sources that do not put additional tax burdens on our citizens" — no large across-the-board tax abatements are documented. Industry-targeted recruitment with an explicit job-quality (family-wage) and community-compatibility test matches the targeted-incentives chair rather than maximum-subsidy competition.', ARRAY['https://rosener.com/therosenercorner/2024/2/9/mayors-corner-keeping-the-water-turned-on-ejdng', 'https://rosener.com/priorities']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT 'bdde1b46-d4ff-4409-b215-ee9d4f41be06'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('growth-and-development', 1, 'Rosener presided over the October 28, 2025 special session at which the council adopted, 7:0 with his vote, Resolutions 2025-073/074/075 referring two City Charter amendments; the minutes record him saying "local control was important and should be enshrined in the Charter" and urging the emergency election so voters could act "before the next legislative session in Salem." Measure 34-348 wrote into the Charter that "annexation may only take effect with the approval of city voters" (except declared public-health emergencies) and that these procedures "shall not be preempted by state laws," while Measure 34-347 bars any Type III or higher development from being decided without at least one neighborhood meeting and one public hearing; voters ratified them January 13, 2026 (82.71% and 94.23% yes per his blog). He frames this as pro-growth-on-community-terms ("These Charter amendments are not about opposing growth; they are about ensuring Sherwood grows on our terms"), but the operative policy he championed — voter approval as a precondition for annexations and charter-locked procedural gates before large-scale developments — is the voter-approval-gate chair, deliberately entrenched against state housing-production mandates like SB 974.', ARRAY['https://www.sherwoodoregon.gov/wp-content/uploads/2025/12/10.28.2025-City-Council-Meeting-Minutes.pdf', 'https://rosener.com/therosenercorner/2025/1/9/zuhok11ucuf3ja521az38lu4sspokc-rwfft-dd9sm-tprwf', 'https://rosener.com/therosenercorner/2025/1/9/zuhok11ucuf3ja521az38lu4sspokc-rwfft-dd9sm-tprwf-m4z8z-a77yz', 'https://www.opb.org/article/2026/01/18/sherwood-votes-overwhelmingly-to-challenge-new-state-housing-laws/']::text[]),
    ('residential-zoning', 2, 'In his December 31, 2025 blog post Rosener argued that state laws "such as HB 2001 (2019), SB 1537 (2024), and SB 974 (2025) have steadily eroded cities'' ability to manage growth" and that housing types should be decided by "the community," not "out-of-town developers." His alternative is the community-developed Sherwood West Plan, which designates "specific areas for duplexes and townhomes" and guarantees "cottage clusters and middle housing" for affordability while preserving "traditional single-family detached neighborhoods"; his January 2026 post reiterates the plan targets "cottage clusters, townhomes, and plexes" for affordability. He simultaneously championed Charter Measure 34-347 requiring a neighborhood meeting, a public hearing, and 1,000-foot mailed notice before significant land-use decisions. Accepting modest middle-housing density in designated areas under strong neighborhood-input requirements — while opposing state-mandated broad upzoning — matches the modest-density-with-neighborhood-input chair.', ARRAY['https://rosener.com/therosenercorner/2025/1/9/zuhok11ucuf3ja521az38lu4sspokc-rwfft-dd9sm-tprwf-m4z8z', 'https://rosener.com/therosenercorner/2025/1/9/zuhok11ucuf3ja521az38lu4sspokc-rwfft-dd9sm-tprwf-m4z8z-a77yz', 'https://www.sherwoodoregon.gov/wp-content/uploads/2025/12/10.28.2025-City-Council-Meeting-Minutes.pdf']::text[]),
    ('housing', 3, 'Rosener acknowledges "a regional housing crisis" and wrote after the January 2026 charter vote that "We are ready and willing to do our part to solve the regional housing crisis," pointing to the nearly 1,300-acre Sherwood West plan in which the city itself designates and guarantees middle-housing types — "cottage clusters, townhomes, and plexes" — specifically for affordability. In his September 2023 "Balancing Act" post he called for Sherwood to "diversify our housing options," and he told Tigard Life in September 2025 that Sherwood has "invested local funds and staff capacity into homelessness response and housing affordability efforts." He rejects the pure-deregulation path — publicly opposing SB 974 and similar bills that bypass local planning — and has proposed no rent caps or city-built public housing; city-led planning that carves out and enables affordable and middle housing, backed by local funds for affordability efforts, matches the targeted-help chair.', ARRAY['https://rosener.com/therosenercorner/2025/1/9/zuhok11ucuf3ja521az38lu4sspokc-rwfft-dd9sm-tprwf-m4z8z-a77yz', 'https://rosener.com/therosenercorner/2024/2/9/mayors-corner-keeping-the-water-turned-on-ejdng', 'https://tigardlife.com/featured/as-homelessness-surges-tigard-revisits-regulations-questions-equity-of-shared-response/']::text[]),
    ('transportation-priorities', 2, 'Rosener championed and publicly defended Sherwood''s $30 million pedestrian and bicycle bridge over Highway 99W (roughly $4 million in state lottery funds plus about $24-26 million in urban-renewal tax-increment financing), writing in May 2025 that it "represents more than just improved transportation; it''s a commitment to public safety, accessibility, and responsible growth," providing "a safe, ADA-compliant route for pedestrians and cyclists" and connecting schools and trail systems. His published mayoral priorities pair that multimodal investment with road work: championing "traffic calming and congestion solutions," ensuring student safety on roads and trails to schools, and securing state/federal funding for a grade-separated crossing at Cedar Creek. Committing major capital to walking/biking infrastructure alongside continued road and congestion investment matches the invest-in-both-roads-and-multimodal chair, not a transit-first posture with reduced parking.', ARRAY['https://rosener.com/therosenercorner/2025/1/9/zuhok11ucuf3ja521az38lu4sspokc-rwfft', 'https://rosener.com/priorities']::text[]),
    ('public-safety-approach', 4, 'In a March 18, 2026 Sherwood Sun interview Rosener made clear he wants more police resources: "Our police department does an amazing job. We''re not staffed at the same level as on a per capita basis as some of the agencies around us, but it''s expensive," adding "We''re talking right now about other revenue sources for the police department... There have been talks of a levy, maybe a fee," and warning "If you get behind on public safety, it''s really hard to catch up." Police are already the top general-fund cost, yet he is pursuing new dedicated revenue to raise staffing toward peer-agency levels rather than reallocating away from police; Sherwood''s mental-health crisis response is handled through a county partnership he cites (co-funding Washington County''s Mental Health Response Team with Tigard and Tualatin, $24,539 last fiscal year). Seeking additional revenue to expand police staffing matches the increase-police-investment chair.', ARRAY['https://www.sherwoodsun.org/sherwood-mayor-tim-rosener-highlights-progress-eyes-future-challenges/', 'https://tigardlife.com/featured/as-homelessness-surges-tigard-revisits-regulations-questions-equity-of-shared-response/']::text[]),
    ('homelessness-response', 3, 'Rosener''s documented strategy is services investment through regional partnership: he told Tigard Life (September 10, 2025) that Sherwood has "invested local funds and staff capacity into homelessness response," co-funds Washington County''s Mental Health Response Team with Tigard and Tualatin ($24,539 in the last fiscal year), donates $10,000 annually to the Family Justice Center, and serves on Metro''s President''s Work Group advocating that Supportive Housing Services funds be reshaped to include direct city allocations. He framed the posture as "Above all, Sherwood is committed to a compassionate response for our friends experiencing homelessness in our region" and "These are shared challenges, and inter-jurisdictional cooperation, not competition, is the best way to solve them," while noting Sherwood''s caseload was low enough that it ceded most of its shared homelessness liaison time to Tigard. Outreach and mental-health services investment within the region''s existing public-space framework — with no documented push for either enforcement-first crackdowns or unconditional housing-first — matches the invest-in-outreach-and-mental-health-services chair.', ARRAY['https://tigardlife.com/featured/as-homelessness-surges-tigard-revisits-regulations-questions-equity-of-shared-response/']::text[]),
    ('economic-development', 3, 'Rosener''s September 2023 "Balancing Act" post argues Sherwood must "encourage growth in high-quality jobs" (only about 900 of 9,000 commuting residents work locally) and makes a fiscal case for employment land — residential service costs run about $1.25 per tax dollar received versus $0.50-0.75 for jobs land. His tool of choice is targeted public infrastructure for a specific sector: he touts the $3 million federally funded road through the Tonquin Employment Area and the recruitment of high-tech employers Lam Research, DW Fritz, and NSI. His published priorities are to "attract family-wage jobs" while focusing growth "on projects that are compatible with our community values, goals, and expectations" and promoting "stable funding sources that do not put additional tax burdens on our citizens" — no large across-the-board tax abatements are documented. Industry-targeted recruitment with an explicit job-quality (family-wage) and community-compatibility test matches the targeted-incentives chair rather than maximum-subsidy competition.', ARRAY['https://rosener.com/therosenercorner/2024/2/9/mayors-corner-keeping-the-water-turned-on-ejdng', 'https://rosener.com/priorities']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT 'bdde1b46-d4ff-4409-b215-ee9d4f41be06'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = 'bdde1b46-d4ff-4409-b215-ee9d4f41be06';
  IF v_ext IS DISTINCT FROM -4167101 THEN
    RAISE EXCEPTION 'UUID bdde1b46-d4ff-4409-b215-ee9d4f41be06 does not belong to external_id -4167101 (Tim Rosener) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = 'bdde1b46-d4ff-4409-b215-ee9d4f41be06';
  IF n <> 7 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 7, n;
  END IF;
  -- Context-parity gate (WR-03): the context VALUES list is a verbatim
  -- duplicate of the answers list; count it too so a single-sided edit
  -- cannot silently drop or skew reasoning/sources rows.
  SELECT COUNT(*) INTO n FROM inform.politician_context WHERE politician_id = 'bdde1b46-d4ff-4409-b215-ee9d4f41be06';
  IF n <> 7 THEN
    RAISE EXCEPTION 'Expected % context rows, found % — answers/context VALUES lists diverged', 7, n;
  END IF;
END $$;

COMMIT;
