-- Migration 1193: Keith Mays (Councilor, Sherwood OR) compass stances — AUDIT-ONLY (not registered in the ledger)
-- Evidence-only; 100% cited; chairs model (value 1-5); 5 cited stances; blank spokes omitted.
-- topic_id resolved LIVE via JOIN on compass_topics.topic_key AND is_live=true (no hardcoded topic UUIDs).

BEGIN;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('growth-and-development', 1, 'At the October 28, 2025 special session Mays personally moved Resolution 2025-074, the Charter amendment requiring that "annexation may only take effect with the approval of city voters" and that those procedures "shall not be preempted by state laws"; the minutes record him present, saying he "supported the language as presented and it would protect the community''s rights," and all three home-rule resolutions passed 7:0 with all present members in favor. This caps a long documented record of gating growth on community consent: in 2018 he campaigned against submitting Sherwood''s 626-acre urban growth boundary expansion request — "When we look at tremendous growth in Sherwood West or anywhere, we for sure better know what our families, businesses, schools, community partners want, what their concerns are, and respond accordingly together" — spoke in favor of deferring any growth ask for three to six years, and the council unanimously withdrew the city''s letter of interest to Metro. Personally moving a charter-locked voter-approval gate on annexations and campaigning to halt a major boundary expansion matches the voter-approval-gate chair.', ARRAY['https://www.sherwoodoregon.gov/wp-content/uploads/2025/12/10.28.2025-City-Council-Meeting-Minutes.pdf', 'https://pamplinmedia.com/pt/9-news/394208-287207-sherwood-withdraws-growth-boundary-request', 'https://pamplinmedia.com/bvt/15-news/392097-284219-sherwood-city-council-keeps-possibility-of-expansion-alive-']::text[]),
    ('residential-zoning', 2, 'At the October 28, 2025 public hearings Mays supported Charter Resolution 2025-075, which requires at least one duly noticed neighborhood meeting and one public hearing before any Type III or higher land-use decision plus 1,000-foot mailed notice for Type II and higher applications; the minutes record him saying Oregon''s land-use process "tried to make it straightforward for people to develop" and that "Oregon had created more flexibility lately, but the state should not eliminate the public input portion of the process" — accepting the state''s recent added housing flexibility while insisting public input stay mandatory. He also moved the companion annexation amendment and voted with the unanimous 7:0 majority on all three resolutions, and in 2018 he framed Sherwood West growth as something the city must shape around what "our families, businesses, schools, community partners want." Tolerating modest added density while charter-locking neighborhood-meeting, hearing, and notice requirements matches the modest-density-with-strong-neighborhood-input chair.', ARRAY['https://www.sherwoodoregon.gov/wp-content/uploads/2025/12/10.28.2025-City-Council-Meeting-Minutes.pdf', 'https://pamplinmedia.com/pt/9-news/394208-287207-sherwood-withdraws-growth-boundary-request']::text[]),
    ('economic-development', 3, 'As mayor Mays pursued industry-targeted recruitment with an explicit job-quality rationale: welcoming semiconductor/solar supplier NSI''s 62,000-square-foot advanced-manufacturing facility he said "We are very excited to be able to work with Nuance Systems/NSI Manufacturing," describing high-quality jobs and significant new economic impact, and he argued that increasing the focus on economic development and bringing more jobs to Sherwood would greatly reduce commuting — the Tonquin Employment Area strategy that landed advanced-manufacturing and high-tech employers during his tenure. He paired that with direct small-business support, announcing a $100,000 Small Business Emergency Relief Program in March 2020 to offset COVID-19 impacts, and he previously served as president of the Sherwood Chamber of Commerce. Targeted recruitment of specific industries framed around high-quality jobs — with no documented large across-the-board tax abatements — matches the targeted-incentives chair.', ARRAY['https://businesstribune.online/2022/04/22/portland-high-tech-firm-nsi-headed-to-sherwood/', 'https://www.sherwoodoregon.gov/economicdevelopment/page/sherwood-mayor-announces-emergency-relief-program-businesses', 'https://www.sherwoodoregon.gov/government/city-council/']::text[]),
    ('transportation-priorities', 2, 'Mays initiated Sherwood''s Highway 99W pedestrian/bicycle bridge as mayor — state Rep. Courtney Neron recalled meeting with him around 2018-19 and agreeing on the need for a safer crossing, Valley Times coverage of his 2022 decision to step down lists advancing the bridge to design phase as a signature accomplishment, and at the March 2024 groundbreaking he applauded the 1,000-foot span as a "one of a kind" structure in the United States. The League of Oregon Cities'' 2025 Mark O. Hatfield Statesmanship Award citation credits him with leading major Sherwood projects including transportation funding alongside the new city center and clean-water infrastructure. Championing a major dedicated walking-and-biking capital project while leading broader transportation funding for a congested highway city matches the invest-in-both-roads-and-multimodal chair; nothing in his record supports a transit-first, parking-reduction posture.', ARRAY['https://beavertonvalleytimes.com/2024/03/06/sherwood-breaks-ground-on-1000-foot-pedestrian-bridge-across-highway-99w/', 'https://valleytimes.news/2022/08/01/sherwoods-mays-wont-seek-eight-term-as-mayor/', 'https://www.sherwoodoregon.gov/news/sherwood-councilor-keith-mays-receives-prestigious-leage-of-oregon-cities-award/']::text[]),
    ('civil-rights', 2, 'In June 2020 Mays joined the Metropolitan Mayors Consortium — the 26-mayor regional group the League of Oregon Cities credits him with creating — in a statement standing in solidarity with residents mourning the murder of George Floyd, committing the mayors to convene their communities, particularly Black residents, to listen, examine their own processes and policies with full transparency, and advance meaningful reforms. The LOC''s 2025 Hatfield Statesmanship Award citation also credits him with helping establish the LOC''s Diversity, Equity, Inclusion, and Accessibility (DEIA) Committee to promote inclusive governance statewide. Publicly committing government to examine its own policies for discrimination and advance reforms, and institutionalizing equity and inclusion work in Oregon''s league of cities, matches the address-systemic-discrimination chair rather than a maintain-current-law posture.', ARRAY['https://www.sherwoodoregon.gov/cm/page/sherwood-mayor-mays-joins-regional-mayors-statement', 'https://www.sherwoodoregon.gov/news/sherwood-councilor-keith-mays-receives-prestigious-leage-of-oregon-cities-award/']::text[])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT 'c2a6383a-56e9-4ead-9f22-9a6d3e88f68c'::uuid, ct.id, s.val
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH s(topic_key, val, reasoning, sources) AS (
  VALUES
    ('growth-and-development', 1, 'At the October 28, 2025 special session Mays personally moved Resolution 2025-074, the Charter amendment requiring that "annexation may only take effect with the approval of city voters" and that those procedures "shall not be preempted by state laws"; the minutes record him present, saying he "supported the language as presented and it would protect the community''s rights," and all three home-rule resolutions passed 7:0 with all present members in favor. This caps a long documented record of gating growth on community consent: in 2018 he campaigned against submitting Sherwood''s 626-acre urban growth boundary expansion request — "When we look at tremendous growth in Sherwood West or anywhere, we for sure better know what our families, businesses, schools, community partners want, what their concerns are, and respond accordingly together" — spoke in favor of deferring any growth ask for three to six years, and the council unanimously withdrew the city''s letter of interest to Metro. Personally moving a charter-locked voter-approval gate on annexations and campaigning to halt a major boundary expansion matches the voter-approval-gate chair.', ARRAY['https://www.sherwoodoregon.gov/wp-content/uploads/2025/12/10.28.2025-City-Council-Meeting-Minutes.pdf', 'https://pamplinmedia.com/pt/9-news/394208-287207-sherwood-withdraws-growth-boundary-request', 'https://pamplinmedia.com/bvt/15-news/392097-284219-sherwood-city-council-keeps-possibility-of-expansion-alive-']::text[]),
    ('residential-zoning', 2, 'At the October 28, 2025 public hearings Mays supported Charter Resolution 2025-075, which requires at least one duly noticed neighborhood meeting and one public hearing before any Type III or higher land-use decision plus 1,000-foot mailed notice for Type II and higher applications; the minutes record him saying Oregon''s land-use process "tried to make it straightforward for people to develop" and that "Oregon had created more flexibility lately, but the state should not eliminate the public input portion of the process" — accepting the state''s recent added housing flexibility while insisting public input stay mandatory. He also moved the companion annexation amendment and voted with the unanimous 7:0 majority on all three resolutions, and in 2018 he framed Sherwood West growth as something the city must shape around what "our families, businesses, schools, community partners want." Tolerating modest added density while charter-locking neighborhood-meeting, hearing, and notice requirements matches the modest-density-with-strong-neighborhood-input chair.', ARRAY['https://www.sherwoodoregon.gov/wp-content/uploads/2025/12/10.28.2025-City-Council-Meeting-Minutes.pdf', 'https://pamplinmedia.com/pt/9-news/394208-287207-sherwood-withdraws-growth-boundary-request']::text[]),
    ('economic-development', 3, 'As mayor Mays pursued industry-targeted recruitment with an explicit job-quality rationale: welcoming semiconductor/solar supplier NSI''s 62,000-square-foot advanced-manufacturing facility he said "We are very excited to be able to work with Nuance Systems/NSI Manufacturing," describing high-quality jobs and significant new economic impact, and he argued that increasing the focus on economic development and bringing more jobs to Sherwood would greatly reduce commuting — the Tonquin Employment Area strategy that landed advanced-manufacturing and high-tech employers during his tenure. He paired that with direct small-business support, announcing a $100,000 Small Business Emergency Relief Program in March 2020 to offset COVID-19 impacts, and he previously served as president of the Sherwood Chamber of Commerce. Targeted recruitment of specific industries framed around high-quality jobs — with no documented large across-the-board tax abatements — matches the targeted-incentives chair.', ARRAY['https://businesstribune.online/2022/04/22/portland-high-tech-firm-nsi-headed-to-sherwood/', 'https://www.sherwoodoregon.gov/economicdevelopment/page/sherwood-mayor-announces-emergency-relief-program-businesses', 'https://www.sherwoodoregon.gov/government/city-council/']::text[]),
    ('transportation-priorities', 2, 'Mays initiated Sherwood''s Highway 99W pedestrian/bicycle bridge as mayor — state Rep. Courtney Neron recalled meeting with him around 2018-19 and agreeing on the need for a safer crossing, Valley Times coverage of his 2022 decision to step down lists advancing the bridge to design phase as a signature accomplishment, and at the March 2024 groundbreaking he applauded the 1,000-foot span as a "one of a kind" structure in the United States. The League of Oregon Cities'' 2025 Mark O. Hatfield Statesmanship Award citation credits him with leading major Sherwood projects including transportation funding alongside the new city center and clean-water infrastructure. Championing a major dedicated walking-and-biking capital project while leading broader transportation funding for a congested highway city matches the invest-in-both-roads-and-multimodal chair; nothing in his record supports a transit-first, parking-reduction posture.', ARRAY['https://beavertonvalleytimes.com/2024/03/06/sherwood-breaks-ground-on-1000-foot-pedestrian-bridge-across-highway-99w/', 'https://valleytimes.news/2022/08/01/sherwoods-mays-wont-seek-eight-term-as-mayor/', 'https://www.sherwoodoregon.gov/news/sherwood-councilor-keith-mays-receives-prestigious-leage-of-oregon-cities-award/']::text[]),
    ('civil-rights', 2, 'In June 2020 Mays joined the Metropolitan Mayors Consortium — the 26-mayor regional group the League of Oregon Cities credits him with creating — in a statement standing in solidarity with residents mourning the murder of George Floyd, committing the mayors to convene their communities, particularly Black residents, to listen, examine their own processes and policies with full transparency, and advance meaningful reforms. The LOC''s 2025 Hatfield Statesmanship Award citation also credits him with helping establish the LOC''s Diversity, Equity, Inclusion, and Accessibility (DEIA) Committee to promote inclusive governance statewide. Publicly committing government to examine its own policies for discrimination and advance reforms, and institutionalizing equity and inclusion work in Oregon''s league of cities, matches the address-systemic-discrimination chair rather than a maintain-current-law posture.', ARRAY['https://www.sherwoodoregon.gov/cm/page/sherwood-mayor-mays-joins-regional-mayors-statement', 'https://www.sherwoodoregon.gov/news/sherwood-councilor-keith-mays-receives-prestigious-leage-of-oregon-cities-award/']::text[])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT 'c2a6383a-56e9-4ead-9f22-9a6d3e88f68c'::uuid, ct.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics ct ON ct.topic_key = s.topic_key AND ct.is_live = true
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

DO $$
DECLARE n INTEGER;
        v_ext BIGINT;
BEGIN
  -- Identity gate (WR-01): the hardcoded politician UUID must belong to the
  -- intended official's external_id — a wrong-but-existing UUID would satisfy
  -- the FK and the count gate below while silently misattributing stances.
  SELECT external_id INTO v_ext FROM essentials.politicians WHERE id = 'c2a6383a-56e9-4ead-9f22-9a6d3e88f68c';
  IF v_ext IS DISTINCT FROM -4167105 THEN
    RAISE EXCEPTION 'UUID c2a6383a-56e9-4ead-9f22-9a6d3e88f68c does not belong to external_id -4167105 (Keith Mays) — found %', v_ext;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_answers WHERE politician_id = 'c2a6383a-56e9-4ead-9f22-9a6d3e88f68c';
  IF n <> 5 THEN
    RAISE EXCEPTION 'Expected % answers, found % — topic_key mismatch dropped rows', 5, n;
  END IF;
  -- Context-parity gate (WR-03): the context VALUES list is a verbatim
  -- duplicate of the answers list; count it too so a single-sided edit
  -- cannot silently drop or skew reasoning/sources rows.
  SELECT COUNT(*) INTO n FROM inform.politician_context WHERE politician_id = 'c2a6383a-56e9-4ead-9f22-9a6d3e88f68c';
  IF n <> 5 THEN
    RAISE EXCEPTION 'Expected % context rows, found % — answers/context VALUES lists diverged', 5, n;
  END IF;
  -- Content-correspondence gate (WR-04, 181-REVIEW): the count checks above
  -- can't catch a hand-edit that changes one table's topic set (or blanks
  -- its reasoning/sources) without mirroring the other — both would still
  -- report the same N. Assert set equality on topic_id between the two
  -- tables for this politician, and that every context row carries
  -- non-empty reasoning and sources.
  SELECT COUNT(*) INTO n FROM inform.politician_answers a
  WHERE a.politician_id = 'c2a6383a-56e9-4ead-9f22-9a6d3e88f68c'
    AND NOT EXISTS (
      SELECT 1 FROM inform.politician_context c
      WHERE c.politician_id = a.politician_id AND c.topic_id = a.topic_id
        AND c.reasoning IS NOT NULL AND length(trim(c.reasoning)) > 0
        AND c.sources IS NOT NULL AND array_length(c.sources, 1) > 0
    );
  IF n <> 0 THEN
    RAISE EXCEPTION '% answers row(s) have no corresponding non-empty context row (topic_id mismatch or empty reasoning/sources)', n;
  END IF;
  SELECT COUNT(*) INTO n FROM inform.politician_context c
  WHERE c.politician_id = 'c2a6383a-56e9-4ead-9f22-9a6d3e88f68c'
    AND NOT EXISTS (
      SELECT 1 FROM inform.politician_answers a
      WHERE a.politician_id = c.politician_id AND a.topic_id = c.topic_id
    );
  IF n <> 0 THEN
    RAISE EXCEPTION '% context row(s) reference a topic_id with no corresponding answers row', n;
  END IF;
END $$;

COMMIT;
