-- Migration 1414: Bend, OR deep seed — records
--
-- Purpose: seeds every locally-elected body a Bend resident votes for, across FOUR governments:
--   1. City of Bend                                  geo_id '4105800'   — 7 officials (Mayor + 6 councilors)
--   2. Deschutes County                               geo_id '41017'      — 7 officials (3 commissioners + 4 row officers)
--   3. Bend-La Pine Administrative School District 1  geo_id '4101980'   — 7 directors (Zones 1-7)
--   4. Bend Metro Park & Recreation District          geo_id 'bend-or-park-rec-district' — 5 directors
-- Total: 4 governments, 5 chambers, 5 districts (1 pre-existing), 26 politicians, 26 offices.
--
-- Every roster row is sourced in backend/data/stance-research/bend-or/00-ROSTER-RESEARCH.md.
-- This file is GENERATED by scripts/gen-1414-bend-records.mjs — edit the generator, not the SQL.
--
-- FORM OF GOVERNMENT (research-confirmed against primary sources):
--   City of Bend: council-manager. 6 councilors + a directly-elected Mayor, ALL AT-LARGE but with
--     NUMBERED POSITIONS (1-6, Mayor = Position 7 on the ballot). Per bendoregon.gov/city-council/
--     elections/: "All positions are elected at-large and are not tied to any specific geographic
--     areas." So: numbered titles, but NO ward districts/geofences of any kind. Differs from Tigard
--     (mig 1159, pure at-large plain 'Councilor') and Hillsboro (mig 1150, real wards).
--     Mayor Pro Tem (Perkins) is chosen BY the council — a note on her seat, NOT a separate office.
--   Deschutes County: 3 commissioners elected AT LARGE to numbered positions; all county offices
--     are NONPARTISAN. Chair/Vice Chair rotate among the three — annotated in the title, not
--     separate offices. Voters approved expansion to 5 seats effective with the 2026 election;
--     the two new seats (Positions 4 and 5) are NOT seeded as officeholders because nobody holds
--     them until January 2027 — they exist only as 2026 races (see the races migration).
--   Bend-La Pine Schools: 7 directors, elected district-wide but each resident in a zone (1-7).
--   BPRD: 5 directors, ORS ch. 198/266, 4-year terms ending June 30.
--
-- CRITICAL / traps this migration deliberately handles:
--   * chambers.slug is GENERATED — never INSERT it. Every chamber lookup is scoped by
--     (name, government_id), NEVER by slug (Springfield MO mig 1049: 'springfield-city-council'
--     silently resolved to the MASSACHUSETTS chamber and mis-attached offices).
--   * districts.state must be lowercase 'or'; governments.state and offices.representing_state
--     are uppercase 'OR'.
--   * geo_id '41017' is ALSO used by OR "State House District 17" (G5220) and "State Senate
--     District 17" (G5210) district rows. Every county district lookup here is scoped by
--     district_type='COUNTY' — geo_id alone is ambiguous.
--   * The Deschutes County COUNTY district row ALREADY EXISTS (census_tiger_2024) with
--     government_id NULL — this migration ADOPTS it (UPDATE) rather than inserting a duplicate.
--   * Both Deschutes chambers share that one COUNTY district. That is the established
--     multi-chamber-county pattern (see Brown/Greene/Jackson County IN, where Assessor, Sheriff,
--     Treasurer... chambers all hang off the single COUNTY district row), so the section-split
--     detector below is scoped to the CITY geo_id only.
--   * The two geofences this seed needs beyond what TIGER already loaded (Bend-La Pine G5420 and
--     BPRD X0024) are imported by scripts/import-bend-geofences.ts, which MUST run first — gate
--     (c) asserts all four boundaries are present and rolls back if not.
--   * essentials.governments has no unique constraint on geo_id — all inserts use NOT EXISTS.

BEGIN;

-- =============================================================================
-- Pre-flight: hard abort if this migration was already applied
-- =============================================================================
DO $$
BEGIN
  IF (SELECT COUNT(*) FROM essentials.governments
      WHERE name IN ('City of Bend, Oregon, US', 'Deschutes County, Oregon, US',
                     'Bend-La Pine Administrative School District 1, Oregon, US',
                     'Bend Metro Park & Recreation District, Oregon, US')) > 0 THEN
    RAISE EXCEPTION 'Migration 1414 already applied (a Bend/Deschutes government row exists) — aborting re-run';
  END IF;
END $$;


-- =============================================================================
-- Step 1: Government rows (4)
-- =============================================================================
INSERT INTO essentials.governments (id, name, type, state, city, geo_id)
SELECT gen_random_uuid(), 'City of Bend, Oregon, US', 'LOCAL', 'OR', 'Bend', '4105800'
WHERE NOT EXISTS (SELECT 1 FROM essentials.governments WHERE name = 'City of Bend, Oregon, US');

INSERT INTO essentials.governments (id, name, type, state, city, geo_id)
SELECT gen_random_uuid(), 'Deschutes County, Oregon, US', 'County', 'OR', NULL, '41017'
WHERE NOT EXISTS (SELECT 1 FROM essentials.governments WHERE name = 'Deschutes County, Oregon, US');

INSERT INTO essentials.governments (id, name, type, state, city, geo_id)
SELECT gen_random_uuid(), 'Bend-La Pine Administrative School District 1, Oregon, US', 'LOCAL', 'OR', NULL, '4101980'
WHERE NOT EXISTS (SELECT 1 FROM essentials.governments WHERE name = 'Bend-La Pine Administrative School District 1, Oregon, US');

INSERT INTO essentials.governments (id, name, type, state, city, geo_id)
SELECT gen_random_uuid(), 'Bend Metro Park & Recreation District, Oregon, US', 'LOCAL', 'OR', 'Bend', 'bend-or-park-rec-district'
WHERE NOT EXISTS (SELECT 1 FROM essentials.governments WHERE name = 'Bend Metro Park & Recreation District, Oregon, US');


-- =============================================================================
-- Step 2: Chambers (5) — generated slug column intentionally omitted
-- =============================================================================
INSERT INTO essentials.chambers (id, name, name_formal, government_id, official_count, election_method)
SELECT gen_random_uuid(), 'City Council', 'Bend City Council', (SELECT id FROM essentials.governments WHERE name = 'City of Bend, Oregon, US'), 7, 'at-large numbered positions'
WHERE NOT EXISTS (SELECT 1 FROM essentials.chambers
                  WHERE name = 'City Council' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'City of Bend, Oregon, US'));

INSERT INTO essentials.chambers (id, name, name_formal, government_id, official_count, election_method)
SELECT gen_random_uuid(), 'Board of County Commissioners', 'Deschutes County Board of County Commissioners',
       (SELECT id FROM essentials.governments WHERE name = 'Deschutes County, Oregon, US'), 3, 'at-large numbered positions, nonpartisan'
WHERE NOT EXISTS (SELECT 1 FROM essentials.chambers
                  WHERE name = 'Board of County Commissioners' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Deschutes County, Oregon, US'));

INSERT INTO essentials.chambers (id, name, name_formal, government_id, official_count, election_method)
SELECT gen_random_uuid(), 'Countywide Elected Officials', 'Deschutes County Countywide Elected Officials',
       (SELECT id FROM essentials.governments WHERE name = 'Deschutes County, Oregon, US'), 4, 'countywide, nonpartisan'
WHERE NOT EXISTS (SELECT 1 FROM essentials.chambers
                  WHERE name = 'Countywide Elected Officials' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Deschutes County, Oregon, US'));

INSERT INTO essentials.chambers (id, name, name_formal, government_id, official_count, election_method)
SELECT gen_random_uuid(), 'School Board', 'Bend-La Pine Administrative School District 1 School Board',
       (SELECT id FROM essentials.governments WHERE name = 'Bend-La Pine Administrative School District 1, Oregon, US'), 7, 'district-wide vote, zone residency'
WHERE NOT EXISTS (SELECT 1 FROM essentials.chambers
                  WHERE name = 'School Board' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Bend-La Pine Administrative School District 1, Oregon, US'));

INSERT INTO essentials.chambers (id, name, name_formal, government_id, official_count, election_method)
SELECT gen_random_uuid(), 'Board of Directors', 'Bend Metro Park & Recreation District Board of Directors',
       (SELECT id FROM essentials.governments WHERE name = 'Bend Metro Park & Recreation District, Oregon, US'), 5, 'district-wide, nonpartisan'
WHERE NOT EXISTS (SELECT 1 FROM essentials.chambers
                  WHERE name = 'Board of Directors' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Bend Metro Park & Recreation District, Oregon, US'));


-- =============================================================================
-- Step 3: Districts
--   City:   LOCAL_EXEC (Mayor, citywide) + LOCAL (at-large councilors) at the place FIPS
--   County: ADOPT the pre-existing COUNTY/G4020 row (set government_id) — do NOT insert
--   School: SCHOOL/G5420 at the TIGER unified-school-district GEOID
--   Park:   LOCAL/X0024 at the synthetic park-district geo_id
-- =============================================================================
INSERT INTO essentials.districts (id, district_type, state, geo_id, label, mtfcc, government_id)
SELECT gen_random_uuid(), 'LOCAL_EXEC', 'or', '4105800', 'Bend (Mayor, Citywide)', NULL, (SELECT id FROM essentials.governments WHERE name = 'City of Bend, Oregon, US')
WHERE NOT EXISTS (SELECT 1 FROM essentials.districts
                  WHERE geo_id = '4105800' AND district_type = 'LOCAL_EXEC' AND state = 'or');

INSERT INTO essentials.districts (id, district_type, state, geo_id, label, mtfcc, government_id)
SELECT gen_random_uuid(), 'LOCAL', 'or', '4105800', 'Bend (At-Large)', NULL, (SELECT id FROM essentials.governments WHERE name = 'City of Bend, Oregon, US')
WHERE NOT EXISTS (SELECT 1 FROM essentials.districts
                  WHERE geo_id = '4105800' AND district_type = 'LOCAL' AND state = 'or');

-- ADOPT the existing Deschutes County district (created by the TIGER county load with a NULL
-- government_id). Scoped by district_type='COUNTY' because geo_id '41017' also names OR
-- State House/Senate District 17 rows.
UPDATE essentials.districts
SET government_id = (SELECT id FROM essentials.governments WHERE name = 'Deschutes County, Oregon, US'),
    label = 'Deschutes County',
    city = NULL
WHERE geo_id = '41017' AND district_type = 'COUNTY' AND state = 'or'
  AND government_id IS NULL;

INSERT INTO essentials.districts (id, district_type, state, geo_id, label, mtfcc, government_id)
SELECT gen_random_uuid(), 'SCHOOL', 'or', '4101980',
       'Bend-La Pine Administrative School District 1', 'G5420', (SELECT id FROM essentials.governments WHERE name = 'Bend-La Pine Administrative School District 1, Oregon, US')
WHERE NOT EXISTS (SELECT 1 FROM essentials.districts
                  WHERE geo_id = '4101980' AND district_type = 'SCHOOL' AND state = 'or');

INSERT INTO essentials.districts (id, district_type, state, geo_id, label, mtfcc, government_id)
SELECT gen_random_uuid(), 'LOCAL', 'or', 'bend-or-park-rec-district',
       'Bend Metro Park & Recreation District', 'X0024', (SELECT id FROM essentials.governments WHERE name = 'Bend Metro Park & Recreation District, Oregon, US')
WHERE NOT EXISTS (SELECT 1 FROM essentials.districts
                  WHERE geo_id = 'bend-or-park-rec-district' AND district_type = 'LOCAL' AND state = 'or');


-- =============================================================================
-- Step 4: Officials — 26 politician + office pairs
-- =============================================================================

-- Official 1/26: Melanie Kebler — Mayor (external_id -4105801)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Melanie Kebler', 'Melanie', 'Kebler', NULL,
          true, false, false, true, -4105801, ARRAY['mkebler@bendoregon.gov']::text[], ARRAY['https://bendoregon.gov/city-council/melanie-kebler/']::text[], ARRAY['Mayor of Bend; directly elected Nov 2022, term through January 2027. Filed for re-election Nov 3, 2026.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'City Council' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'City of Bend, Oregon, US')),
       p.id,
       'Mayor', 'OR', 'Bend', false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '4105800'
  AND d.district_type = 'LOCAL_EXEC'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 2/26: Megan Norris — Councilor, Position 1 (external_id -4105802)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Megan Norris', 'Megan', 'Norris', NULL,
          true, false, false, true, -4105802, ARRAY['mnorris@bendoregon.gov']::text[], ARRAY['https://bendoregon.gov/city-council/megan-norris/']::text[], ARRAY['Re-elected Nov 2024 (73.0%), term through January 2029.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'City Council' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'City of Bend, Oregon, US')),
       p.id,
       'Councilor, Position 1', 'OR', 'Bend', false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '4105800'
  AND d.district_type = 'LOCAL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 3/26: Gina Franzosa — Councilor, Position 2 (external_id -4105803)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Gina Franzosa', 'Gina', 'Franzosa', NULL,
          true, false, false, true, -4105803, ARRAY['gfranzosa@bendoregon.gov']::text[], ARRAY['https://bendoregon.gov/city-council/gina-franzosa/']::text[], ARRAY['Elected unopposed Nov 2024, term through January 2029.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'City Council' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'City of Bend, Oregon, US')),
       p.id,
       'Councilor, Position 2', 'OR', 'Bend', false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '4105800'
  AND d.district_type = 'LOCAL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 4/26: Megan Perkins — Councilor, Position 3 (external_id -4105804)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Megan Perkins', 'Megan', 'Perkins', NULL,
          true, false, false, true, -4105804, ARRAY['mperkins@bendoregon.gov']::text[], ARRAY['https://bendoregon.gov/city-council/megan-perkins/']::text[], ARRAY['Mayor Pro Tem (chosen by the Council, not a separate office). Re-elected Nov 2024, term through January 2029.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'City Council' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'City of Bend, Oregon, US')),
       p.id,
       'Councilor, Position 3', 'OR', 'Bend', false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '4105800'
  AND d.district_type = 'LOCAL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 5/26: Steve Platt — Councilor, Position 4 (external_id -4105805)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Steve Platt', 'Steve', 'Platt', NULL,
          true, false, false, true, -4105805, ARRAY['splatt@bendoregon.gov']::text[], ARRAY['https://bendoregon.gov/city-council/steve-platt/']::text[], ARRAY['Elected Nov 2024 (58.3%), term through January 2029.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'City Council' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'City of Bend, Oregon, US')),
       p.id,
       'Councilor, Position 4', 'OR', 'Bend', false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '4105800'
  AND d.district_type = 'LOCAL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 6/26: Ariel Méndez — Councilor, Position 5 (external_id -4105806)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Ariel Méndez', 'Ariel', 'Méndez', NULL,
          true, false, false, true, -4105806, ARRAY['amendez@bendoregon.gov']::text[], ARRAY['https://bendoregon.gov/city-council/ariel-mendez/']::text[], ARRAY['Elected Nov 2022, term through January 2027. Filed for re-election Nov 3, 2026.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'City Council' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'City of Bend, Oregon, US')),
       p.id,
       'Councilor, Position 5', 'OR', 'Bend', false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '4105800'
  AND d.district_type = 'LOCAL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 7/26: Mike Riley — Councilor, Position 6 (external_id -4105807)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Mike Riley', 'Mike', 'Riley', NULL,
          true, false, false, true, -4105807, ARRAY['mriley@bendoregon.gov']::text[], ARRAY['https://bendoregon.gov/city-council/mike-riley/']::text[], ARRAY['Elected Nov 2022, term through January 2027. Had NOT filed for re-election as of 2026-07-24 (city filing closes Aug 25, 2026).']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'City Council' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'City of Bend, Oregon, US')),
       p.id,
       'Councilor, Position 6', 'OR', 'Bend', false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '4105800'
  AND d.district_type = 'LOCAL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 8/26: Anthony (Tony) DeBone — Commissioner, Position 1 (Vice Chair) (external_id -4101701)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Anthony (Tony) DeBone', 'Anthony', 'DeBone', NULL,
          true, false, false, true, -4101701, NULL, NULL, ARRAY['Term expires January 2027. Lost the May 19, 2026 primary for Position 1 to Jamie Collins (38% to 55%).']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'Board of County Commissioners' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Deschutes County, Oregon, US')),
       p.id,
       'Commissioner, Position 1 (Vice Chair)', 'OR', NULL, false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '41017'
  AND d.district_type = 'COUNTY'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 9/26: Phil Chang — Commissioner, Position 2 (Chair) (external_id -4101702)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Phil Chang', 'Phil', 'Chang', NULL,
          true, false, false, true, -4101702, NULL, NULL, ARRAY['Board Chair. Re-elected 2024, term expires January 2029 — not on the 2026 ballot.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'Board of County Commissioners' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Deschutes County, Oregon, US')),
       p.id,
       'Commissioner, Position 2 (Chair)', 'OR', NULL, false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '41017'
  AND d.district_type = 'COUNTY'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 10/26: Patti Adair — Commissioner, Position 3 (external_id -4101703)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Patti Adair', 'Patti', 'Adair', NULL,
          true, false, false, true, -4101703, NULL, NULL, ARRAY['Term expires January 2027; not seeking re-election. Republican nominee for U.S. House OR-05 in Nov 2026.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'Board of County Commissioners' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Deschutes County, Oregon, US')),
       p.id,
       'Commissioner, Position 3', 'OR', NULL, false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '41017'
  AND d.district_type = 'COUNTY'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 11/26: Steve Dennison — County Clerk (external_id -4101711)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Steve Dennison', 'Steve', 'Dennison', NULL,
          true, false, false, true, -4101711, NULL, NULL, ARRAY['Appointed 2021-08-01, elected Nov 2022; term expires January 2027. Running for re-election Nov 3, 2026.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'Countywide Elected Officials' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Deschutes County, Oregon, US')),
       p.id,
       'County Clerk', 'OR', NULL, false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '41017'
  AND d.district_type = 'COUNTY'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 12/26: Scot Langton — County Assessor (external_id -4101712)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Scot Langton', 'Scot', 'Langton', NULL,
          true, false, false, true, -4101712, NULL, NULL, ARRAY['In office since 2001; term expires January 2027. Retiring — not seeking re-election.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'Countywide Elected Officials' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Deschutes County, Oregon, US')),
       p.id,
       'County Assessor', 'OR', NULL, false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '41017'
  AND d.district_type = 'COUNTY'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 13/26: Bill Kuhn — County Treasurer (external_id -4101713)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Bill Kuhn', 'Bill', 'Kuhn', NULL,
          true, false, false, true, -4101713, NULL, NULL, ARRAY['Elected Nov 2022; term expires January 2027. Not running in 2026.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'Countywide Elected Officials' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Deschutes County, Oregon, US')),
       p.id,
       'County Treasurer', 'OR', NULL, false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '41017'
  AND d.district_type = 'COUNTY'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 14/26: Ty Rupert — County Sheriff (external_id -4101714)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Ty Rupert', 'Ty', 'Rupert', NULL,
          true, true, false, true, -4101714, NULL, NULL, ARRAY['Appointed interim Sheriff 2025-07-29 (effective Aug 1, 2025) after Kent van der Kamp resigned; serves through January 2027. Candidate in the Nov 3, 2026 Sheriff election.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'Countywide Elected Officials' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Deschutes County, Oregon, US')),
       p.id,
       'County Sheriff', 'OR', NULL, true, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '41017'
  AND d.district_type = 'COUNTY'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 15/26: Jenn Lynch — Director, Zone 1 (external_id -4101981)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Jenn Lynch', 'Jenn', 'Lynch', NULL,
          true, false, false, true, -4101981, NULL, NULL, NULL)
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'School Board' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Bend-La Pine Administrative School District 1, Oregon, US')),
       p.id,
       'Director, Zone 1', 'OR', NULL, false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '4101980'
  AND d.district_type = 'SCHOOL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 16/26: Marcus LeGrand — Director, Zone 2 (external_id -4101982)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Marcus LeGrand', 'Marcus', 'LeGrand', NULL,
          true, false, false, true, -4101982, NULL, NULL, NULL)
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'School Board' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Bend-La Pine Administrative School District 1, Oregon, US')),
       p.id,
       'Director, Zone 2', 'OR', NULL, false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '4101980'
  AND d.district_type = 'SCHOOL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 17/26: Cameron Fischer — Director, Zone 3 (Vice Chair) (external_id -4101983)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Cameron Fischer', 'Cameron', 'Fischer', NULL,
          true, false, false, true, -4101983, NULL, NULL, NULL)
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'School Board' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Bend-La Pine Administrative School District 1, Oregon, US')),
       p.id,
       'Director, Zone 3 (Vice Chair)', 'OR', NULL, false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '4101980'
  AND d.district_type = 'SCHOOL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 18/26: Shirley Olson — Director, Zone 4 (external_id -4101984)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Shirley Olson', 'Shirley', 'Olson', NULL,
          true, false, false, true, -4101984, NULL, NULL, NULL)
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'School Board' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Bend-La Pine Administrative School District 1, Oregon, US')),
       p.id,
       'Director, Zone 4', 'OR', NULL, false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '4101980'
  AND d.district_type = 'SCHOOL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 19/26: Amy Tatom — Director, Zone 5 (Chair) (external_id -4101985)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Amy Tatom', 'Amy', 'Tatom', NULL,
          true, false, false, true, -4101985, NULL, NULL, NULL)
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'School Board' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Bend-La Pine Administrative School District 1, Oregon, US')),
       p.id,
       'Director, Zone 5 (Chair)', 'OR', NULL, false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '4101980'
  AND d.district_type = 'SCHOOL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 20/26: Ross Tomlin — Director, Zone 6 (external_id -4101986)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Ross Tomlin', 'Ross', 'Tomlin', NULL,
          true, false, false, true, -4101986, NULL, NULL, NULL)
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'School Board' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Bend-La Pine Administrative School District 1, Oregon, US')),
       p.id,
       'Director, Zone 6', 'OR', NULL, false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '4101980'
  AND d.district_type = 'SCHOOL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 21/26: Kina Chadwick — Director, Zone 7 (external_id -4101987)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Kina Chadwick', 'Kina', 'Chadwick', NULL,
          true, false, false, true, -4101987, NULL, NULL, NULL)
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'School Board' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Bend-La Pine Administrative School District 1, Oregon, US')),
       p.id,
       'Director, Zone 7', 'OR', NULL, false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = '4101980'
  AND d.district_type = 'SCHOOL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 22/26: Cary Schneider — Director (Chair) (external_id -4105821)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Cary Schneider', 'Cary', 'Schneider', NULL,
          true, false, false, true, -4105821, NULL, NULL, ARRAY['Board Chair; term through June 30, 2029.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'Board of Directors' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Bend Metro Park & Recreation District, Oregon, US')),
       p.id,
       'Director (Chair)', 'OR', 'Bend', false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = 'bend-or-park-rec-district'
  AND d.district_type = 'LOCAL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 23/26: Deb Schoen — Director (Vice Chair) (external_id -4105822)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Deb Schoen', 'Deb', 'Schoen', NULL,
          true, false, false, true, -4105822, NULL, NULL, ARRAY['Board Vice-Chair; term through June 30, 2029.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'Board of Directors' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Bend Metro Park & Recreation District, Oregon, US')),
       p.id,
       'Director (Vice Chair)', 'OR', 'Bend', false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = 'bend-or-park-rec-district'
  AND d.district_type = 'LOCAL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 24/26: Nathan Hovekamp — Director (external_id -4105823)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Nathan Hovekamp', 'Nathan', 'Hovekamp', NULL,
          true, false, false, true, -4105823, NULL, NULL, ARRAY['Legislative Liaison; on the board since 2015; term through June 30, 2029.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'Board of Directors' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Bend Metro Park & Recreation District, Oregon, US')),
       p.id,
       'Director', 'OR', 'Bend', false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = 'bend-or-park-rec-district'
  AND d.district_type = 'LOCAL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 25/26: Jodie Schiffman — Director (external_id -4105824)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Jodie Schiffman', 'Jodie', 'Schiffman', NULL,
          true, false, false, true, -4105824, NULL, NULL, ARRAY['Joined the board by appointment in January 2023; term through June 30, 2027. Former Bend city councilor and Mayor Pro Tem.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'Board of Directors' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Bend Metro Park & Recreation District, Oregon, US')),
       p.id,
       'Director', 'OR', 'Bend', false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = 'bend-or-park-rec-district'
  AND d.district_type = 'LOCAL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );

-- Official 26/26: Donna Owens — Director (external_id -4105825)
WITH ins_p AS (
  INSERT INTO essentials.politicians
    (id, full_name, first_name, last_name, party, is_active, is_appointed,
     is_vacant, is_incumbent, external_id, email_addresses, urls, notes)
  VALUES (gen_random_uuid(), 'Donna Owens', 'Donna', 'Owens', NULL,
          true, false, false, true, -4105825, NULL, NULL, ARRAY['Joined the board by appointment in January 2023; term through June 30, 2027.']::text[])
  ON CONFLICT (external_id) DO UPDATE
    SET is_active = EXCLUDED.is_active
  RETURNING id
)
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state,
   representing_city, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(),
       d.id,
       (SELECT id FROM essentials.chambers WHERE name = 'Board of Directors' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Bend Metro Park & Recreation District, Oregon, US')),
       p.id,
       'Director', 'OR', 'Bend', false, false, NULL
FROM essentials.districts d
CROSS JOIN ins_p p
WHERE d.geo_id = 'bend-or-park-rec-district'
  AND d.district_type = 'LOCAL'
  AND d.state = 'or'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.district_id = d.id AND o.politician_id = p.id
  );


-- =============================================================================
-- Step 5: office_id back-fill (all 26); WHERE office_id IS NULL for idempotency
-- =============================================================================
UPDATE essentials.politicians p
SET office_id = o.id
FROM essentials.offices o
WHERE o.politician_id = p.id
  AND p.external_id IN (-4105801,-4105802,-4105803,-4105804,-4105805,-4105806,-4105807,-4101701,-4101702,-4101703,-4101711,-4101712,-4101713,-4101714,-4101981,-4101982,-4101983,-4101984,-4101985,-4101986,-4101987,-4105821,-4105822,-4105823,-4105824,-4105825)
  AND p.office_id IS NULL;


-- =============================================================================
-- Post-verification — raises EXCEPTION on any failure, rolling back the whole seed
--   (a) 4 governments present
--   (b) per-chamber office counts land in the INTENDED chamber (Springfield slug-collision trap)
--   (c) all four geofence boundaries present (import-bend-geofences.ts ran)
--   (d) section-split detector for the CITY geo_id (county intentionally exempt — shared district)
--   (e) office_id back-fill: 0 nulls
--   (f) representing_city='Bend' on the 12 city + park offices
--   (g) the pre-existing Deschutes COUNTY district is now owned by the county government
-- =============================================================================
DO $$
DECLARE
  v_gov       INTEGER;
  v_city      INTEGER;
  v_comm      INTEGER;
  v_row       INTEGER;
  v_school    INTEGER;
  v_park      INTEGER;
  v_geo       INTEGER;
  v_split     INTEGER;
  v_nulls     INTEGER;
  v_repcity   INTEGER;
  v_countydis INTEGER;
BEGIN
  -- (a)
  SELECT COUNT(*) INTO v_gov FROM essentials.governments
  WHERE name IN ('City of Bend, Oregon, US', 'Deschutes County, Oregon, US',
                 'Bend-La Pine Administrative School District 1, Oregon, US', 'Bend Metro Park & Recreation District, Oregon, US');
  IF v_gov <> 4 THEN
    RAISE EXCEPTION 'FAILED (a): governments=%, expected 4', v_gov;
  END IF;

  -- (b) office counts BY CHAMBER — asserts offices landed in the intended chamber, not a
  --     same-named chamber belonging to another government
  SELECT COUNT(*) INTO v_city FROM essentials.offices o
  WHERE o.chamber_id = (SELECT id FROM essentials.chambers WHERE name = 'City Council' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'City of Bend, Oregon, US'));
  IF v_city <> 7 THEN RAISE EXCEPTION 'FAILED (b): Bend City Council offices=%, expected 7', v_city; END IF;

  SELECT COUNT(*) INTO v_comm FROM essentials.offices o
  WHERE o.chamber_id = (SELECT id FROM essentials.chambers WHERE name = 'Board of County Commissioners' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Deschutes County, Oregon, US'));
  IF v_comm <> 3 THEN RAISE EXCEPTION 'FAILED (b): Deschutes commissioner offices=%, expected 3', v_comm; END IF;

  SELECT COUNT(*) INTO v_row FROM essentials.offices o
  WHERE o.chamber_id = (SELECT id FROM essentials.chambers WHERE name = 'Countywide Elected Officials' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Deschutes County, Oregon, US'));
  IF v_row <> 4 THEN RAISE EXCEPTION 'FAILED (b): Deschutes row-officer offices=%, expected 4', v_row; END IF;

  SELECT COUNT(*) INTO v_school FROM essentials.offices o
  WHERE o.chamber_id = (SELECT id FROM essentials.chambers WHERE name = 'School Board' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Bend-La Pine Administrative School District 1, Oregon, US'));
  IF v_school <> 7 THEN RAISE EXCEPTION 'FAILED (b): Bend-La Pine board offices=%, expected 7', v_school; END IF;

  SELECT COUNT(*) INTO v_park FROM essentials.offices o
  WHERE o.chamber_id = (SELECT id FROM essentials.chambers WHERE name = 'Board of Directors' AND government_id = (SELECT id FROM essentials.governments WHERE name = 'Bend Metro Park & Recreation District, Oregon, US'));
  IF v_park <> 5 THEN RAISE EXCEPTION 'FAILED (b): BPRD board offices=%, expected 5', v_park; END IF;

  -- (c) geofence presence — independent of anything this migration inserts
  SELECT COUNT(*) INTO v_geo FROM essentials.geofence_boundaries
  WHERE (geo_id = '4105800' AND mtfcc = 'G4110')
     OR (geo_id = '41017' AND mtfcc = 'G4020')
     OR (geo_id = '4101980' AND mtfcc = 'G5420')
     OR (geo_id = 'bend-or-park-rec-district' AND mtfcc = 'X0024');
  IF v_geo <> 4 THEN
    RAISE EXCEPTION 'FAILED (c): Bend-area geofence rows=%, expected 4 — run scripts/import-bend-geofences.ts first', v_geo;
  END IF;

  -- (d) one chamber per district, city only
  SELECT COUNT(*) INTO v_split FROM (
    SELECT o.district_id
    FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
    WHERE d.geo_id = '4105800'
    GROUP BY o.district_id
    HAVING COUNT(DISTINCT o.chamber_id) > 1
  ) x;
  IF v_split <> 0 THEN RAISE EXCEPTION 'FAILED (d): city section-split rows=%', v_split; END IF;

  -- (e)
  SELECT COUNT(*) INTO v_nulls FROM essentials.politicians
  WHERE external_id IN (-4105801,-4105802,-4105803,-4105804,-4105805,-4105806,-4105807,-4101701,-4101702,-4101703,-4101711,-4101712,-4101713,-4101714,-4101981,-4101982,-4101983,-4101984,-4101985,-4101986,-4101987,-4105821,-4105822,-4105823,-4105824,-4105825) AND office_id IS NULL;
  IF v_nulls <> 0 THEN RAISE EXCEPTION 'FAILED (e): % politicians with NULL office_id', v_nulls; END IF;

  -- (f)
  SELECT COUNT(*) INTO v_repcity FROM essentials.offices o
  JOIN essentials.politicians p ON p.id = o.politician_id
  WHERE p.external_id IN (-4105801,-4105802,-4105803,-4105804,-4105805,-4105806,-4105807,-4105821,-4105822,-4105823,-4105824,-4105825)
    AND o.representing_city = 'Bend';
  IF v_repcity <> 12 THEN
    RAISE EXCEPTION 'FAILED (f): representing_city=Bend on % offices, expected 12', v_repcity;
  END IF;

  -- (g)
  SELECT COUNT(*) INTO v_countydis FROM essentials.districts d
  WHERE d.geo_id = '41017' AND d.district_type = 'COUNTY' AND d.state = 'or'
    AND d.government_id = (SELECT id FROM essentials.governments WHERE name = 'Deschutes County, Oregon, US');
  IF v_countydis <> 1 THEN
    RAISE EXCEPTION 'FAILED (g): Deschutes COUNTY district rows owned by the county gov=%, expected 1', v_countydis;
  END IF;

  RAISE NOTICE 'Post-verification PASSED: govs=4, offices 7/3/4/7/5=26, geofences=4, split=0, office_id nulls=0, representing_city=12, county district adopted';
END $$;


-- NOTE: the supabase_migrations.schema_migrations ledger entry is deliberately NOT written here.
-- This file is applied with psql over the Session pooler, whose role has no privileges on the
-- supabase_migrations schema; including the INSERT aborts the transaction and rolls back the whole
-- seed (observed 2026-07-24). Ledger registration for version '1414' is done separately as the
-- postgres role:  INSERT INTO supabase_migrations.schema_migrations (version) VALUES ('1414')
--                 ON CONFLICT (version) DO NOTHING;

COMMIT;
