-- 1619_districts_census_population_and_web.sql
--
-- Adds population and official web address to essentials.districts, backfilled from the
-- Census Bureau Government Units Listing 2025 (Annual Organization public use file):
--   https://www.census.gov/programs-surveys/gus/data/publicusefiles.html
--   https://www2.census.gov/programs-surveys/gus/datasets/2025/gov_units_2025.zip
--
-- Scope: CA + OR. 204 government units matched one or more of our
-- districts. 204 carry a population, 200 carry a usable official URL.
--
-- MATCHED ON FIPS ONLY -- never on name. Counties key on FIPS_STATE||FIPS_COUNTY (the file's
-- FIPS_PLACE for a county is a synthetic '99'+county code), places on FIPS_STATE||FIPS_PLACE.
-- A name match here would attribute a whole city's population to the wrong geography.
--
-- geo_id is deliberately NOT unique: an at-large body models each seat as its own district row,
-- so several rows share a place FIPS. Updating every row carrying that FIPS is correct -- they
-- describe the same place.
--
-- Idempotent. Re-running overwrites with the same source values and re-passes the gate.
-- Generated by scripts/gen-census-enrichment-migration.mts.

BEGIN;

ALTER TABLE essentials.districts
  ADD COLUMN IF NOT EXISTS population             integer,
  ADD COLUMN IF NOT EXISTS population_source_year smallint,
  ADD COLUMN IF NOT EXISTS official_web_url       text,
  ADD COLUMN IF NOT EXISTS census_unit_id         text;

COMMENT ON COLUMN essentials.districts.population IS
  'Resident population from the Census Government Units Listing 2025. See population_source_year for the vintage. Backfilled by migration 1619; NULL means not sourced, never zero.';
COMMENT ON COLUMN essentials.districts.population_source_year IS
  'Vintage of the population estimate, as published by the Census (migration 1619).';
COMMENT ON COLUMN essentials.districts.official_web_url IS
  'Official government URL as published in the Census Government Units Listing 2025 (migration 1619). Absolute http(s) only.';
COMMENT ON COLUMN essentials.districts.census_unit_id IS
  'CENSUS_ID_PID6 of the matching Government Units Listing record (migration 1619). Provenance and re-join key for future refreshes.';

CREATE TEMP TABLE _census_units (
  geo_id         text PRIMARY KEY,
  population     integer,
  pop_year       smallint,
  web_url        text,
  census_unit_id text
) ON COMMIT DROP;

INSERT INTO _census_units (geo_id, population, pop_year, web_url, census_unit_id) VALUES
    -- COUNTY OF ALAMEDA
    ('06001', 1622188, 2023, 'http://www.co.alameda.ca.us', '123083'),
    -- COUNTY OF ALPINE
    ('06003', 1141, 2023, 'http://www.alpinecountyca.gov', '161095'),
    -- CITY OF AGOURA HILLS
    ('0600394', 19474, 2023, 'http://www.ciagoura-hills.ca.us', '161196'),
    -- COUNTY OF AMADOR
    ('06005', 41811, 2023, 'http://www.co.amador.ca.us/', '203964'),
    -- COUNTY OF BUTTE
    ('06007', 207172, 2023, 'http://www.buttecounty.net', '161096'),
    -- CITY OF ALHAMBRA
    ('0600884', 79776, 2023, 'http://www.cityofalhambra.org/', '100673'),
    -- COUNTY OF CALAVERAS
    ('06009', 46565, 2023, 'http://www.co.calaveras.ca.us', '123084'),
    -- COUNTY OF COLUSA
    ('06011', 22037, 2023, 'http://www.colusacounty.org', '100617'),
    -- COUNTY OF CONTRA COSTA
    ('06013', 1155025, 2023, 'http://www.co.contracosta.ca.us/', '161097'),
    -- COUNTY OF DEL NORTE
    ('06015', 26589, 2023, 'http://www.dnco.org', '193099'),
    -- COUNTY OF EL DORADO
    ('06017', 192215, 2023, 'http://www.co.eldorado.ca.us', '183752'),
    -- COUNTY OF FRESNO
    ('06019', 1017162, 2023, 'http://www.co.fresno.ca.us/', '161098'),
    -- COUNTY OF GLENN
    ('06021', 28129, 2023, 'http://www.countyofglenn.net', '183753'),
    -- COUNTY OF HUMBOLDT
    ('06023', 133985, 2023, 'http://www.co.humboldt.ca.us', '161099'),
    -- CITY OF ARCADIA
    ('0602462', 54157, 2023, 'http://www.ci.arcadia.ca.us/', '123108'),
    -- COUNTY OF IMPERIAL
    ('06025', 179057, 2023, 'http://www.co.imperial.ca.us/', '161100'),
    -- COUNTY OF INYO
    ('06027', 18527, 2023, 'http://www.inyocounty.us/', '100622'),
    -- CITY OF ARTESIA
    ('0602896', 15597, 2023, 'http://www.cityofartesia.us', '161190'),
    -- COUNTY OF KERN
    ('06029', 913820, 2023, 'http://www.co.kern.ca.us', '189634'),
    -- COUNTY OF KINGS
    ('06031', 152682, 2023, 'http://www.countyofkings.com/', '161101'),
    -- CITY OF AVALON
    ('0603274', 3261, 2023, 'http://WWW.CITYOFAVALON.COM', '161162'),
    -- COUNTY OF LAKE
    ('06033', 67878, 2023, 'http://www.w.co.lake.ca.us', '161102'),
    -- CITY OF AZUSA
    ('0603386', 48272, 2023, 'http://www.ci.azusa.ca.us/', '161163'),
    -- COUNTY OF LASSEN
    ('06035', 28861, 2023, 'http://www.co.lassen.ca.us', '161103'),
    -- CITY OF BALDWIN PARK
    ('0603666', 68806, 2023, 'http://www.baldwinpark.com', '161164'),
    -- COUNTY OF LOS ANGELES
    ('06037', 9663345, 2023, 'http://www.lacounty.gov', '123085'),
    -- COUNTY OF MADERA
    ('06039', 162858, 2023, 'http://www.maderacounty.com', '207575'),
    -- COUNTY OF MARIN
    ('06041', 254407, 2023, 'http://www.co.marin.ca.us', '100630'),
    -- COUNTY OF MARIPOSA
    ('06043', 16919, 2023, 'http://www.mariposacounty.org', '203965'),
    -- COUNTY OF MENDOCINO
    ('06045', 89108, 2023, 'http://www.co.mendocino.ca.us/', '161104'),
    -- COUNTY OF MERCED
    ('06047', 291920, 2023, 'http://www.co.merced.ca.us', '161105'),
    -- CITY OF BELL
    ('0604870', 31864, 2023, NULL, '203970'),
    -- COUNTY OF MODOC
    ('06049', 8500, 2023, 'http://www.modoccounty.ca.us', '161106'),
    -- CITY OF BELLFLOWER
    ('0604982', 75122, 2023, 'http://www.bellflower.org', '161187'),
    -- CITY OF BELL GARDENS
    ('0604996', 37467, 2023, 'http://www.bellgardens.org', '100692'),
    -- COUNTY OF MONO
    ('06051', 13066, 2023, 'http://www.monocounty.ca.gov', '123086'),
    -- COUNTY OF MONTEREY
    ('06053', 430723, 2023, 'http://www.co.monterey.ca.us', '100633'),
    -- COUNTY OF NAPA
    ('06055', 133216, 2023, 'http://www.co.napa.ca.us', '161107'),
    -- COUNTY OF NEVADA
    ('06057', 102037, 2023, 'http://www.mynevadacounty.com', '193100'),
    -- COUNTY OF ORANGE
    ('06059', 3135755, 2023, 'http://www.ocgov.com', '207576'),
    -- CITY OF BERKELEY
    ('0606000', 118962, 2023, 'http://www.cityofberkeley.info', '123092'),
    -- COUNTY OF PLACER
    ('06061', 423561, 2023, 'http://www.placer.ca.gov', '123087'),
    -- COUNTY OF PLUMAS
    ('06063', 19131, 2023, 'http://www.countyofplumas.com', '183754'),
    -- CITY OF BEVERLY HILLS
    ('0606308', 30974, 2023, 'http://www.beverlyhills.org', '161165'),
    -- COUNTY OF RIVERSIDE
    ('06065', 2492442, 2023, 'http://www.co.riverside.ca.us', '161108'),
    -- COUNTY OF SACRAMENTO
    ('06067', 1584288, 2023, 'https://www.saccounty.gov/', '161109'),
    -- COUNTY OF SAN BENITO
    ('06069', 68175, 2023, 'http://www.san-benito.ca.us', '183755'),
    -- COUNTY OF SAN BERNARDINO
    ('06071', 2195611, 2023, 'http://www.sbcounty.gov', '161110'),
    -- COUNTY OF SAN DIEGO
    ('06073', 3269973, 2023, 'http://www.sdcounty.ca.gov', '161111'),
    -- COUNTY OF SAN JOAQUIN
    ('06077', 800965, 2023, 'http://www.sjgov.org', '161112'),
    -- COUNTY OF SAN LUIS OBISPO
    ('06079', 281639, 2023, 'http://www.co.slo.ca.us', '161113'),
    -- CITY OF BRADBURY
    ('0607946', 892, 2023, 'http://www.cityofbradbury.org/', '123116'),
    -- COUNTY OF SAN MATEO
    ('06081', 726353, 2023, 'http://www.smcgov.org', '123088'),
    -- COUNTY OF SANTA BARBARA
    ('06083', 441257, 2023, 'http://www.countyofsb.org', '161114'),
    -- COUNTY OF SANTA CLARA
    ('06085', 1877592, 2023, 'http://www.sccgov.org/', '183756'),
    -- COUNTY OF SANTA CRUZ
    ('06087', 261547, 2023, 'http://www.co.santa-cruz.ca.us', '194942'),
    -- COUNTY OF SHASTA
    ('06089', 180366, 2023, 'http://www.co.shasta.ca.us/', '161115'),
    -- CITY OF BURBANK
    ('0608954', 102755, 2023, 'http://www.burbankusa.com', '184443'),
    -- COUNTY OF SIERRA
    ('06091', 3200, 2023, 'http://www.sierracounty.ws', '161116'),
    -- COUNTY OF SISKIYOU
    ('06093', 42905, 2023, 'http://www.co.siskiyou.ca.us/', '123089'),
    -- COUNTY OF SOLANO
    ('06095', 449218, 2023, 'http://www.co.solano.ca.us', '100642'),
    -- CITY OF CALABASAS
    ('0609598', 22227, 2023, 'http://www.cityofcalabases.com', '123114'),
    -- COUNTY OF SONOMA
    ('06097', 481812, 2023, 'http://www.sonomacounty.org', '161117'),
    -- COUNTY OF STANISLAUS
    ('06099', 551430, 2023, 'http://www.stancounty.com', '123090'),
    -- COUNTY OF SUTTER
    ('06101', 97948, 2023, 'http://www.co.sutter.ca.us', '161118'),
    -- COUNTY OF TEHAMA
    ('06103', 64896, 2023, 'http://www.co.tehama.ca.us', '193101'),
    -- COUNTY OF TRINITY
    ('06105', 15670, 2023, 'http://www.trinitycounty.org', '161119'),
    -- COUNTY OF TULARE
    ('06107', 479468, 2023, 'http://www.co.tulare.ca.us', '123091'),
    -- COUNTY OF TUOLUMNE
    ('06109', 54204, 2023, 'http://www.tuolumnecounty.ca.gov', '184432'),
    -- COUNTY OF VENTURA
    ('06111', 829590, 2023, 'http://www.countyofventura.org/', '161120'),
    -- COUNTY OF YOLO
    ('06113', 220544, 2023, 'http://www.yolocounty.org', '161121'),
    -- COUNTY OF YUBA
    ('06115', 85722, 2023, 'http://www.co.yuba.ca.us/', '183757'),
    -- CITY OF CARSON
    ('0611530', 91139, 2023, 'http://ci.carson.ca.us', '183833'),
    -- CITY OF CERRITOS
    ('0612552', 46797, 2023, 'http://www.cerritos.us', '161168'),
    -- CITY OF CLAREMONT
    ('0613756', 35640, 2023, 'http://www.ci.claremont.ca.us', '189637'),
    -- CITY OF COMMERCE
    ('0614974', 11672, 2023, 'http://www.ci.commerce.ca.us/', '161191'),
    -- CITY OF COMPTON
    ('0615044', 90986, 2023, 'http://www.comptoncity.org/', '161166'),
    -- CITY OF COVINA
    ('0616742', 48728, 2023, 'http://www.covinaca.gov', '161167'),
    -- CITY OF CUDAHY
    ('0617498', 21723, 2023, 'http://www.cudahy.ca.us/', '123119'),
    -- CITY OF CULVER CITY
    ('0617568', 39041, 2023, 'http://www.culvercity.org', '100677'),
    -- CITY OF DIAMOND BAR
    ('0619192', 52041, 2023, 'http://www.diamondbarca.gov', '161186'),
    -- CITY OF DOWNEY
    ('0619766', 108816, 2023, 'http://www.downeyca.org/', '183829'),
    -- CITY OF DUARTE
    ('0619990', 23131, 2023, 'http://www.accessduarte.com/', '161188'),
    -- CITY OF EL MONTE
    ('0622230', 103794, 2023, 'http://www.elmonte.org', '161169'),
    -- CITY OF EL SEGUNDO
    ('0622412', 16445, 2023, 'http://www.elsegundo.org', '123109'),
    -- CITY OF FREMONT
    ('0626000', 226208, 2023, 'http://www.fremont.gov', '207577'),
    -- CITY OF GARDENA
    ('0628168', 58377, 2023, 'http://www.ci.gardena.ca.us/', '183861'),
    -- CITY OF GLENDALE
    ('0630000', 187050, 2023, 'http://www.ci.glendale.ca.us', '161170'),
    -- CITY OF GLENDORA
    ('0630014', 49934, 2023, 'http://www.ci.glendora.ca.us/', '161171'),
    -- CITY OF HAWAIIAN GARDENS
    ('0632506', 13396, 2023, 'http://hgcity.org/', '123121'),
    -- CITY OF HAWTHORNE
    ('0632548', 83364, 2023, 'http://www.cityofhawthorne.org', '100681'),
    -- CITY OF HERMOSA BEACH
    ('0633364', 18641, 2023, 'http://hermosabch.org', '193108'),
    -- CITY OF HIDDEN HILLS
    ('0633518', 1685, 2023, 'http://www.hiddenhillscity.org', '161197'),
    -- CITY OF HUNTINGTON BEACH
    ('0636000', 192129, 2023, 'http://www.ci.huntington-beach.ca.us/', '100709'),
    -- CITY OF HUNTINGTON PARK
    ('0636056', 51942, 2023, 'http://www.huntingtonpark.org/', '211216'),
    -- CITY OF INDUSTRY
    ('0636490', 257, 2023, 'http://www.cityofindustry.org', '207584'),
    -- CITY OF INGLEWOOD
    ('0636546', 102865, 2023, 'http://www.cityofinglewood.org/', '123110'),
    -- CITY OF IRWINDALE
    ('0636826', 1426, 2023, 'http://www.ci.irwindale.ca.us', '211219'),
    -- CITY OF LA CANADA FLINTRIDGE
    ('0639003', 19538, 2023, 'http://www.lacanadaflintridge.com', '161199'),
    -- CITY OF LA HABRA HEIGHTS
    ('0639304', 5368, 2023, 'http://www.la-habra-heights.org/', '161194'),
    -- CITY OF LAKEWOOD
    ('0639892', 78135, 2023, 'http://www.LakewoodCity.org', '183827'),
    -- CITY OF LA MIRADA
    ('0640032', 45505, 2023, 'http://www.cityoflamirada.org/', '161192'),
    -- CITY OF LANCASTER
    ('0640130', 166236, 2023, 'http://www.cityoflancasterca.org/', '184451'),
    -- CITY OF LA PALMA
    ('0640256', 15029, 2023, 'http://WWW.CITYOFLAPALMA.ORG', '123132'),
    -- CITY OF LA PUENTE
    ('0640340', 36516, 2023, 'http://www.lapuente.org', '161172'),
    -- CITY OF LA VERNE
    ('0640830', 29898, 2023, 'http://www.ci.laverne.ca.us', '123111'),
    -- CITY OF LAWNDALE
    ('0640886', 30155, 2023, 'http://www.lawndalecity.org/', '123118'),
    -- CITY OF LOMITA
    ('0642468', 19782, 2023, 'http://www.lomita.com/cityhall', '161198'),
    -- CITY OF LONG BEACH
    ('0643000', 449468, 2023, 'http://www.longbeach.gov', '161173'),
    -- CITY OF LOS ALAMITOS
    ('0643224', 11901, 2023, 'http://www.ci.losalamitos.ca.us/', '211209'),
    -- CITY OF LOS ANGELES
    ('0644000', 3820914, 2023, 'http://www.ci.la.ca.us/', '161174'),
    -- CITY OF LYNWOOD
    ('0644574', 63234, 2023, 'http://www.lynwood.ca.us/', '161175'),
    -- CITY OF MALIBU
    ('0645246', 10277, 2023, 'http://www.malibucity.org', '183830'),
    -- CITY OF MANHATTAN BEACH
    ('0645400', 33369, 2023, 'http://www.ci.manhattan-beach.ca.us', '123112'),
    -- CITY OF MAYWOOD
    ('0646492', 23824, 2023, 'http://www.cityofmaywood.com', '184447'),
    -- CITY OF MONROVIA
    ('0648648', 36768, 2023, 'http://www.ci.monrovia.ca.us', '161176'),
    -- CITY OF MONTEBELLO
    ('0648816', 60015, 2023, 'http://www.cityofmontebello.com/', '161177'),
    -- CITY OF MONTEREY PARK
    ('0648914', 57877, 2023, 'http://www.ci.monterey-park.ca.us', '183828'),
    -- CITY OF NORWALK
    ('0652526', 98078, 2023, 'http://www.ci-norwalk.ca.us', '123117'),
    -- CITY OF PALMDALE
    ('0655156', 161404, 2023, 'http://www.cityofpalmdale.org/', '183832'),
    -- CITY OF PALOS VERDES ESTATES
    ('0655380', 12646, 2023, 'http://www.pvestates.org', '161178'),
    -- CITY OF PARAMOUNT
    ('0655618', 51072, 2023, 'http://www.paramountcity.com/', '161189'),
    -- CITY OF PASADENA
    ('0656000', 133560, 2023, 'http://www.ci.pasadena.ca.us/', '207582'),
    -- CITY OF PICO RIVERA
    ('0656924', 59189, 2023, 'http://www.picorivera.org', '207585'),
    -- CITY OF POMONA
    ('0658072', 145502, 2023, 'http://www.ci.pomona.ca.us/', '161179'),
    -- CITY OF RANCHO PALOS VERDES
    ('0659514', 39980, 2023, 'http://www.palosverdes.com/rpv/', '184452'),
    -- CITY OF REDONDO BEACH
    ('0660018', 67749, 2023, 'http://www.redondo.org', '100688'),
    -- CITY OF ROLLING HILLS
    ('0662602', 1644, 2023, 'http://www.rollinghills.org', '211217'),
    -- CITY OF ROLLING HILLS ESTATES
    ('0662644', 8033, 2023, 'http://www.ci.rollinghillsestates.ca.us', '193110'),
    -- CITY OF ROSEMEAD
    ('0662896', 49305, 2023, 'http://www.cityofrosemead.org', '123120'),
    -- CITY OF SACRAMENTO
    ('0664000', 526384, 2023, 'http://www.cityofsacramento.org', '161241'),
    -- CITY OF SAN DIEGO
    ('0666000', 1388320, 2023, 'http://www.sandiego.gov/', '207598'),
    -- CITY OF SAN DIMAS
    ('0666070', 33105, 2023, 'http://cityofsandimas.com', '161193'),
    -- CITY OF SAN FERNANDO
    ('0666140', 23364, 2023, 'http://www.ci.san-fernando.ca.us/', '211218'),
    -- CITY AND COUNTY OF SAN FRANCISCO
    ('0667000', 808988, 2023, 'http://www.sfgov.org', '161258'),
    -- CITY OF SAN GABRIEL
    ('0667042', 37732, 2023, 'http://www.sangabrielcity.com/', '161180'),
    -- CITY OF SAN JOSE
    ('0668000', 969655, 2023, 'http://www.sanjoseca.gov', '100745'),
    -- CITY OF SAN MARINO
    ('0668224', 11977, 2023, 'http://www.cityofsanmarino.org', '161181'),
    -- CITY OF SANTA CLARITA
    ('0669088', 224028, 2023, 'http://www.santaclarita.com', '137232'),
    -- CITY OF SANTA FE SPRINGS
    ('0669154', 20174, 2023, 'http://santafesprings.org', '183831'),
    -- CITY OF SANTA MONICA
    ('0670000', 89922, 2023, 'http://pen.ci.santa-monica.ca.us', '201366'),
    -- CITY OF SIERRA MADRE
    ('0671806', 10713, 2023, NULL, '203971'),
    -- CITY OF SIGNAL HILL
    ('0671876', 11249, 2023, 'http://www.cityofsignalhill.org', '193109'),
    -- CITY OF SOUTH EL MONTE
    ('0672996', 19032, 2023, 'http://www.ci.southelmonte.ca.us/', '189638'),
    -- CITY OF SOUTH GATE
    ('0673080', 90070, 2023, 'http://www.sogate.org', '161182'),
    -- CITY OF SOUTH PASADENA
    ('0673220', 25623, 2023, 'http://www.ci.southpasadena.ca.us', '161183'),
    -- CITY OF TEMPLE
    ('0678148', 34854, 2023, 'http://www.templecity.us', '193111'),
    -- CITY OF TORRANCE
    ('0680000', 139224, 2023, 'http://www.torranceca.gov', '207583'),
    -- CITY OF VERNON
    ('0682422', 209, 2023, 'http://www.cityofvernon.org/', '123113'),
    -- CITY OF WALNUT
    ('0683332', 27104, 2023, 'http://www.ci.walnut.ca.us', '100691'),
    -- CITY OF WEST COVINA
    ('0684200', 105617, 2023, 'http://www.westcovina.org', '100689'),
    -- CITY OF WEST HOLLYWOOD
    ('0684410', 34349, 2023, 'http://www.weho.org', '123115'),
    -- CITY OF WESTLAKE VILLAGE
    ('0684438', 7573, 2023, 'http://www.wlv.org', '161195'),
    -- CITY OF WHITTIER
    ('0685292', 84143, 2023, 'http://www.cityofwhittier.org', '161184'),
    -- COUNTY OF BAKER
    ('41001', 16912, 2023, 'http://www.bakercounty.org', '183793'),
    -- COUNTY OF BENTON
    ('41003', 97713, 2023, 'http://www.co.benton.or.us/', '209184'),
    -- COUNTY OF CLACKAMAS
    ('41005', 423173, 2023, 'http://www.clackamas.us', '173610'),
    -- COUNTY OF CLATSOP
    ('41007', 41102, 2023, 'http://www.co.clatsop.or.us/', '209185'),
    -- COUNTY OF COLUMBIA
    ('41009', 53880, 2023, 'http://www.co.columbia.or.us/', '173611'),
    -- COUNTY OF COOS
    ('41011', 64212, 2023, 'http://www.co.coos.or.us/', '133194'),
    -- COUNTY OF CROOK
    ('41013', 26952, 2023, 'http://www.co.crook.or.us/', '187138'),
    -- COUNTY OF CURRY
    ('41015', 23296, 2023, 'http://www.co.curry.or.us/', '173612'),
    -- COUNTY OF DESCHUTES
    ('41017', 208513, 2023, 'http://www.deschutes.org/', '173613'),
    -- COUNTY OF DOUGLAS
    ('41019', 112435, 2023, 'http://www.co.douglas.or.us/', '133195'),
    -- COUNTY OF GILLIAM
    ('41021', 2026, 2023, 'http://www.co.gilliam.or.us', '111584'),
    -- COUNTY OF GRANT
    ('41023', 7215, 2023, 'http://www.gcoregonlive2.com', '173614'),
    -- COUNTY OF HARNEY
    ('41025', 7440, 2023, 'http://www.co.harney.or.us/', '193955'),
    -- COUNTY OF HOOD RIVER
    ('41027', 23745, 2023, 'http://www.co.hood-river.or.us/', '133196'),
    -- COUNTY OF JACKSON
    ('41029', 220768, 2023, 'http://www.co.jackson.or.us/', '173615'),
    -- COUNTY OF JEFFERSON
    ('41031', 25454, 2023, 'http://www.co.jefferson.or.us', '173616'),
    -- COUNTY OF JOSEPHINE
    ('41033', 87821, 2023, 'http://www.co.josephine.or.us/', '173617'),
    -- COUNTY OF KLAMATH
    ('41035', 70003, 2023, 'http://www.klamathcounty.org', '111585'),
    -- COUNTY OF LAKE
    ('41037', 8293, 2023, 'http://www.lakecountyor.org/', '133197'),
    -- COUNTY OF LANE
    ('41039', 381181, 2023, 'http://www.lanecounty.org', '173618'),
    -- COUNTY OF LINCOLN
    ('41041', 50821, 2023, 'http://www.co.lincoln.or.us/', '173619'),
    -- COUNTY OF LINN
    ('41043', 131496, 2023, 'http://www.co.linn.or.us/', '202429'),
    -- COUNTY OF MALHEUR
    ('41045', 32044, 2023, 'http://www.malheurco.org/', '133198'),
    -- COUNTY OF MARION
    ('41047', 346741, 2023, 'http://co.marion.or.us/', '133199'),
    -- COUNTY OF MORROW
    ('41049', 12302, 2023, 'http://www.morrowcountyoregon.com/', '173620'),
    -- COUNTY OF MULTNOMAH
    ('41051', 789698, 2023, 'http://www.multco.us', '173621'),
    -- COUNTY OF POLK
    ('41053', 89805, 2023, 'http://www.co.polk.or.us/', '173622'),
    -- CITY OF BEAVERTON
    ('4105350', 96945, 2023, 'http://www.beavertonoregon.gov/', '173706'),
    -- COUNTY OF SHERMAN
    ('41055', 1951, 2023, 'http://www.sherman-county.com/', '193956'),
    -- COUNTY OF TILLAMOOK
    ('41057', 27417, 2023, 'http://www.co.tillamook.or.us/', '111587'),
    -- CITY OF BEND
    ('4105800', 104557, 2023, 'http://www.ci.bend.or.us/', '193960'),
    -- COUNTY OF UMATILLA
    ('41059', 80053, 2023, 'http://www.umatillacounty.net', '183795'),
    -- COUNTY OF UNION
    ('41061', 25944, 2023, 'http://www.unioncounty.org', '209186'),
    -- COUNTY OF WALLOWA
    ('41063', 7674, 2023, 'http://www.wallowa.co.or.us', '173623'),
    -- COUNTY OF WASCO
    ('41065', 26333, 2023, 'http://www.co.wasco.or.us/', '133200'),
    -- COUNTY OF WASHINGTON
    ('41067', 598865, 2023, 'http://www.co.washington.or.us', '173624'),
    -- COUNTY OF WHEELER
    ('41069', 1436, 2023, 'http://www.wheelercountyoregon.gov', '173625'),
    -- COUNTY OF YAMHILL
    ('41071', 108644, 2023, 'http://www.co.yamhill.or.us/', '183794'),
    -- CITY OF CORNELIUS
    ('4115550', 14981, 2023, 'http://www.ci.cornelius.or.us/', '111621'),
    -- CITY OF FAIRVIEW
    ('4124250', 10782, 2023, 'http://www.fairvieworegon.gov', '209204'),
    -- CITY OF FOREST GROVE
    ('4126200', 26799, 2023, 'http://www.forestgroveor.gov', '173707'),
    -- CITY OF GRESHAM
    ('4131250', 110685, 2023, 'http://www.greshamoregon.gov', '173685'),
    -- CITY OF HILLSBORO
    ('4134100', 107730, 2023, 'http://www.ci.hillsboro.or.us/', '211253'),
    -- CITY OF MAYWOOD PARK
    ('4146730', 801, 2023, NULL, '133230'),
    -- CITY OF PORTLAND
    ('4159000', 630498, 2023, NULL, '211254'),
    -- CITY OF SHERWOOD
    ('4167100', 19957, 2023, 'http://www.sherwoodoregon.gov', '173708'),
    -- CITY OF TIGARD
    ('4173650', 55590, 2023, 'http://www.tigardor.gov/', '173710'),
    -- CITY OF TROUTDALE
    ('4174850', 15717, 2023, 'http://www.troutdaleoregon.gov', '209205'),
    -- CITY OF TUALATIN
    ('4174950', 27383, 2023, 'http://www.ci.tualatin.or.us/', '111622'),
    -- CITY OF WOOD VILLAGE
    ('4183950', 4717, 2023, 'http://www.ci.woodvillage.or.us', '173686')
;

UPDATE essentials.districts d
   SET population             = c.population,
       population_source_year = c.pop_year,
       official_web_url       = c.web_url,
       census_unit_id         = c.census_unit_id
  FROM _census_units c
 WHERE btrim(d.geo_id) = c.geo_id
   AND lower(d.state) = ANY (ARRAY['ca', 'or'])
   AND d.district_type IN ('LOCAL', 'LOCAL_EXEC', 'COUNTY')
   AND (d.population             IS DISTINCT FROM c.population
     OR d.population_source_year IS DISTINCT FROM c.pop_year
     OR d.official_web_url       IS DISTINCT FROM c.web_url
     OR d.census_unit_id         IS DISTINCT FROM c.census_unit_id);

DO $$
DECLARE
  v_staged   integer;
  v_enriched integer;
  v_bad_pop  integer;
  v_bad_url  integer;
  v_orphan   integer;
BEGIN
  SELECT count(*) INTO v_staged FROM _census_units;
  IF v_staged <> 204 THEN
    RAISE EXCEPTION '1619: staged % units, expected 204', v_staged;
  END IF;

  -- Every district carrying a matched FIPS must now be enriched. If this count drops, the join
  -- silently missed rows and the coverage figures built on it would be wrong.
  SELECT count(*) INTO v_enriched
    FROM essentials.districts d
    JOIN _census_units c ON btrim(d.geo_id) = c.geo_id
   WHERE lower(d.state) = ANY (ARRAY['ca', 'or'])
     AND d.district_type IN ('LOCAL', 'LOCAL_EXEC', 'COUNTY')
     AND d.census_unit_id IS NOT DISTINCT FROM c.census_unit_id;
  IF v_enriched = 0 THEN
    RAISE EXCEPTION '1619: no districts were enriched';
  END IF;

  -- Population is a count of people: zero or negative is a parse failure, not a small town.
  SELECT count(*) INTO v_bad_pop
    FROM essentials.districts
   WHERE population IS NOT NULL AND population <= 0;
  IF v_bad_pop > 0 THEN
    RAISE EXCEPTION '1619: % districts have a non-positive population', v_bad_pop;
  END IF;

  SELECT count(*) INTO v_bad_url
    FROM essentials.districts
   WHERE official_web_url IS NOT NULL AND official_web_url !~* '^https?://';
  IF v_bad_url > 0 THEN
    RAISE EXCEPTION '1619: % districts have a non-absolute official_web_url', v_bad_url;
  END IF;

  -- Nothing outside the intended scope may have been touched.
  SELECT count(*) INTO v_orphan
    FROM essentials.districts
   WHERE census_unit_id IS NOT NULL
     AND (lower(state) <> ALL (ARRAY['ca', 'or'])
       OR district_type NOT IN ('LOCAL', 'LOCAL_EXEC', 'COUNTY'));
  IF v_orphan > 0 THEN
    RAISE EXCEPTION '1619: % districts enriched outside the intended scope', v_orphan;
  END IF;

  RAISE NOTICE '1619 OK: % units staged, % district rows enriched', v_staged, v_enriched;
END $$;

COMMIT;
