-- 1906_tx_held_set_cleared_and_ssm_carry_correction.sql
-- Two things: the NINE rows migration 1903 held out for the operator, now cleared; and a
-- CORRECTION to migration 1903, which blanked thirteen same-sex-marriage rows by mistake.
-- 21 rows written in all.
--
-- ══ PART ONE: THE HELD SET, CLEARED (8 chair moves; the 9th is not a move) ════════════════════
-- A citation repair may not move a chair, so migration 1903 wrote 243 keys and held out twelve
-- whose own record proved a rung the chair did not hold. Three were settled by migrations 1904
-- and 1905. The operator cleared the rest on 2026-10-08.
--
--   Ann Johnson     redistricting  1 -> 2   HJR 59 and HB 241/HJR 22 seat APPOINTEES of elected
--                                           officials, balanced by party. 🔴 Her row said "No
--                                           specific bill found"; she authored HB 241 in the
--                                           special session she was breaking quorum over.
--   Chris Turner    redistricting  1 -> 2   HJR 83 seats four senior-member appointees, a fifth
--                                           they choose and two retired federal judges.
--   Chris Turner    fossil-fuels   4 -> 3   ⚠ the row's OWN reasoning argued rung 3 while the
--                                           chair said 4. Rung 4 is "expand drilling permits",
--                                           which nothing on his record supports.
--   Ryan Guillen    healthcare     4 -> 3   🔴 the row said "No evidence of supporting Medicaid
--                                           expansion". HE AUTHORED TWELVE EXPANSION BILLS, two
--                                           of them constitutional amendments REQUIRING it.
--   Gina Hinojosa   same-sex-marr  2 -> 1   coauthor of a housing-discrimination ban on the
--                                           basis of sexual orientation -- the clause that is
--                                           unique to rung 1.
--   Chuy Hinojosa   same-sex-marr  3 -> 1   🔴 the instrument 1903 held him on was his OLDEST --
--                                           a 2013 civil-union bill, filed two years before
--                                           Obergefell. Everything after it is rung 1: equal
--                                           marriage (SB 98), repeal of the constitutional ban
--                                           (SJR 13/16/9) and three discrimination bans.
--   Briscoe Cain    trans-athletes 5 -> 4   ten instruments, every one rung 4, none reaching 5.
--   Carrie Isaac    trans-athletes 5 -> 4   HB 23 is rung 4 verbatim; the HB 229 her row cited
--                                           defines male and female for state records and says
--                                           nothing about athletics.
--   Ken Paxton      redistricting  NOT WRITTEN -- he is not in this cohort. His second citation
--                                  is Abbott v. Perez, the case his own office litigated and
--                                  won, which is evidence about the position rather than a
--                                  biography. The national "Wikipedia only" detector counts any
--                                  en.wikipedia.org URL as a bio; twelve Texas rows are this
--                                  false positive. His row is left exactly as it stands.
--
-- ══ 🔴🔴 PART TWO: CORRECTING MIGRATION 1903 -- 13 ROWS BLANKED BY A TEST APPLIED TO THE WRONG
--    PAIR OF RUNGS ════════════════════════════════════════════════════════════════════════════
-- Migration 1903 blanked 26 rows as LADDER_SCOPE, on the ground that the Season 2 rung at the
-- row's value asks a different question from the Season 1 rung at that value. For 13 of them
-- that comparison was invalid.
--
-- 🔑 THERE IS NO CARRY QUESTION FOR A ROW THAT IS ALREADY IN SEASON 2. The carry gate compared
-- the SAME NUMBER in both seasons for every row. That is the right pair only when the chair was
-- read from Season 1. Where a Season 2 answer already exists, the Season 2 value and the Season
-- 2 rung text ARE the live pair: the row was carried long ago, by whoever wrote Season 2.
--
-- AND THIS LADDER WAS RENUMBERED, SO THE SAME NUMBER IS NOT THE SAME RUNG. Season 2 INSERTED a
-- new rung 1 on same-sex marriage -- "full legal equality: equal marriage plus protection from
-- discrimination (such as in jobs and housing)" -- and shifted the rest down. Measured against
-- production, the Season 2 write remapped:
--       Season 1 rung 1  ->  Season 2 rung 2     476 rows
--       Season 1 rung 2  ->  Season 2 rung 3     143 rows
--       Season 1 rung 3  ->  blanked              28 rows  (the federalism rung, which Season 2
--                                                           does not contain)
--       rungs 4 and 5 unchanged                  229 rows
-- So a row sitting at Season 2 value 2 arrived there from Season 1 value 1, and reading it
-- against Season 1's rung 2 reads it against a rung it was never on. All 13 of the wrongly
-- blanked rows had a Season 2 answer already; the other 13 LADDER_SCOPE blanks in migration
-- 1903 (climate-change 2, four rows; voting-rights 2, eight; and one same-sex-marriage row
-- still in Season 1) were read from Season 1 and remain correct.
--
--   8 RESTORED to the chair Season 2 already held, with the citation repaired to a first-person
--     instrument: Christian Manuel, Hubert Vo, Jessica Gonzalez, Josey Garcia, Lauren Ashley
--     Simmons, Lulu Flores, Suleman Lalani, Terry Canales.
--   5 LEFT AT 0 AND RE-REASONED, because their own record argues a DIFFERENT rung and a chair
--     move needs a decision rather than a repair: Erin Zwiener, John Bryant, Penny Morales
--     Shaw, Toni Rose, Venton Jones. Each filed a bill prohibiting discrimination on the basis
--     of sexual orientation or gender identity, and Season 2 rung 1 is the only rung that adds
--     anti-discrimination protection to equal marriage. Their blanks now say so instead of
--     giving the wrong reason.
--
-- ══ 🔴 A SECOND DEFECT FOUND IN THE SAME PLACE ════════════════════════════════════════════════
-- The rung-1 pattern matched "discrimination ON THE BASIS OF sexual orientation" and not
-- "discrimination BASED ON sexual orientation". Texas captions use both forms freely and the
-- second is the commoner one, so the rule missed a first-person rung-1 filing on six rows --
-- including every one of Chuy Hinojosa's eight. Both defects are in the same part of the
-- pipeline and both are fixed; the re-run changes exactly these 13 rows and nothing else in the
-- 282.
--
-- Season 1 is CLOSED and IMMUTABLE: every write here is forward, into Season 2.
-- No migration runner exists; this file records SQL applied by hand.


DO $pre$
DECLARE n integer;
BEGIN
  -- 1. all thirteen same-sex-marriage rows are sitting at 0, blanked by migration 1903, and
  --    carry its reasoning. If they do not, this file is correcting something else.
  SELECT count(*) INTO n FROM inform.politician_answers a
    JOIN inform.politician_context c ON c.politician_id = a.politician_id
     AND c.topic_id = a.topic_id AND c.season_id = a.season_id
   WHERE a.season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND a.topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid AND a.value = 0
     AND c.reasoning LIKE '%(migration 1903)%'
     AND a.politician_id IN (SELECT * FROM (VALUES
    ('6d13d033-f970-4356-8cce-73d81f342dc8'::uuid),
    ('25183d7a-9300-4065-8d42-941ae826ca91'::uuid),
    ('e36f4bc1-4896-48cb-8ae7-39e1f742ace3'::uuid),
    ('2824037c-8574-41f6-9fc9-a1342d32250b'::uuid),
    ('d62f0017-3d27-43f0-8908-781f3c9e5050'::uuid),
    ('6af34442-997a-4b8d-8c19-3ae65519fa38'::uuid),
    ('96a7a21f-87c1-4a3c-b7ee-4caa30d8ff09'::uuid),
    ('02691090-c16c-4216-ac3b-1caa89a618a8'::uuid),
    ('17648ed7-5a6a-4ac1-b49e-0d3eaf08417e'::uuid),
    ('70920806-a146-4dc3-8cc7-4566f9caf903'::uuid),
    ('81d931a9-5906-4ff4-9ac8-15b49c4ae38a'::uuid),
    ('43567dd1-db59-40af-928e-03708237eb98'::uuid),
    ('e8058f2b-c68a-474b-b9fe-df4d2d22545b'::uuid)
     ) AS k(pid));
  IF n <> 13 THEN
    RAISE EXCEPTION 'migration 1906: expected 13 same-sex-marriage rows blanked at 0 by 1903, found %', n;
  END IF;

  -- 2. THE RENUMBERING THIS CORRECTION RESTS ON IS REAL, not inferred. Season 1 rung 2 and
  --    Season 2 rung 2 on this ladder must say DIFFERENT things, and Season 1 rung 2 must say
  --    what Season 2 calls rung 3 -- that is the shift that made the original test invalid.
  SELECT count(*) INTO n
    FROM inform.compass_stance_revisions s1r
    JOIN inform.season_questions q1 ON q1.topic_revision_id = s1r.topic_revision_id
     AND q1.season_id = '2d5d67d1-2a2a-4c73-88bb-3c2e3e33cba3'
    JOIN inform.season_questions q2 ON q2.topic_id = q1.topic_id AND q2.season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194'
    JOIN inform.compass_stance_revisions s2r ON s2r.topic_revision_id = q2.topic_revision_id
   WHERE q1.topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid AND s1r.value = 2 AND s2r.value = 3
     AND lower(s1r.text) LIKE '%right to decline%'
     AND lower(s2r.text) LIKE '%right to decline%';
  IF n <> 1 THEN
    RAISE EXCEPTION 'migration 1906: the same-sex-marriage rung shift S1(2)->S2(3) is not what this file assumes (%)', n;
  END IF;

  -- 3. the eight being restored must have no Season 2 answer other than the 0 we are replacing
  SELECT count(*) INTO n FROM inform.politician_answers
   WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid AND value <> 0
     AND politician_id IN (SELECT * FROM (VALUES
    ('6d13d033-f970-4356-8cce-73d81f342dc8'::uuid),
    ('25183d7a-9300-4065-8d42-941ae826ca91'::uuid),
    ('e36f4bc1-4896-48cb-8ae7-39e1f742ace3'::uuid),
    ('2824037c-8574-41f6-9fc9-a1342d32250b'::uuid),
    ('d62f0017-3d27-43f0-8908-781f3c9e5050'::uuid),
    ('6af34442-997a-4b8d-8c19-3ae65519fa38'::uuid),
    ('96a7a21f-87c1-4a3c-b7ee-4caa30d8ff09'::uuid),
    ('02691090-c16c-4216-ac3b-1caa89a618a8'::uuid)
     ) AS k(pid));
  IF n <> 0 THEN
    RAISE EXCEPTION 'migration 1906: % of the 8 restorations already hold a non-zero Season 2 chair', n;
  END IF;
END
$pre$;

INSERT INTO inform.politician_context
  (politician_id, topic_id, season_id, topic_revision_id, reasoning, sources)
VALUES
  -- Ann Johnson / redistricting  (chair 1 -> 2, CHAIR_MOVED_HELD_SET_CLEARED)
    ('136fc01b-f061-4e30-9aa7-d5735e0a4659'::uuid, '48cc9585-ec22-4f53-8d42-6839828dd36f'::uuid, '86d893a1-c1a2-4bbf-b4e5-69ec43221194'::uuid, 'c7f973fc-33f5-4570-bfe2-bff4ac6141cc'::uuid, 'Chair moved from 1 to 2 on 2026-10-08 (migration 1906). Migration 1903 held this row out rather than repair it, because a citation repair may not move a chair and this member''s own record proves a rung the chair did not hold. The operator cleared the held set on 2026-10-08. 🔴 THE ROW SAID "No specific bill found" AND SHE WAS THE AUTHOR OF ONE. THE RECORD: Johnson authored HJR 59 (87R), which seats a seven-member commission appointed by the most senior member of each chamber and by the most senior member of each chamber belonging to the other party; and HB 241 with HJR 22 (89th, second called session), which seats eight members appointed by the four party caucuses, two each, who then choose a ninth from the independent applicants. Both are commissions of APPOINTEES OF ELECTED OFFICIALS, balanced by party -- rung 2, "independent redistricting commissions with equal representation from both major parties", and not rung 1 on either reading of "no elected officials involved at any level". She filed HB 241 in the very special session she was breaking quorum over. 🔑 THE SIDE IS UNCHANGED: she voted against HB 4, the 2025 mid-decade congressional map, 88-52 on Record 30, and was absent and undisclaimed on all nine quorum rolls taken while she served.', ARRAY['http://journals.house.texas.gov/hjrnl/892/pdf/89C2DAY05FINAL.PDF', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=87R&Bill=HJR59', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=892&Bill=HB241', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=892&Bill=HJR22', 'https://capitol.texas.gov/tlodocs/892/billtext/html/HB00241I.htm', 'https://en.wikipedia.org/wiki/Ann_Johnson_(politician)']::text[]),
  -- Chris Turner / redistricting  (chair 1 -> 2, CHAIR_MOVED_HELD_SET_CLEARED)
    ('625ec7a8-10b3-446d-a935-a8bee51e72fd'::uuid, '48cc9585-ec22-4f53-8d42-6839828dd36f'::uuid, '86d893a1-c1a2-4bbf-b4e5-69ec43221194'::uuid, 'c7f973fc-33f5-4570-bfe2-bff4ac6141cc'::uuid, 'Chair moved from 1 to 2 on 2026-10-08 (migration 1906). Migration 1903 held this row out rather than repair it, because a citation repair may not move a chair and this member''s own record proves a rung the chair did not hold. The operator cleared the held set on 2026-10-08. THE RECORD: Turner authored HJR 83 (88R), establishing a seven-member Texas Redistricting Commission: four members appointed by the most senior member of each chamber and by the most senior member of each chamber belonging to a different party, a fifth chosen by those four, and two retired federal judges appointed by the fifth. Those are APPOINTEES OF ELECTED OFFICIALS, balanced by party -- rung 2 exactly, and not rung 1 on either reading of "no elected officials involved at any level". 🔑 THE SIDE IS UNCHANGED: he voted against HB 4, the 2025 mid-decade congressional map, 88-52 on Record 30, and was absent and undisclaimed on all nine quorum rolls taken while he served.', ARRAY['http://journals.house.texas.gov/hjrnl/892/pdf/89C2DAY05FINAL.PDF', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HJR83', 'https://capitol.texas.gov/tlodocs/88R/billtext/html/HJ00083I.htm', 'https://en.wikipedia.org/wiki/Chris_Turner_(Texas_politician)']::text[]),
  -- Chris Turner / fossil-fuels  (chair 4 -> 3, CHAIR_MOVED_HELD_SET_CLEARED)
    ('625ec7a8-10b3-446d-a935-a8bee51e72fd'::uuid, 'a22215c3-6693-4bc2-b248-01aebba14570'::uuid, '86d893a1-c1a2-4bbf-b4e5-69ec43221194'::uuid, 'c8e12b53-64f6-48ac-9c2d-0a3cf4d3df9b'::uuid, 'Chair moved from 4 to 3 on 2026-10-08 (migration 1906). Migration 1903 held this row out rather than repair it, because a citation repair may not move a chair and this member''s own record proves a rung the chair did not hold. The operator cleared the held set on 2026-10-08. ⚠ THE ROW''S OWN REASONING ARGUED RUNG 3 WHILE THE CHAIR SAID 4. It read: "his position is more moderate than a full ban -- he has supported regulating emissions and safety while not calling to ban new drilling permits", which is rung 3, "maintain current levels of fossil fuel production with existing environmental regulations". Rung 4 is "expand fossil fuel drilling permits", which nothing on his record supports. THE RECORD: he voted against SB 13 (87R), which bars state investment in companies that boycott energy firms, 105-40 -- a vote that rules out the two pro-extraction rungs. ⚠ That instrument establishes the SIDE and not the rung, so 3 is the placement consistent with both the vote and the row''s own argument, and it is the smallest move that removes the contradiction.', ARRAY['http://journals.house.texas.gov/hjrnl/87r/pdf/87RDAY60FINAL.PDF', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=87R&Bill=SB13', 'https://en.wikipedia.org/wiki/Chris_Turner_(Texas_politician)']::text[]),
  -- Ryan Guillen / healthcare  (chair 4 -> 3, CHAIR_MOVED_HELD_SET_CLEARED)
    ('b6ea3b73-5664-462f-bc99-6c377418c34f'::uuid, 'e8dad4a8-eb93-4931-91f5-d8fb5d7dd529'::uuid, '86d893a1-c1a2-4bbf-b4e5-69ec43221194'::uuid, 'afc91aa2-4d48-4db6-aebd-f4c9788e6ad7'::uuid, 'Chair moved from 4 to 3 on 2026-10-08 (migration 1906). Migration 1903 held this row out rather than repair it, because a citation repair may not move a chair and this member''s own record proves a rung the chair did not hold. The operator cleared the held set on 2026-10-08. 🔴 THE ROW SAID "No evidence of supporting Medicaid expansion or a public option". HE AUTHORED TWELVE MEDICAID-EXPANSION BILLS. THE RECORD: as author -- HB 2308 and HJR 46 (86R); HB 171, HB 398, HB 509, HB 1189, HB 1741, HB 4053, HB 4406 and HJR 24 (87R) -- and as coauthor, HB 590 (86R) and HB 3871 (87R), the Live Well Texas program. Several would expand Medicaid "to all persons for whom federal matching funds are available", and two are constitutional amendments REQUIRING the state to expand it. ⚖ THE RUNG: expanding Medicaid under the Affordable Care Act covers low-income adults while leaving everyone else to private insurance, which is rung 3 -- "Help people who can''t afford care and expand programs for seniors and low-income residents, while keeping private insurance for everyone else" -- not rung 2, which requires universal coverage, and emphatically not rung 4, "only help the poorest people". ⚠ HE CHANGED PARTY IN NOVEMBER 2021, after these bills. Under the operator''s latest-filing rule his subsequent healthcare filings were checked and none points the other way: his later work is administrative (89R HB 2994, a report on Medicaid eligibility) or protective of Medicaid recipients (88R HB 44, on provider discrimination against them).', ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=86R&Bill=HB2308', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=86R&Bill=HJR46', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=87R&Bill=HB171', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=87R&Bill=HB3871', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=87R&Bill=HJR24', 'https://en.wikipedia.org/wiki/Ryan_Guillen']::text[]),
  -- Briscoe Cain / trans-athletes  (chair 5 -> 4, CHAIR_MOVED_HELD_SET_CLEARED)
    ('9d6eae75-9400-46bf-a2f1-34de55db3d49'::uuid, 'd1618b9c-0b9e-45af-b986-bb33d270b8e4'::uuid, '86d893a1-c1a2-4bbf-b4e5-69ec43221194'::uuid, 'af2c6427-daf8-4819-93ba-42db212bae68'::uuid, 'Chair moved from 5 to 4 on 2026-10-08 (migration 1906). Migration 1903 held this row out rather than repair it, because a citation repair may not move a chair and this member''s own record proves a rung the chair did not hold. The operator cleared the held set on 2026-10-08. 🔴 TEN INSTRUMENTS, ALL OF THEM RUNG 4, AND NOT ONE REACHES RUNG 5. THE RECORD: he voted for HB 25 (87th, second called session), 76-54, requiring public school students to compete in interscholastic athletics according to their biological sex; and he is a coauthor of HB 187, HB 212 and HB 274 (87th first called), HB 25 and HB 100 (second called), HB 10, HB 25 and HB 84 (third called), and HB 23 (88R), every one of them the same requirement. ⚖ THE RUNG: that caption and rung 4 are the same sentence -- "require transgender athletes to compete only on teams matching their biological sex assigned at birth". Rung 5 is different in kind: "completely ban all transgender athletes from competing in any organized sports competitions". HB 25 and its companions do not ban anyone from sport; they route transgender students to the team matching their birth sex. A precise instrument unseats as well as confirms, and nothing he has filed or voted for reaches rung 5. The row itself hedged: it said he "would require trans athletes to compete by biological sex OR ban them entirely".', ARRAY['http://journals.house.texas.gov/hjrnl/872/pdf/87C2DAY27FINAL.PDF', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=872&Bill=HB25', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=873&Bill=HB10', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HB23', 'https://en.wikipedia.org/wiki/Briscoe_Cain']::text[]),
  -- Carrie Isaac / trans-athletes  (chair 5 -> 4, CHAIR_MOVED_HELD_SET_CLEARED)
    ('42370d1a-2ffd-480b-a24f-b2a39405c929'::uuid, 'd1618b9c-0b9e-45af-b986-bb33d270b8e4'::uuid, '86d893a1-c1a2-4bbf-b4e5-69ec43221194'::uuid, 'af2c6427-daf8-4819-93ba-42db212bae68'::uuid, 'Chair moved from 5 to 4 on 2026-10-08 (migration 1906). Migration 1903 held this row out rather than repair it, because a citation repair may not move a chair and this member''s own record proves a rung the chair did not hold. The operator cleared the held set on 2026-10-08. THE RECORD: she is a coauthor of HB 23 (88R), "Relating to participation in athletic activities based on biological sex; providing a civil right of action", which is rung 4 verbatim -- "require transgender athletes to compete only on teams matching their biological sex assigned at birth". ⚖ Rung 5 is a different claim: "completely ban all transgender athletes from competing in any organized sports competitions". HB 23 does not do that; it routes transgender students to the team matching their birth sex. ⚠ THE BILL THE ROW CITED DOES NOT REACH RUNG 5 EITHER: it rested on HB 229, the "Women''s Bill of Rights", which is captioned "general definitions for and collection of governmental information regarding biological sex" -- it defines male and female for state records and says nothing about athletic eligibility at all.', ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HB23', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=HB229', 'https://capitol.texas.gov/Members/MemberInfo.aspx?Leg=89&Chamber=H&Code=A4265', 'https://en.wikipedia.org/wiki/Carrie_Isaac']::text[]);

INSERT INTO inform.politician_answers
  (politician_id, topic_id, season_id, topic_revision_id, value)
VALUES
  -- Ann Johnson / redistricting  (chair 1 -> 2, CHAIR_MOVED_HELD_SET_CLEARED) -> 2
    ('136fc01b-f061-4e30-9aa7-d5735e0a4659'::uuid, '48cc9585-ec22-4f53-8d42-6839828dd36f'::uuid, '86d893a1-c1a2-4bbf-b4e5-69ec43221194'::uuid, 'c7f973fc-33f5-4570-bfe2-bff4ac6141cc'::uuid, 2),
  -- Chris Turner / redistricting  (chair 1 -> 2, CHAIR_MOVED_HELD_SET_CLEARED) -> 2
    ('625ec7a8-10b3-446d-a935-a8bee51e72fd'::uuid, '48cc9585-ec22-4f53-8d42-6839828dd36f'::uuid, '86d893a1-c1a2-4bbf-b4e5-69ec43221194'::uuid, 'c7f973fc-33f5-4570-bfe2-bff4ac6141cc'::uuid, 2),
  -- Chris Turner / fossil-fuels  (chair 4 -> 3, CHAIR_MOVED_HELD_SET_CLEARED) -> 3
    ('625ec7a8-10b3-446d-a935-a8bee51e72fd'::uuid, 'a22215c3-6693-4bc2-b248-01aebba14570'::uuid, '86d893a1-c1a2-4bbf-b4e5-69ec43221194'::uuid, 'c8e12b53-64f6-48ac-9c2d-0a3cf4d3df9b'::uuid, 3),
  -- Ryan Guillen / healthcare  (chair 4 -> 3, CHAIR_MOVED_HELD_SET_CLEARED) -> 3
    ('b6ea3b73-5664-462f-bc99-6c377418c34f'::uuid, 'e8dad4a8-eb93-4931-91f5-d8fb5d7dd529'::uuid, '86d893a1-c1a2-4bbf-b4e5-69ec43221194'::uuid, 'afc91aa2-4d48-4db6-aebd-f4c9788e6ad7'::uuid, 3),
  -- Briscoe Cain / trans-athletes  (chair 5 -> 4, CHAIR_MOVED_HELD_SET_CLEARED) -> 4
    ('9d6eae75-9400-46bf-a2f1-34de55db3d49'::uuid, 'd1618b9c-0b9e-45af-b986-bb33d270b8e4'::uuid, '86d893a1-c1a2-4bbf-b4e5-69ec43221194'::uuid, 'af2c6427-daf8-4819-93ba-42db212bae68'::uuid, 4),
  -- Carrie Isaac / trans-athletes  (chair 5 -> 4, CHAIR_MOVED_HELD_SET_CLEARED) -> 4
    ('42370d1a-2ffd-480b-a24f-b2a39405c929'::uuid, 'd1618b9c-0b9e-45af-b986-bb33d270b8e4'::uuid, '86d893a1-c1a2-4bbf-b4e5-69ec43221194'::uuid, 'af2c6427-daf8-4819-93ba-42db212bae68'::uuid, 4);

-- Gina Hinojosa / same-sex-marriage  (chair 2 -> 1, CHAIR_MOVED_HELD_SET_CLEARED)
UPDATE inform.politician_context SET reasoning = 'Chair moved from 2 to 1 on 2026-10-08 (migration 1906). Migration 1903 held this row out rather than repair it, because a citation repair may not move a chair and this member''s own record proves a rung the chair did not hold. The operator cleared the held set on 2026-10-08. THE RECORD: she is a coauthor of HB 188 (86R), "Relating to the prohibition of housing discrimination on the basis of sexual orientation or gender identity or expression". ⚖ THE RUNG: Season 2 rung 1 is the ONLY rung that adds anti-discrimination protection to equal marriage -- "full legal equality: equal marriage plus protection from discrimination (such as in jobs and housing)". Rung 2 is marriage equality alone. This row already sat at rung 2, so the marriage half was granted; her own bill supplies the half that distinguishes rung 1, and in the example the rung itself gives. ⚠ Her later filings -- the repeal of the offense of homosexual conduct (88R HB 2055, 89R HB 1738) -- span rungs 1 to 3 and so do not conflict with rung 1 under the latest-filing rule; a band that CONTAINS the rung is not a disagreement with it.', sources = ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=86R&Bill=HB188', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HB2055', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=HB1738', 'https://en.wikipedia.org/wiki/Gina_Hinojosa']::text[], updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = 'bc67255e-e79d-4328-9775-a7ac7cd1efce'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
UPDATE inform.politician_answers SET value = 1, updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = 'bc67255e-e79d-4328-9775-a7ac7cd1efce'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
-- Juan "Chuy" Hinojosa / same-sex-marriage  (chair 3 -> 1, CHAIR_MOVED_HELD_SET_CLEARED)
UPDATE inform.politician_context SET reasoning = 'Chair moved from 3 to 1 on 2026-10-08 (migration 1906). Migration 1903 held this row out rather than repair it, because a citation repair may not move a chair and this member''s own record proves a rung the chair did not hold. The operator cleared the held set on 2026-10-08. 🔴 THE INSTRUMENT MIGRATION 1903 HELD THIS ROW ON WAS HIS OLDEST, AND HIS RECORD MOVED PAST IT. That instrument was SB 480 (83R, 2013), "the formation of a civil union between persons of the same sex", which reads as rung 4 -- civil unions instead of marriage. It was filed two years before Obergefell, when Texas still banned same-sex marriage by constitutional provision. EVERYTHING HE FILED AFTERWARDS IS RUNG 1, as author: SB 98 (84R), authorizing a marriage between two persons of the same sex and repealing the statutory prohibition; SJR 13 (84R), SJR 16 (85R) and SJR 9 (86R), constitutional amendments to repeal the provision restricting marriage to one man and one woman; SB 157 (85R), the conforming statutory changes; and SB 165 (85R), SB 38 (85 first called session) and SB 151 (86R), prohibiting discrimination based on sexual orientation or gender identity. ⚖ That is BOTH halves of Season 2 rung 1 -- equal marriage AND protection from discrimination -- filed repeatedly, under his own name, over four legislatures. Under the operator''s rule that THE LATEST FILING GOVERNS, this is rung 1 and the 2013 civil-union bill is superseded by his own later work rather than representative of it.', sources = ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=83R&Bill=SB480', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=84R&Bill=SB98', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=85R&Bill=SB157', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=85R&Bill=SB165', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=86R&Bill=SB151', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=86R&Bill=SJR9', 'https://en.wikipedia.org/wiki/Juan_%22Chuy%22_Hinojosa', 'https://en.wikipedia.org/wiki/Juan_Hinojosa']::text[], updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '6153ca04-6c12-4a04-b58b-5a6db1e92861'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
UPDATE inform.politician_answers SET value = 1, updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '6153ca04-6c12-4a04-b58b-5a6db1e92861'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
-- Christian Manuel / same-sex-marriage  (0 -> 2, RESTORED_WRONGLY_BLANKED)
UPDATE inform.politician_context SET reasoning = 'Citation repaired and chair restored 2026-10-08 (migration 1906). 🔴 CORRECTING MIGRATION 1903, WHICH BLANKED THIS ROW BY MISTAKE. 1903 recorded it as a ladder-scope blank on the ground that the Season 2 rung at this value asks a different question from Season 1''s. THAT TEST WAS APPLIED TO THE WRONG PAIR OF RUNGS. Season 2 INSERTED a new rung 1 on this ladder -- "full legal equality: equal marriage plus protection from discrimination" -- and shifted the others down, remapping Season 1 rung 1 to Season 2 rung 2 (476 rows), Season 1 rung 2 to Season 2 rung 3 (143 rows) and blanking Season 1 rung 3, the federalism rung Season 2 does not contain (28 rows). This row ALREADY HAD a Season 2 answer at its remapped value, so it had been carried correctly long before this audit and no carry question existed for it; comparing Season 1 rung 2 against Season 2 rung 2 compared two different rungs. The chair is restored to where Season 2 already had it. 🔑 AND THE ROW HAS A FIRST-PERSON INSTRUMENT, which is what it now cites instead of a biography: he is a coauthor of HB 2055 (88R) and HB 1738 (89R), both repealing the offense of homosexual conduct. ⚠ That places this member on the equal-marriage side of the ladder; it does not by itself separate rung 1 from rung 2 or 3, and the chair keeps the placement Season 2 already held.', sources = ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HB2055', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=HB1738', 'https://en.wikipedia.org/wiki/Christian_Manuel']::text[], updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '6d13d033-f970-4356-8cce-73d81f342dc8'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
UPDATE inform.politician_answers SET value = 2, updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '6d13d033-f970-4356-8cce-73d81f342dc8'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
-- Hubert Vo / same-sex-marriage  (0 -> 2, RESTORED_WRONGLY_BLANKED)
UPDATE inform.politician_context SET reasoning = 'Citation repaired and chair restored 2026-10-08 (migration 1906). 🔴 CORRECTING MIGRATION 1903, WHICH BLANKED THIS ROW BY MISTAKE. 1903 recorded it as a ladder-scope blank on the ground that the Season 2 rung at this value asks a different question from Season 1''s. THAT TEST WAS APPLIED TO THE WRONG PAIR OF RUNGS. Season 2 INSERTED a new rung 1 on this ladder -- "full legal equality: equal marriage plus protection from discrimination" -- and shifted the others down, remapping Season 1 rung 1 to Season 2 rung 2 (476 rows), Season 1 rung 2 to Season 2 rung 3 (143 rows) and blanking Season 1 rung 3, the federalism rung Season 2 does not contain (28 rows). This row ALREADY HAD a Season 2 answer at its remapped value, so it had been carried correctly long before this audit and no carry question existed for it; comparing Season 1 rung 2 against Season 2 rung 2 compared two different rungs. The chair is restored to where Season 2 already had it. 🔑 AND THE ROW HAS A FIRST-PERSON INSTRUMENT, which is what it now cites instead of a biography: he is a coauthor of HB 2055 (88R), repealing the offense of homosexual conduct. ⚠ That places this member on the equal-marriage side of the ladder; it does not by itself separate rung 1 from rung 2 or 3, and the chair keeps the placement Season 2 already held.', sources = ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HB2055', 'https://en.wikipedia.org/wiki/Hubert_Vo']::text[], updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '25183d7a-9300-4065-8d42-941ae826ca91'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
UPDATE inform.politician_answers SET value = 2, updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '25183d7a-9300-4065-8d42-941ae826ca91'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
-- Jessica Gonzalez / same-sex-marriage  (0 -> 2, RESTORED_WRONGLY_BLANKED)
UPDATE inform.politician_context SET reasoning = 'Citation repaired and chair restored 2026-10-08 (migration 1906). 🔴 CORRECTING MIGRATION 1903, WHICH BLANKED THIS ROW BY MISTAKE. 1903 recorded it as a ladder-scope blank on the ground that the Season 2 rung at this value asks a different question from Season 1''s. THAT TEST WAS APPLIED TO THE WRONG PAIR OF RUNGS. Season 2 INSERTED a new rung 1 on this ladder -- "full legal equality: equal marriage plus protection from discrimination" -- and shifted the others down, remapping Season 1 rung 1 to Season 2 rung 2 (476 rows), Season 1 rung 2 to Season 2 rung 3 (143 rows) and blanking Season 1 rung 3, the federalism rung Season 2 does not contain (28 rows). This row ALREADY HAD a Season 2 answer at its remapped value, so it had been carried correctly long before this audit and no carry question existed for it; comparing Season 1 rung 2 against Season 2 rung 2 compared two different rungs. The chair is restored to where Season 2 already had it. 🔑 AND THE ROW HAS A FIRST-PERSON INSTRUMENT, which is what it now cites instead of a biography: she is the author of HR 1401 (89R), recognising 26 June 2025 as Marriage Equality Day, and a coauthor of HB 2055 (88R) and HB 1738 (89R), both repealing the offense of homosexual conduct. ⚠ That places this member on the equal-marriage side of the ladder; it does not by itself separate rung 1 from rung 2 or 3, and the chair keeps the placement Season 2 already held.', sources = ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HB2055', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=HB1738', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=HR1401', 'https://en.wikipedia.org/wiki/Jessica_Gonz%C3%A1lez_(politician)']::text[], updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = 'e36f4bc1-4896-48cb-8ae7-39e1f742ace3'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
UPDATE inform.politician_answers SET value = 2, updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = 'e36f4bc1-4896-48cb-8ae7-39e1f742ace3'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
-- Josey Garcia / same-sex-marriage  (0 -> 2, RESTORED_WRONGLY_BLANKED)
UPDATE inform.politician_context SET reasoning = 'Citation repaired and chair restored 2026-10-08 (migration 1906). 🔴 CORRECTING MIGRATION 1903, WHICH BLANKED THIS ROW BY MISTAKE. 1903 recorded it as a ladder-scope blank on the ground that the Season 2 rung at this value asks a different question from Season 1''s. THAT TEST WAS APPLIED TO THE WRONG PAIR OF RUNGS. Season 2 INSERTED a new rung 1 on this ladder -- "full legal equality: equal marriage plus protection from discrimination" -- and shifted the others down, remapping Season 1 rung 1 to Season 2 rung 2 (476 rows), Season 1 rung 2 to Season 2 rung 3 (143 rows) and blanking Season 1 rung 3, the federalism rung Season 2 does not contain (28 rows). This row ALREADY HAD a Season 2 answer at its remapped value, so it had been carried correctly long before this audit and no carry question existed for it; comparing Season 1 rung 2 against Season 2 rung 2 compared two different rungs. The chair is restored to where Season 2 already had it. 🔑 AND THE ROW HAS A FIRST-PERSON INSTRUMENT, which is what it now cites instead of a biography: she is a coauthor of HB 2055 (88R) and HB 1738 (89R), both repealing the offense of homosexual conduct. ⚠ That places this member on the equal-marriage side of the ladder; it does not by itself separate rung 1 from rung 2 or 3, and the chair keeps the placement Season 2 already held.', sources = ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HB2055', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=HB1738', 'https://en.wikipedia.org/wiki/Josey_Garcia']::text[], updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '2824037c-8574-41f6-9fc9-a1342d32250b'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
UPDATE inform.politician_answers SET value = 2, updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '2824037c-8574-41f6-9fc9-a1342d32250b'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
-- Lauren Ashley Simmons / same-sex-marriage  (0 -> 2, RESTORED_WRONGLY_BLANKED)
UPDATE inform.politician_context SET reasoning = 'Citation repaired and chair restored 2026-10-08 (migration 1906). 🔴 CORRECTING MIGRATION 1903, WHICH BLANKED THIS ROW BY MISTAKE. 1903 recorded it as a ladder-scope blank on the ground that the Season 2 rung at this value asks a different question from Season 1''s. THAT TEST WAS APPLIED TO THE WRONG PAIR OF RUNGS. Season 2 INSERTED a new rung 1 on this ladder -- "full legal equality: equal marriage plus protection from discrimination" -- and shifted the others down, remapping Season 1 rung 1 to Season 2 rung 2 (476 rows), Season 1 rung 2 to Season 2 rung 3 (143 rows) and blanking Season 1 rung 3, the federalism rung Season 2 does not contain (28 rows). This row ALREADY HAD a Season 2 answer at its remapped value, so it had been carried correctly long before this audit and no carry question existed for it; comparing Season 1 rung 2 against Season 2 rung 2 compared two different rungs. The chair is restored to where Season 2 already had it. 🔑 AND THE ROW HAS A FIRST-PERSON INSTRUMENT, which is what it now cites instead of a biography: she is a coauthor of HB 1738 (89R), repealing the offense of homosexual conduct. ⚠ That places this member on the equal-marriage side of the ladder; it does not by itself separate rung 1 from rung 2 or 3, and the chair keeps the placement Season 2 already held.', sources = ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=HB1738', 'https://en.wikipedia.org/wiki/Lauren_Simmons']::text[], updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = 'd62f0017-3d27-43f0-8908-781f3c9e5050'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
UPDATE inform.politician_answers SET value = 2, updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = 'd62f0017-3d27-43f0-8908-781f3c9e5050'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
-- Lulu Flores / same-sex-marriage  (0 -> 2, RESTORED_WRONGLY_BLANKED)
UPDATE inform.politician_context SET reasoning = 'Citation repaired and chair restored 2026-10-08 (migration 1906). 🔴 CORRECTING MIGRATION 1903, WHICH BLANKED THIS ROW BY MISTAKE. 1903 recorded it as a ladder-scope blank on the ground that the Season 2 rung at this value asks a different question from Season 1''s. THAT TEST WAS APPLIED TO THE WRONG PAIR OF RUNGS. Season 2 INSERTED a new rung 1 on this ladder -- "full legal equality: equal marriage plus protection from discrimination" -- and shifted the others down, remapping Season 1 rung 1 to Season 2 rung 2 (476 rows), Season 1 rung 2 to Season 2 rung 3 (143 rows) and blanking Season 1 rung 3, the federalism rung Season 2 does not contain (28 rows). This row ALREADY HAD a Season 2 answer at its remapped value, so it had been carried correctly long before this audit and no carry question existed for it; comparing Season 1 rung 2 against Season 2 rung 2 compared two different rungs. The chair is restored to where Season 2 already had it. 🔑 AND THE ROW HAS A FIRST-PERSON INSTRUMENT, which is what it now cites instead of a biography: she is a coauthor of HB 2055 (88R) and HB 1738 (89R), both repealing the offense of homosexual conduct. ⚠ That places this member on the equal-marriage side of the ladder; it does not by itself separate rung 1 from rung 2 or 3, and the chair keeps the placement Season 2 already held.', sources = ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HB2055', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=HB1738', 'https://capitol.texas.gov/Members/MemberInfo.aspx?Leg=89&Chamber=H&Code=A4150', 'https://en.wikipedia.org/wiki/Lulu_Flores']::text[], updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '6af34442-997a-4b8d-8c19-3ae65519fa38'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
UPDATE inform.politician_answers SET value = 2, updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '6af34442-997a-4b8d-8c19-3ae65519fa38'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
-- Suleman Lalani / same-sex-marriage  (0 -> 2, RESTORED_WRONGLY_BLANKED)
UPDATE inform.politician_context SET reasoning = 'Citation repaired and chair restored 2026-10-08 (migration 1906). 🔴 CORRECTING MIGRATION 1903, WHICH BLANKED THIS ROW BY MISTAKE. 1903 recorded it as a ladder-scope blank on the ground that the Season 2 rung at this value asks a different question from Season 1''s. THAT TEST WAS APPLIED TO THE WRONG PAIR OF RUNGS. Season 2 INSERTED a new rung 1 on this ladder -- "full legal equality: equal marriage plus protection from discrimination" -- and shifted the others down, remapping Season 1 rung 1 to Season 2 rung 2 (476 rows), Season 1 rung 2 to Season 2 rung 3 (143 rows) and blanking Season 1 rung 3, the federalism rung Season 2 does not contain (28 rows). This row ALREADY HAD a Season 2 answer at its remapped value, so it had been carried correctly long before this audit and no carry question existed for it; comparing Season 1 rung 2 against Season 2 rung 2 compared two different rungs. The chair is restored to where Season 2 already had it. 🔑 AND THE ROW HAS A FIRST-PERSON INSTRUMENT, which is what it now cites instead of a biography: he is a coauthor of HB 2055 (88R) and HB 1738 (89R), both repealing the offense of homosexual conduct. ⚠ That places this member on the equal-marriage side of the ladder; it does not by itself separate rung 1 from rung 2 or 3, and the chair keeps the placement Season 2 already held.', sources = ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HB2055', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=HB1738', 'https://capitol.texas.gov/Members/MemberInfo.aspx?Leg=89&Chamber=H&Code=A4285', 'https://en.wikipedia.org/wiki/Suleman_Lalani']::text[], updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '96a7a21f-87c1-4a3c-b7ee-4caa30d8ff09'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
UPDATE inform.politician_answers SET value = 2, updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '96a7a21f-87c1-4a3c-b7ee-4caa30d8ff09'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
-- Terry Canales / same-sex-marriage  (0 -> 2, RESTORED_WRONGLY_BLANKED)
UPDATE inform.politician_context SET reasoning = 'Citation repaired and chair restored 2026-10-08 (migration 1906). 🔴 CORRECTING MIGRATION 1903, WHICH BLANKED THIS ROW BY MISTAKE. 1903 recorded it as a ladder-scope blank on the ground that the Season 2 rung at this value asks a different question from Season 1''s. THAT TEST WAS APPLIED TO THE WRONG PAIR OF RUNGS. Season 2 INSERTED a new rung 1 on this ladder -- "full legal equality: equal marriage plus protection from discrimination" -- and shifted the others down, remapping Season 1 rung 1 to Season 2 rung 2 (476 rows), Season 1 rung 2 to Season 2 rung 3 (143 rows) and blanking Season 1 rung 3, the federalism rung Season 2 does not contain (28 rows). This row ALREADY HAD a Season 2 answer at its remapped value, so it had been carried correctly long before this audit and no carry question existed for it; comparing Season 1 rung 2 against Season 2 rung 2 compared two different rungs. The chair is restored to where Season 2 already had it. 🔑 AND THE ROW HAS A FIRST-PERSON INSTRUMENT, which is what it now cites instead of a biography: he is a coauthor of HB 2055 (88R) and HB 1738 (89R), both repealing the offense of homosexual conduct. ⚠ That places this member on the equal-marriage side of the ladder; it does not by itself separate rung 1 from rung 2 or 3, and the chair keeps the placement Season 2 already held.', sources = ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HB2055', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=HB1738', 'https://capitol.texas.gov/Members/MemberInfo.aspx?Leg=89&Chamber=H&Code=A2340']::text[], updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '02691090-c16c-4216-ac3b-1caa89a618a8'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
UPDATE inform.politician_answers SET value = 2, updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '02691090-c16c-4216-ac3b-1caa89a618a8'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
-- Erin Zwiener / same-sex-marriage  (stays 0, RUNG_1_ARGUED_AWAITING_DECISION)
UPDATE inform.politician_context SET reasoning = 'Blanked 2026-10-08 (migration 1906), and the reason RESTATED because the reason migration 1903 gave was wrong. 🔴 CORRECTING MIGRATION 1903, WHICH BLANKED THIS ROW BY MISTAKE. 1903 recorded it as a ladder-scope blank on the ground that the Season 2 rung at this value asks a different question from Season 1''s. THAT TEST WAS APPLIED TO THE WRONG PAIR OF RUNGS. Season 2 INSERTED a new rung 1 on this ladder -- "full legal equality: equal marriage plus protection from discrimination" -- and shifted the others down, remapping Season 1 rung 1 to Season 2 rung 2 (476 rows), Season 1 rung 2 to Season 2 rung 3 (143 rows) and blanking Season 1 rung 3, the federalism rung Season 2 does not contain (28 rows). This row ALREADY HAD a Season 2 answer at its remapped value, so it had been carried correctly long before this audit and no carry question existed for it; comparing Season 1 rung 2 against Season 2 rung 2 compared two different rungs. The chair is restored to where Season 2 already had it. ⚠ THIS ROW IS NOT RESTORED WITH THE OTHERS, because its own record argues a DIFFERENT rung from the one Season 2 holds and a chair move needs a decision, not a repair. THE RECORD: HB 254 (86R), as coauthor -- bills prohibiting discrimination on the basis of sexual orientation or gender identity. Season 2 rung 1 is the only rung that adds anti-discrimination protection to equal marriage, and this row already sat above the marriage threshold, so its own filings argue rung 1 rather than rung 2. It is left at 0 pending that decision rather than written at a chair its own evidence contradicts. The sources examined are kept below. This is a blank, not a deletion.', sources = ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=86R&Bill=HB254', 'https://en.wikipedia.org/wiki/Erin_Zwiener']::text[], updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '17648ed7-5a6a-4ac1-b49e-0d3eaf08417e'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
UPDATE inform.politician_answers SET value = 0, updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '17648ed7-5a6a-4ac1-b49e-0d3eaf08417e'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
-- John Bryant / same-sex-marriage  (stays 0, RUNG_1_ARGUED_AWAITING_DECISION)
UPDATE inform.politician_context SET reasoning = 'Blanked 2026-10-08 (migration 1906), and the reason RESTATED because the reason migration 1903 gave was wrong. 🔴 CORRECTING MIGRATION 1903, WHICH BLANKED THIS ROW BY MISTAKE. 1903 recorded it as a ladder-scope blank on the ground that the Season 2 rung at this value asks a different question from Season 1''s. THAT TEST WAS APPLIED TO THE WRONG PAIR OF RUNGS. Season 2 INSERTED a new rung 1 on this ladder -- "full legal equality: equal marriage plus protection from discrimination" -- and shifted the others down, remapping Season 1 rung 1 to Season 2 rung 2 (476 rows), Season 1 rung 2 to Season 2 rung 3 (143 rows) and blanking Season 1 rung 3, the federalism rung Season 2 does not contain (28 rows). This row ALREADY HAD a Season 2 answer at its remapped value, so it had been carried correctly long before this audit and no carry question existed for it; comparing Season 1 rung 2 against Season 2 rung 2 compared two different rungs. The chair is restored to where Season 2 already had it. ⚠ THIS ROW IS NOT RESTORED WITH THE OTHERS, because its own record argues a DIFFERENT rung from the one Season 2 holds and a chair move needs a decision, not a repair. THE RECORD: HB 1806 (88R), as coauthor, and HB 5031 (88R) and HB 2758 (89R) as author, the statutory changes recognising same-sex marriages and parenting relationships -- bills prohibiting discrimination on the basis of sexual orientation or gender identity. Season 2 rung 1 is the only rung that adds anti-discrimination protection to equal marriage, and this row already sat above the marriage threshold, so its own filings argue rung 1 rather than rung 3. It is left at 0 pending that decision rather than written at a chair its own evidence contradicts. The sources examined are kept below. This is a blank, not a deletion.', sources = ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HB1806', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HB5031', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=HB2758', 'https://capitol.texas.gov/Members/MemberInfo.aspx?Leg=89&Chamber=H&Code=A4120', 'https://en.wikipedia.org/wiki/John_Bryant_(Texas_politician)']::text[], updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '70920806-a146-4dc3-8cc7-4566f9caf903'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
UPDATE inform.politician_answers SET value = 0, updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '70920806-a146-4dc3-8cc7-4566f9caf903'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
-- Penny Morales Shaw / same-sex-marriage  (stays 0, RUNG_1_ARGUED_AWAITING_DECISION)
UPDATE inform.politician_context SET reasoning = 'Blanked 2026-10-08 (migration 1906), and the reason RESTATED because the reason migration 1903 gave was wrong. 🔴 CORRECTING MIGRATION 1903, WHICH BLANKED THIS ROW BY MISTAKE. 1903 recorded it as a ladder-scope blank on the ground that the Season 2 rung at this value asks a different question from Season 1''s. THAT TEST WAS APPLIED TO THE WRONG PAIR OF RUNGS. Season 2 INSERTED a new rung 1 on this ladder -- "full legal equality: equal marriage plus protection from discrimination" -- and shifted the others down, remapping Season 1 rung 1 to Season 2 rung 2 (476 rows), Season 1 rung 2 to Season 2 rung 3 (143 rows) and blanking Season 1 rung 3, the federalism rung Season 2 does not contain (28 rows). This row ALREADY HAD a Season 2 answer at its remapped value, so it had been carried correctly long before this audit and no carry question existed for it; comparing Season 1 rung 2 against Season 2 rung 2 compared two different rungs. The chair is restored to where Season 2 already had it. ⚠ THIS ROW IS NOT RESTORED WITH THE OTHERS, because its own record argues a DIFFERENT rung from the one Season 2 holds and a chair move needs a decision, not a repair. THE RECORD: HB 3796 (87R) and HB 1806 (88R) as author, and HB 850 (88R) as coauthor -- bills prohibiting discrimination on the basis of sexual orientation or gender identity. Season 2 rung 1 is the only rung that adds anti-discrimination protection to equal marriage, and this row already sat above the marriage threshold, so its own filings argue rung 1 rather than rung 2. It is left at 0 pending that decision rather than written at a chair its own evidence contradicts. The sources examined are kept below. This is a blank, not a deletion.', sources = ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=87R&Bill=HB3796', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HB1806', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HB850', 'https://capitol.texas.gov/Members/MemberInfo.aspx?Leg=89&Chamber=H&Code=A4035', 'https://en.wikipedia.org/wiki/Penny_Morales_Shaw']::text[], updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '81d931a9-5906-4ff4-9ac8-15b49c4ae38a'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
UPDATE inform.politician_answers SET value = 0, updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '81d931a9-5906-4ff4-9ac8-15b49c4ae38a'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
-- Toni Rose / same-sex-marriage  (stays 0, RUNG_1_ARGUED_AWAITING_DECISION)
UPDATE inform.politician_context SET reasoning = 'Blanked 2026-10-08 (migration 1906), and the reason RESTATED because the reason migration 1903 gave was wrong. 🔴 CORRECTING MIGRATION 1903, WHICH BLANKED THIS ROW BY MISTAKE. 1903 recorded it as a ladder-scope blank on the ground that the Season 2 rung at this value asks a different question from Season 1''s. THAT TEST WAS APPLIED TO THE WRONG PAIR OF RUNGS. Season 2 INSERTED a new rung 1 on this ladder -- "full legal equality: equal marriage plus protection from discrimination" -- and shifted the others down, remapping Season 1 rung 1 to Season 2 rung 2 (476 rows), Season 1 rung 2 to Season 2 rung 3 (143 rows) and blanking Season 1 rung 3, the federalism rung Season 2 does not contain (28 rows). This row ALREADY HAD a Season 2 answer at its remapped value, so it had been carried correctly long before this audit and no carry question existed for it; comparing Season 1 rung 2 against Season 2 rung 2 compared two different rungs. The chair is restored to where Season 2 already had it. ⚠ THIS ROW IS NOT RESTORED WITH THE OTHERS, because its own record argues a DIFFERENT rung from the one Season 2 holds and a chair move needs a decision, not a repair. THE RECORD: HB 4122 (87R) and HB 725 (88R), both as author -- bills prohibiting discrimination on the basis of sexual orientation or gender identity. Season 2 rung 1 is the only rung that adds anti-discrimination protection to equal marriage, and this row already sat above the marriage threshold, so its own filings argue rung 1 rather than rung 2. It is left at 0 pending that decision rather than written at a chair its own evidence contradicts. The sources examined are kept below. This is a blank, not a deletion.', sources = ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=87R&Bill=HB4122', 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HB725', 'https://capitol.texas.gov/Members/MemberInfo.aspx?Leg=89&Chamber=H&Code=A2555']::text[], updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '43567dd1-db59-40af-928e-03708237eb98'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
UPDATE inform.politician_answers SET value = 0, updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = '43567dd1-db59-40af-928e-03708237eb98'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
-- Venton Jones / same-sex-marriage  (stays 0, RUNG_1_ARGUED_AWAITING_DECISION)
UPDATE inform.politician_context SET reasoning = 'Blanked 2026-10-08 (migration 1906), and the reason RESTATED because the reason migration 1903 gave was wrong. 🔴 CORRECTING MIGRATION 1903, WHICH BLANKED THIS ROW BY MISTAKE. 1903 recorded it as a ladder-scope blank on the ground that the Season 2 rung at this value asks a different question from Season 1''s. THAT TEST WAS APPLIED TO THE WRONG PAIR OF RUNGS. Season 2 INSERTED a new rung 1 on this ladder -- "full legal equality: equal marriage plus protection from discrimination" -- and shifted the others down, remapping Season 1 rung 1 to Season 2 rung 2 (476 rows), Season 1 rung 2 to Season 2 rung 3 (143 rows) and blanking Season 1 rung 3, the federalism rung Season 2 does not contain (28 rows). This row ALREADY HAD a Season 2 answer at its remapped value, so it had been carried correctly long before this audit and no carry question existed for it; comparing Season 1 rung 2 against Season 2 rung 2 compared two different rungs. The chair is restored to where Season 2 already had it. ⚠ THIS ROW IS NOT RESTORED WITH THE OTHERS, because its own record argues a DIFFERENT rung from the one Season 2 holds and a chair move needs a decision, not a repair. THE RECORD: HB 1806 (88R), as coauthor -- bills prohibiting discrimination on the basis of sexual orientation or gender identity. Season 2 rung 1 is the only rung that adds anti-discrimination protection to equal marriage, and this row already sat above the marriage threshold, so its own filings argue rung 1 rather than rung 2. It is left at 0 pending that decision rather than written at a chair its own evidence contradicts. The sources examined are kept below. This is a blank, not a deletion.', sources = ARRAY['https://capitol.texas.gov/BillLookup/History.aspx?LegSess=88R&Bill=HB1806', 'https://en.wikipedia.org/wiki/Venton_Jones']::text[], updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = 'e8058f2b-c68a-474b-b9fe-df4d2d22545b'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;
UPDATE inform.politician_answers SET value = 0, updated_at = now()
 WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND politician_id = 'e8058f2b-c68a-474b-b9fe-df4d2d22545b'::uuid AND topic_id = 'c5ab4eab-702f-49b8-9277-8ea53f3835c6'::uuid;


DO $post$
DECLARE n integer;
BEGIN
  SELECT count(*) INTO n FROM inform.politician_context
   WHERE season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND reasoning LIKE '%(migration 1906)%';
  IF n <> 21 THEN
    RAISE EXCEPTION 'migration 1906: expected 21 rows written, found %', n;
  END IF;
  -- the five awaiting a decision must still be 0, and nothing else written here may be
  SELECT count(*) INTO n FROM inform.politician_context c
    JOIN inform.politician_answers a ON a.politician_id = c.politician_id
     AND a.topic_id = c.topic_id AND a.season_id = c.season_id
   WHERE c.season_id = '86d893a1-c1a2-4bbf-b4e5-69ec43221194' AND c.reasoning LIKE '%(migration 1906)%' AND a.value = 0;
  IF n <> 5 THEN
    RAISE EXCEPTION 'migration 1906: expected exactly 5 rows left at 0, found %', n;
  END IF;
END
$post$;
