-- Migration 239: OR 2026 Legislative Race Scaffold
-- Generated by generate_or_legislative_races.ps1
-- 30 Senate districts + 60 House districts = 90 rows, general election only

DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41001' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 1', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41002' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 2', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41003' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 3', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41004' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 4', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41005' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 5', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41006' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 6', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41007' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 7', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41008' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 8', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41009' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 9', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41010' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 10', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41011' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 11', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41012' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 12', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41013' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 13', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41014' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 14', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41015' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 15', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41016' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 16', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41017' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 17', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41018' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 18', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41019' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 19', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41020' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 20', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41021' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 21', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41022' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 22', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41023' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 23', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41024' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 24', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41025' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 25', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41026' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 26', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41027' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 27', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41028' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 28', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41029' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 29', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41030' AND d.district_type = 'STATE_UPPER' AND d.state = 'or'
       AND ch.name = 'Oregon Senate' LIMIT 1),
    'OR State Senate District 30', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41001' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 1', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41002' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 2', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41003' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 3', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41004' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 4', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41005' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 5', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41006' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 6', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41007' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 7', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41008' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 8', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41009' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 9', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41010' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 10', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41011' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 11', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41012' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 12', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41013' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 13', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41014' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 14', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41015' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 15', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41016' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 16', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41017' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 17', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41018' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 18', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41019' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 19', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41020' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 20', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41021' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 21', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41022' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 22', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41023' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 23', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41024' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 24', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41025' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 25', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41026' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 26', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41027' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 27', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41028' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 28', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41029' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 29', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41030' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 30', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41031' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 31', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41032' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 32', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41033' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 33', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41034' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 34', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41035' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 35', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41036' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 36', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41037' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 37', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41038' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 38', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41039' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 39', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41040' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 40', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41041' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 41', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41042' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 42', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41043' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 43', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41044' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 44', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41045' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 45', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41046' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 46', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41047' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 47', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41048' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 48', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41049' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 49', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41050' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 50', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41051' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 51', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41052' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 52', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41053' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 53', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41054' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 54', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41055' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 55', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41056' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 56', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41057' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 57', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41058' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 58', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41059' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 59', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
DO $$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = 'OR 2026 General' AND state = 'OR';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '41060' AND d.district_type = 'STATE_LOWER' AND d.state = 'or'
       AND ch.name = 'Oregon House of Representatives' LIMIT 1),
    'OR State House District 60', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END $$;
