BEGIN;

-- ============================================================
-- Domenic J. Sarno (d8449201-38b4-4851-b8a7-40b1bcf40161)
-- ============================================================
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', 'eb3d1247-0de1-4b7f-baec-7259861efd53', 4.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', 'eb3d1247-0de1-4b7f-baec-7259861efd53', $$Sarno's administration has attracted over $5 billion in private and public investment including the $800M MGM Springfield casino resort (negotiated $25M/year city payment), Union Station redevelopment, and the Naismith Basketball Hall of Fame expansion. The city actively uses Opportunity Zones, tax incentive programs, storefront grants, and the Housing Development Incentive Program to compete for and retain major employers.$$, ARRAY['https://www.springfield-ma.gov/index.php/mayor','https://www.springfield-ma.gov/planning/','https://en.wikipedia.org/wiki/Domenic_Sarno']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', '669cac97-66a6-4087-b036-936fbe62efb3', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', '669cac97-66a6-4087-b036-936fbe62efb3', $$The Springfield Office of Housing runs affordable homeownership lotteries targeting buyers at up to 100% AMI, down payment assistance, and ARPA-funded home rehab grants. The city coordinates the Springfield-Hampden County Continuum of Care distributing federal funds for permanent supportive housing and rapid rehousing, and seeks nonprofit partners for infill single-family development on city-owned land. This reflects targeted subsidies and assistance rather than publicly-built housing for all or a pure market approach.$$, ARRAY['https://www.springfield-ma.gov/housing/','https://www.springfield-ma.gov/index.php/mayor']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', '6fbf39ae-6b19-4182-b4c2-6a8d25c86c0f', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', '6fbf39ae-6b19-4182-b4c2-6a8d25c86c0f', $$Springfield invests in outreach and shelter through the Continuum of Care and Emergency Solutions Grant, funding street outreach, housing navigation, and emergency solutions. The city's Health and Human Services department provides nursing and dental services for people experiencing homelessness at 769 Worthington Street. The approach combines service investment with quality-of-life enforcement via the Police Ordinance Flex Squad — consistent with investing in outreach and shelter while enforcing reasonable public space rules.$$, ARRAY['https://www.springfield-ma.gov/hhs/','https://www.springfield-ma.gov/housing/','https://www.springfield-ma.gov/index.php/mayor']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', '4938766b-b45a-46e3-93bd-b8b30651271a', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', '4938766b-b45a-46e3-93bd-b8b30651271a', $$Springfield funds shelter and services through the CoC (permanent supportive housing and rapid rehousing) and ESG (street outreach and homelessness prevention), while the Police Ordinance Flex Squad addresses quality-of-life violations. This balanced services-and-enforcement approach aligns with allowing enforcement only when shelter capacity exists while investing in services. No evidence of encampment bans with criminal penalties or of explicit right-to-sleep protections.$$, ARRAY['https://www.springfield-ma.gov/housing/','https://www.springfield-ma.gov/hhs/']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', 'e9ebefcd-c496-45e8-b816-a79f8442ba85', 4.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', 'e9ebefcd-c496-45e8-b816-a79f8442ba85', $$Mayor Sarno fought the Massachusetts Supreme Judicial Court to maintain unilateral control over the Springfield Police Department, opposing the restoration of an independent five-member police commission. His administration expanded the Crime Analysis Division, deployed body-worn cameras, runs a Police Ordinance Flex Squad, and maintains the Counter Criminal Continuum policing program. The DOJ entered a consent decree with Springfield over police practices, indicating an administration that prioritized policing capacity over reform.$$, ARRAY['https://www.springfield-ma.gov/index.php/mayor','https://www.springfield-ma.gov/police/','https://commonwealthbeacon.org/?s=springfield+sarno+police']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', 'b9ccee94-ad96-4f10-b655-889d8e5abe92', 4.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', 'b9ccee94-ad96-4f10-b655-889d8e5abe92', $$Wikipedia documents that Sarno faced criticism from activists and Massachusetts Democrats for his stances against illegal immigration and that he sought to punish a church offering sanctuary to an undocumented immigrant. He has explicitly rejected sanctuary city designation for Springfield. This indicates a posture of honoring federal immigration detainers and sharing information proactively rather than limiting city cooperation with ICE.$$, ARRAY['https://en.wikipedia.org/wiki/Domenic_Sarno']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', 'ba59337e-30e2-4aba-a39a-426b3366eb27', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', 'ba59337e-30e2-4aba-a39a-426b3366eb27', $$DPW page shows Sarno's administration focuses on road paving and maintenance (annual paving programs 2015-2024), traffic signal maintenance, and street improvement projects including the Safe Streets and Roads for All initiative. A WAMC report noted Sarno sought to end free PVTA bus service citing youth disturbances at Union Station — signaling skepticism toward transit subsidies. Road maintenance is the dominant focus with selective pedestrian improvements.$$, ARRAY['https://www.springfield-ma.gov/dpw/','https://www.wamc.org/new-england-news']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', '7687de4f-4d0b-462a-b803-bdfb23b16b42', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', '7687de4f-4d0b-462a-b803-bdfb23b16b42', $$DPW manages systematic paving programs, single-stream recycling, bulk pickup, and 311-based issue reporting. The administration's messaging emphasizes resident and property-owner responsibility for contamination prevention and catch basin maintenance while maintaining regular municipal collection services. This reflects maintenance of current services with enforcement of anti-dumping rules rather than significant expansion or privatization.$$, ARRAY['https://www.springfield-ma.gov/dpw/']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', '1935979c-b290-42e4-baa5-8cb0138b4ffa', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', '1935979c-b290-42e4-baa5-8cb0138b4ffa', $$Springfield's Office of Planning and Economic Development incorporates smart growth principles, Conservation Commission oversight of wetlands, open space land preservation, and brownfields redevelopment. The city balances development attraction (Opportunity Zones, business incentives) with environmental review requirements. The Conservation Commission implements the Massachusetts Wetlands Protection Act with a mission of sustainable development and redevelopment, reflecting consistent environmental standards with developer flexibility.$$, ARRAY['https://www.springfield-ma.gov/planning/','https://www.springfield-ma.gov/cos/conservation']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', 'f1e44d66-5d27-4b51-b54f-b7ace86f6a3c', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', 'f1e44d66-5d27-4b51-b54f-b7ace86f6a3c', $$Mayor Sarno's administration reduced city energy consumption by 26% over a decade saving $3.5 million annually, earned Green Community designation from Massachusetts, and has maintained Tree City USA status for 38 consecutive years. These are incremental clean-energy and efficiency investments — not a rapid fossil-fuel phaseout or emergency climate declaration, but also not a rejection of climate initiatives.$$, ARRAY['https://www.springfield-ma.gov/index.php/mayor']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', '0bc588c6-39e1-4084-b5de-cac909b8b762', 2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', '0bc588c6-39e1-4084-b5de-cac909b8b762', $$Sarno appointed the first Black Police Superintendent and first Black City Clerk of Latino descent in Springfield's history, created a chief diversity and inclusion officer position, directed 88% of $123M in ARPA relief to minority- and women-owned businesses, and supported the inaugural Springfield Pride Parade. These actions reflect active steps to address systemic inequities, aligning with strengthening civil rights enforcement and addressing systemic discrimination.$$, ARRAY['https://www.springfield-ma.gov/index.php/mayor']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', 'fb25c1ac-91cc-49bf-8afc-c7fa22ef45e4', 4.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', 'fb25c1ac-91cc-49bf-8afc-c7fa22ef45e4', $$The Office of Planning and Economic Development's stated mission is to create a climate in Springfield that is conducive to growing and attracting businesses. The administration has pursued multiple master plans (Northeast Downtown 2021, Main Street/Convention District 2021, Downtown Housing Study 2023, Food Hall Feasibility 2026), streamlined business attraction through Opportunity Zones and incentive programs, and completed $5 billion in private/public investment under Sarno — active recruitment of development rather than growth management.$$, ARRAY['https://www.springfield-ma.gov/planning/','https://www.springfield-ma.gov/index.php/mayor']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', 'd4f18138-a2e0-4110-b925-7387d9d0d16d', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d8449201-38b4-4851-b8a7-40b1bcf40161', 'd4f18138-a2e0-4110-b925-7387d9d0d16d', $$Springfield's OPED manages zoning ordinances and focuses downtown-corridor planning (Northeast Downtown Master Plan, Main Street/Convention District) while the 2023 Downtown Market Rate Housing Study examines new residential development potential in targeted areas. Infill development focuses on former school buildings converted to affordable senior housing and city-owned vacant lots — multifamily and mixed-use allowed near commercial corridors while most residential zones are maintained.$$, ARRAY['https://www.springfield-ma.gov/planning/','https://www.springfield-ma.gov/housing/']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

-- ============================================================
-- Justin Hurst (91e24565-79b3-4473-9d7b-3ca72beceed2)
-- ============================================================
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('91e24565-79b3-4473-9d7b-3ca72beceed2', 'ba59337e-30e2-4aba-a39a-426b3366eb27', 2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('91e24565-79b3-4473-9d7b-3ca72beceed2', 'ba59337e-30e2-4aba-a39a-426b3366eb27', $$In April 2022 Hurst co-led a proposal to make three PVTA bus lines (B7, G2, B6) fare-free for two years using $3.4M in ARPA funds. He explicitly championed the initiative stating the cost was worth it given the number of people it would impact. His 2022 mayoral announcement also proposed free public transportation as an ARPA-funded city priority, noting some residents spend a third of income on transit. This is equal investment in multimodal and transit options funded at public expense.$$, ARRAY['https://www.wamc.org/news/2022-04-01/five-springfield-city-councilors-float-a-fare-free-bus-proposal','https://www.wamc.org/news/2022-11-30/springfield-city-councilor-justin-hurst-announces-run-for-mayor']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('91e24565-79b3-4473-9d7b-3ca72beceed2', 'eb3d1247-0de1-4b7f-baec-7259861efd53', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('91e24565-79b3-4473-9d7b-3ca72beceed2', 'eb3d1247-0de1-4b7f-baec-7259861efd53', $$Hurst voted against the $6.5M city subsidy for Court Square Hotel calling it a money grab for millionaires and championed a 30-day advance-notice requirement before councilors vote on economic development spending. His mayoral platform prioritized investment in small businesses and micro-enterprises over large corporate subsidies while his 2026 HoopHall resolution pressed for a sports complex to anchor downtown growth. This reflects targeted incentives with community-benefit accountability.$$, ARRAY['https://www.wamc.org/news/2022-04-20/springfield-city-councilors-want-advance-briefings-on-economic-development-projects','https://www.wamc.org/news/2022-11-30/springfield-city-councilor-justin-hurst-announces-run-for-mayor','https://www.wamc.org/news/2026-03-04/springfield-city-council-calls-for-hoophall-classic-to-stay']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('91e24565-79b3-4473-9d7b-3ca72beceed2', 'e9ebefcd-c496-45e8-b816-a79f8442ba85', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('91e24565-79b3-4473-9d7b-3ca72beceed2', 'e9ebefcd-c496-45e8-b816-a79f8442ba85', $$Hurst's 2023 mayoral campaign included a comprehensive plan covering hiring additional police officers AND strengthening community-law enforcement relationships AND examining root causes of gun violence. His early council statements emphasized investing in young people through education and internships as a crime solution. He is not a defund advocate but pairs police hiring with social investment — aligning with keeping current public safety funding while adding community and crisis-response elements.$$, ARRAY['https://www.wamc.org/news/2023-11-03/in-the-springfield-mayoral-election-the-longtime-incumbent-faces-a-challenger-who-says-change-is-long-overdue','https://www.wamc.org/news/2022-11-30/springfield-city-councilor-justin-hurst-announces-run-for-mayor']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('91e24565-79b3-4473-9d7b-3ca72beceed2', '669cac97-66a6-4087-b036-936fbe62efb3', 2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('91e24565-79b3-4473-9d7b-3ca72beceed2', '669cac97-66a6-4087-b036-936fbe62efb3', $$Hurst acknowledged a Springfield housing crisis in his 2022 mayoral announcement stating rents are absolutely skyrocketing and committed to a comprehensive plan addressing both housing supply and affordability. His 2023 campaign criticized property tax increases eight of the last ten years and a 28% water-rate jump hitting struggling residents. These positions reflect a commitment beyond targeted subsidies toward rent-pressure relief and affordability investment.$$, ARRAY['https://www.wamc.org/news/2022-11-30/springfield-city-councilor-justin-hurst-announces-run-for-mayor','https://www.wamc.org/news/2023-11-03/in-the-springfield-mayoral-election-the-longtime-incumbent-faces-a-challenger-who-says-change-is-long-overdue']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('91e24565-79b3-4473-9d7b-3ca72beceed2', '0bc588c6-39e1-4084-b5de-cac909b8b762', 2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('91e24565-79b3-4473-9d7b-3ca72beceed2', '0bc588c6-39e1-4084-b5de-cac909b8b762', $$Hurst ran his 2022-2023 mayoral campaign on pillars of transparency, accountability, and social and economic justice. He would have been Springfield's first Black mayor — a majority-minority city — and has served on the city council since 2014 advocating for residents who are struggling. His platform language and career arc reflect strengthening civil rights enforcement and addressing systemic discrimination.$$, ARRAY['https://www.wamc.org/news/2022-11-30/springfield-city-councilor-justin-hurst-announces-run-for-mayor','https://www.wamc.org/news/2023-11-03/in-the-springfield-mayoral-election-the-longtime-incumbent-faces-a-challenger-who-says-change-is-long-overdue','https://www.springfield-ma.gov/cos/council/city-council-sub-committees']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('91e24565-79b3-4473-9d7b-3ca72beceed2', '7687de4f-4d0b-462a-b803-bdfb23b16b42', 2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('91e24565-79b3-4473-9d7b-3ca72beceed2', '7687de4f-4d0b-462a-b803-bdfb23b16b42', $$In his January 2026 return-to-council priorities Hurst explicitly called out clean streets and clean parks as minimum expectations: We've got to get the little things right here in the city if taxes are going to keep going up and up and up — we need to make sure, at the very least, that folks are going to get the services that they rightfully deserve. He framed poor conditions as a service-delivery failure, reflecting a services-first investment approach.$$, ARRAY['https://www.wamc.org/news/2026-01-13/coming-going-incoming-springfield-city-councilors-talk-priorities-outgoing-councilors-reflect-on-work']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('91e24565-79b3-4473-9d7b-3ca72beceed2', '1935979c-b290-42e4-baa5-8cb0138b4ffa', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('91e24565-79b3-4473-9d7b-3ca72beceed2', '1935979c-b290-42e4-baa5-8cb0138b4ffa', $$Hurst co-sponsored the fare-free bus proposal whose supporters cited environmental and road-safety benefits. He serves on the Planning and Economic Development committee and is focused on downtown growth including a new sports complex. He is not documented as opposing development on environmental grounds nor as seeking strict preservation rules. His record reflects consistent environmental standards applied while giving developers flexibility.$$, ARRAY['https://www.wamc.org/news/2022-04-01/five-springfield-city-councilors-float-a-fare-free-bus-proposal','https://www.springfield-ma.gov/cos/council/city-council-sub-committees']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('91e24565-79b3-4473-9d7b-3ca72beceed2', 'fb25c1ac-91cc-49bf-8afc-c7fa22ef45e4', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('91e24565-79b3-4473-9d7b-3ca72beceed2', 'fb25c1ac-91cc-49bf-8afc-c7fa22ef45e4', $$Hurst demanded a 30-day advance-notice rule before council votes on development spending and opposed the rushed $6.5M Court Square subsidy. Yet he actively supports growth — his 2026 HoopHall resolution called on the mayor to accelerate plans for a sports complex, stating we need to stop doing so much planning and start doing more acting. This is proactive infrastructure investment ahead of growth rather than growth limits or barrier removal.$$, ARRAY['https://www.wamc.org/news/2022-04-20/springfield-city-councilors-want-advance-briefings-on-economic-development-projects','https://www.wamc.org/news/2026-03-04/springfield-city-council-calls-for-hoophall-classic-to-stay']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

-- ============================================================
-- Michael A. Fenton (fc17d6ea-c967-4d0d-a636-41b1d136765f)
-- ============================================================
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('fc17d6ea-c967-4d0d-a636-41b1d136765f', 'e9ebefcd-c496-45e8-b816-a79f8442ba85', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('fc17d6ea-c967-4d0d-a636-41b1d136765f', 'e9ebefcd-c496-45e8-b816-a79f8442ba85', $$Fenton authored and championed a civilian Board of Police Commissioners in 2016 to address documented misconduct, securing a 10-2 council vote and then a 9-3 veto override. However, in 2021 he was one of only three dissenters on a 9-3 vote to ban facial recognition technology, suggesting he supports police accountability without reducing police capacity or surveillance tools. This combination — structural reform plus opposition to surveillance limits — aligns with maintaining current public safety funding while adding accountability mechanisms.$$, ARRAY['https://www.wamc.org/new-england-news/2016-12-06/city-council-votes-to-put-civilian-board-in-charge-of-springfield-police-department','https://www.wamc.org/new-england-news/2016-12-20/court-fight-likely-between-springfield-mayor-and-city-council','https://www.wamc.org/post/springfield-city-council-votes-ban-facial-recognition-technology']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('fc17d6ea-c967-4d0d-a636-41b1d136765f', '1935979c-b290-42e4-baa5-8cb0138b4ffa', 2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('fc17d6ea-c967-4d0d-a636-41b1d136765f', '1935979c-b290-42e4-baa5-8cb0138b4ffa', $$In July 2024 Fenton championed the expansion of Abbey Brook Conservation Area using $500,000 in Community Preservation Act funds and $134,000 in city budget funds, creating the largest contiguous conservation parcel in the city at roughly 80 acres. He explicitly stated that prior plans for a gas station or strip mall on the land would have been a tragic outcome. He sits on the Sustainability & Environment committee and has repeatedly supported CPA funding for environmental preservation.$$, ARRAY['https://www.wamc.org/news/2024-07-24/springfield-looking-to-add-five-acres-to-abbey-brook-conservation-area','https://www.springfield-ma.gov/cos/council/city-council-sub-committees']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('fc17d6ea-c967-4d0d-a636-41b1d136765f', 'eb3d1247-0de1-4b7f-baec-7259861efd53', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('fc17d6ea-c967-4d0d-a636-41b1d136765f', 'eb3d1247-0de1-4b7f-baec-7259861efd53', $$Fenton chairs the Casino Oversight Committee and monitors MGM Springfield's job-creation obligations while holding the company accountable to its 3,000-job commitment. He also championed Community Preservation Act adoption and confronted Eversource over $44 million in withheld property taxes. This pattern reflects targeted incentives with accountability for major employers rather than blanket corporate subsidies or no-incentives posture.$$, ARRAY['https://www.wamc.org/news/2023-01-20/three-thousand-jobs-once-promised-at-mgm-springfield-is-no-longer-realistic-concedes-top-casino-official','https://www.wamc.org/new-england-news/2016-07-25/community-preservation-act-on-ballots-in-three-massachusetts-cities','https://www.wamc.org/news/2021-10-20/legislator-will-try-to-close-loophole-that-allows-utility-company-to-avoid-paying-property-taxes-in-full']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

-- ============================================================
-- Lavar Click-Bruce (b0df471c-db3a-4f10-8817-f14c7e611593)
-- ============================================================
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('b0df471c-db3a-4f10-8817-f14c7e611593', 'e9ebefcd-c496-45e8-b816-a79f8442ba85', 4.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('b0df471c-db3a-4f10-8817-f14c7e611593', 'e9ebefcd-c496-45e8-b816-a79f8442ba85', $$After winning his 2022 special election, Click-Bruce explicitly campaigned on expanding the C3 policing program to areas of Ward 5 and installing gunshot detection (ShotSpotter) technology in Pine Point. In February 2023 he chaired a hearing on safe exchange sites and advocated for additional surveillance infrastructure. In April 2025 he raised non-functioning streetlights as a public safety hazard and linked them to rising shootings. All actions add police capacity and technology, not divert resources to social services.$$, ARRAY['https://www.wamc.org/news/2022-09-14/lavar-click-bruce-wins-special-election-for-ward-5-springfield-city-council','https://www.wamc.org/news/2023-02-15/springfield-city-councilor-seeks-options-for-safe-pick-up-sites-for-online-purchases','https://www.wamc.org/news/2025-04-12/springfield-city-council-questions-commission-re-appointments-oks-utility-bill-pricing-resolution']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('b0df471c-db3a-4f10-8817-f14c7e611593', 'eb3d1247-0de1-4b7f-baec-7259861efd53', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('b0df471c-db3a-4f10-8817-f14c7e611593', 'eb3d1247-0de1-4b7f-baec-7259861efd53', $$In August 2024 Click-Bruce led a resolution calling on the Healey administration to reopen the SNAP Restaurant Meals Program to additional Springfield restaurants and food trucks, citing both food access and local economic stimulation. The resolution passed unanimously. This reflects targeted program advocacy for small local businesses with a community benefit (food access), not large employer subsidies or a pure market approach.$$, ARRAY['https://www.wamc.org/news/2024-08-20/springfield-city-council-seeks-expansion-of-pilot-program-allowing-snap-benefits-to-be-used-at-restaurants-food-trucks']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('b0df471c-db3a-4f10-8817-f14c7e611593', '7687de4f-4d0b-462a-b803-bdfb23b16b42', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('b0df471c-db3a-4f10-8817-f14c7e611593', '7687de4f-4d0b-462a-b803-bdfb23b16b42', $$In April 2025 Click-Bruce raised concern about 15-30 non-functioning streetlights maintained by Eversource in Ward 5, arguing the city should not pay for non-operational lights. He also championed Resolution 8524 (April 2025) calling for a DPU investigation into utility rate increases harming residents. Both actions reflect maintaining and enforcing city service standards rather than expanding or contracting sanitation investment.$$, ARRAY['https://www.wamc.org/news/2025-04-12/springfield-city-council-questions-commission-re-appointments-oks-utility-bill-pricing-resolution']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

-- ============================================================
-- Gerry Martin (de39ab94-3663-4b2e-be14-222e79a87638)
-- ============================================================
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('de39ab94-3663-4b2e-be14-222e79a87638', 'e9ebefcd-c496-45e8-b816-a79f8442ba85', 4.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('de39ab94-3663-4b2e-be14-222e79a87638', 'e9ebefcd-c496-45e8-b816-a79f8442ba85', $$Martin campaigned explicitly on obtaining a police substation and expanding walking patrols in Ward 7, and stated in January 2026 that public safety will always be his top priority. He was assigned chair of the Public Safety subcommittee. These actions reflect a stance of increasing police presence and capacity, not redirecting funds to social services.$$, ARRAY['https://www.wamc.org/news/2026-01-13/coming-going-incoming-springfield-city-councilors-talk-priorities-outgoing-councilors-reflect-on-work','https://www.springfield-ma.gov/cos/council/city-council-sub-committees']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

-- ============================================================
-- Zaida Govan (1b987aa5-fba6-4ce5-a926-8cb957b43410)
-- ============================================================
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('1b987aa5-fba6-4ce5-a926-8cb957b43410', '669cac97-66a6-4087-b036-936fbe62efb3', 2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('1b987aa5-fba6-4ce5-a926-8cb957b43410', '669cac97-66a6-4087-b036-936fbe62efb3', $$Govan voted in favor of the Springfield housing trust fund in March 2022 and stated it was essential for young residents who don't have affordable housing to move into. In December 2022 on the Parsons Block development she challenged the $2,000/month rents as inaccessible for teachers and police officers. Both actions show she supports requiring or funding affordable units and opposing market-rate-only development.$$, ARRAY['https://www.wamc.org/news/2022-03-28/springfield-city-council-approves-housing-trust-fund','https://www.wamc.org/news/2022-12-21/springfield-city-council-okays-development-of-historic-property']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('1b987aa5-fba6-4ce5-a926-8cb957b43410', 'e9ebefcd-c496-45e8-b816-a79f8442ba85', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('1b987aa5-fba6-4ce5-a926-8cb957b43410', 'e9ebefcd-c496-45e8-b816-a79f8442ba85', $$In February 2022 Govan created and chaired a new ad-hoc City Council Mental Health Committee, launching free community mental health checkup days and a report on mental health services. She explicitly framed the initiative as preventing tragedies through accessible preventive care, not through police action. Her approach adds community-based mental health services alongside existing policing — keeping current public safety funding while adding crisis response and mental health resources.$$, ARRAY['https://www.wamc.org/news/2022-02-22/springfield-city-council-president-creates-new-committee-on-mental-health','https://www.wamc.org/news/2022-07-01/free-mental-health-checkups-being-offered-in-springfield-this-summer','https://www.wamc.org/news/2023-03-01/springfield-city-council-committee-on-mental-health-issues-report']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('1b987aa5-fba6-4ce5-a926-8cb957b43410', '1935979c-b290-42e4-baa5-8cb0138b4ffa', 2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('1b987aa5-fba6-4ce5-a926-8cb957b43410', '1935979c-b290-42e4-baa5-8cb0138b4ffa', $$In July 2022 Govan voted with the Springfield City Council to urge rejection of the Eversource natural gas pipeline project from Longmeadow to Springfield. She stated the city and state need to start doing things to reach that goal and not putting in new pipelines, explicitly linking the vote to reducing fossil fuel dependence. This reflects a posture of strictly protecting the environment and opposing new infrastructure that increases environmental harm.$$, ARRAY['https://www.wamc.org/news/2022-07-27/springfield-city-council-urges-rejection-of-eversource-pipeline-project','https://www.springfield-ma.gov/cos/council/city-council-sub-committees']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

-- ============================================================
-- Kateri Walsh (6db2abd4-86ce-414a-ba80-6565e6e3b23d)
-- ============================================================
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('6db2abd4-86ce-414a-ba80-6565e6e3b23d', 'ba59337e-30e2-4aba-a39a-426b3366eb27', 2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('6db2abd4-86ce-414a-ba80-6565e6e3b23d', 'ba59337e-30e2-4aba-a39a-426b3366eb27', $$In April 2022 Walsh co-sponsored the Fare-Free Bus Riding Initiative alongside four colleagues, calling for a two-year pilot making Springfield's three highest-ridership PVTA bus lines free using ARPA funds. She directly invoked peer cities (Boston, Worcester, Lawrence) with active fare-free pilots and framed Springfield as needing to lead on multimodal transit investment, clearly prioritizing transit access over road capacity or parking.$$, ARRAY['https://www.wamc.org/news/2022-04-01/five-springfield-city-councilors-float-a-fare-free-bus-proposal']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

-- ============================================================
-- Tracye Whitfield (8f7f44a0-2580-4e32-97a1-e8341c6b155f)
-- ============================================================
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('8f7f44a0-2580-4e32-97a1-e8341c6b155f', 'ba59337e-30e2-4aba-a39a-426b3366eb27', 2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('8f7f44a0-2580-4e32-97a1-e8341c6b155f', 'ba59337e-30e2-4aba-a39a-426b3366eb27', $$In April 2022 Whitfield co-sponsored the Fare-Free Bus Riding Initiative with four colleagues, and as Finance Committee chair she announced she would schedule a public hearing for the proposal. She championed the initiative by highlighting a single mother spending roughly $300/month on transit for herself and two children, framing fare elimination as real household savings. Co-sponsoring a multimodal transit investment proposal and fast-tracking it through her committee reflects equal investment in roads and transit options.$$, ARRAY['https://www.wamc.org/news/2022-04-01/five-springfield-city-councilors-float-a-fare-free-bus-proposal']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('8f7f44a0-2580-4e32-97a1-e8341c6b155f', 'eb3d1247-0de1-4b7f-baec-7259861efd53', 3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('8f7f44a0-2580-4e32-97a1-e8341c6b155f', 'eb3d1247-0de1-4b7f-baec-7259861efd53', $$As incoming Council President in January 2026 Whitfield announced the creation of a Revenue and Economic Growth special committee and a Residential Developments committee, emphasizing local business inclusion in city projects and cutting corners to avoid property tax increases. She stated priorities as budget accountability and community economic development rather than competing for large employers with tax abatements — targeted incentives with community benefit requirements.$$, ARRAY['https://www.wamc.org/news/2026-01-07/new-springfield-city-council-prez-vice-prez-talk-priorities-heading-into-new-term','https://www.wamc.org/news/2025-12-18/at-informal-caucus-springfield-city-council-picks-whitfield-to-serve-as-next-years-council-president']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('8f7f44a0-2580-4e32-97a1-e8341c6b155f', 'e9ebefcd-c496-45e8-b816-a79f8442ba85', 4.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('8f7f44a0-2580-4e32-97a1-e8341c6b155f', 'e9ebefcd-c496-45e8-b816-a79f8442ba85', $$In January 2026 as newly-elected Council President Whitfield highlighted that Police Superintendent Larry Akers achieved a drop in homicides from 31 to 17 in 2024 and record seizure of at least 164 illegal firearms in 2025. She framed these enforcement outcomes as a positive story for the city and listed public safety alongside economic growth as a top priority. Celebrating record gun seizures and homicide reduction driven by police action — without pairing with co-responder or budget-reallocation proposals — aligns with increasing police effectiveness.$$, ARRAY['https://www.wamc.org/news/2026-01-07/new-springfield-city-council-prez-vice-prez-talk-priorities-heading-into-new-term']::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
