-- Migration 741: Rodney G. Tanaka (Gardena Council) Stances
-- Phase 132 — Gardena. Rodney G. Tanaka, external_id -700502, UUID 21d23e8d-fedc-4485-beca-b7ef5e5a23b7.
-- Mayor Pro Tem; retired Gardena PD Lieutenant (31 yrs).
BEGIN;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('21d23e8d-fedc-4485-beca-b7ef5e5a23b7','e9ebefcd-c496-45e8-b816-a79f8442ba85',4.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('21d23e8d-fedc-4485-beca-b7ef5e5a23b7','e9ebefcd-c496-45e8-b816-a79f8442ba85',$$A retired Gardena Police Department lieutenant of 31 years, Council Member Tanaka pledges to keep police and fire personnel "the best in the South Bay" with quick response times so the community is as safe as possible, a strongly enforcement-supportive public-safety stance.$$,ARRAY['https://rodneytanakaforcitycouncil.com/']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('21d23e8d-fedc-4485-beca-b7ef5e5a23b7','d4f18138-a2e0-4110-b925-7387d9d0d16d',4.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('21d23e8d-fedc-4485-beca-b7ef5e5a23b7','d4f18138-a2e0-4110-b925-7387d9d0d16d',$$Tanaka insists housing and land-use decisions keep local control a priority, arguing "Sacramento cannot be allowed to tell the city how to run itself," a position resisting state upzoning mandates in favor of local zoning preservation.$$,ARRAY['https://rodneytanakaforcitycouncil.com/']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('21d23e8d-fedc-4485-beca-b7ef5e5a23b7','eb3d1247-0de1-4b7f-baec-7259861efd53',2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('21d23e8d-fedc-4485-beca-b7ef5e5a23b7','eb3d1247-0de1-4b7f-baec-7259861efd53',$$Tanaka lists economic development among his core priorities, supporting business growth and enhanced city services in Gardena.$$,ARRAY['https://gardenavalleynews.org/city-council-incumbent-tanaka-eyes-third-term/']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
COMMIT;
