-- Migration 747: Angie Reyes English (Hawthorne Council) Stances
-- Phase 133 — Hawthorne. Angie Reyes English, external_id -700353, UUID be3ca929-4fe1-4797-acf2-570ba8fcebbf.
BEGIN;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('be3ca929-4fe1-4797-acf2-570ba8fcebbf','6fbf39ae-6b19-4182-b4c2-6a8d25c86c0f',2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('be3ca929-4fe1-4797-acf2-570ba8fcebbf','6fbf39ae-6b19-4182-b4c2-6a8d25c86c0f',$$Council Member Reyes English has made housing and homelessness a core priority since 2009 and, collaborating with agencies, helped reduce Hawthorne's unhoused population from 277 to 152 in 2023 — a services-and-housing approach.$$,ARRAY['https://www.angie4hawthorne.com/']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('be3ca929-4fe1-4797-acf2-570ba8fcebbf','669cac97-66a6-4087-b036-936fbe62efb3',2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('be3ca929-4fe1-4797-acf2-570ba8fcebbf','669cac97-66a6-4087-b036-936fbe62efb3',$$Reyes English supports housing production including mixed-use development and job creation as council priorities.$$,ARRAY['https://www.angie4hawthorne.com/']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('be3ca929-4fe1-4797-acf2-570ba8fcebbf','eb3d1247-0de1-4b7f-baec-7259861efd53',2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('be3ca929-4fe1-4797-acf2-570ba8fcebbf','eb3d1247-0de1-4b7f-baec-7259861efd53',$$Reyes English prioritizes economic development — assisting current businesses and offering incentives to bring new businesses and quality local jobs to Hawthorne.$$,ARRAY['https://www.angie4hawthorne.com/']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('be3ca929-4fe1-4797-acf2-570ba8fcebbf','e9ebefcd-c496-45e8-b816-a79f8442ba85',4.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('be3ca929-4fe1-4797-acf2-570ba8fcebbf','e9ebefcd-c496-45e8-b816-a79f8442ba85',$$Reyes English emphasizes that public safety is critical and works closely with police, code enforcement, and building & safety departments to strengthen neighborhood safety — an enforcement-supportive posture.$$,ARRAY['https://www.cityofhawthorne.org/government/elected-officials/council-member-angie-reyes-english']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
COMMIT;
