-- Migration 749: Phil Brock (Santa Monica Council) Stances
-- Phase 134 — Santa Monica. Phil Brock, external_id -201400, UUID 7714b7c6-9283-4ab8-802e-cbcfba5ddc96. Rotational mayor.
BEGIN;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('7714b7c6-9283-4ab8-802e-cbcfba5ddc96','e9ebefcd-c496-45e8-b816-a79f8442ba85',4.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('7714b7c6-9283-4ab8-802e-cbcfba5ddc96','e9ebefcd-c496-45e8-b816-a79f8442ba85',$$Council Member Brock has consistently supported increasing police resources in response to rising crime and called for private security in the Third Street Promenade area, an enforcement-supportive public-safety posture.$$,ARRAY['https://patch.com/california/santamonica/candidate-profile-phil-brock-santa-monica-city-council']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('7714b7c6-9283-4ab8-802e-cbcfba5ddc96','6fbf39ae-6b19-4182-b4c2-6a8d25c86c0f',3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('7714b7c6-9283-4ab8-802e-cbcfba5ddc96','6fbf39ae-6b19-4182-b4c2-6a8d25c86c0f',$$Brock initiated a homelessness emergency declaration and served on the US Conference of Mayors Homelessness Task Force, describing an approach that balances law enforcement with compassionate solutions.$$,ARRAY['https://patch.com/california/santamonica/candidate-profile-phil-brock-santa-monica-city-council']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('7714b7c6-9283-4ab8-802e-cbcfba5ddc96','fb25c1ac-91cc-49bf-8afc-c7fa22ef45e4',4.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('7714b7c6-9283-4ab8-802e-cbcfba5ddc96','fb25c1ac-91cc-49bf-8afc-c7fa22ef45e4',$$Brock supports slow growth and reduced traffic, expressing concern that big developers and the State want to replace the heart of the city with tall, dense buildings.$$,ARRAY['https://www.votebrock.org/issues/a-statement-of-purpose']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('7714b7c6-9283-4ab8-802e-cbcfba5ddc96','c308e8e8-caac-44f5-ab04-dbfecf40bbe2',2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('7714b7c6-9283-4ab8-802e-cbcfba5ddc96','c308e8e8-caac-44f5-ab04-dbfecf40bbe2',$$Brock has championed rent control as part of his platform, supporting tenant-protective rent regulation.$$,ARRAY['https://patch.com/california/santamonica/candidate-profile-phil-brock-santa-monica-city-council']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
COMMIT;
