-- Migration 754: Jesse Zwick (Santa Monica Council) Stances
-- Phase 134 — Santa Monica. Jesse Zwick, external_id -201405, UUID d970169d-cecc-4cb0-979b-785fecc47ed6. Rotational mayor.
BEGIN;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d970169d-cecc-4cb0-979b-785fecc47ed6','669cac97-66a6-4087-b036-936fbe62efb3',1.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d970169d-cecc-4cb0-979b-785fecc47ed6','669cac97-66a6-4087-b036-936fbe62efb3',$$Council Member Zwick is a pro-housing leader (Abundant Housing-endorsed) advocating a rezoning that legalizes "missing middle" housing, meets RHNA obligations, and affirmatively furthers fair housing, alongside more supportive, affordable, and market-rate housing.$$,ARRAY['https://abundanthousingla.org/abundant-housing-la-endorses-jesse-zwick-for-santa-monica-city-council/']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d970169d-cecc-4cb0-979b-785fecc47ed6','d4f18138-a2e0-4110-b925-7387d9d0d16d',1.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d970169d-cecc-4cb0-979b-785fecc47ed6','d4f18138-a2e0-4110-b925-7387d9d0d16d',$$Zwick argues progressives "cannot solve segregation, homelessness, and climate crises until we get serious about ending exclusionary zoning," and advocates repurposing commercial corridors for greater residential use — a strongly pro-density, anti-exclusionary-zoning stance.$$,ARRAY['https://smdp.com/2022/10/04/council-candidate-jesse-zwick/']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d970169d-cecc-4cb0-979b-785fecc47ed6','6fbf39ae-6b19-4182-b4c2-6a8d25c86c0f',2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d970169d-cecc-4cb0-979b-785fecc47ed6','6fbf39ae-6b19-4182-b4c2-6a8d25c86c0f',$$Zwick campaigned on the principle that "housing solves homelessness," arguing that until housing-market dysfunction is addressed, homeless-services spending alone will not solve the crisis — a housing-first orientation.$$,ARRAY['https://www.planningreport.com/2023/09/06/santa-monica-councilmember-jesse-zwick-homelessness-civic-engagement-land-use-priorities']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d970169d-cecc-4cb0-979b-785fecc47ed6','c308e8e8-caac-44f5-ab04-dbfecf40bbe2',2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d970169d-cecc-4cb0-979b-785fecc47ed6','c308e8e8-caac-44f5-ab04-dbfecf40bbe2',$$Zwick advocates renter protections, holding that renters are due the same housing stability afforded homeowners and that rent control balances that against landlords' fair return.$$,ARRAY['https://smdp.com/2022/10/04/council-candidate-jesse-zwick/']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d970169d-cecc-4cb0-979b-785fecc47ed6','ba59337e-30e2-4aba-a39a-426b3366eb27',1.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d970169d-cecc-4cb0-979b-785fecc47ed6','ba59337e-30e2-4aba-a39a-426b3366eb27',$$Zwick promotes "15-minute cities" where residents meet daily needs without a car, prioritizing residential density along corridors to combat vehicular traffic and air pollution — a strongly multimodal transportation stance.$$,ARRAY['https://smdp.com/2022/10/04/council-candidate-jesse-zwick/']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('d970169d-cecc-4cb0-979b-785fecc47ed6','f1e44d66-5d27-4b51-b54f-b7ace86f6a3c',2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('d970169d-cecc-4cb0-979b-785fecc47ed6','f1e44d66-5d27-4b51-b54f-b7ace86f6a3c',$$Zwick frames ending exclusionary zoning and reducing car dependence as essential to addressing the climate crisis, tying land use directly to climate goals.$$,ARRAY['https://smdp.com/2022/10/04/council-candidate-jesse-zwick/']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
COMMIT;
