-- Migration 764: John Heilman (West Hollywood Council) Stances
-- Phase 136 — West Hollywood. John Heilman, external_id -700600, UUID ea0b6144-fea3-47a1-878b-8cee956a4c79. Rotational mayor.
BEGIN;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('ea0b6144-fea3-47a1-878b-8cee956a4c79','c308e8e8-caac-44f5-ab04-dbfecf40bbe2',1.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('ea0b6144-fea3-47a1-878b-8cee956a4c79','c308e8e8-caac-44f5-ab04-dbfecf40bbe2',$$A founding 1984 council member, Heilman was an architect of West Hollywood's strong rent-control ordinance — a founding priority of the renter-majority city — and remains a leading rent-control advocate.$$,ARRAY['https://johnheilman.com/issues']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('ea0b6144-fea3-47a1-878b-8cee956a4c79','669cac97-66a6-4087-b036-936fbe62efb3',1.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('ea0b6144-fea3-47a1-878b-8cee956a4c79','669cac97-66a6-4087-b036-936fbe62efb3',$$Heilman created the city's inclusionary housing policy requiring developers to include low- and moderate-income units, and founded the City-funded West Hollywood Community Housing Corporation that develops affordable housing — a strongly pro-affordable-housing record.$$,ARRAY['https://johnheilman.com/biography']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('ea0b6144-fea3-47a1-878b-8cee956a4c79','0bc588c6-39e1-4084-b5de-cac909b8b762',1.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('ea0b6144-fea3-47a1-878b-8cee956a4c79','0bc588c6-39e1-4084-b5de-cac909b8b762',$$Heilman drafted West Hollywood's landmark ordinances prohibiting discrimination based on sexual orientation and on HIV/AIDS status and has architected decades of LGBTQ+ civil-rights policy, receiving the US Conference of Mayors' award for AIDS leadership.$$,ARRAY['https://johnheilman.com/biography']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
COMMIT;
