-- Migration 766: Chelsea Byers (West Hollywood Council) Stances
-- Phase 136 — West Hollywood. Chelsea Byers, external_id -700602, UUID a3aac8fc-d8cb-4cb7-b6be-e5b0fa97c15a. Rotational mayor (Mayor 2025-26).
BEGIN;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('a3aac8fc-d8cb-4cb7-b6be-e5b0fa97c15a','669cac97-66a6-4087-b036-936fbe62efb3',1.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('a3aac8fc-d8cb-4cb7-b6be-e5b0fa97c15a','669cac97-66a6-4087-b036-936fbe62efb3',$$Council Member Byers prioritizes creating more affordable housing and serves on the city's 6th Cycle Housing Element Task Force, a strongly pro-housing position.$$,ARRAY['https://www.weho.org/city-government/city-council/councilmembers/chelsea-lee-byers']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('a3aac8fc-d8cb-4cb7-b6be-e5b0fa97c15a','6fbf39ae-6b19-4182-b4c2-6a8d25c86c0f',2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('a3aac8fc-d8cb-4cb7-b6be-e5b0fa97c15a','6fbf39ae-6b19-4182-b4c2-6a8d25c86c0f',$$As Chair of the Council's Homelessness Subcommittee and a former United Way "Everyone In" campaign organizer, Byers emphasizes social-service delivery and housing solutions for unhoused residents.$$,ARRAY['https://www.weho.org/city-government/city-council/councilmembers/chelsea-lee-byers']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('a3aac8fc-d8cb-4cb7-b6be-e5b0fa97c15a','ba59337e-30e2-4aba-a39a-426b3366eb27',1.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('a3aac8fc-d8cb-4cb7-b6be-e5b0fa97c15a','ba59337e-30e2-4aba-a39a-426b3366eb27',$$Byers prioritizes enhancing the streetscape for pedestrians and cyclists while reducing vehicle-dependency, and was backed by housing and transportation advocates — a strongly multimodal stance.$$,ARRAY['https://www.chelsea4weho.com/biography']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('a3aac8fc-d8cb-4cb7-b6be-e5b0fa97c15a','f1e44d66-5d27-4b51-b54f-b7ace86f6a3c',2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('a3aac8fc-d8cb-4cb7-b6be-e5b0fa97c15a','f1e44d66-5d27-4b51-b54f-b7ace86f6a3c',$$Byers lists climate-change mitigation strategies and emergency-resiliency efforts among her council priorities.$$,ARRAY['https://www.weho.org/city-government/city-council/councilmembers/chelsea-lee-byers']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('a3aac8fc-d8cb-4cb7-b6be-e5b0fa97c15a','c308e8e8-caac-44f5-ab04-dbfecf40bbe2',2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('a3aac8fc-d8cb-4cb7-b6be-e5b0fa97c15a','c308e8e8-caac-44f5-ab04-dbfecf40bbe2',$$Byers serves on the Rent Stabilization Ordinance ad-hoc committee and prioritizes resources for renters, supporting tenant-protective rent regulation.$$,ARRAY['https://www.weho.org/city-government/city-council/councilmembers/chelsea-lee-byers']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
COMMIT;
