-- Migration 767: Lauren Meister (West Hollywood Council) Stances
-- Phase 136 — West Hollywood. Lauren Meister, external_id -700603, UUID 5b6291a0-b5ab-4f27-a318-d309c726d8e6. Rotational mayor.
BEGIN;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('5b6291a0-b5ab-4f27-a318-d309c726d8e6','c308e8e8-caac-44f5-ab04-dbfecf40bbe2',1.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('5b6291a0-b5ab-4f27-a318-d309c726d8e6','c308e8e8-caac-44f5-ab04-dbfecf40bbe2',$$Council Member Meister advocates protecting rent-stabilized buildings and disincentivizing developer evictions, and in 2022 was the only councilmember to support requiring one-for-one replacement of rent-stabilized units as all-affordable — a strongly pro-tenant rent-regulation record.$$,ARRAY['https://meister4weho.com/issues-that-matter']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('5b6291a0-b5ab-4f27-a318-d309c726d8e6','fb25c1ac-91cc-49bf-8afc-c7fa22ef45e4',4.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('5b6291a0-b5ab-4f27-a318-d309c726d8e6','fb25c1ac-91cc-49bf-8afc-c7fa22ef45e4',$$A longtime neighborhood-association leader, Meister champions neighborhood-friendly planning and land-use policies and works to disincentivize luxury development, a controlled-growth, neighborhood-preservation orientation.$$,ARRAY['https://meister4weho.com/issues-that-matter']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('5b6291a0-b5ab-4f27-a318-d309c726d8e6','e9ebefcd-c496-45e8-b816-a79f8442ba85',3.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('5b6291a0-b5ab-4f27-a318-d309c726d8e6','e9ebefcd-c496-45e8-b816-a79f8442ba85',$$A former Public Safety Commissioner, Meister centers resident public safety through quality-of-life measures such as a Public Access Defibrillation program and traffic/pedestrian safety, a pragmatic resident-services approach.$$,ARRAY['https://www.weho.org/city-government/city-council/councilmembers/lauren-meister']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
INSERT INTO inform.politician_answers (politician_id, topic_id, value) VALUES ('5b6291a0-b5ab-4f27-a318-d309c726d8e6','1935979c-b290-42e4-baa5-8cb0138b4ffa',2.0) ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources) VALUES ('5b6291a0-b5ab-4f27-a318-d309c726d8e6','1935979c-b290-42e4-baa5-8cb0138b4ffa',$$Meister works to increase green-space opportunities and raise the bar on environmental programs and sustainability in West Hollywood.$$,ARRAY['https://meister4weho.com/issues-that-matter']::text[]::text[]) ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
COMMIT;
