-- 913_rex_parris_stances.sql
-- Phase 145 Wave 4 — AUDIT-ONLY (raw SQL; does NOT register in schema_migrations)
-- Evidence-only compass stances for R. Rex Parris (Mayor of Lancaster), external_id -200795.
-- Chairs model; 100% citation; no defaults. 10 evidence-backed topics.

BEGIN;

WITH pol AS (SELECT id AS pid FROM essentials.politicians WHERE external_id = -200795),
s(topic_key, val, reasoning, sources) AS (VALUES
  ('climate-change', 3, $r$Parris built Lancaster into a 'net-zero' clean-energy city (Lancaster Choice Energy, net-zero new-home mandate, EPA Green Power award) and in 2024 launched Lancaster Energy investing in hydrogen, green ammonia and solar — aggressive clean-energy investment + gradual transition rather than an emissions-ban emergency.$r$, ARRAY[$u$https://en.wikipedia.org/wiki/R._Rex_Parris$u$,$u$https://www.prnewswire.com/news-releases/mayor-r-rex-parris-embraces-hydrogen-as-the-next-clean-green-fuel-301120456.html$u$]),
  ('fossil-fuels', 2, $r$Parris has staked Lancaster's economy on replacing fossil fuels with renewable hydrogen and solar — chairing First Public Hydrogen and launching Lancaster Energy to supply clean fuel — a posture of moving off fossil fuels rather than expanding extraction.$r$, ARRAY[$u$https://www.prnewswire.com/news-releases/mayor-r-rex-parris-embraces-hydrogen-as-the-next-clean-green-fuel-301120456.html$u$,$u$https://en.wikipedia.org/wiki/R._Rex_Parris$u$]),
  ('local-environment', 3, $r$Lancaster pairs strong environmental branding (net-zero, renewable mandates) with active recruitment of large development (e.g. data centers) governed by a community-benefits agreement — consistent standards applied with flexibility, not absolute protection nor pure economic deference.$r$, ARRAY[$u$https://en.wikipedia.org/wiki/R._Rex_Parris$u$,$u$https://lancasteronline.com/news/local/lancaster-city-council-votes-to-approve-data-center-benefits-agreement/article_b05cb1fd-a585-4c4f-8945-c96ada3172ad.html$u$]),
  ('economic-development', 3, $r$Parris's council approved a data-center community-benefits agreement securing a guaranteed $20M investment and quality-of-life protections in exchange for the development — targeted incentives with community benefit.$r$, ARRAY[$u$https://lancasteronline.com/news/local/lancaster-city-council-votes-to-approve-data-center-benefits-agreement/article_b05cb1fd-a585-4c4f-8945-c96ada3172ad.html$u$]),
  ('data-centers', 3, $r$Lancaster approved AI data-center campuses through a negotiated community-benefits agreement (quality-of-life protections + $20M investment) rather than a moratorium or no-strings approval — the impact-assessment/community-benefit chair.$r$, ARRAY[$u$https://lancasteronline.com/news/local/lancaster-city-council-votes-to-approve-data-center-benefits-agreement/article_b05cb1fd-a585-4c4f-8945-c96ada3172ad.html$u$]),
  ('housing', 4, $r$Lancaster earned California's 2025 Prohousing Designation for streamlining development approvals and using city-owned land to spur housing, with Parris touting results-driven housing — cutting regulatory barriers so housing gets built.$r$, ARRAY[$u$https://www.cityoflancasterca.org/Home/Components/News/News/10422/20$u$,$u$https://www.hcd.ca.gov/planning-and-research/prohousing/designated-jurisdictions$u$]),
  ('growth-and-development', 4, $r$Under Parris the city streamlined approvals (Prohousing Designation) and aggressively recruited major projects ($10B data centers, clean-energy industry) — a streamline-and-recruit approach to growth.$r$, ARRAY[$u$https://www.cityoflancasterca.org/Home/Components/News/News/10422/20$u$,$u$https://lancasteronline.com/news/local/lancaster-city-council-votes-to-approve-data-center-benefits-agreement/article_b05cb1fd-a585-4c4f-8945-c96ada3172ad.html$u$]),
  ('homelessness', 5, $r$At a Feb 25 2025 council meeting Parris floated congregating unhoused residents into an encampment, then said he wanted 'a purge' and to give the homeless 'all the fentanyl they want' — a punitive enforcement-and-removal stance matching the strictest anti-camping chair.$r$, ARRAY[$u$https://www.aol.com/news/lancaster-mayors-remedy-homelessness-free-100005128.html$u$,$u$https://abc7.com/post/lancaster-mayor-rex-parris-defends-controversial-comments-giving-homeless-free-fentanyl/16227283/$u$]),
  ('homelessness-response', 5, $r$Parris's on-record homelessness strategy — forced encampment congregation plus 'purge'/'free fentanyl' rhetoric — signals strict enforcement and hostility to service spending rather than housing- or shelter-first investment.$r$, ARRAY[$u$https://www.aol.com/news/lancaster-mayors-remedy-homelessness-free-100005128.html$u$,$u$https://www.yahoo.com/news/california-mayor-says-wants-homeless-225659472.html$u$]),
  ('public-safety-approach', 4, $r$Parris spearheaded creating Lancaster's own municipal police department (sworn in 2023, ~$10M, growing officer headcount) to add policing capacity atop sheriff's deputies — the increase-police-staffing chair.$r$, ARRAY[$u$https://ktla.com/news/local-news/lancaster-creates-new-police-department/$u$,$u$https://www.nbclosangeles.com/news/local/lancaster-creates-its-own-police-department-to-fight-crime/3225050/$u$])
)
INSERT INTO inform.politician_answers (politician_id, topic_id, value)
SELECT pol.pid, t.id, s.val
FROM s JOIN inform.compass_topics t ON t.topic_key = s.topic_key CROSS JOIN pol
ON CONFLICT (politician_id, topic_id) DO UPDATE SET value = EXCLUDED.value;

WITH pol AS (SELECT id AS pid FROM essentials.politicians WHERE external_id = -200795),
s(topic_key, reasoning, sources) AS (VALUES
  ('climate-change', $r$Parris built Lancaster into a 'net-zero' clean-energy city (Lancaster Choice Energy, net-zero new-home mandate, EPA Green Power award) and in 2024 launched Lancaster Energy investing in hydrogen, green ammonia and solar — aggressive clean-energy investment + gradual transition rather than an emissions-ban emergency.$r$, ARRAY[$u$https://en.wikipedia.org/wiki/R._Rex_Parris$u$,$u$https://www.prnewswire.com/news-releases/mayor-r-rex-parris-embraces-hydrogen-as-the-next-clean-green-fuel-301120456.html$u$]),
  ('fossil-fuels', $r$Parris has staked Lancaster's economy on replacing fossil fuels with renewable hydrogen and solar — chairing First Public Hydrogen and launching Lancaster Energy to supply clean fuel — a posture of moving off fossil fuels rather than expanding extraction.$r$, ARRAY[$u$https://www.prnewswire.com/news-releases/mayor-r-rex-parris-embraces-hydrogen-as-the-next-clean-green-fuel-301120456.html$u$,$u$https://en.wikipedia.org/wiki/R._Rex_Parris$u$]),
  ('local-environment', $r$Lancaster pairs strong environmental branding (net-zero, renewable mandates) with active recruitment of large development (e.g. data centers) governed by a community-benefits agreement — consistent standards applied with flexibility, not absolute protection nor pure economic deference.$r$, ARRAY[$u$https://en.wikipedia.org/wiki/R._Rex_Parris$u$,$u$https://lancasteronline.com/news/local/lancaster-city-council-votes-to-approve-data-center-benefits-agreement/article_b05cb1fd-a585-4c4f-8945-c96ada3172ad.html$u$]),
  ('economic-development', $r$Parris's council approved a data-center community-benefits agreement securing a guaranteed $20M investment and quality-of-life protections in exchange for the development — targeted incentives with community benefit.$r$, ARRAY[$u$https://lancasteronline.com/news/local/lancaster-city-council-votes-to-approve-data-center-benefits-agreement/article_b05cb1fd-a585-4c4f-8945-c96ada3172ad.html$u$]),
  ('data-centers', $r$Lancaster approved AI data-center campuses through a negotiated community-benefits agreement (quality-of-life protections + $20M investment) rather than a moratorium or no-strings approval — the impact-assessment/community-benefit chair.$r$, ARRAY[$u$https://lancasteronline.com/news/local/lancaster-city-council-votes-to-approve-data-center-benefits-agreement/article_b05cb1fd-a585-4c4f-8945-c96ada3172ad.html$u$]),
  ('housing', $r$Lancaster earned California's 2025 Prohousing Designation for streamlining development approvals and using city-owned land to spur housing, with Parris touting results-driven housing — cutting regulatory barriers so housing gets built.$r$, ARRAY[$u$https://www.cityoflancasterca.org/Home/Components/News/News/10422/20$u$,$u$https://www.hcd.ca.gov/planning-and-research/prohousing/designated-jurisdictions$u$]),
  ('growth-and-development', $r$Under Parris the city streamlined approvals (Prohousing Designation) and aggressively recruited major projects ($10B data centers, clean-energy industry) — a streamline-and-recruit approach to growth.$r$, ARRAY[$u$https://www.cityoflancasterca.org/Home/Components/News/News/10422/20$u$,$u$https://lancasteronline.com/news/local/lancaster-city-council-votes-to-approve-data-center-benefits-agreement/article_b05cb1fd-a585-4c4f-8945-c96ada3172ad.html$u$]),
  ('homelessness', $r$At a Feb 25 2025 council meeting Parris floated congregating unhoused residents into an encampment, then said he wanted 'a purge' and to give the homeless 'all the fentanyl they want' — a punitive enforcement-and-removal stance matching the strictest anti-camping chair.$r$, ARRAY[$u$https://www.aol.com/news/lancaster-mayors-remedy-homelessness-free-100005128.html$u$,$u$https://abc7.com/post/lancaster-mayor-rex-parris-defends-controversial-comments-giving-homeless-free-fentanyl/16227283/$u$]),
  ('homelessness-response', $r$Parris's on-record homelessness strategy — forced encampment congregation plus 'purge'/'free fentanyl' rhetoric — signals strict enforcement and hostility to service spending rather than housing- or shelter-first investment.$r$, ARRAY[$u$https://www.aol.com/news/lancaster-mayors-remedy-homelessness-free-100005128.html$u$,$u$https://www.yahoo.com/news/california-mayor-says-wants-homeless-225659472.html$u$]),
  ('public-safety-approach', $r$Parris spearheaded creating Lancaster's own municipal police department (sworn in 2023, ~$10M, growing officer headcount) to add policing capacity atop sheriff's deputies — the increase-police-staffing chair.$r$, ARRAY[$u$https://ktla.com/news/local-news/lancaster-creates-new-police-department/$u$,$u$https://www.nbclosangeles.com/news/local/lancaster-creates-its-own-police-department-to-fight-crime/3225050/$u$])
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT pol.pid, t.id, s.reasoning, s.sources
FROM s JOIN inform.compass_topics t ON t.topic_key = s.topic_key CROSS JOIN pol
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning = EXCLUDED.reasoning, sources = EXCLUDED.sources;

COMMIT;
