-- 949_victor_gordo_stances.sql  AUDIT-ONLY (NOT registered in schema_migrations; ledger stays 947)
-- Victor M. Gordo (Mayor, ext -200901) — evidence-only compass stances (chairs model), 100% citation.
-- Resolves politician_id by external_id and topic_id by topic_key at apply time (live topics only).
BEGIN;
WITH pol AS (SELECT id FROM essentials.politicians WHERE external_id = -200901),
d(topic_key, val, reasoning, sources) AS (
 VALUES
  ('rent-regulation', 4::numeric, $stz$Gordo publicly urged a No vote on Measure H rent control, arguing rent control 'does not work' and instead pointing to California's 2019 Tenant Protection Act and subsidized/affordable-housing development as the right tools — opposing broad local rent control while still endorsing existing statutory protections and subsidized units.$stz$, ARRAY[$stz$https://pasadenanow.com/main/guest-opinion-mayor-victor-m-gordo-vote-no-on-measure-h$stz$]::text[]),
  ('housing', 3::numeric, $stz$Gordo champions targeted affordable-housing development — converting older/luxury buildings to senior and low/moderate-income units, the regional housing trust, and supporting subsidized projects — rather than direct public housing or broad deregulation.$stz$, ARRAY[$stz$https://pasadenanow.com/main/guest-opinion-mayor-victor-m-gordo-vote-no-on-measure-h$stz$,$stz$https://www.pasadenaweekly.com/news/the-future-of-pasadena-mayor-gordo-seeks-2nd-term/article_d0a8a808-ef60-11ed-87f7-630f30dff74b.html$stz$]::text[]),
  ('growth-and-development', 2::numeric, $stz$Gordo's signature theme is opposing overdevelopment; he argues developers were allowed to put a 'for sale' sign on the city and insists growth be guided by resident input with a deliberate, community-centered process ('there are no do-overs').$stz$, ARRAY[$stz$https://www.victorgordoformayor.com/about-victor$stz$,$stz$https://pasadenanow.com/main/mayoral-candidate-victor-gordo-talks-about-development-transparency-social-justice-and-consensus-building$stz$]::text[]),
  ('residential-zoning', 2::numeric, $stz$Gordo repeatedly objects to state-mandated upzoning/density laws stripping local discretion ('the local elected body essentially has little to no say, and that's wrong') and wants neighborhood input on zoning, while still approving modest/affordable infill — favoring local-input-driven density over by-right upzoning.$stz$, ARRAY[$stz$https://laist.com/news/housing-homelessness/pasadena-affordable-housing-city-council-design-review-vote-eaton-fire$stz$,$stz$https://pasadenanow.com/main/pasadena-votes-to-delay-a-state-housing-law-near-the-gold-line-three-top-officials-sit-it-out$stz$]::text[]),
  ('transportation-priorities', 1::numeric, $stz$Under Gordo the council adopted the Reconnecting Pasadena 710-stub vision plan that reduces vehicle throughput and adds multimodal transit and ~1,800 housing units; Gordo framed it as restitching a community rather than a road project.$stz$, ARRAY[$stz$https://la.streetsblog.org/2026/04/16/pasadena-adopts-most-of-the-710-stub-vision-plan$stz$]::text[]),
  ('local-immigration', 1::numeric, $stz$Gordo reaffirmed that Pasadena Police will not coordinate with, assist, or participate in ICE operations, condemned the raids, and joined LA County and other cities in a federal civil-rights lawsuit against ICE.$stz$, ARRAY[$stz$https://time.com/7295305/pasadena-trump-immigration-raids/$stz$,$stz$https://www.cbsnews.com/losangeles/video/pasadena-mayor-victor-gordo-on-ice-raids-and-a-federal-lawsuit/$stz$]::text[]),
  ('climate-change', 3::numeric, $stz$Gordo supported the council-approved Optimized Strategic Plan to reach 100% carbon-free electricity by 2030 and a major solar pact, but emphasized affordability and close scrutiny of costs/rate increases — investing in clean energy while managing pace and cost.$stz$, ARRAY[$stz$https://pasadenanow.com/main/pasadena-approves-power-utilitys-plan-to-guide-carbon-free-electricity-goals$stz$]::text[]),
  ('public-safety-approach', 3::numeric, $stz$As councilmember Gordo proposed and the council in Oct 2020 established an independent police auditor and Community Police Oversight Commission; he frames public safety as fighting crime while building trust and adding oversight — keeping policing funded while layering accountability rather than defunding.$stz$, ARRAY[$stz$https://www.pasadenanow.com/main/city-council-approves-community-police-oversight-commission-independent-auditor$stz$]::text[]),
  ('homelessness-response', 2::numeric, $stz$Gordo's approach centers permanent supportive housing and services delivered through regional partnerships (SGV COG, federal supportive-housing/rapid-rehousing grants, Salvation Army Hope Center), which he credits for cutting Pasadena's homeless count — services/housing expansion as the primary tool.$stz$, ARRAY[$stz$https://pasadenanow.com/main/federal-court-battle-and-act-of-congress-set-stage-for-pasadena-councils-6-6-million-homeless-grant-vote-monday$stz$]::text[]),
  ('economic-development', 3::numeric, $stz$Gordo actively recruits employers (GM, Lucid, Rivian, Xencor) with modest targeted incentives (no gross-receipts tax) while a long record of championing a living wage and tying development to community/job quality — targeted, community-benefit-minded incentives rather than maximum no-strings abatements.$stz$, ARRAY[$stz$https://www.pasadenaweekly.com/news/the-future-of-pasadena-mayor-gordo-seeks-2nd-term/article_d0a8a808-ef60-11ed-87f7-630f30dff74b.html$stz$,$stz$https://www.victorgordoformayor.com/about-victor$stz$]::text[])
),
ans AS (
 INSERT INTO inform.politician_answers (politician_id, topic_id, value)
 SELECT pol.id, t.id, d.val
 FROM d JOIN inform.compass_topics t ON t.topic_key=d.topic_key AND t.is_live=true CROSS JOIN pol
 ON CONFLICT (politician_id, topic_id) DO UPDATE SET value=EXCLUDED.value
 RETURNING 1
)
INSERT INTO inform.politician_context (politician_id, topic_id, reasoning, sources)
SELECT pol.id, t.id, d.reasoning, d.sources
FROM d JOIN inform.compass_topics t ON t.topic_key=d.topic_key AND t.is_live=true CROSS JOIN pol
ON CONFLICT (politician_id, topic_id) DO UPDATE SET reasoning=EXCLUDED.reasoning, sources=EXCLUDED.sources;
COMMIT;
