-- 980_state_exec_seed_batch_a.sql
-- Phase 141 (v2.18 State Leaders), plan 141-03.
-- GENERATED by backend/scripts/gen-state-exec-seed.mjs from live-verified (June 2026) roster.
-- Seeds 35 in-scope elected Big-5 offices across: AK, AL, FL, IL, MS, NC, NY, SD.
-- Idempotent (NOT EXISTS / ON CONFLICT guards). external_id = -(fips*100000+seq) except AK/AZ collision offsets.
-- Run: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f backend/migrations/980_state_exec_seed_batch_a.sql

BEGIN;

CREATE TEMP TABLE _seed (
  state text, fips int, geo_id text, state_name text, title text, role_canonical text,
  full_name text, first_name text, last_name text, party text, ext_id bigint
) ON COMMIT DROP;

INSERT INTO _seed (state, fips, geo_id, state_name, title, role_canonical, full_name, first_name, last_name, party, ext_id) VALUES
  ('AK', 2, '02', 'Alaska', 'Governor', 'governor', 'Mike Dunleavy', 'Mike', 'Dunleavy', 'Republican', -200008),
  ('AK', 2, '02', 'Alaska', 'Lieutenant Governor', 'lt_governor', 'Nancy Dahlstrom', 'Nancy', 'Dahlstrom', 'Republican', -200009),
  ('AL', 1, '01', 'Alabama', 'Governor', 'governor', 'Kay Ivey', 'Kay', 'Ivey', 'Republican', -100001),
  ('AL', 1, '01', 'Alabama', 'Lieutenant Governor', 'lt_governor', 'Will Ainsworth', 'Will', 'Ainsworth', 'Republican', -100002),
  ('AL', 1, '01', 'Alabama', 'Attorney General', 'attorney_general', 'Steve Marshall', 'Steve', 'Marshall', 'Republican', -100003),
  ('AL', 1, '01', 'Alabama', 'Secretary of State', 'secretary_of_state', 'Wes Allen', 'Wes', 'Allen', 'Republican', -100004),
  ('AL', 1, '01', 'Alabama', 'Treasurer', 'treasurer', 'Young Boozer', 'Young', 'Boozer', 'Republican', -100005),
  ('FL', 12, '12', 'Florida', 'Governor', 'governor', 'Ron DeSantis', 'Ron', 'DeSantis', 'Republican', -1200001),
  ('FL', 12, '12', 'Florida', 'Lieutenant Governor', 'lt_governor', 'Jay Collins', 'Jay', 'Collins', 'Republican', -1200002),
  ('FL', 12, '12', 'Florida', 'Attorney General', 'attorney_general', 'James Uthmeier', 'James', 'Uthmeier', 'Republican', -1200003),
  ('FL', 12, '12', 'Florida', 'Chief Financial Officer', 'treasurer', 'Blaise Ingoglia', 'Blaise', 'Ingoglia', 'Republican', -1200004),
  ('IL', 17, '17', 'Illinois', 'Governor', 'governor', 'JB Pritzker', 'JB', 'Pritzker', 'Democrat', -1700001),
  ('IL', 17, '17', 'Illinois', 'Lieutenant Governor', 'lt_governor', 'Juliana Stratton', 'Juliana', 'Stratton', 'Democrat', -1700002),
  ('IL', 17, '17', 'Illinois', 'Attorney General', 'attorney_general', 'Kwame Raoul', 'Kwame', 'Raoul', 'Democrat', -1700003),
  ('IL', 17, '17', 'Illinois', 'Secretary of State', 'secretary_of_state', 'Alexi Giannoulias', 'Alexi', 'Giannoulias', 'Democrat', -1700004),
  ('IL', 17, '17', 'Illinois', 'Treasurer', 'treasurer', 'Mike Frerichs', 'Mike', 'Frerichs', 'Democrat', -1700005),
  ('MS', 28, '28', 'Mississippi', 'Governor', 'governor', 'Tate Reeves', 'Tate', 'Reeves', 'Republican', -2800001),
  ('MS', 28, '28', 'Mississippi', 'Lieutenant Governor', 'lt_governor', 'Delbert Hosemann', 'Delbert', 'Hosemann', 'Republican', -2800002),
  ('MS', 28, '28', 'Mississippi', 'Attorney General', 'attorney_general', 'Lynn Fitch', 'Lynn', 'Fitch', 'Republican', -2800003),
  ('MS', 28, '28', 'Mississippi', 'Secretary of State', 'secretary_of_state', 'Michael Watson', 'Michael', 'Watson', 'Republican', -2800004),
  ('MS', 28, '28', 'Mississippi', 'Treasurer', 'treasurer', 'David McRae', 'David', 'McRae', 'Republican', -2800005),
  ('NC', 37, '37', 'North Carolina', 'Governor', 'governor', 'Josh Stein', 'Josh', 'Stein', 'Democrat', -3700001),
  ('NC', 37, '37', 'North Carolina', 'Lieutenant Governor', 'lt_governor', 'Rachel Hunt', 'Rachel', 'Hunt', 'Democrat', -3700002),
  ('NC', 37, '37', 'North Carolina', 'Attorney General', 'attorney_general', 'Jeff Jackson', 'Jeff', 'Jackson', 'Democrat', -3700003),
  ('NC', 37, '37', 'North Carolina', 'Secretary of State', 'secretary_of_state', 'Elaine Marshall', 'Elaine', 'Marshall', 'Democrat', -3700004),
  ('NC', 37, '37', 'North Carolina', 'Treasurer', 'treasurer', 'Brad Briner', 'Brad', 'Briner', 'Republican', -3700005),
  ('NY', 36, '36', 'New York', 'Governor', 'governor', 'Kathy Hochul', 'Kathy', 'Hochul', 'Democrat', -3600001),
  ('NY', 36, '36', 'New York', 'Lieutenant Governor', 'lt_governor', 'Antonio Delgado', 'Antonio', 'Delgado', 'Democrat', -3600002),
  ('NY', 36, '36', 'New York', 'Attorney General', 'attorney_general', 'Letitia James', 'Letitia', 'James', 'Democrat', -3600003),
  ('NY', 36, '36', 'New York', 'Comptroller', 'treasurer', 'Thomas DiNapoli', 'Thomas', 'DiNapoli', 'Democrat', -3600004),
  ('SD', 46, '46', 'South Dakota', 'Governor', 'governor', 'Larry Rhoden', 'Larry', 'Rhoden', 'Republican', -4600001),
  ('SD', 46, '46', 'South Dakota', 'Lieutenant Governor', 'lt_governor', 'Tony Venhuizen', 'Tony', 'Venhuizen', 'Republican', -4600002),
  ('SD', 46, '46', 'South Dakota', 'Attorney General', 'attorney_general', 'Marty Jackley', 'Marty', 'Jackley', 'Republican', -4600003),
  ('SD', 46, '46', 'South Dakota', 'Secretary of State', 'secretary_of_state', 'Monae Johnson', 'Monae', 'Johnson', 'Republican', -4600004),
  ('SD', 46, '46', 'South Dakota', 'Treasurer', 'treasurer', 'Josh Haeder', 'Josh', 'Haeder', 'Republican', -4600005);

-- PREFLIGHT 1 (D-04): every proposed external_id is below the federal US-House band (< -56000).
DO $$ DECLARE v INT; BEGIN
  SELECT count(*) INTO v FROM _seed WHERE ext_id > -56000;
  IF v > 0 THEN RAISE EXCEPTION 'PREFLIGHT 1 FAILED: % external_id(s) within/above the federal band', v; END IF;
END $$;

-- PREFLIGHT 2 (D-04): no proposed external_id is held by a DIFFERENT politician (true collision).
-- Idempotent: on re-run our own seeded politicians match full_name and are exempt; a real collision
-- (ext_id on someone else) still RAISES.
DO $$ DECLARE v TEXT; BEGIN
  SELECT string_agg(s.ext_id::text, ', ') INTO v
  FROM _seed s JOIN essentials.politicians p ON p.external_id = s.ext_id
  WHERE p.full_name <> s.full_name;
  IF v IS NOT NULL THEN RAISE EXCEPTION 'PREFLIGHT 2 FAILED: external_id collision with a different politician: %', v; END IF;
END $$;

-- PREFLIGHT 3 (Pitfall 4 safe): every state has its 'State of <Name>' government row.
DO $$ DECLARE v TEXT; BEGIN
  SELECT string_agg(DISTINCT s.state, ', ') INTO v FROM _seed s
  WHERE NOT EXISTS (SELECT 1 FROM essentials.governments g WHERE g.state = s.state AND g.name = 'State of ' || s.state_name);
  IF v IS NOT NULL THEN RAISE EXCEPTION 'PREFLIGHT 3 FAILED: missing government row for: %', v; END IF;
END $$;

-- 1) One labeled STATE_EXEC district per office ('<State> <Title>', uppercase state, FIPS geo_id).
INSERT INTO essentials.districts (id, district_type, state, geo_id, label, district_id, mtfcc)
SELECT gen_random_uuid(), 'STATE_EXEC', s.state, s.geo_id, s.state_name || ' ' || s.title, '', ''
FROM _seed s
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts d
  WHERE d.district_type='STATE_EXEC' AND d.state=s.state AND d.label = s.state_name || ' ' || s.title
);

-- 2) One chamber per office under the state's government (name=title; slug is GENERATED ALWAYS - excluded).
INSERT INTO essentials.chambers (id, name, name_formal, government_id)
SELECT gen_random_uuid(), s.title, s.title || ' of ' || s.state_name, g.id
FROM _seed s
JOIN essentials.governments g ON g.state=s.state AND g.name='State of ' || s.state_name
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.chambers c WHERE c.government_id=g.id AND c.name=s.title
);

-- 3) Politicians (idempotent on external_id).
INSERT INTO essentials.politicians
  (id, full_name, first_name, last_name, party, is_active, is_appointed, is_vacant, is_incumbent, external_id)
SELECT gen_random_uuid(), s.full_name, s.first_name, s.last_name, s.party, true, false, false, true, s.ext_id
FROM _seed s
ON CONFLICT (external_id) DO NOTHING;

-- 4) Offices linking politician+district+chamber, role_canonical set (guard on district+chamber).
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(), d.id, c.id, p.id, s.title, s.state, false, false, s.role_canonical
FROM _seed s
JOIN essentials.districts d ON d.district_type='STATE_EXEC' AND d.state=s.state AND d.label = s.state_name || ' ' || s.title
JOIN essentials.governments g ON g.state=s.state AND g.name='State of ' || s.state_name
JOIN essentials.chambers c ON c.government_id=g.id AND c.name=s.title
JOIN essentials.politicians p ON p.external_id=s.ext_id
WHERE NOT EXISTS (SELECT 1 FROM essentials.offices o WHERE o.district_id=d.id AND o.chamber_id=c.id);

-- 5) office_id backfill (idempotent).
UPDATE essentials.politicians p SET office_id = o.id
FROM essentials.offices o, _seed s
WHERE o.politician_id=p.id AND p.external_id=s.ext_id AND p.office_id IS NULL;

-- ============================ POST ASSERTIONS ============================
DO $$ DECLARE v_cnt INT; v_bad INT; v_null INT; BEGIN
  SELECT count(*) INTO v_cnt
  FROM essentials.offices o JOIN essentials.districts d ON d.id=o.district_id
  WHERE d.district_type='STATE_EXEC' AND d.state IN ('AK', 'AL', 'FL', 'IL', 'MS', 'NC', 'NY', 'SD')
    AND o.role_canonical IN ('governor','lt_governor','attorney_general','secretary_of_state','treasurer');
  IF v_cnt <> 35 THEN RAISE EXCEPTION 'POST FAILED: in-scope office count=% (expected 35)', v_cnt; END IF;

  SELECT count(*) INTO v_bad FROM essentials.districts d
  WHERE d.district_type='STATE_EXEC' AND d.state IN ('AK', 'AL', 'FL', 'IL', 'MS', 'NC', 'NY', 'SD')
    AND (d.state <> upper(d.state) OR d.geo_id IS NULL OR d.geo_id='');
  IF v_bad <> 0 THEN RAISE EXCEPTION 'POST FAILED: % districts with lowercase state or empty geo_id', v_bad; END IF;

  SELECT count(*) INTO v_null FROM essentials.offices o
  JOIN essentials.politicians p ON p.id=o.politician_id, _seed s
  WHERE p.external_id=s.ext_id AND o.role_canonical IS NULL;
  IF v_null <> 0 THEN RAISE EXCEPTION 'POST FAILED: % seeded offices with NULL role_canonical', v_null; END IF;

  RAISE NOTICE 'Migration 980 OK: % in-scope Big-5 offices seeded across 8 states (AK/AL/FL/IL/MS/NC/NY/SD)', v_cnt;
END $$;

COMMIT;
