-- 982_state_exec_seed_batch_c.sql
-- Phase 141 (v2.18 State Leaders), plan 141-05.
-- GENERATED by backend/scripts/gen-state-exec-seed.mjs from live-verified (June 2026) roster.
-- Seeds 35 in-scope elected Big-5 offices across: CO, KS, MI, NE, NJ, OH, PA, WA.
-- Idempotent (NOT EXISTS / ON CONFLICT guards). external_id = -(fips*100000+seq) except AK/AZ collision offsets.
-- Run: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f backend/migrations/982_state_exec_seed_batch_c.sql

BEGIN;

CREATE TEMP TABLE _seed (
  state text, fips int, geo_id text, state_name text, title text, role_canonical text,
  full_name text, first_name text, last_name text, party text, ext_id bigint
) ON COMMIT DROP;

INSERT INTO _seed (state, fips, geo_id, state_name, title, role_canonical, full_name, first_name, last_name, party, ext_id) VALUES
  ('CO', 8, '08', 'Colorado', 'Governor', 'governor', 'Jared Polis', 'Jared', 'Polis', 'Democrat', -800001),
  ('CO', 8, '08', 'Colorado', 'Lieutenant Governor', 'lt_governor', 'Dianne Primavera', 'Dianne', 'Primavera', 'Democrat', -800002),
  ('CO', 8, '08', 'Colorado', 'Attorney General', 'attorney_general', 'Phil Weiser', 'Phil', 'Weiser', 'Democrat', -800003),
  ('CO', 8, '08', 'Colorado', 'Secretary of State', 'secretary_of_state', 'Jena Griswold', 'Jena', 'Griswold', 'Democrat', -800004),
  ('CO', 8, '08', 'Colorado', 'Treasurer', 'treasurer', 'Dave Young', 'Dave', 'Young', 'Democrat', -800005),
  ('KS', 20, '20', 'Kansas', 'Governor', 'governor', 'Laura Kelly', 'Laura', 'Kelly', 'Democrat', -2000001),
  ('KS', 20, '20', 'Kansas', 'Lieutenant Governor', 'lt_governor', 'David Toland', 'David', 'Toland', 'Democrat', -2000002),
  ('KS', 20, '20', 'Kansas', 'Attorney General', 'attorney_general', 'Kris Kobach', 'Kris', 'Kobach', 'Republican', -2000003),
  ('KS', 20, '20', 'Kansas', 'Secretary of State', 'secretary_of_state', 'Scott Schwab', 'Scott', 'Schwab', 'Republican', -2000004),
  ('KS', 20, '20', 'Kansas', 'Treasurer', 'treasurer', 'Steven Johnson', 'Steven', 'Johnson', 'Republican', -2000005),
  ('MI', 26, '26', 'Michigan', 'Governor', 'governor', 'Gretchen Whitmer', 'Gretchen', 'Whitmer', 'Democrat', -2600001),
  ('MI', 26, '26', 'Michigan', 'Lieutenant Governor', 'lt_governor', 'Garlin Gilchrist', 'Garlin', 'Gilchrist', 'Democrat', -2600002),
  ('MI', 26, '26', 'Michigan', 'Attorney General', 'attorney_general', 'Dana Nessel', 'Dana', 'Nessel', 'Democrat', -2600003),
  ('MI', 26, '26', 'Michigan', 'Secretary of State', 'secretary_of_state', 'Jocelyn Benson', 'Jocelyn', 'Benson', 'Democrat', -2600004),
  ('NE', 31, '31', 'Nebraska', 'Governor', 'governor', 'Jim Pillen', 'Jim', 'Pillen', 'Republican', -3100001),
  ('NE', 31, '31', 'Nebraska', 'Lieutenant Governor', 'lt_governor', 'Joe Kelly', 'Joe', 'Kelly', 'Republican', -3100002),
  ('NE', 31, '31', 'Nebraska', 'Attorney General', 'attorney_general', 'Mike Hilgers', 'Mike', 'Hilgers', 'Republican', -3100003),
  ('NE', 31, '31', 'Nebraska', 'Secretary of State', 'secretary_of_state', 'Bob Evnen', 'Bob', 'Evnen', 'Republican', -3100004),
  ('NE', 31, '31', 'Nebraska', 'Treasurer', 'treasurer', 'Joey Spellerberg', 'Joey', 'Spellerberg', 'Republican', -3100005),
  ('NJ', 34, '34', 'New Jersey', 'Governor', 'governor', 'Mikie Sherrill', 'Mikie', 'Sherrill', 'Democrat', -3400001),
  ('NJ', 34, '34', 'New Jersey', 'Lieutenant Governor', 'lt_governor', 'Dale Caldwell', 'Dale', 'Caldwell', 'Democrat', -3400002),
  ('OH', 39, '39', 'Ohio', 'Governor', 'governor', 'Mike DeWine', 'Mike', 'DeWine', 'Republican', -3900001),
  ('OH', 39, '39', 'Ohio', 'Lieutenant Governor', 'lt_governor', 'Jim Tressel', 'Jim', 'Tressel', 'Republican', -3900002),
  ('OH', 39, '39', 'Ohio', 'Attorney General', 'attorney_general', 'Andy Wilson', 'Andy', 'Wilson', 'Republican', -3900003),
  ('OH', 39, '39', 'Ohio', 'Secretary of State', 'secretary_of_state', 'Frank LaRose', 'Frank', 'LaRose', 'Republican', -3900004),
  ('OH', 39, '39', 'Ohio', 'Treasurer', 'treasurer', 'Robert Sprague', 'Robert', 'Sprague', 'Republican', -3900005),
  ('PA', 42, '42', 'Pennsylvania', 'Governor', 'governor', 'Josh Shapiro', 'Josh', 'Shapiro', 'Democrat', -4200001),
  ('PA', 42, '42', 'Pennsylvania', 'Lieutenant Governor', 'lt_governor', 'Austin Davis', 'Austin', 'Davis', 'Democrat', -4200002),
  ('PA', 42, '42', 'Pennsylvania', 'Attorney General', 'attorney_general', 'Dave Sunday', 'Dave', 'Sunday', 'Republican', -4200003),
  ('PA', 42, '42', 'Pennsylvania', 'Treasurer', 'treasurer', 'Stacy Garrity', 'Stacy', 'Garrity', 'Republican', -4200004),
  ('WA', 53, '53', 'Washington', 'Governor', 'governor', 'Bob Ferguson', 'Bob', 'Ferguson', 'Democrat', -5300001),
  ('WA', 53, '53', 'Washington', 'Lieutenant Governor', 'lt_governor', 'Denny Heck', 'Denny', 'Heck', 'Democrat', -5300002),
  ('WA', 53, '53', 'Washington', 'Attorney General', 'attorney_general', 'Nick Brown', 'Nick', 'Brown', 'Democrat', -5300003),
  ('WA', 53, '53', 'Washington', 'Secretary of State', 'secretary_of_state', 'Steve Hobbs', 'Steve', 'Hobbs', 'Democrat', -5300004),
  ('WA', 53, '53', 'Washington', 'Treasurer', 'treasurer', 'Mike Pellicciotti', 'Mike', 'Pellicciotti', 'Democrat', -5300005);

-- PREFLIGHT 1 (D-04): every proposed external_id is below the federal US-House band (< -56000).
DO $$ DECLARE v INT; BEGIN
  SELECT count(*) INTO v FROM _seed WHERE ext_id > -56000;
  IF v > 0 THEN RAISE EXCEPTION 'PREFLIGHT 1 FAILED: % external_id(s) within/above the federal band', v; END IF;
END $$;

-- PREFLIGHT 2 (D-04): no proposed external_id is held by a DIFFERENT politician (true collision).
-- Idempotent: on re-run our own seeded politicians match full_name and are exempt; a real collision
-- (ext_id on someone else) still RAISES.
DO $$ DECLARE v TEXT; BEGIN
  SELECT string_agg(s.ext_id::text, ', ') INTO v
  FROM _seed s JOIN essentials.politicians p ON p.external_id = s.ext_id
  WHERE p.full_name <> s.full_name;
  IF v IS NOT NULL THEN RAISE EXCEPTION 'PREFLIGHT 2 FAILED: external_id collision with a different politician: %', v; END IF;
END $$;

-- PREFLIGHT 3 (Pitfall 4 safe): every state has its 'State of <Name>' government row.
DO $$ DECLARE v TEXT; BEGIN
  SELECT string_agg(DISTINCT s.state, ', ') INTO v FROM _seed s
  WHERE NOT EXISTS (SELECT 1 FROM essentials.governments g WHERE g.state = s.state AND g.name = 'State of ' || s.state_name);
  IF v IS NOT NULL THEN RAISE EXCEPTION 'PREFLIGHT 3 FAILED: missing government row for: %', v; END IF;
END $$;

-- 1) One labeled STATE_EXEC district per office ('<State> <Title>', uppercase state, FIPS geo_id).
INSERT INTO essentials.districts (id, district_type, state, geo_id, label, district_id, mtfcc)
SELECT gen_random_uuid(), 'STATE_EXEC', s.state, s.geo_id, s.state_name || ' ' || s.title, '', ''
FROM _seed s
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts d
  WHERE d.district_type='STATE_EXEC' AND d.state=s.state AND d.label = s.state_name || ' ' || s.title
);

-- 2) One chamber per office under the state's government (name=title; slug is GENERATED ALWAYS - excluded).
INSERT INTO essentials.chambers (id, name, name_formal, government_id)
SELECT gen_random_uuid(), s.title, s.title || ' of ' || s.state_name, g.id
FROM _seed s
JOIN essentials.governments g ON g.state=s.state AND g.name='State of ' || s.state_name
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.chambers c WHERE c.government_id=g.id AND c.name=s.title
);

-- 3) Politicians (idempotent on external_id).
INSERT INTO essentials.politicians
  (id, full_name, first_name, last_name, party, is_active, is_appointed, is_vacant, is_incumbent, external_id)
SELECT gen_random_uuid(), s.full_name, s.first_name, s.last_name, s.party, true, false, false, true, s.ext_id
FROM _seed s
ON CONFLICT (external_id) DO NOTHING;

-- 4) Offices linking politician+district+chamber, role_canonical set (guard on district+chamber).
INSERT INTO essentials.offices
  (id, district_id, chamber_id, politician_id, title, representing_state, is_appointed_position, is_vacant, role_canonical)
SELECT gen_random_uuid(), d.id, c.id, p.id, s.title, s.state, false, false, s.role_canonical
FROM _seed s
JOIN essentials.districts d ON d.district_type='STATE_EXEC' AND d.state=s.state AND d.label = s.state_name || ' ' || s.title
JOIN essentials.governments g ON g.state=s.state AND g.name='State of ' || s.state_name
JOIN essentials.chambers c ON c.government_id=g.id AND c.name=s.title
JOIN essentials.politicians p ON p.external_id=s.ext_id
WHERE NOT EXISTS (SELECT 1 FROM essentials.offices o WHERE o.district_id=d.id AND o.chamber_id=c.id);

-- 5) office_id backfill (idempotent).
UPDATE essentials.politicians p SET office_id = o.id
FROM essentials.offices o, _seed s
WHERE o.politician_id=p.id AND p.external_id=s.ext_id AND p.office_id IS NULL;

-- ============================ POST ASSERTIONS ============================
DO $$ DECLARE v_cnt INT; v_bad INT; v_null INT; BEGIN
  SELECT count(*) INTO v_cnt
  FROM essentials.offices o JOIN essentials.districts d ON d.id=o.district_id
  WHERE d.district_type='STATE_EXEC' AND d.state IN ('CO', 'KS', 'MI', 'NE', 'NJ', 'OH', 'PA', 'WA')
    AND o.role_canonical IN ('governor','lt_governor','attorney_general','secretary_of_state','treasurer');
  IF v_cnt <> 35 THEN RAISE EXCEPTION 'POST FAILED: in-scope office count=% (expected 35)', v_cnt; END IF;

  SELECT count(*) INTO v_bad FROM essentials.districts d
  WHERE d.district_type='STATE_EXEC' AND d.state IN ('CO', 'KS', 'MI', 'NE', 'NJ', 'OH', 'PA', 'WA')
    AND (d.state <> upper(d.state) OR d.geo_id IS NULL OR d.geo_id='');
  IF v_bad <> 0 THEN RAISE EXCEPTION 'POST FAILED: % districts with lowercase state or empty geo_id', v_bad; END IF;

  SELECT count(*) INTO v_null FROM essentials.offices o
  JOIN essentials.politicians p ON p.id=o.politician_id, _seed s
  WHERE p.external_id=s.ext_id AND o.role_canonical IS NULL;
  IF v_null <> 0 THEN RAISE EXCEPTION 'POST FAILED: % seeded offices with NULL role_canonical', v_null; END IF;

  RAISE NOTICE 'Migration 982 OK: % in-scope Big-5 offices seeded across 8 states (CO/KS/MI/NE/NJ/OH/PA/WA)', v_cnt;
END $$;

COMMIT;
