-- CA_0005_nc_legislature_incumbents.sql
-- Seats all 170 North Carolina General Assembly members (120 Representatives +
-- 50 Senators).
--
-- SOURCE: ncleg.gov/Members/Biography/<chamber>/<memberId> per seat (identity,
-- district, chamber, portrait), cross-checked against Ballotpedia for the
-- assumed-office date (data/nc-legislature-roster.json, built by
-- build-nc-legislature-roster.mjs). Retrieved 2026-08-22.
--
-- DATE PRECISION is recorded, never fabricated: 151 seats carry a full
-- assumed-office date (start_precision='day'); 18 carry only a year
-- (stored as YYYY-01-01 with start_precision='year' so month/day are explicitly
-- NOT being claimed); 1 seat's start date is genuinely unknown.
--
-- ⚠ THE ONE UNKNOWN-START SEAT: Jake Johnson, NC House District 113. The
-- roster carries assumedOffice: null / assumedPrecision: 'unknown'. Per
-- CLAUDE.md ("don't invent dates") and repo precedent (migration 1459's phase-2
-- backfill, and every later fix that touched an unknown-start row -- 1465,
-- 1546, 1635, 1798, 1814 -- all use this identical shape), this is recorded as
-- term_start NULL / start_precision 'unknown' via a DIRECT INSERT into
-- essentials.office_terms, NOT through essentials.seat_officeholder(): that
-- helper RAISE EXCEPTIONs on a NULL p_term_start by design (confirmed against
-- prod 2026-08-22 -- "seat_officeholder requires a real term_start"). He is
-- still seated: essentials.current_office_holders treats term_start IS NULL /
-- term_end IS NULL as "currently holds", so he counts in the 170-seated gate
-- below exactly like every dated seat.
--
-- how_started: NC's own roster distinguishes this per member --
-- 162 'elected', 8 'appointed' (vacancy replacements). Passed through to
-- p_how_started explicitly; NOT left to seat_officeholder's 'elected' default,
-- which would misclassify the 8 appointees.
--
-- NAME HANDLING: full_name is the roster's exact string, byte-for-byte -- never
-- run through NFD/diacritic-stripping (those helpers exist elsewhere in this
-- repo only for cross-source MATCHING, never for what gets stored). Two names
-- carry non-ASCII characters (Erin Paré, HD 37; Renée A. Price, HD 50) and one
-- carries embedded double quotes around a nickname (Jerry "Alan" Branson, HD
-- 59, stored with 'Alan' in alternate_names -- there is no preferred_name in
-- the INSERT column list; preferred_name is NULL for all 170 rows). This
-- file is written as UTF-8
-- without a BOM; the generator verifies the emitted bytes decode correctly for
-- both accented names before reporting success.
--
-- EXTERNAL IDS: House HD n -> -(3720000+n); Senate SD n -> -(3710000+n),
-- mirroring WA's/CO's scheme off the state FIPS (NC = 37). Verified
-- collision-free against prod 2026-08-22: zero existing rows in
-- -3729999..-3710001.
--
-- IDEMPOTENCY: politicians uses ON CONFLICT (external_id) DO NOTHING (real
-- unique index). Dated seats go through essentials.seat_officeholder(), which
-- is idempotent and closes any predecessor's term rather than silently
-- overlapping it. The one unknown-start seat uses a guarded direct INSERT
-- (NOT EXISTS on office_id) for the same idempotency, since seat_officeholder()
-- cannot accept it.
--
-- Joins key on (geo_id, district_type) together -- geo_id alone is NOT unique
-- across NC's two chambers (50 colliding geo_ids, e.g. '37001' is both HD-1 and
-- SD-1).

BEGIN;

CREATE TEMP TABLE nc_leg_seed (
  geo_id          text,
  district_type   text,
  office_title    text,
  ext_id          bigint,
  full_name       text,
  first_name      text,
  last_name       text,
  middle_name     text,
  name_suffix     text,
  aliases         text[],
  photo_url       text,
  term_start      date,
  start_precision text,
  how_started     text,
  source          text
) ON COMMIT DROP;

INSERT INTO nc_leg_seed VALUES
    ('37001', 'STATE_UPPER', 'Senator', -3710001, 'Bobby Hanig', 'Bobby', 'Hanig', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/435/Low', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/435 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37002', 'STATE_UPPER', 'Senator', -3710002, 'Norman W. Sanderson', 'Norman', 'Sanderson', 'W.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/375/Low', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/375 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37003', 'STATE_UPPER', 'Senator', -3710003, 'Bob Brinson', 'Bob', 'Brinson', NULL, NULL, '{}'::text[], 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Bob_Brinson.jpg', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/448 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37004', 'STATE_UPPER', 'Senator', -3710004, 'Buck Newton', 'Buck', 'Newton', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/443/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/443 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37005', 'STATE_UPPER', 'Senator', -3710005, 'Kandie D. Smith', 'Kandie', 'Smith', 'D.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/447/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/447 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37006', 'STATE_UPPER', 'Senator', -3710006, 'Michael A. Lazzara', 'Michael', 'Lazzara', 'A.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/426/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/426 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37007', 'STATE_UPPER', 'Senator', -3710007, 'Michael V. Lee', 'Michael', 'Lee', 'V.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/387/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/387 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37008', 'STATE_UPPER', 'Senator', -3710008, 'Bill Rabon', 'Bill', 'Rabon', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/303/Low', DATE '2011-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/303 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37009', 'STATE_UPPER', 'Senator', -3710009, 'Brent Jackson', 'Brent', 'Jackson', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/281/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/281 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37010', 'STATE_UPPER', 'Senator', -3710010, 'Benton G. Sawrey', 'Benton', 'Sawrey', 'G.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/445/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/445 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37011', 'STATE_UPPER', 'Senator', -3710011, 'Lisa S. Barnes', 'Lisa', 'Barnes', 'S.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/427/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/427 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37012', 'STATE_UPPER', 'Senator', -3710012, 'Jim Burgin', 'Jim', 'Burgin', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/412/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/412 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37013', 'STATE_UPPER', 'Senator', -3710013, 'Lisa Grafstein', 'Lisa', 'Grafstein', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/439/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/439 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37014', 'STATE_UPPER', 'Senator', -3710014, 'Dan Blue', 'Dan', 'Blue', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/268/Low', DATE '2009-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/S/268 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37015', 'STATE_UPPER', 'Senator', -3710015, 'Jay J. Chaudhuri', 'Jay', 'Chaudhuri', 'J.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/395/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/395 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37016', 'STATE_UPPER', 'Senator', -3710016, 'Gale Adcock', 'Gale', 'Adcock', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/436/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/436 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37017', 'STATE_UPPER', 'Senator', -3710017, 'Sydney Batch', 'Sydney', 'Batch', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/434/Low', DATE '2021-01-13', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/434 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37018', 'STATE_UPPER', 'Senator', -3710018, 'Haseeb Fatmi', 'Haseeb', 'Fatmi', NULL, NULL, '{}'::text[], 'https://ogletree.com/app/uploads/people/haseeb-s-fatmi.jpg', DATE '2026-05-21', 'day', 'appointed', 'https://www.ncleg.gov/Members/Biography/S/1002 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by name_only). Retrieved 2026-08-22.'),
    ('37019', 'STATE_UPPER', 'Senator', -3710019, 'Val Applewhite', 'Val', 'Applewhite', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/440/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/440 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37020', 'STATE_UPPER', 'Senator', -3710020, 'Natalie S. Murdock', 'Natalie', 'Murdock', 'S.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/422/Low', DATE '2020-04-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/422 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37021', 'STATE_UPPER', 'Senator', -3710021, 'Tom McInnis', 'Tom', 'McInnis', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/389/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/389 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37022', 'STATE_UPPER', 'Senator', -3710022, 'Sophia Chitlik', 'Sophia', 'Chitlik', NULL, NULL, '{}'::text[], 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/SophiaChitlik2024.jpg', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/452 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37023', 'STATE_UPPER', 'Senator', -3710023, 'Jonah Garson', 'Jonah', 'Garson', NULL, NULL, '{}'::text[], 'https://images.squarespace-cdn.com/content/v1/5ce70c57184229000120643d/1635110523522-15B7H44X3PRPJSL2DYJH/ParryLaw_PLLC_20211020_1501-2.jpg', DATE '2026-04-10', 'day', 'appointed', 'https://www.ncleg.gov/Members/Biography/S/1001 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by name_only). Retrieved 2026-08-22.'),
    ('37024', 'STATE_UPPER', 'Senator', -3710024, 'Danny Earl Britt, Jr.', 'Danny', 'Britt', 'Earl', 'Jr.', '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/399/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/399 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37025', 'STATE_UPPER', 'Senator', -3710025, 'Amy S. Galey', 'Amy', 'Galey', 'S.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/429/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/429 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37026', 'STATE_UPPER', 'Senator', -3710026, 'Phil Berger', 'Phil', 'Berger', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/64/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/64 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37027', 'STATE_UPPER', 'Senator', -3710027, 'Michael Garrett', 'Michael', 'Garrett', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/414/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/414 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37028', 'STATE_UPPER', 'Senator', -3710028, 'Gladys A. Robinson', 'Gladys', 'Robinson', 'A.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/364/Low', DATE '2011-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/364 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37029', 'STATE_UPPER', 'Senator', -3710029, 'David W. Craven, Jr.', 'David', 'Craven', 'W.', 'Jr.', '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/423/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/423 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37030', 'STATE_UPPER', 'Senator', -3710030, 'Steve Jarvis', 'Steve', 'Jarvis', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/430/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/430 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37031', 'STATE_UPPER', 'Senator', -3710031, 'Dana Jones', 'Dana', 'Jones', NULL, NULL, '{}'::text[], 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/162671.jpg', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/449 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37032', 'STATE_UPPER', 'Senator', -3710032, 'Paul A. Lowe, Jr.', 'Paul', 'Lowe', 'A.', 'Jr.', '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/394/Low', DATE '2015-01-30', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/394 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37033', 'STATE_UPPER', 'Senator', -3710033, 'Carl Ford', 'Carl', 'Ford', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/410/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/410 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37034', 'STATE_UPPER', 'Senator', -3710034, 'Chris Measmer', 'Chris', 'Measmer', NULL, NULL, '{}'::text[], NULL, DATE '2025-04-08', 'day', 'appointed', 'https://www.ncleg.gov/Members/Biography/S/455 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37035', 'STATE_UPPER', 'Senator', -3710035, 'Todd Johnson', 'Todd', 'Johnson', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/406/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/406 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37036', 'STATE_UPPER', 'Senator', -3710036, 'Eddie D. Settle', 'Eddie', 'Settle', 'D.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/446/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/446 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37037', 'STATE_UPPER', 'Senator', -3710037, 'Vickie Sawyer', 'Vickie', 'Sawyer', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/405/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/405 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37038', 'STATE_UPPER', 'Senator', -3710038, 'Mujtaba A. Mohammed', 'Mujtaba', 'Mohammed', 'A.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/417/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/417 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37039', 'STATE_UPPER', 'Senator', -3710039, 'DeAndrea Salvador', 'DeAndrea', 'Salvador', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/431/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/431 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37040', 'STATE_UPPER', 'Senator', -3710040, 'Joyce Waddell', 'Joyce', 'Waddell', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/393/Low', DATE '2015-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/393 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37041', 'STATE_UPPER', 'Senator', -3710041, 'Caleb Theodros', 'Caleb', 'Theodros', NULL, NULL, '{}'::text[], 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcST0VSf38rEGBD-siclt6NuNe1QJ5F0bSq2yeTZaPl6B5jN6UixO_XTlOxWxObcJM0wmNgic4MjyZBFddFBYaj7sg', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/451 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37042', 'STATE_UPPER', 'Senator', -3710042, 'Woodson Bradley', 'Woodson', 'Bradley', NULL, NULL, '{}'::text[], 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Woodson_Bradley_20240820_013503.jpg', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/454 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37043', 'STATE_UPPER', 'Senator', -3710043, 'Brad Overcash', 'Brad', 'Overcash', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/444/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/444 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37044', 'STATE_UPPER', 'Senator', -3710044, 'W. Ted Alexander', 'W.', 'Alexander', 'Ted', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/416/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/416 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37045', 'STATE_UPPER', 'Senator', -3710045, 'Mark Hollo', 'Mark', 'Hollo', NULL, NULL, '{}'::text[], 'http://www.ncga.state.nc.us/House/pictures/hiRes/619.jpg', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/450 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37046', 'STATE_UPPER', 'Senator', -3710046, 'Warren Daniel', 'Warren', 'Daniel', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/295/Low', DATE '2013-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/295 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37047', 'STATE_UPPER', 'Senator', -3710047, 'Ralph Hise', 'Ralph', 'Hise', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/298/Low', DATE '2011-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/298 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37048', 'STATE_UPPER', 'Senator', -3710048, 'Timothy D. Moffitt', 'Timothy', 'Moffitt', 'D.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/438/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/438 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37049', 'STATE_UPPER', 'Senator', -3710049, 'Julie Mayfield', 'Julie', 'Mayfield', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/432/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/432 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37050', 'STATE_UPPER', 'Senator', -3710050, 'Kevin Corbin', 'Kevin', 'Corbin', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/S/433/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/S/433 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37001', 'STATE_LOWER', 'Representative', -3720001, 'Edward C. Goodwin', 'Edward', 'Goodwin', 'C.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/744/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/744 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37002', 'STATE_LOWER', 'Representative', -3720002, 'B. Ray Jeffers', 'B.', 'Jeffers', 'Ray', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/805/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/805 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37003', 'STATE_LOWER', 'Representative', -3720003, 'Steve Tyson', 'Steve', 'Tyson', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/774/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/774 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37004', 'STATE_LOWER', 'Representative', -3720004, 'Jimmy Dixon', 'Jimmy', 'Dixon', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/613/Low', DATE '2011-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/613 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37005', 'STATE_LOWER', 'Representative', -3720005, 'Bill Ward', 'Bill', 'Ward', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/816/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/816 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37006', 'STATE_LOWER', 'Representative', -3720006, 'Joseph Pike', 'Joseph', 'Pike', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/808/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/808 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37007', 'STATE_LOWER', 'Representative', -3720007, 'Matthew Winslow', 'Matthew', 'Winslow', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/776/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/776 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37008', 'STATE_LOWER', 'Representative', -3720008, 'Gloristine Brown', 'Gloristine', 'Brown', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/794/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/794 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37009', 'STATE_LOWER', 'Representative', -3720009, 'Timothy Reeder, MD', 'Timothy', 'Reeder', NULL, 'MD', '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/811/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/811 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37010', 'STATE_LOWER', 'Representative', -3720010, 'John R. Bell, IV', 'John', 'Bell', 'R.', 'IV', '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/661/Low', DATE '2013-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/661 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37011', 'STATE_LOWER', 'Representative', -3720011, 'Allison A. Dahle', 'Allison', 'Dahle', 'A.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/740/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/740 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37012', 'STATE_LOWER', 'Representative', -3720012, 'Chris Humphrey', 'Chris', 'Humphrey', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/747/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/747 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37013', 'STATE_LOWER', 'Representative', -3720013, 'Celeste C. Cairns', 'Celeste', 'Cairns', 'C.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/797/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/797 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37014', 'STATE_LOWER', 'Representative', -3720014, 'Wyatt Gable', 'Wyatt', 'Gable', NULL, NULL, '{}'::text[], 'https://images.squarespace-cdn.com/content/v1/6555362b58434b0824932281/15739355-3436-4410-b02c-ed4d63322f69/untitled-7317.jpg', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/837 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37015', 'STATE_LOWER', 'Representative', -3720015, 'Phil Shepard', 'Phil', 'Shepard', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/628/Low', DATE '2011-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/628 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37016', 'STATE_LOWER', 'Representative', -3720016, 'Carson Smith', 'Carson', 'Smith', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/755/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/755 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37017', 'STATE_LOWER', 'Representative', -3720017, 'Frank Iler', 'Frank', 'Iler', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/598/Low', DATE '2009-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/598 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37018', 'STATE_LOWER', 'Representative', -3720018, 'Deb Butler', 'Deb', 'Butler', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/730/Low', DATE '2017-02-06', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/730 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37019', 'STATE_LOWER', 'Representative', -3720019, 'Charles W. Miller', 'Charles', 'Miller', 'W.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/778/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/778 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37020', 'STATE_LOWER', 'Representative', -3720020, 'Ted Davis, Jr.', 'Ted', 'Davis', NULL, 'Jr.', '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/637/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/637 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37021', 'STATE_LOWER', 'Representative', -3720021, 'Ya Liu', 'Ya', 'Liu', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/806/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/806 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37022', 'STATE_LOWER', 'Representative', -3720022, 'William D. Brisson', 'William', 'Brisson', 'D.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/558/Low', DATE '2007-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/558 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37023', 'STATE_LOWER', 'Representative', -3720023, 'Shelly Willingham', 'Shelly', 'Willingham', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/700/Low', DATE '2015-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/700 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37024', 'STATE_LOWER', 'Representative', -3720024, 'Dante Pittman', 'Dante', 'Pittman', NULL, NULL, '{}'::text[], 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/DantePittman2024.JPG', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/839 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37025', 'STATE_LOWER', 'Representative', -3720025, 'Allen Chesser', 'Allen', 'Chesser', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/799/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/799 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37026', 'STATE_LOWER', 'Representative', -3720026, 'Donna McDowell White', 'Donna', 'White', 'McDowell', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/728/Low', DATE '2017-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/728 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37027', 'STATE_LOWER', 'Representative', -3720027, 'Rodney D. Pierce', 'Rodney', 'Pierce', 'D.', NULL, '{}'::text[], 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/RodneyPierce2024.jpeg', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/838 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37028', 'STATE_LOWER', 'Representative', -3720028, 'Larry C. Strickland', 'Larry', 'Strickland', 'C.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/727/Low', DATE '2017-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/727 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37029', 'STATE_LOWER', 'Representative', -3720029, 'Vernetta Alston', 'Vernetta', 'Alston', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/765/Low', DATE '2020-04-13', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/765 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37030', 'STATE_LOWER', 'Representative', -3720030, 'Marcia Morey', 'Marcia', 'Morey', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/732/Low', DATE '2017-04-05', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/732 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37031', 'STATE_LOWER', 'Representative', -3720031, 'Zack Hawkins', 'Zack', 'Hawkins', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/742/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/742 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37032', 'STATE_LOWER', 'Representative', -3720032, 'Bryan Cohn', 'Bryan', 'Cohn', NULL, NULL, '{}'::text[], 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Bryan__Cohn__20240808_093541.jpg', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/827 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37033', 'STATE_LOWER', 'Representative', -3720033, 'Monika Johnson-Hostler', 'Monika', 'Johnson-Hostler', NULL, NULL, '{}'::text[], 'https://www.uncfsu.edu/assets/Images/Student_Stories/Monika-Hostler.jpg', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/834 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37034', 'STATE_LOWER', 'Representative', -3720034, 'Tim Longest', 'Tim', 'Longest', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/818/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/818 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37035', 'STATE_LOWER', 'Representative', -3720035, 'Mike Schietzelt', 'Mike', 'Schietzelt', NULL, NULL, '{}'::text[], 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/MikeSchietzelt2024.jpg', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/840 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37036', 'STATE_LOWER', 'Representative', -3720036, 'Julie von Haefen', 'Julie', 'von Haefen', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/758/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/758 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37037', 'STATE_LOWER', 'Representative', -3720037, 'Erin Paré', 'Erin', 'Paré', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/770/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/770 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37038', 'STATE_LOWER', 'Representative', -3720038, 'Abe Jones', 'Abe', 'Jones', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/780/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/780 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37039', 'STATE_LOWER', 'Representative', -3720039, 'James Roberson', 'James', 'Roberson', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/786/Low', DATE '2021-01-13', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/786 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37040', 'STATE_LOWER', 'Representative', -3720040, 'Phil Rubin', 'Phil', 'Rubin', NULL, NULL, '{}'::text[], NULL, DATE '2025-01-29', 'day', 'appointed', 'https://www.ncleg.gov/Members/Biography/H/844 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37041', 'STATE_LOWER', 'Representative', -3720041, 'Maria Cervania', 'Maria', 'Cervania', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/798/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/798 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37042', 'STATE_LOWER', 'Representative', -3720042, 'Mike Colvin', 'Mike', 'Colvin', NULL, NULL, '{}'::text[], 'https://votemikecolvin.com/wp-content/uploads/2024/01/untitled-1024x1024.jpg', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/831 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37043', 'STATE_LOWER', 'Representative', -3720043, 'Diane Wheatley', 'Diane', 'Wheatley', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/785/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/785 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37044', 'STATE_LOWER', 'Representative', -3720044, 'Charles Smith', 'Charles', 'Smith', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/813/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/813 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37045', 'STATE_LOWER', 'Representative', -3720045, 'Frances Jackson, PhD', 'Frances', 'Jackson', NULL, 'PhD', '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/803/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/803 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37046', 'STATE_LOWER', 'Representative', -3720046, 'Brenden H. Jones', 'Brenden', 'Jones', 'H.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/723/Low', DATE '2017-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/723 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37047', 'STATE_LOWER', 'Representative', -3720047, 'John L. Lowery', 'John', 'Lowery', 'L.', NULL, '{}'::text[], NULL, DATE '2025-10-13', 'day', 'appointed', 'https://www.ncleg.gov/Members/Biography/H/1001 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37048', 'STATE_LOWER', 'Representative', -3720048, 'Garland E. Pierce', 'Garland', 'Pierce', 'E.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/497/Low', DATE '2005-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/497 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37049', 'STATE_LOWER', 'Representative', -3720049, 'Cynthia Ball', 'Cynthia', 'Ball', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/711/Low', DATE '2017-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/711 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37050', 'STATE_LOWER', 'Representative', -3720050, 'Renée A. Price', 'Renée', 'Price', 'A.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/810/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/810 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37051', 'STATE_LOWER', 'Representative', -3720051, 'John Sauls', 'John', 'Sauls', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/393/Low', DATE '2017-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/393 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37052', 'STATE_LOWER', 'Representative', -3720052, 'Ben T. Moss, Jr.', 'Ben', 'Moss', 'T.', 'Jr.', '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/784/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/784 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37053', 'STATE_LOWER', 'Representative', -3720053, 'Howard Penny, Jr.', 'Howard', 'Penny', NULL, 'Jr.', '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/768/Low', DATE '2020-09-17', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/768 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37054', 'STATE_LOWER', 'Representative', -3720054, 'Robert T. Reives, II', 'Robert', 'Reives', 'T.', 'II', '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/684/Low', DATE '2014-01-29', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/684 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37055', 'STATE_LOWER', 'Representative', -3720055, 'Mark Brody', 'Mark', 'Brody', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/663/Low', DATE '2013-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/663 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37056', 'STATE_LOWER', 'Representative', -3720056, 'Allen Buansi', 'Allen', 'Buansi', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/790/Low', DATE '2022-06-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/790 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37057', 'STATE_LOWER', 'Representative', -3720057, 'Tracy Clark', 'Tracy', 'Clark', NULL, NULL, '{}'::text[], 'https://storage.googleapis.com/enview-public-general/legislative-people-photos/148017.jpg', DATE '2024-08-06', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/822 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37058', 'STATE_LOWER', 'Representative', -3720058, 'Amos L. Quick, III', 'Amos', 'Quick', 'L.', 'III', '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/725/Low', DATE '2017-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/725 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37059', 'STATE_LOWER', 'Representative', -3720059, 'Jerry "Alan" Branson', 'Jerry', 'Branson', NULL, NULL, ARRAY['Alan']::text[], 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/alan_branson.jpg', DATE '2024-04-24', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/821 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37060', 'STATE_LOWER', 'Representative', -3720060, 'Amanda P. Cook', 'Amanda', 'Cook', 'P.', NULL, '{}'::text[], NULL, DATE '2025-11-18', 'day', 'appointed', 'https://www.ncleg.gov/Members/Biography/H/1002 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37061', 'STATE_LOWER', 'Representative', -3720061, 'Pricey Harrison', 'Pricey', 'Harrison', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/504/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/504 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37062', 'STATE_LOWER', 'Representative', -3720062, 'John M. Blust', 'John', 'Blust', 'M.', NULL, '{}'::text[], 'https://storage.googleapis.com/enview-public-general/legislative-people-photos/21657.jpg', DATE '2024-10-09', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/234 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37063', 'STATE_LOWER', 'Representative', -3720063, 'Stephen M. Ross', 'Stephen', 'Ross', 'M.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/812/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/812 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37064', 'STATE_LOWER', 'Representative', -3720064, 'Dennis Riddell', 'Dennis', 'Riddell', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/665/Low', DATE '2013-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/665 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37065', 'STATE_LOWER', 'Representative', -3720065, 'A. Reece Pyrtle, Jr.', 'A.', 'Pyrtle', 'Reece', 'Jr.', '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/787/Low', DATE '2021-08-18', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/787 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37066', 'STATE_LOWER', 'Representative', -3720066, 'Sarah Crawford', 'Sarah', 'Crawford', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/800/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/800 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37067', 'STATE_LOWER', 'Representative', -3720067, 'Cody Huneycutt', 'Cody', 'Huneycutt', NULL, NULL, '{}'::text[], 'https://assets.civicengine.com/uploads/candidate/headshot/797923/797923.jpg', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/833 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37068', 'STATE_LOWER', 'Representative', -3720068, 'David Willis', 'David', 'Willis', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/779/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/779 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37069', 'STATE_LOWER', 'Representative', -3720069, 'Dean Arp', 'Dean', 'Arp', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/640/Low', DATE '2013-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/640 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37070', 'STATE_LOWER', 'Representative', -3720070, 'Brian Biggs', 'Brian', 'Biggs', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/793/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/793 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37071', 'STATE_LOWER', 'Representative', -3720071, 'Kanika Brown', 'Kanika', 'Brown', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/795/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/795 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37072', 'STATE_LOWER', 'Representative', -3720072, 'Amber M. Baker', 'Amber', 'Baker', 'M.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/782/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/782 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37073', 'STATE_LOWER', 'Representative', -3720073, 'Jonathan L. Almond', 'Jonathan', 'Almond', 'L.', NULL, '{}'::text[], 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jonathan_Almond_20241029_031016.png', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/843 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37074', 'STATE_LOWER', 'Representative', -3720074, 'Jeff Zenger', 'Jeff', 'Zenger', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/775/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/775 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37075', 'STATE_LOWER', 'Representative', -3720075, 'Donny Lambeth', 'Donny', 'Lambeth', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/646/Low', DATE '2013-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/646 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37076', 'STATE_LOWER', 'Representative', -3720076, 'Harry Warren', 'Harry', 'Warren', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/630/Low', DATE '2019-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/630 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37077', 'STATE_LOWER', 'Representative', -3720077, 'Julia C. Howard', 'Julia', 'Howard', 'C.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/53/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/53 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37078', 'STATE_LOWER', 'Representative', -3720078, 'Neal Jackson', 'Neal', 'Jackson', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/804/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/804 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37079', 'STATE_LOWER', 'Representative', -3720079, 'Keith Kidwell', 'Keith', 'Kidwell', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/749/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/749 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37080', 'STATE_LOWER', 'Representative', -3720080, 'Sam Watford', 'Sam', 'Watford', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/687/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/687 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37081', 'STATE_LOWER', 'Representative', -3720081, 'Larry W. Potts', 'Larry', 'Potts', 'W.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/724/Low', DATE '2017-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/724 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37082', 'STATE_LOWER', 'Representative', -3720082, 'Brian Echevarria', 'Brian', 'Echevarria', NULL, NULL, '{}'::text[], 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Brian_Echiveria_.jpg', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/828 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37083', 'STATE_LOWER', 'Representative', -3720083, 'Grant L. Campbell, MD', 'Grant', 'Campbell', 'L.', 'MD', '{}'::text[], 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/campbellgrant.jpg', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/830 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37084', 'STATE_LOWER', 'Representative', -3720084, 'Jeffrey C. McNeely', 'Jeffrey', 'McNeely', 'C.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/761/Low', DATE '2019-07-05', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/761 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37085', 'STATE_LOWER', 'Representative', -3720085, 'Dudley Greene', 'Dudley', 'Greene', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/777/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/777 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37086', 'STATE_LOWER', 'Representative', -3720086, 'Hugh Blackwell', 'Hugh', 'Blackwell', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/580/Low', DATE '2009-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/580 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37087', 'STATE_LOWER', 'Representative', -3720087, 'Destin Hall', 'Destin', 'Hall', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/719/Low', DATE '2017-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/719 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37088', 'STATE_LOWER', 'Representative', -3720088, 'Mary Belk', 'Mary', 'Belk', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/713/Low', DATE '2017-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/713 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37089', 'STATE_LOWER', 'Representative', -3720089, 'Mitchell S. Setzer', 'Mitchell', 'Setzer', 'S.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/149/Low', DATE '1999-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/149 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37090', 'STATE_LOWER', 'Representative', -3720090, 'Dan Kiger', 'Dan', 'Kiger', NULL, NULL, '{}'::text[], NULL, DATE '2026-06-23', 'day', 'appointed', 'https://www.ncleg.gov/Members/Biography/H/1004 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by name_only). Retrieved 2026-08-22.'),
    ('37091', 'STATE_LOWER', 'Representative', -3720091, 'Kyle Hall', 'Kyle', 'Hall', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/704/Low', DATE '2015-11-23', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/704 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37092', 'STATE_LOWER', 'Representative', -3720092, 'Terry M. Brown Jr.', 'Terry', 'Jr.', 'M. Brown', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/783/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/783 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37093', 'STATE_LOWER', 'Representative', -3720093, 'Ray Pickett', 'Ray', 'Pickett', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/772/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/772 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37094', 'STATE_LOWER', 'Representative', -3720094, 'Blair Eddins', 'Blair', 'Eddins', NULL, NULL, '{}'::text[], 'https://storage.googleapis.com/enview-public-general/legislative-people-photos/151642.jpg', DATE '2024-10-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/825 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37095', 'STATE_LOWER', 'Representative', -3720095, 'Todd Carver', 'Todd', 'Carver', NULL, NULL, '{}'::text[], 'https://www.iredellfreenews.com/wp-content/uploads/2023/12/Todd-Carver.jpg.webp', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/842 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37096', 'STATE_LOWER', 'Representative', -3720096, 'Jay Adams', 'Jay', 'Adams', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/697/Low', DATE '2015-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/697 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37097', 'STATE_LOWER', 'Representative', -3720097, 'Heather H. Rhyne', 'Heather', 'Rhyne', 'H.', NULL, '{}'::text[], 'https://storage.googleapis.com/enview-public-general/legislative-people-photos/148921.jpg', DATE '2024-08-19', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/823 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37098', 'STATE_LOWER', 'Representative', -3720098, 'Beth Helfrich', 'Beth', 'Helfrich', NULL, NULL, '{}'::text[], 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Beth_Gardner_Helfrich.jpeg', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/832 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37099', 'STATE_LOWER', 'Representative', -3720099, 'Nasif Majeed', 'Nasif', 'Majeed', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/752/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/752 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37100', 'STATE_LOWER', 'Representative', -3720100, 'Julia Greenfield', 'Julia', 'Greenfield', NULL, NULL, '{}'::text[], 'https://greenvoterguidenc.org/wp-content/uploads/Julia-Greenfield-square-400x400.png', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/829 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37101', 'STATE_LOWER', 'Representative', -3720101, 'Carolyn G. Logan', 'Carolyn', 'Logan', 'G.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/750/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/750 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37102', 'STATE_LOWER', 'Representative', -3720102, 'Becky Carney', 'Becky', 'Carney', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/322/Low', DATE '2003-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/322 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37103', 'STATE_LOWER', 'Representative', -3720103, 'Laura Budd', 'Laura', 'Budd', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/796/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/796 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37104', 'STATE_LOWER', 'Representative', -3720104, 'Brandon Lofton', 'Brandon', 'Lofton', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/751/Low', DATE '2019-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/751 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37105', 'STATE_LOWER', 'Representative', -3720105, 'Tricia Ann Cotham', 'Tricia', 'Cotham', 'Ann', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/817/Low', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/817 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37106', 'STATE_LOWER', 'Representative', -3720106, 'Carla D. Cunningham', 'Carla', 'Cunningham', 'D.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/642/Low', DATE '2013-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/642 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37107', 'STATE_LOWER', 'Representative', -3720107, 'Aisha O. Dew', 'Aisha', 'Dew', 'O.', NULL, '{}'::text[], 'https://static.wixstatic.com/media/382708_03a01c002bae45c2a4dd4b665892e242~mv2.png/v1/fill/w_369,h_369,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/aisha%20dew%20updated%20headshot.png', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/836 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37108', 'STATE_LOWER', 'Representative', -3720108, 'John A. Torbett', 'John', 'Torbett', 'A.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/606/Low', DATE '2010-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/606 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37109', 'STATE_LOWER', 'Representative', -3720109, 'Donnie Loftis', 'Donnie', 'Loftis', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/788/Low', DATE '2021-11-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/788 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37110', 'STATE_LOWER', 'Representative', -3720110, 'Kelly E. Hastings', 'Kelly', 'Hastings', 'E.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/618/Low', DATE '2011-01-01', 'year', 'elected', 'https://www.ncleg.gov/Members/Biography/H/618 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37111', 'STATE_LOWER', 'Representative', -3720111, 'Paul Scott', 'Paul', 'Scott', NULL, NULL, '{}'::text[], 'https://static.wixstatic.com/media/a254ce_1422fda1afc540a697d4c59e20275ee8~mv2.png/v1/fill/w_626,h_1003,al_c,q_90,usm_0.66_1.00_0.01,enc_auto/a254ce_1422fda1afc540a697d4c59e20275ee8~mv2.png', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/841 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37112', 'STATE_LOWER', 'Representative', -3720112, 'Jordan Lopez', 'Jordan', 'Lopez', NULL, NULL, '{}'::text[], 'https://lopez4nc.com/wp-content/uploads/2023/12/FAV1127_LOPEZ_-121.webp', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/835 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37113', 'STATE_LOWER', 'Representative', -3720113, 'Jake Johnson', 'Jake', 'Johnson', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/762/Low', NULL, 'unknown', 'elected', 'https://www.ncleg.gov/Members/Biography/H/762 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by name_only). Retrieved 2026-08-22.'),
    ('37114', 'STATE_LOWER', 'Representative', -3720114, 'Eric Ager', 'Eric', 'Ager', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/819/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/819 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37115', 'STATE_LOWER', 'Representative', -3720115, 'Lindsey Prather', 'Lindsey', 'Prather', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/809/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/809 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37116', 'STATE_LOWER', 'Representative', -3720116, 'Brian Turner', 'Brian', 'Turner', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/696/Low', DATE '2025-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/696 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37117', 'STATE_LOWER', 'Representative', -3720117, 'Jennifer Balkcom', 'Jennifer', 'Balkcom', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/820/Low', DATE '2023-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/820 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37118', 'STATE_LOWER', 'Representative', -3720118, 'Mark Pless', 'Mark', 'Pless', NULL, NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/773/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/773 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.'),
    ('37119', 'STATE_LOWER', 'Representative', -3720119, 'Anna Ferguson', 'Anna', 'Ferguson', NULL, NULL, '{}'::text[], NULL, DATE '2026-04-16', 'day', 'appointed', 'https://www.ncleg.gov/Members/Biography/H/1003 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by name_only). Retrieved 2026-08-22.'),
    ('37120', 'STATE_LOWER', 'Representative', -3720120, 'Karl E. Gillespie', 'Karl', 'Gillespie', 'E.', NULL, '{}'::text[], 'https://www.ncleg.gov/Members/MemberImage/H/771/Low', DATE '2021-01-01', 'day', 'elected', 'https://www.ncleg.gov/Members/Biography/H/771 (ncleg.gov Member Biography — identity, district, chamber); assumed-office date cross-checked against Ballotpedia (matched by member_id). Retrieved 2026-08-22.');

-- Guard the payload itself before it touches anything.
DO $$
DECLARE v_n int; v_dup int;
BEGIN
  SELECT count(*) INTO v_n FROM nc_leg_seed;
  IF v_n <> 170 THEN RAISE EXCEPTION 'seed payload: expected 170 rows, got %', v_n; END IF;
  SELECT count(*) INTO v_dup FROM (SELECT ext_id FROM nc_leg_seed GROUP BY ext_id HAVING count(*) > 1) x;
  IF v_dup <> 0 THEN RAISE EXCEPTION 'seed payload: % duplicate external_id(s)', v_dup; END IF;
  SELECT count(*) INTO v_dup FROM (SELECT geo_id, district_type FROM nc_leg_seed GROUP BY geo_id, district_type HAVING count(*) > 1) x;
  IF v_dup <> 0 THEN RAISE EXCEPTION 'seed payload: % duplicate (geo_id, district_type) key(s)', v_dup; END IF;
END $$;

-- ─── Politicians ─────────────────────────────────────────────────────────────

INSERT INTO essentials.politicians
  (external_id, full_name, first_name, last_name, middle_initial, name_suffix,
   alternate_names, photo_origin_url, is_incumbent, is_active, data_source)
SELECT s.ext_id, s.full_name, s.first_name, s.last_name, s.middle_name, s.name_suffix,
       s.aliases, s.photo_url, true, true, s.source
FROM nc_leg_seed s
ON CONFLICT (external_id) DO NOTHING;

-- ─── Occupancy: dated seats, via the helper ──────────────────────────────────
-- seat_officeholder() closes any predecessor's open-ended term before
-- inserting, which is the whole reason it exists.

DO $$
DECLARE
  r record;
  v_seated int := 0;
BEGIN
  FOR r IN
    SELECT s.term_start, s.start_precision, s.how_started, s.source,
           o.id AS office_id, p.id AS politician_id
    FROM nc_leg_seed s
    JOIN essentials.politicians p ON p.external_id = s.ext_id
    JOIN essentials.districts d
      ON d.geo_id = s.geo_id
     AND d.district_type = s.district_type
     AND lower(d.state) = 'nc'
    JOIN essentials.offices o
      ON o.district_id = d.id AND o.title = s.office_title
    WHERE s.term_start IS NOT NULL
      AND NOT EXISTS (
        SELECT 1 FROM essentials.office_terms t
        WHERE t.office_id = o.id AND t.politician_id = p.id
      )
  LOOP
    PERFORM essentials.seat_officeholder(
      r.office_id, r.politician_id, r.term_start,
      r.source,
      r.how_started,
      r.start_precision
    );
    v_seated := v_seated + 1;
  END LOOP;
  RAISE NOTICE 'seated % NC legislator(s) with a known start date', v_seated;
END $$;

-- ─── Occupancy: the one unknown-start seat, direct insert ────────────────────
-- Jake Johnson, HD 113. seat_officeholder() refuses a NULL p_term_start by
-- design -- this is the identical shape the 1459 phase-2 backfill and its
-- later corrections (1465, 1546, 1635, 1798, 1814) all use for a genuinely
-- unknown start: term_start NULL, term_end NULL, start_precision 'unknown'.
-- The office_terms_no_overlap exclusion constraint permits this because it is
-- the only term ever written for this office.

INSERT INTO essentials.office_terms (office_id, politician_id, term_start, term_end, start_precision, how_started, source)
SELECT o.id, p.id, NULL, NULL, s.start_precision, s.how_started, s.source
FROM nc_leg_seed s
JOIN essentials.politicians p ON p.external_id = s.ext_id
JOIN essentials.districts d
  ON d.geo_id = s.geo_id
 AND d.district_type = s.district_type
 AND lower(d.state) = 'nc'
JOIN essentials.offices o
  ON o.district_id = d.id AND o.title = s.office_title
WHERE s.term_start IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM essentials.office_terms t WHERE t.office_id = o.id
  );

-- ─── Post-verify gate ────────────────────────────────────────────────────────
DO $$
DECLARE
  v_pol int; v_seated int; v_appointed int;
BEGIN
  SELECT count(*) INTO v_pol
  FROM essentials.politicians WHERE external_id BETWEEN -3729999 AND -3710001;
  IF v_pol <> 170 THEN RAISE EXCEPTION 'CA_0005: NC legislators inserted: expected 170, got %', v_pol; END IF;

  -- count(och.politician_id), NOT count(*): office_current_holder LEFT JOINs
  -- from offices, so a vacancy is a NULL politician_id, never an absent row.
  -- count(*) would pass vacuously with every seat empty.
  SELECT count(och.politician_id) INTO v_seated
    FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
    LEFT JOIN essentials.office_current_holder och ON och.office_id = o.id
   WHERE lower(d.state) = 'nc' AND d.district_type IN ('STATE_LOWER','STATE_UPPER');
  IF v_seated <> 170 THEN RAISE EXCEPTION 'CA_0005: expected 170 seated NC legislators, found %', v_seated; END IF;

  SELECT count(*) INTO v_appointed
    FROM essentials.office_terms t
    JOIN essentials.offices o ON o.id = t.office_id
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE lower(d.state) = 'nc' AND d.district_type IN ('STATE_LOWER','STATE_UPPER')
     AND t.how_started = 'appointed';
  IF v_appointed <> 8 THEN RAISE EXCEPTION 'CA_0005: expected 8 NC legislative terms with how_started=appointed, found %', v_appointed; END IF;
END $$;

COMMIT;
