-- CA_0010_asheville_buncombe_incumbents.sql
-- NC deep-seed program, WAVE 3 (incumbents). Companion: CA_0009 (structure).
--
-- Inserts 17 politicians and seats each one, via essentials.seat_officeholder().
--
-- Roster: data/seed-buncombe-asheville-2026/ROSTERS.md
-- Generated by: scripts/gen-buncombe-asheville-migrations.mjs
--
-- ─────────────────────────────────────────────────────────────────────────────
-- 🔴 term_start IS THE DAY THIS PERSON BEGAN HOLDING THIS SEAT, and Buncombe's
-- published year is TERM EXPIRY. Reading it as "elected four years earlier" is
-- wrong for FIVE of these 17 people, because this board fills vacancies by
-- appointment repeatedly:
--
--   Whitesides  naive 2022 -> appointed 2016-12 (filled Newman's seat)
--   Wells       naive 2024 -> elected   2020-12
--   Sloan       naive 2024 -> elected   2020-12
--   Ball        naive 2022 -> appointed 2025-01 (filled Edwards' seat; the naive
--                                                read credits him with HER election)
--   Christy     naive 2022 -> appointed 2023    (on Cogburn's retirement)
--
-- Asheville has the mirror defect: its council page's "Term:" start is service
-- on the BODY, so the Mayor row reads December 2009 -- Manheimer's COUNCIL
-- start. She became Mayor 2013-12-10.
--
-- how_started: 13 'elected', 4 'appointed' (Mosley, Whitesides, Ball, Christy).
-- Passed to p_how_started EXPLICITLY -- never left to seat_officeholder()'s
-- 'elected' default, which would misclassify all 4.
--
-- start_precision is per-source, not uniform: 'day' for Manheimer alone (a
-- documented swearing-in), 'month' for the 13 whose sources publish month and
-- year, 'year' for the three row officers. Where precision is 'year' the date is
-- written YYYY-01-01 and carries NO claim about the month -- the flag is what is
-- load-bearing.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- IDENTITY. Guarded on external_id -- band -(3740000+n), n=1..17 -- never on
-- full_name. Verified 2026-08-23: all 17 names return ZERO rows in prod, and
-- the band -3740001..-3740017 is empty.
--
-- This is wave 2's Mike Lee lesson: prod holds three distinct people named some
-- variant of Michael Lee, and a bare-name guard would have inserted nothing,
-- passed a 1:1 assertion, and seated a sitting US Senator on the Durham County
-- Commission. A surname sweep for this wave surfaced three real but distinct
-- people -- Chaney Mosley, George Whitesides, Steve Christy -- plus FEC ALLCAPS
-- committee junk matching 'CHRISTY'. All separable by FIRST name.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- FOUR GROUPS CONTAIN MORE THAN ONE IDENTICALLY-TITLED OFFICE:
--   6 x 'Council Member'            on 3702140
--   2 x 'Commissioner, District 1'  on buncombe-nc-commissioner-district-1
--   2 x 'Commissioner, District 2'  on buncombe-nc-commissioner-district-2
--   2 x 'Commissioner, District 3'  on buncombe-nc-commissioner-district-3
--
-- A title join cannot resolve one person to one office row inside those groups,
-- so the pairing is CA_0007's deterministic row_number() bijection, partitioned
-- by (geo_id, district_type, office_title): offices ORDER BY o.id (stable once
-- CA_0009 creates them), roster ORDER BY ext_id (fixed by ROSTERS.md). CA_0009's
-- gate asserts the exact office count per group and the guard below asserts the
-- exact roster count per group, so both sides yield 1..N with no gaps -- a
-- bijection, and idempotent on re-run.
--
-- 🔴 Same caveat as CA_0007: this is silent about OUT-OF-BAND deletion. If an
-- office row is deleted outside these two migrations and CA_0009's top-up
-- regenerates it, the replacement gets a new UUID that may sort to a different
-- rank. Within a group the seats are interchangeable, so no voter-facing label
-- goes wrong -- but seat_officeholder() would close and reopen terms against the
-- wrong predecessor, fabricating a term_end on a real person's record.
--
-- Joins key on (geo_id, district_type) together -- '37021' is NOT unique across
-- Buncombe County (COUNTY), Senate District 21 (STATE_UPPER) and House District
-- 21 (STATE_LOWER).

BEGIN;

CREATE TEMP TABLE wave3_seed (
  geo_id          text,
  district_type   text,
  office_title    text,
  ext_id          bigint,
  full_name       text,
  first_name      text,
  last_name       text,
  middle_initial  text,
  name_suffix     text,
  aliases         text[],
  term_start      date,
  start_precision text,
  how_started     text,
  source          text
) ON COMMIT DROP;

INSERT INTO wave3_seed VALUES
  ('3702140', 'LOCAL', 'Mayor', -3740001, 'Esther E. Manheimer', 'Esther', 'Manheimer', 'E', NULL, ARRAY[]::text[], '2013-12-10'::date, 'day', 'elected', 'ashevillenc.gov/government/meet-city-council/ (retrieved 2026-08-23)'),
  ('3702140', 'LOCAL', 'Council Member', -3740002, 'S. Antanette Mosley', 'S. Antanette', 'Mosley', NULL, NULL, ARRAY['Antanette']::text[], '2020-09-01'::date, 'month', 'appointed', 'ashevillenc.gov/government/meet-city-council/ (retrieved 2026-08-23)'),
  ('3702140', 'LOCAL', 'Council Member', -3740003, 'Sheneika Smith', 'Sheneika', 'Smith', NULL, NULL, ARRAY[]::text[], '2017-12-01'::date, 'month', 'elected', 'ashevillenc.gov/government/meet-city-council/ (retrieved 2026-08-23)'),
  ('3702140', 'LOCAL', 'Council Member', -3740004, 'Kim Roney', 'Kim', 'Roney', NULL, NULL, ARRAY[]::text[], '2020-12-01'::date, 'month', 'elected', 'ashevillenc.gov/government/meet-city-council/ (retrieved 2026-08-23)'),
  ('3702140', 'LOCAL', 'Council Member', -3740005, 'Sage Turner', 'Sage', 'Turner', NULL, NULL, ARRAY[]::text[], '2020-12-01'::date, 'month', 'elected', 'ashevillenc.gov/government/meet-city-council/ (retrieved 2026-08-23)'),
  ('3702140', 'LOCAL', 'Council Member', -3740006, 'Maggie Ullman', 'Maggie', 'Ullman', NULL, NULL, ARRAY[]::text[], '2022-12-01'::date, 'month', 'elected', 'ashevillenc.gov/government/meet-city-council/ (retrieved 2026-08-23)'),
  ('3702140', 'LOCAL', 'Council Member', -3740007, 'Bo Hess', 'Bo', 'Hess', NULL, NULL, ARRAY['Roberto']::text[], '2024-12-01'::date, 'month', 'elected', 'ashevillenc.gov/government/meet-city-council/ (retrieved 2026-08-23)'),
  ('37021', 'COUNTY', 'Chair, Board of Commissioners', -3740008, 'Amanda Edwards', 'Amanda', 'Edwards', NULL, NULL, ARRAY[]::text[], '2024-12-01'::date, 'month', 'elected', 'media.buncombenc.gov/common/election/elected-officials.pdf (Buncombe County Election Services, retrieved 2026-08-23)'),
  ('37021', 'COUNTY', 'Sheriff', -3740015, 'Quentin E. Miller', 'Quentin', 'Miller', 'E', NULL, ARRAY[]::text[], '2018-01-01'::date, 'year', 'elected', 'buncombenc.gov/568/Sheriffs-Office ("since taking office in 2018"), retrieved 2026-08-23'),
  ('37021', 'COUNTY', 'Register of Deeds', -3740016, 'Drew Reisinger', 'Drew', 'Reisinger', NULL, NULL, ARRAY[]::text[], '2012-01-01'::date, 'year', 'elected', 'media.buncombenc.gov/common/election/elected-officials.pdf (Buncombe County Election Services, retrieved 2026-08-23)'),
  ('37021', 'COUNTY', 'Clerk of Superior Court', -3740017, 'Jean Marie Christy', 'Jean Marie', 'Christy', NULL, NULL, ARRAY[]::text[], '2023-01-01'::date, 'year', 'appointed', 'Appointed 2023 on Steven Cogburn''s retirement; elected in the November 2024 special election. media.buncombenc.gov/common/election/elected-officials.pdf (Buncombe County Election Services, retrieved 2026-08-23)'),
  ('buncombe-nc-commissioner-district-1', 'COUNTY', 'Commissioner, District 1', -3740009, 'Al Whitesides', 'Al', 'Whitesides', NULL, NULL, ARRAY['Alfred']::text[], '2016-12-01'::date, 'month', 'appointed', 'Appointed December 2016 to the District 1 seat vacated when Brownie Newman became Chair; elected 2018 and 2022. media.buncombenc.gov/common/election/elected-officials.pdf (Buncombe County Election Services, retrieved 2026-08-23)'),
  ('buncombe-nc-commissioner-district-1', 'COUNTY', 'Commissioner, District 1', -3740010, 'Jennifer Horton', 'Jennifer', 'Horton', NULL, NULL, ARRAY[]::text[], '2024-12-01'::date, 'month', 'elected', 'media.buncombenc.gov/common/election/elected-officials.pdf (Buncombe County Election Services, retrieved 2026-08-23)'),
  ('buncombe-nc-commissioner-district-2', 'COUNTY', 'Commissioner, District 2', -3740011, 'Martin Moore', 'Martin', 'Moore', NULL, NULL, ARRAY[]::text[], '2022-12-01'::date, 'month', 'elected', 'media.buncombenc.gov/common/election/elected-officials.pdf (Buncombe County Election Services, retrieved 2026-08-23)'),
  ('buncombe-nc-commissioner-district-2', 'COUNTY', 'Commissioner, District 2', -3740012, 'Terri Wells', 'Terri', 'Wells', NULL, NULL, ARRAY[]::text[], '2020-12-01'::date, 'month', 'elected', 'media.buncombenc.gov/common/election/elected-officials.pdf (Buncombe County Election Services, retrieved 2026-08-23)'),
  ('buncombe-nc-commissioner-district-3', 'COUNTY', 'Commissioner, District 3', -3740013, 'Parker Sloan', 'Parker', 'Sloan', NULL, NULL, ARRAY[]::text[], '2020-12-01'::date, 'month', 'elected', 'media.buncombenc.gov/common/election/elected-officials.pdf (Buncombe County Election Services, retrieved 2026-08-23)'),
  ('buncombe-nc-commissioner-district-3', 'COUNTY', 'Commissioner, District 3', -3740014, 'Drew Ball', 'Drew', 'Ball', NULL, NULL, ARRAY['Daryl']::text[], '2025-01-01'::date, 'month', 'appointed', 'Appointed January 2025 to the District 3 seat vacated when Amanda Edwards became Chair (sworn 2025-01-07 per contemporaneous press; the county news release is no longer reachable, so recorded at month precision). media.buncombenc.gov/common/election/elected-officials.pdf (Buncombe County Election Services, retrieved 2026-08-23)');

-- ─── Payload guard ───────────────────────────────────────────────────────────
-- Four groups legitimately repeat a (geo_id, district_type, office_title) triple,
-- so this checks per-group COUNTS rather than rejecting any duplicate.
DO $$
DECLARE v_n int; v_dup int; v_grp int;
BEGIN
  SELECT count(*) INTO v_n FROM wave3_seed;
  IF v_n <> 17 THEN RAISE EXCEPTION 'seed payload: expected 17 rows, got %', v_n; END IF;

  SELECT count(*) INTO v_dup FROM (SELECT ext_id FROM wave3_seed GROUP BY ext_id HAVING count(*) > 1) x;
  IF v_dup <> 0 THEN RAISE EXCEPTION 'seed payload: % duplicate external_id(s)', v_dup; END IF;

  SELECT count(*) INTO v_grp FROM wave3_seed
   WHERE geo_id = '3702140' AND district_type = 'LOCAL' AND office_title = 'Council Member';
  IF v_grp <> 6 THEN RAISE EXCEPTION 'seed payload: expected 6 Council Member rows, got %', v_grp; END IF;

  SELECT count(*) INTO v_grp FROM wave3_seed
   WHERE geo_id = 'buncombe-nc-commissioner-district-1' AND district_type = 'COUNTY' AND office_title = 'Commissioner, District 1';
  IF v_grp <> 2 THEN RAISE EXCEPTION 'seed payload: expected 2 Commissioner, District 1 rows, got %', v_grp; END IF;

  SELECT count(*) INTO v_grp FROM wave3_seed
   WHERE geo_id = 'buncombe-nc-commissioner-district-2' AND district_type = 'COUNTY' AND office_title = 'Commissioner, District 2';
  IF v_grp <> 2 THEN RAISE EXCEPTION 'seed payload: expected 2 Commissioner, District 2 rows, got %', v_grp; END IF;

  SELECT count(*) INTO v_grp FROM wave3_seed
   WHERE geo_id = 'buncombe-nc-commissioner-district-3' AND district_type = 'COUNTY' AND office_title = 'Commissioner, District 3';
  IF v_grp <> 2 THEN RAISE EXCEPTION 'seed payload: expected 2 Commissioner, District 3 rows, got %', v_grp; END IF;

  -- Every OTHER triple must be unique -- the genuinely single-seat titles.
  SELECT count(*) INTO v_dup FROM (
    SELECT geo_id, district_type, office_title FROM wave3_seed
    WHERE office_title NOT IN ('Council Member', 'Commissioner, District 1', 'Commissioner, District 2', 'Commissioner, District 3')
    GROUP BY geo_id, district_type, office_title HAVING count(*) > 1
  ) x;
  IF v_dup <> 0 THEN RAISE EXCEPTION 'seed payload: % unexpected duplicate single-seat key(s)', v_dup; END IF;
END $$;

-- ─── Politicians ─────────────────────────────────────────────────────────────

INSERT INTO essentials.politicians
  (external_id, full_name, first_name, last_name, middle_initial, name_suffix,
   alternate_names, is_incumbent, is_active, data_source)
SELECT s.ext_id, s.full_name, s.first_name, s.last_name, s.middle_initial, s.name_suffix,
       s.aliases, true, true, s.source
FROM wave3_seed s
ON CONFLICT (external_id) DO NOTHING;

-- ─── Occupancy, via the helper ───────────────────────────────────────────────

DO $$
DECLARE
  r record;
  v_seated int := 0;
BEGIN
  FOR r IN
    WITH office_rank AS (
      SELECT o.id AS office_id, d.geo_id, d.district_type, o.title,
             row_number() OVER (
               PARTITION BY d.geo_id, d.district_type, o.title ORDER BY o.id
             ) AS rn
      FROM essentials.offices o
      JOIN essentials.districts d ON d.id = o.district_id
      WHERE (d.geo_id = '3702140' AND d.district_type = 'LOCAL')
         OR (d.geo_id = '37021' AND d.district_type = 'COUNTY')
         OR (d.mtfcc = 'X0034')
    ),
    seed_rank AS (
      SELECT s.*,
             row_number() OVER (
               PARTITION BY s.geo_id, s.district_type, s.office_title ORDER BY s.ext_id
             ) AS rn
      FROM wave3_seed s
    )
    SELECT sr.term_start, sr.start_precision, sr.how_started, sr.source,
           orr.office_id, p.id AS politician_id
    FROM seed_rank sr
    JOIN office_rank orr
      ON orr.geo_id = sr.geo_id
     AND orr.district_type = sr.district_type
     AND orr.title = sr.office_title
     AND orr.rn = sr.rn
    JOIN essentials.politicians p ON p.external_id = sr.ext_id
    WHERE NOT EXISTS (
      SELECT 1 FROM essentials.office_terms t
      WHERE t.office_id = orr.office_id AND t.politician_id = p.id
    )
  LOOP
    PERFORM essentials.seat_officeholder(
      r.office_id, r.politician_id, r.term_start,
      r.source,
      r.how_started,
      r.start_precision
    );
    v_seated := v_seated + 1;
  END LOOP;
  RAISE NOTICE 'seated % Asheville/Buncombe official(s)', v_seated;
END $$;

-- ─── Post-verify gate ────────────────────────────────────────────────────────
DO $$
DECLARE
  v_pol int; v_seated int; v_appointed int; v_homonym int; v_n int;
BEGIN
  SELECT count(*) INTO v_pol
  FROM essentials.politicians WHERE external_id BETWEEN -3740017 AND -3740001;
  IF v_pol <> 17 THEN RAISE EXCEPTION 'CA_0010: officials inserted: expected 17, got %', v_pol; END IF;

  -- count(och.politician_id), NOT count(*): office_current_holder LEFT JOINs from
  -- offices, so a vacancy is a NULL politician_id, never an absent row. count(*)
  -- would pass vacuously with every seat empty.
  SELECT count(och.politician_id) INTO v_seated
    FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
    LEFT JOIN essentials.office_current_holder och ON och.office_id = o.id
   WHERE (d.geo_id = '3702140' AND d.district_type = 'LOCAL')
      OR (d.geo_id = '37021' AND d.district_type = 'COUNTY')
      OR (d.mtfcc = 'X0034');
  IF v_seated <> 17 THEN RAISE EXCEPTION 'CA_0010: expected 17 seated officials, found %', v_seated; END IF;

  -- Exactly 2 SEATED commissioners per district -- again per-district, because a
  -- total of 6 is what the chamber-scoped top-up bug would also produce.
  SELECT count(och.politician_id) INTO v_n
    FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
    LEFT JOIN essentials.office_current_holder och ON och.office_id = o.id
   WHERE d.geo_id = 'buncombe-nc-commissioner-district-1' AND d.mtfcc = 'X0034';
  IF v_n <> 2 THEN RAISE EXCEPTION 'CA_0010: commission district 1 has % seated commissioner(s), expected 2', v_n; END IF;
  SELECT count(och.politician_id) INTO v_n
    FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
    LEFT JOIN essentials.office_current_holder och ON och.office_id = o.id
   WHERE d.geo_id = 'buncombe-nc-commissioner-district-2' AND d.mtfcc = 'X0034';
  IF v_n <> 2 THEN RAISE EXCEPTION 'CA_0010: commission district 2 has % seated commissioner(s), expected 2', v_n; END IF;
  SELECT count(och.politician_id) INTO v_n
    FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
    LEFT JOIN essentials.office_current_holder och ON och.office_id = o.id
   WHERE d.geo_id = 'buncombe-nc-commissioner-district-3' AND d.mtfcc = 'X0034';
  IF v_n <> 2 THEN RAISE EXCEPTION 'CA_0010: commission district 3 has % seated commissioner(s), expected 2', v_n; END IF;

  SELECT count(*) INTO v_appointed
    FROM essentials.office_terms t
    JOIN essentials.politicians p ON p.id = t.politician_id
   WHERE p.external_id BETWEEN -3740017 AND -3740001 AND t.how_started = 'appointed';
  IF v_appointed <> 4 THEN RAISE EXCEPTION 'CA_0010: expected 4 appointed term(s), found %', v_appointed; END IF;

  -- 🔴 Cross-state homonym assertion: no wave-3 seat may resolve to someone who
  -- also holds an office outside NC. This is the Mike Lee guard.
  SELECT count(*) INTO v_homonym
  FROM essentials.politicians p
  JOIN essentials.office_current_holder och ON och.politician_id = p.id
  JOIN essentials.offices o ON o.id = och.office_id
  JOIN essentials.districts d ON d.id = o.district_id
   AND ((d.geo_id = '3702140' AND d.district_type = 'LOCAL')
     OR (d.geo_id = '37021' AND d.district_type = 'COUNTY')
     OR (d.mtfcc = 'X0034'))
  JOIN essentials.office_current_holder och2 ON och2.politician_id = p.id
  JOIN essentials.offices o2 ON o2.id = och2.office_id
  JOIN essentials.districts d2 ON d2.id = o2.district_id AND lower(d2.state) <> 'nc';
  IF v_homonym <> 0 THEN RAISE EXCEPTION
    'CA_0010: % wave-3 seat(s) resolved to an out-of-state politician -- the Mike Lee failure', v_homonym; END IF;

  RAISE NOTICE 'CA_0010 OK -- 17 officials seated, 4 by appointment, 0 homonyms.';
END $$;

COMMIT;
