-- CA_0009_asheville_buncombe_structure.sql
-- NC deep-seed program, WAVE 3 (structure). Companion: CA_0010 (incumbents).
--
-- Creates the geography-and-seats half of Asheville + Buncombe County:
--   * 1 LOCAL district  -- 'Asheville Citywide' on TIGER place 3702140
--   * 3 COUNTY districts -- Buncombe's commission districts, mtfcc X0034
--   * 2 governments, 3 chambers
--   * 17 offices -- 7 Asheville, 4 on the county polygon, 6 on the commission districts
--
-- Spec: .planning/todos/2026-08-21-nc-durham-asheville-deep-seed.md (wave 3)
-- Plan: docs/superpowers/plans/2026-08-23-nc-wave-3-asheville-buncombe.md
-- Roster: data/seed-buncombe-asheville-2026/ROSTERS.md
-- Generated by: scripts/gen-buncombe-asheville-migrations.mjs
--
-- ─────────────────────────────────────────────────────────────────────────────
-- 🔴 THE MULTI-SEAT TOP-UP MUST BE SCOPED TO (chamber_id, district_id).
--
-- CA_0006 tops up identically-titled seats with
-- generate_series(1, N - (SELECT count(*) ... WHERE chamber_id = c.id AND title = ...)),
-- scoped to chamber_id ALONE, and says in its own comments that this is correct
-- only because Durham's chamber maps to exactly ONE district.
--
-- Buncombe is the case CA_0006 predicted. Its Board of Commissioners chamber
-- spans THREE districts with two seats each. A chamber-scoped count would see
-- the first district's 2 seats, compute 6 - 2 = 4, and keep topping up until the
-- chamber held 6 -- landing them on whichever district the join produced, while
-- still reporting "6 offices created". Nothing errors.
--
-- Two changes below, and BOTH are required:
--   1. the count subquery is scoped to (chamber_id, district_id);
--   2. the top-up runs PER DISTRICT (3 x 2), never once for 6.
-- The post-verify gate counts PER DISTRICT for the same reason: a total-only
-- assertion of 6 is exactly what the chamber-scoped bug satisfies.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- 🔴 'Chair' IS AN OFFICE HERE. Durham's chairmanship rotates by board vote
-- among 5 at-large seats, so CA_0006 correctly refused to create one. A 2011
-- local act seats SEVEN commissioners in Buncombe: the chair elected COUNTYWIDE
-- plus six by district. Amanda Edwards ran for Chair as its own ballot line, and
-- her move from a District 3 seat to Chair is what created the vacancy Drew Ball
-- was appointed to fill. Do not carry CA_0006's rule across.
--
-- Conversely, Asheville's "Vice Mayor" is only a board role -- CA_0006's rule
-- DOES apply there. Asheville gets Mayor + 6 'Council Member', not 7 + a Vice
-- Mayor.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- 🔴 geo_id '37021' IS CLAIMED BY THREE DISTRICTS. Measured in prod 2026-08-23:
--     COUNTY      | Buncombe County           | 37021
--     STATE_UPPER | State Senate District 21  | 37021
--     STATE_LOWER | State House District 21   | 37021
-- Every county join below pairs geo_id with district_type = 'COUNTY'. A bare
-- geo_id join would attach the Chair, Sheriff, Register of Deeds and Clerk to a
-- state legislative district while an "offices created" count still looked
-- right. The post-verify gate asserts both legislative rows are untouched.
--
-- The three X0034 districts are loaded by
-- scripts/load-buncombe-commissioner-boundaries.ts and verified by
-- scripts/verify-buncombe-commission-coupling.sql. This migration does NOT
-- create geometry; it fails if the boundaries are absent.
--
-- IDEMPOTENT: every insert is NOT EXISTS-guarded or a target-count top-up.

BEGIN;

-- ─── 0. Precondition: the commission boundaries must already be loaded ───────
DO $$
DECLARE v_n int;
BEGIN
  SELECT count(*) INTO v_n FROM essentials.geofence_boundaries WHERE mtfcc = 'X0034';
  IF v_n <> 3 THEN
    RAISE EXCEPTION 'CA_0009: expected 3 X0034 boundaries, found % -- run scripts/load-buncombe-commissioner-boundaries.ts first', v_n;
  END IF;
END $$;

-- ─── 1. Districts ────────────────────────────────────────────────────────────
-- Asheville's citywide district. Follows the 'Durham Citywide' / 'Bainbridge
-- Island Citywide' precedent: ALL council seats hang off ONE district because
-- every seat is elected citywide. Not Austin's one-district-per-seat shape.

INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc)
SELECT '3702140', 'Asheville Citywide', 'LOCAL', 'nc', 'G4110'
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
  WHERE geo_id = '3702140' AND district_type = 'LOCAL'
);

-- Buncombe's 3 commission districts. district_type 'COUNTY' matches the Kitsap
-- (X0027) and Washington County (X0027-era) precedents and is semantically right
-- for county offices; it was verified harmless on both read paths that branch on
-- district_type -- campaignFinanceSearchService.ts puts LOCAL and COUNTY in one
-- tier, and inform.compass_lenses auto-applies the 'local' lens to
-- {LOCAL,LOCAL_EXEC,COUNTY,SCHOOL}.
--
-- num_officials = 2: each district elects two commissioners. This is a measured
-- fact, not a template default.

INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'buncombe-nc-commissioner-district-1', 'Buncombe County Commissioner District 1', 'COUNTY', 'nc', 'X0034', 2
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
  WHERE geo_id = 'buncombe-nc-commissioner-district-1' AND mtfcc = 'X0034'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'buncombe-nc-commissioner-district-2', 'Buncombe County Commissioner District 2', 'COUNTY', 'nc', 'X0034', 2
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
  WHERE geo_id = 'buncombe-nc-commissioner-district-2' AND mtfcc = 'X0034'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'buncombe-nc-commissioner-district-3', 'Buncombe County Commissioner District 3', 'COUNTY', 'nc', 'X0034', 2
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
  WHERE geo_id = 'buncombe-nc-commissioner-district-3' AND mtfcc = 'X0034'
);

-- 🔴 Buncombe County's own COUNTY district (37021) ALREADY EXISTS and is NOT
-- created here. Measured 2026-08-23: it exists and carries ZERO offices.

-- ─── 2. Governments ──────────────────────────────────────────────────────────
-- Neither exists yet (verified against prod 2026-08-23: zero rows in
-- essentials.governments for geo_id '3702140' or '37021').

INSERT INTO essentials.governments (name, type, state, city, geo_id)
SELECT 'City of Asheville, North Carolina, US', 'City', 'NC', 'Asheville', '3702140'
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.governments WHERE geo_id = '3702140' AND type = 'City'
);

INSERT INTO essentials.governments (name, type, state, city, geo_id)
SELECT 'Buncombe County, North Carolina, US', 'County', 'NC', NULL, '37021'
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.governments WHERE geo_id = '37021' AND type = 'County'
);

-- ─── 3. Chambers ─────────────────────────────────────────────────────────────
-- Buncombe follows Durham's (and Travis County's) shape: one chamber for the
-- elected legislative board, one for the countywide elected executive officials.

INSERT INTO essentials.chambers
  (government_id, name, name_formal, official_count, policy_engagement_level)
SELECT g.id, 'City Council', 'Asheville City Council', 7, 'full'
FROM essentials.governments g
WHERE g.geo_id = '3702140' AND g.type = 'City'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.chambers c
    WHERE c.government_id = g.id AND c.name = 'City Council'
  );

-- official_count 7 = chair + 6 district commissioners.
INSERT INTO essentials.chambers
  (government_id, name, name_formal, official_count, policy_engagement_level)
SELECT g.id, 'Board of County Commissioners', 'Buncombe County Board of Commissioners', 7, 'full'
FROM essentials.governments g
WHERE g.geo_id = '37021' AND g.type = 'County'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.chambers c
    WHERE c.government_id = g.id AND c.name = 'Board of County Commissioners'
  );

INSERT INTO essentials.chambers
  (government_id, name, name_formal, official_count, policy_engagement_level)
SELECT g.id, 'Elected Officials', 'Buncombe County Elected Officials', 3, 'full'
FROM essentials.governments g
WHERE g.geo_id = '37021' AND g.type = 'County'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.chambers c
    WHERE c.government_id = g.id AND c.name = 'Elected Officials'
  );

-- ─── 4a. Asheville: Mayor, a genuine single seat ─────────────────────────────

INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Mayor', 'NC', 'Asheville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = '3702140' AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'nc'
) d
WHERE g.geo_id = '3702140' AND g.type = 'City' AND c.name = 'City Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o WHERE o.chamber_id = c.id AND o.title = 'Mayor'
  );

-- ─── 4b. Asheville: 6 IDENTICAL 'Council Member' rows ────────────────────────
-- All six are elected at-large; no numbered seat exists on Asheville's ballot,
-- so the six offices are genuinely interchangeable and share one title. Guarded
-- by a target-count top-up rather than NOT EXISTS-on-title, which would collapse
-- six rows to one on a re-run.
--
-- The count is scoped to (chamber_id, district_id) even though this chamber maps
-- to a single district. It costs nothing and it means this block cannot become
-- the CA_0006 bug if Asheville ever districts its council.

INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member', 'NC', 'Asheville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = '3702140' AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'nc'
) d
CROSS JOIN LATERAL (
  SELECT generate_series(1, 6 - (
    SELECT count(*) FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member'
  )) AS n
) gs
WHERE g.geo_id = '3702140' AND g.type = 'City' AND c.name = 'City Council';

-- ─── 5a. Buncombe: Chair, countywide on the EXISTING county district ─────────
-- A real single-seat office -- see header.

INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state)
SELECT c.id, d.id, 'Chair, Board of Commissioners', 'NC'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = '37021' AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'nc'
) d
WHERE g.geo_id = '37021' AND g.type = 'County' AND c.name = 'Board of County Commissioners'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.title = 'Chair, Board of Commissioners'
  );

-- ─── 5b. Buncombe: 6 district commissioners, 2 PER DISTRICT ──────────────────
-- 🔴 THE BLOCK CA_0006 WARNED ABOUT. One top-up per district, each counting
-- within (chamber_id, district_id). See header for why a chamber-scoped count
-- silently creates 2 of 6.

INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representation_note)
SELECT c.id, d.id, 'Commissioner, District 1', 'NC', 'District 1''s boundaries are, by a 2011 local act of the North Carolina General Assembly, identical to those of NC House District 114. Buncombe is the only one of North Carolina''s 100 counties whose commission districts are defined this way, so a redraw of the state House district also moves this county district. Two commissioners are elected from each district. (Buncombe County GIS layer bcmap_VotingDistricts3/7, cross-checked against TIGER 2024, retrieved 2026-08-23.)'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'buncombe-nc-commissioner-district-1' AND dd.mtfcc = 'X0034'
) d
CROSS JOIN LATERAL (
  SELECT generate_series(1, 2 - (
    SELECT count(*) FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id
      AND o.title = 'Commissioner, District 1'
  )) AS nn
) gs
WHERE g.geo_id = '37021' AND g.type = 'County' AND c.name = 'Board of County Commissioners';

INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representation_note)
SELECT c.id, d.id, 'Commissioner, District 2', 'NC', 'District 2''s boundaries are, by a 2011 local act of the North Carolina General Assembly, identical to those of NC House District 115. Buncombe is the only one of North Carolina''s 100 counties whose commission districts are defined this way, so a redraw of the state House district also moves this county district. Two commissioners are elected from each district. (Buncombe County GIS layer bcmap_VotingDistricts3/7, cross-checked against TIGER 2024, retrieved 2026-08-23.)'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'buncombe-nc-commissioner-district-2' AND dd.mtfcc = 'X0034'
) d
CROSS JOIN LATERAL (
  SELECT generate_series(1, 2 - (
    SELECT count(*) FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id
      AND o.title = 'Commissioner, District 2'
  )) AS nn
) gs
WHERE g.geo_id = '37021' AND g.type = 'County' AND c.name = 'Board of County Commissioners';

INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representation_note)
SELECT c.id, d.id, 'Commissioner, District 3', 'NC', 'District 3''s boundaries are, by a 2011 local act of the North Carolina General Assembly, identical to those of NC House District 116. Buncombe is the only one of North Carolina''s 100 counties whose commission districts are defined this way, so a redraw of the state House district also moves this county district. Two commissioners are elected from each district. (Buncombe County GIS layer bcmap_VotingDistricts3/7, cross-checked against TIGER 2024, retrieved 2026-08-23.)'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'buncombe-nc-commissioner-district-3' AND dd.mtfcc = 'X0034'
) d
CROSS JOIN LATERAL (
  SELECT generate_series(1, 2 - (
    SELECT count(*) FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id
      AND o.title = 'Commissioner, District 3'
  )) AS nn
) gs
WHERE g.geo_id = '37021' AND g.type = 'County' AND c.name = 'Board of County Commissioners';


-- ─── 5c. Buncombe: 3 countywide row offices ──────────────────────────────────

INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state)
SELECT c.id, d.id, v.title, 'NC'
FROM (VALUES
  ('Sheriff'),
  ('Register of Deeds'),
  ('Clerk of Superior Court')
) AS v(title)
CROSS JOIN LATERAL (
  SELECT ch.id FROM essentials.chambers ch
  JOIN essentials.governments g ON g.id = ch.government_id
  WHERE g.geo_id = '37021' AND g.type = 'County' AND ch.name = 'Elected Officials'
) c
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = '37021' AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'nc'
) d
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.offices o WHERE o.chamber_id = c.id AND o.title = v.title
);

-- ─── 6. Post-verify gate ─────────────────────────────────────────────────────
DO $$
DECLARE
  v_n int; v_hd21 int; v_sd21 int; v_nogeom int; v_notes int;
BEGIN
  -- Districts
  SELECT count(*) INTO v_n FROM essentials.districts
   WHERE geo_id = '3702140' AND district_type = 'LOCAL';
  IF v_n <> 1 THEN RAISE EXCEPTION 'CA_0009: expected 1 Asheville LOCAL district, got %', v_n; END IF;

  SELECT count(*) INTO v_n FROM essentials.districts WHERE mtfcc = 'X0034';
  IF v_n <> 3 THEN RAISE EXCEPTION 'CA_0009: expected 3 X0034 districts, got %', v_n; END IF;

  -- Asheville offices
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE d.geo_id = '3702140' AND d.district_type = 'LOCAL';
  IF v_n <> 7 THEN RAISE EXCEPTION 'CA_0009: expected 7 Asheville offices, got %', v_n; END IF;

  -- Buncombe county-polygon offices (chair + 3 row offices)
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE d.geo_id = '37021' AND d.district_type = 'COUNTY';
  IF v_n <> 4 THEN RAISE EXCEPTION 'CA_0009: expected 4 offices on the Buncombe county polygon, got %', v_n; END IF;

  -- 🔴 PER-DISTRICT, not 6 in total. A total-only assertion is precisely what a
  -- chamber-scoped top-up satisfies while putting every seat on one district.
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE d.geo_id = 'buncombe-nc-commissioner-district-1' AND d.mtfcc = 'X0034';
  IF v_n <> 2 THEN RAISE EXCEPTION 'CA_0009: commission district 1 carries % offices, expected exactly 2', v_n; END IF;
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE d.geo_id = 'buncombe-nc-commissioner-district-2' AND d.mtfcc = 'X0034';
  IF v_n <> 2 THEN RAISE EXCEPTION 'CA_0009: commission district 2 carries % offices, expected exactly 2', v_n; END IF;
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE d.geo_id = 'buncombe-nc-commissioner-district-3' AND d.mtfcc = 'X0034';
  IF v_n <> 2 THEN RAISE EXCEPTION 'CA_0009: commission district 3 carries % offices, expected exactly 2', v_n; END IF;

  -- The coupling note is required on all 6 district commissioner seats.
  SELECT count(*) INTO v_notes FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE d.mtfcc = 'X0034' AND o.representation_note IS NOT NULL;
  IF v_notes <> 6 THEN RAISE EXCEPTION 'CA_0009: expected 6 commissioner offices carrying a representation_note, got %', v_notes; END IF;

  -- 🔴 The assertions that actually catch the geo_id collision. Counting offices
  -- on the county row alone would NOT notice offices landing on either
  -- legislative district.
  SELECT count(*) INTO v_hd21 FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE d.geo_id = '37021' AND d.district_type = 'STATE_LOWER';
  IF v_hd21 <> 1 THEN RAISE EXCEPTION
    'CA_0009: NC House District 21 carries % offices, expected 1 -- county offices cross-wired onto the house district', v_hd21; END IF;

  SELECT count(*) INTO v_sd21 FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE d.geo_id = '37021' AND d.district_type = 'STATE_UPPER';
  IF v_sd21 <> 1 THEN RAISE EXCEPTION
    'CA_0009: NC Senate District 21 carries % offices, expected 1 -- county offices cross-wired onto the senate district', v_sd21; END IF;

  -- No office may sit on a district with no geometry: it would be unreachable by
  -- address and nothing else would say so.
  SELECT count(*) INTO v_nogeom FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE (d.geo_id = '3702140' AND d.district_type = 'LOCAL' OR d.mtfcc = 'X0034')
     AND NOT EXISTS (
       SELECT 1 FROM essentials.geofence_boundaries b
        WHERE b.geo_id = d.geo_id AND b.mtfcc = d.mtfcc
     );
  IF v_nogeom <> 0 THEN RAISE EXCEPTION 'CA_0009: % office(s) sit on a district with no matching boundary', v_nogeom; END IF;

  RAISE NOTICE 'CA_0009 OK -- 17 offices across 1 city district, 3 commission districts and the Buncombe county polygon.';
END $$;

COMMIT;
