-- CC_0049_macon_bibb_structure.sql
--
-- Knight Foundation cities program, wave GA-5 Task 2, CITY STRUCTURE half.
--   * 1 government, 2 chambers
--   * 10 districts -- 1 citywide (TIGER place 1349008/G4110) + 9 commission (X0045)
--   * 10 offices   -- 1 Mayor + 9 district commissioners, and NO at-large seats
--
-- Roster: backend/data/seed-macon-bibb-2026/ROSTERS.md
-- Slice:  .planning/knight-foundation/ga.md
-- Generated by scripts/gen-ga5-macon-bibb-migrations.mjs from
-- data/ga5-macon-bibb-roster.json -- edit the roster and regenerate, do not
-- hand-edit this file.
--
-- 🔴 THE NUMBER WAS TAKEN LAST, at apply time on 2026-09-02, re-counted across
--    all 98 remote refs. CC_0044 was the max and it sits on a colleague's
--    UNMERGED branch, which is why the sweep covers every remote ref rather than
--    just master. GA-4's numbers collided with a parallel session of the SAME
--    author six minutes after its re-count and had to be renumbered post-apply.
--    ⚠ Once APPLIED, do not renumber: a renamed applied migration desyncs the
--      filename from its apply order.
--
-- ---------------------------------------------------------------------------
-- 🔴 MACON-BIBB IS THE PROGRAM'S SECOND CONSOLIDATED CITY-COUNTY, AND THE
--    CONSOLIDATION IS COMPLETE.
--
-- TIGER place 1349008 measures 254.906 sq mi, identical to Bibb County
-- 13021, and Georgia publishes no BALANCE record for it (FUNCSTAT 'A',
-- unlike Augusta-Richmond and Athens-Clarke, which are 'F' because satellites
-- survive there). So -- unlike Nashville, whose place polygon excludes six
-- satellite cities whose residents still elect the same council -- the place
-- polygon here is the whole electorate, and the government row can key on it.
--
-- ⚠ Charter Sec. 9(a) excludes "the city limits of the City of Payne City" from
--   the districting plan. Payne City was a municipality inside Bibb, and if it
--   still existed the nine districts would not tile the county. It dissolved
--   into the consolidated government and appears nowhere in the TIGER 2024
--   place file; the boundary loader measured the residual at 0.0139 sq mi, far
--   below Payne City's footprint, so the carve-out is spent. That was PROVED,
--   not assumed.
--
-- ONE government covers both tiers. Task 4 attaches a THIRD chamber, "Bibb County Elected Officials",
-- to THIS SAME government row. That is why every count in the post-verify gate
-- below is scoped to the two CITY chambers and never to the government.
--
-- ---------------------------------------------------------------------------
-- 🔴 RULING M1: NINE COMMISSIONERS, NINE SINGLE-MEMBER DISTRICTS, NO AT-LARGE.
--
-- Charter Sec. 9(a): "The territory of the restructured government shall consist
-- of nine election districts to be designated as Commission Districts 1 through
-- 9". Sec. 9(c): "The members shall be elected from the nine districts specified
-- in subsection (a) of this section by a majority of electors voting in such
-- election from such district."
--
-- All five GIS layers that publish these districts return exactly nine polygons,
-- which is the independent confirmation that there is no at-large pair.
--
-- ⚠ THE CHARTER CONTRADICTS ITSELF AND Sec. 9(c) GOVERNS. Sec. 5 says the
--   commission is "composed of a mayor and nine commissioners" and then defines
--   every member as a "commissioner". Sec. 9(c) says "The commission shall
--   consist of nine members" and makes the mayor the presiding officer and
--   expressly not a voting member. Sec. 9(c) is the provision that sets
--   membership and voting, and the body's own conduct settles it: the mayor pro
--   tem was elected 5-4 among NINE in January 2025 and 5-3 among EIGHT on
--   2026-01-06 with District 5 vacant. official_count is 9.
--
-- 🔴 DO NOT COPY COLUMBUS HERE. Columbus is 8 districts + 2 at-large posts, so
--   its citywide district carries num_officials 3. Macon-Bibb's carries 1.
--
-- ---------------------------------------------------------------------------
-- 🔴 RULING M2: THE MAYOR IS non_voting, WITH A MANDATORY NOTE CITING Sec. 9(c).
--
-- Charter Sec. 9(c): "All members of the commission shall be full voting members
-- of the commission. The mayor shall be the presiding officer of the commission
-- but shall not be a voting member of the commission; provided, however, that
-- the mayor may cast a vote on any matter before the commission to break a tie.
-- The mayor may propose ordinances in the same manner as a commissioner."
--
-- That is Nashville's Vice Mayor ruling and Columbus's R2 in a third dress:
-- voting_powers 'non_voting' with the tie-break carried in representation_note,
-- which ADR 0003 makes mandatory and both read paths render.
--
-- ⚠ THE SECTION WAS READ, NOT CARRIED FROM A SUMMARY. GA-4 cited Columbus's
--   "Sec. 4-102" for the same power through three files; 4-102 is "General
--   provisions concerning departments" and the real section was 4-201.
--   representation_note is voter-facing prose, so a wrong section number ships
--   to readers. The post-verify below asserts the note actually contains
--   "9(c)", not merely that a note exists.
--
-- ---------------------------------------------------------------------------
-- 🔴 RULING M3: MAYOR PRO TEM IS A PARENTHETICAL, NOT AN OFFICE.
--
-- Charter Sec. 9(f): "The commission shall elect from among its members in
-- January of each year a member to serve as mayor pro tempore, who shall preside
-- over meetings of the commission in the mayor's absence." Elected by the body,
-- from the body, annually -- and it moved from Seth Clark to Valerie Wynn on
-- 2026-01-06, which is the demonstration. Baldwin R2, the Lawrence County
-- ruling, and Columbus R3. The post-verify gate refuses any office titled with it.
--
-- ---------------------------------------------------------------------------
-- ⚠ THE NINE DISTRICTS DO TILE THE COUNTY, WHICH IS THE OPPOSITE OF COLUMBUS.
--
-- Columbus's eight districts leave 74.79 sq mi (Fort Benning) in no council
-- district, so GA-4's rule was "gate the structure, not full coverage". Bibb's
-- nine cover 254.9060 of the county's 254.9059 sq mi, uncovered 0.0139. Full
-- coverage is gated -- in the BOUNDARY LOADER, where the geometry lives, not
-- here. This migration gates the structure: one office per district, exactly one
-- seat citywide, and no crossed tier.
--
-- IDEMPOTENT: every insert is NOT EXISTS-guarded, and every assertion is a
-- statement about the END STATE, not about a delta.

BEGIN;

-- --- 0. Pre-flight: refuse to create offices whose district has no polygon ---
-- 🔴 An office on a district with no boundary is an office NOBODY CAN REACH BY
-- ADDRESS, and nothing else in the system errors. This is the one failure mode
-- CI cannot catch after the fact.
DO $$
DECLARE v_n int; v_unpaired int;
BEGIN
  SELECT count(*) INTO v_n FROM essentials.geofence_boundaries WHERE mtfcc = 'X0045';
  IF v_n <> 9 THEN
    RAISE EXCEPTION 'macon-bibb structure: expected 9 X0045 boundaries, found % -- run scripts/load-macon-bibb-commission-boundaries.ts (GA-5 Task 1) first', v_n;
  END IF;

  -- ⚠ A COUNT IS NOT AN IDENTITY CHECK. Nine boundaries under some other slug
  -- would satisfy the count above and then silently produce zero offices,
  -- because the office insert resolves each district by its geo_id.
  SELECT count(*) INTO v_n FROM essentials.geofence_boundaries
   WHERE mtfcc = 'X0045'
     AND geo_id IN ('macon-bibb-ga-commission-district-1', 'macon-bibb-ga-commission-district-2', 'macon-bibb-ga-commission-district-3', 'macon-bibb-ga-commission-district-4', 'macon-bibb-ga-commission-district-5', 'macon-bibb-ga-commission-district-6', 'macon-bibb-ga-commission-district-7', 'macon-bibb-ga-commission-district-8', 'macon-bibb-ga-commission-district-9');
  IF v_n <> 9 THEN
    RAISE EXCEPTION 'macon-bibb structure: the X0045 boundaries are not the % expected slugs (matched %)', 9, v_n;
  END IF;

  -- The citywide district hangs on the TIGER place boundary GA-1 loaded.
  -- ⚠ ALWAYS PAIR geo_id WITH mtfcc.
  IF NOT EXISTS (
    SELECT 1 FROM essentials.geofence_boundaries
     WHERE geo_id = '1349008' AND mtfcc = 'G4110'
  ) THEN
    RAISE EXCEPTION 'macon-bibb structure: boundary 1349008/G4110 is missing -- GA-1 must be applied first';
  END IF;

  -- 🔴 GEORGIA'S geo_id COLLISION IS THREE-WAY AND LIVE IN `districts`. The
  -- COUNTY district Task 4 needs must resolve to EXACTLY ONE row when geo_id is
  -- paired with mtfcc and district_type -- and bare '13021' does NOT.
  -- This migration creates nothing on the county tier; it only proves the tier
  -- is reachable and distinguishable before Task 4 relies on it.
  SELECT count(*) INTO v_n FROM essentials.districts
   WHERE geo_id = '13021' AND mtfcc = 'G4020'
     AND district_type = 'COUNTY';
  IF v_n <> 1 THEN
    RAISE EXCEPTION 'macon-bibb structure: expected exactly 1 COUNTY district 13021/G4020, got % -- the TIGER county load must be applied first, and Task 4 ASSERTS this row rather than inserting it', v_n;
  END IF;

  SELECT count(*) INTO v_unpaired FROM essentials.districts
   WHERE geo_id = '13021';
  RAISE NOTICE 'macon-bibb structure: bare geo_id 13021 matches % district rows across tiers (COUNTY + State House 21 + State Senate 21) -- this is why every join here pairs geo_id with mtfcc AND district_type', v_unpaired;
  IF v_unpaired < 2 THEN
    RAISE EXCEPTION 'macon-bibb structure: bare geo_id 13021 matched only % row(s). Georgia''s three-way collision is documented as MEASURED; if it has genuinely gone away, re-measure before relaxing any join', v_unpaired;
  END IF;
END $$;

-- --- 1. Districts -----------------------------------------------------------
-- ⚠ Synthetic districts carry no ocd_id and no government_id, matching X0035,
-- X0042, X0043 and X0044's siblings. district state is LOWER case here and
-- UPPER on governments and offices; both conventions are live in prod.
--
-- num_officials on the citywide district is 1: exactly one official is
-- elected on it, the Mayor. Columbus wrote 3 because its two at-large posts are
-- elected citywide too; Tallahassee wrote 5 because all five of its
-- commissioners are at-large; Miami wrote 1 because only its Mayor is. The
-- column counts officials elected on the district ACROSS CHAMBERS, not seats
-- within one chamber -- and Macon-Bibb has no at-large seats at all.

INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'LOCAL', 'Macon-Bibb Citywide', 'ga', '1349008', 'G4110', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = '1349008' AND mtfcc = 'G4110' AND district_type = 'LOCAL'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'LOCAL', 'Macon-Bibb County Commission District 1', 'ga', 'macon-bibb-ga-commission-district-1', 'X0045', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'macon-bibb-ga-commission-district-1' AND mtfcc = 'X0045' AND district_type = 'LOCAL'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'LOCAL', 'Macon-Bibb County Commission District 2', 'ga', 'macon-bibb-ga-commission-district-2', 'X0045', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'macon-bibb-ga-commission-district-2' AND mtfcc = 'X0045' AND district_type = 'LOCAL'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'LOCAL', 'Macon-Bibb County Commission District 3', 'ga', 'macon-bibb-ga-commission-district-3', 'X0045', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'macon-bibb-ga-commission-district-3' AND mtfcc = 'X0045' AND district_type = 'LOCAL'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'LOCAL', 'Macon-Bibb County Commission District 4', 'ga', 'macon-bibb-ga-commission-district-4', 'X0045', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'macon-bibb-ga-commission-district-4' AND mtfcc = 'X0045' AND district_type = 'LOCAL'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'LOCAL', 'Macon-Bibb County Commission District 5', 'ga', 'macon-bibb-ga-commission-district-5', 'X0045', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'macon-bibb-ga-commission-district-5' AND mtfcc = 'X0045' AND district_type = 'LOCAL'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'LOCAL', 'Macon-Bibb County Commission District 6', 'ga', 'macon-bibb-ga-commission-district-6', 'X0045', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'macon-bibb-ga-commission-district-6' AND mtfcc = 'X0045' AND district_type = 'LOCAL'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'LOCAL', 'Macon-Bibb County Commission District 7', 'ga', 'macon-bibb-ga-commission-district-7', 'X0045', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'macon-bibb-ga-commission-district-7' AND mtfcc = 'X0045' AND district_type = 'LOCAL'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'LOCAL', 'Macon-Bibb County Commission District 8', 'ga', 'macon-bibb-ga-commission-district-8', 'X0045', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'macon-bibb-ga-commission-district-8' AND mtfcc = 'X0045' AND district_type = 'LOCAL'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'LOCAL', 'Macon-Bibb County Commission District 9', 'ga', 'macon-bibb-ga-commission-district-9', 'X0045', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'macon-bibb-ga-commission-district-9' AND mtfcc = 'X0045' AND district_type = 'LOCAL'
);

-- --- 2. Government ----------------------------------------------------------
-- ⚠ The charter's corporate name is the bare "Macon-Bibb County" (Sec. 1(a)),
-- which is not a usable row label; the government publishes itself as the
-- Macon-Bibb County Government.

INSERT INTO essentials.governments (name, type, state, city, geo_id)
SELECT 'Macon-Bibb County Government, Georgia, US', 'City', 'GA', 'Macon', '1349008'
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.governments WHERE geo_id = '1349008' AND type = 'City'
);

-- --- 3. Chambers ------------------------------------------------------------
-- ⚠ chambers.slug is GENERATED from name_formal and cannot be inserted.
-- Getting name_formal wrong silently yields a different slug.

INSERT INTO essentials.chambers
  (government_id, name, name_formal, official_count, policy_engagement_level)
SELECT g.id, 'Macon-Bibb County Commission', 'Macon-Bibb County Commission', 9, 'full'
FROM essentials.governments g
WHERE g.geo_id = '1349008' AND g.type = 'City'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.chambers c WHERE c.government_id = g.id AND c.name = 'Macon-Bibb County Commission'
  );

INSERT INTO essentials.chambers
  (government_id, name, name_formal, official_count, policy_engagement_level)
SELECT g.id, 'Office of the Mayor', 'Office of the Mayor of Macon-Bibb County, Georgia', 1, 'full'
FROM essentials.governments g
WHERE g.geo_id = '1349008' AND g.type = 'City'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.chambers c WHERE c.government_id = g.id AND c.name = 'Office of the Mayor'
  );

-- --- 4. Offices -------------------------------------------------------------
-- Every title is distinct, so a NOT EXISTS-on-title guard cannot collapse rows.
-- ⚠ The CROSS JOIN LATERAL resolves each district by geo_id + mtfcc +
-- district_type. If it matches nothing the row VANISHES and no office is
-- inserted, with no error -- which is what the pre-flight slug check and the
-- per-district post-verify below exist to catch.

INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers, representation_note)
SELECT c.id, d.id, 'Mayor', 'GA', 'Macon', 'non_voting', 'The Mayor of Macon-Bibb County is elected countywide and presides over the nine-member Macon-Bibb County Commission. Under Section 9(c) of the Charter of Macon-Bibb County, the Mayor is the presiding officer of the Commission but is not a voting member of it, and may cast a vote on a matter before the Commission only to break a tie. The Mayor may propose ordinances in the same manner as a commissioner. Macon-Bibb County is a strong-mayor government, so the Mayor is also its chief executive, responsible for carrying out its laws and policies. If the office of Mayor becomes vacant, Section 15(c) makes the mayor pro tempore the acting mayor.'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = '1349008' AND dd.mtfcc = 'G4110'
     AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'ga'
) d
WHERE g.geo_id = '1349008' AND g.type = 'City' AND c.name = 'Office of the Mayor'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Mayor'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 1', 'GA', 'Macon', 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'macon-bibb-ga-commission-district-1' AND dd.mtfcc = 'X0045'
     AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'ga'
) d
WHERE g.geo_id = '1349008' AND g.type = 'City' AND c.name = 'Macon-Bibb County Commission'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 1'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 2', 'GA', 'Macon', 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'macon-bibb-ga-commission-district-2' AND dd.mtfcc = 'X0045'
     AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'ga'
) d
WHERE g.geo_id = '1349008' AND g.type = 'City' AND c.name = 'Macon-Bibb County Commission'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 2'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 3', 'GA', 'Macon', 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'macon-bibb-ga-commission-district-3' AND dd.mtfcc = 'X0045'
     AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'ga'
) d
WHERE g.geo_id = '1349008' AND g.type = 'City' AND c.name = 'Macon-Bibb County Commission'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 3'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 4', 'GA', 'Macon', 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'macon-bibb-ga-commission-district-4' AND dd.mtfcc = 'X0045'
     AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'ga'
) d
WHERE g.geo_id = '1349008' AND g.type = 'City' AND c.name = 'Macon-Bibb County Commission'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 4'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 5', 'GA', 'Macon', 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'macon-bibb-ga-commission-district-5' AND dd.mtfcc = 'X0045'
     AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'ga'
) d
WHERE g.geo_id = '1349008' AND g.type = 'City' AND c.name = 'Macon-Bibb County Commission'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 5'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 6', 'GA', 'Macon', 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'macon-bibb-ga-commission-district-6' AND dd.mtfcc = 'X0045'
     AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'ga'
) d
WHERE g.geo_id = '1349008' AND g.type = 'City' AND c.name = 'Macon-Bibb County Commission'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 6'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 7', 'GA', 'Macon', 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'macon-bibb-ga-commission-district-7' AND dd.mtfcc = 'X0045'
     AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'ga'
) d
WHERE g.geo_id = '1349008' AND g.type = 'City' AND c.name = 'Macon-Bibb County Commission'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 7'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 8', 'GA', 'Macon', 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'macon-bibb-ga-commission-district-8' AND dd.mtfcc = 'X0045'
     AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'ga'
) d
WHERE g.geo_id = '1349008' AND g.type = 'City' AND c.name = 'Macon-Bibb County Commission'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 8'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 9', 'GA', 'Macon', 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'macon-bibb-ga-commission-district-9' AND dd.mtfcc = 'X0045'
     AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'ga'
) d
WHERE g.geo_id = '1349008' AND g.type = 'City' AND c.name = 'Macon-Bibb County Commission'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 9'
  );

-- --- 5. Post-verify gate ----------------------------------------------------
-- 🔴 EVERY COUNT HERE IS SCOPED TO THE TWO CITY CHAMBERS, NEVER TO THE
-- GOVERNMENT. Macon-Bibb is consolidated, so Task 4's five county officers join
-- this SAME government row. A government-wide count would pass today and fail
-- forever after that, breaking this migration's own re-run -- the FL-4
-- correction, in a new dress, proved at GA-4 by simulating Task 4 mid-transaction.
DO $$
DECLARE v_n int; v_gov uuid; v_d text;
BEGIN
  SELECT count(*) INTO v_n FROM essentials.districts
   WHERE mtfcc = 'X0045' AND district_type = 'LOCAL' AND lower(state) = 'ga';
  IF v_n <> 9 THEN RAISE EXCEPTION 'macon-bibb structure: expected 9 X0045 districts, got %', v_n; END IF;

  SELECT count(*) INTO v_n FROM essentials.districts
   WHERE geo_id = '1349008' AND mtfcc = 'G4110' AND district_type = 'LOCAL'
     AND num_officials = 1;
  IF v_n <> 1 THEN RAISE EXCEPTION 'macon-bibb structure: expected exactly 1 Macon-Bibb Citywide district carrying num_officials = 1, got %', v_n; END IF;

  SELECT id INTO v_gov FROM essentials.governments
   WHERE geo_id = '1349008' AND type = 'City';
  IF v_gov IS NULL THEN RAISE EXCEPTION 'macon-bibb structure: the government row is missing'; END IF;

  -- The two CITY chambers exist and carry the right official_count. Deliberately
  -- NOT "this government has exactly 2 chambers" -- see the header.
  -- 🔴 official_count on the Commission is 9, not 10. Charter Sec. 9(c):
  -- "The commission shall consist of nine members." Sec. 5's "a mayor and nine
  -- commissioners" contradicts it; 9(c) is the provision that sets membership
  -- and voting, and the two mayor pro tem roll calls (5-4 of nine, then 5-3 of
  -- eight with a seat vacant) show which one the body follows.
  SELECT count(*) INTO v_n FROM essentials.chambers c
   WHERE c.government_id = v_gov AND ((c.name = 'Macon-Bibb County Commission' AND c.official_count = 9)
                                       OR (c.name = 'Office of the Mayor' AND c.official_count = 1));
  IF v_n <> 2 THEN RAISE EXCEPTION 'macon-bibb structure: expected 2 city chambers with the right official_count, got %', v_n; END IF;

  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
   WHERE c.government_id = v_gov AND c.name IN ('Macon-Bibb County Commission', 'Office of the Mayor');
  IF v_n <> 10 THEN RAISE EXCEPTION 'macon-bibb structure: expected 10 city offices, got %', v_n; END IF;

  -- Exactly one office per numbered district, counted PER DISTRICT. A single
  -- total can hide two offices on one district and none on another.
  FOR v_d IN SELECT 'macon-bibb-ga-commission-district-' || gs FROM generate_series(1,9) gs LOOP
    SELECT count(*) INTO v_n FROM essentials.offices o
      JOIN essentials.districts d ON d.id = o.district_id
     WHERE d.geo_id = v_d AND d.mtfcc = 'X0045' AND d.district_type = 'LOCAL';
    IF v_n <> 1 THEN RAISE EXCEPTION 'macon-bibb structure: district % carries % offices, expected exactly 1', v_d, v_n; END IF;
  END LOOP;

  -- 🔴 EXACTLY ONE seat hangs on the citywide district: the Mayor.
  -- ⚠ THIS IS WHERE COLUMBUS MUST NOT BE COPIED. Columbus expects THREE here --
  -- its Mayor plus at-large Posts 9 and 10. Macon-Bibb has NO at-large seats
  -- (charter Sec. 9(a) and 9(c); all five GIS layers return nine polygons), so
  -- three would mean two commissioners had been hung on the wrong district.
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
    JOIN essentials.chambers c ON c.id = o.chamber_id
   WHERE c.government_id = v_gov AND c.name IN ('Macon-Bibb County Commission', 'Office of the Mayor')
     AND d.geo_id = '1349008' AND d.mtfcc = 'G4110' AND d.district_type = 'LOCAL';
  IF v_n <> 1 THEN RAISE EXCEPTION 'macon-bibb structure: expected 1 office(s) on Macon-Bibb Citywide, got %', v_n; END IF;

  -- 🔴 Ruling M2 must have SURVIVED generation. The Mayor presides, has a voice,
  -- and votes only to break a tie (charter Sec. 9(c)), so the seat is non_voting
  -- and ADR 0003 makes the note mandatory -- and both read paths must render it.
  -- A generator that dropped the note would satisfy every count above and be
  -- caught only by the CHECK, or NOT AT ALL if the seat had silently been
  -- written 'full', because a 'full' seat with no note is legal.
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
   WHERE c.government_id = v_gov AND o.title = 'Mayor'
     AND o.voting_powers = 'non_voting'
     AND o.representation_note IS NOT NULL AND length(o.representation_note) >= 200
     AND o.representation_note LIKE '%9(c)%';
  IF v_n <> 1 THEN RAISE EXCEPTION 'macon-bibb structure: expected 1 non_voting Mayor office carrying a substantive representation_note that cites charter Sec. 9(c), got %', v_n; END IF;

  -- And no full-voting city seat carries one: both read paths HIDE the note when
  -- voting_powers is 'full', so writing one there is prose nobody will ever see.
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
   WHERE c.government_id = v_gov AND c.name IN ('Macon-Bibb County Commission', 'Office of the Mayor')
     AND o.voting_powers = 'full' AND o.representation_note IS NOT NULL;
  IF v_n <> 0 THEN RAISE EXCEPTION 'macon-bibb structure: % full-voting seat(s) carry a representation_note that no read path renders', v_n; END IF;

  -- No role leaked out as its own office. Mayor Pro Tem is elected annually by
  -- the Commission from its own members, charter Sec. 9(f) -- ruling M3. It moved
  -- from Seth Clark to Valerie Wynn on 2026-01-06, which is exactly why it is a
  -- parenthetical on the District 1 seat title and not a row.
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
   WHERE c.government_id = v_gov AND c.name IN ('Macon-Bibb County Commission', 'Office of the Mayor')
     AND (o.title ILIKE '%pro tem%' OR o.title ILIKE '%pro-tem%' OR o.title ILIKE '%chair%' OR o.title ILIKE '%vice%');
  IF v_n <> 0 THEN RAISE EXCEPTION 'macon-bibb structure: % role(s) were created as offices -- ruling M3 says they are parentheticals', v_n; END IF;

  -- 🔴🔴 THE TIERS MUST NOT CROSS, AND A CROSSED TIER IS INVISIBLE HERE.
  -- The citywide LOCAL district and Bibb County's COUNTY district cover the SAME
  -- 254.906 sq mi. A city office hung on the COUNTY district would still resolve
  -- at every address in Macon and look completely correct -- only the tier would
  -- be wrong, and nothing would error. So assert that every city office sits on
  -- a LOCAL district. Task 4 asserts the mirror image for its five officers.
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE c.government_id = v_gov AND c.name IN ('Macon-Bibb County Commission', 'Office of the Mayor')
     AND d.district_type <> 'LOCAL';
  IF v_n <> 0 THEN RAISE EXCEPTION 'macon-bibb structure: % city office(s) sit on a district that is not LOCAL -- the tiers have crossed', v_n; END IF;

  -- 🔴 No office may sit on a district with no matching boundary: that is an
  -- office nobody can reach by address, and nothing else errors. Left
  -- government-wide on purpose -- the answer is 0 before and after Task 4.
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE c.government_id = v_gov
     AND NOT EXISTS (SELECT 1 FROM essentials.geofence_boundaries gb
                      WHERE gb.geo_id = d.geo_id AND gb.mtfcc = d.mtfcc);
  IF v_n <> 0 THEN RAISE EXCEPTION 'macon-bibb structure: % office(s) sit on a district with no matching boundary', v_n; END IF;

  RAISE NOTICE 'macon-bibb structure OK: 10 districts created, 1 government, 2 city chambers, 10 city offices (9 district commissioners + 1 non_voting Mayor, NO at-large seats)';
END $$;

COMMIT;
