-- CC_0004_nashville_structure.sql
-- Nashville deep-seed program, WAVE 1a (structure). Companion: CC_0005_nashville_metro_people.sql.
--
-- Creates the geography-and-seats half of the Metropolitan Government of
-- Nashville and Davidson County:
--   * 35 LOCAL districts -- Metro Council districts, mtfcc X0035
--   * 1 government, 2 chambers
--   * 42 offices -- 35 district council + 5 at-large + Vice Mayor + Mayor
--
-- Spec: .planning/todos/2026-08-27-nashville-davidson-deep-seed.md
-- Plan: docs/superpowers/plans/2026-08-27-nashville-wave-1a.md
-- Roster: data/seed-nashville-davidson-2026/ROSTERS.md
-- Generated by: scripts/gen-nashville-migrations.mjs
--
-- ---------------------------------------------------------------------------
-- 🔴 NASHVILLE IS A CONSOLIDATED CITY-COUNTY. There is no county commission.
-- The 40-member Metro Council is both the city and the county legislature, so
-- ONE government row covers both tiers, and its geo_id is the COUNTY polygon
-- 47037 -- NOT TIGER place 4752006, which is the metropolitan government
-- BALANCE and excludes six satellite cities (Belle Meade, Berry Hill, Forest
-- Hills, Goodlettsville, Oak Hill, Ridgetop) whose residents elect this same
-- council. Measured 2026-08-27: Belle Meade City Hall sits in council district
-- 23, Goodlettsville City Hall in 10. Using the place polygon would return no
-- representative for those addresses and nothing would error.
--
-- ---------------------------------------------------------------------------
-- 🔴 THE MULTI-SEAT TOP-UP IS SCOPED TO (chamber_id, district_id).
-- The Metropolitan Council chamber spans 36 districts. A chamber-scoped count is
-- the CA_0006 bug and would land seats on the wrong districts while reporting
-- the right total. The post-verify gate counts PER DISTRICT for the same reason:
-- a total-only assertion is exactly what the bug satisfies.
--
-- ---------------------------------------------------------------------------
-- 🔴 THE VICE MAYOR IS AN OFFICE, AND IT IS NOT A FULL-VOTING ONE.
-- Metropolitan Charter sec. 3.03: "The vice county mayor shall be the presiding
-- officer of the council, but without vote therein, except in the event of a tie
-- vote, when he may cast the deciding vote."
--
-- So Asheville's rule ("Vice Mayor is only a board role", CA_0009) does NOT
-- apply -- Nashville's Vice Mayor is elected countywide on their own ballot
-- line. But neither is the seat voting_powers 'full': the charter's default is
-- no vote. It is written 'non_voting' with the tie-break carried in
-- representation_note, which ADR 0003 then makes mandatory and both read paths
-- render.
--
-- chambers.official_count for the Council is 40, not 41. Charter sec. 15.01
-- provides for electing "a mayor, vice-mayor, five (5) councilmen-at-large and
-- thirty-five (35) district councilmen" -- the Vice Mayor is elected separately
-- and is not one of the 40.
--
-- IDEMPOTENT: every insert is NOT EXISTS-guarded or a target-count top-up.

BEGIN;

-- --- 0. Precondition: the council boundaries must already be loaded ---------
DO $$
DECLARE v_n int;
BEGIN
  SELECT count(*) INTO v_n FROM essentials.geofence_boundaries WHERE mtfcc = 'X0035';
  IF v_n <> 35 THEN
    RAISE EXCEPTION 'nashville structure: expected 35 X0035 boundaries, found % -- run scripts/load-davidson-council-boundaries.ts first', v_n;
  END IF;
END $$;

-- --- 1. Districts -----------------------------------------------------------
-- num_officials = 1: each council district elects one member. The 5 at-large
-- seats, the Vice Mayor and the Mayor hang off the EXISTING county district
-- 47037, which is not created here (verified 2026-08-27: it exists and
-- carries ZERO offices).
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-1', 'Nashville Metro Council District 1', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-1' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-2', 'Nashville Metro Council District 2', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-2' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-3', 'Nashville Metro Council District 3', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-3' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-4', 'Nashville Metro Council District 4', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-4' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-5', 'Nashville Metro Council District 5', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-5' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-6', 'Nashville Metro Council District 6', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-6' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-7', 'Nashville Metro Council District 7', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-7' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-8', 'Nashville Metro Council District 8', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-8' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-9', 'Nashville Metro Council District 9', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-9' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-10', 'Nashville Metro Council District 10', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-10' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-11', 'Nashville Metro Council District 11', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-11' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-12', 'Nashville Metro Council District 12', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-12' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-13', 'Nashville Metro Council District 13', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-13' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-14', 'Nashville Metro Council District 14', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-14' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-15', 'Nashville Metro Council District 15', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-15' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-16', 'Nashville Metro Council District 16', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-16' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-17', 'Nashville Metro Council District 17', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-17' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-18', 'Nashville Metro Council District 18', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-18' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-19', 'Nashville Metro Council District 19', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-19' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-20', 'Nashville Metro Council District 20', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-20' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-21', 'Nashville Metro Council District 21', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-21' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-22', 'Nashville Metro Council District 22', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-22' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-23', 'Nashville Metro Council District 23', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-23' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-24', 'Nashville Metro Council District 24', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-24' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-25', 'Nashville Metro Council District 25', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-25' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-26', 'Nashville Metro Council District 26', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-26' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-27', 'Nashville Metro Council District 27', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-27' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-28', 'Nashville Metro Council District 28', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-28' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-29', 'Nashville Metro Council District 29', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-29' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-30', 'Nashville Metro Council District 30', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-30' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-31', 'Nashville Metro Council District 31', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-31' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-32', 'Nashville Metro Council District 32', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-32' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-33', 'Nashville Metro Council District 33', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-33' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-34', 'Nashville Metro Council District 34', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-34' AND mtfcc = 'X0035'
);
INSERT INTO essentials.districts (geo_id, label, district_type, state, mtfcc, num_officials)
SELECT 'nashville-tn-council-district-35', 'Nashville Metro Council District 35', 'LOCAL', 'tn', 'X0035', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts WHERE geo_id = 'nashville-tn-council-district-35' AND mtfcc = 'X0035'
);

-- --- 2. Government ----------------------------------------------------------
-- ONE row, because the city and the county are one government. type 'City' with
-- city 'Nashville' is the primary label; the name carries both halves. Nothing
-- in the read path branches on governments.type (verified 2026-08-27).

INSERT INTO essentials.governments (name, type, state, city, geo_id)
SELECT 'Metropolitan Government of Nashville and Davidson County, Tennessee, US', 'City', 'TN', 'Nashville', '47037'
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.governments WHERE geo_id = '47037' AND type = 'City'
);

-- --- 3. Chambers ------------------------------------------------------------
-- chambers.slug is GENERATED from name_formal and cannot be inserted. Getting
-- name_formal wrong silently yields a different slug.

INSERT INTO essentials.chambers
  (government_id, name, name_formal, official_count, policy_engagement_level)
SELECT g.id, 'Metropolitan Council', 'Metropolitan Council of Nashville and Davidson County', 40, 'full'
FROM essentials.governments g
WHERE g.geo_id = '47037' AND g.type = 'City'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.chambers c
    WHERE c.government_id = g.id AND c.name = 'Metropolitan Council'
  );

INSERT INTO essentials.chambers
  (government_id, name, name_formal, official_count, policy_engagement_level)
SELECT g.id, 'Office of the Mayor', 'Office of the Mayor of Nashville and Davidson County', 1, 'full'
FROM essentials.governments g
WHERE g.geo_id = '47037' AND g.type = 'City'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.chambers c
    WHERE c.government_id = g.id AND c.name = 'Office of the Mayor'
  );

-- --- 4a. The 35 district council seats --------------------------------------
-- Each title is distinct, because Nashville numbers districts on the ballot. So
-- a NOT EXISTS-on-title guard is correct here and cannot collapse rows.
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 1', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-1' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 1'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 2', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-2' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 2'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 3', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-3' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 3'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 4', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-4' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 4'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 5', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-5' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 5'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 6', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-6' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 6'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 7', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-7' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 7'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 8', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-8' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 8'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 9', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-9' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 9'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 10', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-10' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 10'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 11', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-11' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 11'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 12', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-12' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 12'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 13', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-13' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 13'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 14', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-14' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 14'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 15', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-15' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 15'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 16', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-16' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 16'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 17', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-17' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 17'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 18', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-18' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 18'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 19', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-19' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 19'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 20', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-20' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 20'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 21', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-21' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 21'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 22', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-22' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 22'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 23', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-23' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 23'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 24', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-24' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 24'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 25', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-25' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 25'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 26', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-26' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 26'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 27', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-27' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 27'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 28', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-28' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 28'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 29', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-29' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 29'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 30', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-30' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 30'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 31', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-31' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 31'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 32', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-32' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 32'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 33', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-33' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 33'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 34', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-34' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 34'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member, District 35', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = 'nashville-tn-council-district-35' AND dd.mtfcc = 'X0035' AND dd.district_type = 'LOCAL'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member, District 35'
  );

-- --- 4b. The 5 at-large seats, IDENTICAL titles -----------------------------
-- Nashville does not number the at-large seats; the top five vote-getters win,
-- so the five offices are genuinely interchangeable and share one title.
-- Guarded by a target-count top-up, because NOT EXISTS-on-title would collapse
-- five rows to one on a re-run.
--
-- 🔴 The count is scoped to (chamber_id, district_id). This chamber spans 36
-- districts, so a chamber-scoped count here is the CA_0006 bug outright.

INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Council Member at-Large', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = '47037' AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'tn'
) d
CROSS JOIN LATERAL (
  SELECT generate_series(1, 5 - (
    SELECT count(*) FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Council Member at-Large'
  )) AS n
) gs
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council';

-- --- 4c. Vice Mayor ---------------------------------------------------------
-- See the header. non_voting + a mandatory note, per Charter sec. 3.03.

INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers, representation_note)
SELECT c.id, d.id, 'Vice Mayor', 'TN', 'Nashville', 'non_voting', 'The Vice Mayor is elected countywide and presides over the 40-member Metropolitan Council. Under Section 3.03 of the Metropolitan Charter, the Vice Mayor does not vote on Council business, except to cast the deciding vote when the Council is tied. The Vice Mayor also serves as Mayor if the office of Mayor becomes vacant.'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = '47037' AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'tn'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Metropolitan Council'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o WHERE o.chamber_id = c.id AND o.title = 'Vice Mayor'
  );

-- --- 4d. Mayor --------------------------------------------------------------

INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city)
SELECT c.id, d.id, 'Mayor', 'TN', 'Nashville'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
  WHERE dd.geo_id = '47037' AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'tn'
) d
WHERE g.geo_id = '47037' AND g.type = 'City' AND c.name = 'Office of the Mayor'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o WHERE o.chamber_id = c.id AND o.title = 'Mayor'
  );

-- --- 5. Post-verify gate ----------------------------------------------------
DO $$
DECLARE v_n int; v_d int; v_nogeom int; v_vm int; v_city int;
BEGIN
  SELECT count(*) INTO v_n FROM essentials.districts WHERE mtfcc = 'X0035';
  IF v_n <> 35 THEN RAISE EXCEPTION 'nashville structure: expected 35 X0035 districts, got %', v_n; END IF;

  -- 🔴 PER-DISTRICT, not 35 in total. A total-only assertion is exactly what a
  -- chamber-scoped top-up satisfies while stacking seats on one district.
  FOR v_d IN 1..35 LOOP
    SELECT count(*) INTO v_n FROM essentials.offices o
      JOIN essentials.districts d ON d.id = o.district_id
     WHERE d.geo_id = 'nashville-tn-council-district-' || v_d AND d.mtfcc = 'X0035';
    IF v_n <> 1 THEN RAISE EXCEPTION 'nashville structure: council district % carries % offices, expected exactly 1', v_d, v_n; END IF;
  END LOOP;

  -- The county polygon carries the 5 at-large seats + Vice Mayor + Mayor.
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE d.geo_id = '47037' AND d.district_type = 'COUNTY';
  IF v_n <> 7 THEN RAISE EXCEPTION 'nashville structure: expected 7 offices on the Davidson county polygon, got %', v_n; END IF;

  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE d.geo_id = '47037' AND d.district_type = 'COUNTY' AND o.title = 'Council Member at-Large';
  IF v_n <> 5 THEN RAISE EXCEPTION 'nashville structure: expected 5 at-large offices, got %', v_n; END IF;

  -- 🔴 The Davidson County LABEL exists in TWO states -- NC 37057 and TN 47037.
  -- Assert nothing landed on the North Carolina row, which a label-based join
  -- would have hit and no office count on the TN row would notice.
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE d.geo_id = '37057' AND d.district_type = 'COUNTY';
  IF v_n <> 0 THEN RAISE EXCEPTION 'nashville structure: % office(s) landed on Davidson County, NORTH CAROLINA', v_n; END IF;

  -- The Vice Mayor seat: exactly one, non_voting, and carrying a substantive
  -- note. The note is the whole reason the seat is legible to a voter.
  SELECT count(*) INTO v_vm FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE d.geo_id = '47037' AND o.title = 'Vice Mayor'
     AND o.voting_powers = 'non_voting'
     AND o.representation_note IS NOT NULL AND length(trim(o.representation_note)) > 80;
  IF v_vm <> 1 THEN RAISE EXCEPTION 'nashville structure: expected 1 non_voting Vice Mayor office with a substantive representation_note, got %', v_vm; END IF;

  -- Every Metro seat must carry the city, or the Nashville banner never
  -- resolves from data.
  SELECT count(*) INTO v_city FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE (d.mtfcc = 'X0035' OR (d.geo_id = '47037' AND d.district_type = 'COUNTY'))
     AND (o.representing_city IS DISTINCT FROM 'Nashville' OR o.representing_state IS DISTINCT FROM 'TN');
  IF v_city <> 0 THEN RAISE EXCEPTION 'nashville structure: % Metro office(s) missing representing_city/state', v_city; END IF;

  -- No office may sit on a district with no geometry: unreachable by address,
  -- and nothing else would say so.
  SELECT count(*) INTO v_nogeom FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE d.mtfcc = 'X0035'
     AND NOT EXISTS (
       SELECT 1 FROM essentials.geofence_boundaries b
        WHERE b.geo_id = d.geo_id AND b.mtfcc = d.mtfcc
     );
  IF v_nogeom <> 0 THEN RAISE EXCEPTION 'nashville structure: % office(s) sit on a district with no matching boundary', v_nogeom; END IF;

  RAISE NOTICE 'nashville structure OK -- 42 offices across 35 council districts and the Davidson county polygon.';
END $$;

COMMIT;
