-- CC_0028_milledgeville_people.sql
--
-- Knight Foundation cities program, wave GA-3, CITY OCCUPANCY half.
--   * 7 politicians, 7 open-ended terms, 0 vacancies
--
-- Plan:   docs/superpowers/plans/2026-09-01-knight-ga-wave-3-milledgeville-baldwin.md
-- Roster: backend/data/seed-milledgeville-2026/ROSTERS.md
-- Generated by scripts/gen-ga3-milledgeville-migrations.mjs.
--
-- ⚠ THIS HALF CANNOT BE DRY-RUN ALONE -- its offices do not exist until the
--   structure half runs. Run both as ONE transaction ending in ROLLBACK and
--   assert the stream holds exactly one BEGIN, one ROLLBACK and ZERO COMMIT.
--
-- ---------------------------------------------------------------------------
-- THE ROSTER, CERTIFIED BY THE GEORGIA SECRETARY OF STATE
--
-- November 4 2025 municipal general, certified as of 2025-11-21, 6 of 6 units
-- reporting. 🟢 The SOS publishes certified MUNICIPAL results -- nothing in the
-- Florida slice used that route, and it settled every seat here.
--
--   Mayor      Mary Parham-Copelan    1,235 / 2,330 (53.0%) def. Walter Reynolds
--   District 1 Collinda J. Lee          377, unopposed
--   District 2 Arlene Simmons           108 / 216 -- see the note below
--   District 3 Denese Ray Shinholster   248, unopposed
--   District 4 Morgan Pendergast         79, unopposed
--   District 5 Shonya A. Mapp           498, unopposed
--   District 6 Jeffery C. Wells         456 / 730 (62.5%) def. Kayla Brownlow
--
-- 🔴 THREE SEATS CHANGED HANDS, AND ONE PERSON'S MOVE EXPLAINS ONE OF THEM.
--    Walter Reynolds vacated District 4 to run for Mayor, and lost. Walden (D2)
--    and Chambers (D6) do not appear on the 2025 ballot at all. Baldwin County's
--    ArcGIS layer still names all three predecessors, and the Georgia Municipal
--    Association directory lists NINE members for a six-seat council because it
--    accumulates and has no dateVacated field.
--
-- ⚠ DISTRICT 2's ARITHMETIC DOES NOT CLOSE, AND IT IS RECORDED, NOT EXPLAINED.
--   108 of 216 is exactly 50.0%, not a majority. The Union-Recorder reported
--   five write-ins pending a panel review; the certified sheet carries no
--   write-in option and sums to 216. Baldwin held NO runoff -- it is absent from
--   the December 2 2025 runoff results, which return HTTP 204 for this county.
--   Plurality election is the likely explanation and is NOT confirmed, because
--   the only published charter is the 2014 one. Simmons holds the seat by the
--   certified count, by the city's own roster, and by the absence of any
--   successor contest.
--
-- 🔴 RULING R4: ALL SEVEN TERMS ARE OPEN-ENDED AT 'unknown'. The certified
--    election date above is NOT a term_start: term_start is the start of
--    CONTINUOUS occupancy, which re-election does not end, and four of these
--    seven are incumbents whose occupancy predates 2025. Milledgeville publishes
--    no service-start and no swearing-in date. No date is invented.

BEGIN;

-- --- Politician identity band ----------------------------------------------
-- 🔴 NOBODY ELSE MAY ALREADY OWN THE IDS THIS WAVE IS ABOUT TO INSERT. That is
-- the FL-2 failure exactly: a band collided with 166 existing rows and
-- ON CONFLICT DO NOTHING would have absorbed it in silence, leaving seats held
-- by whoever already owned those ids.
--
-- ⚠ SCOPED TO THIS WAVE'S OWN SUB-RANGE, per the FL-4 correction. A guard over
-- the whole shared band makes a neighbouring wave's legitimate rows look foreign
-- and breaks this migration's OWN re-run. Excluding our own ids keeps it
-- idempotent.
DO $$
DECLARE v_n int; v_foreign text;
BEGIN
  SELECT count(*), string_agg(external_id::text, ', ' ORDER BY external_id)
    INTO v_n, v_foreign
    FROM essentials.politicians
   WHERE external_id BETWEEN -1331007 AND -1331001
     AND external_id NOT IN (-1331007, -1331006, -1331005, -1331004, -1331003, -1331002, -1331001);
  IF v_n <> 0 THEN
    RAISE EXCEPTION 'milledgeville people: % row(s) inside this wave''s id range -1331007..-1331001 are owned by something else (%). Pick another sub-range rather than colliding.', v_n, v_foreign;
  END IF;
END $$;

-- 🔴 IDENTITY IS KEYED ON external_id, NEVER ON NAME. All 7 names in this half
-- were checked against production 2026-09-01 with a POSITIVE CONTROL (Floyd
-- Griffin, seated by GA-2, returns exactly 1) and none matched, so all are fresh
-- inserts and nothing is reused. A name-based guard is what seated a Wisconsin
-- village trustee on the Nashville council and a Colorado senator in Georgia.

CREATE TEMP TABLE mv_seed (
  geo_id          text,
  mtfcc           text,
  district_type   text,
  office_title    text,
  ext_id          bigint,
  full_name       text,
  first_name      text,
  last_name       text,
  middle_initial  text,
  name_suffix     text,
  aliases         text[],
  term_start      date,
  start_precision text,
  how_started     text,
  source          text
) ON COMMIT DROP;

INSERT INTO mv_seed VALUES
  ('1351492', 'G4110', 'LOCAL', 'Mayor', -1331001, 'Mary Parham-Copelan', 'Mary', 'Parham-Copelan', NULL, NULL, ARRAY['Mary Parham Copelan']::text[], NULL::date, 'unknown', 'elected', 'gasos-certified-2025-11-04-municipal-general'),
  ('milledgeville-ga-council-district-1', 'X0042', 'LOCAL', 'Council Member, District 1', -1331002, 'Collinda J. Lee', 'Collinda', 'Lee', 'J.', NULL, '{}'::text[], NULL::date, 'unknown', 'elected', 'gasos-certified-2025-11-04-municipal-general'),
  ('milledgeville-ga-council-district-2', 'X0042', 'LOCAL', 'Council Member, District 2', -1331003, 'Arlene Simmons', 'Arlene', 'Simmons', NULL, NULL, '{}'::text[], NULL::date, 'unknown', 'elected', 'gasos-certified-2025-11-04-municipal-general'),
  ('milledgeville-ga-council-district-3', 'X0042', 'LOCAL', 'Council Member, District 3', -1331004, 'Denese Ray Shinholster', 'Denese', 'Shinholster', 'Ray', NULL, ARRAY['Denese R. Shinholster']::text[], NULL::date, 'unknown', 'elected', 'gasos-certified-2025-11-04-municipal-general'),
  ('milledgeville-ga-council-district-4', 'X0042', 'LOCAL', 'Council Member, District 4', -1331005, 'Morgan Pendergast', 'Morgan', 'Pendergast', NULL, NULL, '{}'::text[], NULL::date, 'unknown', 'elected', 'gasos-certified-2025-11-04-municipal-general'),
  ('milledgeville-ga-council-district-5', 'X0042', 'LOCAL', 'Council Member, District 5', -1331006, 'Shonya A. Mapp', 'Shonya', 'Mapp', 'A.', NULL, '{}'::text[], NULL::date, 'unknown', 'elected', 'gasos-certified-2025-11-04-municipal-general'),
  ('milledgeville-ga-council-district-6', 'X0042', 'LOCAL', 'Council Member, District 6', -1331007, 'Jeffery C. Wells', 'Jeffery', 'Wells', 'C.', NULL, '{}'::text[], NULL::date, 'unknown', 'elected', 'gasos-certified-2025-11-04-municipal-general');

-- --- Payload guard ----------------------------------------------------------
DO $$
DECLARE v_n int; v_dup int;
BEGIN
  SELECT count(*) INTO v_n FROM mv_seed;
  IF v_n <> 7 THEN RAISE EXCEPTION 'milledgeville people payload: expected 7 rows, got %', v_n; END IF;

  SELECT count(*) INTO v_dup FROM (SELECT ext_id FROM mv_seed GROUP BY ext_id HAVING count(*) > 1) x;
  IF v_dup <> 0 THEN RAISE EXCEPTION 'milledgeville people payload: % duplicate external_id(s)', v_dup; END IF;

  SELECT count(*) INTO v_n FROM mv_seed WHERE ext_id NOT BETWEEN -1331018 AND -1331001;
  IF v_n <> 0 THEN RAISE EXCEPTION 'milledgeville people payload: % out-of-band external_id(s)', v_n; END IF;

  -- Every (geo_id, mtfcc, district_type, title) is a single seat in this wave.
  SELECT count(*) INTO v_dup FROM (
    SELECT geo_id, mtfcc, district_type, office_title FROM mv_seed
    GROUP BY geo_id, mtfcc, district_type, office_title HAVING count(*) > 1
  ) x;
  IF v_dup <> 0 THEN RAISE EXCEPTION 'milledgeville people payload: % duplicate seat key(s)', v_dup; END IF;

  -- 🔴 RULING R4: every row in this wave has NO term_start and MUST declare
  -- 'unknown'. Georgia publishes no service-start for either body.
  SELECT count(*) INTO v_n FROM mv_seed WHERE term_start IS NULL AND start_precision <> 'unknown';
  IF v_n <> 0 THEN RAISE EXCEPTION 'milledgeville people payload: % row(s) have no term_start but claim a precision', v_n; END IF;
  SELECT count(*) INTO v_n FROM mv_seed WHERE term_start IS NOT NULL;
  IF v_n <> 0 THEN RAISE EXCEPTION 'milledgeville people payload: % row(s) carry a term_start, which ruling R4 says is not sourced for this wave', v_n; END IF;

  -- ⚠ alternate_names is NOT NULL DEFAULT '{}'. Emit an empty array, never NULL.
  SELECT count(*) INTO v_n FROM mv_seed WHERE aliases IS NULL;
  IF v_n <> 0 THEN RAISE EXCEPTION 'milledgeville people payload: % row(s) carry a NULL aliases array', v_n; END IF;

  -- And every seat named must resolve to exactly one office in prod.
  SELECT count(*) INTO v_n FROM mv_seed s
   WHERE (SELECT count(*) FROM essentials.offices o
            JOIN essentials.districts d ON d.id = o.district_id
           WHERE d.geo_id = s.geo_id AND d.mtfcc = s.mtfcc
             AND d.district_type = s.district_type AND lower(d.state) = 'ga'
             AND o.title = s.office_title) <> 1;
  IF v_n <> 0 THEN RAISE EXCEPTION 'milledgeville people payload: % seat(s) do not resolve to exactly one office -- run the structure half first', v_n; END IF;
END $$;

-- --- Politicians ------------------------------------------------------------
INSERT INTO essentials.politicians
  (external_id, full_name, first_name, last_name, middle_initial, name_suffix,
   alternate_names, is_incumbent, is_active, data_source)
SELECT s.ext_id, s.full_name, s.first_name, s.last_name,
       nullif(s.middle_initial, ''), nullif(s.name_suffix, ''),
       s.aliases, true, true, s.source
FROM mv_seed s
ON CONFLICT (external_id) DO NOTHING;

-- --- Occupancy --------------------------------------------------------------
-- 🔴 EVERY ROW IN THIS WAVE TAKES THE DIRECT-INSERT PATH, because
-- essentials.seat_officeholder() REFUSES a NULL term_start ("pass Jan 1 with
-- p_start_precision => 'year' rather than NULL") and ruling R4 has no date to
-- pass. Inventing Jan 1 of a guessed year is a false statement about history
-- that no end_precision exists to soften.
--
-- The schema allows the honest record and prod is full of it: the ADR 0002
-- phase-2 backfill wrote 81,676 'unknown'-precision rows with term_start NULL.
-- Only the HELPER refuses it.
--
-- Direct insert is safe ONLY into an office with zero existing term rows: the
-- helper's two-step exists to close a predecessor before an open-ended range
-- overlaps it, and with no predecessor there is nothing to close and the
-- exclusion constraint cannot fire. The guard REFUSES rather than guesses if
-- that stops being true.
DO $$
DECLARE r record; v_blank int := 0; v_prior int;
BEGIN
  FOR r IN
    SELECT s.start_precision, s.how_started, s.source,
           o.id AS office_id, p.id AS politician_id
      FROM mv_seed s
      JOIN essentials.districts d
        ON d.geo_id = s.geo_id AND d.mtfcc = s.mtfcc
       AND d.district_type = s.district_type AND lower(d.state) = 'ga'
      JOIN essentials.offices o ON o.district_id = d.id AND o.title = s.office_title
      JOIN essentials.politicians p ON p.external_id = s.ext_id
     WHERE NOT EXISTS (
       SELECT 1 FROM essentials.office_terms t
        WHERE t.office_id = o.id AND t.politician_id = p.id
     )
  LOOP
    IF r.start_precision <> 'unknown' THEN
      RAISE EXCEPTION 'milledgeville people: office % has no term_start but claims precision % -- refusing', r.office_id, r.start_precision;
    END IF;
    SELECT count(*) INTO v_prior FROM essentials.office_terms t WHERE t.office_id = r.office_id;
    IF v_prior <> 0 THEN
      RAISE EXCEPTION 'milledgeville people: office % already carries % term row(s), so an undated open term cannot be inserted directly -- close the predecessor and give this person a real date', r.office_id, v_prior;
    END IF;
    INSERT INTO essentials.office_terms
      (office_id, politician_id, term_start, term_end, start_precision, how_started, source)
    VALUES (r.office_id, r.politician_id, NULL, NULL, 'unknown', r.how_started, r.source);
    v_blank := v_blank + 1;
  END LOOP;
  RAISE NOTICE 'milledgeville people: seated % official(s), every one with an honest unknown start', v_blank;
END $$;

-- --- Post-verify gate ------------------------------------------------------
DO $$
DECLARE v_gov uuid; v_pol int; v_seated int; v_n int; v_d text;
BEGIN
  SELECT id INTO v_gov FROM essentials.governments
   WHERE geo_id = '1351492' AND type = 'City';
  IF v_gov IS NULL THEN RAISE EXCEPTION 'milledgeville people: the government row is missing'; END IF;

  SELECT count(*) INTO v_pol FROM essentials.politicians
   WHERE external_id BETWEEN -1331007 AND -1331001;
  IF v_pol <> 7 THEN RAISE EXCEPTION 'milledgeville people: expected 7 politicians in -1331007..-1331001, got %', v_pol; END IF;

  -- 🔴 office_current_holder LEFT JOINs from offices, so a vacancy is a NULL
  -- politician_id, NEVER an absent row. count(*) would pass VACUOUSLY.
  SELECT count(och.politician_id) INTO v_seated
    FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
    JOIN essentials.office_current_holder och ON och.office_id = o.id
   WHERE c.government_id = v_gov;
  IF v_seated <> 7 THEN RAISE EXCEPTION 'milledgeville people: expected 7 seated officials, got %', v_seated; END IF;

  -- Exactly one holder per numbered district.
  FOR v_d IN SELECT 'milledgeville-ga-council-district-' || gs FROM generate_series(1,6) gs LOOP
    SELECT count(och.politician_id) INTO v_n
      FROM essentials.districts d
      JOIN essentials.offices o ON o.district_id = d.id
      JOIN essentials.office_current_holder och ON och.office_id = o.id
     WHERE d.geo_id = v_d AND d.mtfcc = 'X0042' AND d.district_type = 'LOCAL';
    IF v_n <> 1 THEN RAISE EXCEPTION 'milledgeville people: district % has % holder(s), expected exactly 1', v_d, v_n; END IF;
  END LOOP;

  -- Every term is open-ended at 'unknown' (ruling R4), and NO term_end was
  -- written: a future term_end makes a seat silently self-vacate.
  SELECT count(*) INTO v_n
    FROM essentials.office_terms t
    JOIN essentials.politicians p ON p.id = t.politician_id
   WHERE p.external_id BETWEEN -1331007 AND -1331001
     AND (t.start_precision <> 'unknown' OR t.term_start IS NOT NULL OR t.term_end IS NOT NULL);
  IF v_n <> 0 THEN RAISE EXCEPTION 'milledgeville people: % term row(s) are not an open-ended unknown-precision term', v_n; END IF;

  -- No office in this government may be left with no term row at all: that is
  -- the invisible-office failure, and nothing else errors.
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
   WHERE c.government_id = v_gov
     AND NOT EXISTS (SELECT 1 FROM essentials.office_terms t WHERE t.office_id = o.id);
  IF v_n <> 0 THEN RAISE EXCEPTION 'milledgeville people: % office(s) carry no office_terms row and are invisible', v_n; END IF;

  RAISE NOTICE 'milledgeville people OK: 7 politicians, 7 seated across 7 offices, 0 vacancies';
END $$;

COMMIT;
