-- CC_0015_miami_structure.sql
-- Knight Foundation cities program, wave FL-6. Companion: CC_0016_miami_people.sql.
--
-- Creates the geography-and-seats half of the City of Miami:
--   * 5 new LOCAL districts (mtfcc X0041) + 1 citywide LOCAL district (TIGER place 1245000)
--   * 1 government, 2 chambers -- the Mayor is NOT a member of the Commission
--   * 6 offices -- 5 single-member commissioners + the Mayor
--
-- Spec:   docs/superpowers/specs/2026-08-28-knight-cities-program-design.md
-- Plan:   docs/superpowers/plans/2026-08-29-knight-fl-wave-6-miami-miami-dade.md
-- Slice:  .planning/knight-foundation/fl.md
-- Roster: data/seed-miami-dade-2026/ROSTERS.md
-- Generated by: scripts/gen-miami-dade-migrations.mjs
--
-- ---------------------------------------------------------------------------
-- 🔴 EVERY DISTRICT LOOKUP PAIRS geo_id WITH mtfcc AND district_type, and every
-- CHAMBER lookup is scoped by its GOVERNMENT. This wave seats TWO governments
-- over one anchor: 'Office of the Mayor' is a chamber in both, and 'Mayor' and
-- 'Commissioner, District 1'..'District 5' are office titles in both. A lookup
-- on name alone matches two rows and the insert fans out.
--
-- ---------------------------------------------------------------------------
-- No party affiliation is recorded. Party lives on races.primary_party.
--
-- No term_end is written. A future term_end makes a seat silently self-vacate,
-- and office_terms has no end_precision, so a published expiry cannot become a
-- term_end without inventing a day. The SOE's "Current Term Ends" column is
-- deliberately NOT written.

-- ---------------------------------------------------------------------------
-- 🔴 THE MAYOR IS NOT A COMMISSIONER, WHICH INVERTS FL-4's SHAPE.
--
-- Tallahassee's mayor is SEAT 4 of a five-member at-large commission -- one
-- chamber, five seats on one district. Miami's Mayor is a separate executive
-- elected citywide, and the five commissioners are elected from single-member
-- districts. So: TWO chambers, and the citywide district carries exactly ONE
-- office where Tallahassee's carries five.
--
-- ⚠ Chair and Vice Chair ARE NOT OFFICES. The Commission elects them from among
-- its own members; Christine King (D5) was reappointed Chair on 2025-12-22. Same
-- ruling as Bradenton's and Asheville's Vice Mayor.
--
-- ⚠ City Manager, City Clerk and City Attorney are APPOINTED. miami.gov lists
-- them beside the six elected officials; they are not offices in this wave.
--
-- ---------------------------------------------------------------------------
-- 🔴 THE FIVE DISTRICTS ARE THE MAY 2024 SETTLEMENT MAP.
--
-- Miami's 2022 and 2023 commission maps were BOTH held unconstitutionally
-- racially gerrymandered by Judge K. Michael Moore in April 2024. The map in
-- force is the one the Commission adopted 4-1 in a May 2024 settlement, drawn by
-- the plaintiffs. X0041 carries that map, and its loader refuses to run against
-- the 2017 "Enriched Commission Districts" vintage that is still published with
-- identical field names.

BEGIN;

-- --- 0. Pre-flight ----------------------------------------------------------
DO $$
DECLARE v_n int;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM essentials.geofence_boundaries
     WHERE geo_id = '1245000' AND mtfcc = 'G4110'
  ) THEN
    RAISE EXCEPTION 'miami structure: TIGER place 1245000/G4110 is missing -- FL-1 must be applied first; the Mayor hangs off it';
  END IF;

  SELECT count(*) INTO v_n FROM essentials.geofence_boundaries WHERE mtfcc = 'X0041';
  IF v_n <> 5 THEN
    RAISE EXCEPTION 'miami structure: expected 5 X0041 boundaries, found % -- run scripts/load-miami-city-commission-boundaries.ts first', v_n;
  END IF;
END $$;

-- --- 1. The citywide district (the Mayor only) ------------------------------
-- ⚠ num_officials is 1, NOT Tallahassee's 5. Only the Mayor is elected citywide.

INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'LOCAL', 'Miami Citywide', 'fl', '1245000', 'G4110', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = '1245000' AND mtfcc = 'G4110' AND district_type = 'LOCAL'
);

-- --- 2. The five single-member commission districts -------------------------

INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'LOCAL', 'Miami City Commission District 1', 'fl', 'miami-fl-commission-district-1', 'X0041', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'miami-fl-commission-district-1' AND mtfcc = 'X0041' AND district_type = 'LOCAL'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'LOCAL', 'Miami City Commission District 2', 'fl', 'miami-fl-commission-district-2', 'X0041', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'miami-fl-commission-district-2' AND mtfcc = 'X0041' AND district_type = 'LOCAL'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'LOCAL', 'Miami City Commission District 3', 'fl', 'miami-fl-commission-district-3', 'X0041', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'miami-fl-commission-district-3' AND mtfcc = 'X0041' AND district_type = 'LOCAL'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'LOCAL', 'Miami City Commission District 4', 'fl', 'miami-fl-commission-district-4', 'X0041', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'miami-fl-commission-district-4' AND mtfcc = 'X0041' AND district_type = 'LOCAL'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'LOCAL', 'Miami City Commission District 5', 'fl', 'miami-fl-commission-district-5', 'X0041', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'miami-fl-commission-district-5' AND mtfcc = 'X0041' AND district_type = 'LOCAL'
);

-- --- 3. Government ----------------------------------------------------------

INSERT INTO essentials.governments (name, type, state, city, geo_id)
SELECT 'City of Miami, Florida, US', 'City', 'FL', 'Miami', '1245000'
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.governments WHERE geo_id = '1245000' AND type = 'City'
);

-- --- 4. Chambers ------------------------------------------------------------
-- chambers.slug is GENERATED from name_formal and cannot be inserted.
-- ⚠ 'Office of the Mayor' also exists in the COUNTY government. name_formal
--    differs, so the generated slugs differ and the rows cannot collide.

INSERT INTO essentials.chambers
  (government_id, name, name_formal, official_count, policy_engagement_level)
SELECT g.id, 'City Commission', 'Miami City Commission', 5, 'full'
FROM essentials.governments g
WHERE g.geo_id = '1245000' AND g.type = 'City'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.chambers c
     WHERE c.government_id = g.id AND c.name = 'City Commission'
  );

INSERT INTO essentials.chambers
  (government_id, name, name_formal, official_count, policy_engagement_level)
SELECT g.id, 'Office of the Mayor', 'City of Miami Office of the Mayor', 1, 'full'
FROM essentials.governments g
WHERE g.geo_id = '1245000' AND g.type = 'City'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.chambers c
     WHERE c.government_id = g.id AND c.name = 'Office of the Mayor'
  );

-- --- 5. Offices -------------------------------------------------------------

INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Mayor', 'FL', 'Miami', 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = '1245000' AND dd.mtfcc = 'G4110'
     AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '1245000' AND g.type = 'City' AND c.name = 'Office of the Mayor'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Mayor'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 1', 'FL', 'Miami', 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'miami-fl-commission-district-1' AND dd.mtfcc = 'X0041'
     AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '1245000' AND g.type = 'City' AND c.name = 'City Commission'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 1'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 2', 'FL', 'Miami', 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'miami-fl-commission-district-2' AND dd.mtfcc = 'X0041'
     AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '1245000' AND g.type = 'City' AND c.name = 'City Commission'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 2'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 3', 'FL', 'Miami', 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'miami-fl-commission-district-3' AND dd.mtfcc = 'X0041'
     AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '1245000' AND g.type = 'City' AND c.name = 'City Commission'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 3'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 4', 'FL', 'Miami', 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'miami-fl-commission-district-4' AND dd.mtfcc = 'X0041'
     AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '1245000' AND g.type = 'City' AND c.name = 'City Commission'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 4'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 5', 'FL', 'Miami', 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'miami-fl-commission-district-5' AND dd.mtfcc = 'X0041'
     AND dd.district_type = 'LOCAL' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '1245000' AND g.type = 'City' AND c.name = 'City Commission'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 5'
  );

-- --- 6. Post-verify gate ----------------------------------------------------
DO $$
DECLARE v_n int; v_gov uuid; v_d text; v_t text;
BEGIN
  SELECT count(*) INTO v_n FROM essentials.districts
   WHERE mtfcc = 'X0041' AND district_type = 'LOCAL' AND lower(state) = 'fl';
  IF v_n <> 5 THEN RAISE EXCEPTION 'miami structure: expected 5 X0041 districts, got %', v_n; END IF;

  SELECT count(*) INTO v_n FROM essentials.districts
   WHERE geo_id = '1245000' AND mtfcc = 'G4110' AND district_type = 'LOCAL';
  IF v_n <> 1 THEN RAISE EXCEPTION 'miami structure: expected exactly 1 citywide district, got %', v_n; END IF;

  SELECT id INTO v_gov FROM essentials.governments
   WHERE geo_id = '1245000' AND type = 'City';
  IF v_gov IS NULL THEN RAISE EXCEPTION 'miami structure: the government row is missing'; END IF;

  -- 🔴 TWO chambers, not Tallahassee's one. The Mayor is not a commissioner.
  SELECT count(*) INTO v_n FROM essentials.chambers WHERE government_id = v_gov;
  IF v_n <> 2 THEN RAISE EXCEPTION 'miami structure: expected 2 chambers, got % -- Miami''s Mayor is a separate executive, not a seat on the Commission', v_n; END IF;

  SELECT count(*) INTO v_n FROM essentials.chambers
   WHERE government_id = v_gov AND ((name = 'City Commission' AND official_count = 5)
                                 OR (name = 'Office of the Mayor' AND official_count = 1));
  IF v_n <> 2 THEN RAISE EXCEPTION 'miami structure: chamber names or official_counts are wrong'; END IF;

  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
   WHERE c.government_id = v_gov;
  IF v_n <> 6 THEN RAISE EXCEPTION 'miami structure: expected 6 offices, got %', v_n; END IF;

  -- PER DISTRICT: exactly one commissioner on each of the five.
  FOR v_d IN SELECT 'miami-fl-commission-district-' || g FROM generate_series(1,5) g LOOP
    SELECT count(*) INTO v_n FROM essentials.offices o
      JOIN essentials.districts d ON d.id = o.district_id
     WHERE d.geo_id = v_d AND d.mtfcc = 'X0041' AND d.district_type = 'LOCAL';
    IF v_n <> 1 THEN RAISE EXCEPTION 'miami structure: city district % carries % offices, expected exactly 1', v_d, v_n; END IF;
  END LOOP;

  -- 🔴 EXACTLY ONE OFFICE ON THE CITYWIDE DISTRICT -- the Mayor, and nothing else.
  -- Tallahassee's equivalent expects 5. If this reads 2 a commissioner was mapped
  -- citywide and now appears for every address in Miami.
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
    JOIN essentials.chambers c ON c.id = o.chamber_id
   WHERE c.government_id = v_gov AND d.geo_id = '1245000'
     AND d.mtfcc = 'G4110' AND d.district_type = 'LOCAL';
  IF v_n <> 1 THEN RAISE EXCEPTION 'miami structure: expected exactly 1 office on the citywide district (the Mayor), got %', v_n; END IF;

  -- ...and no commissioner may be among them, stated directly.
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
    JOIN essentials.chambers c ON c.id = o.chamber_id
   WHERE c.government_id = v_gov AND c.name = 'City Commission'
     AND d.geo_id = '1245000' AND d.mtfcc = 'G4110';
  IF v_n <> 0 THEN RAISE EXCEPTION 'miami structure: % commissioner office(s) landed on the citywide district -- Miami has no at-large commissioner', v_n; END IF;

  SELECT count(DISTINCT o.title) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
   WHERE c.government_id = v_gov;
  IF v_n <> 6 THEN RAISE EXCEPTION 'miami structure: expected 6 DISTINCT seat titles, got %', v_n; END IF;

  -- 🔴 THE THREE FORBIDDEN TITLES, IN THE CITY GOVERNMENT TOO. This generator
  -- descends from Leon's, where Superintendent of Schools is a live entry.
  FOR v_t IN SELECT unnest(ARRAY['Superintendent of Schools', 'State Attorney', 'Public Defender']) LOOP
    SELECT count(*) INTO v_n FROM essentials.offices o
      JOIN essentials.chambers c ON c.id = o.chamber_id
     WHERE c.government_id = v_gov AND o.title = v_t;
    IF v_n <> 0 THEN RAISE EXCEPTION 'miami structure: % must NOT be seated, found % office(s)', v_t, v_n; END IF;
  END LOOP;

  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE c.government_id = v_gov AND lower(d.state) <> 'fl';
  IF v_n <> 0 THEN RAISE EXCEPTION 'miami structure: % office(s) landed outside Florida', v_n; END IF;

  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE c.government_id = v_gov
     AND NOT EXISTS (SELECT 1 FROM essentials.geofence_boundaries gb
                      WHERE gb.geo_id = d.geo_id AND gb.mtfcc = d.mtfcc);
  IF v_n <> 0 THEN RAISE EXCEPTION 'miami structure: % office(s) sit on a district with no matching boundary', v_n; END IF;

  RAISE NOTICE 'miami structure OK: 5 district + 1 citywide, 1 government, 2 chambers, 6 offices';
END $$;

COMMIT;
