-- CC_0010_manatee_county.sql
-- Knight Foundation cities program, wave FL-3.
--
-- Creates Manatee County whole -- offices AND people in ONE migration, per spec section 3:
--   * 5 new COUNTY districts (mtfcc X0037); the countywide district ALREADY EXISTS
--   * 1 government, 2 chambers
--   * 12 offices -- 7 commissioners + 5 constitutional officers
--   * 11 politicians and 11 terms; District 1 is VACANT
--
-- Spec:   docs/superpowers/specs/2026-08-28-knight-cities-program-design.md
-- Plan:   docs/superpowers/plans/2026-08-28-knight-fl-wave-3-bradenton-manatee.md
-- Slice:  .planning/knight-foundation/fl.md
-- Roster: data/seed-bradenton-manatee-2026/ROSTERS.md
-- Generated by: scripts/gen-bradenton-manatee-migrations.mjs
--
-- ---------------------------------------------------------------------------
-- 🔴 EVERY DISTRICT LOOKUP PAIRS geo_id WITH mtfcc AND district_type.
-- In Florida the geo_id collision reaches the COUNTY layer: 12081 is Manatee
-- County (G4020) AND State House District 81 (G5220), and 12020 is SD-20
-- (G5210) AND HD-20 (G5220). Measured 2026-08-28, an unpaired join at Bradenton
-- City Hall returned four rows, two of them officials in other counties, with no
-- error. fl.md documented only the sldl/sldu half of this.
--
-- ---------------------------------------------------------------------------
-- No party affiliation is recorded. The Supervisor of Elections prints (R)
-- beside all seventeen names; it is discarded. Party lives on
-- races.primary_party.
--
-- No term_end is written. A future term_end makes a seat silently self-vacate,
-- and office_terms has no end_precision, so a published expiry YEAR cannot
-- become a term_end without inventing a day.

-- ---------------------------------------------------------------------------
-- 🔴 MANATEE IS A NON-CHARTER COUNTY, so Fla. Const. art. VIII sec. 1(d)
-- applies unmodified and the five constitutional officers are Sheriff, Tax
-- Collector, Property Appraiser, Supervisor of Elections and Clerk of the
-- Circuit Court. The county's own page agrees: "the Board of County
-- Commissioners, together with Manatee County's FIVE constitutional officers,
-- comprise Manatee County Government." A charter was still only being explored
-- as of January 2026.
-- ⚠ NOTHING here may be inherited by Leon, Palm Beach or Miami-Dade. Charter
-- counties vary, and those three are confirmed separately in FL-4, FL-5, FL-6.
--
-- ---------------------------------------------------------------------------
-- 🔴 SEVEN COMMISSIONERS, FIVE POLYGONS. Districts 1-5 are single-member.
-- Districts 6 and 7 are elected COUNTYWIDE and hang off the PRE-EXISTING COUNTY
-- district for TIGER county 12081, together with all five constitutional
-- officers -- 7 offices on that one district. The at-large seats are numbered 6
-- and 7 by the Supervisor of Elections; the county's own board page labels both
-- rows merely "At Large District", with no number.
--
-- ---------------------------------------------------------------------------
-- 🔴 DISTRICT 1 IS VACANT, AND FLAGGING IT IS LOAD-BEARING TWICE OVER.
-- Commissioner Carol Ann Felts DIED on 2026-02-24 -- the county's own
-- announcement of that date. Governor DeSantis declared the vacancy by Executive
-- Order 26-76 and then left the seat empty, which is why it reaches the 2026
-- ballot as a TWO-YEAR unexpired term. Note that a county commission vacancy is
-- filled by GUBERNATORIAL APPOINTMENT (Fla. Const. art. IV sec. 1(f)), unlike a
-- LEGISLATIVE vacancy, which Florida fills by special election -- so FL-2's five
-- vacancies and this one are not the same mechanism.
--
--   1. check-address-reachability.mjs classifies DEAD_GEOGRAPHY as
--      reachable AND offices > 0 AND active_holders = 0 AND vacant_offices = 0.
--      The baseline holds NO fl| bucket in any check, so one unflagged empty
--      office creates a NEW fl|COUNTY bucket and fails CI.
--   2. essentials.offices_missing_terms counts only UNFLAGGED rows as drift.
--
-- ⚠ Felts' own closed term is deliberately NOT written, though every date for it
-- is known. FL-2 wrote no predecessor terms for any of its five legislative
-- vacancies, and doing it for one county seat here would leave Florida
-- internally inconsistent. ROSTERS.md records the evidence so all six can be
-- done together, deliberately.

BEGIN;

-- --- 0. Pre-flight ----------------------------------------------------------
DO $$
DECLARE v_n int;
BEGIN
  SELECT count(*) INTO v_n FROM essentials.geofence_boundaries WHERE mtfcc = 'X0037';
  IF v_n <> 5 THEN
    RAISE EXCEPTION 'manatee county: expected 5 X0037 boundaries, found % -- run scripts/load-manatee-commission-boundaries.ts first', v_n;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM essentials.geofence_boundaries WHERE geo_id = '12081' AND mtfcc = 'G4020'
  ) THEN
    RAISE EXCEPTION 'manatee county: TIGER county 12081/G4020 is missing';
  END IF;

  -- The countywide district must ALREADY exist. This migration must not create a
  -- second one: 7 of its 12 offices hang off it.
  SELECT count(*) INTO v_n FROM essentials.districts
   WHERE geo_id = '12081' AND mtfcc = 'G4020' AND district_type = 'COUNTY' AND lower(state) = 'fl';
  IF v_n <> 1 THEN
    RAISE EXCEPTION 'manatee county: expected exactly 1 pre-existing COUNTY district for 12081, found %', v_n;
  END IF;
END $$;

-- --- 1. The five single-member commission districts ------------------------

INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'COUNTY', 'Manatee County Commissioner District 1', 'fl', 'manatee-fl-commissioner-district-1', 'X0037', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'manatee-fl-commissioner-district-1' AND mtfcc = 'X0037' AND district_type = 'COUNTY'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'COUNTY', 'Manatee County Commissioner District 2', 'fl', 'manatee-fl-commissioner-district-2', 'X0037', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'manatee-fl-commissioner-district-2' AND mtfcc = 'X0037' AND district_type = 'COUNTY'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'COUNTY', 'Manatee County Commissioner District 3', 'fl', 'manatee-fl-commissioner-district-3', 'X0037', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'manatee-fl-commissioner-district-3' AND mtfcc = 'X0037' AND district_type = 'COUNTY'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'COUNTY', 'Manatee County Commissioner District 4', 'fl', 'manatee-fl-commissioner-district-4', 'X0037', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'manatee-fl-commissioner-district-4' AND mtfcc = 'X0037' AND district_type = 'COUNTY'
);
INSERT INTO essentials.districts (district_type, label, state, geo_id, mtfcc, num_officials)
SELECT 'COUNTY', 'Manatee County Commissioner District 5', 'fl', 'manatee-fl-commissioner-district-5', 'X0037', 1
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.districts
   WHERE geo_id = 'manatee-fl-commissioner-district-5' AND mtfcc = 'X0037' AND district_type = 'COUNTY'
);

-- --- 2. Government ----------------------------------------------------------

INSERT INTO essentials.governments (name, type, state, city, geo_id)
SELECT 'Manatee County, Florida, US', 'County', 'FL', NULL, '12081'
WHERE NOT EXISTS (
  SELECT 1 FROM essentials.governments WHERE geo_id = '12081' AND type = 'County'
);

-- --- 3. Chambers ------------------------------------------------------------
-- chambers.slug is GENERATED from name_formal and cannot be inserted.

INSERT INTO essentials.chambers
  (government_id, name, name_formal, official_count, policy_engagement_level)
SELECT g.id, 'Board of County Commissioners', 'Manatee County Board of County Commissioners', 7, 'full'
FROM essentials.governments g
WHERE g.geo_id = '12081' AND g.type = 'County'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.chambers c
     WHERE c.government_id = g.id AND c.name = 'Board of County Commissioners'
  );

INSERT INTO essentials.chambers
  (government_id, name, name_formal, official_count, policy_engagement_level)
SELECT g.id, 'Elected Officials', 'Manatee County Elected Officials', 5, 'full'
FROM essentials.governments g
WHERE g.geo_id = '12081' AND g.type = 'County'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.chambers c
     WHERE c.government_id = g.id AND c.name = 'Elected Officials'
  );

-- --- 4. Offices -------------------------------------------------------------

INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 1', 'FL', NULL, 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'manatee-fl-commissioner-district-1' AND dd.mtfcc = 'X0037'
     AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '12081' AND g.type = 'County' AND c.name = 'Board of County Commissioners'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 1'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 2', 'FL', NULL, 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'manatee-fl-commissioner-district-2' AND dd.mtfcc = 'X0037'
     AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '12081' AND g.type = 'County' AND c.name = 'Board of County Commissioners'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 2'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 3', 'FL', NULL, 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'manatee-fl-commissioner-district-3' AND dd.mtfcc = 'X0037'
     AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '12081' AND g.type = 'County' AND c.name = 'Board of County Commissioners'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 3'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 4', 'FL', NULL, 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'manatee-fl-commissioner-district-4' AND dd.mtfcc = 'X0037'
     AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '12081' AND g.type = 'County' AND c.name = 'Board of County Commissioners'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 4'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 5', 'FL', NULL, 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = 'manatee-fl-commissioner-district-5' AND dd.mtfcc = 'X0037'
     AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '12081' AND g.type = 'County' AND c.name = 'Board of County Commissioners'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 5'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 6 (At-Large)', 'FL', NULL, 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = '12081' AND dd.mtfcc = 'G4020'
     AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '12081' AND g.type = 'County' AND c.name = 'Board of County Commissioners'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 6 (At-Large)'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Commissioner, District 7 (At-Large)', 'FL', NULL, 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = '12081' AND dd.mtfcc = 'G4020'
     AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '12081' AND g.type = 'County' AND c.name = 'Board of County Commissioners'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Commissioner, District 7 (At-Large)'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Sheriff', 'FL', NULL, 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = '12081' AND dd.mtfcc = 'G4020'
     AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '12081' AND g.type = 'County' AND c.name = 'Elected Officials'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Sheriff'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Tax Collector', 'FL', NULL, 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = '12081' AND dd.mtfcc = 'G4020'
     AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '12081' AND g.type = 'County' AND c.name = 'Elected Officials'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Tax Collector'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Property Appraiser', 'FL', NULL, 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = '12081' AND dd.mtfcc = 'G4020'
     AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '12081' AND g.type = 'County' AND c.name = 'Elected Officials'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Property Appraiser'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Supervisor of Elections', 'FL', NULL, 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = '12081' AND dd.mtfcc = 'G4020'
     AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '12081' AND g.type = 'County' AND c.name = 'Elected Officials'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Supervisor of Elections'
  );
INSERT INTO essentials.offices
  (chamber_id, district_id, title, representing_state, representing_city, voting_powers)
SELECT c.id, d.id, 'Clerk of the Circuit Court and Comptroller', 'FL', NULL, 'full'
FROM essentials.chambers c
JOIN essentials.governments g ON g.id = c.government_id
CROSS JOIN LATERAL (
  SELECT dd.id FROM essentials.districts dd
   WHERE dd.geo_id = '12081' AND dd.mtfcc = 'G4020'
     AND dd.district_type = 'COUNTY' AND lower(dd.state) = 'fl'
) d
WHERE g.geo_id = '12081' AND g.type = 'County' AND c.name = 'Elected Officials'
  AND NOT EXISTS (
    SELECT 1 FROM essentials.offices o
    WHERE o.chamber_id = c.id AND o.district_id = d.id AND o.title = 'Clerk of the Circuit Court and Comptroller'
  );

-- --- 5. Flag District 1 vacant --------------------------------------------
-- Guarded UPDATE, so a re-run is a no-op and an appointee seated later is not
-- silently un-seated.
UPDATE essentials.offices o
   SET is_vacant = true,
       vacant_since = '2026-02-24'::timestamptz
  FROM essentials.districts d, essentials.chambers c
 WHERE d.id = o.district_id AND c.id = o.chamber_id
   AND d.geo_id = 'manatee-fl-commissioner-district-1' AND d.mtfcc = 'X0037' AND d.district_type = 'COUNTY'
   AND o.title = 'Commissioner, District 1'
   AND o.is_vacant = false
   AND NOT EXISTS (SELECT 1 FROM essentials.office_terms t WHERE t.office_id = o.id);

-- --- 6. Structure post-verify gate ----------------------------------------
DO $$
DECLARE v_gov uuid; v_n int; v_d text;
BEGIN
  SELECT count(*) INTO v_n FROM essentials.districts
   WHERE mtfcc = 'X0037' AND district_type = 'COUNTY' AND lower(state) = 'fl';
  IF v_n <> 5 THEN RAISE EXCEPTION 'manatee county: expected 5 X0037 districts, got %', v_n; END IF;

  SELECT id INTO v_gov FROM essentials.governments WHERE geo_id = '12081' AND type = 'County';
  IF v_gov IS NULL THEN RAISE EXCEPTION 'manatee county: the government row is missing'; END IF;

  SELECT count(*) INTO v_n FROM essentials.chambers WHERE government_id = v_gov;
  IF v_n <> 2 THEN RAISE EXCEPTION 'manatee county: expected 2 chambers, got %', v_n; END IF;

  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
   WHERE c.government_id = v_gov;
  IF v_n <> 12 THEN RAISE EXCEPTION 'manatee county: expected 12 offices, got %', v_n; END IF;

  -- PER CHAMBER, not just in total.
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
   WHERE c.government_id = v_gov AND c.name = 'Board of County Commissioners';
  IF v_n <> 7 THEN RAISE EXCEPTION 'manatee county: expected 7 commissioner offices, got %', v_n; END IF;

  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
   WHERE c.government_id = v_gov AND c.name = 'Elected Officials';
  IF v_n <> 5 THEN RAISE EXCEPTION 'manatee county: expected 5 constitutional officer offices, got %', v_n; END IF;

  -- PER DISTRICT: one commissioner per single-member district...
  FOR v_d IN SELECT 'manatee-fl-commissioner-district-' || g FROM generate_series(1,5) g LOOP
    SELECT count(*) INTO v_n FROM essentials.offices o
      JOIN essentials.districts d ON d.id = o.district_id
     WHERE d.geo_id = v_d AND d.mtfcc = 'X0037' AND d.district_type = 'COUNTY';
    IF v_n <> 1 THEN RAISE EXCEPTION 'manatee county: commission district % carries % offices, expected exactly 1', v_d, v_n; END IF;
  END LOOP;

  -- ...and exactly 7 on the countywide district: 2 at-large + 5 officers.
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
    JOIN essentials.chambers c ON c.id = o.chamber_id
   WHERE c.government_id = v_gov AND d.geo_id = '12081'
     AND d.mtfcc = 'G4020' AND d.district_type = 'COUNTY';
  IF v_n <> 7 THEN RAISE EXCEPTION 'manatee county: expected 7 offices on the countywide district, got %', v_n; END IF;

  -- 🔴 No office may have landed on a Manatee County in ANOTHER state, and none
  -- may sit on a district with no boundary.
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE c.government_id = v_gov AND lower(d.state) <> 'fl';
  IF v_n <> 0 THEN RAISE EXCEPTION 'manatee county: % office(s) landed outside Florida', v_n; END IF;

  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE c.government_id = v_gov
     AND NOT EXISTS (SELECT 1 FROM essentials.geofence_boundaries gb
                      WHERE gb.geo_id = d.geo_id AND gb.mtfcc = d.mtfcc);
  IF v_n <> 0 THEN RAISE EXCEPTION 'manatee county: % office(s) sit on a district with no matching boundary', v_n; END IF;

  RAISE NOTICE 'manatee county structure OK: 5 new districts, 1 government, 2 chambers, 12 offices';
END $$;

-- --- Politician identity band ----------------------------------------------
-- 🔴 THE BAND MUST HOLD NOTHING THIS WAVE DOES NOT OWN. The obvious FL band was
-- TAKEN in FL-2: -(1210000 + n) collided with 166 existing rows, the 2026 US
-- House candidates, and ON CONFLICT DO NOTHING would have absorbed that in
-- silence and left seats held by whoever already owned those ids.
-- -1249999..-1240000 was measured EMPTY on 2026-08-28.
--
-- ⚠ THIS IS AN ALLOWLIST, NOT A COUNT, AND THE DIFFERENCE IS TWO BUGS.
-- The first version asserted "the band holds exactly N rows before this runs".
-- That is NOT IDEMPOTENT -- a re-run of an applied migration counts its own rows
-- and refuses, which a migration in this repo is required not to do (measured:
-- it refused with "found 17"). It is also WEAKER: a foreign row that happened to
-- make the count match would pass. Naming the ids this wave owns fixes both.
DO $$
DECLARE v_n int; v_foreign text;
BEGIN
  SELECT count(*), string_agg(external_id::text, ', ' ORDER BY external_id)
    INTO v_n, v_foreign
    FROM essentials.politicians
   WHERE external_id BETWEEN -1249999 AND -1240000
     AND external_id NOT IN (-1240025, -1240024, -1240023, -1240022, -1240021, -1240016, -1240015, -1240014, -1240013, -1240012, -1240011, -1240006, -1240005, -1240004, -1240003, -1240002, -1240001);
  IF v_n <> 0 THEN
    RAISE EXCEPTION 'manatee county: the external_id band -1249999..-1240000 holds % row(s) this wave does not own (%). The band was measured EMPTY on 2026-08-28 -- pick another band rather than colliding.', v_n, v_foreign;
  END IF;
END $$;

-- 🔴 IDENTITY IS KEYED ON external_id, NEVER ON NAME. Checked in prod
-- 2026-08-28: none of the seventeen names in this wave matches any existing
-- politician row, so all are fresh inserts and nothing is reused. A name-based
-- guard is what seated a Wisconsin village trustee on the Nashville council.

CREATE TEMP TABLE man_seed (
  geo_id          text,
  mtfcc           text,
  district_type   text,
  office_title    text,
  ext_id          bigint,
  full_name       text,
  first_name      text,
  last_name       text,
  middle_initial  text,
  name_suffix     text,
  aliases         text[],
  term_start      date,
  start_precision text,
  how_started     text,
  source          text
) ON COMMIT DROP;

INSERT INTO man_seed VALUES
  ('manatee-fl-commissioner-district-2', 'X0037', 'COUNTY', 'Commissioner, District 2', -1240011, 'Amanda Ballard', 'Amanda', 'Ballard', NULL, NULL, '{}'::text[], '2022-11-01'::date, 'month', 'elected', 'mymanatee-ballard-bio-2026-08-28'),
  ('manatee-fl-commissioner-district-3', 'X0037', 'COUNTY', 'Commissioner, District 3', -1240012, 'Tal Siddique', 'Tal', 'Siddique', NULL, NULL, '{}'::text[], '2024-11-19'::date, 'day', 'elected', 'manatee-bocc-swearing-in-2024-11-19'),
  ('manatee-fl-commissioner-district-4', 'X0037', 'COUNTY', 'Commissioner, District 4', -1240013, 'Mike Rahn', 'Mike', 'Rahn', NULL, NULL, '{}'::text[], '2022-11-01'::date, 'month', 'elected', 'mymanatee-rahn-bio-2026-08-28'),
  ('manatee-fl-commissioner-district-5', 'X0037', 'COUNTY', 'Commissioner, District 5', -1240014, 'Dr. Bob McCann', 'Bob', 'McCann', NULL, NULL, ARRAY['Robert McCann', 'Bob McCann']::text[], '2024-11-19'::date, 'day', 'elected', 'manatee-bocc-swearing-in-2024-11-19'),
  ('12081', 'G4020', 'COUNTY', 'Commissioner, District 6 (At-Large)', -1240015, 'Jason Bearden', 'Jason', 'Bearden', NULL, NULL, '{}'::text[], '2022-11-01'::date, 'month', 'elected', 'mymanatee-bearden-bio-2026-08-28'),
  ('12081', 'G4020', 'COUNTY', 'Commissioner, District 7 (At-Large)', -1240016, 'George Kruse', 'George', 'Kruse', NULL, NULL, '{}'::text[], '2020-11-01'::date, 'month', 'elected', 'mymanatee-kruse-bio-2026-08-28'),
  ('12081', 'G4020', 'COUNTY', 'Sheriff', -1240021, 'Charles R. "Rick" Wells', 'Charles', 'Wells', 'R', NULL, ARRAY['Rick Wells']::text[], '2017-01-03'::date, 'day', 'elected', 'manateesheriff-wells-bio-2026-08-28'),
  ('12081', 'G4020', 'COUNTY', 'Tax Collector', -1240022, 'Ken Burton, Jr.', 'Ken', 'Burton', NULL, 'Jr.', '{}'::text[], '1993-01-01'::date, 'year', 'elected', 'manatee-taxcollector-about-2026-08-28'),
  ('12081', 'G4020', 'COUNTY', 'Property Appraiser', -1240023, 'Charles E. Hackney', 'Charles', 'Hackney', 'E', NULL, '{}'::text[], '1993-01-01'::date, 'year', 'elected', 'manateepao-hackney-bio-2026-08-28'),
  ('12081', 'G4020', 'COUNTY', 'Supervisor of Elections', -1240024, 'Scott Farrington', 'Scott', 'Farrington', NULL, NULL, '{}'::text[], '2025-01-01'::date, 'month', 'elected', 'votemanatee-farrington-bio-2026-08-28'),
  ('12081', 'G4020', 'COUNTY', 'Clerk of the Circuit Court and Comptroller', -1240025, 'Angelina "Angel" Colonneso', 'Angelina', 'Colonneso', NULL, NULL, ARRAY['Angel Colonneso']::text[], '2015-09-01'::date, 'month', 'appointed', 'manateeclerk-full-circle-blog-2026-08-28');

-- --- Payload guard ----------------------------------------------------------
DO $$
DECLARE v_n int; v_dup int;
BEGIN
  SELECT count(*) INTO v_n FROM man_seed;
  IF v_n <> 11 THEN RAISE EXCEPTION 'manatee county payload: expected 11 rows, got %', v_n; END IF;

  SELECT count(*) INTO v_dup FROM (SELECT ext_id FROM man_seed GROUP BY ext_id HAVING count(*) > 1) x;
  IF v_dup <> 0 THEN RAISE EXCEPTION 'manatee county payload: % duplicate external_id(s)', v_dup; END IF;

  SELECT count(*) INTO v_n FROM man_seed WHERE ext_id NOT BETWEEN -1249999 AND -1240000;
  IF v_n <> 0 THEN RAISE EXCEPTION 'manatee county payload: % out-of-band external_id(s)', v_n; END IF;

  -- Every (geo_id, mtfcc, district_type, title) is a single seat in this wave.
  SELECT count(*) INTO v_dup FROM (
    SELECT geo_id, mtfcc, district_type, office_title FROM man_seed
    GROUP BY geo_id, mtfcc, district_type, office_title HAVING count(*) > 1
  ) x;
  IF v_dup <> 0 THEN RAISE EXCEPTION 'manatee county payload: % duplicate seat key(s)', v_dup; END IF;

  -- A row with no term_start MUST declare 'unknown'. Three Bradenton council
  -- members are in exactly this position: no publisher gives a start date, and
  -- a guessed-late term_start is a false statement about history that no
  -- end_precision exists to soften.
  SELECT count(*) INTO v_n FROM man_seed WHERE term_start IS NULL AND start_precision <> 'unknown';
  IF v_n <> 0 THEN RAISE EXCEPTION 'manatee county payload: % row(s) have no term_start but claim a precision', v_n; END IF;

  -- And every seat named must resolve to exactly one office in prod.
  SELECT count(*) INTO v_n FROM man_seed s
   WHERE (SELECT count(*) FROM essentials.offices o
            JOIN essentials.districts d ON d.id = o.district_id
           WHERE d.geo_id = s.geo_id AND d.mtfcc = s.mtfcc
             AND d.district_type = s.district_type AND lower(d.state) = 'fl'
             AND o.title = s.office_title) <> 1;
  IF v_n <> 0 THEN RAISE EXCEPTION 'manatee county payload: % seat(s) do not resolve to exactly one office -- run the structure half first', v_n; END IF;
END $$;

-- --- Politicians ------------------------------------------------------------
INSERT INTO essentials.politicians
  (external_id, full_name, first_name, last_name, middle_initial, name_suffix,
   alternate_names, is_incumbent, is_active, data_source)
SELECT s.ext_id, s.full_name, s.first_name, s.last_name,
       nullif(s.middle_initial, ''), nullif(s.name_suffix, ''),
       s.aliases, true, true, s.source
FROM man_seed s
ON CONFLICT (external_id) DO NOTHING;

-- --- Occupancy --------------------------------------------------------------
-- 🔴 TWO PATHS, AND THE SECOND ONE IS NOT A SHORTCUT.
--
-- essentials.seat_officeholder() REFUSES a NULL term_start outright: "pass Jan 1
-- with p_start_precision => 'year' rather than NULL." Measured against prod
-- 2026-08-28. But this wave has three people for whom NO publisher gives any
-- start date at all, and inventing Jan 1 of a guessed year would be a false
-- statement about history that no end_precision exists to soften.
--
-- The schema itself allows the honest record, and prod is full of it: all 81,676
-- 'unknown'-precision office_terms rows carry term_start IS NULL, written by the
-- ADR 0002 phase-2 backfill. Only the HELPER refuses it.
--
-- So the dated rows go through the helper, as the house rule requires, and the
-- undated rows are inserted directly -- but ONLY into an office that has zero
-- existing term rows. That condition is what makes bypassing the helper safe:
-- the helper's two-step exists to close a predecessor before an open-ended range
-- overlaps it, and with no predecessor there is nothing to close and the
-- exclusion constraint cannot fire. The guard below refuses rather than guesses
-- if that stops being true.
DO $$
DECLARE r record; v_seated int := 0; v_blank int := 0; v_prior int;
BEGIN
  FOR r IN
    SELECT s.term_start, s.start_precision, s.how_started, s.source,
           o.id AS office_id, p.id AS politician_id
      FROM man_seed s
      JOIN essentials.districts d
        ON d.geo_id = s.geo_id AND d.mtfcc = s.mtfcc
       AND d.district_type = s.district_type AND lower(d.state) = 'fl'
      JOIN essentials.offices o ON o.district_id = d.id AND o.title = s.office_title
      JOIN essentials.politicians p ON p.external_id = s.ext_id
     WHERE NOT EXISTS (
       SELECT 1 FROM essentials.office_terms t
        WHERE t.office_id = o.id AND t.politician_id = p.id
     )
  LOOP
    IF r.term_start IS NOT NULL THEN
      PERFORM essentials.seat_officeholder(
        r.office_id, r.politician_id, r.term_start, r.source, r.how_started, r.start_precision
      );
      v_seated := v_seated + 1;
    ELSE
      IF r.start_precision <> 'unknown' THEN
        RAISE EXCEPTION 'manatee county: office % has no term_start but claims precision % -- refusing', r.office_id, r.start_precision;
      END IF;
      SELECT count(*) INTO v_prior FROM essentials.office_terms t WHERE t.office_id = r.office_id;
      IF v_prior <> 0 THEN
        RAISE EXCEPTION 'manatee county: office % already carries % term row(s), so an undated open term cannot be inserted directly -- close the predecessor and give this person a real date', r.office_id, v_prior;
      END IF;
      INSERT INTO essentials.office_terms
        (office_id, politician_id, term_start, term_end, start_precision, how_started, source)
      VALUES (r.office_id, r.politician_id, NULL, NULL, 'unknown', r.how_started, r.source);
      v_blank := v_blank + 1;
    END IF;
  END LOOP;
  RAISE NOTICE 'manatee county: seated % dated official(s) via the helper, % with an honest unknown start', v_seated, v_blank;
END $$;

-- --- 7. Occupancy post-verify gate ----------------------------------------
DO $$
DECLARE v_gov uuid; v_pol int; v_seated int; v_vac int; v_appt int; v_n int; v_d text;
BEGIN
  SELECT id INTO v_gov FROM essentials.governments WHERE geo_id = '12081' AND type = 'County';

  -- ⚠ COUNT THIS MIGRATION'S OWN IDS, NOT THE WHOLE BAND. The band version also
  -- gave this migration a hidden ORDERING DEPENDENCY on CC_0009: it asserted the
  -- city's six were already present, so applying the county first would have
  -- failed for no real reason.
  SELECT count(*) INTO v_pol FROM essentials.politicians
   WHERE external_id IN (-1240011, -1240012, -1240013, -1240014, -1240015, -1240016, -1240021, -1240022, -1240023, -1240024, -1240025);
  IF v_pol <> 11 THEN
    RAISE EXCEPTION 'manatee county: expected 11 of this wave''s politicians, got %', v_pol;
  END IF;

  SELECT count(och.politician_id) INTO v_seated
    FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
    LEFT JOIN essentials.office_current_holder och ON och.office_id = o.id
   WHERE c.government_id = v_gov;
  IF v_seated <> 11 THEN RAISE EXCEPTION 'manatee county: expected 11 seated officials, found %', v_seated; END IF;

  -- 🔴 EXACTLY ONE VACANCY, AND IT IS DISTRICT 1.
  SELECT count(*) INTO v_vac FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
   WHERE c.government_id = v_gov AND o.is_vacant = true;
  IF v_vac <> 1 THEN RAISE EXCEPTION 'manatee county: expected 1 flagged vacancy, got %', v_vac; END IF;

  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE d.geo_id = 'manatee-fl-commissioner-district-1' AND d.mtfcc = 'X0037'
     AND d.district_type = 'COUNTY'
     AND o.is_vacant = true AND o.vacant_since = '2026-02-24'::timestamptz;
  IF v_n <> 1 THEN RAISE EXCEPTION 'manatee county: District 1 is not flagged vacant since 2026-02-24'; END IF;

  -- One seated commissioner per single-member district, EXCEPT District 1.
  FOR v_d IN SELECT 'manatee-fl-commissioner-district-' || g FROM generate_series(2,5) g LOOP
    SELECT count(och.politician_id) INTO v_n
      FROM essentials.districts d
      JOIN essentials.offices o ON o.district_id = d.id
      LEFT JOIN essentials.office_current_holder och ON och.office_id = o.id
     WHERE d.geo_id = v_d AND d.mtfcc = 'X0037' AND d.district_type = 'COUNTY';
    IF v_n <> 1 THEN RAISE EXCEPTION 'manatee county: commission district % has % seated member(s), expected 1', v_d, v_n; END IF;
  END LOOP;

  SELECT count(och.politician_id) INTO v_n
    FROM essentials.districts d
    JOIN essentials.offices o ON o.district_id = d.id
    LEFT JOIN essentials.office_current_holder och ON och.office_id = o.id
   WHERE d.geo_id = 'manatee-fl-commissioner-district-1' AND d.mtfcc = 'X0037'
     AND d.district_type = 'COUNTY';
  IF v_n <> 0 THEN RAISE EXCEPTION 'manatee county: District 1 has % seated member(s), expected 0', v_n; END IF;

  -- 🔴 THE CLERK'S APPOINTMENT MUST HAVE SURVIVED. Colonneso was sworn in by
  -- appointment in September 2015 after her predecessor died in office; a
  -- generator that defaulted how_started to 'elected' passes every count above.
  SELECT count(*) INTO v_appt
    FROM essentials.office_terms t
    JOIN essentials.offices o ON o.id = t.office_id
    JOIN essentials.chambers c ON c.id = o.chamber_id
   WHERE c.government_id = v_gov AND t.how_started = 'appointed';
  IF v_appt <> 1 THEN RAISE EXCEPTION 'manatee county: expected 1 appointed term (the Clerk), got %', v_appt; END IF;

  -- No office with neither a term row nor a vacancy flag.
  SELECT count(*) INTO v_n FROM essentials.offices o
    JOIN essentials.chambers c ON c.id = o.chamber_id
    LEFT JOIN essentials.office_terms t ON t.office_id = o.id
   WHERE c.government_id = v_gov AND t.id IS NULL AND o.is_vacant = false;
  IF v_n <> 0 THEN RAISE EXCEPTION 'manatee county: % office(s) have no term row and no vacancy flag', v_n; END IF;

  RAISE NOTICE 'manatee county OK: 12 offices, 11 seated, 1 vacant';
END $$;

COMMIT;
