-- CC_0005_nashville_metro_people.sql
-- Nashville deep-seed program, WAVE 1a (people). Companion: CC_0004_nashville_structure.sql.
--
-- Inserts 41 politicians, reuses 1 that already exists, and seats all 42 via
-- essentials.seat_officeholder().
--
-- Roster: data/seed-nashville-davidson-2026/ROSTERS.md
-- Generated by: scripts/gen-nashville-migrations.mjs
--
-- ---------------------------------------------------------------------------
-- 🔴 IDENTITY IS KEYED ON external_id, NEVER ON NAME. Two collisions were
-- measured in prod on 2026-08-27 and BOTH are real -- they are not theoretical
-- risks quoted from a previous wave:
--
--   Robert Nash   -5515005  an active Village Trustee in WISCONSIN, with a
--                           photo. NOT District 27. A name-based guard would
--                           have inserted nothing, passed a 1:1 assertion, and
--                           seated a Wisconsin village trustee on the Nashville
--                           Metro Council. This is wave 2's Mike Lee failure,
--                           reproduced exactly, in this roster.
--
--   Mike Cortese   -470405  IS District 4. The row sits in the TN-04
--                           CONGRESSIONAL candidate band (-470401..-470410) and
--                           the obvious reading -- "Nashville is in TN-05/07, so
--                           this is a homonym" -- is WRONG. He told the Nashville
--                           Banner: "I serve as the elected representative for
--                           District 4 on the Davidson County Metro Council."
--                           He filed in TN-05 and moved to TN-04 after
--                           Tennessee's May 2026 redistricting.
--
-- So this migration inserts 41 people and REUSES -470405. Seeding him fresh
-- would leave prod with two Mike Cortese rows: one holding the council seat, one
-- holding his photo and his 2026 candidacy. ON CONFLICT (external_id) DO NOTHING
-- makes the reuse safe and leaves his existing row untouched.
--
-- ---------------------------------------------------------------------------
-- term_start is the day this person began holding THIS SEAT, continuously.
-- Re-election does not end an occupancy. The dates come from certified election
-- results (2023 vs 2019 vs 2015), NOT from any roster or biography page -- the
-- member pages publish no service-start year at all. 19 of the 42 have held
-- their seat since 2019; 23 began in 2023.
--
-- Terms are computed from 1 September following the August general election
-- (Charter Art. 15, incorporating Tenn. Const. Art. VII sec. 5), so 2023 starts
-- are written 2023-09-01 at MONTH precision -- a runoff winner is sworn in later
-- in the same month and no source gives a per-member day. The Mayor is the one
-- exception, at day precision, because his own page dates it.
--
-- Two members moved between seats in 2023 and their occupancy of the NEW seat
-- therefore begins in 2023, not when they first joined the body:
--   Delishia Porterfield  District 29 (2019) -> at-large (2023)
--   Angie Emery Henderson District 34 (2019) -> Vice Mayor (2023)
--
-- No term_end is written. A future term_end would make all 42 seats silently
-- self-vacate.

BEGIN;

CREATE TEMP TABLE nash_seed (
  geo_id          text,
  district_type   text,
  office_title    text,
  ext_id          bigint,
  full_name       text,
  first_name      text,
  last_name       text,
  middle_initial  text,
  name_suffix     text,
  aliases         text[],
  term_start      date,
  start_precision text,
  how_started     text,
  source          text
) ON COMMIT DROP;

INSERT INTO nash_seed VALUES
  ('nashville-tn-council-district-1', 'LOCAL', 'Council Member, District 1', -4730001, 'Joy Kimbrough', 'Joy', 'Kimbrough', NULL, NULL, ARRAY['Joy Smith Kimbrough']::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('nashville-tn-council-district-2', 'LOCAL', 'Council Member, District 2', -4730002, 'Kyonzté Toombs', 'Kyonzté', 'Toombs', NULL, NULL, ARRAY['Kyonzte Toombs']::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-3', 'LOCAL', 'Council Member, District 3', -4730003, 'Jennifer Gamble', 'Jennifer', 'Gamble', NULL, NULL, ARRAY[]::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-4', 'LOCAL', 'Council Member, District 4', -470405, 'Mike Cortese', 'Mike', 'Cortese', NULL, NULL, ARRAY[]::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4 — REUSES the existing prod politician row; see identity ruling 2'),
  ('nashville-tn-council-district-5', 'LOCAL', 'Council Member, District 5', -4730005, 'Sean Parker', 'Sean', 'Parker', NULL, NULL, ARRAY[]::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-6', 'LOCAL', 'Council Member, District 6', -4730006, 'Clay Capp', 'Clay', 'Capp', NULL, NULL, ARRAY[]::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('nashville-tn-council-district-7', 'LOCAL', 'Council Member, District 7', -4730007, 'Emily Benedict', 'Emily', 'Benedict', NULL, NULL, ARRAY[]::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-8', 'LOCAL', 'Council Member, District 8', -4730008, 'Deonté Harrell', 'Deonté', 'Harrell', NULL, NULL, ARRAY['Deonte Harrell']::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('nashville-tn-council-district-9', 'LOCAL', 'Council Member, District 9', -4730009, 'Tonya Hancock', 'Tonya', 'Hancock', NULL, NULL, ARRAY[]::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-10', 'LOCAL', 'Council Member, District 10', -4730010, 'Jennifer Frensley Webb', 'Jennifer', 'Webb', 'F', NULL, ARRAY['Jennifer F. Webb']::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('nashville-tn-council-district-11', 'LOCAL', 'Council Member, District 11', -4730011, 'Jeff Eslick', 'Jeff', 'Eslick', NULL, NULL, ARRAY[]::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('nashville-tn-council-district-12', 'LOCAL', 'Council Member, District 12', -4730012, 'Erin Evans', 'Erin', 'Evans', NULL, NULL, ARRAY[]::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-13', 'LOCAL', 'Council Member, District 13', -4730013, 'Russ Bradford', 'Russ', 'Bradford', NULL, NULL, ARRAY[]::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-14', 'LOCAL', 'Council Member, District 14', -4730014, 'Jordan Huffman', 'Jordan', 'Huffman', NULL, NULL, ARRAY[]::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('nashville-tn-council-district-15', 'LOCAL', 'Council Member, District 15', -4730015, 'Jeff Gregg', 'Jeff', 'Gregg', NULL, NULL, ARRAY[]::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('nashville-tn-council-district-16', 'LOCAL', 'Council Member, District 16', -4730016, 'Ginny Welsch', 'Ginny', 'Welsch', NULL, NULL, ARRAY[]::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-17', 'LOCAL', 'Council Member, District 17', -4730017, 'Terry Vo', 'Terry', 'Vo', NULL, NULL, ARRAY[]::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('nashville-tn-council-district-18', 'LOCAL', 'Council Member, District 18', -4730018, 'Tom Cash', 'Tom', 'Cash', NULL, NULL, ARRAY[]::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-19', 'LOCAL', 'Council Member, District 19', -4730019, 'Jacob Kupin', 'Jacob', 'Kupin', NULL, NULL, ARRAY[]::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('nashville-tn-council-district-20', 'LOCAL', 'Council Member, District 20', -4730020, 'Rollin Horton', 'Rollin', 'Horton', NULL, NULL, ARRAY[]::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('nashville-tn-council-district-21', 'LOCAL', 'Council Member, District 21', -4730021, 'Brandon Taylor', 'Brandon', 'Taylor', NULL, NULL, ARRAY[]::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-22', 'LOCAL', 'Council Member, District 22', -4730022, 'Sheri Weiner', 'Sheri', 'Weiner', NULL, NULL, ARRAY[]::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('nashville-tn-council-district-23', 'LOCAL', 'Council Member, District 23', -4730023, 'Thom Druffel', 'Thom', 'Druffel', NULL, NULL, ARRAY[]::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-24', 'LOCAL', 'Council Member, District 24', -4730024, 'Brenda Gadd', 'Brenda', 'Gadd', NULL, NULL, ARRAY[]::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('nashville-tn-council-district-25', 'LOCAL', 'Council Member, District 25', -4730025, 'Jeff Preptit', 'Jeff', 'Preptit', NULL, NULL, ARRAY[]::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('nashville-tn-council-district-26', 'LOCAL', 'Council Member, District 26', -4730026, 'Courtney Johnston', 'Courtney', 'Johnston', NULL, NULL, ARRAY[]::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-27', 'LOCAL', 'Council Member, District 27', -4730027, 'Robert Nash', 'Robert', 'Nash', NULL, NULL, ARRAY[]::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-28', 'LOCAL', 'Council Member, District 28', -4730028, 'David Benton', 'David', 'Benton', NULL, NULL, ARRAY[]::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('nashville-tn-council-district-29', 'LOCAL', 'Council Member, District 29', -4730029, 'Tasha Ellis', 'Tasha', 'Ellis', NULL, NULL, ARRAY[]::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('nashville-tn-council-district-30', 'LOCAL', 'Council Member, District 30', -4730030, 'Sandra Sepulveda', 'Sandra', 'Sepulveda', NULL, NULL, ARRAY[]::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-31', 'LOCAL', 'Council Member, District 31', -4730031, 'John Rutherford', 'John', 'Rutherford', NULL, NULL, ARRAY[]::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-32', 'LOCAL', 'Council Member, District 32', -4730032, 'Joy Styles', 'Joy', 'Styles', NULL, NULL, ARRAY[]::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-33', 'LOCAL', 'Council Member, District 33', -4730033, 'Antoinette Lee', 'Antoinette', 'Lee', 'W', NULL, ARRAY['Antoinette W. Lee']::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4; held the seat continuously since 2019 per S5, and did not win it in 2015 per S6'),
  ('nashville-tn-council-district-34', 'LOCAL', 'Council Member, District 34', -4730034, 'Sandy Ewing', 'Sandy', 'Ewing', NULL, NULL, ARRAY[]::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('nashville-tn-council-district-35', 'LOCAL', 'Council Member, District 35', -4730035, 'Jason Spain', 'Jason', 'Spain', NULL, NULL, ARRAY[]::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S2+S3 agree; won 2023 per S4'),
  ('47037', 'COUNTY', 'Council Member at-Large', -4730036, 'Zulfat Suara', 'Zulfat', 'Suara', NULL, NULL, ARRAY['Z']::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S3 agree; elected at-large 2023 per S4 (Suara outright in the general, the other four in the runoff); held an at-large seat continuously since 2019 per S5, and did not hold one in 2015 per S6'),
  ('47037', 'COUNTY', 'Council Member at-Large', -4730037, 'Delishia Porterfield', 'Delishia', 'Porterfield', NULL, NULL, ARRAY['Delishia Danielle Porterfield']::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S3 agree; elected at-large 2023 per S4 (Suara outright in the general, the other four in the runoff)'),
  ('47037', 'COUNTY', 'Council Member at-Large', -4730038, 'Quin Evans Segall', 'Quin', 'Evans Segall', NULL, NULL, ARRAY['Quin Evans-Segall']::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S3 agree; elected at-large 2023 per S4 (Suara outright in the general, the other four in the runoff)'),
  ('47037', 'COUNTY', 'Council Member at-Large', -4730039, 'Burkley Allen', 'Burkley', 'Allen', NULL, NULL, ARRAY[]::text[], '2019-09-01'::date, 'month', 'elected', 'S1+S3 agree; elected at-large 2023 per S4 (Suara outright in the general, the other four in the runoff); held an at-large seat continuously since 2019 per S5, and did not hold one in 2015 per S6'),
  ('47037', 'COUNTY', 'Council Member at-Large', -4730040, 'Olivia Hill', 'Olivia', 'Hill', NULL, NULL, ARRAY[]::text[], '2023-09-01'::date, 'month', 'elected', 'S1+S3 agree; elected at-large 2023 per S4 (Suara outright in the general, the other four in the runoff)'),
  ('47037', 'COUNTY', 'Mayor', -4730041, 'Freddie O''Connell', 'Freddie', 'O''Connell', NULL, NULL, ARRAY[]::text[], '2023-09-25'::date, 'day', 'elected', 'S8 — the Mayor''s own page dates 25 September 2026 as the start of his third year in office; won the 2023 runoff per S4'),
  ('47037', 'COUNTY', 'Vice Mayor', -4730042, 'Angie Emery Henderson', 'Angie', 'Henderson', 'E', NULL, ARRAY['Angie E. Henderson']::text[], '2023-09-01'::date, 'month', 'elected', 'S3+S4 — won the vice mayoral race outright in the 2023 general, defeating the incumbent Jim Shulman; previously District 34 Council Member 2019-2023 per S5, which is a DIFFERENT seat');

-- --- Payload guard ----------------------------------------------------------
DO $$
DECLARE v_n int; v_dup int; v_grp int;
BEGIN
  SELECT count(*) INTO v_n FROM nash_seed;
  IF v_n <> 42 THEN RAISE EXCEPTION 'seed payload: expected 42 rows, got %', v_n; END IF;

  SELECT count(*) INTO v_dup FROM (SELECT ext_id FROM nash_seed GROUP BY ext_id HAVING count(*) > 1) x;
  IF v_dup <> 0 THEN RAISE EXCEPTION 'seed payload: % duplicate external_id(s)', v_dup; END IF;

  SELECT count(*) INTO v_n FROM nash_seed WHERE ext_id BETWEEN -4730042 AND -4730001;
  IF v_n <> 41 THEN RAISE EXCEPTION 'seed payload: expected 41 in-band ext_ids, got %', v_n; END IF;

  SELECT count(*) INTO v_n FROM nash_seed WHERE ext_id IN (-470405);
  IF v_n <> 1 THEN RAISE EXCEPTION 'seed payload: the reused ext_id(s) are missing'; END IF;

  -- 🔴 The reused row must already exist AND still be the person we think it is.
  -- If someone renamed or deleted -470405 since 2026-08-27, seating it blind
  -- would attach a Nashville council seat to whoever now holds that id.
  SELECT count(*) INTO v_n
    FROM nash_seed s JOIN essentials.politicians p ON p.external_id = s.ext_id
   WHERE s.ext_id IN (-470405) AND p.full_name = s.full_name;
  IF v_n <> 1 THEN RAISE EXCEPTION
    'seed payload: a reused ext_id does not resolve to a prod politician of the same full_name -- re-verify identity ruling 2 before proceeding'; END IF;

  SELECT count(*) INTO v_grp FROM nash_seed
   WHERE geo_id = '47037' AND district_type = 'COUNTY' AND office_title = 'Council Member at-Large';
  IF v_grp <> 5 THEN RAISE EXCEPTION 'seed payload: expected 5 at-large rows, got %', v_grp; END IF;

  SELECT count(*) INTO v_grp FROM nash_seed WHERE office_title LIKE 'Council Member, District %';
  IF v_grp <> 35 THEN RAISE EXCEPTION 'seed payload: expected 35 district rows, got %', v_grp; END IF;

  -- Every OTHER triple must be unique -- the genuinely single-seat titles.
  SELECT count(*) INTO v_dup FROM (
    SELECT geo_id, district_type, office_title FROM nash_seed
    WHERE office_title <> 'Council Member at-Large'
    GROUP BY geo_id, district_type, office_title HAVING count(*) > 1
  ) x;
  IF v_dup <> 0 THEN RAISE EXCEPTION 'seed payload: % unexpected duplicate single-seat key(s)', v_dup; END IF;
END $$;

-- --- Politicians ------------------------------------------------------------
-- 41 inserts; the reused row conflicts and is left exactly as it is.

INSERT INTO essentials.politicians
  (external_id, full_name, first_name, last_name, middle_initial, name_suffix,
   alternate_names, is_incumbent, is_active, data_source)
SELECT s.ext_id, s.full_name, s.first_name, s.last_name, s.middle_initial, s.name_suffix,
       s.aliases, true, true, s.source
FROM nash_seed s
ON CONFLICT (external_id) DO NOTHING;

-- --- Occupancy, via the helper ----------------------------------------------

DO $$
DECLARE
  r record;
  v_seated int := 0;
BEGIN
  FOR r IN
    WITH office_rank AS (
      SELECT o.id AS office_id, d.geo_id, d.district_type, o.title,
             row_number() OVER (
               PARTITION BY d.geo_id, d.district_type, o.title ORDER BY o.id
             ) AS rn
      FROM essentials.offices o
      JOIN essentials.districts d ON d.id = o.district_id
      WHERE d.mtfcc = 'X0035'
         OR (d.geo_id = '47037' AND d.district_type = 'COUNTY')
    ),
    seed_rank AS (
      SELECT s.*,
             row_number() OVER (
               PARTITION BY s.geo_id, s.district_type, s.office_title ORDER BY s.ext_id
             ) AS rn
      FROM nash_seed s
    )
    SELECT sr.term_start, sr.start_precision, sr.how_started, sr.source,
           orr.office_id, p.id AS politician_id
    FROM seed_rank sr
    JOIN office_rank orr
      ON orr.geo_id = sr.geo_id
     AND orr.district_type = sr.district_type
     AND orr.title = sr.office_title
     AND orr.rn = sr.rn
    JOIN essentials.politicians p ON p.external_id = sr.ext_id
    WHERE NOT EXISTS (
      SELECT 1 FROM essentials.office_terms t
      WHERE t.office_id = orr.office_id AND t.politician_id = p.id
    )
  LOOP
    PERFORM essentials.seat_officeholder(
      r.office_id, r.politician_id, r.term_start,
      r.source,
      r.how_started,
      r.start_precision
    );
    v_seated := v_seated + 1;
  END LOOP;
  RAISE NOTICE 'seated % Nashville Metro official(s)', v_seated;
END $$;

-- --- Post-verify gate -------------------------------------------------------
DO $$
DECLARE v_pol int; v_seated int; v_appointed int; v_day int; v_homonym int; v_n int; v_d int;
BEGIN
  SELECT count(*) INTO v_pol FROM essentials.politicians
   WHERE external_id BETWEEN -4730042 AND -4730001;
  IF v_pol <> 41 THEN RAISE EXCEPTION 'nashville people: expected 41 in-band politicians, got %', v_pol; END IF;

  -- 🔴 And exactly ONE Mike Cortese. A duplicate here is the failure this
  -- migration exists to avoid, and a band count alone cannot see it.
  SELECT count(*) INTO v_n FROM essentials.politicians WHERE full_name = 'Mike Cortese';
  IF v_n <> 1 THEN RAISE EXCEPTION 'nashville people: found % politicians named Mike Cortese, expected exactly 1 -- the reuse failed and prod now holds a duplicate', v_n; END IF;

  -- count(och.politician_id), NOT count(*): office_current_holder LEFT JOINs
  -- from offices, so a vacancy is a NULL politician_id, never an absent row.
  -- count(*) would pass vacuously with every seat empty.
  SELECT count(och.politician_id) INTO v_seated
    FROM essentials.offices o
    JOIN essentials.districts d ON d.id = o.district_id
    LEFT JOIN essentials.office_current_holder och ON och.office_id = o.id
   WHERE d.mtfcc = 'X0035'
      OR (d.geo_id = '47037' AND d.district_type = 'COUNTY');
  IF v_seated <> 42 THEN RAISE EXCEPTION 'nashville people: expected 42 seated officials, found %', v_seated; END IF;

  -- Per district, for the same reason the structure gate counts per district.
  FOR v_d IN 1..35 LOOP
    SELECT count(och.politician_id) INTO v_n
      FROM essentials.offices o
      JOIN essentials.districts d ON d.id = o.district_id
      LEFT JOIN essentials.office_current_holder och ON och.office_id = o.id
     WHERE d.geo_id = 'nashville-tn-council-district-' || v_d AND d.mtfcc = 'X0035';
    IF v_n <> 1 THEN RAISE EXCEPTION 'nashville people: council district % has % seated member(s), expected 1', v_d, v_n; END IF;
  END LOOP;

  SELECT count(*) INTO v_appointed
    FROM essentials.office_terms t
    JOIN essentials.politicians p ON p.id = t.politician_id
   WHERE (p.external_id BETWEEN -4730042 AND -4730001 OR p.external_id IN (-470405))
     AND t.how_started = 'appointed';
  IF v_appointed <> 0 THEN RAISE EXCEPTION 'nashville people: expected 0 appointed term(s), found %', v_appointed; END IF;

  SELECT count(*) INTO v_day
    FROM essentials.office_terms t
    JOIN essentials.politicians p ON p.id = t.politician_id
    JOIN essentials.offices o ON o.id = t.office_id
    JOIN essentials.districts d ON d.id = o.district_id
   WHERE (d.mtfcc = 'X0035' OR (d.geo_id = '47037' AND d.district_type = 'COUNTY'))
     AND t.start_precision = 'day';
  IF v_day <> 1 THEN RAISE EXCEPTION 'nashville people: expected 1 day-precision term(s), found % -- a date was invented or dropped', v_day; END IF;

  -- 🔴 Cross-state homonym assertion: no Nashville seat may resolve to someone
  -- who also holds an office outside Tennessee. Robert Nash is the live case
  -- this exists for.
  SELECT count(*) INTO v_homonym
  FROM essentials.politicians p
  JOIN essentials.office_current_holder och ON och.politician_id = p.id
  JOIN essentials.offices o ON o.id = och.office_id
  JOIN essentials.districts d ON d.id = o.district_id
   AND (d.mtfcc = 'X0035' OR (d.geo_id = '47037' AND d.district_type = 'COUNTY'))
  JOIN essentials.office_current_holder och2 ON och2.politician_id = p.id
  JOIN essentials.offices o2 ON o2.id = och2.office_id
  JOIN essentials.districts d2 ON d2.id = o2.district_id AND lower(d2.state) <> 'tn';
  IF v_homonym <> 0 THEN RAISE EXCEPTION
    'nashville people: % seat(s) resolved to an out-of-state politician -- the Mike Lee failure', v_homonym; END IF;

  RAISE NOTICE 'nashville people OK -- 42 officials seated, 0 by appointment, 1 Mike Cortese, 0 homonyms.';
END $$;

COMMIT;
