# generate_md_legislative_races.ps1
# Generates 280_md_2026_legislative_races.sql
# 47 Senate districts (seats=1) + 71 House districts (variable seats) = 118 race rows
#
# MD SLDL geo_ids are NON-SEQUENTIAL (mix of whole-district 24NNN and sub-district 24NNA/B/C).
# The generator uses hardcoded data arrays from the verified live DB query (Phase 96 research).
# MD SLDU geo_ids ARE sequential (24001..24047) so a simple for-loop works for senate.
#
# CRITICAL: d.state = 'md' (lowercase) for both STATE_UPPER and STATE_LOWER lookups.
#   Using 'MD' (uppercase) returns NULL office_ids for every legislative district.

if (-not $PSScriptRoot) {
    Write-Error "PSScriptRoot is empty -- run this script with 'powershell -File generate_md_legislative_races.ps1', not dot-sourced."
    exit 1
}

$output = @()
$output += "-- Migration 280: MD 2026 Legislative Race Scaffold - Phase 96 Plan 02"
$output += "-- Generated by generate_md_legislative_races.ps1"
$output += "-- 47 Senate districts + 71 House districts = 118 race rows, general election only"
$output += "--"
$output += "-- ROADMAP DEVIATION: ROADMAP estimated 198 total race rows (one-row-per-seat model)."
$output += "-- Actual count is 130 (12 statewide + 47 senate + 71 SLDL house geofences)."
$output += "-- The reduction is enforced by UNIQUE (election_id, position_name, primary_party)"
$output += "-- which makes one-row-per-district the only viable model per D-01."
$output += "-- ROADMAP 'cron_active=true' language is also stale -- no such column exists on"
$output += "-- essentials.discovery_jurisdictions; eligibility is date-based (180-day cron window)."
$output += ""

# --- SENATE DISTRICTS (1..47) ---
# All seats=1; geo_ids 24001..24047 (sequential, no sub-districts)
# IMPORTANT: ch.name = 'Maryland Senate' (short name in DB), NOT 'Maryland State Senate'
# The name_formal is 'Maryland State Senate' but the chambers.name used in queries is 'Maryland Senate'
# Using the wrong name results in NULL office_ids for all senate races (verified 2026-06-06)
for ($n = 1; $n -le 47; $n++) {
    $geo_id = "24" + ($n.ToString().PadLeft(3, '0'))  # '24001' through '24047'
    $pos = "MD State Senate District $n"

    $block = @"
DO `$`$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = '2026 Maryland General Election' AND state = 'MD';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '$geo_id' AND d.district_type = 'STATE_UPPER' AND d.state = 'md'
       AND ch.name = 'Maryland Senate' LIMIT 1),
    '$pos', NULL, 1)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END `$`$;
"@
    $output += $block
}

# --- HOUSE DISTRICTS (SLDL) ---
# 71 geofence rows: 29 whole-district (seats=3) + 42 sub-district (variable seats)
# Geo_ids are NON-SEQUENTIAL — must use hardcoded array from live DB query.
$houseDistricts = @(
  # Whole-district rows (seats=3): 29 districts
  @{ geo_id='24003'; label='District 3';        seats=3 },
  @{ geo_id='24004'; label='District 4';        seats=3 },
  @{ geo_id='24005'; label='District 5';        seats=3 },
  @{ geo_id='24006'; label='District 6';        seats=3 },
  @{ geo_id='24008'; label='District 8';        seats=3 },
  @{ geo_id='24010'; label='District 10';       seats=3 },
  @{ geo_id='24013'; label='District 13';       seats=3 },
  @{ geo_id='24014'; label='District 14';       seats=3 },
  @{ geo_id='24015'; label='District 15';       seats=3 },
  @{ geo_id='24016'; label='District 16';       seats=3 },
  @{ geo_id='24017'; label='District 17';       seats=3 },
  @{ geo_id='24018'; label='District 18';       seats=3 },
  @{ geo_id='24019'; label='District 19';       seats=3 },
  @{ geo_id='24020'; label='District 20';       seats=3 },
  @{ geo_id='24021'; label='District 21';       seats=3 },
  @{ geo_id='24022'; label='District 22';       seats=3 },
  @{ geo_id='24023'; label='District 23';       seats=3 },
  @{ geo_id='24024'; label='District 24';       seats=3 },
  @{ geo_id='24025'; label='District 25';       seats=3 },
  @{ geo_id='24026'; label='District 26';       seats=3 },
  @{ geo_id='24028'; label='District 28';       seats=3 },
  @{ geo_id='24031'; label='District 31';       seats=3 },
  @{ geo_id='24032'; label='District 32';       seats=3 },
  @{ geo_id='24036'; label='District 36';       seats=3 },
  @{ geo_id='24039'; label='District 39';       seats=3 },
  @{ geo_id='24040'; label='District 40';       seats=3 },
  @{ geo_id='24041'; label='District 41';       seats=3 },
  @{ geo_id='24045'; label='District 45';       seats=3 },
  @{ geo_id='24046'; label='District 46';       seats=3 },
  # Sub-district rows (42 rows, variable seats):
  @{ geo_id='2401A'; label='Subdistrict 1A';    seats=1 },
  @{ geo_id='2401B'; label='Subdistrict 1B';    seats=1 },
  @{ geo_id='2401C'; label='Subdistrict 1C';    seats=1 },
  @{ geo_id='2402A'; label='Subdistrict 2A';    seats=2 },
  @{ geo_id='2402B'; label='Subdistrict 2B';    seats=1 },
  @{ geo_id='2407A'; label='Subdistrict 7A';    seats=2 },
  @{ geo_id='2407B'; label='Subdistrict 7B';    seats=1 },
  @{ geo_id='2409A'; label='Subdistrict 9A';    seats=2 },
  @{ geo_id='2409B'; label='Subdistrict 9B';    seats=1 },
  @{ geo_id='2411A'; label='Subdistrict 11A';   seats=1 },
  @{ geo_id='2411B'; label='Subdistrict 11B';   seats=2 },
  @{ geo_id='2412A'; label='Subdistrict 12A';   seats=2 },
  @{ geo_id='2412B'; label='Subdistrict 12B';   seats=1 },
  @{ geo_id='2427A'; label='Subdistrict 27A';   seats=1 },
  @{ geo_id='2427B'; label='Subdistrict 27B';   seats=1 },
  @{ geo_id='2427C'; label='Subdistrict 27C';   seats=1 },
  @{ geo_id='2429A'; label='Subdistrict 29A';   seats=1 },
  @{ geo_id='2429B'; label='Subdistrict 29B';   seats=1 },
  @{ geo_id='2429C'; label='Subdistrict 29C';   seats=1 },
  @{ geo_id='2430A'; label='Subdistrict 30A';   seats=2 },
  @{ geo_id='2430B'; label='Subdistrict 30B';   seats=1 },
  @{ geo_id='2433A'; label='Subdistrict 33A';   seats=1 },
  @{ geo_id='2433B'; label='Subdistrict 33B';   seats=1 },
  @{ geo_id='2433C'; label='Subdistrict 33C';   seats=1 },
  @{ geo_id='2434A'; label='Subdistrict 34A';   seats=2 },
  @{ geo_id='2434B'; label='Subdistrict 34B';   seats=1 },
  @{ geo_id='2435A'; label='Subdistrict 35A';   seats=2 },
  @{ geo_id='2435B'; label='Subdistrict 35B';   seats=1 },
  @{ geo_id='2437A'; label='Subdistrict 37A';   seats=1 },
  @{ geo_id='2437B'; label='Subdistrict 37B';   seats=2 },
  @{ geo_id='2438A'; label='Subdistrict 38A';   seats=1 },
  @{ geo_id='2438B'; label='Subdistrict 38B';   seats=1 },
  @{ geo_id='2438C'; label='Subdistrict 38C';   seats=1 },
  @{ geo_id='2442A'; label='Subdistrict 42A';   seats=1 },
  @{ geo_id='2442B'; label='Subdistrict 42B';   seats=1 },
  @{ geo_id='2442C'; label='Subdistrict 42C';   seats=1 },
  @{ geo_id='2443A'; label='Subdistrict 43A';   seats=2 },
  @{ geo_id='2443B'; label='Subdistrict 43B';   seats=1 },
  @{ geo_id='2444A'; label='Subdistrict 44A';   seats=1 },
  @{ geo_id='2444B'; label='Subdistrict 44B';   seats=2 },
  @{ geo_id='2447A'; label='Subdistrict 47A';   seats=2 },
  @{ geo_id='2447B'; label='Subdistrict 47B';   seats=1 }
)

foreach ($d in $houseDistricts) {
    $geo_id = $d.geo_id
    $seats  = $d.seats

    # position_name convention (per PATTERNS.md):
    # Whole-district rows (label starts with 'District '): 'MD House Delegate District N'
    # Sub-district rows (label starts with 'Subdistrict '): 'MD House Delegate Subdistrict NNA'
    if ($d.label -like 'District *') {
        $num = $d.label -replace 'District ', ''
        $pos = "MD House Delegate District $num"
    } else {
        $sub = $d.label -replace 'Subdistrict ', ''
        $pos = "MD House Delegate Subdistrict $sub"
    }

    $block = @"
DO `$`$
DECLARE
  v_general_id UUID;
BEGIN
  SELECT id INTO v_general_id FROM essentials.elections
  WHERE name = '2026 Maryland General Election' AND state = 'MD';

  INSERT INTO essentials.races (election_id, office_id, position_name, primary_party, seats)
  VALUES (v_general_id,
    (SELECT o.id FROM essentials.offices o
     JOIN essentials.districts d ON d.id = o.district_id
     JOIN essentials.chambers ch ON ch.id = o.chamber_id
     WHERE d.geo_id = '$geo_id' AND d.district_type = 'STATE_LOWER' AND d.state = 'md'
       AND ch.name = 'Maryland House of Delegates' LIMIT 1),
    '$pos', NULL, $seats)
  ON CONFLICT (election_id, position_name) WHERE primary_party IS NULL DO NOTHING;
END `$`$;
"@
    $output += $block
}

# --- TRAILING POST-VERIFICATION ---
# After migration 279 (12 statewide) + this migration (47 senate + 71 house = 118),
# total MD race rows must equal 130.
$verifyBlock = @"
DO `$`$
DECLARE
  v_count INT;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM essentials.races r
  JOIN essentials.elections e ON e.id = r.election_id
  WHERE e.state = 'MD';
  -- Expected: 12 statewide + 47 senate + 71 SLDL = 130 total
  IF v_count <> 130 THEN
    RAISE EXCEPTION 'Expected 130 MD race rows total (12 statewide + 47 senate + 71 SLDL), found %', v_count;
  END IF;
END `$`$;
"@
$output += $verifyBlock

# Ledger entry
$ledgerBlock = @"
-- Ledger entry
INSERT INTO supabase_migrations.schema_migrations (version)
VALUES ('280')
ON CONFLICT (version) DO NOTHING;
"@
$output += $ledgerBlock

# CRITICAL: Use UTF-8 without BOM — the PowerShell default Out-File appends a BOM
# that PostgreSQL rejects with "syntax error at or near ''"; use WriteAllLines instead.
[System.IO.File]::WriteAllLines(
  (Join-Path $PSScriptRoot '280_md_2026_legislative_races.sql'),
  $output,
  [System.Text.UTF8Encoding]::new($false)
)
Write-Host "Generated 280_md_2026_legislative_races.sql with $($output.Count) lines"
