// David Clanaugh — Duluth 4th District, seated 2026-01-05. 35 rows, 0 chairs. A documented zero.
//
// The tracker called him "the best single lead of the three newcomers". He is, on volume of
// quotable material, and none of it names a rung. He has the clearest record in this slice of a
// member whose positions are all DIRECTION and no INSTRUMENT.
//
// 🔴 THE AMBIGUITY CHECK THREW AWAY TEN OF HIS TWENTY-THREE USABLE ARTICLES FOR PEOPLE WHO DO NOT
// EXIST. `attribute_quotes` excludes an article that names a different "<First> Clanaugh". The
// "other Clanaughs" it found were **Repair**, **Represents**, **While**, **Local** and **Yet** —
// ordinary words sitting before his surname: "Right to Repair Clanaugh noted…", the Duluth News
// Tribune's roster line "Represents: … Clanaugh", and three sentence boundaries. The single most
// useful article in his corpus, the News Tribune and Chamber candidate forum where he and the
// incumbent answered the same questions, was excluded by "Repair".
// ▶ The check needs a stoplist, or a test that the candidate first name is a plausible given name.
// Until then, read the excluded list by hand. Same class of defect as the Yang name-order bug.
import fs from 'node:fs';

const B = 'data/stance-research/2026-10-04-knight-mn-cities';
const N = 'David Clanaugh';

const SWEEP = 'A sweep of the three Duluth outlets that pass a differential control - the Duluth News Tribune, WDIO and Duluth Monitor - together with MinnPost and Sahan Journal, over 23 queries, fetched 539 articles and kept 32, of which 23 name David Clanaugh: 72% signal, and the surname has one spelling across every outlet. Minnesota Reformer was searched separately, with a control run at both ends, and added nothing naming him - a measured zero. Sahan Journal and the Saint Paul Pioneer Press also contributed nothing and are blind here rather than empty. 🔴 Ten of the 23 were initially set aside by the automatic check as naming a different Clanaugh, and every one of those exclusions was false: the supposed other people were the words Repair, Represents, While, Local and Yet sitting in front of his surname. All ten were read by hand, including the candidate forum that the word Repair had excluded. The other eight Duluth corpora in this slice were read for him as well; fourteen further articles name him there. Perfect Duluth Day, FOX 21, Business North, Northern News Now and Duluth Reader could not be searched by any method found, so no outlet count here covers them. MPR News and Racket are not covered either: MPR News renders its articles in the browser, so a passage there cannot be verified against the page, and Racket returns the same results for any query including a nonsense one. He took office on 5 January 2026, having unseated the incumbent in the 4th District with about 54% of the vote, so C44 excludes everything the council did before that date. Since then the council has divided on two matters: he abstained on the Housing Trust Fund Committee appointments and voted against a motion to table. His sponsorships were read from the council’s own legislative record, matter by matter. His statements as a candidate are used, under the ruling of 2026-10-05.';

const searched = {
  housing: 'Housing is his subject and he never names the instrument. A former executive director of Habitat for Humanity, he said his top priority would be to boost the city’s supply of affordable housing, and the reporter records him suggesting the community consider alternative building techniques and ways to remove barriers to building low- to mid-cost housing. Speaking of his Habitat experience he said builders want to get permits, and: let us move these things along and figure out ways that we can be safe, we can be healthy, but we can also be creative in addressing the needs of the community. Before the election he described hearing the same problem at every income level - middle-income people on fixed incomes struggling with property taxes, businesses unable to retain employees who cannot afford housing, renters priced out of the market, and homelessness at the lowest end. That is a diagnosis and a direction, and the five rungs separate on who makes housing affordable and how. Moving permits along faster is not cutting the regulations and zoning limits that block private building, which is chair 5, and he says in the same breath that the result must still be safe and healthy. He names no public building programme, no binding rule on the private market, and no subsidy. Chairs 3, 4 and 5 all remain open.',
  'homelessness-response': 'He has worked at the Damiano Center and speaks about it from the inside: he said he could not begin to say how many people came to the soup kitchen there who had jobs. At the candidate forum he argued that the city’s support for nonprofit organisations such as the Damiano Center and the Union Gospel Mission should be seen as investments, because the city is investing that money in human beings with the potential to do something different with their lives and to be full members of the community. That is a defence of city money going to nonprofits, and it is the same place every other member of this council lands on this ladder. Public money expanding shelter and services reads as chair 2; the money going to nonprofits that lead the response rather than to a programme the city runs is the description chair 4 gives. He names no funding level and does not say which of the two the city should be doing. Forsman, Randorf, Nephew, Kennedy and Tomanek are all blank here for the same reason.',
  'rent-regulation': '🔴 He is the member of this council with the most to say about tenants, and he says the one thing that keeps it off this ladder. He co-authored, with Durrwachter, the resolution asking the governor for a temporary statewide eviction moratorium; it failed 7-2 on the merits with support only from its two authors. He said that if the council does not step up and protect the people currently in the crosshairs of ICE violence, eventually that violence will reach all of us, and that now is the time to push back alongside the most vulnerable. As a candidate he noted that 40% of Duluth residents are renters, said the Right to Repair referendum on the November ballot was worthy of public support, and applauded its supporters; after it passed he credited it with bringing voters to the polls. When his opponent characterised Right to Repair as a step towards rent control, he answered that it is problematic to assign additional motives to the measure’s supporters - that is, he declined the rent-control reading of his own position. Every rung of this ladder is about the price of rent. An eviction moratorium and a repair remedy are tenant protections, Duluth has no rent stabilisation ordinance for any rung to extend or narrow, and he has refused the one framing that would have put him on this axis.',
  'economic-development': 'In September 2026 the council approved tax increment financing for a five-storey apartment building near Lake Superior College. He and Durrwachter tried first to table the resolution for eleven days, so that the council and the public could read documents the housing authority had supplied only the day before; that motion failed 7-2. He then voted for the project, and said: I see this as a good move for the community, and that his concern is for the future and how the city goes about executing these tax increment agreements and maximising public oversight and input. Chairs 1 and 2 are excluded, because he voted to give a developer a subsidy. What he asks for is process - documents in front of the public before the vote, better execution of the agreements afterwards - and this ladder separates on the terms of the deal. Chair 3 wants good wages, local hiring and money repayable if the firm does not deliver, and he names none of those. Chair 4 wants limits and a willingness to pass on deals that cost too much, and he passed on nothing; he wanted to read the file first. Oversight is not a condition and it is not a limit.',
  'city-sanitation': 'He is the lead author of the ordinance establishing the Lincoln Park Special Service District, with Vice President Kennedy, together with the resolution imposing the service charges that fund it. It was brought on a petition from property owners in the district who want to improve its safety, cleanliness and economic vitality, and under the state statute only commercial, industrial and public utility property pays the charge. That is a real instrument on exactly this subject and no rung describes it. The ladder separates on how far the city itself should go: expanding public sanitation, concentrating it on the worst-served neighbourhoods, holding big waste producers to account, enforcing against residents and businesses, or privatising the service. A special service district is none of those - it is extra service, inside the city’s own framework, bought by the owners who asked for it and who benefit from it. Recording a chair from it would mean choosing a rung the instrument does not take.',
  'local-immigration': 'His immigration work is about tenants rather than about policing. With Durrwachter he proposed the resolution asking the governor for a temporary statewide eviction moratorium to keep tenants out of ICE’s reach, and he spoke for it in those terms. He is not among the four sponsors of the resolution that bars city agencies from using city resources to assist federal civil immigration enforcement, which is the instrument that seats this chair for four of his colleagues; the council adopted that one separately. This ladder asks how local law enforcement should relate to federal immigration enforcement, and no passage states his position on detainers, on information sharing, or on the use of local police. The question was live in front of him and he answered a different one.',
  'transportation-priorities': 'He talks about infrastructure as responsiveness rather than as priority. He said residents understand the city has a lot of challenges and needs, especially in infrastructure, and do not expect miracles, but that when there are delays or a really serious pothole that is an absolute hazard, those things should be addressed and people who ask for help should get a reply rather than having to call repeatedly. He has pointed to lead pipe replacement as real progress. None of that chooses between road capacity and transit, cycling or pedestrian investment.',
  'growth-and-development': 'No passage states a position on the pace of growth or on whether development should wait for infrastructure capacity. He co-sponsored the resolution calling a special election to put two Lester Park initiative ordinances to the voters, which was withdrawn before it took effect; putting a citizen initiative on a ballot is a procedural act and not a position on its merits.',
  'residential-zoning': 'His remarks about alternative building techniques and removing barriers to low- and mid-cost housing concern how housing gets built and permitted. No passage states a position on density or neighbourhood character - nothing on duplexes, accessory dwellings, multifamily by right, or single-family-only zoning.',
  'public-safety-approach': 'The special service district he authored names safety among the things its property owners want to improve, which is a description of their petition rather than a position of his. No passage states a position on police staffing, police funding, co-responders or crisis teams.',
  homelessness: 'He describes homelessness as the bottom of a single affordability problem and speaks about the people he met working at the Damiano Center. No passage states a position on how the city should treat people sleeping or camping in public. The 2024 camping ordinance predates his term and is excluded by C44.',
  'local-environment': 'No passage states a position on how far environmental protection should constrain development.',
  'climate-change': 'No passage states a position on clean energy mandates, subsidies, public investment, permitting or the grid.',
  childcare: 'At the candidate forum his opponent spoke about supporting childcare facilities; he did not answer on that subject. No passage states a position on childcare funding or provision.',
  'civil-rights': 'He said his district is diverse with distinct neighbourhoods, that this gets used to pit people against each other, and that residents have more in common than not. That is an appeal against division. This ladder separates on how far government should go in addressing racial and social inequality, and no passage states a position on enforcement or on race-conscious programmes.',
  'data-centers': 'No passage names a data centre proposal in Duluth or states a position on one.',
  'minimum-wage': 'Duluth has no city minimum wage ordinance, so there is no local instrument, and Minn. Stat. 177.24 carries no local preemption clause, so the lever exists and this is not a scope blank. No passage states a position on the wage floor.',
  'ranked-choice-voting': 'Duluth’s only ranked choice matter is 15-0516R from 2015, a decade before he took office, and C44 excludes it. No passage states a position on the electoral method.',
  'religious-freedom': 'No passage states a position on any rung.',
  '2020-election': 'No passage states a view of the 2020 presidential election.',
};

const rows = [...JSON.parse(fs.readFileSync(B + '/_rows/clanaugh-blanks.json', 'utf8'))];
for (const [k, v] of Object.entries(searched)) {
  rows.push({ full_name: N, topic_key: k, value: '', evidence_type: '', reasoning: 'Searched blank. ' + SWEEP + ' ' + v, source_url_1: '', source_url_2: '', source_url_3: '', quote_text: '', quote_deidentified: '', editor_note: '' });
}

if (new Set(rows.map((r) => r.topic_key)).size !== rows.length) throw new Error('duplicate topic');
if (rows.length !== 35) throw new Error('expected 35 rows, got ' + rows.length);
if (rows.some((r) => r.value)) throw new Error('this pass found no chair; a scored row here is a mistake');
// No uncitable file number may appear: nothing here is cited.
for (const r of rows) {
  const m = r.reasoning.match(/\b2[0-6]-\d{3,4}R\b|\b2[0-6]-\d{3}-O\b/);
  if (m) throw new Error('uncitable file number leaked into ' + r.topic_key + ': ' + m[0]);
}

fs.writeFileSync(B + '/_rows/clanaugh-rows.json', JSON.stringify(rows, null, 1));
console.log('rows:', rows.length, '| scored:', rows.filter((r) => r.value).length, '| documented zero');
