// Jordon Johnson — Duluth at large, seated 2026-01-05. 35 rows, 0 chairs. A documented zero.
//
// 🔴🔴 HIS OWN CORPUS IS THE WORST SOURCE ON HIM, AND THE NUMBERS SAY SO.
// The sweep kept 700 files on the surname alone. Nine of them name him: 1% signal, against
// Kennedy's 6%. `attribute_quotes` then skipped 692 as not naming him, excluded four more for Pete
// Johnson — a different Johnson who beat him in the 2024 DFL primary for Minnesota House 8A — and
// returned ZERO attributed quotes from four clean articles.
// Everything used here came from the OTHER members' corpora. Twenty-six articles across the eight
// Duluth corpora name him, nearly three times his own sweep.
//
// 🔴 AND TEN OF THOSE TWENTY-SIX ARE A SIDEBAR, NOT COVERAGE. The Duluth News Tribune appends its
// full council roster — every councilor, ward and email — to its local stories, so "the article
// names him" is true of DNT stories that are not about him at all. Stripping the roster leaves 16,
// and two of those are about Pete Johnson. A name-presence count is not a coverage count.
import fs from 'node:fs';

const B = 'data/stance-research/2026-10-04-knight-mn-cities';
const N = 'Jordon Johnson';

const SWEEP = 'A sweep of the three Duluth outlets that pass a differential control - the Duluth News Tribune, WDIO and Duluth Monitor - together with MinnPost and Sahan Journal, over 23 queries covering both spellings of his first name, fetched 817 articles and kept 700. Minnesota Reformer was searched separately, with a control run at both ends, and added 122 more. That corpus is almost entirely other people: the keep-filter matches the surname alone, and only nine of the 700 name Jordon or Jordan Johnson, a signal ratio of 1%. Four of those nine also name Pete Johnson, the firefighter who beat him in the 2024 DFL primary for Minnesota House district 8A, so no bare-surname attribution was trusted in them. Because of that, the other seven Duluth corpora in this slice were read for him as well, which is where almost all of his coverage turned out to be: 26 articles across the slice name him. Ten of those 26 name him only in the council roster sidebar that the Duluth News Tribune appends to its local stories, which is not coverage of him, and two of the remaining 16 are about Pete Johnson. All 16 were read. Perfect Duluth Day, FOX 21, Business North, Northern News Now and Duluth Reader could not be searched by any method found, so no outlet count here covers them. MPR News and Racket are not covered either: MPR News renders its articles in the browser, so a passage there cannot be verified against the page, and Racket returns the same results for any query including a nonsense one. He took office on 5 January 2026, so C44 excludes everything the council did before that date. In the nine months since, the council has divided on two matters: a resolution confirming appointments to the Housing Trust Fund Committee, which is an appointment rather than a policy, and a motion he himself made to table a resolution, which is procedural. Neither can seat a chair. His statements as a candidate are used, under the ruling of 2026-10-05; he launched his council campaign in April 2025 and was elected in November 2025. His 2024 run for Minnesota House is also in the corpus and is weighed below where it bears on anything.';

const searched = {
  'local-immigration': 'This is the closest he comes to a chair and it does not arrive. At the council meeting that followed the Pretti shooting he said he was working on draft legislation about the city’s relationship with federal agencies over the enforcement of federal immigration laws, and that the city’s agencies are not there for the purpose of federal immigration laws. The reporter records in the same breath that he offered no specifics and expected a proposal within weeks. The statement puts him at the non-cooperation end and cannot choose between the two chairs there. Chair 3 declines to use local resources for proactive enforcement, which is close to what he said. Chair 1 goes further, refusing all detainers and prohibiting employees from sharing immigration status, and a person holding chair 1 would say exactly the same sentence about city agencies on the way to it. He names no detainer policy and no information-sharing rule, which is what separates them. Chairs 4 and 5 are excluded. What would settle this row is the ordinance itself once it is introduced and its text is readable.',
  'rent-regulation': 'He has an instrument here and it belongs to no rung. With Nephew he offered the resolution calling for $50 million in rent assistance for households hit by the federal immigration enforcement push, and the council passed it unanimously - so C46 refuses the vote, though the authorship is his. It was the stripped-down alternative to the Clanaugh and Durrwachter resolution that would have added an eviction moratorium, which failed 7-2 the same night; his measure deliberately carried no moratorium. That is a real choice between relief and a binding rule on landlords, and this ladder cannot record it: every rung here is about the price of rent, from communitywide rent control to market rents, and rent assistance is money paid to tenants. Duluth has no rent stabilisation ordinance for any rung to extend or narrow. The same reasoning keeps Cheniqua Johnson’s housing row blank in this batch.',
  'economic-development': 'Asked what he would prioritise, he said that the developers the city brings in around housing and economic opportunity should not just be given tax breaks but should actually be invested in the community and contributing to it in some regard, and separately that the city should look beyond a tourist tax or additional sales tax to local opportunities it has not fully explored. That is a direction - incentives ought to buy something real - and this ladder separates on mechanism. Chair 3 is incentives conditioned on good wages and local hiring with the money repayable if the firm does not deliver, and he names no wage condition, no hiring condition and no clawback. Chair 2 would refuse subsidy to large outside companies, and he does not say that either; he says he is interested in creative solutions and in attracting investment. Chairs 1, 4 and 5 are further away still. The remark is consistent with chair 2 and chair 3 at once and chooses neither.',
  'residential-zoning': 'He raises zoning twice and states no density. Asked what city government can do about housing he said some of it has to go to what the zoning and regulation laws are, and asked how the city might revisit those regulations without compromising existing safety mechanisms or progress towards clean energy, and he referred to what is called missing middle housing. Missing middle is the term for duplexes, triplexes and small multifamily between single-family houses and apartment blocks, which would be chair 2, but his own gloss describes it as options to do with green space and community spaces, which is not what the term means. A chair cannot be seated on a term the speaker appears to be using for something else. Everything else in the passage is interrogative - how are we looking at maybe revisiting - and a question about whether to revisit the rules is not a position on what the rules should say.',
  'transportation-priorities': 'Asked after the election what his early priority was, he answered that transportation is a safety issue and asked what the future of bike lanes, of walkability and of adequate lighting in the city should be. That names the modes this ladder is about and states no priority among them. He does not say whether investment should go to road capacity, to transit and cycling, or be split between them, and the framing is a question he intends to take up rather than an answer.',
  housing: 'Housing is the subject he returns to most and he never names an instrument. He said housing and economic development go together and the city is short on housing to attract people who might move here and build the tax base; that housing is multi-layered, and asked how the city provides options for elders, for people who are unhoused or moving into transitional housing, and for people becoming homeowners; and that the aim is affordable, accessible housing options created in a thoughtful way. He also listed fair housing and making sure there are affordable rental rates among his priorities, and said the city should be mindful of tenants and of landlords alike. The rungs separate on who makes housing affordable and how - government building and operating it, binding rules on the private market, or subsidy - and he commits to none of those and explicitly balances tenants against landlords. His 2024 campaign for Minnesota House, which is in the corpus and is admissible, adds that the future of housing matters and that rising property taxes must not push people out of their homes. That is the same shape: a concern, not a rung.',
  'growth-and-development': 'Asked how Duluth can attract new residents and businesses he said housing and economic development go together, that the city is short on housing, and that it should think about what it wants to attract and take a strategic, layered approach. That is an argument that housing must come before growth and that planning should be deliberate. It is the sequencing argument Nephew makes, and it falls short here for the same reason: chair 2 makes development wait for capacity and chair 3 invests ahead of demand, and saying the city must build housing so that growth becomes possible is consistent with both. He states no preferred pace.',
  'public-safety-approach': 'He names community safety as a priority and broadens what it covers rather than placing it on this ladder. He said transportation is a safety issue and asked about bike lanes, walkability and adequate lighting, and that young people should never have to feel concerned about going to school. He also said that when there are concerns the council should bring attention to them rather than hearing strategies after the fact, which is a complaint about timing. The rungs separate on the balance between police and other responders - whether to shift away from policing, to send unarmed responders instead, to add crisis teams alongside police, or to expand police presence - and no passage states a position on police staffing, police funding, co-responders or crisis teams. This is the same shape as Mayor Her’s record on this ladder in this batch, and it is blank for the same reason.',
  homelessness: 'No passage states a position on how the city should treat people sleeping or camping in public. The camping ordinance was adopted in July 2024, eighteen months before he took office, and C44 excludes it.',
  'homelessness-response': 'The $50 million rent assistance resolution he offered with Nephew is aimed at households affected by federal immigration enforcement, not at the city’s homelessness response, and it asks the state for money rather than setting a city funding level. No passage states what level of funding he thinks the city’s homelessness response should carry. The $500,000 increase for Stepping on Up was approved in July 2024 and is excluded by C44.',
  'local-environment': 'His only environmental reference is a qualifier inside a housing answer: that revisiting zoning and regulation should not compromise existing safety mechanisms or future traction towards clean energy. That is a constraint on how one rule change should be done, not a position on how far environmental protection should constrain development. No passage states a view on the balance this ladder asks about.',
  'climate-change': 'The phrase future traction towards clean energy appears once, as a thing not to compromise while revisiting housing regulation. It names no mandate, no subsidy or public investment, and nothing about permitting or the grid, which is what the five rungs separate on.',
  childcare: 'No passage states a position on childcare funding or provision.',
  'city-sanitation': 'No passage states a position on street cleanliness, litter enforcement, or who should be responsible for it.',
  'civil-rights': 'He is the associate director of the American Indian Community Housing Organization and has spoken about lifting up the voices of Indigenous and Black communities of colour, about his own experience of housing and economic insecurity as a child, and about recognising that policies affect everyone’s lives. That is an account of who he works with and what formed him. This ladder separates on how far government should go in addressing racial and social inequality, from mandated equity requirements through to ending race-based programmes, and no passage states a position on enforcement or on race-conscious programmes.',
  'data-centers': 'No passage names a data centre proposal in Duluth or states a position on one.',
  'minimum-wage': 'Duluth has no city minimum wage ordinance, so there is no local instrument, and Minn. Stat. 177.24 carries no local preemption clause, so the lever exists and this is not a scope blank. No passage states a position on the wage floor.',
  'ranked-choice-voting': 'Duluth’s only ranked choice matter is 15-0516R from 2015, a decade before he took office, and C44 excludes it. No passage states a position on the electoral method.',
  'religious-freedom': 'No passage states a position on any rung.',
  '2020-election': 'No passage states a view of the 2020 presidential election. The corpus carries several articles about Pete Johnson’s Minnesota House races, and each was checked against that before being set aside.',
};

const rows = [...JSON.parse(fs.readFileSync(B + '/_rows/johnson-blanks.json', 'utf8'))];
for (const [k, v] of Object.entries(searched)) {
  rows.push({ full_name: N, topic_key: k, value: '', evidence_type: '', reasoning: 'Searched blank. ' + SWEEP + ' ' + v, source_url_1: '', source_url_2: '', source_url_3: '', quote_text: '', quote_deidentified: '', editor_note: '' });
}

if (new Set(rows.map((r) => r.topic_key)).size !== rows.length) throw new Error('duplicate topic');
if (rows.length !== 35) throw new Error('expected 35 rows, got ' + rows.length);
// A documented zero is a finding, not an absence — assert it rather than let it happen quietly.
if (rows.some((r) => r.value)) throw new Error('this pass found no chair; a scored row here is a mistake');

fs.writeFileSync(B + '/_rows/johnson-rows.json', JSON.stringify(rows, null, 1));
console.log('rows:', rows.length, '| scored:', rows.filter((r) => r.value).length, '| documented zero');
